;;; Czech translations

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Čeština")
 (:lang-flag . "🇨🇿")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Vyberte svůj jazyk")
 (:lang-modal-subtitle . "Zvolte preferovaný jazyk rozhraní:")

 ;; Navigation
 (:nav-translate . "Přeložit")
 (:nav-review . "Opakování")
 (:nav-dashboard . "Přehled")
 (:nav-logout . "Odhlásit se")
 (:nav-home . "Domů")
 (:nav-pricing . "Ceník")
 (:nav-export-data . "Exportovat data")

 ;; App title and branding
 (:app-title . "Hiisi")
 (:app-tagline . "Učte se jazyky s překlady poháněnými AI")

 ;; Landing page
 (:landing-hero-title . "Ovládněte jakýkoliv jazyk")
 (:landing-hero-subtitle . "Překládejte cokoliv. Automaticky vytvářejte kartičky, které vás naučí, proč to tak funguje.")
 (:landing-cta . "Začít se učit")
 (:landing-learn-more . "Zjistit více")
 (:landing-how-it-works . "Jak to funguje")
 (:landing-feature-1-title . "Automatické kartičky")
 (:landing-feature-1-desc . "Každý překlad automaticky vytvoří kartičky s gramatickým rozborem. Žádné ruční vytváření.")
 (:landing-feature-2-title . "Rozložené opakování")
 (:landing-feature-2-desc . "Algoritmus SM-2 plánuje opakování v optimálních intervalech. Učte se efektivně, pamatujte si trvale.")
 (:landing-feature-3-title . "Výuka gramatiky")
 (:landing-feature-3-desc . "Každý překlad vysvětluje gramatiku, slovní kořeny a strukturu věty. Pochopte proč, nejen co.")
 (:landing-free-trial . "7denní zkušební verze zdarma. Kreditní karta není vyžadována.")
 (:landing-start-trial . "Vyzkoušet zdarma")
 (:landing-best-value . "Nejlepší hodnota")
 (:landing-cta-title . "Připraveni učit se jazyky skrze gramatiku, ne memorování?")
 (:landing-cta-subtitle . "Každý překlad se stává příležitostí k učení. Každá kartička vás naučí proč.")
 (:landing-signup-free . "Registrovat zdarma")

 ;; Auth pages
 (:auth-register . "Registrace")
 (:auth-login . "Přihlášení")
 (:auth-logout . "Odhlásit se")
 (:auth-email . "E-mail")
 (:auth-password . "Heslo")
 (:auth-password-again . "Potvrzení hesla")
 (:auth-display-name . "Zobrazované jméno")
 (:auth-register-title . "Registrace do Hiisi")
 (:auth-register-subtitle . "Vytvořte nový účet")
 (:auth-login-title . "Přihlášení do Hiisi")
 (:auth-login-subtitle . "Zadejte své přihlašovací údaje")
 (:auth-forgot-password . "Zapomenuté heslo?")
 (:auth-no-account . "Nemáte účet?")
 (:auth-have-account . "Již máte účet?")
 (:auth-google . "Google")
 (:auth-account-created . "Účet vytvořen!")
 (:auth-check-email . "Zkontrolujte svůj e-mail pro aktivační odkaz.")
 (:auth-redirect-login . "Přesměrování na přihlášení za")
 (:auth-seconds . "sekund...")
 (:auth-go-now . "Přejít nyní")
 (:auth-not-activated . "Účet není aktivován")
 (:auth-activate-title . "Aktivujte svůj účet!")
 (:auth-activated . "Účet aktivován!")
 (:auth-activated-message . "Váš účet byl aktivován. Nyní můžete používat Hiisi.")
 (:auth-redirecting . "Přesměrování za")
 (:auth-go-to-app . "Přejít do aplikace")
 (:auth-resend-title . "Znovu odeslat aktivační e-mail")
 (:auth-resend-subtitle . "Zadejte svůj e-mail pro získání nového aktivačního odkazu.")
 (:auth-resend-button . "Znovu odeslat aktivační e-mail")
 (:auth-resend-success . "Aktivační e-mail odeslán!")
 (:auth-resend-success-detail . "Zkontrolujte svou schránku pro nový aktivační odkaz.")
 (:auth-resend-rate-limited . "Prosím počkejte několik minut před dalším požadavkem o aktivační e-mail.")
 (:auth-resend-cooldown . "Další e-mail můžete vyžádat za ~a sekund.")
 (:auth-back-to-login . "Zpět na přihlášení")
 (:auth-forgot-password-title . "Zapomenuté heslo")
 (:auth-forgot-password-subtitle . "Zadejte svůj e-mail a pošleme vám odkaz pro obnovení hesla.")
 (:auth-send-reset-link . "Odeslat odkaz pro obnovení")
 (:auth-reset-email-sent . "Odkaz odeslán!")
 (:auth-reset-email-sent-detail . "Pokud účet s tímto e-mailem existuje, brzy obdržíte odkaz pro obnovení hesla.")
 (:auth-reset-rate-limited . "Prosím počkejte několik minut před dalším požadavkem o obnovení hesla.")
 (:auth-reset-invalid-token . "Tento odkaz pro obnovení hesla je neplatný nebo vypršel.")
 (:auth-reset-password-title . "Obnovení hesla")
 (:auth-reset-password-subtitle . "Zadejte své nové heslo níže.")
 (:auth-new-password . "Nové heslo")
 (:auth-confirm-new-password . "Potvrďte nové heslo")
 (:auth-reset-password . "Obnovit heslo")
 (:auth-password-changed . "Heslo změněno!")
 (:auth-password-changed-detail . "Vaše heslo bylo úspěšně změněno. Nyní se můžete přihlásit s novým heslem.")
 (:auth-change-password-title . "Změna hesla")
 (:auth-change-password-subtitle . "Aktualizujte heslo svého účtu.")
 (:auth-current-password . "Současné heslo")
 (:auth-change-password . "Změnit heslo")
 (:auth-back-to-app . "Zpět do aplikace")
 (:auth-password-updated . "Heslo aktualizováno!")
 (:auth-password-updated-detail . "Vaše heslo bylo úspěšně aktualizováno.")

 ;; Translation page
 (:translate-title . "Překlad")
 (:translate-input-label . "Zadejte text k překladu")
 (:translate-input-placeholder . "Napište něco...")
 (:translate-from . "Z")
 (:translate-to . "Do")
 (:translate-submit . "Přeložit")
 (:translate-save . "Uložit do kartíček")
 (:translate-saved . "Uloženo!")
 (:translate-like . "Líbí se mi")
 (:translate-dislike . "Nelíbí se mi")
 (:translate-char-limit . "zbývajících znaků")
 (:translate-auto-detect . "Jakýkoliv (Auto-detekce)")
 (:translate-empty-state . "Zadejte text výše a klikněte na Přeložit pro zobrazení výsledku s gramatickým rozborem")
 (:translate-like-tooltip . "Dobrý překlad")
 (:translate-dislike-tooltip . "Špatný překlad - vyžádat nový")
 (:translate-dislike-confirm . "Toto vygeneruje nový překlad. Pokračovat?")
 (:translate-liked . "Líbí se!")

 ;; Flashcard review
 (:review-title . "Opakování")
 (:review-session-title . "Opakovací relace")
 (:review-session-subtitle . "Procvičujte uložené kartičky")
 (:review-start . "Začít opakování")
 (:review-no-cards . "Žádné kartičky k opakování")
 (:review-no-cards-desc . "Momentálně nemáte žádné kartičky k opakování.")
 (:review-no-cards-hint . "Přeložte nějaký text a klikněte na \"Uložit do kartiček\" pro vytvoření balíčku!")
 (:review-start-translating . "Začít překládat")
 (:review-show-answer . "Ukázat odpověď")
 (:review-click-reveal . "Klikněte pro zobrazení odpovědi")
 (:review-grammar-breakdown . "Gramatický rozbor")
 (:review-how-well . "Jak dobře jste si zapamatovali?")
 (:review-again . "Znovu")
 (:review-hard . "Těžké")
 (:review-good . "Dobře")
 (:review-easy . "Snadné")
 (:review-progress . "Kartička ~a z ~a")
 (:review-complete . "Opakování dokončeno!")
 (:review-complete-msg . "Zopakovali jste ~a kartíček")
 (:review-correct . "Správně")
 (:review-accuracy . "Přesnost")
 (:review-again-btn . "Opakovat znovu")
 (:review-translate-more . "Překládat více")
 (:review-streak . "denní série")

 ;; Dashboard
 (:dashboard-title . "Přehled")
 (:dashboard-cards-due . "Kartičky na dnes")
 (:dashboard-total-cards . "Celkem kartíček")
 (:dashboard-subscription . "Předplatné")
 (:dashboard-subscribed-until . "Předplaceno do")
 (:dashboard-not-subscribed . "Bez předplatného")
 (:dashboard-recent . "Nedávné překlady")
 (:dashboard-no-translations . "Zatím žádné překlady")
 (:dashboard-streak . "Aktuální série")
 (:dashboard-days . "dní")
 (:dashboard-quick-actions . "Rychlé akce")
 (:dashboard-getting-started . "Začínáme")
 (:dashboard-tip-1 . "Přeložte text, který se chcete naučit")
 (:dashboard-tip-2 . "Klikněte na \"Uložit do kartiček\" u překladů, které si chcete zapamatovat")
 (:dashboard-tip-3 . "Pravidelně opakujte kartičky - rozložené opakování pomáhá dlouhodobému zapamatování")
 (:dashboard-tip-4 . "Hodnoťte upřímně - pomáhá to algoritmu optimálně plánovat opakování")

 ;; Subscription
 (:subscribe-title . "Vyberte si plán")
 (:subscribe-choose-plan . "Vyberte si plán")
 (:subscribe-start-today . "Začněte se učit již dnes se 7denní zkušební verzí zdarma")
 (:subscribe-monthly . "Měsíčně")
 (:subscribe-annual . "Ročně")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/měsíc")
 (:subscribe-per-year . "/rok")
 (:subscribe-monthly-desc . "600 překladů měsíčně")
 (:subscribe-unlimited-flashcards . "Neomezené kartičky")
 (:subscribe-grammar-explanations . "Gramatická vysvětlení")
 (:subscribe-spaced-repetition . "Rozložené opakování")
 (:subscribe-annual-desc . "Ušetřete 20 € - dva měsíce zdarma!")
 (:subscribe-cta . "Předplatit")
 (:subscribe-success . "Předplatné úspěšné!")
 (:subscribe-manage . "Správa předplatného")
 (:subscribe-activated . "Předplatné aktivováno!")
 (:subscribe-thank-you . "Děkujeme za předplacení. Váš účet je nyní aktivní.")
 (:subscribe-start-learning . "Začít se učit")
 (:subscribe-management . "Správa předplatného")
 (:subscribe-active . "Aktivní předplatné")
 (:subscribe-status . "Stav:")
 (:subscribe-status-active . "Aktivní")
 (:subscribe-days-remaining . "Zbývající dny:")
 (:subscribe-renews-on . "Obnovení:")
 (:subscribe-no-subscription . "Žádné aktivní předplatné")
 (:subscribe-access-features . "Předplaťte si přístup ke všem funkcím.")
 (:subscribe-view-plans . "Zobrazit plány")
 (:subscribe-faq-title . "Často kladené otázky")
 (:subscribe-faq-trial-q . "Co se stane po zkušební verzi zdarma?")
 (:subscribe-faq-trial-a . "Po 7denní zkušební verzi zdarma vám bude účtován vybraný plán. Můžete kdykoliv zrušit před koncem zkušební doby.")
 (:subscribe-faq-cancel-q . "Mohu kdykoliv zrušit?")
 (:subscribe-faq-cancel-a . "Ano! Předplatné můžete zrušit kdykoliv. Přístup si zachováte do konce fakturačního období.")
 (:subscribe-faq-payment-q . "Jaké platební metody přijímáte?")
 (:subscribe-faq-payment-a . "Přijímáme všechny hlavní kreditní a debetní karty prostřednictvím našeho platebního partnera Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Něco se pokazilo")
 (:error-not-found . "Stránka nenalezena")
 (:error-unauthorized . "Pro pokračování se přihlaste")
 (:error-subscription-required . "Vyžadováno předplatné")
 (:error-text-too-long . "Text je příliš dlouhý. Maximální délka překladu je 120 znaků.")
 (:error-input-too-long . "Vstup je příliš dlouhý")
 (:error-unknown-source-lang . "Vybraný zdrojový jazyk není podporován.")
 (:error-unknown-target-lang . "Vybraný cílový jazyk není podporován.")
 (:error-unknown-language . "Neznámý jazyk")
 (:error-translation-unavailable . "Překladová služba je dočasně nedostupná. Zkuste to prosím za chvíli.")
 (:error-translation-failed . "Překlad selhal")
 (:error-translation-retry . "Nepodařilo se vygenerovat překlad po několika pokusech. Zkuste přeformulovat text.")
 (:error-quota-exceeded . "Dosažen limit překladů")
 (:error-quota-exceeded-detail . "Vyčerpali jste všechny překlady na tento měsíc. Kvóta se automaticky obnoví každý měsíc.")
 (:loading . "Načítání...")
 (:empty-state . "Zatím zde nic není")

 ;; Footer
 (:footer-privacy . "Zásady ochrany osobních údajů")
 (:footer-terms . "Podmínky služby")
 (:footer-contact . "Kontakt")

 ;; Early software notice
 (:early-software-notice . "Hiisi je v rané fázi vývoje. Našli jste chybu nebo máte návrh?")
 (:early-software-contact . "Kontaktujte nás na")

 ;; Privacy Policy
 (:privacy-title . "Privacy Policy")
 (:privacy-updated . "Last updated: January 2026")
 (:privacy-who-title . "Who We Are")
 (:privacy-who-body . "Hiisi is operated by Lambda Symbolics OÜ, a company registered in Estonia. As an Estonian company, we comply with the European Union's General Data Protection Regulation (GDPR).")
 (:privacy-collect-title . "Data We Collect")
 (:privacy-collect-intro . "We collect the following information when you use Hiisi:")
 (:privacy-collect-account-key . "Account information: ")
 (:privacy-collect-account-val . "Email address, display name, and a securely hashed password.")
 (:privacy-collect-learning-key . "Learning data: ")
 (:privacy-collect-learning-val . "Your translations, saved flashcards, and review history.")
 (:privacy-collect-usage-key . "Usage data: ")
 (:privacy-collect-usage-val . "Basic server logs for security and debugging purposes.")
 (:privacy-use-title . "How We Use Your Data")
 (:privacy-use-auth-key . "Authentication: ")
 (:privacy-use-auth-val . "To verify your identity and secure your account.")
 (:privacy-use-service-key . "Service delivery: ")
 (:privacy-use-service-val . "To provide translations and manage your flashcard collection.")
 (:privacy-use-ai-key . "AI translations: ")
 (:privacy-use-ai-val . "Your translation requests are sent to Anthropic's Claude API to generate responses. See Anthropic's privacy policy for how they handle this data.")
 (:privacy-third-title . "Third-Party Services")
 (:privacy-third-intro . "We use the following third-party services:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "For AI-powered translations.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "For sending account activation and transactional emails.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "For subscription payment processing.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "We use only essential cookies:")
 (:privacy-cookies-auth-key . "Authentication token: ")
 (:privacy-cookies-auth-val . "A secure, HTTP-only cookie to keep you logged in.")
 (:privacy-cookies-lang-key . "Language preference: ")
 (:privacy-cookies-lang-val . "To remember your preferred UI language.")
 (:privacy-retention-title . "Data Retention")
 (:privacy-retention-body . "Your data is stored as long as you maintain an account. When you request deletion, your account is scheduled for deletion in 14 days.")
 (:privacy-rights-title . "Your Rights (GDPR)")
 (:privacy-rights-intro . "Under GDPR, you have the right to:")
 (:privacy-rights-access . "Access your personal data")
 (:privacy-rights-export . "Export your data (available at /app/api/export)")
 (:privacy-rights-correct . "Request correction of inaccurate data")
 (:privacy-rights-delete . "Request deletion of your account and data")
 (:privacy-rights-object . "Object to processing of your data")
 (:privacy-rights-contact . "To exercise these rights, contact us at")
 (:privacy-contact-title . "Contact")
 (:privacy-contact-intro . "For privacy-related inquiries:")
 (:privacy-contact-email-label . "Email: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Estonia")

 ;; Terms of Service
 (:terms-title . "Terms of Service")
 (:terms-updated . "Last updated: January 2026")
 (:terms-1-title . "1. Service Description")
 (:terms-1-body . "Hiisi is a language learning application that provides AI-powered translations with grammatical explanations and spaced repetition flashcards. The service is operated by Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Account Registration")
 (:terms-2-body . "To use Hiisi, you must create an account with a valid email address. You are responsible for maintaining the security of your account credentials.")
 (:terms-3-title . "3. Subscription and Payments")
 (:terms-3-body . "Hiisi offers paid subscription plans (monthly and annual). Subscriptions are processed through Polar.sh.")
 (:terms-3-list-1 . "Subscriptions auto-renew unless cancelled before the renewal date.")
 (:terms-3-list-2 . "Refunds are provided in accordance with applicable consumer protection laws.")
 (:terms-3-list-3 . "Non-payment results in loss of access to premium features.")
 (:terms-4-title . "4. Acceptable Use")
 (:terms-4-intro . "You agree not to:")
 (:terms-4-list-1 . "Use the service for any illegal purpose")
 (:terms-4-list-2 . "Attempt to circumvent usage limits or security measures")
 (:terms-4-list-3 . "Share your account credentials with others")
 (:terms-4-list-4 . "Use automated tools to access the service in a way that degrades performance for others")
 (:terms-5-title . "5. Content and Intellectual Property")
 (:terms-5-body-1 . "Translations generated by Hiisi are created using AI and may not be unique. You may use your translations and flashcards for any personal purpose, but you do not hold exclusive authorship rights over AI-generated content.")
 (:terms-5-body-2 . "The Hiisi application, branding, and original content remain the property of Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Service Availability")
 (:terms-6-intro . "Hiisi is provided on an \"as-is\" basis. We do not guarantee:")
 (:terms-6-list-1 . "Uninterrupted or error-free service")
 (:terms-6-list-2 . "Accuracy of AI-generated translations")
 (:terms-6-list-3 . "Availability of specific features")
 (:terms-6-body . "We may modify or discontinue features at any time.")
 (:terms-7-title . "7. Limitation of Liability")
 (:terms-7-body-1 . "To the maximum extent permitted by law, Lambda Symbolics OÜ shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of Hiisi.")
 (:terms-7-body-2 . "Our total liability shall not exceed the amount you paid for the service in the 12 months preceding the claim.")
 (:terms-8-title . "8. Account Termination")
 (:terms-8-body-1 . "We may suspend or terminate your account if you violate these terms. You may request account deletion at any time through the application.")
 (:terms-8-body-2 . "Upon deletion request, your account is scheduled for deletion in 14 days.")
 (:terms-9-title . "9. Changes to Terms")
 (:terms-9-body . "We may update these terms from time to time. Continued use of Hiisi after changes constitutes acceptance of the new terms.")
 (:terms-10-title . "10. Governing Law")
 (:terms-10-body . "These terms are governed by the laws of Estonia. Any disputes shall be resolved in the courts of Estonia.")
 (:terms-contact-title . "Contact")
 (:terms-contact-intro . "For questions about these terms:")
 (:terms-contact-email-label . "Email: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Estonia")



 ;; Decks
 (:decks-title . "Decks")
 (:decks-subtitle . "Create custom decks and share them with others.")
 (:decks-create-title . "Create Deck")
 (:decks-name-placeholder . "Deck name")
 (:decks-desc-placeholder . "Description")
 (:decks-create-btn . "Create deck")
 (:decks-your-title . "Your Decks")
 (:decks-col-name . "Name")
 (:decks-col-desc . "Description")
 (:decks-col-updated . "Updated")
 (:decks-col-actions . "Actions")
 (:decks-no-decks . "No decks yet.")
 (:decks-open-btn . "Open")
 (:decks-no-desc . "No description.")
 (:decks-share-title . "Share Link")
 (:decks-share-info . "Anyone with this link can import the deck:")
 (:decks-add-trans-title . "Add Translation")
 (:decks-trans-id-placeholder . "Translation ID")
 (:decks-add-trans-btn . "Add translation")
 (:decks-items-title . "Deck Items")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Translated")
 (:decks-col-lang . "Lang To")
 (:decks-no-items . "No items yet.")
 (:decks-share-page-title . "Share Deck")
 (:decks-share-preview . "Preview and import this deck.")
 (:decks-import-title . "Import")
 (:decks-import-btn . "Import deck")

)
