;;; Czech translations

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Čeština")
 (:lang-flag . "🇨🇿")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Vyberte svůj jazyk")
 (:lang-modal-subtitle . "Zvolte preferovaný jazyk rozhraní:")

 ;; Navigation
 (:nav-translate . "Přeložit")
 (:nav-review . "Opakování")
 (:nav-flashcards . "Moje kartičky")
 (:nav-dashboard . "Přehled")
 (:nav-decks . "Balíčky")
 (:nav-logout . "Odhlásit se")
 (:nav-home . "Domů")
 (:nav-pricing . "Ceník")
 (:nav-export-data . "Exportovat data")

 ;; App title and branding
 (:app-title . "Hiisi - Studium jazyků")
 (:app-tagline . "Učte se jazyky s překlady poháněnými AI")

 ;; Landing page
 (:landing-hero-title . "Ovládněte jakýkoliv jazyk")
 (:landing-hero-subtitle . "Překládejte cokoliv. Automaticky vytvářejte kartičky, které vás naučí, proč to tak funguje.")
 (:landing-cta . "Začít se učit")
 (:landing-learn-more . "Zjistit více")
 (:landing-how-it-works . "Jak to funguje")
 (:landing-feature-1-title . "Automatické kartičky")
 (:landing-feature-1-desc . "Každý překlad automaticky vytvoří kartičky s gramatickým rozborem. Žádné ruční vytváření.")
 (:landing-feature-2-title . "Rozložené opakování")
 (:landing-feature-2-desc . "Algoritmus SM-2 plánuje opakování v optimálních intervalech. Učte se efektivně, pamatujte si trvale.")
 (:landing-feature-3-title . "Výuka gramatiky")
 (:landing-feature-3-desc . "Každý překlad vysvětluje gramatiku, slovní kořeny a strukturu věty. Pochopte proč, nejen co.")
 (:landing-free-trial . "7denní zkušební verze zdarma.")
 (:landing-start-trial . "Vyzkoušet zdarma")
 (:landing-best-value . "Nejlepší hodnota")
 (:landing-cta-title . "Připraveni učit se jazyky skrze gramatiku, ne memorování?")
 (:landing-cta-subtitle . "Každý překlad se stává příležitostí k učení. Každá kartička vás naučí proč.")
 (:landing-signup-free . "Registrovat zdarma")

 ;; Auth pages
 (:auth-register . "Registrace")
 (:auth-login . "Přihlášení")
 (:auth-logout . "Odhlásit se")
 (:auth-email . "E-mail")
 (:auth-password . "Heslo")
 (:auth-password-again . "Potvrzení hesla")
 (:auth-display-name . "Zobrazované jméno")
 (:auth-register-title . "Registrace do Hiisi")
 (:auth-register-subtitle . "Vytvořte nový účet")
 (:auth-login-title . "Přihlášení do Hiisi")
 (:auth-login-subtitle . "Zadejte své přihlašovací údaje")
 (:auth-login-invalid-credentials . "Neplatny e-mail nebo heslo.")
 (:auth-login-rate-limited . "Prilis mnoho pokusu o prihlaseni. Pockejte prosim nekolik minut a zkuste to znovu.")
 (:auth-forgot-password . "Zapomenuté heslo?")
 (:auth-no-account . "Nemáte účet?")
 (:auth-have-account . "Již máte účet?")
 (:auth-google . "Google")
 (:auth-account-created . "Účet vytvořen!")
 (:auth-check-email . "Zkontrolujte svůj e-mail pro aktivační odkaz.")
 (:auth-redirect-login . "Přesměrování na přihlášení za")
 (:auth-seconds . "sekund...")
 (:auth-go-now . "Přejít nyní")
 (:auth-not-activated . "Účet není aktivován")
 (:auth-activate-title . "Aktivujte svůj účet!")
 (:auth-activated . "Účet aktivován!")
 (:auth-activated-message . "Váš účet byl aktivován. Nyní můžete používat Hiisi.")
 (:auth-redirecting . "Přesměrování za")
 (:auth-go-to-app . "Přejít do aplikace")
 (:auth-resend-title . "Znovu odeslat aktivační e-mail")
 (:auth-resend-subtitle . "Zadejte svůj e-mail pro získání nového aktivačního odkazu.")
 (:auth-resend-button . "Znovu odeslat aktivační e-mail")
 (:auth-resend-success . "Aktivační e-mail odeslán!")
 (:auth-resend-success-detail . "Zkontrolujte svou schránku pro nový aktivační odkaz.")
 (:auth-resend-rate-limited . "Prosím počkejte několik minut před dalším požadavkem o aktivační e-mail.")
 (:auth-resend-cooldown . "Další e-mail můžete vyžádat za ~a sekund.")
 (:auth-back-to-login . "Zpět na přihlášení")
 (:auth-forgot-password-title . "Zapomenuté heslo")
 (:auth-forgot-password-subtitle . "Zadejte svůj e-mail a pošleme vám odkaz pro obnovení hesla.")
 (:auth-send-reset-link . "Odeslat odkaz pro obnovení")
 (:auth-reset-email-sent . "Odkaz odeslán!")
 (:auth-reset-email-sent-detail . "Pokud účet s tímto e-mailem existuje, brzy obdržíte odkaz pro obnovení hesla.")
 (:auth-reset-rate-limited . "Prosím počkejte několik minut před dalším požadavkem o obnovení hesla.")
 (:auth-reset-invalid-token . "Tento odkaz pro obnovení hesla je neplatný nebo vypršel.")
 (:auth-reset-password-title . "Obnovení hesla")
 (:auth-reset-password-subtitle . "Zadejte své nové heslo níže.")
 (:auth-new-password . "Nové heslo")
 (:auth-confirm-new-password . "Potvrďte nové heslo")
 (:auth-reset-password . "Obnovit heslo")
 (:auth-password-changed . "Heslo změněno!")
 (:auth-password-changed-detail . "Vaše heslo bylo úspěšně změněno. Nyní se můžete přihlásit s novým heslem.")
 (:auth-change-password-title . "Změna hesla")
 (:auth-change-password-subtitle . "Aktualizujte heslo svého účtu.")
 (:auth-current-password . "Současné heslo")
 (:auth-change-password . "Změnit heslo")
 (:auth-back-to-app . "Zpět do aplikace")
 (:auth-password-updated . "Heslo aktualizováno!")
 (:auth-password-updated-detail . "Vaše heslo bylo úspěšně aktualizováno.")

 ;; Translation page
 (:translate-title . "Překlad")
 (:translate-input-label . "Zadejte text k překladu")
 (:translate-input-placeholder . "Napište něco...")
 (:translate-from . "Z")
 (:translate-to . "Do")
 (:translate-submit . "Přeložit")
 (:translate-save . "Uložit do kartíček")
 (:translate-saved . "Uloženo!")
 (:translate-like . "Líbí se mi")
 (:translate-dislike . "Nelíbí se mi")
 (:translate-char-limit . "zbývajících znaků")
 (:translate-auto-detect . "Jakýkoliv (Auto-detekce)")
 (:translate-empty-state . "Zadejte text výše a klikněte na Přeložit pro zobrazení výsledku s gramatickým rozborem")
 (:translate-select-deck-placeholder . "Vyberte balíček (volitelné)")
 (:translate-new-deck . "Nový balíček")
 (:translate-add-to-deck . "Přidat do balíčku")
 (:translate-bookmark . "Uložit")
 (:translate-bookmarked . "Uloženo")
 (:translate-retry . "Zkusit znovu")
 (:translate-like-tooltip . "Dobrý překlad")
 (:translate-dislike-tooltip . "Špatný překlad - vyžádat nový")
 (:translate-dislike-confirm . "Toto vygeneruje nový překlad. Pokračovat?")
 (:translate-liked . "Líbí se!")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Cíl")
 (:translate-deck-create-title . "Vytvořit nový balíček")
 (:translate-deck-name-label . "Název balíčku")
 (:translate-deck-name-placeholder . "např. Základy finštiny")
 (:translate-deck-description-label . "Popis (volitelné)")
 (:translate-deck-cancel . "Zrušit")
 (:translate-deck-create . "Vytvořit")
 (:translate-rate-label . "Ohodnotit překlad")
 (:flashcards-delete-confirm . "Opravdu chcete smazat tuto kartičku?")
 (:flashcards-deck-search-placeholder . "Hledat balíčky...")
 (:flashcards-no-decks . "Zatím žádné balíčky. Nejdřív nějaký vytvořte.")
 (:flashcards-deck-cancel . "Zrušit")
 (:flashcards-recollection-tooltip . "Zapamatování: ~A")
 (:flashcards-recollection-poor . "Slabé")
 (:flashcards-recollection-fair . "Ucházející")
 (:flashcards-recollection-normal . "Normální")
 (:flashcards-recollection-strong . "Silné")
 (:flashcards-recollection-very-strong . "Velmi silné")

 ;; Flashcard review
 (:review-title . "Opakování")
 (:review-session-title . "Opakovací relace")
 (:review-session-subtitle . "Procvičujte uložené kartičky")
 (:review-selector-title . "Vyberte, co chcete opakovat")
 (:review-selector-subtitle . "Vyberte balíček nebo jazykový pár, na který se chcete v této relaci zaměřit.")
 (:review-by-deck . "Opakovat podle balíčku")
 (:review-by-language-pair . "Opakovat podle jazykového páru")
 (:review-all-cards . "Opakovat všechny kartičky")

 (:review-start . "Začít opakování")
 (:review-no-cards . "Žádné kartičky k opakování")
 (:review-no-cards-desc . "Momentálně nemáte žádné kartičky k opakování.")
 (:review-no-cards-hint . "Přeložte nějaký text a klikněte na \"Uložit do kartiček\" pro vytvoření balíčku!")
 (:review-start-translating . "Začít překládat")
 (:review-show-answer . "Ukázat odpověď")
 (:review-click-reveal . "Klikněte pro zobrazení odpovědi")
 (:review-grammar-breakdown . "Gramatický rozbor")
 (:review-how-well . "Jak dobře jste si zapamatovali?")
 (:review-again . "Znovu")
 (:review-hard . "Těžké")
 (:review-good . "Dobře")
 (:review-easy . "Snadné")
 (:review-progress . "Kartička ~a z ~a")
 (:review-complete . "Opakování dokončeno!")
 (:review-complete-msg . "Zopakovali jste ~a kartíček")
 (:review-correct . "Správně")
 (:review-accuracy . "Přesnost")
 (:review-again-btn . "Opakovat znovu")
 (:review-translate-more . "Překládat více")
 (:review-streak . "denní série")

 ;; Dashboard
 (:dashboard-title . "Přehled")
 (:dashboard-cards-due . "Kartičky na dnes")
 (:dashboard-total-cards . "Celkem kartíček")
 (:dashboard-subscription . "Předplatné")
 (:dashboard-subscribed-until . "Předplaceno do")
 (:dashboard-not-subscribed . "Bez předplatného")
 (:dashboard-recent . "Nedávné překlady")
 (:dashboard-no-translations . "Zatím žádné překlady")
 (:dashboard-streak . "Aktuální série")
 (:dashboard-days . "dní")
 (:dashboard-quick-actions . "Rychlé akce")
 (:dashboard-getting-started . "Začínáme")
 (:dashboard-tip-1 . "Přeložte text, který se chcete naučit")
 (:dashboard-tip-2 . "Klikněte na \"Uložit do kartiček\" u překladů, které si chcete zapamatovat")
 (:dashboard-tip-3 . "Pravidelně opakujte kartičky - rozložené opakování pomáhá dlouhodobému zapamatování")
 (:dashboard-tip-4 . "Hodnoťte upřímně - pomáhá to algoritmu optimálně plánovat opakování")

 ;; Account
 (:account-title . "Účet")
 (:account-subtitle . "Spravujte nastavení účtu a plán odstranění.")
 (:account-deletion-title . "Odstranění účtu")
 (:account-deletion-scheduled . "Váš účet je naplánován k odstranění na ~A.")
 (:account-deletion-cancel-hint . "Zrušením před tímto datem si účet ponecháte.")
 (:account-deletion-cancel . "Zrušit odstranění")
 (:account-deletion-request . "O odstranění účtu můžete požádat kdykoli. Odstranění je naplánováno na 14 dní od potvrzení. Pokud si to po odstranění rozmyslíte, kontaktujte podporu.")
 (:account-deletion-confirm . "Naplánovat odstranění účtu za 14 dní od dneška?")
 (:account-deletion-schedule . "Naplánovat odstranění")
 (:account-reminders-title . "E-mailová připomenutí")
 (:account-reminders-subtitle . "Nastavte si připomenutí ke studiu a pokračování.")
 (:account-reminders-opt-out . "Nezasílat připomenutí ke studiu a pokračování")
 (:account-reminders-save . "Uložit nastavení")

 ;; Subscription
 (:subscribe-title . "Vyberte si plán")
 (:subscribe-choose-plan . "Vyberte si plán")
 (:subscribe-start-today . "Začněte se učit již dnes se 7denní zkušební verzí zdarma")
 (:subscribe-monthly . "Měsíčně")
 (:subscribe-annual . "Ročně")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/měsíc")
 (:subscribe-per-year . "/rok")
 (:subscribe-monthly-desc . "600 překladů měsíčně")
 (:subscribe-unlimited-flashcards . "Neomezené kartičky")
 (:subscribe-grammar-explanations . "Gramatická vysvětlení")
 (:subscribe-spaced-repetition . "Rozložené opakování")
 (:subscribe-annual-desc . "Ušetřete 20 € - dva měsíce zdarma!")
 (:subscribe-cta . "Předplatit")
 (:subscribe-success . "Předplatné úspěšné!")
 (:subscribe-manage . "Správa předplatného")
 (:subscribe-activated . "Předplatné aktivováno!")
 (:subscribe-thank-you . "Děkujeme za předplacení. Váš účet je nyní aktivní.")
 (:subscribe-start-learning . "Začít se učit")
 (:subscribe-management . "Správa předplatného")
 (:subscribe-active . "Aktivní předplatné")
 (:subscribe-status . "Stav:")
 (:subscribe-status-active . "Aktivní")
 (:subscribe-days-remaining . "Zbývající dny:")
 (:subscribe-renews-on . "Obnovení:")
 (:subscribe-no-subscription . "Žádné aktivní předplatné")
 (:subscribe-access-features . "Předplaťte si přístup ke všem funkcím.")
 (:subscribe-view-plans . "Zobrazit plány")
 (:subscribe-faq-title . "Často kladené otázky")
 (:subscribe-faq-trial-q . "Co se stane po zkušební verzi zdarma?")
 (:subscribe-faq-trial-a . "Po 7denní zkušební verzi zdarma vám bude účtován vybraný plán. Můžete kdykoliv zrušit před koncem zkušební doby.")
 (:subscribe-faq-cancel-q . "Mohu kdykoliv zrušit?")
 (:subscribe-faq-cancel-a . "Ano! Předplatné můžete zrušit kdykoliv. Přístup si zachováte do konce fakturačního období.")
 (:subscribe-faq-payment-q . "Jaké platební metody přijímáte?")
 (:subscribe-faq-payment-a . "Přijímáme všechny hlavní kreditní a debetní karty prostřednictvím našeho platebního partnera Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Něco se pokazilo")
 (:error-not-found . "Stránka nenalezena")
 (:error-unauthorized . "Pro pokračování se přihlaste")
 (:error-subscription-required . "Vyžadováno předplatné")
 (:error-text-too-long . "Text je příliš dlouhý. Maximální délka překladu je 120 znaků.")
 (:error-input-too-long . "Vstup je příliš dlouhý")
 (:error-unknown-source-lang . "Vybraný zdrojový jazyk není podporován.")
 (:error-unknown-target-lang . "Vybraný cílový jazyk není podporován.")
 (:error-unknown-language . "Neznámý jazyk")
 (:error-translation-unavailable . "Překladová služba je dočasně nedostupná. Zkuste to prosím za chvíli.")
 (:error-translation-failed . "Překlad selhal")
 (:error-translation-retry . "Nepodařilo se vygenerovat překlad po několika pokusech. Zkuste přeformulovat text.")
 (:error-quota-exceeded . "Dosažen limit překladů")
 (:error-quota-exceeded-detail . "Vyčerpali jste všechny překlady na tento měsíc. Kvóta se automaticky obnoví každý měsíc.")
 (:quota-warning . "Zbývající překlady: ~A")
 (:quota-low-warning . "Zbývá pouze ~A překladů. Zvažte nákup dalších.")
 (:top-up-button . "Koupit další překlady")
 (:top-up-success . "Dobití úspěšné! Nyní máte ~A dalších překladů.")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 překladů")
 (:loading . "Načítání...")
 (:empty-state . "Zatím zde nic není")

 ;; Institutions
 (:institutions-page-title . "Hiisi pro školy - institucionální licence")
 (:institutions-hero-title . "Hiisi pro školy")
 (:institutions-hero-subtitle . "Umožněte svým studentům jazykové učení s podporou AI")
 (:institutions-section-title . "Institucionální licence")
 (:institutions-section-body . "Nabízíme hromadné licence pro školy, univerzity a jazykové instituce. Studenti s e-mailovými adresami z vaší domény automaticky získají plný přístup.")
 (:institutions-benefit-1 . "Automatické přihlášení studentů s institucionálním e-mailem")
 (:institutions-benefit-2 . "Žádné účty jednotlivých studentů k správě")
 (:institutions-benefit-3 . "Flexibilní fakturační možnosti")
 (:institutions-benefit-4 . "Dedikovaná podpora pro pedagogy")
 (:institutions-request-title . "Požádat o licenci")
 (:institutions-request-subtitle . "Vyplňte formulář níže a ozveme se vám do 2 pracovních dnů.")
 (:institutions-field-name . "Název instituce")
 (:institutions-field-name-placeholder . "Univerzita v Helsinkách")
 (:institutions-field-contact-name . "Jméno kontaktní osoby")
 (:institutions-field-contact-name-placeholder . "Vaše jméno")
 (:institutions-field-contact-email . "Kontaktní e-mail")
 (:institutions-field-contact-email-placeholder . "vy@univerzita.cz")
 (:institutions-field-domains . "E-mailové domény")
 (:institutions-field-domains-placeholder . "univerzita.cz, fit.univerzita.cz")
 (:institutions-field-domains-help . "Seznam e-mailových domén vaší instituce oddělených čárkou")
 (:institutions-field-notes . "Další informace")
 (:institutions-field-notes-placeholder . "Odhadovaný počet studentů, preferovaný fakturační cyklus, speciální požadavky...")
 (:institutions-submit . "Odeslat poptávku")
 (:institutions-success-title . "Děkujeme - Hiisi pro školy")
 (:institutions-success-heading . "Děkujeme!")
 (:institutions-success-body . "Obdrželi jsme vaši žádost o institucionální licenci. Náš tým žádost posoudí a ozve se vám do 2 pracovních dnů.")
 (:institutions-success-back . "Zpět na úvod")

 ;; Footer
 (:footer-privacy . "Zásady ochrany osobních údajů")
 (:footer-terms . "Podmínky služby")
 (:footer-contact . "Kontakt")

 ;; Early software notice
 (:early-software-notice . "Hiisi je v rané fázi vývoje. Našli jste chybu nebo máte návrh?")
 (:early-software-contact . "Kontaktujte nás na")

 ;; Privacy Policy
 (:privacy-title . "Zásady ochrany osobních údajů")
 (:privacy-updated . "Poslední aktualizace: leden 2026")
 (:privacy-who-title . "Kdo jsme")
 (:privacy-who-body . "Hiisi provozuje Lambda Symbolics OÜ, společnost registrovaná v Estonsku. Jako estonská společnost dodržujeme Obecné nařízení o ochraně osobních údajů (GDPR) Evropské unie.")
 (:privacy-collect-title . "Jaké údaje shromažďujeme")
 (:privacy-collect-intro . "Při používání Hiisi shromažďujeme následující informace:")
 (:privacy-collect-account-key . "Účetní informace: ")
 (:privacy-collect-account-val . "E-mailová adresa, zobrazované jméno a bezpečně hashované heslo.")
 (:privacy-collect-learning-key . "Vzdělávací data: ")
 (:privacy-collect-learning-val . "Vaše překlady, uložené kartičky a historie opakování.")
 (:privacy-collect-usage-key . "Údaje o používání: ")
 (:privacy-collect-usage-val . "Základní serverové protokoly pro bezpečnost a účely ladění.")
 (:privacy-use-title . "Jak používáme vaše údaje")
 (:privacy-use-auth-key . "Ověřování: ")
 (:privacy-use-auth-val . "K ověření vaší identity a zabezpečení vašeho účtu.")
 (:privacy-use-service-key . "Poskytování služeb: ")
 (:privacy-use-service-val . "K poskytování překladů a správě vaší sbírky kartiček.")
 (:privacy-use-ai-key . "AI překlady: ")
 (:privacy-use-ai-val . "Vaše požadavky na překlad jsou odesílány do API Claude společnosti Anthropic pro generování odpovědí. Podívejte se na zásady ochrany osobních údajů Anthropic, jak s těmito údaji nakládají.")
 (:privacy-third-title . "Služby třetích stran")
 (:privacy-third-intro . "Používáme následující služby třetích stran:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "Pro překlady poháněné umělou inteligencí.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "Pro odesílání aktivačních e-mailů a transakčních zpráv.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Pro zpracování plateb za předplatné.")
 (:privacy-cookies-title . "Soubory cookie")
 (:privacy-cookies-intro . "Používáme pouze nezbytné soubory cookie:")
 (:privacy-cookies-auth-key . "Ověřovací token: ")
 (:privacy-cookies-auth-val . "Bezpečný soubor cookie s atributem HTTP-only, který udržuje vaše přihlášení.")
 (:privacy-cookies-lang-key . "Preference jazyka: ")
 (:privacy-cookies-lang-val . "K zapamatování vašeho preferovaného jazyka rozhraní.")
 (:privacy-retention-title . "Uchovávání údajů")
 (:privacy-retention-body . "Vaše údaje jsou uchovávány po celou dobu existence vašeho účtu. Při žádosti o smazání je váš účet naplánován na smazání do 14 dnů.")
 (:privacy-rights-title . "Vaše práva (GDPR)")
 (:privacy-rights-intro . "Podle GDPR máte právo:")
 (:privacy-rights-access . "Přístup k vašim osobním údajům")
 (:privacy-rights-export . "Exportovat vaše údaje (dostupné na /app/api/export)")
 (:privacy-rights-correct . "Požádat o opravu nepřesných údajů")
 (:privacy-rights-delete . "Požádat o smazání vašeho účtu a údajů")
 (:privacy-rights-object . "Vznést námitku proti zpracování vašich údajů")
 (:privacy-rights-contact . "Pro uplatnění těchto práv nás kontaktujte na")
 (:privacy-contact-title . "Kontakt")
 (:privacy-contact-intro . "Pro dotazy týkající se ochrany osobních údajů:")
 (:privacy-contact-email-label . "E-mail: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Estonsko")

 ;; Terms of Service
 (:terms-title . "Podmínky služby")
 (:terms-updated . "Poslední aktualizace: leden 2026")
 (:terms-1-title . "1. Popis služby")
 (:terms-1-body . "Hiisi je jazyková výuková aplikace, která poskytuje překlady poháněné umělou inteligencí s gramatickými vysvětleními a kartičkami s rozloženým opakováním. Službu provozuje Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Registrace účtu")
 (:terms-2-body . "Pro používání Hiisi musíte vytvořit účet s platnou e-mailovou adresou. Jste zodpovědní za zabezpečení svých přihlašovacích údajů.")
 (:terms-3-title . "3. Předplatné a platby")
 (:terms-3-body . "Hiisi nabízí placené plány předplatného (měsíční a roční). Předplatné se zpracovává prostřednictvím Polar.sh.")
 (:terms-3-list-1 . "Předplatné se automaticky obnovuje, pokud není zrušeno před datem obnovení.")
 (:terms-3-list-2 . "Refundace jsou poskytovány v souladu s platnými zákony na ochranu spotřebitele.")
 (:terms-3-list-3 . "Neuhrazení plateb má za následek ztrátu přístupu k prémiovým funkcím.")
 (:terms-4-title . "4. Přijatelné používání")
 (:terms-4-intro . "Souhlasíte, že nebudete:")
 (:terms-4-list-1 . "Používat službu k jakémukoli nezákonnému účelu")
 (:terms-4-list-2 . "Pokoušet se obejít limity používání nebo bezpečnostní opatření")
 (:terms-4-list-3 . "Sdílet své přihlašovací údaje s ostatními")
 (:terms-4-list-4 . "Používat automatizované nástroje pro přístup ke službě způsobem, který zhoršuje výkon pro ostatní")
 (:terms-5-title . "5. Obsah a duševní vlastnictví")
 (:terms-5-body-1 . "Překlady generované Hiisi jsou vytvářeny pomocí umělé inteligence a nemusí být unikátní. Své překlady a kartičky můžete používat pro jakýkoli osobní účel, ale nemáte výhradní autorská práva k obsahu generovanému umělou inteligencí.")
 (:terms-5-body-2 . "Aplikace Hiisi, značka a původní obsah zůstávají majetkem Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Dostupnost služby")
 (:terms-6-intro . "Hiisi je poskytováno na bázi \"jak je\". Negarantujeme:")
 (:terms-6-list-1 . "Nepřerušenou nebo bezchybnou službu")
 (:terms-6-list-2 . "Přesnost překladů generovaných umělou inteligencí")
 (:terms-6-list-3 . "Dostupnost konkrétních funkcí")
 (:terms-6-body . "Funkce můžeme kdykoli upravit nebo ukončit.")
 (:terms-7-title . "7. Omezení odpovědnosti")
 (:terms-7-body-1 . "V maximální míře povolené zákonem nenese Lambda Symbolics OÜ odpovědnost za žádné nepřímé, náhodné, zvláštní nebo následné škody vzniklé z vašeho používání Hiisi.")
 (:terms-7-body-2 . "Naše celková odpovědnost nepřekročí částku, kterou jste zaplatili za službu v 12 měsících předcházejících nároku.")
 (:terms-8-title . "8. Ukončení účtu")
 (:terms-8-body-1 . "Váš účet můžeme pozastavit nebo ukončit, pokud porušíte tyto podmínky. O smazání účtu můžete požádat kdykoli prostřednictvím aplikace.")
 (:terms-8-body-2 . "Po žádosti o smazání je váš účet naplánován na smazání do 14 dnů.")
 (:terms-9-title . "9. Změny podmínek")
 (:terms-9-body . "Tyto podmínky můžeme čas od času aktualizovat. Pokračování v používání Hiisi po změnách představuje přijetí nových podmínek.")
 (:terms-10-title . "10. Rozhodné právo")
 (:terms-10-body . "Tyto podmínky se řídí zákony Estonska. Jakékoli spory budou řešeny u soudů v Estonsku.")
 (:terms-contact-title . "Kontakt")
 (:terms-contact-intro . "Pro dotazy k těmto podmínkám:")
 (:terms-contact-email-label . "E-mail: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Estonsko")



 ;; Decks
 (:decks-title . "Balíčky")
 (:decks-subtitle . "Vytvářejte vlastní balíčky a sdílejte je s ostatními.")
 (:decks-create-title . "Vytvořit balíček")
 (:decks-name-placeholder . "Název balíčku")
 (:decks-desc-placeholder . "Popis")
 (:decks-create-btn . "Vytvořit balíček")
 (:decks-your-title . "Vaše balíčky")
 (:decks-col-name . "Název")
 (:decks-col-desc . "Popis")
 (:decks-col-updated . "Aktualizováno")
 (:decks-col-actions . "Akce")
 (:decks-no-decks . "Zatím žádné balíčky.")
 (:decks-open-btn . "Otevřít")
 (:decks-no-desc . "Bez popisu.")
 (:decks-share-title . "Odkaz ke sdílení")
 (:decks-share-info . "Kdokoli s tímto odkazem může balíček importovat:")
 (:decks-share-copy . "Kopírovat odkaz")
 (:decks-share-copied . "Zkopírováno")
 (:decks-add-from-flashcards-title . "Přidat překlady")
 (:decks-add-from-flashcards-info . "Vyberte kartičku a přidejte její překlad do tohoto balíčku.")
 (:decks-open-flashcards . "Přidat z kartiček")
 (:decks-filter-from . "Z jazyka")
 (:decks-filter-to . "Do jazyka")
 (:decks-filter-any . "Jakýkoli jazyk")
 (:decks-filter-include-assigned . "Zahrnout kartičky, které už jsou v balíčku")
 (:decks-flashcards-col-from . "Z")
 (:decks-flashcards-col-to . "Do")
 (:decks-flashcards-add . "Přidat")
 (:decks-flashcards-added . "Přidáno")
 (:decks-flashcards-in-deck . "V jiném balíčku")
 (:decks-flashcards-empty . "Žádné kartičky neodpovídají těmto filtrům.")
 (:decks-add-trans-title . "Přidat překlad")
 (:decks-trans-id-placeholder . "ID překladu")
 (:decks-add-trans-btn . "Přidat překlad")
 (:decks-items-title . "Položky balíčku")
 (:decks-col-original . "Originál")
 (:decks-col-translated . "Překlad")
 (:decks-col-lang . "Cílový jazyk")
 (:decks-no-items . "Zatím žádné položky.")
 (:decks-share-page-title . "Sdílet balíček")
 (:decks-share-preview . "Náhled a import tohoto balíčku.")
 (:decks-import-title . "Import")
 (:decks-import-btn . "Importovat balíček")

 ;; Flashcards management page
 (:flashcards-title . "Moje kartičky")
 (:flashcards-subtitle . "Všechny vaše uložené kartičky na jednom místě. Hledejte, organizujte a spravujte.")
 (:flashcards-search-placeholder . "Hledat kartičky...")
 (:flashcards-col-original . "Originál")
 (:flashcards-col-translated . "Překlad")
 (:flashcards-col-lang . "Jazyky")
 (:flashcards-no-cards . "Zatím žádné kartičky. Začněte překládat a vytvořte si nějaké!")

 ;; API Errors (EN fallback)
 (:api-error-missing-text . "Missing text to translate.")
 (:api-error-invalid-translation-id . "Invalid translation ID.")
 (:api-error-translation-not-found . "The translation you tried to save no longer exists.")
 (:api-error-invalid-bookmark-id . "Invalid bookmark ID")
 (:api-error-bookmark-not-found . "Bookmark not found")
 (:api-error-forbidden . "Forbidden")
 (:api-error-failed-delete-bookmark . "Failed to delete bookmark")
 (:api-error-invalid-flashcard-id . "Invalid flashcard ID")
 (:api-error-missing-deck-id . "Missing deck_id")
 (:api-error-flashcard-not-found . "Flashcard not found")
 (:api-error-deck-not-found . "Deck not found")
 (:api-error-deck-name-required . "Deck name is required")
 (:api-error-session-expired . "Your review session has expired. Please start a new session.")
 (:api-error-invalid-card-id . "Invalid card ID.")
 (:api-error-invalid-rating . "Invalid rating.")
 (:api-error-rating-range . "Rating must be between 0 and 5.")
 (:api-error-card-not-found . "Card not found.")
 (:api-error-permission-denied . "You don't have permission to review this card.")
 (:api-error-unknown-source-lang . "Unknown source language.")
 (:api-error-unknown-target-lang . "Unknown target language.")
 (:api-error-failed-add-to-deck . "Failed to add to deck")

 ;; API Success messages
 (:api-success-added . "Added!")
 (:api-success-added-simple . "Added")

 ;; API Stats
 (:api-stats-due . "~A due")
 (:api-stats-total . "~A total")

 ;; Time units
 (:api-time-day . "day")
 (:api-time-days . "days")
 (:api-time-day-left . "day left")
 (:api-time-days-left . "days left")

 ;; Subscription status
 (:api-subscription-active . "Active")
 (:api-subscription-inactive . "Inactive")
 (:api-subscription-subscribe-hint . "Subscribe to unlock translations")

 ;; Generic status
 (:status-bad-request . "Bad Request")
 (:status-not-found . "Not Found")
 (:status-forbidden . "Forbidden")

)
