;;; Danish translations
;;; This file mirrors the structure of en.lisp

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Dansk")
 (:lang-flag . "🇩🇰")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Vælg dit sprog")
 (:lang-modal-subtitle . "Vælg dit foretrukne sprog til grænsefladen:")

 ;; Navigation
 (:nav-translate . "Oversæt")
 (:nav-review . "Gentag")
 (:nav-flashcards . "Mine kort")
 (:nav-dashboard . "Oversigt")
 (:nav-decks . "Decks")
 (:nav-logout . "Log ud")
 (:nav-home . "Hjem")
 (:nav-pricing . "Priser")
 (:nav-export-data . "Eksporter data")

 ;; App title and branding
 (:app-title . "Hiisi - Sproglæring")
 (:app-tagline . "Lær sprog gennem oversættelser")

 ;; Landing page
 (:landing-hero-title . "Mestre ethvert sprog")
 (:landing-hero-subtitle . "Oversæt hvad som helst. Generer automatisk flashcards der lærer dig hvorfor det fungerer sådan.")
 (:landing-cta . "Begynd at lære")
 (:landing-learn-more . "Læs mere")
 (:landing-how-it-works . "Sådan fungerer det")
 (:landing-feature-1-title . "Automatiske flashcards")
 (:landing-feature-1-desc . "Hver oversættelse genererer automatisk flashcards med grammatisk analyse. Ingen manuel oprettelse af kort.")
 (:landing-feature-2-title . "Spredt gentagelse")
 (:landing-feature-2-desc . "SM-2-algoritmen planlægger gentagelser med optimale intervaller. Lær effektivt, husk permanent.")
 (:landing-feature-3-title . "Grammatikundervisning")
 (:landing-feature-3-desc . "Hver oversættelse forklarer grammatik, ordstammer og sætningsstruktur. Forstå hvorfor, ikke kun hvad.")
 (:landing-free-trial . "7 dages gratis prøveperiode.")
 (:landing-start-trial . "Start gratis prøveperiode")
 (:landing-best-value . "Bedste værdi")
 (:landing-cta-title . "Klar til at lære sprog gennem grammatik, ikke udenadslære?")
 (:landing-cta-subtitle . "Hver oversættelse bliver en læringsmulighed. Hvert flashcard lærer dig hvorfor.")
 (:landing-signup-free . "Tilmeld dig gratis")

 ;; Auth pages
 (:auth-register . "Registrer")
 (:auth-login . "Log ind")
 (:auth-logout . "Log ud")
 (:auth-email . "E-mail")
 (:auth-password . "Adgangskode")
 (:auth-password-again . "Bekræft adgangskode")
 (:auth-display-name . "Visningsnavn")
 (:auth-register-title . "Registrer dig på Hiisi")
 (:auth-register-subtitle . "Opret en ny konto")
 (:auth-login-title . "Log ind på Hiisi")
 (:auth-login-subtitle . "Indtast dine oplysninger")
 (:auth-login-invalid-credentials . "Ugyldig e-mail eller adgangskode.")
 (:auth-login-rate-limited . "For mange loginforsog. Vent et par minutter og prov igen.")
 (:auth-forgot-password . "Glemt adgangskode?")
 (:auth-no-account . "Har du ikke en konto?")
 (:auth-have-account . "Har du allerede en konto?")
 (:auth-google . "Google")
 (:auth-account-created . "Konto oprettet!")
 (:auth-check-email . "Tjek din e-mail for aktiveringslinket.")
 (:auth-redirect-login . "Omdirigerer til login om")
 (:auth-seconds . "sekunder...")
 (:auth-go-now . "Gå nu")
 (:auth-not-activated . "Konto ikke aktiveret")
 (:auth-activate-title . "Aktiver din konto!")
 (:auth-activated . "Konto aktiveret!")
 (:auth-activated-message . "Din konto er blevet aktiveret. Du kan nu bruge Hiisi.")
 (:auth-redirecting . "Omdirigerer om")
 (:auth-go-to-app . "Gå til appen")
 (:auth-resend-title . "Gensend aktiveringsmail")
 (:auth-resend-subtitle . "Indtast din e-mail for at modtage et nyt aktiveringslink.")
 (:auth-resend-button . "Gensend aktiveringsmail")
 (:auth-resend-success . "Aktiveringsmail sendt!")
 (:auth-resend-success-detail . "Tjek din indbakke for det nye aktiveringslink.")
 (:auth-resend-rate-limited . "Vent venligst et par minutter før du anmoder om en ny aktiveringsmail.")
 (:auth-resend-cooldown . "Du kan anmode om en ny mail om ~a sekunder.")
 (:auth-back-to-login . "Tilbage til login")
 (:auth-forgot-password-title . "Glemt adgangskode")
 (:auth-forgot-password-subtitle . "Indtast din e-mail, så sender vi dig et link til at nulstille din adgangskode.")
 (:auth-send-reset-link . "Send nulstillingslink")
 (:auth-reset-email-sent . "Nulstillingslink sendt!")
 (:auth-reset-email-sent-detail . "Hvis en konto findes med den e-mail, vil du snart modtage et link til nulstilling af adgangskoden.")
 (:auth-reset-rate-limited . "Vent venligst et par minutter før du anmoder om en ny nulstilling af adgangskoden.")
 (:auth-reset-invalid-token . "Dette nulstillingslink er ugyldigt eller udløbet.")
 (:auth-reset-password-title . "Nulstil adgangskode")
 (:auth-reset-password-subtitle . "Indtast din nye adgangskode nedenfor.")
 (:auth-new-password . "Ny adgangskode")
 (:auth-confirm-new-password . "Bekræft ny adgangskode")
 (:auth-reset-password . "Nulstil adgangskode")
 (:auth-password-changed . "Adgangskode ændret!")
 (:auth-password-changed-detail . "Din adgangskode er blevet ændret. Du kan nu logge ind med din nye adgangskode.")
 (:auth-change-password-title . "Skift adgangskode")
 (:auth-change-password-subtitle . "Opdater din kontos adgangskode.")
 (:auth-current-password . "Nuværende adgangskode")
 (:auth-change-password . "Skift adgangskode")
 (:auth-back-to-app . "Tilbage til appen")
 (:auth-password-updated . "Adgangskode opdateret!")
 (:auth-password-updated-detail . "Din adgangskode er blevet opdateret.")

 ;; Translation page
 (:translate-title . "Oversæt")
 (:translate-input-label . "Tekst at oversætte")
 (:translate-input-placeholder . "Indtast tekst at oversætte...")
 (:translate-from . "Fra:")
 (:translate-to . "Til:")
 (:translate-submit . "Oversæt")
 (:translate-save . "Gem som flashcard")
 (:translate-saved . "Gemt!")
 (:translate-like . "Synes godt om")
 (:translate-dislike . "Synes ikke om")
 (:translate-char-limit . "tegn tilbage")
 (:translate-auto-detect . "Alle (Automatisk)")
 (:translate-empty-state . "Indtast tekst ovenfor og klik Oversæt for at se resultatet med grammatisk analyse")
 (:translate-select-deck-placeholder . "Vælg kortbunke (valgfrit)")
 (:translate-new-deck . "Ny kortbunke")
 (:translate-add-to-deck . "Tilføj til kortbunke")
 (:translate-bookmark . "Gem")
 (:translate-bookmarked . "Gemt")
 (:translate-retry . "Prøv igen")
 (:translate-like-tooltip . "God oversættelse")
 (:translate-dislike-tooltip . "Dårlig oversættelse - anmod om en ny")
 (:translate-dislike-confirm . "Dette genererer en ny oversættelse. Fortsæt?")
 (:translate-liked . "Kan lide!")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Mål")
 (:translate-deck-create-title . "Opret ny kortbunke")
 (:translate-deck-name-label . "Kortbunkens navn")
 (:translate-deck-name-placeholder . "f.eks. Finsk grundlag")
 (:translate-deck-description-label . "Beskrivelse (valgfri)")
 (:translate-deck-cancel . "Annuller")
 (:translate-deck-create . "Opret")
 (:translate-rate-label . "Bedøm oversættelse")
 (:flashcards-delete-confirm . "Er du sikker på, at du vil slette dette kort?")
 (:flashcards-deck-search-placeholder . "Søg i kortbunker...")
 (:flashcards-no-decks . "Ingen kortbunker endnu. Opret en først!")
 (:flashcards-deck-cancel . "Annuller")
 (:flashcards-recollection-tooltip . "Hukommelse: ~A")
 (:flashcards-recollection-poor . "Svag")
 (:flashcards-recollection-fair . "Rimelig")
 (:flashcards-recollection-normal . "Normal")
 (:flashcards-recollection-strong . "Stærk")
 (:flashcards-recollection-very-strong . "Meget stærk")

 ;; Flashcard review
 (:review-title . "Gentag")
 (:review-session-title . "Gentagelsessession")
 (:review-session-subtitle . "Øv dine gemte flashcards")
 (:review-selector-title . "Vælg hvad du vil gentage")
 (:review-selector-subtitle . "Vælg et kortsæt eller et sprogpar at fokusere din gentagelsessession på.")
 (:review-by-deck . "Gentag efter kortsæt")
 (:review-by-language-pair . "Gentag efter sprogpar")
 (:review-all-cards . "Gentag alle kort")

 (:review-start . "Start gentagelse")
 (:review-no-cards . "Ingen kort at gentage")
 (:review-no-cards-desc . "Du har ingen flashcards der skal gentages lige nu.")
 (:review-no-cards-hint . "Oversæt noget tekst og klik \"Gem som flashcard\" for at opbygge din samling!")
 (:review-start-translating . "Begynd at oversætte")
 (:review-show-answer . "Vis svar")
 (:review-click-reveal . "Klik for at vise svar")
 (:review-grammar-breakdown . "Grammatisk analyse")
 (:review-how-well . "Hvor godt huskede du?")
 (:review-again . "Igen")
 (:review-hard . "Svært")
 (:review-good . "Godt")
 (:review-easy . "Nemt")
 (:review-progress . "Kort ~a af ~a")
 (:review-complete . "Session fuldført!")
 (:review-complete-msg . "Du gennemgik ~a kort")
 (:review-correct . "Korrekt")
 (:review-accuracy . "Præcision")
 (:review-again-btn . "Gentag igen")
 (:review-translate-more . "Oversæt mere")
 (:review-streak . "dages række")

 ;; Dashboard
 (:dashboard-title . "Oversigt")
 (:dashboard-cards-due . "Kort for i dag")
 (:dashboard-total-cards . "Kort i alt")
 (:dashboard-subscription . "Abonnement")
 (:dashboard-subscribed-until . "Abonnerer til")
 (:dashboard-not-subscribed . "Ikke abonneret")
 (:dashboard-recent . "Seneste oversættelser")
 (:dashboard-no-translations . "Ingen oversættelser endnu")
 (:dashboard-streak . "Gentagelsesrække")
 (:dashboard-days . "dage")
 (:dashboard-quick-actions . "Hurtige handlinger")
 (:dashboard-getting-started . "Kom godt i gang")
 (:dashboard-tip-1 . "Oversæt tekst du vil lære")
 (:dashboard-tip-2 . "Klik \"Gem som flashcard\" på oversættelser du vil huske")
 (:dashboard-tip-3 . "Gentag dine flashcards regelmæssigt - spredt gentagelse hjælper dig med at huske langsigtet")
 (:dashboard-tip-4 . "Bedøm ærligt - det hjælper algoritmen med at planlægge dine gentagelser optimalt")

 ;; Account
 (:account-title . "Konto")
 (:account-subtitle . "Administrer dine kontoindstillinger og sletteplan.")
 (:account-deletion-title . "Sletning af konto")
 (:account-deletion-scheduled . "Din konto er planlagt til sletning den ~A.")
 (:account-deletion-cancel-hint . "Du kan annullere før denne dato for at beholde din konto.")
 (:account-deletion-cancel . "Annuller sletning")
 (:account-deletion-request . "Du kan anmode om sletning af kontoen når som helst. Sletning planlægges 14 dage efter bekræftelse. Hvis du fortryder efter sletning, kontakt support.")
 (:account-deletion-confirm . "Planlæg sletning af konto om 14 dage fra nu?")
 (:account-deletion-schedule . "Planlæg sletning")
 (:account-reminders-title . "E-mailpåmindelser")
 (:account-reminders-subtitle . "Styr påmindelser om gentagelse og fortsættelse for denne konto.")
 (:account-reminders-opt-out . "Fravælg påmindelser om gentagelse og fortsættelse")
 (:account-reminders-save . "Gem indstillinger")

 ;; Subscription
 (:subscribe-title . "Enkle priser")
 (:subscribe-choose-plan . "Vælg din plan")
 (:subscribe-start-today . "Begynd at lære i dag med en 7-dages gratis prøveperiode")
 (:subscribe-monthly . "Månedlig")
 (:subscribe-annual . "Årlig")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/måned")
 (:subscribe-per-year . "/år")
 (:subscribe-monthly-desc . "600 oversættelser om måneden")
 (:subscribe-unlimited-flashcards . "Ubegrænsede flashcards")
 (:subscribe-grammar-explanations . "Grammatikforklaringer")
 (:subscribe-spaced-repetition . "Spredt gentagelse")
 (:subscribe-annual-desc . "Spar €20 - to måneder gratis!")
 (:subscribe-cta . "Abonner")
 (:subscribe-success . "Abonnement gennemført!")
 (:subscribe-manage . "Administrer abonnement")
 (:subscribe-activated . "Abonnement aktiveret!")
 (:subscribe-thank-you . "Tak fordi du abonnerer. Din konto er nu aktiv.")
 (:subscribe-start-learning . "Begynd at lære")
 (:subscribe-management . "Abonnementsstyring")
 (:subscribe-active . "Aktivt abonnement")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Aktiv")
 (:subscribe-days-remaining . "Dage tilbage:")
 (:subscribe-renews-on . "Fornyes den:")
 (:subscribe-no-subscription . "Intet aktivt abonnement")
 (:subscribe-access-features . "Abonner for at få adgang til alle funktioner.")
 (:subscribe-view-plans . "Se planer")
 (:subscribe-faq-title . "Ofte stillede spørgsmål")
 (:subscribe-faq-trial-q . "Hvad sker der efter den gratis prøveperiode?")
 (:subscribe-faq-trial-a . "Efter din 7-dages gratis prøveperiode opkræves du for den valgte plan. Du kan annullere når som helst inden prøveperioden slutter.")
 (:subscribe-faq-cancel-q . "Kan jeg annullere når som helst?")
 (:subscribe-faq-cancel-a . "Ja! Du kan annullere dit abonnement når som helst. Du beholder adgangen indtil udgangen af din faktureringsperiode.")
 (:subscribe-faq-payment-q . "Hvilke betalingsmetoder accepterer I?")
 (:subscribe-faq-payment-a . "Vi accepterer alle større kredit- og debetkort gennem vores betalingspartner Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Noget gik galt")
 (:error-not-found . "Siden blev ikke fundet")
 (:error-unauthorized . "Log ind for at fortsætte")
 (:error-subscription-required . "Abonnement påkrævet")
 (:error-text-too-long . "Teksten er for lang. Maksimal oversættelseslængde er 120 tegn.")
 (:error-input-too-long . "Input for langt")
 (:error-unknown-source-lang . "Det valgte kildesprog understøttes ikke.")
 (:error-unknown-target-lang . "Det valgte målsprog understøttes ikke.")
 (:error-unknown-language . "Ukendt sprog")
 (:error-translation-unavailable . "Oversættelsestjenesten er midlertidigt utilgængelig. Prøv igen om et øjeblik.")
 (:error-translation-failed . "Oversættelse mislykkedes")
 (:error-translation-retry . "Kunne ikke generere en oversættelse efter flere forsøg. Prøv at omformulere din tekst.")
 (:error-quota-exceeded . "Oversættelsesgrænse nået")
 (:error-quota-exceeded-detail . "Du har brugt alle dine oversættelser for denne måned. Din kvote nulstilles automatisk hver måned.")
 (:quota-warning . "Oversættelser tilbage: ~A")
 (:quota-low-warning . "Kun ~A oversættelser tilbage. Overvej at købe flere.")
 (:top-up-button . "Køb flere oversættelser")
 (:top-up-success . "Opfyldning succesfuld! Du har nu ~A yderligere oversættelser.")
 (:top-up-price . "€5")
 (:top-up-amount . "300 oversættelser")
 (:loading . "Indlæser...")
 (:empty-state . "Intet her endnu")

 ;; Institutions
 (:institutions-page-title . "Hiisi til skoler - institutionelle licenser")
 (:institutions-hero-title . "Hiisi til skoler")
 (:institutions-hero-subtitle . "Giv dine studerende AI-understøttet sprogindlæring")
 (:institutions-section-title . "Institutionelle licenser")
 (:institutions-section-body . "Vi tilbyder volumenlicenser til skoler, universiteter og sprogskoler. Studerende med e-mailadresser fra dit domæne får automatisk fuld adgang.")
 (:institutions-benefit-1 . "Automatisk tilmelding for studerende med institutionel e-mail")
 (:institutions-benefit-2 . "Ingen individuelle studiekonti at administrere")
 (:institutions-benefit-3 . "Fleksible faktureringsmuligheder")
 (:institutions-benefit-4 . "Dedikeret support til undervisere")
 (:institutions-request-title . "Anmod om en licens")
 (:institutions-request-subtitle . "Udfyld formularen nedenfor, så vender vi tilbage inden for 2 arbejdsdage.")
 (:institutions-field-name . "Institutionsnavn")
 (:institutions-field-name-placeholder . "Københavns Universitet")
 (:institutions-field-contact-name . "Kontaktperson")
 (:institutions-field-contact-name-placeholder . "Dit navn")
 (:institutions-field-contact-email . "Kontakt-e-mail")
 (:institutions-field-contact-email-placeholder . "dig@universitet.dk")
 (:institutions-field-domains . "E-maildomæner")
 (:institutions-field-domains-placeholder . "universitet.dk, cs.universitet.dk")
 (:institutions-field-domains-help . "Kommasepareret liste over e-maildomæner for din institution")
 (:institutions-field-notes . "Yderligere oplysninger")
 (:institutions-field-notes-placeholder . "Estimeret antal studerende, foretrukken faktureringscyklus, særlige krav...")
 (:institutions-submit . "Send forespørgsel")
 (:institutions-success-title . "Tak - Hiisi til skoler")
 (:institutions-success-heading . "Tak!")
 (:institutions-success-body . "Vi har modtaget din forespørgsel om en institutionel licens. Vores team vil gennemgå din anmodning og vende tilbage inden for 2 arbejdsdage.")
 (:institutions-success-back . "Tilbage til forsiden")

 ;; Footer
 (:footer-privacy . "Privatlivspolitik")
 (:footer-terms . "Servicevilkår")
 (:footer-contact . "Kontakt")

 ;; Early software notice
 (:early-software-notice . "Hiisi er under tidlig udvikling. Fundet en fejl eller har du et forslag?")
 (:early-software-contact . "Kontakt os på")

 ;; Privacy Policy
 (:privacy-title . "Privacy Policy")
 (:privacy-updated . "Last updated: January 2026")
 (:privacy-who-title . "Who We Are")
 (:privacy-who-body . "Hiisi is operated by Lambda Symbolics OÜ, a company registered in Estonia. As an Estonian company, we comply with the European Union's General Data Protection Regulation (GDPR).")
 (:privacy-collect-title . "Data We Collect")
 (:privacy-collect-intro . "We collect the following information when you use Hiisi:")
 (:privacy-collect-account-key . "Account information: ")
 (:privacy-collect-account-val . "Email address, display name, and a securely hashed password.")
 (:privacy-collect-learning-key . "Learning data: ")
 (:privacy-collect-learning-val . "Your translations, saved flashcards, and review history.")
 (:privacy-collect-usage-key . "Usage data: ")
 (:privacy-collect-usage-val . "Basic server logs for security and debugging purposes.")
 (:privacy-use-title . "How We Use Your Data")
 (:privacy-use-auth-key . "Authentication: ")
 (:privacy-use-auth-val . "To verify your identity and secure your account.")
 (:privacy-use-service-key . "Service delivery: ")
 (:privacy-use-service-val . "To provide translations and manage your flashcard collection.")
 (:privacy-use-ai-key . "AI translations: ")
 (:privacy-use-ai-val . "Your translation requests are sent to Anthropic's Claude API to generate responses. See Anthropic's privacy policy for how they handle this data.")
 (:privacy-third-title . "Third-Party Services")
 (:privacy-third-intro . "We use the following third-party services:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "For AI-powered translations.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "For sending account activation and transactional emails.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "For subscription payment processing.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "We use only essential cookies:")
 (:privacy-cookies-auth-key . "Authentication token: ")
 (:privacy-cookies-auth-val . "A secure, HTTP-only cookie to keep you logged in.")
 (:privacy-cookies-lang-key . "Language preference: ")
 (:privacy-cookies-lang-val . "To remember your preferred UI language.")
 (:privacy-retention-title . "Data Retention")
 (:privacy-retention-body . "Your data is stored as long as you maintain an account. When you request deletion, your account is scheduled for deletion in 14 days.")
 (:privacy-rights-title . "Your Rights (GDPR)")
 (:privacy-rights-intro . "Under GDPR, you have the right to:")
 (:privacy-rights-access . "Access your personal data")
 (:privacy-rights-export . "Export your data (available at /app/api/export)")
 (:privacy-rights-correct . "Request correction of inaccurate data")
 (:privacy-rights-delete . "Request deletion of your account and data")
 (:privacy-rights-object . "Object to processing of your data")
 (:privacy-rights-contact . "To exercise these rights, contact us at")
 (:privacy-contact-title . "Contact")
 (:privacy-contact-intro . "For privacy-related inquiries:")
 (:privacy-contact-email-label . "Email: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Estonia")

 ;; Terms of Service
 (:terms-title . "Terms of Service")
 (:terms-updated . "Last updated: January 2026")
 (:terms-1-title . "1. Service Description")
 (:terms-1-body . "Hiisi is a language learning application that provides AI-powered translations with grammatical explanations and spaced repetition flashcards. The service is operated by Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Account Registration")
 (:terms-2-body . "To use Hiisi, you must create an account with a valid email address. You are responsible for maintaining the security of your account credentials.")
 (:terms-3-title . "3. Subscription and Payments")
 (:terms-3-body . "Hiisi offers paid subscription plans (monthly and annual). Subscriptions are processed through Polar.sh.")
 (:terms-3-list-1 . "Subscriptions auto-renew unless cancelled before the renewal date.")
 (:terms-3-list-2 . "Refunds are provided in accordance with applicable consumer protection laws.")
 (:terms-3-list-3 . "Non-payment results in loss of access to premium features.")
 (:terms-4-title . "4. Acceptable Use")
 (:terms-4-intro . "You agree not to:")
 (:terms-4-list-1 . "Use the service for any illegal purpose")
 (:terms-4-list-2 . "Attempt to circumvent usage limits or security measures")
 (:terms-4-list-3 . "Share your account credentials with others")
 (:terms-4-list-4 . "Use automated tools to access the service in a way that degrades performance for others")
 (:terms-5-title . "5. Content and Intellectual Property")
 (:terms-5-body-1 . "Translations generated by Hiisi are created using AI and may not be unique. You may use your translations and flashcards for any personal purpose, but you do not hold exclusive authorship rights over AI-generated content.")
 (:terms-5-body-2 . "The Hiisi application, branding, and original content remain the property of Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Service Availability")
 (:terms-6-intro . "Hiisi is provided on an \"as-is\" basis. We do not guarantee:")
 (:terms-6-list-1 . "Uninterrupted or error-free service")
 (:terms-6-list-2 . "Accuracy of AI-generated translations")
 (:terms-6-list-3 . "Availability of specific features")
 (:terms-6-body . "We may modify or discontinue features at any time.")
 (:terms-7-title . "7. Limitation of Liability")
 (:terms-7-body-1 . "To the maximum extent permitted by law, Lambda Symbolics OÜ shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of Hiisi.")
 (:terms-7-body-2 . "Our total liability shall not exceed the amount you paid for the service in the 12 months preceding the claim.")
 (:terms-8-title . "8. Account Termination")
 (:terms-8-body-1 . "We may suspend or terminate your account if you violate these terms. You may request account deletion at any time through the application.")
 (:terms-8-body-2 . "Upon deletion request, your account is scheduled for deletion in 14 days.")
 (:terms-9-title . "9. Changes to Terms")
 (:terms-9-body . "We may update these terms from time to time. Continued use of Hiisi after changes constitutes acceptance of the new terms.")
 (:terms-10-title . "10. Governing Law")
 (:terms-10-body . "These terms are governed by the laws of Estonia. Any disputes shall be resolved in the courts of Estonia.")
 (:terms-contact-title . "Contact")
 (:terms-contact-intro . "For questions about these terms:")
 (:terms-contact-email-label . "Email: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Estonia")



 ;; Decks
 (:decks-title . "Kortbunker")
 (:decks-subtitle . "Opret brugerdefinerede kortbunker og del dem med andre.")
 (:decks-create-title . "Opret kortbunke")
 (:decks-name-placeholder . "Kortbunkens navn")
 (:decks-desc-placeholder . "Beskrivelse")
 (:decks-create-btn . "Opret kortbunke")
 (:decks-your-title . "Dine kortbunker")
 (:decks-col-name . "Navn")
 (:decks-col-desc . "Beskrivelse")
 (:decks-col-updated . "Opdateret")
 (:decks-col-actions . "Handlinger")
 (:decks-no-decks . "Ingen kortbunker endnu.")
 (:decks-open-btn . "Åbn")
 (:decks-no-desc . "Ingen beskrivelse.")
 (:decks-share-title . "Delingslink")
 (:decks-share-info . "Alle med dette link kan importere kortbunken:")
 (:decks-share-copy . "Kopiér link")
 (:decks-share-copied . "Kopieret")
 (:decks-add-from-flashcards-title . "Tilføj oversættelser")
 (:decks-add-from-flashcards-info . "Vælg et kort for at tilføje dets oversættelse til denne kortbunke.")
 (:decks-open-flashcards . "Tilføj fra kort")
 (:decks-filter-from . "Kildesprog")
 (:decks-filter-to . "Målsprog")
 (:decks-filter-any . "Alle sprog")
 (:decks-filter-include-assigned . "Inkludér kort, der allerede er i en kortbunke")
 (:decks-flashcards-col-from . "Fra")
 (:decks-flashcards-col-to . "Til")
 (:decks-flashcards-add . "Tilføj")
 (:decks-flashcards-added . "Tilføjet")
 (:decks-flashcards-in-deck . "I en anden kortbunke")
 (:decks-flashcards-empty . "Ingen kort matcher disse filtre.")
 (:decks-add-trans-title . "Tilføj oversættelse")
 (:decks-trans-id-placeholder . "Oversættelses-ID")
 (:decks-add-trans-btn . "Tilføj oversættelse")
 (:decks-items-title . "Kortbunkens indhold")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Oversættelse")
 (:decks-col-lang . "Målsprog")
 (:decks-no-items . "Ingen elementer endnu.")
 (:decks-share-page-title . "Del kortbunke")
 (:decks-share-preview . "Forhåndsvis og importer denne kortbunke.")
 (:decks-import-title . "Importer")
 (:decks-import-btn . "Importer kortbunke")

 ;; Flashcards management page
 (:flashcards-title . "Mine kort")
 (:flashcards-subtitle . "Alle dine gemte kort på ét sted. Søg, organiser og administrer.")
 (:flashcards-search-placeholder . "Søg i kort...")
 (:flashcards-col-original . "Original")
 (:flashcards-col-translated . "Oversættelse")
 (:flashcards-col-lang . "Sprog")
 (:flashcards-no-cards . "Ingen kort endnu. Begynd at oversætte for at oprette nogle!")

 ;; API errors
 (:api-error-missing-text . "Manglende tekst til oversættelse.")
 (:api-error-invalid-translation-id . "Ugyldigt oversættelses-ID.")
 (:api-error-translation-not-found . "Oversættelsen, du forsøgte at gemme, findes ikke længere.")
 (:api-error-invalid-bookmark-id . "Ugyldigt bogmærke-ID")
 (:api-error-bookmark-not-found . "Bogmærke ikke fundet")
 (:api-error-forbidden . "Forbudt")
 (:api-error-failed-delete-bookmark . "Kunne ikke slette bogmærke")
 (:api-error-invalid-flashcard-id . "Ugyldigt flashkort-ID")
 (:api-error-missing-deck-id . "Manglende kortbunke-ID")
 (:api-error-flashcard-not-found . "Flashkort ikke fundet")
 (:api-error-deck-not-found . "Kortbunke ikke fundet")
 (:api-error-deck-name-required . "Kortbunkenavn er påkrævet")
 (:api-error-session-expired . "Din repetitionssession er udløbet. Start venligst en ny session.")
 (:api-error-invalid-card-id . "Ugyldigt kort-ID.")
 (:api-error-invalid-rating . "Ugyldig vurdering.")
 (:api-error-rating-range . "Vurdering skal være mellem 0 og 5.")
 (:api-error-card-not-found . "Kort ikke fundet.")
 (:api-error-permission-denied . "Du har ikke tilladelse til at repetere dette kort.")
 (:api-error-unknown-source-lang . "Ukendt kildesprog.")
 (:api-error-unknown-target-lang . "Ukendt målsprog.")
 (:api-error-failed-add-to-deck . "Kunne ikke tilføje til kortbunke")

 ;; API success messages
 (:api-success-added . "Tilføjet!")
 (:api-success-added-simple . "Tilføjet")

 ;; API stats
 (:api-stats-due . "~A forfalder")
 (:api-stats-total . "~A i alt")

 ;; Time units
 (:api-time-day . "dag")
 (:api-time-days . "dage")
 (:api-time-day-left . "dag tilbage")
 (:api-time-days-left . "dage tilbage")

 ;; Subscription status
 (:api-subscription-active . "Aktiv")
 (:api-subscription-inactive . "Inaktiv")
 (:api-subscription-subscribe-hint . "Abonnér for at låse oversættelser op")

 ;; Generic status
 (:status-bad-request . "Ugyldig anmodning")
 (:status-not-found . "Ikke fundet")
 (:status-forbidden . "Forbudt")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Lær sprog grundigt")
 (:landing-hero-subheadline . "Få oversættelser med fuld grammatisk analyse og opbyg et varigt ordforråd gennem flashkort med distribueret repetition.")
 (:landing-hero-trust-line . "7 dages gratis prøveperiode med 100 oversættelser. Kort kræves. Opsig når som helst.")
 (:landing-credibility-languages . "14 sprog")
 (:landing-credibility-ai . "Grammatisk analyse inkluderet")
 (:landing-credibility-origin . "Lavet i Estland")
 (:landing-step-1-title . "Oversæt enhver tekst")
 (:landing-step-1-desc . "Indtast et ord eller en sætning. Få en oversættelse med fuld grammatisk analyse.")
 (:landing-step-2-title . "Gem som flashkort")
 (:landing-step-2-desc . "Gem de oversættelser, du vil huske. Flashkort oprettes automatisk.")
 (:landing-step-3-title . "Repetér og husk")
 (:landing-step-3-desc . "Distribueret repetition planlægger gennemgange på det perfekte tidspunkt for langtidshukommelsen.")
 (:landing-feature-grammar-title . "Forstå grammatik, ikke kun ord")
 (:landing-feature-grammar-desc . "Hver oversættelse indeholder en detaljeret grammatisk analyse - ordformer, kasus og bøjninger forklaret på dit sprog.")
 (:landing-feature-srs-title . "Videnskabeligt baseret memorering")
 (:landing-feature-srs-desc . "SM-2-algoritmen tilpasser sig din præstation. Svære kort vises oftere. Kort, du kan, træder i baggrunden.")
 (:landing-feature-share-title . "Del kortbunker med elever")
 (:landing-feature-share-desc . "Lærere kan oprette egne kortbunker og dele dem med et link. Elever importerer kortbunken og begynder at repetere med det samme.")
 (:landing-pricing-trial-note . "Inkluderer 7 dages gratis prøveperiode")
 (:landing-pricing-monthly-after . "7 dage gratis, derefter ~A/måned")
 (:landing-pricing-annual-after . "7 dage gratis, derefter ~A/år")
 (:landing-faq-title . "Ofte stillede spørgsmål")
 (:landing-faq-trial-cap-q . "Hvor mange oversættelser får jeg under prøveperioden?")
 (:landing-faq-trial-cap-a . "Du får 100 oversættelser i din 7-dages prøveperiode. Efter abonnement får du 600 om måneden.")
 (:landing-final-cta-title . "Begynd at lære i dag")
 (:landing-final-cta-subtitle . "Bliv en del af Hiisi og begynd at opbygge ordforråd, der holder.")

 ;; Trial status (in-app)
 (:trial-status . "Gratis prøveperiode")
 (:trial-days-remaining . "~A dage tilbage")
 (:trial-translations-used . "~A/100 oversættelser brugt")
 (:trial-upgrade-prompt . "Opgrader for at fortsætte med at oversætte")
 (:trial-expired . "Din gratis prøveperiode er udløbet")
 (:trial-expired-detail . "Abonner for at fortsætte med at lære med Hiisi.")
 (:trial-quota-warning . "~A prøveoversættelser tilbage (~A dage). Abonner for 600/måned.")
 (:trial-quota-exceeded . "Grænse for prøveoversættelser nået. Abonner for at fortsætte.")
 (:error-trial-quota-exceeded . "Grænse for prøveoversættelser nået")
 (:error-trial-quota-detail . "Du har brugt alle 100 prøveoversættelser. Abonner for at fortsætte med at lære.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Opret flashkort")
 (:custom-flashcard-edit-title . "Rediger flashkort")
 (:custom-flashcard-original . "Originaltekst")
 (:custom-flashcard-translated . "Oversættelse")
 (:custom-flashcard-lang-from . "Kildesprog")
 (:custom-flashcard-lang-to . "Målsprog")
 (:custom-flashcard-note . "Pædagogisk note")
 (:custom-flashcard-forms . "Grammatisk analyse")
 (:custom-flashcard-form-term . "Begreb")
 (:custom-flashcard-form-explanation . "Forklaring")
 (:custom-flashcard-add-form . "Tilføj grammatisk begreb")
 (:custom-flashcard-remove-form . "Fjern")
 (:custom-flashcard-ai-fill . "Udfyld med AI")
 (:custom-flashcard-ai-fill-all . "Udfyld alt med AI")
 (:custom-flashcard-ai-fill-translation . "Oversæt med AI")
 (:custom-flashcard-ai-fill-breakdown . "Generer analyse")
 (:custom-flashcard-ai-fill-note . "Generer note")
 (:custom-flashcard-create-btn . "Opret flashkort")
 (:custom-flashcard-update-btn . "Gem ændringer")
 (:custom-flashcard-delete-btn . "Slet flashkort")
 (:custom-flashcard-delete-confirm . "Er du sikker på, at du vil slette dette flashkort?")
 (:custom-flashcard-created . "Flashkort oprettet")
 (:custom-flashcard-updated . "Flashkort opdateret")
 (:custom-flashcard-deleted . "Flashkort slettet")
 (:custom-flashcard-add-to-deck . "Tilføj til kortbunke")
 (:custom-flashcard-not-found . "Flashkort ikke fundet")
 (:custom-flashcard-not-owner . "Du kan kun redigere flashkort, du selv har oprettet")
 (:custom-flashcard-ai-generating . "Genererer med AI...")
 (:custom-flashcard-badge . "Tilpasset")

)
