;;; Danish translations
;;; This file mirrors the structure of en.lisp

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Dansk")
 (:lang-flag . "🇩🇰")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Vælg dit sprog")
 (:lang-modal-subtitle . "Vælg dit foretrukne sprog til grænsefladen:")

 ;; Navigation
 (:nav-translate . "Oversæt")
 (:nav-review . "Gentag")
 (:nav-flashcards . "Mine kort")
 (:nav-dashboard . "Oversigt")
 (:nav-decks . "Decks")
 (:nav-logout . "Log ud")
 (:nav-home . "Hjem")
 (:nav-pricing . "Priser")
 (:nav-export-data . "Eksporter data")

 ;; App title and branding
 (:app-title . "Hiisi - Sproglæring")
 (:app-tagline . "Lær sprog gennem oversættelser")

 ;; Landing page
 (:landing-hero-title . "Mestre ethvert sprog")
 (:landing-hero-subtitle . "Oversæt hvad som helst. Generer automatisk flashcards der lærer dig hvorfor det fungerer sådan.")
 (:landing-cta . "Begynd at lære")
 (:landing-learn-more . "Læs mere")
 (:landing-how-it-works . "Sådan fungerer det")
 (:landing-feature-1-title . "Automatiske flashcards")
 (:landing-feature-1-desc . "Hver oversættelse genererer automatisk flashcards med grammatisk analyse. Ingen manuel oprettelse af kort.")
 (:landing-feature-2-title . "Spredt gentagelse")
 (:landing-feature-2-desc . "SM-2-algoritmen planlægger gentagelser med optimale intervaller. Lær effektivt, husk permanent.")
 (:landing-feature-3-title . "Grammatikundervisning")
 (:landing-feature-3-desc . "Hver oversættelse forklarer grammatik, ordstammer og sætningsstruktur. Forstå hvorfor, ikke kun hvad.")
 (:landing-free-trial . "7 dages gratis prøveperiode.")
 (:landing-start-trial . "Start gratis prøveperiode")
 (:landing-best-value . "Bedste værdi")
 (:landing-cta-title . "Klar til at lære sprog gennem grammatik, ikke udenadslære?")
 (:landing-cta-subtitle . "Hver oversættelse bliver en læringsmulighed. Hvert flashcard lærer dig hvorfor.")
 (:landing-signup-free . "Tilmeld dig gratis")

 ;; Auth pages
 (:auth-register . "Registrer")
 (:auth-login . "Log ind")
 (:auth-logout . "Log ud")
 (:auth-email . "E-mail")
 (:auth-password . "Adgangskode")
 (:auth-password-again . "Bekræft adgangskode")
 (:auth-display-name . "Visningsnavn")
 (:auth-register-title . "Registrer dig på Hiisi")
 (:auth-register-subtitle . "Opret en ny konto")
 (:auth-login-title . "Log ind på Hiisi")
 (:auth-login-subtitle . "Indtast dine oplysninger")
 (:auth-login-invalid-credentials . "Ugyldig e-mail eller adgangskode.")
 (:auth-login-rate-limited . "For mange loginforsog. Vent et par minutter og prov igen.")
 (:auth-forgot-password . "Glemt adgangskode?")
 (:auth-no-account . "Har du ikke en konto?")
 (:auth-have-account . "Har du allerede en konto?")
 (:auth-google . "Google")
 (:auth-account-created . "Konto oprettet!")
 (:auth-check-email . "Tjek din e-mail for aktiveringslinket.")
 (:auth-redirect-login . "Omdirigerer til login om")
 (:auth-seconds . "sekunder...")
 (:auth-go-now . "Gå nu")
 (:auth-not-activated . "Konto ikke aktiveret")
 (:auth-activate-title . "Aktiver din konto!")
 (:auth-activated . "Konto aktiveret!")
 (:auth-activated-message . "Din konto er blevet aktiveret. Du kan nu bruge Hiisi.")
 (:auth-redirecting . "Omdirigerer om")
 (:auth-go-to-app . "Gå til appen")
 (:auth-resend-title . "Gensend aktiveringsmail")
 (:auth-resend-subtitle . "Indtast din e-mail for at modtage et nyt aktiveringslink.")
 (:auth-resend-button . "Gensend aktiveringsmail")
 (:auth-resend-success . "Aktiveringsmail sendt!")
 (:auth-resend-success-detail . "Tjek din indbakke for det nye aktiveringslink.")
 (:auth-resend-rate-limited . "Vent venligst et par minutter før du anmoder om en ny aktiveringsmail.")
 (:auth-resend-cooldown . "Du kan anmode om en ny mail om ~a sekunder.")
 (:auth-back-to-login . "Tilbage til login")
 (:auth-forgot-password-title . "Glemt adgangskode")
 (:auth-forgot-password-subtitle . "Indtast din e-mail, så sender vi dig et link til at nulstille din adgangskode.")
 (:auth-send-reset-link . "Send nulstillingslink")
 (:auth-reset-email-sent . "Nulstillingslink sendt!")
 (:auth-reset-email-sent-detail . "Hvis en konto findes med den e-mail, vil du snart modtage et link til nulstilling af adgangskoden.")
 (:auth-reset-rate-limited . "Vent venligst et par minutter før du anmoder om en ny nulstilling af adgangskoden.")
 (:auth-reset-invalid-token . "Dette nulstillingslink er ugyldigt eller udløbet.")
 (:auth-reset-password-title . "Nulstil adgangskode")
 (:auth-reset-password-subtitle . "Indtast din nye adgangskode nedenfor.")
 (:auth-new-password . "Ny adgangskode")
 (:auth-confirm-new-password . "Bekræft ny adgangskode")
 (:auth-reset-password . "Nulstil adgangskode")
 (:auth-password-changed . "Adgangskode ændret!")
 (:auth-password-changed-detail . "Din adgangskode er blevet ændret. Du kan nu logge ind med din nye adgangskode.")
 (:auth-change-password-title . "Skift adgangskode")
 (:auth-change-password-subtitle . "Opdater din kontos adgangskode.")
 (:auth-current-password . "Nuværende adgangskode")
 (:auth-change-password . "Skift adgangskode")
 (:auth-back-to-app . "Tilbage til appen")
 (:auth-password-updated . "Adgangskode opdateret!")
 (:auth-password-updated-detail . "Din adgangskode er blevet opdateret.")

 ;; Translation page
 (:translate-title . "Oversæt")
 (:translate-input-label . "Tekst at oversætte")
 (:translate-input-placeholder . "Indtast tekst at oversætte...")
 (:translate-from . "Fra:")
 (:translate-to . "Til:")
 (:translate-submit . "Oversæt")
 (:translate-save . "Gem som flashcard")
 (:translate-saved . "Gemt!")
 (:translate-like . "Synes godt om")
 (:translate-dislike . "Synes ikke om")
 (:translate-char-limit . "tegn tilbage")
 (:translate-auto-detect . "Alle (Automatisk)")
 (:translate-empty-state . "Indtast tekst ovenfor og klik Oversæt for at se resultatet med grammatisk analyse")
 (:translate-select-deck-placeholder . "Vælg kortbunke (valgfrit)")
 (:translate-new-deck . "Ny kortbunke")
 (:translate-add-to-deck . "Tilføj til kortbunke")
 (:translate-bookmark . "Gem")
 (:translate-bookmarked . "Gemt")
 (:translate-retry . "Prøv igen")
 (:translate-like-tooltip . "God oversættelse")
 (:translate-dislike-tooltip . "Dårlig oversættelse - anmod om en ny")
 (:translate-dislike-confirm . "Dette genererer en ny oversættelse. Fortsæt?")
 (:translate-liked . "Kan lide!")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Mål")
 (:translate-deck-create-title . "Opret ny kortbunke")
 (:translate-deck-name-label . "Kortbunkens navn")
 (:translate-deck-name-placeholder . "f.eks. Finsk grundlag")
 (:translate-deck-description-label . "Beskrivelse (valgfri)")
 (:translate-deck-cancel . "Annuller")
 (:translate-deck-create . "Opret")
 (:translate-rate-label . "Bedøm oversættelse")
 (:flashcards-delete-confirm . "Er du sikker på, at du vil slette dette kort?")
 (:flashcards-deck-search-placeholder . "Søg i kortbunker...")
 (:flashcards-no-decks . "Ingen kortbunker endnu. Opret en først!")
 (:flashcards-deck-cancel . "Annuller")
 (:flashcards-recollection-tooltip . "Hukommelse: ~A")
 (:flashcards-recollection-poor . "Svag")
 (:flashcards-recollection-fair . "Rimelig")
 (:flashcards-recollection-normal . "Normal")
 (:flashcards-recollection-strong . "Stærk")
 (:flashcards-recollection-very-strong . "Meget stærk")

 ;; Flashcard review
 (:review-title . "Gentag")
 (:review-session-title . "Gentagelsessession")
 (:review-session-subtitle . "Øv dine gemte flashcards")
 (:review-selector-title . "Vælg hvad du vil gentage")
 (:review-selector-subtitle . "Vælg et kortsæt eller et sprogpar at fokusere din gentagelsessession på.")
 (:review-by-deck . "Gentag efter kortsæt")
 (:review-by-language-pair . "Gentag efter sprogpar")
 (:review-all-cards . "Gentag alle kort")

 (:review-start . "Start gentagelse")
 (:review-no-cards . "Ingen kort at gentage")
 (:review-no-cards-desc . "Du har ingen flashcards der skal gentages lige nu.")
 (:review-no-cards-hint . "Oversæt noget tekst og klik \"Gem som flashcard\" for at opbygge din samling!")
 (:review-start-translating . "Begynd at oversætte")
 (:review-show-answer . "Vis svar")
 (:review-click-reveal . "Klik for at vise svar")
 (:review-grammar-breakdown . "Grammatisk analyse")
 (:review-how-well . "Kunne du huske det?")
 (:review-again . "Nej")
 (:review-hard . "Knap nok")
 (:review-good . "Ja")
 (:review-easy . "Nemt")
 (:review-progress . "Kort ~a af ~a")
 (:review-complete . "Session fuldført!")
 (:review-complete-msg . "Du gennemgik ~a kort")
 (:review-correct . "Korrekt")
 (:review-accuracy . "Præcision")
 (:review-again-btn . "Gentag igen")
 (:review-translate-more . "Oversæt mere")
 (:review-streak . "dages række")

 ;; Dashboard
 (:dashboard-title . "Oversigt")
 (:dashboard-cards-due . "Kort for i dag")
 (:dashboard-total-cards . "Kort i alt")
 (:dashboard-subscription . "Abonnement")
 (:dashboard-subscribed-until . "Abonnerer til")
 (:dashboard-not-subscribed . "Ikke abonneret")
 (:dashboard-recent . "Seneste oversættelser")
 (:dashboard-no-translations . "Ingen oversættelser endnu")
 (:dashboard-streak . "Gentagelsesrække")
 (:dashboard-days . "dage")
 (:dashboard-all-caught-up . "Du er ajour!")
 (:dashboard-all-caught-up-hint . "Oversæt mere for at udbygge din samling.")
 (:dashboard-quick-actions . "Hurtige handlinger")
 (:dashboard-getting-started . "Kom godt i gang")
 (:dashboard-tip-1 . "Oversæt tekst du vil lære")
 (:dashboard-tip-2 . "Klik \"Gem som flashcard\" på oversættelser du vil huske")
 (:dashboard-tip-3 . "Gentag dine flashcards regelmæssigt - spredt gentagelse hjælper dig med at huske langsigtet")
 (:dashboard-tip-4 . "Bedøm ærligt - det hjælper algoritmen med at planlægge dine gentagelser optimalt")

 ;; Account
 (:account-title . "Konto")
 (:account-subtitle . "Administrer dine kontoindstillinger og sletteplan.")
 (:account-deletion-title . "Sletning af konto")
 (:account-deletion-scheduled . "Din konto er planlagt til sletning den ~A.")
 (:account-deletion-cancel-hint . "Du kan annullere før denne dato for at beholde din konto.")
 (:account-deletion-cancel . "Annuller sletning")
 (:account-deletion-request . "Du kan anmode om sletning af kontoen når som helst. Sletning planlægges 14 dage efter bekræftelse. Hvis du fortryder efter sletning, kontakt support.")
 (:account-deletion-confirm . "Planlæg sletning af konto om 14 dage fra nu?")
 (:account-deletion-schedule . "Planlæg sletning")
 (:account-reminders-title . "E-mailpåmindelser")
 (:account-reminders-subtitle . "Styr påmindelser om gentagelse og fortsættelse for denne konto.")
 (:account-reminders-opt-out . "Fravælg påmindelser om gentagelse og fortsættelse")
 (:account-reminders-save . "Gem indstillinger")

 ;; Subscription
 (:subscribe-title . "Enkle priser")
 (:subscribe-choose-plan . "Vælg din plan")
 (:subscribe-start-today . "Begynd at lære i dag med en 7-dages gratis prøveperiode")
 (:subscribe-monthly . "Månedlig")
 (:subscribe-annual . "Årlig")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/måned")
 (:subscribe-per-year . "/år")
 (:subscribe-monthly-desc . "600 oversættelser om måneden")
 (:subscribe-unlimited-flashcards . "Ubegrænsede flashcards")
 (:subscribe-grammar-explanations . "Grammatikforklaringer")
 (:subscribe-spaced-repetition . "Spredt gentagelse")
 (:subscribe-annual-desc . "Spar €20 - to måneder gratis!")
 (:subscribe-cta . "Abonner")
 (:subscribe-success . "Abonnement gennemført!")
 (:subscribe-manage . "Administrer abonnement")
 (:subscribe-activated . "Abonnement aktiveret!")
 (:subscribe-thank-you . "Tak fordi du abonnerer. Din konto er nu aktiv.")
 (:subscribe-start-learning . "Begynd at lære")
 (:subscribe-management . "Abonnementsstyring")
 (:subscribe-active . "Aktivt abonnement")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Aktiv")
 (:subscribe-days-remaining . "Dage tilbage:")
 (:subscribe-renews-on . "Fornyes den:")
 (:subscribe-no-subscription . "Intet aktivt abonnement")
 (:subscribe-access-features . "Abonner for at få adgang til alle funktioner.")
 (:subscribe-view-plans . "Se planer")
 (:subscribe-faq-title . "Ofte stillede spørgsmål")
 (:subscribe-faq-trial-q . "Hvad sker der efter den gratis prøveperiode?")
 (:subscribe-faq-trial-a . "Efter din 7-dages gratis prøveperiode opkræves du for den valgte plan. Du kan annullere når som helst inden prøveperioden slutter.")
 (:subscribe-faq-cancel-q . "Kan jeg annullere når som helst?")
 (:subscribe-faq-cancel-a . "Ja! Du kan annullere dit abonnement når som helst. Du beholder adgangen indtil udgangen af din faktureringsperiode.")
 (:subscribe-faq-payment-q . "Hvilke betalingsmetoder accepterer I?")
 (:subscribe-faq-payment-a . "Vi accepterer alle større kredit- og debetkort gennem vores betalingspartner Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Noget gik galt")
 (:error-not-found . "Siden blev ikke fundet")
 (:error-unauthorized . "Log ind for at fortsætte")
 (:error-subscription-required . "Abonnement påkrævet")
 (:error-text-too-long . "Teksten er for lang. Maksimal oversættelseslængde er 120 tegn.")
 (:error-input-too-long . "Input for langt")
 (:error-unknown-source-lang . "Det valgte kildesprog understøttes ikke.")
 (:error-unknown-target-lang . "Det valgte målsprog understøttes ikke.")
 (:error-unknown-language . "Ukendt sprog")
 (:error-translation-unavailable . "Oversættelsestjenesten er midlertidigt utilgængelig. Prøv igen om et øjeblik.")
 (:error-translation-failed . "Oversættelse mislykkedes")
 (:error-translation-retry . "Kunne ikke generere en oversættelse efter flere forsøg. Prøv at omformulere din tekst.")
 (:error-quota-exceeded . "Oversættelsesgrænse nået")
 (:error-quota-exceeded-detail . "Du har brugt alle dine oversættelser for denne måned. Din kvote nulstilles automatisk hver måned.")
 (:quota-warning . "Oversættelser tilbage: ~A")
 (:quota-low-warning . "Kun ~A oversættelser tilbage. Overvej at købe flere.")
 (:top-up-button . "Køb flere oversættelser")
 (:top-up-success . "Opfyldning succesfuld! Du har nu ~A yderligere oversættelser.")
 (:top-up-price . "€5")
 (:top-up-amount . "300 oversættelser")
 (:loading . "Indlæser...")
 (:empty-state . "Intet her endnu")

 ;; Institutions
 (:institutions-page-title . "Hiisi til skoler - institutionelle licenser")
 (:institutions-hero-title . "Hiisi til skoler")
 (:institutions-hero-subtitle . "Giv dine studerende AI-understøttet sprogindlæring")
 (:institutions-section-title . "Institutionelle licenser")
 (:institutions-section-body . "Vi tilbyder volumenlicenser til skoler, universiteter og sprogskoler. Studerende med e-mailadresser fra dit domæne får automatisk fuld adgang.")
 (:institutions-benefit-1 . "Automatisk tilmelding for studerende med institutionel e-mail")
 (:institutions-benefit-2 . "Ingen individuelle studiekonti at administrere")
 (:institutions-benefit-3 . "Fleksible faktureringsmuligheder")
 (:institutions-benefit-4 . "Dedikeret support til undervisere")
 (:institutions-request-title . "Anmod om en licens")
 (:institutions-request-subtitle . "Udfyld formularen nedenfor, så vender vi tilbage inden for 2 arbejdsdage.")
 (:institutions-field-name . "Institutionsnavn")
 (:institutions-field-name-placeholder . "Københavns Universitet")
 (:institutions-field-contact-name . "Kontaktperson")
 (:institutions-field-contact-name-placeholder . "Dit navn")
 (:institutions-field-contact-email . "Kontakt-e-mail")
 (:institutions-field-contact-email-placeholder . "dig@universitet.dk")
 (:institutions-field-domains . "E-maildomæner")
 (:institutions-field-domains-placeholder . "universitet.dk, cs.universitet.dk")
 (:institutions-field-domains-help . "Kommasepareret liste over e-maildomæner for din institution")
 (:institutions-field-notes . "Yderligere oplysninger")
 (:institutions-field-notes-placeholder . "Estimeret antal studerende, foretrukken faktureringscyklus, særlige krav...")
 (:institutions-submit . "Send forespørgsel")
 (:institutions-success-title . "Tak - Hiisi til skoler")
 (:institutions-success-heading . "Tak!")
 (:institutions-success-body . "Vi har modtaget din forespørgsel om en institutionel licens. Vores team vil gennemgå din anmodning og vende tilbage inden for 2 arbejdsdage.")
 (:institutions-success-back . "Tilbage til forsiden")

 ;; Footer
 (:footer-privacy . "Privatlivspolitik")
 (:footer-terms . "Servicevilkår")
 (:footer-contact . "Kontakt")

 ;; Early software notice
 (:early-software-notice . "Hiisi er under tidlig udvikling. Fundet en fejl eller har du et forslag?")
 (:early-software-contact . "Kontakt os på")

 ;; Privatlivspolitik
 (:privacy-title . "Privatlivspolitik")
 (:privacy-updated . "Sidst opdateret: januar 2026")
 (:privacy-who-title . "Hvem vi er")
 (:privacy-who-body . "Hiisi drives af Lambda Symbolics OÜ, et selskab registreret i Estland. Som estisk virksomhed overholder vi EU's generelle databeskyttelsesforordning (GDPR).")
 (:privacy-collect-title . "Data vi indsamler")
 (:privacy-collect-intro . "Når du bruger Hiisi, indsamler vi følgende oplysninger:")
 (:privacy-collect-account-key . "Kontooplysninger: ")
 (:privacy-collect-account-val . "E-mailadresse, vist navn og en sikkert hashet adgangskode.")
 (:privacy-collect-learning-key . "Læringsdata: ")
 (:privacy-collect-learning-val . "Dine oversættelser, gemte flashkort og din repetitionshistorik.")
 (:privacy-collect-usage-key . "Brugsdata: ")
 (:privacy-collect-usage-val . "Grundlæggende serverlogs til sikkerhed og fejlfinding.")
 (:privacy-use-title . "Sådan bruger vi dine data")
 (:privacy-use-auth-key . "Autentificering: ")
 (:privacy-use-auth-val . "Til at bekræfte din identitet og beskytte din konto.")
 (:privacy-use-service-key . "Levering af tjenesten: ")
 (:privacy-use-service-val . "Til at levere oversættelser og administrere din flashkortsamling.")
 (:privacy-use-ai-key . "AI-oversættelser: ")
 (:privacy-use-ai-val . "Dine oversættelsesforespørgsler sendes til Anthropics Claude API for at generere svar. Se Anthropics privatlivspolitik for, hvordan de håndterer disse data.")
 (:privacy-third-title . "Tredjepartstjenester")
 (:privacy-third-intro . "Vi bruger følgende tredjepartstjenester:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "Til AI-baserede oversættelser.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "Til afsendelse af aktiveringsmails og transaktionsmails.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Til behandling af abonnementsbetalinger.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "Vi bruger kun nødvendige cookies:")
 (:privacy-cookies-auth-key . "Autentificeringstoken: ")
 (:privacy-cookies-auth-val . "En sikker HTTP-only cookie, som holder dig logget ind.")
 (:privacy-cookies-lang-key . "Sprogpræference: ")
 (:privacy-cookies-lang-val . "Til at huske dit foretrukne sprog i brugerfladen.")
 (:privacy-retention-title . "Opbevaring af data")
 (:privacy-retention-body . "Dine data gemmes, så længe du har en konto. Når du anmoder om sletning, planlægges din konto til sletning om 14 dage.")
 (:privacy-rights-title . "Dine rettigheder (GDPR)")
 (:privacy-rights-intro . "Under GDPR har du ret til at:")
 (:privacy-rights-access . "Få adgang til dine personoplysninger")
 (:privacy-rights-export . "Eksportere dine data (tilgængeligt på /app/api/export)")
 (:privacy-rights-correct . "Anmode om rettelse af unøjagtige data")
 (:privacy-rights-delete . "Anmode om sletning af din konto og dine data")
 (:privacy-rights-object . "Gøre indsigelse mod behandling af dine data")
 (:privacy-rights-contact . "For at udøve disse rettigheder, kontakt os på")
 (:privacy-contact-title . "Kontakt")
 (:privacy-contact-intro . "Ved spørgsmål om privatliv:")
 (:privacy-contact-email-label . "E-mail: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Estland")

 ;; Brugsvilkår
 (:terms-title . "Brugsvilkår")
 (:terms-updated . "Sidst opdateret: januar 2026")
 (:terms-1-title . "1. Tjenestebeskrivelse")
 (:terms-1-body . "Hiisi er en sproglæringsapp, der tilbyder AI-baserede oversættelser med grammatiske forklaringer og flashkort med distribueret repetition. Tjenesten drives af Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Oprettelse af konto")
 (:terms-2-body . "For at bruge Hiisi skal du oprette en konto med en gyldig e-mailadresse. Du er ansvarlig for sikkerheden af dine loginoplysninger.")
 (:terms-3-title . "3. Abonnement og betaling")
 (:terms-3-body . "Hiisi tilbyder betalte abonnementer (månedligt og årligt). Abonnementer behandles gennem Polar.sh.")
 (:terms-3-list-1 . "Abonnementer fornyes automatisk, medmindre de opsiges før fornyelsesdatoen.")
 (:terms-3-list-2 . "Refundering sker i overensstemmelse med gældende forbrugerbeskyttelseslovgivning.")
 (:terms-3-list-3 . "Manglende betaling medfører tab af adgang til premiumfunktioner.")
 (:terms-4-title . "4. Tilladt brug")
 (:terms-4-intro . "Du accepterer, at du ikke må:")
 (:terms-4-list-1 . "Bruge tjenesten til ulovlige formål")
 (:terms-4-list-2 . "Forsøge at omgå brugsgrænser eller sikkerhedsforanstaltninger")
 (:terms-4-list-3 . "Dele dine kontooplysninger med andre")
 (:terms-4-list-4 . "Bruge automatiserede værktøjer på en måde, der forringer ydelsen for andre")
 (:terms-5-title . "5. Indhold og immaterielle rettigheder")
 (:terms-5-body-1 . "Oversættelser genereret af Hiisi er skabt med AI og er muligvis ikke unikke. Du må bruge dine oversættelser og flashkort til personlige formål, men du har ikke eksklusive ophavsrettigheder til AI-genereret indhold.")
 (:terms-5-body-2 . "Hiisi-applikationen, branding og originalt indhold forbliver Lambda Symbolics OÜ's ejendom.")
 (:terms-6-title . "6. Tjenestens tilgængelighed")
 (:terms-6-intro . "Hiisi leveres \"som den er\". Vi garanterer ikke:")
 (:terms-6-list-1 . "Uafbrudt eller fejlfri tjeneste")
 (:terms-6-list-2 . "Nøjagtigheden af AI-genererede oversættelser")
 (:terms-6-list-3 . "Tilgængeligheden af bestemte funktioner")
 (:terms-6-body . "Vi kan til enhver tid ændre eller afvikle funktioner.")
 (:terms-7-title . "7. Ansvarsbegrænsning")
 (:terms-7-body-1 . "I det omfang loven tillader det, er Lambda Symbolics OÜ ikke ansvarlig for indirekte, tilfældige, særlige eller afledte skader, der opstår ved brug af Hiisi.")
 (:terms-7-body-2 . "Vores samlede ansvar overstiger ikke det beløb, du har betalt for tjenesten i de 12 måneder før kravet.")
 (:terms-8-title . "8. Lukning af konto")
 (:terms-8-body-1 . "Vi kan suspendere eller afslutte din konto, hvis du overtræder disse vilkår. Du kan til enhver tid anmode om sletning af konto i applikationen.")
 (:terms-8-body-2 . "Ved anmodning om sletning planlægges din konto til sletning om 14 dage.")
 (:terms-9-title . "9. Ændringer af vilkår")
 (:terms-9-body . "Vi kan opdatere disse vilkår fra tid til anden. Fortsat brug af Hiisi efter ændringer udgør accept af de nye vilkår.")
 (:terms-10-title . "10. Lovvalg")
 (:terms-10-body . "Disse vilkår er underlagt estisk lov. Eventuelle tvister afgøres ved domstolene i Estland.")
 (:terms-contact-title . "Kontakt")
 (:terms-contact-intro . "Ved spørgsmål om disse vilkår:")
 (:terms-contact-email-label . "E-mail: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Estland")



 ;; Decks
 (:decks-title . "Kortbunker")
 (:decks-subtitle . "Opret brugerdefinerede kortbunker og del dem med andre.")
 (:decks-create-title . "Opret kortbunke")
 (:decks-name-placeholder . "Kortbunkens navn")
 (:decks-desc-placeholder . "Beskrivelse")
 (:decks-create-btn . "Opret kortbunke")
 (:decks-edit-title . "Redigér kortbunke")
 (:decks-edit-btn . "Redigér kortbunke")
 (:decks-update-btn . "Gem ændringer")
 (:decks-default-badge . "Automatisk")
 (:decks-default-description . "Denne kortbunke administreres automatisk for dette sprogpar.")
 (:decks-default-readonly . "Automatiske kortbunker har faste navne og beskrivelser.")
 (:decks-error-name-required . "Navn på kortbunken er påkrævet.")
 (:decks-error-name-too-long . "Navnet på kortbunken må højst være ~A tegn.")
 (:decks-error-desc-too-long . "Beskrivelsen af kortbunken må højst være ~A tegn.")
 (:decks-error-default-readonly . "Automatiske kortbunker kan ikke redigeres.")
 (:decks-your-title . "Dine kortbunker")
 (:decks-col-name . "Navn")
 (:decks-col-desc . "Beskrivelse")
 (:decks-col-updated . "Opdateret")
 (:decks-col-actions . "Handlinger")
 (:decks-no-decks . "Ingen kortbunker endnu.")
 (:decks-open-btn . "Åbn")
 (:decks-no-desc . "Ingen beskrivelse.")
 (:decks-share-title . "Delingslink")
 (:decks-share-info . "Alle med dette link kan importere kortbunken:")
 (:decks-share-copy . "Kopiér link")
 (:decks-share-copied . "Kopieret")
 (:decks-add-from-flashcards-title . "Tilføj oversættelser")
 (:decks-add-from-flashcards-info . "Vælg et kort for at tilføje dets oversættelse til denne kortbunke.")
 (:decks-open-flashcards . "Tilføj fra kort")
 (:decks-filter-from . "Kildesprog")
 (:decks-filter-to . "Målsprog")
 (:decks-filter-any . "Alle sprog")
 (:decks-filter-include-assigned . "Inkludér kort, der allerede er i en kortbunke")
 (:decks-flashcards-col-from . "Fra")
 (:decks-flashcards-col-to . "Til")
 (:decks-flashcards-add . "Tilføj")
 (:decks-flashcards-added . "Tilføjet")
 (:decks-flashcards-in-deck . "I en anden kortbunke")
 (:decks-flashcards-empty . "Ingen kort matcher disse filtre.")
 (:decks-add-trans-title . "Tilføj oversættelse")
 (:decks-trans-id-placeholder . "Oversættelses-ID")
 (:decks-add-trans-btn . "Tilføj oversættelse")
 (:decks-items-title . "Kortbunkens indhold")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Oversættelse")
 (:decks-col-lang . "Målsprog")
 (:decks-no-items . "Ingen elementer endnu.")
 (:decks-share-page-title . "Del kortbunke")
 (:decks-share-preview . "Forhåndsvis og importer denne kortbunke.")
 (:decks-import-title . "Importer")
 (:decks-import-btn . "Importer kortbunke")

 ;; Flashcards management page
 (:flashcards-title . "Mine kort")
 (:flashcards-subtitle . "Alle dine gemte kort på ét sted. Søg, organiser og administrer.")
 (:flashcards-search-placeholder . "Søg i kort...")
 (:flashcards-hide-perfected . "Skjul fuldt indlærte kort")
 (:flashcards-col-original . "Original")
 (:flashcards-col-translated . "Oversættelse")
 (:flashcards-col-lang . "Sprog")
 (:flashcards-no-cards . "Ingen kort endnu. Begynd at oversætte for at oprette nogle!")

 ;; API errors
 (:api-error-missing-text . "Manglende tekst til oversættelse.")
 (:api-error-invalid-translation-id . "Ugyldigt oversættelses-ID.")
 (:api-error-translation-not-found . "Oversættelsen, du forsøgte at gemme, findes ikke længere.")
 (:api-error-invalid-bookmark-id . "Ugyldigt bogmærke-ID")
 (:api-error-bookmark-not-found . "Bogmærke ikke fundet")
 (:api-error-forbidden . "Forbudt")
 (:api-error-failed-delete-bookmark . "Kunne ikke slette bogmærke")
 (:api-error-invalid-flashcard-id . "Ugyldigt flashkort-ID")
 (:api-error-missing-deck-id . "Manglende kortbunke-ID")
 (:api-error-flashcard-not-found . "Flashkort ikke fundet")
 (:api-error-deck-not-found . "Kortbunke ikke fundet")
 (:api-error-deck-name-required . "Kortbunkenavn er påkrævet")
 (:api-error-session-expired . "Din repetitionssession er udløbet. Start venligst en ny session.")
 (:api-error-invalid-card-id . "Ugyldigt kort-ID.")
 (:api-error-invalid-rating . "Ugyldig vurdering.")
 (:api-error-rating-range . "Vurdering skal være mellem 0 og 5.")
 (:api-error-card-not-found . "Kort ikke fundet.")
 (:api-error-permission-denied . "Du har ikke tilladelse til at repetere dette kort.")
 (:api-error-unknown-source-lang . "Ukendt kildesprog.")
 (:api-error-unknown-target-lang . "Ukendt målsprog.")
 (:api-error-failed-add-to-deck . "Kunne ikke tilføje til kortbunke")

 ;; API success messages
 (:api-success-added . "Tilføjet!")
 (:api-success-added-simple . "Tilføjet")

 ;; API stats
 (:api-stats-due . "~A forfalder")
 (:api-stats-total . "~A i alt")

 ;; Time units
 (:api-time-day . "dag")
 (:api-time-days . "dage")
 (:api-time-day-left . "dag tilbage")
 (:api-time-days-left . "dage tilbage")

 ;; Subscription status
 (:api-subscription-active . "Aktiv")
 (:api-subscription-inactive . "Inaktiv")
 (:api-subscription-subscribe-hint . "Abonnér for at låse oversættelser op")

 ;; Generic status
 (:status-bad-request . "Ugyldig anmodning")
 (:status-not-found . "Ikke fundet")
 (:status-forbidden . "Forbudt")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Lær sprog grundigt")
 (:landing-hero-subheadline . "Få oversættelser med fuld grammatisk analyse og opbyg et varigt ordforråd gennem flashkort med distribueret repetition.")
 (:landing-hero-trust-line . "7 dages gratis prøveperiode med 100 oversættelser. Opsig når som helst.")
 (:landing-credibility-languages . "14 sprog")
 (:landing-credibility-ai . "Grammatisk analyse inkluderet")
 (:landing-credibility-origin . "Lavet i Estland")
 (:landing-step-1-title . "Oversæt enhver tekst")
 (:landing-step-1-desc . "Indtast et ord eller en sætning. Få en oversættelse med fuld grammatisk analyse.")
 (:landing-step-2-title . "Gem som flashkort")
 (:landing-step-2-desc . "Gem de oversættelser, du vil huske. Flashkort oprettes automatisk.")
 (:landing-step-3-title . "Repetér og husk")
 (:landing-step-3-desc . "Distribueret repetition planlægger gennemgange på det perfekte tidspunkt for langtidshukommelsen.")
 (:landing-feature-grammar-title . "Forstå grammatik, ikke kun ord")
 (:landing-feature-grammar-desc . "Hver oversættelse indeholder en detaljeret grammatisk analyse - ordformer, kasus og bøjninger forklaret på dit sprog.")
 (:landing-feature-srs-title . "Videnskabeligt baseret memorering")
 (:landing-feature-srs-desc . "SM-2-algoritmen tilpasser sig din præstation. Svære kort vises oftere. Kort, du kan, træder i baggrunden.")
 (:landing-feature-share-title . "Del kortbunker med elever")
 (:landing-feature-share-desc . "Lærere kan oprette egne kortbunker og dele dem med et link. Elever importerer kortbunken og begynder at repetere med det samme.")
 (:landing-pricing-trial-note . "Inkluderer 7 dages gratis prøveperiode")
 (:landing-pricing-monthly-after . "7 dage gratis, derefter ~A/måned")
 (:landing-pricing-annual-after . "7 dage gratis, derefter ~A/år")
 (:landing-faq-title . "Ofte stillede spørgsmål")
 (:landing-faq-trial-cap-q . "Hvor mange oversættelser får jeg under prøveperioden?")
 (:landing-faq-trial-cap-a . "Du får 100 oversættelser i din 7-dages prøveperiode. Efter abonnement får du 600 om måneden.")
 (:landing-final-cta-title . "Begynd at lære i dag")
 (:landing-final-cta-subtitle . "Bliv en del af Hiisi og begynd at opbygge ordforråd, der holder.")

 ;; Trial status (in-app)
 (:trial-status . "Gratis prøveperiode")
 (:trial-days-remaining . "~A dage tilbage")
 (:trial-translations-used . "~A/100 oversættelser brugt")
 (:trial-upgrade-prompt . "Opgrader for at fortsætte med at oversætte")
 (:trial-expired . "Din gratis prøveperiode er udløbet")
 (:trial-expired-detail . "Abonner for at fortsætte med at lære med Hiisi.")
 (:trial-quota-warning . "~A prøveoversættelser tilbage (~A dage). Abonner for 600/måned.")
 (:trial-quota-exceeded . "Grænse for prøveoversættelser nået. Abonner for at fortsætte.")
 (:error-trial-quota-exceeded . "Grænse for prøveoversættelser nået")
 (:error-trial-quota-detail . "Du har brugt alle 100 prøveoversættelser. Abonner for at fortsætte med at lære.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Opret flashkort")
 (:custom-flashcard-edit-title . "Rediger flashkort")
 (:custom-flashcard-original . "Originaltekst")
 (:custom-flashcard-translated . "Oversættelse")
 (:custom-flashcard-lang-from . "Kildesprog")
 (:custom-flashcard-lang-to . "Målsprog")
 (:custom-flashcard-note . "Pædagogisk note")
 (:custom-flashcard-forms . "Grammatisk analyse")
 (:custom-flashcard-form-term . "Begreb")
 (:custom-flashcard-form-explanation . "Forklaring")
 (:custom-flashcard-add-form . "Tilføj grammatisk begreb")
 (:custom-flashcard-remove-form . "Fjern")
 (:custom-flashcard-ai-fill . "Udfyld med AI")
 (:custom-flashcard-ai-fill-all . "Udfyld alt med AI")
 (:custom-flashcard-ai-fill-translation . "Oversæt med AI")
 (:custom-flashcard-ai-fill-breakdown . "Generer analyse")
 (:custom-flashcard-ai-fill-note . "Generer note")
 (:custom-flashcard-create-btn . "Opret flashkort")
 (:custom-flashcard-update-btn . "Gem ændringer")
 (:custom-flashcard-delete-btn . "Slet flashkort")
 (:custom-flashcard-delete-confirm . "Er du sikker på, at du vil slette dette flashkort?")
 (:custom-flashcard-created . "Flashkort oprettet")
 (:custom-flashcard-updated . "Flashkort opdateret")
 (:custom-flashcard-deleted . "Flashkort slettet")
 (:custom-flashcard-add-to-deck . "Tilføj til kortbunke")
 (:custom-flashcard-not-found . "Flashkort ikke fundet")
 (:custom-flashcard-not-owner . "Du kan kun redigere flashkort, du selv har oprettet")
 (:custom-flashcard-ai-generating . "Genererer med AI...")
 (:custom-flashcard-badge . "Tilpasset")

 ;; Problemrapportering
 (:issues-open-button . "Rapportér et problem")
 (:issues-modal-title . "Rapportér et problem")
 (:issues-modal-subtitle . "Beskriv, hvad der gik galt. Vi vedhæfter automatisk den aktuelle side.")
 (:issues-title-label . "Kort titel")
 (:issues-title-placeholder . "Kort opsummering af problemet")
 (:issues-message-label . "Hvad skete der?")
 (:issues-message-placeholder . "Angiv trin til at genskabe, forventet adfærd og hvad der skete i stedet.")
 (:issues-submit . "Send rapport")
 (:issues-cancel . "Annullér")
 (:issues-success . "Tak. Din problemrapport er sendt.")
 (:issues-error-required . "Beskriv problemet, før du sender.")
 (:issues-error-title-too-long . "Sagens titel er for lang. Hold den under 160 tegn.")
 (:issues-error-too-long . "Rapportteksten er for lang. Hold den under 4000 tegn.")
 (:issues-error-rate-limit . "For mange rapporter fra denne kilde. Vent og prøv igen senere.")
 (:issues-error-generic . "Problemrapporten kunne ikke sendes. Prøv igen.")

)
