;;; Danish translations
;;; This file mirrors the structure of en.lisp

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Dansk")
 (:lang-flag . "🇩🇰")

 ;; Navigation
 (:nav-translate . "Oversæt")
 (:nav-review . "Gentag")
 (:nav-dashboard . "Oversigt")
 (:nav-logout . "Log ud")
 (:nav-home . "Hjem")
 (:nav-pricing . "Priser")
 (:nav-export-data . "Eksporter data")

 ;; App title and branding
 (:app-title . "Hiisi")
 (:app-tagline . "Lær sprog gennem oversættelser")

 ;; Landing page
 (:landing-hero-title . "Mestre ethvert sprog")
 (:landing-hero-subtitle . "Oversæt hvad som helst. Generer automatisk flashcards der lærer dig hvorfor det fungerer sådan.")
 (:landing-cta . "Begynd at lære")
 (:landing-learn-more . "Læs mere")
 (:landing-how-it-works . "Sådan fungerer det")
 (:landing-feature-1-title . "Automatiske flashcards")
 (:landing-feature-1-desc . "Hver oversættelse genererer automatisk flashcards med grammatisk analyse. Ingen manuel oprettelse af kort.")
 (:landing-feature-2-title . "Spredt gentagelse")
 (:landing-feature-2-desc . "SM-2-algoritmen planlægger gentagelser med optimale intervaller. Lær effektivt, husk permanent.")
 (:landing-feature-3-title . "Grammatikundervisning")
 (:landing-feature-3-desc . "Hver oversættelse forklarer grammatik, ordstammer og sætningsstruktur. Forstå hvorfor, ikke kun hvad.")
 (:landing-free-trial . "7 dages gratis prøveperiode. Intet kreditkort påkrævet.")
 (:landing-start-trial . "Start gratis prøveperiode")
 (:landing-best-value . "Bedste værdi")
 (:landing-cta-title . "Klar til at lære sprog gennem grammatik, ikke udenadslære?")
 (:landing-cta-subtitle . "Hver oversættelse bliver en læringsmulighed. Hvert flashcard lærer dig hvorfor.")
 (:landing-signup-free . "Tilmeld dig gratis")

 ;; Auth pages
 (:auth-register . "Registrer")
 (:auth-login . "Log ind")
 (:auth-logout . "Log ud")
 (:auth-email . "E-mail")
 (:auth-password . "Adgangskode")
 (:auth-password-again . "Bekræft adgangskode")
 (:auth-display-name . "Visningsnavn")
 (:auth-register-title . "Registrer dig på Hiisi")
 (:auth-register-subtitle . "Opret en ny konto")
 (:auth-login-title . "Log ind på Hiisi")
 (:auth-login-subtitle . "Indtast dine oplysninger")
 (:auth-forgot-password . "Glemt adgangskode?")
 (:auth-no-account . "Har du ikke en konto?")
 (:auth-have-account . "Har du allerede en konto?")
 (:auth-google . "Google")
 (:auth-account-created . "Konto oprettet!")
 (:auth-check-email . "Tjek din e-mail for aktiveringslinket.")
 (:auth-redirect-login . "Omdirigerer til login om")
 (:auth-seconds . "sekunder...")
 (:auth-go-now . "Gå nu")
 (:auth-not-activated . "Konto ikke aktiveret")
 (:auth-activate-title . "Aktiver din konto!")
 (:auth-activated . "Konto aktiveret!")
 (:auth-activated-message . "Din konto er blevet aktiveret. Du kan nu bruge Hiisi.")
 (:auth-redirecting . "Omdirigerer om")
 (:auth-go-to-app . "Gå til appen")
 (:auth-resend-title . "Gensend aktiveringsmail")
 (:auth-resend-subtitle . "Indtast din e-mail for at modtage et nyt aktiveringslink.")
 (:auth-resend-button . "Gensend aktiveringsmail")
 (:auth-resend-success . "Aktiveringsmail sendt!")
 (:auth-resend-success-detail . "Tjek din indbakke for det nye aktiveringslink.")
 (:auth-resend-rate-limited . "Vent venligst et par minutter før du anmoder om en ny aktiveringsmail.")
 (:auth-resend-cooldown . "Du kan anmode om en ny mail om ~a sekunder.")
 (:auth-back-to-login . "Tilbage til login")
 (:auth-forgot-password-title . "Glemt adgangskode")
 (:auth-forgot-password-subtitle . "Indtast din e-mail, så sender vi dig et link til at nulstille din adgangskode.")
 (:auth-send-reset-link . "Send nulstillingslink")
 (:auth-reset-email-sent . "Nulstillingslink sendt!")
 (:auth-reset-email-sent-detail . "Hvis en konto findes med den e-mail, vil du snart modtage et link til nulstilling af adgangskoden.")
 (:auth-reset-rate-limited . "Vent venligst et par minutter før du anmoder om en ny nulstilling af adgangskoden.")
 (:auth-reset-invalid-token . "Dette nulstillingslink er ugyldigt eller udløbet.")
 (:auth-reset-password-title . "Nulstil adgangskode")
 (:auth-reset-password-subtitle . "Indtast din nye adgangskode nedenfor.")
 (:auth-new-password . "Ny adgangskode")
 (:auth-confirm-new-password . "Bekræft ny adgangskode")
 (:auth-reset-password . "Nulstil adgangskode")
 (:auth-password-changed . "Adgangskode ændret!")
 (:auth-password-changed-detail . "Din adgangskode er blevet ændret. Du kan nu logge ind med din nye adgangskode.")
 (:auth-change-password-title . "Skift adgangskode")
 (:auth-change-password-subtitle . "Opdater din kontos adgangskode.")
 (:auth-current-password . "Nuværende adgangskode")
 (:auth-change-password . "Skift adgangskode")
 (:auth-back-to-app . "Tilbage til appen")
 (:auth-password-updated . "Adgangskode opdateret!")
 (:auth-password-updated-detail . "Din adgangskode er blevet opdateret.")

 ;; Translation page
 (:translate-title . "Oversæt")
 (:translate-input-label . "Tekst at oversætte")
 (:translate-input-placeholder . "Indtast tekst at oversætte...")
 (:translate-from . "Fra:")
 (:translate-to . "Til:")
 (:translate-submit . "Oversæt")
 (:translate-save . "Gem som flashcard")
 (:translate-saved . "Gemt!")
 (:translate-like . "Synes godt om")
 (:translate-dislike . "Synes ikke om")
 (:translate-char-limit . "tegn tilbage")
 (:translate-auto-detect . "Alle (Automatisk)")
 (:translate-empty-state . "Indtast tekst ovenfor og klik Oversæt for at se resultatet med grammatisk analyse")
 (:translate-like-tooltip . "God oversættelse")
 (:translate-dislike-tooltip . "Dårlig oversættelse - anmod om en ny")
 (:translate-dislike-confirm . "Dette genererer en ny oversættelse. Fortsæt?")
 (:translate-liked . "Kan lide!")

 ;; Flashcard review
 (:review-title . "Gentag")
 (:review-session-title . "Gentagelsessession")
 (:review-session-subtitle . "Øv dine gemte flashcards")
 (:review-start . "Start gentagelse")
 (:review-no-cards . "Ingen kort at gentage")
 (:review-no-cards-desc . "Du har ingen flashcards der skal gentages lige nu.")
 (:review-no-cards-hint . "Oversæt noget tekst og klik \"Gem som flashcard\" for at opbygge din samling!")
 (:review-start-translating . "Begynd at oversætte")
 (:review-show-answer . "Vis svar")
 (:review-click-reveal . "Klik for at vise svar")
 (:review-grammar-breakdown . "Grammatisk analyse")
 (:review-how-well . "Hvor godt huskede du?")
 (:review-again . "Igen")
 (:review-hard . "Svært")
 (:review-good . "Godt")
 (:review-easy . "Nemt")
 (:review-progress . "Kort ~a af ~a")
 (:review-complete . "Session fuldført!")
 (:review-complete-msg . "Du gennemgik ~a kort")
 (:review-correct . "Korrekt")
 (:review-accuracy . "Præcision")
 (:review-again-btn . "Gentag igen")
 (:review-translate-more . "Oversæt mere")
 (:review-streak . "dages række")

 ;; Dashboard
 (:dashboard-title . "Oversigt")
 (:dashboard-cards-due . "Kort for i dag")
 (:dashboard-total-cards . "Kort i alt")
 (:dashboard-subscription . "Abonnement")
 (:dashboard-subscribed-until . "Abonnerer til")
 (:dashboard-not-subscribed . "Ikke abonneret")
 (:dashboard-recent . "Seneste oversættelser")
 (:dashboard-no-translations . "Ingen oversættelser endnu")
 (:dashboard-streak . "Gentagelsesrække")
 (:dashboard-days . "dage")
 (:dashboard-quick-actions . "Hurtige handlinger")
 (:dashboard-getting-started . "Kom godt i gang")
 (:dashboard-tip-1 . "Oversæt tekst du vil lære")
 (:dashboard-tip-2 . "Klik \"Gem som flashcard\" på oversættelser du vil huske")
 (:dashboard-tip-3 . "Gentag dine flashcards regelmæssigt - spredt gentagelse hjælper dig med at huske langsigtet")
 (:dashboard-tip-4 . "Bedøm ærligt - det hjælper algoritmen med at planlægge dine gentagelser optimalt")

 ;; Subscription
 (:subscribe-title . "Enkle priser")
 (:subscribe-choose-plan . "Vælg din plan")
 (:subscribe-start-today . "Begynd at lære i dag med en 7-dages gratis prøveperiode")
 (:subscribe-monthly . "Månedlig")
 (:subscribe-annual . "Årlig")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/måned")
 (:subscribe-per-year . "/år")
 (:subscribe-monthly-desc . "600 oversættelser om måneden")
 (:subscribe-unlimited-flashcards . "Ubegrænsede flashcards")
 (:subscribe-grammar-explanations . "Grammatikforklaringer")
 (:subscribe-spaced-repetition . "Spredt gentagelse")
 (:subscribe-annual-desc . "Spar €20 - to måneder gratis!")
 (:subscribe-cta . "Abonner")
 (:subscribe-success . "Abonnement gennemført!")
 (:subscribe-manage . "Administrer abonnement")
 (:subscribe-activated . "Abonnement aktiveret!")
 (:subscribe-thank-you . "Tak fordi du abonnerer. Din konto er nu aktiv.")
 (:subscribe-start-learning . "Begynd at lære")
 (:subscribe-management . "Abonnementsstyring")
 (:subscribe-active . "Aktivt abonnement")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Aktiv")
 (:subscribe-days-remaining . "Dage tilbage:")
 (:subscribe-renews-on . "Fornyes den:")
 (:subscribe-no-subscription . "Intet aktivt abonnement")
 (:subscribe-access-features . "Abonner for at få adgang til alle funktioner.")
 (:subscribe-view-plans . "Se planer")
 (:subscribe-faq-title . "Ofte stillede spørgsmål")
 (:subscribe-faq-trial-q . "Hvad sker der efter den gratis prøveperiode?")
 (:subscribe-faq-trial-a . "Efter din 7-dages gratis prøveperiode opkræves du for den valgte plan. Du kan annullere når som helst inden prøveperioden slutter.")
 (:subscribe-faq-cancel-q . "Kan jeg annullere når som helst?")
 (:subscribe-faq-cancel-a . "Ja! Du kan annullere dit abonnement når som helst. Du beholder adgangen indtil udgangen af din faktureringsperiode.")
 (:subscribe-faq-payment-q . "Hvilke betalingsmetoder accepterer I?")
 (:subscribe-faq-payment-a . "Vi accepterer alle større kredit- og debetkort gennem vores betalingspartner Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Noget gik galt")
 (:error-not-found . "Siden blev ikke fundet")
 (:error-unauthorized . "Log ind for at fortsætte")
 (:error-subscription-required . "Abonnement påkrævet")
 (:error-text-too-long . "Teksten er for lang. Maksimal oversættelseslængde er 120 tegn.")
 (:error-input-too-long . "Input for langt")
 (:error-unknown-source-lang . "Det valgte kildesprog understøttes ikke.")
 (:error-unknown-target-lang . "Det valgte målsprog understøttes ikke.")
 (:error-unknown-language . "Ukendt sprog")
 (:error-translation-unavailable . "Oversættelsestjenesten er midlertidigt utilgængelig. Prøv igen om et øjeblik.")
 (:error-translation-failed . "Oversættelse mislykkedes")
 (:error-translation-retry . "Kunne ikke generere en oversættelse efter flere forsøg. Prøv at omformulere din tekst.")
 (:error-quota-exceeded . "Oversættelsesgrænse nået")
 (:error-quota-exceeded-detail . "Du har brugt alle dine oversættelser for denne måned. Din kvote nulstilles automatisk hver måned.")
 (:loading . "Indlæser...")
 (:empty-state . "Intet her endnu")

 ;; Footer
 (:footer-privacy . "Privatlivspolitik")
 (:footer-terms . "Servicevilkår")
 (:footer-contact . "Kontakt")

 ;; Early software notice
 (:early-software-notice . "Hiisi er under tidlig udvikling. Fundet en fejl eller har du et forslag?")
 (:early-software-contact . "Kontakt os på")
)
