;;; German translations
;;; This file must contain all keys from en.lisp

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Deutsch")
 (:lang-flag . "🇩🇪")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Wähle deine Sprache")
 (:lang-modal-subtitle . "Wähle deine bevorzugte Sprache für die Benutzeroberfläche:")

 ;; Navigation
 (:nav-translate . "Übersetzen")
 (:nav-review . "Wiederholen")
 (:nav-flashcards . "Meine Karten")
 (:nav-dashboard . "Dashboard")
 (:nav-decks . "Decks")
 (:nav-logout . "Abmelden")
 (:nav-home . "Startseite")
 (:nav-pricing . "Preise")
 (:nav-export-data . "Daten exportieren")

 ;; App title and branding
 (:app-title . "Hiisi - Sprachenlernen")
 (:app-tagline . "Sprachen lernen durch Übersetzungen")

 ;; Landing page
 (:landing-hero-title . "Jede Sprache meistern")
 (:landing-hero-subtitle . "Übersetze alles. Generiere automatisch Karteikarten, die dir erklären, warum es so funktioniert.")
 (:landing-cta . "Jetzt lernen")
 (:landing-learn-more . "Mehr erfahren")
 (:landing-how-it-works . "So funktioniert's")
 (:landing-feature-1-title . "Automatische Karteikarten")
 (:landing-feature-1-desc . "Jede Übersetzung generiert automatisch Karteikarten mit Grammatikanalyse. Keine manuelle Kartenerstellung.")
 (:landing-feature-2-title . "Spaced Repetition")
 (:landing-feature-2-desc . "Der SM-2 Algorithmus plant Wiederholungen in optimalen Abständen. Effizient lernen, dauerhaft behalten.")
 (:landing-feature-3-title . "Grammatik verstehen")
 (:landing-feature-3-desc . "Jede Übersetzung erklärt Grammatik, Wortstämme und Satzstruktur. Verstehe das Warum, nicht nur das Was.")
 (:landing-free-trial . "7 Tage kostenlos testen.")
 (:landing-start-trial . "Kostenlos testen")
 (:landing-best-value . "Bestes Angebot")
 (:landing-cta-title . "Bereit, Sprachen durch Grammatik statt Auswendiglernen zu lernen?")
 (:landing-cta-subtitle . "Jede Übersetzung wird zur Lernmöglichkeit. Jede Karteikarte erklärt dir das Warum.")
 (:landing-signup-free . "Kostenlos registrieren")

 ;; Auth pages
 (:auth-register . "Registrieren")
 (:auth-login . "Anmelden")
 (:auth-logout . "Abmelden")
 (:auth-email . "E-Mail")
 (:auth-password . "Passwort")
 (:auth-password-again . "Passwort bestätigen")
 (:auth-display-name . "Anzeigename")
 (:auth-register-title . "Bei Hiisi registrieren")
 (:auth-register-subtitle . "Neues Konto erstellen")
 (:auth-login-title . "Bei Hiisi anmelden")
 (:auth-login-subtitle . "Anmeldedaten eingeben")
 (:auth-login-invalid-credentials . "Ungültige E-Mail oder ungültiges Passwort.")
 (:auth-login-rate-limited . "Zu viele Anmeldeversuche. Bitte warte ein paar Minuten und versuche es erneut.")
 (:auth-forgot-password . "Passwort vergessen?")
 (:auth-no-account . "Noch kein Konto?")
 (:auth-have-account . "Bereits ein Konto?")
 (:auth-google . "Google")
 (:auth-account-created . "Konto erstellt!")
 (:auth-check-email . "Prüfe deine E-Mails für den Aktivierungslink.")
 (:auth-redirect-login . "Weiterleitung zur Anmeldung in")
 (:auth-seconds . "Sekunden...")
 (:auth-go-now . "Jetzt weiter")
 (:auth-not-activated . "Konto nicht aktiviert")
 (:auth-activate-title . "Aktiviere dein Konto!")
 (:auth-activated . "Konto aktiviert!")
 (:auth-activated-message . "Dein Konto wurde aktiviert. Du kannst Hiisi jetzt nutzen.")
 (:auth-redirecting . "Weiterleitung in")
 (:auth-go-to-app . "Zur App")
 (:auth-resend-title . "Aktivierungs-E-Mail erneut senden")
 (:auth-resend-subtitle . "Gib deine E-Mail-Adresse ein, um einen neuen Aktivierungslink zu erhalten.")
 (:auth-resend-button . "Aktivierungs-E-Mail erneut senden")
 (:auth-resend-success . "Aktivierungs-E-Mail gesendet!")
 (:auth-resend-success-detail . "Überprüfe deinen Posteingang für den neuen Aktivierungslink.")
 (:auth-resend-rate-limited . "Bitte warte einige Minuten, bevor du eine weitere Aktivierungs-E-Mail anforderst.")
 (:auth-resend-cooldown . "Du kannst in ~a Sekunden eine weitere E-Mail anfordern.")
 (:auth-back-to-login . "Zurück zum Login")
 (:auth-forgot-password-title . "Passwort vergessen")
 (:auth-forgot-password-subtitle . "Gib deine E-Mail-Adresse ein und wir senden dir einen Link zum Zurücksetzen deines Passworts.")
 (:auth-send-reset-link . "Link zum Zurücksetzen senden")
 (:auth-reset-email-sent . "Link gesendet!")
 (:auth-reset-email-sent-detail . "Wenn ein Konto mit dieser E-Mail existiert, erhältst du in Kürze einen Link zum Zurücksetzen des Passworts.")
 (:auth-reset-rate-limited . "Bitte warte einige Minuten, bevor du eine weitere Passwort-Zurücksetzung anforderst.")
 (:auth-reset-invalid-token . "Dieser Link zum Zurücksetzen des Passworts ist ungültig oder abgelaufen.")
 (:auth-reset-password-title . "Passwort zurücksetzen")
 (:auth-reset-password-subtitle . "Gib unten dein neues Passwort ein.")
 (:auth-new-password . "Neues Passwort")
 (:auth-confirm-new-password . "Neues Passwort bestätigen")
 (:auth-reset-password . "Passwort zurücksetzen")
 (:auth-password-changed . "Passwort geändert!")
 (:auth-password-changed-detail . "Dein Passwort wurde erfolgreich geändert. Du kannst dich jetzt mit deinem neuen Passwort anmelden.")
 (:auth-change-password-title . "Passwort ändern")
 (:auth-change-password-subtitle . "Aktualisiere dein Kontopasswort.")
 (:auth-current-password . "Aktuelles Passwort")
 (:auth-change-password . "Passwort ändern")
 (:auth-back-to-app . "Zurück zur App")
 (:auth-password-updated . "Passwort aktualisiert!")
 (:auth-password-updated-detail . "Dein Passwort wurde erfolgreich aktualisiert.")

 ;; Translation page
 (:translate-title . "Übersetzen")
 (:translate-input-label . "Text zum Übersetzen")
 (:translate-input-placeholder . "Text zum Übersetzen eingeben...")
 (:translate-from . "Von:")
 (:translate-to . "Nach:")
 (:translate-submit . "Übersetzen")
 (:translate-save . "Als Karteikarte speichern")
 (:translate-saved . "Gespeichert!")
 (:translate-like . "Gefällt mir")
 (:translate-dislike . "Gefällt mir nicht")
 (:translate-char-limit . "Zeichen übrig")
 (:translate-auto-detect . "Beliebig (Automatisch erkennen)")
 (:translate-empty-state . "Gib oben Text ein und klicke auf Übersetzen, um das Ergebnis mit Grammatikanalyse zu sehen")
 (:translate-select-deck-placeholder . "Deck auswählen (optional)")
 (:translate-new-deck . "Neues Deck")
 (:translate-add-to-deck . "Zum Deck hinzufügen")
 (:translate-bookmark . "Merken")
 (:translate-bookmarked . "Gemerkt")
 (:translate-retry . "Erneut versuchen")
 (:translate-like-tooltip . "Gute Übersetzung")
 (:translate-dislike-tooltip . "Schlechte Übersetzung - neue anfordern")
 (:translate-dislike-confirm . "Dies generiert eine neue Übersetzung. Fortfahren?")
 (:translate-liked . "Gefällt!")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Ziel")
 (:translate-deck-create-title . "Neuen Stapel erstellen")
 (:translate-deck-name-label . "Stapelname")
 (:translate-deck-name-placeholder . "z. B. Finnisch Grundlagen")
 (:translate-deck-description-label . "Beschreibung (optional)")
 (:translate-deck-cancel . "Abbrechen")
 (:translate-deck-create . "Erstellen")
 (:translate-rate-label . "Übersetzung bewerten")
 (:flashcards-delete-confirm . "Möchten Sie diese Karteikarte wirklich löschen?")
 (:flashcards-deck-search-placeholder . "Stapel suchen...")
 (:flashcards-no-decks . "Noch keine Stapel. Erstellen Sie zuerst einen!")
 (:flashcards-deck-cancel . "Abbrechen")
 (:flashcards-recollection-tooltip . "Erinnerung: ~A")
 (:flashcards-recollection-poor . "Schwach")
 (:flashcards-recollection-fair . "Mäßig")
 (:flashcards-recollection-normal . "Normal")
 (:flashcards-recollection-strong . "Stark")
 (:flashcards-recollection-very-strong . "Sehr stark")

 ;; Flashcard review
 (:review-title . "Wiederholen")
 (:review-session-title . "Wiederholungssitzung")
 (:review-session-subtitle . "Übe deine gespeicherten Karteikarten")
 (:review-selector-title . "Wähle aus, was du wiederholen möchtest")
 (:review-selector-subtitle . "Wähle ein Deck oder ein Sprachpaar für deine Wiederholungssitzung.")
 (:review-by-deck . "Nach Deck wiederholen")
 (:review-by-language-pair . "Nach Sprachpaar wiederholen")
 (:review-all-cards . "Alle Karten wiederholen")

 (:review-start . "Wiederholung starten")
 (:review-no-cards . "Keine Karten zur Wiederholung")
 (:review-no-cards-desc . "Du hast gerade keine Karteikarten zur Wiederholung fällig.")
 (:review-no-cards-hint . "Übersetze Text und klicke auf \"Als Karteikarte speichern\", um dein Deck aufzubauen!")
 (:review-start-translating . "Übersetzen starten")
 (:review-show-answer . "Antwort zeigen")
 (:review-click-reveal . "Klicken um Antwort anzuzeigen")
 (:review-grammar-breakdown . "Grammatikanalyse")
 (:review-how-well . "Hast du dich erinnert?")
 (:review-again . "Nein")
 (:review-hard . "Kaum")
 (:review-good . "Ja")
 (:review-easy . "Leicht")
 (:review-progress . "Karte ~a von ~a")
 (:review-complete . "Sitzung abgeschlossen!")
 (:review-complete-msg . "Du hast ~a Karten wiederholt")
 (:review-correct . "Richtig")
 (:review-accuracy . "Genauigkeit")
 (:review-again-btn . "Erneut wiederholen")
 (:review-translate-more . "Mehr übersetzen")
 (:review-streak . "Tage Serie")

 ;; Dashboard
 (:dashboard-title . "Dashboard")
 (:dashboard-cards-due . "Fällige Karten")
 (:dashboard-total-cards . "Karten insgesamt")
 (:dashboard-subscription . "Abonnement")
 (:dashboard-subscribed-until . "Abonniert bis")
 (:dashboard-not-subscribed . "Nicht abonniert")
 (:dashboard-recent . "Letzte Übersetzungen")
 (:dashboard-no-translations . "Noch keine Übersetzungen")
 (:dashboard-streak . "Wiederholungsserie")
 (:dashboard-days . "Tage")
 (:dashboard-quick-actions . "Schnellaktionen")
 (:dashboard-getting-started . "Erste Schritte")
 (:dashboard-tip-1 . "Übersetze Text, den du lernen möchtest")
 (:dashboard-tip-2 . "Klicke bei Übersetzungen auf \"Als Karteikarte speichern\", die du behalten möchtest")
 (:dashboard-tip-3 . "Wiederhole deine Karteikarten regelmäßig - Spaced Repetition hilft beim langfristigen Behalten")
 (:dashboard-tip-4 . "Bewerte ehrlich - das hilft dem Algorithmus, deine Wiederholungen optimal zu planen")

 ;; Account
 (:account-title . "Konto")
 (:account-subtitle . "Verwalten Sie Ihre Kontoeinstellungen und den Löschzeitplan.")
 (:account-deletion-title . "Kontolöschung")
 (:account-deletion-scheduled . "Ihr Konto ist für die Löschung am ~A geplant.")
 (:account-deletion-cancel-hint . "Sie können vor diesem Datum abbrechen, um Ihr Konto zu behalten.")
 (:account-deletion-cancel . "Löschung abbrechen")
 (:account-deletion-request . "Sie können die Kontolöschung jederzeit anfordern. Die Löschung ist 14 Tage nach der Bestätigung geplant. Wenn Sie es sich nach der Löschung anders überlegen, kontaktieren Sie bitte den Support.")
 (:account-deletion-confirm . "Kontolöschung in 14 Tagen ab heute planen?")
 (:account-deletion-schedule . "Löschung planen")
 (:account-reminders-title . "E-Mail-Erinnerungen")
 (:account-reminders-subtitle . "Steuern Sie Wiederholungs- und Fortsetzungserinnerungen für dieses Konto.")
 (:account-reminders-opt-out . "Erinnerungen für Wiederholung und Fortsetzung abbestellen")
 (:account-reminders-save . "Einstellungen speichern")

 ;; Subscription
 (:subscribe-title . "Einfache Preise")
 (:subscribe-choose-plan . "Wähle deinen Plan")
 (:subscribe-start-today . "Starte heute mit einer 7-tägigen kostenlosen Testphase")
 (:subscribe-monthly . "Monatlich")
 (:subscribe-annual . "Jährlich")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/Monat")
 (:subscribe-per-year . "/Jahr")
 (:subscribe-monthly-desc . "600 Übersetzungen pro Monat")
 (:subscribe-unlimited-flashcards . "Unbegrenzte Karteikarten")
 (:subscribe-grammar-explanations . "Grammatikerklärungen")
 (:subscribe-spaced-repetition . "Spaced Repetition")
 (:subscribe-annual-desc . "Spare 20€ — zwei Monate gratis!")
 (:subscribe-cta . "Abonnieren")
 (:subscribe-success . "Abonnement erfolgreich!")
 (:subscribe-manage . "Abonnement verwalten")
 (:subscribe-activated . "Abonnement aktiviert!")
 (:subscribe-thank-you . "Vielen Dank für dein Abonnement. Dein Konto ist jetzt aktiv.")
 (:subscribe-start-learning . "Jetzt lernen")
 (:subscribe-management . "Abonnementverwaltung")
 (:subscribe-active . "Aktives Abonnement")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Aktiv")
 (:subscribe-days-remaining . "Verbleibende Tage:")
 (:subscribe-renews-on . "Verlängert am:")
 (:subscribe-no-subscription . "Kein aktives Abonnement")
 (:subscribe-access-features . "Abonniere, um alle Funktionen freizuschalten.")
 (:subscribe-view-plans . "Pläne ansehen")
 (:subscribe-faq-title . "Häufig gestellte Fragen")
 (:subscribe-faq-trial-q . "Was passiert nach der kostenlosen Testphase?")
 (:subscribe-faq-trial-a . "Nach deiner 7-tägigen kostenlosen Testphase wird der gewählte Plan berechnet. Du kannst jederzeit vor Ende der Testphase kündigen.")
 (:subscribe-faq-cancel-q . "Kann ich jederzeit kündigen?")
 (:subscribe-faq-cancel-a . "Ja! Du kannst dein Abonnement jederzeit kündigen. Du behältst den Zugang bis zum Ende deines Abrechnungszeitraums.")
 (:subscribe-faq-payment-q . "Welche Zahlungsmethoden akzeptiert ihr?")
 (:subscribe-faq-payment-a . "Wir akzeptieren alle gängigen Kredit- und Debitkarten über unseren Zahlungspartner Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Etwas ist schiefgelaufen")
 (:error-not-found . "Seite nicht gefunden")
 (:error-unauthorized . "Bitte melde dich an, um fortzufahren")
 (:error-subscription-required . "Abonnement erforderlich")
 (:error-text-too-long . "Text ist zu lang. Die maximale Übersetzungslänge beträgt 120 Zeichen.")
 (:error-input-too-long . "Eingabe zu lang")
 (:error-unknown-source-lang . "Die ausgewählte Ausgangssprache wird nicht unterstützt.")
 (:error-unknown-target-lang . "Die ausgewählte Zielsprache wird nicht unterstützt.")
 (:error-unknown-language . "Unbekannte Sprache")
 (:error-translation-unavailable . "Der Übersetzungsdienst ist vorübergehend nicht verfügbar. Bitte versuche es gleich noch einmal.")
 (:error-translation-failed . "Übersetzung fehlgeschlagen")
 (:error-translation-retry . "Konnte nach mehreren Versuchen keine Übersetzung generieren. Bitte formuliere deinen Text um.")
 (:error-quota-exceeded . "Übersetzungslimit erreicht")
 (:error-quota-exceeded-detail . "Du hast alle Übersetzungen für diesen Monat aufgebraucht. Dein Kontingent wird automatisch jeden Monat zurückgesetzt.")
 (:quota-warning . "Verbleibende Übersetzungen: ~A")
 (:quota-low-warning . "Nur noch ~A Übersetzungen übrig. Erwägen Sie den Kauf von mehr.")
 (:top-up-button . "Mehr Übersetzungen kaufen")
 (:top-up-success . "Aufstockung erfolgreich! Sie haben jetzt ~A zusätzliche Übersetzungen.")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 Übersetzungen")
 (:loading . "Lädt...")
 (:empty-state . "Hier ist noch nichts")

 ;; Institutions
 (:institutions-page-title . "Hiisi für Schulen - institutionelle Lizenzen")
 (:institutions-hero-title . "Hiisi für Schulen")
 (:institutions-hero-subtitle . "Stärken Sie Ihre Lernenden mit KI-gestütztem Sprachenlernen")
 (:institutions-section-title . "Institutionelle Lizenzen")
 (:institutions-section-body . "Wir bieten Volumenlizenzen für Schulen, Universitäten und Sprachinstitute an. Studierende mit E-Mail-Adressen aus Ihrer Domain erhalten automatisch vollen Zugriff.")
 (:institutions-benefit-1 . "Automatische Registrierung für Studierende mit institutioneller E-Mail")
 (:institutions-benefit-2 . "Keine einzelnen Studierendenkonten zu verwalten")
 (:institutions-benefit-3 . "Flexible Abrechnungsmodelle")
 (:institutions-benefit-4 . "Engagierter Support für Lehrkräfte")
 (:institutions-request-title . "Lizenz anfragen")
 (:institutions-request-subtitle . "Füllen Sie das Formular unten aus und wir melden uns innerhalb von 2 Werktagen.")
 (:institutions-field-name . "Name der Institution")
 (:institutions-field-name-placeholder . "Universität Helsinki")
 (:institutions-field-contact-name . "Kontaktperson")
 (:institutions-field-contact-name-placeholder . "Ihr Name")
 (:institutions-field-contact-email . "Kontakt-E-Mail")
 (:institutions-field-contact-email-placeholder . "sie@universitaet.de")
 (:institutions-field-domains . "E-Mail-Domains")
 (:institutions-field-domains-placeholder . "universitaet.de, cs.universitaet.de")
 (:institutions-field-domains-help . "Kommagetrennte Liste der E-Mail-Domains Ihrer Institution")
 (:institutions-field-notes . "Zusätzliche Informationen")
 (:institutions-field-notes-placeholder . "Geschätzte Anzahl der Studierenden, bevorzugter Abrechnungszyklus, besondere Anforderungen...")
 (:institutions-submit . "Anfrage senden")
 (:institutions-success-title . "Danke - Hiisi für Schulen")
 (:institutions-success-heading . "Danke!")
 (:institutions-success-body . "Wir haben Ihre Anfrage nach einer institutionellen Lizenz erhalten. Unser Team prüft Ihre Anfrage und meldet sich innerhalb von 2 Werktagen.")
 (:institutions-success-back . "Zurück zur Startseite")

 ;; Footer
 (:footer-privacy . "Datenschutz")
 (:footer-terms . "Nutzungsbedingungen")
 (:footer-contact . "Kontakt")

 ;; Early software notice
 (:early-software-notice . "Hiisi befindet sich in früher Entwicklung. Einen Fehler gefunden oder einen Vorschlag?")
 (:early-software-contact . "Kontaktiere uns unter")

 ;; Datenschutzerklärung
 (:privacy-title . "Datenschutzerklärung")
 (:privacy-updated . "Zuletzt aktualisiert: Januar 2026")
 (:privacy-who-title . "Wer wir sind")
 (:privacy-who-body . "Hiisi wird von Lambda Symbolics OÜ betrieben, einem in Estland registrierten Unternehmen. Als estnisches Unternehmen halten wir die Datenschutz-Grundverordnung (DSGVO) der Europäischen Union ein.")
 (:privacy-collect-title . "Welche Daten wir erfassen")
 (:privacy-collect-intro . "Wenn Sie Hiisi verwenden, erfassen wir folgende Informationen:")
 (:privacy-collect-account-key . "Kontoinformationen: ")
 (:privacy-collect-account-val . "E-Mail-Adresse, Anzeigename und ein sicher gehashtes Passwort.")
 (:privacy-collect-learning-key . "Lerndaten: ")
 (:privacy-collect-learning-val . "Ihre Übersetzungen, gespeicherten Karteikarten und Ihr Wiederholungsverlauf.")
 (:privacy-collect-usage-key . "Nutzungsdaten: ")
 (:privacy-collect-usage-val . "Grundlegende Serverprotokolle für Sicherheits- und Debugging-Zwecke.")
 (:privacy-use-title . "Wie wir Ihre Daten verwenden")
 (:privacy-use-auth-key . "Authentifizierung: ")
 (:privacy-use-auth-val . "Zur Überprüfung Ihrer Identität und zum Schutz Ihres Kontos.")
 (:privacy-use-service-key . "Bereitstellung des Dienstes: ")
 (:privacy-use-service-val . "Um Übersetzungen bereitzustellen und Ihre Karteikartensammlung zu verwalten.")
 (:privacy-use-ai-key . "KI-Übersetzungen: ")
 (:privacy-use-ai-val . "Ihre Übersetzungsanfragen werden an die Claude API von Anthropic gesendet, um Antworten zu erzeugen. Wie Anthropic diese Daten verarbeitet, finden Sie in der Datenschutzerklärung von Anthropic.")
 (:privacy-third-title . "Dienste von Drittanbietern")
 (:privacy-third-intro . "Wir verwenden die folgenden Drittanbieter-Dienste:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "Für KI-gestützte Übersetzungen.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "Für den Versand von Aktivierungs- und Transaktions-E-Mails.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Für die Verarbeitung von Abonnementzahlungen.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "Wir verwenden nur notwendige Cookies:")
 (:privacy-cookies-auth-key . "Authentifizierungs-Token: ")
 (:privacy-cookies-auth-val . "Ein sicheres, nur über HTTP zugängliches Cookie, damit Sie eingeloggt bleiben.")
 (:privacy-cookies-lang-key . "Spracheinstellung: ")
 (:privacy-cookies-lang-val . "Damit Ihre bevorzugte Sprache der Benutzeroberfläche gespeichert bleibt.")
 (:privacy-retention-title . "Speicherdauer")
 (:privacy-retention-body . "Ihre Daten werden gespeichert, solange Sie ein Konto haben. Wenn Sie eine Löschung anfordern, wird Ihr Konto zur Löschung in 14 Tagen vorgemerkt.")
 (:privacy-rights-title . "Ihre Rechte (DSGVO)")
 (:privacy-rights-intro . "Nach der DSGVO haben Sie das Recht auf:")
 (:privacy-rights-access . "Auskunft über Ihre personenbezogenen Daten")
 (:privacy-rights-export . "Export Ihrer Daten (verfügbar unter /app/api/export)")
 (:privacy-rights-correct . "Berichtigung unrichtiger Daten")
 (:privacy-rights-delete . "Löschung Ihres Kontos und Ihrer Daten")
 (:privacy-rights-object . "Widerspruch gegen die Verarbeitung Ihrer Daten")
 (:privacy-rights-contact . "Um diese Rechte auszuüben, kontaktieren Sie uns unter")
 (:privacy-contact-title . "Kontakt")
 (:privacy-contact-intro . "Für Datenschutzanfragen:")
 (:privacy-contact-email-label . "E-Mail: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Estland")

 ;; Nutzungsbedingungen
 (:terms-title . "Nutzungsbedingungen")
 (:terms-updated . "Zuletzt aktualisiert: Januar 2026")
 (:terms-1-title . "1. Dienstbeschreibung")
 (:terms-1-body . "Hiisi ist eine Sprachlern-Anwendung, die KI-gestützte Übersetzungen mit grammatischen Erklärungen und Karteikarten mit verteilter Wiederholung anbietet. Der Dienst wird von Lambda Symbolics OÜ betrieben.")
 (:terms-2-title . "2. Kontoregistrierung")
 (:terms-2-body . "Um Hiisi zu nutzen, müssen Sie ein Konto mit einer gültigen E-Mail-Adresse erstellen. Sie sind für die Sicherheit Ihrer Zugangsdaten verantwortlich.")
 (:terms-3-title . "3. Abonnement und Zahlungen")
 (:terms-3-body . "Hiisi bietet kostenpflichtige Abonnements (monatlich und jährlich). Abonnements werden über Polar.sh verarbeitet.")
 (:terms-3-list-1 . "Abonnements verlängern sich automatisch, sofern sie nicht vor dem Verlängerungsdatum gekündigt werden.")
 (:terms-3-list-2 . "Rückerstattungen erfolgen nach den geltenden Verbraucherschutzgesetzen.")
 (:terms-3-list-3 . "Bei ausbleibender Zahlung entfällt der Zugriff auf Premium-Funktionen.")
 (:terms-4-title . "4. Zulässige Nutzung")
 (:terms-4-intro . "Sie verpflichten sich, Folgendes zu unterlassen:")
 (:terms-4-list-1 . "Den Dienst für rechtswidrige Zwecke zu verwenden")
 (:terms-4-list-2 . "Nutzungsbeschränkungen oder Sicherheitsmaßnahmen zu umgehen")
 (:terms-4-list-3 . "Ihre Zugangsdaten mit anderen zu teilen")
 (:terms-4-list-4 . "Automatisierte Werkzeuge so einzusetzen, dass die Leistung für andere beeinträchtigt wird")
 (:terms-5-title . "5. Inhalte und geistiges Eigentum")
 (:terms-5-body-1 . "Von Hiisi erzeugte Übersetzungen werden mithilfe von KI erstellt und sind möglicherweise nicht einzigartig. Sie dürfen Ihre Übersetzungen und Karteikarten für persönliche Zwecke nutzen, besitzen aber keine exklusiven Urheberrechte an KI-generierten Inhalten.")
 (:terms-5-body-2 . "Die Hiisi-Anwendung, die Marke und originale Inhalte bleiben Eigentum von Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Verfügbarkeit des Dienstes")
 (:terms-6-intro . "Hiisi wird in der Form \"wie bereitgestellt\" angeboten. Wir garantieren nicht:")
 (:terms-6-list-1 . "Einen unterbrechungsfreien oder fehlerfreien Dienst")
 (:terms-6-list-2 . "Die Genauigkeit von KI-generierten Übersetzungen")
 (:terms-6-list-3 . "Die Verfügbarkeit bestimmter Funktionen")
 (:terms-6-body . "Wir können Funktionen jederzeit ändern oder einstellen.")
 (:terms-7-title . "7. Haftungsbeschränkung")
 (:terms-7-body-1 . "Soweit gesetzlich zulässig haftet Lambda Symbolics OÜ nicht für indirekte, zufällige, besondere oder Folgeschäden, die aus Ihrer Nutzung von Hiisi entstehen.")
 (:terms-7-body-2 . "Unsere Gesamthaftung ist auf den Betrag begrenzt, den Sie in den 12 Monaten vor dem Anspruch für den Dienst bezahlt haben.")
 (:terms-8-title . "8. Konto-Kündigung")
 (:terms-8-body-1 . "Wir können Ihr Konto sperren oder kündigen, wenn Sie gegen diese Bedingungen verstoßen. Sie können jederzeit in der Anwendung die Löschung Ihres Kontos anfordern.")
 (:terms-8-body-2 . "Nach einem Löschantrag wird Ihr Konto zur Löschung in 14 Tagen vorgemerkt.")
 (:terms-9-title . "9. Änderungen der Bedingungen")
 (:terms-9-body . "Wir können diese Bedingungen von Zeit zu Zeit aktualisieren. Die weitere Nutzung von Hiisi nach Änderungen gilt als Zustimmung zu den neuen Bedingungen.")
 (:terms-10-title . "10. Anwendbares Recht")
 (:terms-10-body . "Für diese Bedingungen gilt estnisches Recht. Streitigkeiten werden vor den Gerichten Estlands entschieden.")
 (:terms-contact-title . "Kontakt")
 (:terms-contact-intro . "Bei Fragen zu diesen Bedingungen:")
 (:terms-contact-email-label . "E-Mail: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Estland")



 ;; Decks
 (:decks-title . "Stapel")
 (:decks-subtitle . "Erstelle eigene Stapel und teile sie mit anderen.")
 (:decks-create-title . "Stapel erstellen")
 (:decks-name-placeholder . "Stapelname")
 (:decks-desc-placeholder . "Beschreibung")
 (:decks-create-btn . "Stapel erstellen")
 (:decks-your-title . "Deine Stapel")
 (:decks-col-name . "Name")
 (:decks-col-desc . "Beschreibung")
 (:decks-col-updated . "Aktualisiert")
 (:decks-col-actions . "Aktionen")
 (:decks-no-decks . "Noch keine Stapel.")
 (:decks-open-btn . "Öffnen")
 (:decks-no-desc . "Keine Beschreibung.")
 (:decks-share-title . "Teilen-Link")
 (:decks-share-info . "Jeder mit diesem Link kann den Stapel importieren:")
 (:decks-share-copy . "Link kopieren")
 (:decks-share-copied . "Kopiert")
 (:decks-add-from-flashcards-title . "Übersetzungen hinzufügen")
 (:decks-add-from-flashcards-info . "Wähle eine Karte aus, um ihre Übersetzung diesem Stapel hinzuzufügen.")
 (:decks-open-flashcards . "Aus Karten hinzufügen")
 (:decks-filter-from . "Ausgangssprache")
 (:decks-filter-to . "Zielsprache")
 (:decks-filter-any . "Beliebige Sprache")
 (:decks-filter-include-assigned . "Auch Karten anzeigen, die bereits in einem Stapel sind")
 (:decks-flashcards-col-from . "Von")
 (:decks-flashcards-col-to . "Nach")
 (:decks-flashcards-add . "Hinzufügen")
 (:decks-flashcards-added . "Hinzugefügt")
 (:decks-flashcards-in-deck . "In einem anderen Stapel")
 (:decks-flashcards-empty . "Keine Karten entsprechen diesen Filtern.")
 (:decks-add-trans-title . "Übersetzung hinzufügen")
 (:decks-trans-id-placeholder . "Übersetzungs-ID")
 (:decks-add-trans-btn . "Übersetzung hinzufügen")
 (:decks-items-title . "Stapelinhalt")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Übersetzung")
 (:decks-col-lang . "Zielsprache")
 (:decks-no-items . "Noch keine Einträge.")
 (:decks-share-page-title . "Stapel teilen")
 (:decks-share-preview . "Vorschau und Import dieses Stapels.")
 (:decks-import-title . "Importieren")
 (:decks-import-btn . "Stapel importieren")

 ;; Flashcards management page
 (:flashcards-title . "Meine Karten")
 (:flashcards-subtitle . "Alle gespeicherten Karteikarten an einem Ort. Suchen, organisieren und verwalten.")
 (:flashcards-search-placeholder . "Karten suchen...")
 (:flashcards-hide-perfected . "Perfekt beherrschte Karten ausblenden")
 (:flashcards-col-original . "Original")
 (:flashcards-col-translated . "Übersetzung")
 (:flashcards-col-lang . "Sprachen")
 (:flashcards-no-cards . "Noch keine Karteikarten. Beginne mit Übersetzen, um welche zu erstellen!")

 ;; API Errors
 (:api-error-missing-text . "Zu übersetzender Text fehlt.")
 (:api-error-invalid-translation-id . "Ungültige Übersetzungs-ID.")
 (:api-error-translation-not-found . "Die Übersetzung, die Sie speichern wollten, existiert nicht mehr.")
 (:api-error-invalid-bookmark-id . "Ungültige Lesezeichen-ID")
 (:api-error-bookmark-not-found . "Lesezeichen nicht gefunden")
 (:api-error-forbidden . "Verboten")
 (:api-error-failed-delete-bookmark . "Lesezeichen konnte nicht gelöscht werden")
 (:api-error-invalid-flashcard-id . "Ungültige Karteikarten-ID")
 (:api-error-missing-deck-id . "Deck-ID fehlt")
 (:api-error-flashcard-not-found . "Karteikarte nicht gefunden")
 (:api-error-deck-not-found . "Deck nicht gefunden")
 (:api-error-deck-name-required . "Deck-Name ist erforderlich")
 (:api-error-session-expired . "Ihre Wiederholungssitzung ist abgelaufen. Bitte starten Sie eine neue Sitzung.")
 (:api-error-invalid-card-id . "Ungültige Karten-ID.")
 (:api-error-invalid-rating . "Ungültige Bewertung.")
 (:api-error-rating-range . "Die Bewertung muss zwischen 0 und 5 liegen.")
 (:api-error-card-not-found . "Karte nicht gefunden.")
 (:api-error-permission-denied . "Sie haben keine Berechtigung, diese Karte zu wiederholen.")
 (:api-error-unknown-source-lang . "Unbekannte Ausgangssprache.")
 (:api-error-unknown-target-lang . "Unbekannte Zielsprache.")
 (:api-error-failed-add-to-deck . "Hinzufügen zum Deck fehlgeschlagen")

 ;; API Success messages
 (:api-success-added . "Hinzugefügt!")
 (:api-success-added-simple . "Hinzugefügt")

 ;; API Stats
 (:api-stats-due . "~A fällig")
 (:api-stats-total . "~A gesamt")

 ;; Time units
 (:api-time-day . "Tag")
 (:api-time-days . "Tage")
 (:api-time-day-left . "Tag übrig")
 (:api-time-days-left . "Tage übrig")

 ;; Subscription status
 (:api-subscription-active . "Aktiv")
 (:api-subscription-inactive . "Inaktiv")
 (:api-subscription-subscribe-hint . "Abonnieren Sie, um Übersetzungen freizuschalten")

 ;; Generic status
 (:status-bad-request . "Ungültige Anfrage")
 (:status-not-found . "Nicht gefunden")
 (:status-forbidden . "Verboten")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Sprachen umfassend lernen")
 (:landing-hero-subheadline . "Erhalten Sie Übersetzungen mit vollständiger Grammatikanalyse und bauen Sie dauerhaften Wortschatz mit Karteikarten-Wiederholung auf.")
 (:landing-hero-trust-line . "7 Tage kostenlos testen mit 100 Übersetzungen. Jederzeit kündbar.")
 (:landing-credibility-languages . "14 Sprachen")
 (:landing-credibility-ai . "Grammatikanalyse inklusive")
 (:landing-credibility-origin . "Entwickelt in Estland")
 (:landing-step-1-title . "Beliebigen Text übersetzen")
 (:landing-step-1-desc . "Geben Sie ein Wort oder einen Satz ein. Erhalten Sie eine Übersetzung mit vollständiger Grammatikanalyse.")
 (:landing-step-2-title . "Als Karteikarten speichern")
 (:landing-step-2-desc . "Speichern Sie Übersetzungen, die Sie sich merken möchten. Karteikarten werden automatisch erstellt.")
 (:landing-step-3-title . "Wiederholen und einprägen")
 (:landing-step-3-desc . "Verteilte Wiederholung plant Überprüfungen im perfekten Moment für das Langzeitgedächtnis.")
 (:landing-feature-grammar-title . "Grammatik verstehen, nicht nur Wörter")
 (:landing-feature-grammar-desc . "Jede Übersetzung enthält eine detaillierte Grammatikanalyse -- Wortformen, Fälle, Konjugationen in Ihrer Sprache erklärt.")
 (:landing-feature-srs-title . "Wissenschaftlich fundiertes Einprägen")
 (:landing-feature-srs-desc . "Der SM-2-Algorithmus passt sich Ihrer Leistung an. Schwierige Karten erscheinen häufiger. Bekannte Karten treten zurück.")
 (:landing-feature-share-title . "Kartenstapel mit Schülerinnen und Schülern teilen")
 (:landing-feature-share-desc . "Lehrkräfte können eigene Kartenstapel erstellen und per Link teilen. Schülerinnen und Schüler importieren den Stapel und beginnen sofort mit dem Wiederholen.")
 (:landing-pricing-trial-note . "7 Tage kostenlose Testphase inklusive")
 (:landing-pricing-monthly-after . "7 Tage kostenlos, danach ~A/Monat")
 (:landing-pricing-annual-after . "7 Tage kostenlos, danach ~A/Jahr")
 (:landing-faq-title . "Häufig gestellte Fragen")
 (:landing-faq-trial-cap-q . "Wie viele Übersetzungen erhalte ich während der Testphase?")
 (:landing-faq-trial-cap-a . "Sie erhalten 100 Übersetzungen während Ihrer 7-tägigen Testphase. Nach dem Abonnement erhalten Sie 600 pro Monat.")
 (:landing-final-cta-title . "Heute mit dem Lernen beginnen")
 (:landing-final-cta-subtitle . "Werden Sie Teil von Hiisi und bauen Sie Wortschatz auf, der bleibt.")

 ;; Trial status (in-app)
 (:trial-status . "Kostenlose Testphase")
 (:trial-days-remaining . "~A Tage verbleibend")
 (:trial-translations-used . "~A/100 Übersetzungen verbraucht")
 (:trial-upgrade-prompt . "Upgraden Sie, um weiter zu übersetzen")
 (:trial-expired . "Ihre kostenlose Testphase ist abgelaufen")
 (:trial-expired-detail . "Abonnieren Sie, um mit Hiisi weiterzulernen.")
 (:trial-quota-warning . "~A Test-Übersetzungen übrig (~A Tage verbleibend). Abonnieren Sie für 600/Monat.")
 (:trial-quota-exceeded . "Test-Übersetzungslimit erreicht. Abonnieren Sie, um fortzufahren.")
 (:error-trial-quota-exceeded . "Test-Übersetzungslimit erreicht")
 (:error-trial-quota-detail . "Sie haben alle 100 Test-Übersetzungen verbraucht. Abonnieren Sie, um weiterzulernen.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Karteikarte erstellen")
 (:custom-flashcard-edit-title . "Karteikarte bearbeiten")
 (:custom-flashcard-original . "Originaltext")
 (:custom-flashcard-translated . "Übersetzung")
 (:custom-flashcard-lang-from . "Ausgangssprache")
 (:custom-flashcard-lang-to . "Zielsprache")
 (:custom-flashcard-note . "Lernhinweis")
 (:custom-flashcard-forms . "Grammatikanalyse")
 (:custom-flashcard-form-term . "Begriff")
 (:custom-flashcard-form-explanation . "Erklärung")
 (:custom-flashcard-add-form . "Grammatikbegriff hinzufügen")
 (:custom-flashcard-remove-form . "Entfernen")
 (:custom-flashcard-ai-fill . "Mit KI ausfüllen")
 (:custom-flashcard-ai-fill-all . "Alles mit KI ausfüllen")
 (:custom-flashcard-ai-fill-translation . "Mit KI übersetzen")
 (:custom-flashcard-ai-fill-breakdown . "Analyse generieren")
 (:custom-flashcard-ai-fill-note . "Hinweis generieren")
 (:custom-flashcard-create-btn . "Karteikarte erstellen")
 (:custom-flashcard-update-btn . "Änderungen speichern")
 (:custom-flashcard-delete-btn . "Karteikarte löschen")
 (:custom-flashcard-delete-confirm . "Möchten Sie diese Karteikarte wirklich löschen?")
 (:custom-flashcard-created . "Karteikarte erfolgreich erstellt")
 (:custom-flashcard-updated . "Karteikarte erfolgreich aktualisiert")
 (:custom-flashcard-deleted . "Karteikarte erfolgreich gelöscht")
 (:custom-flashcard-add-to-deck . "Zum Stapel hinzufügen")
 (:custom-flashcard-not-found . "Karteikarte nicht gefunden")
 (:custom-flashcard-not-owner . "Sie können nur selbst erstellte Karteikarten bearbeiten")
 (:custom-flashcard-ai-generating . "Wird mit KI generiert...")
 (:custom-flashcard-badge . "Eigene")

 ;; Problemmeldungen
 (:issues-open-button . "Problem melden")
 (:issues-modal-title . "Problem melden")
 (:issues-modal-subtitle . "Beschreiben Sie, was schiefgelaufen ist. Ihre aktuelle Seite wird automatisch mitgesendet.")
 (:issues-title-label . "Kurzer Titel")
 (:issues-title-placeholder . "Kurze Zusammenfassung des Problems")
 (:issues-message-label . "Was ist passiert?")
 (:issues-message-placeholder . "Bitte geben Sie Schritte zur Reproduktion, das erwartete Verhalten und das tatsächliche Ergebnis an.")
 (:issues-submit . "Meldung senden")
 (:issues-cancel . "Abbrechen")
 (:issues-success . "Danke. Ihre Problemmeldung wurde gesendet.")
 (:issues-error-required . "Bitte beschreiben Sie das Problem vor dem Absenden.")
 (:issues-error-title-too-long . "Der Titel der Meldung ist zu lang. Bitte auf unter 160 Zeichen kürzen.")
 (:issues-error-too-long . "Der Meldungstext ist zu lang. Bitte bleiben Sie unter 4000 Zeichen.")
 (:issues-error-rate-limit . "Zu viele Meldungen von dieser Quelle. Bitte warten Sie und versuchen Sie es später erneut.")
 (:issues-error-generic . "Die Problemmeldung konnte nicht gesendet werden. Bitte versuchen Sie es erneut.")

)
