;;; German translations
;;; This file must contain all keys from en.lisp

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Deutsch")
 (:lang-flag . "🇩🇪")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Wähle deine Sprache")
 (:lang-modal-subtitle . "Wähle deine bevorzugte Sprache für die Benutzeroberfläche:")

 ;; Navigation
 (:nav-translate . "Übersetzen")
 (:nav-review . "Wiederholen")
 (:nav-dashboard . "Dashboard")
 (:nav-logout . "Abmelden")
 (:nav-home . "Startseite")
 (:nav-pricing . "Preise")
 (:nav-export-data . "Daten exportieren")

 ;; App title and branding
 (:app-title . "Hiisi")
 (:app-tagline . "Sprachen lernen durch Übersetzungen")

 ;; Landing page
 (:landing-hero-title . "Jede Sprache meistern")
 (:landing-hero-subtitle . "Übersetze alles. Generiere automatisch Karteikarten, die dir erklären, warum es so funktioniert.")
 (:landing-cta . "Jetzt lernen")
 (:landing-learn-more . "Mehr erfahren")
 (:landing-how-it-works . "So funktioniert's")
 (:landing-feature-1-title . "Automatische Karteikarten")
 (:landing-feature-1-desc . "Jede Übersetzung generiert automatisch Karteikarten mit Grammatikanalyse. Keine manuelle Kartenerstellung.")
 (:landing-feature-2-title . "Spaced Repetition")
 (:landing-feature-2-desc . "Der SM-2 Algorithmus plant Wiederholungen in optimalen Abständen. Effizient lernen, dauerhaft behalten.")
 (:landing-feature-3-title . "Grammatik verstehen")
 (:landing-feature-3-desc . "Jede Übersetzung erklärt Grammatik, Wortstämme und Satzstruktur. Verstehe das Warum, nicht nur das Was.")
 (:landing-free-trial . "7 Tage kostenlos testen. Keine Kreditkarte erforderlich.")
 (:landing-start-trial . "Kostenlos testen")
 (:landing-best-value . "Bestes Angebot")
 (:landing-cta-title . "Bereit, Sprachen durch Grammatik statt Auswendiglernen zu lernen?")
 (:landing-cta-subtitle . "Jede Übersetzung wird zur Lernmöglichkeit. Jede Karteikarte erklärt dir das Warum.")
 (:landing-signup-free . "Kostenlos registrieren")

 ;; Auth pages
 (:auth-register . "Registrieren")
 (:auth-login . "Anmelden")
 (:auth-logout . "Abmelden")
 (:auth-email . "E-Mail")
 (:auth-password . "Passwort")
 (:auth-password-again . "Passwort bestätigen")
 (:auth-display-name . "Anzeigename")
 (:auth-register-title . "Bei Hiisi registrieren")
 (:auth-register-subtitle . "Neues Konto erstellen")
 (:auth-login-title . "Bei Hiisi anmelden")
 (:auth-login-subtitle . "Anmeldedaten eingeben")
 (:auth-forgot-password . "Passwort vergessen?")
 (:auth-no-account . "Noch kein Konto?")
 (:auth-have-account . "Bereits ein Konto?")
 (:auth-google . "Google")
 (:auth-account-created . "Konto erstellt!")
 (:auth-check-email . "Prüfe deine E-Mails für den Aktivierungslink.")
 (:auth-redirect-login . "Weiterleitung zur Anmeldung in")
 (:auth-seconds . "Sekunden...")
 (:auth-go-now . "Jetzt weiter")
 (:auth-not-activated . "Konto nicht aktiviert")
 (:auth-activate-title . "Aktiviere dein Konto!")
 (:auth-activated . "Konto aktiviert!")
 (:auth-activated-message . "Dein Konto wurde aktiviert. Du kannst Hiisi jetzt nutzen.")
 (:auth-redirecting . "Weiterleitung in")
 (:auth-go-to-app . "Zur App")
 (:auth-resend-title . "Aktivierungs-E-Mail erneut senden")
 (:auth-resend-subtitle . "Gib deine E-Mail-Adresse ein, um einen neuen Aktivierungslink zu erhalten.")
 (:auth-resend-button . "Aktivierungs-E-Mail erneut senden")
 (:auth-resend-success . "Aktivierungs-E-Mail gesendet!")
 (:auth-resend-success-detail . "Überprüfe deinen Posteingang für den neuen Aktivierungslink.")
 (:auth-resend-rate-limited . "Bitte warte einige Minuten, bevor du eine weitere Aktivierungs-E-Mail anforderst.")
 (:auth-resend-cooldown . "Du kannst in ~a Sekunden eine weitere E-Mail anfordern.")
 (:auth-back-to-login . "Zurück zum Login")
 (:auth-forgot-password-title . "Passwort vergessen")
 (:auth-forgot-password-subtitle . "Gib deine E-Mail-Adresse ein und wir senden dir einen Link zum Zurücksetzen deines Passworts.")
 (:auth-send-reset-link . "Link zum Zurücksetzen senden")
 (:auth-reset-email-sent . "Link gesendet!")
 (:auth-reset-email-sent-detail . "Wenn ein Konto mit dieser E-Mail existiert, erhältst du in Kürze einen Link zum Zurücksetzen des Passworts.")
 (:auth-reset-rate-limited . "Bitte warte einige Minuten, bevor du eine weitere Passwort-Zurücksetzung anforderst.")
 (:auth-reset-invalid-token . "Dieser Link zum Zurücksetzen des Passworts ist ungültig oder abgelaufen.")
 (:auth-reset-password-title . "Passwort zurücksetzen")
 (:auth-reset-password-subtitle . "Gib unten dein neues Passwort ein.")
 (:auth-new-password . "Neues Passwort")
 (:auth-confirm-new-password . "Neues Passwort bestätigen")
 (:auth-reset-password . "Passwort zurücksetzen")
 (:auth-password-changed . "Passwort geändert!")
 (:auth-password-changed-detail . "Dein Passwort wurde erfolgreich geändert. Du kannst dich jetzt mit deinem neuen Passwort anmelden.")
 (:auth-change-password-title . "Passwort ändern")
 (:auth-change-password-subtitle . "Aktualisiere dein Kontopasswort.")
 (:auth-current-password . "Aktuelles Passwort")
 (:auth-change-password . "Passwort ändern")
 (:auth-back-to-app . "Zurück zur App")
 (:auth-password-updated . "Passwort aktualisiert!")
 (:auth-password-updated-detail . "Dein Passwort wurde erfolgreich aktualisiert.")

 ;; Translation page
 (:translate-title . "Übersetzen")
 (:translate-input-label . "Text zum Übersetzen")
 (:translate-input-placeholder . "Text zum Übersetzen eingeben...")
 (:translate-from . "Von:")
 (:translate-to . "Nach:")
 (:translate-submit . "Übersetzen")
 (:translate-save . "Als Karteikarte speichern")
 (:translate-saved . "Gespeichert!")
 (:translate-like . "Gefällt mir")
 (:translate-dislike . "Gefällt mir nicht")
 (:translate-char-limit . "Zeichen übrig")
 (:translate-auto-detect . "Beliebig (Automatisch erkennen)")
 (:translate-empty-state . "Gib oben Text ein und klicke auf Übersetzen, um das Ergebnis mit Grammatikanalyse zu sehen")
 (:translate-like-tooltip . "Gute Übersetzung")
 (:translate-dislike-tooltip . "Schlechte Übersetzung - neue anfordern")
 (:translate-dislike-confirm . "Dies generiert eine neue Übersetzung. Fortfahren?")
 (:translate-liked . "Gefällt!")

 ;; Flashcard review
 (:review-title . "Wiederholen")
 (:review-session-title . "Wiederholungssitzung")
 (:review-session-subtitle . "Übe deine gespeicherten Karteikarten")
 (:review-start . "Wiederholung starten")
 (:review-no-cards . "Keine Karten zur Wiederholung")
 (:review-no-cards-desc . "Du hast gerade keine Karteikarten zur Wiederholung fällig.")
 (:review-no-cards-hint . "Übersetze Text und klicke auf \"Als Karteikarte speichern\", um dein Deck aufzubauen!")
 (:review-start-translating . "Übersetzen starten")
 (:review-show-answer . "Antwort zeigen")
 (:review-click-reveal . "Klicken um Antwort anzuzeigen")
 (:review-grammar-breakdown . "Grammatikanalyse")
 (:review-how-well . "Wie gut hast du dich erinnert?")
 (:review-again . "Nochmal")
 (:review-hard . "Schwer")
 (:review-good . "Gut")
 (:review-easy . "Leicht")
 (:review-progress . "Karte ~a von ~a")
 (:review-complete . "Sitzung abgeschlossen!")
 (:review-complete-msg . "Du hast ~a Karten wiederholt")
 (:review-correct . "Richtig")
 (:review-accuracy . "Genauigkeit")
 (:review-again-btn . "Erneut wiederholen")
 (:review-translate-more . "Mehr übersetzen")
 (:review-streak . "Tage Serie")

 ;; Dashboard
 (:dashboard-title . "Dashboard")
 (:dashboard-cards-due . "Fällige Karten")
 (:dashboard-total-cards . "Karten insgesamt")
 (:dashboard-subscription . "Abonnement")
 (:dashboard-subscribed-until . "Abonniert bis")
 (:dashboard-not-subscribed . "Nicht abonniert")
 (:dashboard-recent . "Letzte Übersetzungen")
 (:dashboard-no-translations . "Noch keine Übersetzungen")
 (:dashboard-streak . "Wiederholungsserie")
 (:dashboard-days . "Tage")
 (:dashboard-quick-actions . "Schnellaktionen")
 (:dashboard-getting-started . "Erste Schritte")
 (:dashboard-tip-1 . "Übersetze Text, den du lernen möchtest")
 (:dashboard-tip-2 . "Klicke bei Übersetzungen auf \"Als Karteikarte speichern\", die du behalten möchtest")
 (:dashboard-tip-3 . "Wiederhole deine Karteikarten regelmäßig - Spaced Repetition hilft beim langfristigen Behalten")
 (:dashboard-tip-4 . "Bewerte ehrlich - das hilft dem Algorithmus, deine Wiederholungen optimal zu planen")

 ;; Subscription
 (:subscribe-title . "Einfache Preise")
 (:subscribe-choose-plan . "Wähle deinen Plan")
 (:subscribe-start-today . "Starte heute mit einer 7-tägigen kostenlosen Testphase")
 (:subscribe-monthly . "Monatlich")
 (:subscribe-annual . "Jährlich")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/Monat")
 (:subscribe-per-year . "/Jahr")
 (:subscribe-monthly-desc . "600 Übersetzungen pro Monat")
 (:subscribe-unlimited-flashcards . "Unbegrenzte Karteikarten")
 (:subscribe-grammar-explanations . "Grammatikerklärungen")
 (:subscribe-spaced-repetition . "Spaced Repetition")
 (:subscribe-annual-desc . "Spare 20€ — zwei Monate gratis!")
 (:subscribe-cta . "Abonnieren")
 (:subscribe-success . "Abonnement erfolgreich!")
 (:subscribe-manage . "Abonnement verwalten")
 (:subscribe-activated . "Abonnement aktiviert!")
 (:subscribe-thank-you . "Vielen Dank für dein Abonnement. Dein Konto ist jetzt aktiv.")
 (:subscribe-start-learning . "Jetzt lernen")
 (:subscribe-management . "Abonnementverwaltung")
 (:subscribe-active . "Aktives Abonnement")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Aktiv")
 (:subscribe-days-remaining . "Verbleibende Tage:")
 (:subscribe-renews-on . "Verlängert am:")
 (:subscribe-no-subscription . "Kein aktives Abonnement")
 (:subscribe-access-features . "Abonniere, um alle Funktionen freizuschalten.")
 (:subscribe-view-plans . "Pläne ansehen")
 (:subscribe-faq-title . "Häufig gestellte Fragen")
 (:subscribe-faq-trial-q . "Was passiert nach der kostenlosen Testphase?")
 (:subscribe-faq-trial-a . "Nach deiner 7-tägigen kostenlosen Testphase wird der gewählte Plan berechnet. Du kannst jederzeit vor Ende der Testphase kündigen.")
 (:subscribe-faq-cancel-q . "Kann ich jederzeit kündigen?")
 (:subscribe-faq-cancel-a . "Ja! Du kannst dein Abonnement jederzeit kündigen. Du behältst den Zugang bis zum Ende deines Abrechnungszeitraums.")
 (:subscribe-faq-payment-q . "Welche Zahlungsmethoden akzeptiert ihr?")
 (:subscribe-faq-payment-a . "Wir akzeptieren alle gängigen Kredit- und Debitkarten über unseren Zahlungspartner Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Etwas ist schiefgelaufen")
 (:error-not-found . "Seite nicht gefunden")
 (:error-unauthorized . "Bitte melde dich an, um fortzufahren")
 (:error-subscription-required . "Abonnement erforderlich")
 (:error-text-too-long . "Text ist zu lang. Die maximale Übersetzungslänge beträgt 120 Zeichen.")
 (:error-input-too-long . "Eingabe zu lang")
 (:error-unknown-source-lang . "Die ausgewählte Ausgangssprache wird nicht unterstützt.")
 (:error-unknown-target-lang . "Die ausgewählte Zielsprache wird nicht unterstützt.")
 (:error-unknown-language . "Unbekannte Sprache")
 (:error-translation-unavailable . "Der Übersetzungsdienst ist vorübergehend nicht verfügbar. Bitte versuche es gleich noch einmal.")
 (:error-translation-failed . "Übersetzung fehlgeschlagen")
 (:error-translation-retry . "Konnte nach mehreren Versuchen keine Übersetzung generieren. Bitte formuliere deinen Text um.")
 (:error-quota-exceeded . "Übersetzungslimit erreicht")
 (:error-quota-exceeded-detail . "Du hast alle Übersetzungen für diesen Monat aufgebraucht. Dein Kontingent wird automatisch jeden Monat zurückgesetzt.")
 (:loading . "Lädt...")
 (:empty-state . "Hier ist noch nichts")

 ;; Footer
 (:footer-privacy . "Datenschutz")
 (:footer-terms . "Nutzungsbedingungen")
 (:footer-contact . "Kontakt")

 ;; Early software notice
 (:early-software-notice . "Hiisi befindet sich in früher Entwicklung. Einen Fehler gefunden oder einen Vorschlag?")
 (:early-software-contact . "Kontaktiere uns unter")
)
