;;; English translations (base language)
;;; This is the authoritative source for all translation keys

(
 ;; Language metadata (used for language picker)
 (:lang-name . "English")
 (:lang-flag . "🇬🇧")

 ;; Navigation
 (:nav-translate . "Translate")
 (:nav-review . "Review")
 (:nav-dashboard . "Dashboard")
 (:nav-logout . "Logout")
 (:nav-home . "Home")
 (:nav-pricing . "Pricing")
 (:nav-export-data . "Export Data")

 ;; App title and branding
 (:app-title . "Hiisi")
 (:app-tagline . "Learn languages through translations")

 ;; Landing page
 (:landing-hero-title . "Master Any Language")
 (:landing-hero-subtitle . "Translate anything. Automatically generate flashcards that teach you why it works that way.")
 (:landing-cta . "Start Learning")
 (:landing-learn-more . "Learn More")
 (:landing-how-it-works . "How It Works")
 (:landing-feature-1-title . "Automatic Flashcards")
 (:landing-feature-1-desc . "Every translation automatically generates flashcards with grammar breakdowns. No manual card creation.")
 (:landing-feature-2-title . "Spaced Repetition")
 (:landing-feature-2-desc . "SM-2 algorithm schedules reviews at optimal intervals. Learn efficiently, remember permanently.")
 (:landing-feature-3-title . "Grammar Teaching")
 (:landing-feature-3-desc . "Every translation explains grammar, word roots, and sentence structure. Understand the why, not just the what.")
 (:landing-free-trial . "7-day free trial. No credit card required.")
 (:landing-start-trial . "Start Free Trial")
 (:landing-best-value . "Best Value")
 (:landing-cta-title . "Ready to learn languages through grammar, not memorization?")
 (:landing-cta-subtitle . "Every translation becomes a learning opportunity. Every flashcard teaches you why.")
 (:landing-signup-free . "Sign Up Free")

 ;; Auth pages
 (:auth-register . "Register")
 (:auth-login . "Login")
 (:auth-logout . "Logout")
 (:auth-email . "Email")
 (:auth-password . "Password")
 (:auth-password-again . "Confirm Password")
 (:auth-display-name . "Display Name")
 (:auth-register-title . "Register to Hiisi")
 (:auth-register-subtitle . "Create a new account")
 (:auth-login-title . "Login to Hiisi")
 (:auth-login-subtitle . "Enter your credentials")
 (:auth-forgot-password . "Forgot password?")
 (:auth-no-account . "Don't have an account?")
 (:auth-have-account . "Already have an account?")
 (:auth-google . "Google")
 (:auth-account-created . "Account created!")
 (:auth-check-email . "Check your email for the activation link.")
 (:auth-redirect-login . "Redirecting to login in")
 (:auth-seconds . "seconds...")
 (:auth-go-now . "Go now")
 (:auth-not-activated . "Account not activated")
 (:auth-activate-title . "Activate your account!")
 (:auth-activated . "Account Activated!")
 (:auth-activated-message . "Your account has been activated. You can now use Hiisi.")
 (:auth-redirecting . "Redirecting in")
 (:auth-go-to-app . "Go to App")
 (:auth-resend-title . "Resend Activation Email")
 (:auth-resend-subtitle . "Enter your email to receive a new activation link.")
 (:auth-resend-button . "Resend Activation Email")
 (:auth-resend-success . "Activation email sent!")
 (:auth-resend-success-detail . "Check your inbox for the new activation link.")
 (:auth-resend-rate-limited . "Please wait a few minutes before requesting another activation email.")
 (:auth-resend-cooldown . "You can request another email in ~a seconds.")
 (:auth-back-to-login . "Back to Login")
 (:auth-forgot-password-title . "Forgot Password")
 (:auth-forgot-password-subtitle . "Enter your email and we'll send you a link to reset your password.")
 (:auth-send-reset-link . "Send Reset Link")
 (:auth-reset-email-sent . "Reset link sent!")
 (:auth-reset-email-sent-detail . "If an account exists with that email, you'll receive a password reset link shortly.")
 (:auth-reset-rate-limited . "Please wait a few minutes before requesting another password reset.")
 (:auth-reset-invalid-token . "This password reset link is invalid or has expired.")
 (:auth-reset-password-title . "Reset Password")
 (:auth-reset-password-subtitle . "Enter your new password below.")
 (:auth-new-password . "New Password")
 (:auth-confirm-new-password . "Confirm New Password")
 (:auth-reset-password . "Reset Password")
 (:auth-password-changed . "Password changed!")
 (:auth-password-changed-detail . "Your password has been successfully changed. You can now log in with your new password.")
 (:auth-change-password-title . "Change Password")
 (:auth-change-password-subtitle . "Update your account password.")
 (:auth-current-password . "Current Password")
 (:auth-change-password . "Change Password")
 (:auth-back-to-app . "Back to App")
 (:auth-password-updated . "Password updated!")
 (:auth-password-updated-detail . "Your password has been successfully updated.")

 ;; Translation page
 (:translate-title . "Translate")
 (:translate-input-label . "Text to translate")
 (:translate-input-placeholder . "Enter text to translate...")
 (:translate-from . "From:")
 (:translate-to . "To:")
 (:translate-submit . "Translate")
 (:translate-save . "Save to Flashcards")
 (:translate-saved . "Saved!")
 (:translate-like . "Like")
 (:translate-dislike . "Dislike")
 (:translate-char-limit . "characters remaining")
 (:translate-auto-detect . "Any (Auto-detect)")
 (:translate-empty-state . "Enter text above and click Translate to see the result with grammar breakdown")
 (:translate-like-tooltip . "Good translation")
 (:translate-dislike-tooltip . "Bad translation - request a new one")
 (:translate-dislike-confirm . "This will generate a new translation. Continue?")
 (:translate-liked . "Liked!")

 ;; Flashcard review
 (:review-title . "Review")
 (:review-session-title . "Review Session")
 (:review-session-subtitle . "Practice your saved flashcards")
 (:review-start . "Start Review")
 (:review-no-cards . "No Cards to Review")
 (:review-no-cards-desc . "You don't have any flashcards due for review right now.")
 (:review-no-cards-hint . "Translate some text and click \"Save to Flashcards\" to build your deck!")
 (:review-start-translating . "Start Translating")
 (:review-show-answer . "Show Answer")
 (:review-click-reveal . "Click to reveal answer")
 (:review-grammar-breakdown . "Grammar Breakdown")
 (:review-how-well . "How well did you remember?")
 (:review-again . "Again")
 (:review-hard . "Hard")
 (:review-good . "Good")
 (:review-easy . "Easy")
 (:review-progress . "Card ~a of ~a")
 (:review-complete . "Session Complete!")
 (:review-complete-msg . "You reviewed ~a cards")
 (:review-correct . "Correct")
 (:review-accuracy . "Accuracy")
 (:review-again-btn . "Review Again")
 (:review-translate-more . "Translate More")
 (:review-streak . "day streak")

 ;; Dashboard
 (:dashboard-title . "Dashboard")
 (:dashboard-cards-due . "Cards Due")
 (:dashboard-total-cards . "Total Cards")
 (:dashboard-subscription . "Subscription")
 (:dashboard-subscribed-until . "Subscribed until")
 (:dashboard-not-subscribed . "Not subscribed")
 (:dashboard-recent . "Recent Translations")
 (:dashboard-no-translations . "No translations yet")
 (:dashboard-streak . "Review Streak")
 (:dashboard-days . "days")
 (:dashboard-quick-actions . "Quick Actions")
 (:dashboard-getting-started . "Getting Started")
 (:dashboard-tip-1 . "Translate text you want to learn")
 (:dashboard-tip-2 . "Click \"Save to Flashcards\" on translations you want to remember")
 (:dashboard-tip-3 . "Review your flashcards regularly - spaced repetition helps you remember long-term")
 (:dashboard-tip-4 . "Rate honestly - it helps the algorithm schedule your reviews optimally")

 ;; Subscription
 (:subscribe-title . "Simple Pricing")
 (:subscribe-choose-plan . "Choose Your Plan")
 (:subscribe-start-today . "Start learning today with a 7-day free trial")
 (:subscribe-monthly . "Monthly")
 (:subscribe-annual . "Annual")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/month")
 (:subscribe-per-year . "/year")
 (:subscribe-monthly-desc . "600 translations per month")
 (:subscribe-unlimited-flashcards . "Unlimited flashcards")
 (:subscribe-grammar-explanations . "Grammar explanations")
 (:subscribe-spaced-repetition . "Spaced repetition")
 (:subscribe-annual-desc . "Save €20 — two months free!")
 (:subscribe-cta . "Subscribe")
 (:subscribe-success . "Subscription Successful!")
 (:subscribe-manage . "Manage Subscription")
 (:subscribe-activated . "Subscription Activated!")
 (:subscribe-thank-you . "Thank you for subscribing. Your account is now active.")
 (:subscribe-start-learning . "Start Learning")
 (:subscribe-management . "Subscription Management")
 (:subscribe-active . "Active Subscription")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Active")
 (:subscribe-days-remaining . "Days remaining:")
 (:subscribe-renews-on . "Renews on:")
 (:subscribe-no-subscription . "No Active Subscription")
 (:subscribe-access-features . "Subscribe to access all features.")
 (:subscribe-view-plans . "View Plans")
 (:subscribe-faq-title . "Frequently Asked Questions")
 (:subscribe-faq-trial-q . "What happens after the free trial?")
 (:subscribe-faq-trial-a . "After your 7-day free trial, you'll be charged for your selected plan. You can cancel anytime before the trial ends.")
 (:subscribe-faq-cancel-q . "Can I cancel anytime?")
 (:subscribe-faq-cancel-a . "Yes! You can cancel your subscription at any time. You'll keep access until the end of your billing period.")
 (:subscribe-faq-payment-q . "What payment methods do you accept?")
 (:subscribe-faq-payment-a . "We accept all major credit cards and debit cards through our payment partner Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Something went wrong")
 (:error-not-found . "Page not found")
 (:error-unauthorized . "Please log in to continue")
 (:error-subscription-required . "Subscription required")
 (:error-text-too-long . "Text is too long. Maximum translation length is 120 characters.")
 (:error-input-too-long . "Input Too Long")
 (:error-unknown-source-lang . "The source language you selected is not supported.")
 (:error-unknown-target-lang . "The target language you selected is not supported.")
 (:error-unknown-language . "Unknown Language")
 (:error-translation-unavailable . "Translation service is temporarily unavailable. Please try again in a moment.")
 (:error-translation-failed . "Translation Failed")
 (:error-translation-retry . "Unable to generate a translation after multiple attempts. Please try rephrasing your text.")
 (:error-quota-exceeded . "Translation Limit Reached")
 (:error-quota-exceeded-detail . "You've used all your translations for this month. Your quota resets automatically each month.")
 (:loading . "Loading...")
 (:empty-state . "Nothing here yet")

 ;; Footer
 (:footer-privacy . "Privacy Policy")
 (:footer-terms . "Terms of Service")
 (:footer-contact . "Contact")

 ;; Early software notice
 (:early-software-notice . "Hiisi is in early development. Found a bug or have a suggestion?")
 (:early-software-contact . "Contact us at")
)
