;;; English translations (base language)
;;; This is the authoritative source for all translation keys

(
 ;; Language metadata (used for language picker)
 (:lang-name . "English")
 (:lang-flag . "🇬🇧")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Choose Your Language")
 (:lang-modal-subtitle . "Select your preferred language for the interface:")

 ;; Navigation
 (:nav-translate . "Translate")
 (:nav-review . "Review")
 (:nav-dashboard . "Dashboard")
 (:nav-logout . "Logout")
 (:nav-home . "Home")
 (:nav-pricing . "Pricing")
 (:nav-export-data . "Export Data")

 ;; App title and branding
 (:app-title . "Hiisi")
 (:app-tagline . "Learn languages through translations")

 ;; Landing page
 (:landing-hero-title . "Master Any Language")
 (:landing-hero-subtitle . "Translate anything. Automatically generate flashcards that teach you why it works that way.")
 (:landing-cta . "Start Learning")
 (:landing-learn-more . "Learn More")
 (:landing-how-it-works . "How It Works")
 (:landing-feature-1-title . "Automatic Flashcards")
 (:landing-feature-1-desc . "Every translation automatically generates flashcards with grammar breakdowns. No manual card creation.")
 (:landing-feature-2-title . "Spaced Repetition")
 (:landing-feature-2-desc . "SM-2 algorithm schedules reviews at optimal intervals. Learn efficiently, remember permanently.")
 (:landing-feature-3-title . "Grammar Teaching")
 (:landing-feature-3-desc . "Every translation explains grammar, word roots, and sentence structure. Understand the why, not just the what.")
 (:landing-free-trial . "7-day free trial. No credit card required.")
 (:landing-start-trial . "Start Free Trial")
 (:landing-best-value . "Best Value")
 (:landing-cta-title . "Ready to learn languages through grammar, not memorization?")
 (:landing-cta-subtitle . "Every translation becomes a learning opportunity. Every flashcard teaches you why.")
 (:landing-signup-free . "Sign Up Free")

 ;; Auth pages
 (:auth-register . "Register")
 (:auth-login . "Login")
 (:auth-logout . "Logout")
 (:auth-email . "Email")
 (:auth-password . "Password")
 (:auth-password-again . "Confirm Password")
 (:auth-display-name . "Display Name")
 (:auth-register-title . "Register to Hiisi")
 (:auth-register-subtitle . "Create a new account")
 (:auth-login-title . "Login to Hiisi")
 (:auth-login-subtitle . "Enter your credentials")
 (:auth-forgot-password . "Forgot password?")
 (:auth-no-account . "Don't have an account?")
 (:auth-have-account . "Already have an account?")
 (:auth-google . "Google")
 (:auth-account-created . "Account created!")
 (:auth-check-email . "Check your email for the activation link.")
 (:auth-redirect-login . "Redirecting to login in")
 (:auth-seconds . "seconds...")
 (:auth-go-now . "Go now")
 (:auth-not-activated . "Account not activated")
 (:auth-activate-title . "Activate your account!")
 (:auth-activated . "Account Activated!")
 (:auth-activated-message . "Your account has been activated. You can now use Hiisi.")
 (:auth-redirecting . "Redirecting in")
 (:auth-go-to-app . "Go to App")
 (:auth-resend-title . "Resend Activation Email")
 (:auth-resend-subtitle . "Enter your email to receive a new activation link.")
 (:auth-resend-button . "Resend Activation Email")
 (:auth-resend-success . "Activation email sent!")
 (:auth-resend-success-detail . "Check your inbox for the new activation link.")
 (:auth-resend-rate-limited . "Please wait a few minutes before requesting another activation email.")
 (:auth-resend-cooldown . "You can request another email in ~a seconds.")
 (:auth-back-to-login . "Back to Login")
 (:auth-forgot-password-title . "Forgot Password")
 (:auth-forgot-password-subtitle . "Enter your email and we'll send you a link to reset your password.")
 (:auth-send-reset-link . "Send Reset Link")
 (:auth-reset-email-sent . "Reset link sent!")
 (:auth-reset-email-sent-detail . "If an account exists with that email, you'll receive a password reset link shortly.")
 (:auth-reset-rate-limited . "Please wait a few minutes before requesting another password reset.")
 (:auth-reset-invalid-token . "This password reset link is invalid or has expired.")
 (:auth-reset-password-title . "Reset Password")
 (:auth-reset-password-subtitle . "Enter your new password below.")
 (:auth-new-password . "New Password")
 (:auth-confirm-new-password . "Confirm New Password")
 (:auth-reset-password . "Reset Password")
 (:auth-password-changed . "Password changed!")
 (:auth-password-changed-detail . "Your password has been successfully changed. You can now log in with your new password.")
 (:auth-change-password-title . "Change Password")
 (:auth-change-password-subtitle . "Update your account password.")
 (:auth-current-password . "Current Password")
 (:auth-change-password . "Change Password")
 (:auth-back-to-app . "Back to App")
 (:auth-password-updated . "Password updated!")
 (:auth-password-updated-detail . "Your password has been successfully updated.")

 ;; Translation page
 (:translate-title . "Translate")
 (:translate-input-label . "Text to translate")
 (:translate-input-placeholder . "Enter text to translate...")
 (:translate-from . "From:")
 (:translate-to . "To:")
 (:translate-submit . "Translate")
 (:translate-save . "Save to Flashcards")
 (:translate-saved . "Saved!")
 (:translate-like . "Like")
 (:translate-dislike . "Dislike")
 (:translate-char-limit . "characters remaining")
 (:translate-auto-detect . "Any (Auto-detect)")
 (:translate-empty-state . "Enter text above and click Translate to see the result with grammar breakdown")
 (:translate-like-tooltip . "Good translation")
 (:translate-dislike-tooltip . "Bad translation - request a new one")
 (:translate-dislike-confirm . "This will generate a new translation. Continue?")
 (:translate-liked . "Liked!")

 ;; Flashcard review
 (:review-title . "Review")
 (:review-session-title . "Review Session")
 (:review-session-subtitle . "Practice your saved flashcards")
 (:review-start . "Start Review")
 (:review-no-cards . "No Cards to Review")
 (:review-no-cards-desc . "You don't have any flashcards due for review right now.")
 (:review-no-cards-hint . "Translate some text and click \"Save to Flashcards\" to build your deck!")
 (:review-start-translating . "Start Translating")
 (:review-show-answer . "Show Answer")
 (:review-click-reveal . "Click to reveal answer")
 (:review-grammar-breakdown . "Grammar Breakdown")
 (:review-how-well . "How well did you remember?")
 (:review-again . "Again")
 (:review-hard . "Hard")
 (:review-good . "Good")
 (:review-easy . "Easy")
 (:review-progress . "Card ~a of ~a")
 (:review-complete . "Session Complete!")
 (:review-complete-msg . "You reviewed ~a cards")
 (:review-correct . "Correct")
 (:review-accuracy . "Accuracy")
 (:review-again-btn . "Review Again")
 (:review-translate-more . "Translate More")
 (:review-streak . "day streak")

 ;; Dashboard
 (:dashboard-title . "Dashboard")
 (:dashboard-cards-due . "Cards Due")
 (:dashboard-total-cards . "Total Cards")
 (:dashboard-subscription . "Subscription")
 (:dashboard-subscribed-until . "Subscribed until")
 (:dashboard-not-subscribed . "Not subscribed")
 (:dashboard-recent . "Recent Translations")
 (:dashboard-no-translations . "No translations yet")
 (:dashboard-streak . "Review Streak")
 (:dashboard-days . "days")
 (:dashboard-quick-actions . "Quick Actions")
 (:dashboard-getting-started . "Getting Started")
 (:dashboard-tip-1 . "Translate text you want to learn")
 (:dashboard-tip-2 . "Click \"Save to Flashcards\" on translations you want to remember")
 (:dashboard-tip-3 . "Review your flashcards regularly - spaced repetition helps you remember long-term")
 (:dashboard-tip-4 . "Rate honestly - it helps the algorithm schedule your reviews optimally")

 ;; Subscription
 (:subscribe-title . "Simple Pricing")
 (:subscribe-choose-plan . "Choose Your Plan")
 (:subscribe-start-today . "Start learning today with a 7-day free trial")
 (:subscribe-monthly . "Monthly")
 (:subscribe-annual . "Annual")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/month")
 (:subscribe-per-year . "/year")
 (:subscribe-monthly-desc . "600 translations per month")
 (:subscribe-unlimited-flashcards . "Unlimited flashcards")
 (:subscribe-grammar-explanations . "Grammar explanations")
 (:subscribe-spaced-repetition . "Spaced repetition")
 (:subscribe-annual-desc . "Save €20 — two months free!")
 (:subscribe-cta . "Subscribe")
 (:subscribe-success . "Subscription Successful!")
 (:subscribe-manage . "Manage Subscription")
 (:subscribe-activated . "Subscription Activated!")
 (:subscribe-thank-you . "Thank you for subscribing. Your account is now active.")
 (:subscribe-start-learning . "Start Learning")
 (:subscribe-management . "Subscription Management")
 (:subscribe-active . "Active Subscription")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Active")
 (:subscribe-days-remaining . "Days remaining:")
 (:subscribe-renews-on . "Renews on:")
 (:subscribe-no-subscription . "No Active Subscription")
 (:subscribe-access-features . "Subscribe to access all features.")
 (:subscribe-view-plans . "View Plans")
 (:subscribe-faq-title . "Frequently Asked Questions")
 (:subscribe-faq-trial-q . "What happens after the free trial?")
 (:subscribe-faq-trial-a . "After your 7-day free trial, you'll be charged for your selected plan. You can cancel anytime before the trial ends.")
 (:subscribe-faq-cancel-q . "Can I cancel anytime?")
 (:subscribe-faq-cancel-a . "Yes! You can cancel your subscription at any time. You'll keep access until the end of your billing period.")
 (:subscribe-faq-payment-q . "What payment methods do you accept?")
 (:subscribe-faq-payment-a . "We accept all major credit cards and debit cards through our payment partner Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Something went wrong")
 (:error-not-found . "Page not found")
 (:error-unauthorized . "Please log in to continue")
 (:error-subscription-required . "Subscription required")
 (:error-text-too-long . "Text is too long. Maximum translation length is 120 characters.")
 (:error-input-too-long . "Input Too Long")
 (:error-unknown-source-lang . "The source language you selected is not supported.")
 (:error-unknown-target-lang . "The target language you selected is not supported.")
 (:error-unknown-language . "Unknown Language")
 (:error-translation-unavailable . "Translation service is temporarily unavailable. Please try again in a moment.")
 (:error-translation-failed . "Translation Failed")
 (:error-translation-retry . "Unable to generate a translation after multiple attempts. Please try rephrasing your text.")
 (:error-quota-exceeded . "Translation Limit Reached")
 (:error-quota-exceeded-detail . "You've used all your translations for this month. Your quota resets automatically each month.")
 (:loading . "Loading...")
 (:empty-state . "Nothing here yet")

 ;; Footer
 (:footer-privacy . "Privacy Policy")
 (:footer-terms . "Terms of Service")
 (:footer-contact . "Contact")

 ;; Early software notice
 (:early-software-notice . "Hiisi is in early development. Found a bug or have a suggestion?")
 (:early-software-contact . "Contact us at")

 ;; Privacy Policy
 (:privacy-title . "Privacy Policy")
 (:privacy-updated . "Last updated: January 2026")
 (:privacy-who-title . "Who We Are")
 (:privacy-who-body . "Hiisi is operated by Lambda Symbolics OÜ, a company registered in Estonia. As an Estonian company, we comply with the European Union's General Data Protection Regulation (GDPR).")
 (:privacy-collect-title . "Data We Collect")
 (:privacy-collect-intro . "We collect the following information when you use Hiisi:")
 (:privacy-collect-account-key . "Account information: ")
 (:privacy-collect-account-val . "Email address, display name, and a securely hashed password.")
 (:privacy-collect-learning-key . "Learning data: ")
 (:privacy-collect-learning-val . "Your translations, saved flashcards, and review history.")
 (:privacy-collect-usage-key . "Usage data: ")
 (:privacy-collect-usage-val . "Basic server logs for security and debugging purposes.")
 (:privacy-use-title . "How We Use Your Data")
 (:privacy-use-auth-key . "Authentication: ")
 (:privacy-use-auth-val . "To verify your identity and secure your account.")
 (:privacy-use-service-key . "Service delivery: ")
 (:privacy-use-service-val . "To provide translations and manage your flashcard collection.")
 (:privacy-use-ai-key . "AI translations: ")
 (:privacy-use-ai-val . "Your translation requests are sent to Anthropic's Claude API to generate responses. See Anthropic's privacy policy for how they handle this data.")
 (:privacy-third-title . "Third-Party Services")
 (:privacy-third-intro . "We use the following third-party services:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "For AI-powered translations.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "For sending account activation and transactional emails.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "For subscription payment processing.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "We use only essential cookies:")
 (:privacy-cookies-auth-key . "Authentication token: ")
 (:privacy-cookies-auth-val . "A secure, HTTP-only cookie to keep you logged in.")
 (:privacy-cookies-lang-key . "Language preference: ")
 (:privacy-cookies-lang-val . "To remember your preferred UI language.")
 (:privacy-retention-title . "Data Retention")
 (:privacy-retention-body . "Your data is stored as long as you maintain an account. When you request deletion, your account is scheduled for deletion in 14 days.")
 (:privacy-rights-title . "Your Rights (GDPR)")
 (:privacy-rights-intro . "Under GDPR, you have the right to:")
 (:privacy-rights-access . "Access your personal data")
 (:privacy-rights-export . "Export your data (available at /app/api/export)")
 (:privacy-rights-correct . "Request correction of inaccurate data")
 (:privacy-rights-delete . "Request deletion of your account and data")
 (:privacy-rights-object . "Object to processing of your data")
 (:privacy-rights-contact . "To exercise these rights, contact us at")
 (:privacy-contact-title . "Contact")
 (:privacy-contact-intro . "For privacy-related inquiries:")
 (:privacy-contact-email-label . "Email: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Estonia")

 ;; Terms of Service
 (:terms-title . "Terms of Service")
 (:terms-updated . "Last updated: January 2026")
 (:terms-1-title . "1. Service Description")
 (:terms-1-body . "Hiisi is a language learning application that provides AI-powered translations with grammatical explanations and spaced repetition flashcards. The service is operated by Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Account Registration")
 (:terms-2-body . "To use Hiisi, you must create an account with a valid email address. You are responsible for maintaining the security of your account credentials.")
 (:terms-3-title . "3. Subscription and Payments")
 (:terms-3-body . "Hiisi offers paid subscription plans (monthly and annual). Subscriptions are processed through Polar.sh.")
 (:terms-3-list-1 . "Subscriptions auto-renew unless cancelled before the renewal date.")
 (:terms-3-list-2 . "Refunds are provided in accordance with applicable consumer protection laws.")
 (:terms-3-list-3 . "Non-payment results in loss of access to premium features.")
 (:terms-4-title . "4. Acceptable Use")
 (:terms-4-intro . "You agree not to:")
 (:terms-4-list-1 . "Use the service for any illegal purpose")
 (:terms-4-list-2 . "Attempt to circumvent usage limits or security measures")
 (:terms-4-list-3 . "Share your account credentials with others")
 (:terms-4-list-4 . "Use automated tools to access the service in a way that degrades performance for others")
 (:terms-5-title . "5. Content and Intellectual Property")
 (:terms-5-body-1 . "Translations generated by Hiisi are created using AI and may not be unique. You may use your translations and flashcards for any personal purpose, but you do not hold exclusive authorship rights over AI-generated content.")
 (:terms-5-body-2 . "The Hiisi application, branding, and original content remain the property of Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Service Availability")
 (:terms-6-intro . "Hiisi is provided on an \"as-is\" basis. We do not guarantee:")
 (:terms-6-list-1 . "Uninterrupted or error-free service")
 (:terms-6-list-2 . "Accuracy of AI-generated translations")
 (:terms-6-list-3 . "Availability of specific features")
 (:terms-6-body . "We may modify or discontinue features at any time.")
 (:terms-7-title . "7. Limitation of Liability")
 (:terms-7-body-1 . "To the maximum extent permitted by law, Lambda Symbolics OÜ shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of Hiisi.")
 (:terms-7-body-2 . "Our total liability shall not exceed the amount you paid for the service in the 12 months preceding the claim.")
 (:terms-8-title . "8. Account Termination")
 (:terms-8-body-1 . "We may suspend or terminate your account if you violate these terms. You may request account deletion at any time through the application.")
 (:terms-8-body-2 . "Upon deletion request, your account is scheduled for deletion in 14 days.")
 (:terms-9-title . "9. Changes to Terms")
 (:terms-9-body . "We may update these terms from time to time. Continued use of Hiisi after changes constitutes acceptance of the new terms.")
 (:terms-10-title . "10. Governing Law")
 (:terms-10-body . "These terms are governed by the laws of Estonia. Any disputes shall be resolved in the courts of Estonia.")
 (:terms-contact-title . "Contact")
 (:terms-contact-intro . "For questions about these terms:")
 (:terms-contact-email-label . "Email: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Estonia")



 ;; Decks
 (:decks-title . "Decks")
 (:decks-subtitle . "Create custom decks and share them with others.")
 (:decks-create-title . "Create Deck")
 (:decks-name-placeholder . "Deck name")
 (:decks-desc-placeholder . "Description")
 (:decks-create-btn . "Create deck")
 (:decks-your-title . "Your Decks")
 (:decks-col-name . "Name")
 (:decks-col-desc . "Description")
 (:decks-col-updated . "Updated")
 (:decks-col-actions . "Actions")
 (:decks-no-decks . "No decks yet.")
 (:decks-open-btn . "Open")
 (:decks-no-desc . "No description.")
 (:decks-share-title . "Share Link")
 (:decks-share-info . "Anyone with this link can import the deck:")
 (:decks-add-trans-title . "Add Translation")
 (:decks-trans-id-placeholder . "Translation ID")
 (:decks-add-trans-btn . "Add translation")
 (:decks-items-title . "Deck Items")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Translated")
 (:decks-col-lang . "Lang To")
 (:decks-no-items . "No items yet.")
 (:decks-share-page-title . "Share Deck")
 (:decks-share-preview . "Preview and import this deck.")
 (:decks-import-title . "Import")
 (:decks-import-btn . "Import deck")

)
