;;; English translations (base language)
;;; This is the authoritative source for all translation keys

(
 ;; Language metadata (used for language picker)
 (:lang-name . "English")
 (:lang-flag . "🇬🇧")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Choose Your Language")
 (:lang-modal-subtitle . "Select your preferred language for the interface:")

 ;; Navigation
 (:nav-translate . "Translate")
 (:nav-review . "Review")
 (:nav-flashcards . "My Cards")
 (:nav-dashboard . "Dashboard")
 (:nav-decks . "Decks")
 (:nav-logout . "Logout")
 (:nav-home . "Home")
 (:nav-pricing . "Pricing")
 (:nav-export-data . "Export Data")

 ;; App title and branding
 (:app-title . "Hiisi - Language Learning")
 (:app-tagline . "Learn languages through translations")

 ;; Landing page
 (:landing-hero-title . "Master Any Language")
 (:landing-hero-subtitle . "Translate anything. Automatically generate flashcards that teach you why it works that way.")
 (:landing-cta . "Start Learning")
 (:landing-learn-more . "Learn More")
 (:landing-how-it-works . "How It Works")
 (:landing-feature-1-title . "Automatic Flashcards")
 (:landing-feature-1-desc . "Every translation automatically generates flashcards with grammar breakdowns. No manual card creation.")
 (:landing-feature-2-title . "Spaced Repetition")
 (:landing-feature-2-desc . "SM-2 algorithm schedules reviews at optimal intervals. Learn efficiently, remember permanently.")
 (:landing-feature-3-title . "Grammar Teaching")
 (:landing-feature-3-desc . "Every translation explains grammar, word roots, and sentence structure. Understand the why, not just the what.")
 (:landing-free-trial . "7-day free trial.")
 (:landing-start-trial . "Start Free Trial")
 (:landing-best-value . "Best Value")
 (:landing-cta-title . "Ready to learn languages through grammar, not memorization?")
 (:landing-cta-subtitle . "Every translation becomes a learning opportunity. Every flashcard teaches you why.")
 (:landing-signup-free . "Sign Up Free")

 ;; Auth pages
 (:auth-register . "Register")
 (:auth-login . "Login")
 (:auth-logout . "Logout")
 (:auth-email . "Email")
 (:auth-password . "Password")
 (:auth-password-again . "Confirm Password")
 (:auth-display-name . "Display Name")
 (:auth-register-title . "Register to Hiisi")
 (:auth-register-subtitle . "Create a new account")
 (:auth-login-title . "Login to Hiisi")
 (:auth-login-subtitle . "Enter your credentials")
 (:auth-login-invalid-credentials . "Invalid email or password.")
 (:auth-login-rate-limited . "Too many login attempts. Please wait a few minutes and try again.")
 (:auth-forgot-password . "Forgot password?")
 (:auth-no-account . "Don't have an account?")
 (:auth-have-account . "Already have an account?")
 (:auth-google . "Google")
 (:auth-account-created . "Account created!")
 (:auth-check-email . "Check your email for the activation link.")
 (:auth-redirect-login . "Redirecting to login in")
 (:auth-seconds . "seconds...")
 (:auth-go-now . "Go now")
 (:auth-not-activated . "Account not activated")
 (:auth-activate-title . "Activate your account!")
 (:auth-activated . "Account Activated!")
 (:auth-activated-message . "Your account has been activated. You can now use Hiisi.")
 (:auth-redirecting . "Redirecting in")
 (:auth-go-to-app . "Go to App")
 (:auth-resend-title . "Resend Activation Email")
 (:auth-resend-subtitle . "Enter your email to receive a new activation link.")
 (:auth-resend-button . "Resend Activation Email")
 (:auth-resend-success . "Activation email sent!")
 (:auth-resend-success-detail . "Check your inbox for the new activation link.")
 (:auth-resend-rate-limited . "Please wait a few minutes before requesting another activation email.")
 (:auth-resend-cooldown . "You can request another email in ~a seconds.")
 (:auth-back-to-login . "Back to Login")
 (:auth-forgot-password-title . "Forgot Password")
 (:auth-forgot-password-subtitle . "Enter your email and we'll send you a link to reset your password.")
 (:auth-send-reset-link . "Send Reset Link")
 (:auth-reset-email-sent . "Reset link sent!")
 (:auth-reset-email-sent-detail . "If an account exists with that email, you'll receive a password reset link shortly.")
 (:auth-reset-rate-limited . "Please wait a few minutes before requesting another password reset.")
 (:auth-reset-invalid-token . "This password reset link is invalid or has expired.")
 (:auth-reset-password-title . "Reset Password")
 (:auth-reset-password-subtitle . "Enter your new password below.")
 (:auth-new-password . "New Password")
 (:auth-confirm-new-password . "Confirm New Password")
 (:auth-reset-password . "Reset Password")
 (:auth-password-changed . "Password changed!")
 (:auth-password-changed-detail . "Your password has been successfully changed. You can now log in with your new password.")
 (:auth-change-password-title . "Change Password")
 (:auth-change-password-subtitle . "Update your account password.")
 (:auth-current-password . "Current Password")
 (:auth-change-password . "Change Password")
 (:auth-back-to-app . "Back to App")
 (:auth-password-updated . "Password updated!")
 (:auth-password-updated-detail . "Your password has been successfully updated.")

 ;; Translation page
 (:translate-title . "Translate")
 (:translate-input-label . "Text to translate")
 (:translate-input-placeholder . "Enter text to translate...")
 (:translate-from . "From:")
 (:translate-to . "To:")
 (:translate-submit . "Translate")
 (:translate-save . "Save to Flashcards")
 (:translate-saved . "Saved!")
 (:translate-like . "Like")
 (:translate-dislike . "Dislike")
 (:translate-char-limit . "characters remaining")
 (:translate-auto-detect . "Any (Auto-detect)")
 (:translate-empty-state . "Enter text above and click Translate to see the result with grammar breakdown")
 (:translate-select-deck-placeholder . "Select deck (optional)")
 (:translate-new-deck . "New deck")
 (:translate-add-to-deck . "Add to deck")
 (:translate-bookmark . "Bookmark")
 (:translate-bookmarked . "Bookmarked")
 (:translate-retry . "Retry")
 (:translate-like-tooltip . "Good translation")
 (:translate-dislike-tooltip . "Bad translation - request a new one")
 (:translate-dislike-confirm . "This will generate a new translation. Continue?")
 (:translate-liked . "Liked!")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Target")
 (:translate-deck-create-title . "Create New Deck")
 (:translate-deck-name-label . "Deck Name")
 (:translate-deck-name-placeholder . "e.g., Finnish Basics")
 (:translate-deck-description-label . "Description (optional)")
 (:translate-deck-cancel . "Cancel")
 (:translate-deck-create . "Create")
 (:translate-rate-label . "Rate translation")
 (:flashcards-delete-confirm . "Are you sure you want to delete this flashcard?")
 (:flashcards-deck-search-placeholder . "Search decks...")
 (:flashcards-no-decks . "No decks yet. Create one first!")
 (:flashcards-deck-cancel . "Cancel")
 (:flashcards-recollection-tooltip . "Recollection: ~A")
 (:flashcards-recollection-poor . "Poor")
 (:flashcards-recollection-fair . "Fair")
 (:flashcards-recollection-normal . "Normal")
 (:flashcards-recollection-strong . "Strong")
 (:flashcards-recollection-very-strong . "Very Strong")

 ;; Flashcard review
 (:review-title . "Review")
 (:review-session-title . "Review Session")
 (:review-session-subtitle . "Practice your saved flashcards")
 (:review-selector-title . "Choose what to review")
 (:review-selector-subtitle . "Select a deck or language pair to focus your review session.")
 (:review-by-deck . "Review by Deck")
 (:review-by-language-pair . "Review by Language Pair")
 (:review-all-cards . "Review All Cards")

 (:review-start . "Start Review")
 (:review-no-cards . "No Cards to Review")
 (:review-no-cards-desc . "You don't have any flashcards due for review right now.")
 (:review-no-cards-hint . "Translate some text and click \"Save to Flashcards\" to build your deck!")
 (:review-start-translating . "Start Translating")
 (:review-show-answer . "Show Answer")
 (:review-click-reveal . "Click to reveal answer")
 (:review-grammar-breakdown . "Grammar Breakdown")
 (:review-how-well . "How well did you remember?")
 (:review-again . "Again")
 (:review-hard . "Hard")
 (:review-good . "Good")
 (:review-easy . "Easy")
 (:review-progress . "Card ~a of ~a")
 (:review-complete . "Session Complete!")
 (:review-complete-msg . "You reviewed ~a cards")
 (:review-correct . "Correct")
 (:review-accuracy . "Accuracy")
 (:review-again-btn . "Review Again")
 (:review-translate-more . "Translate More")
 (:review-streak . "day streak")

 ;; Dashboard
 (:dashboard-title . "Dashboard")
 (:dashboard-cards-due . "Cards Due")
 (:dashboard-total-cards . "Total Cards")
 (:dashboard-subscription . "Subscription")
 (:dashboard-subscribed-until . "Subscribed until")
 (:dashboard-not-subscribed . "Not subscribed")
 (:dashboard-recent . "Recent Translations")
 (:dashboard-no-translations . "No translations yet")
 (:dashboard-streak . "Review Streak")
 (:dashboard-days . "days")
 (:dashboard-quick-actions . "Quick Actions")
 (:dashboard-getting-started . "Getting Started")
 (:dashboard-tip-1 . "Translate text you want to learn")
 (:dashboard-tip-2 . "Click \"Save to Flashcards\" on translations you want to remember")
 (:dashboard-tip-3 . "Review your flashcards regularly - spaced repetition helps you remember long-term")
 (:dashboard-tip-4 . "Rate honestly - it helps the algorithm schedule your reviews optimally")

 ;; Account
 (:account-title . "Account")
 (:account-subtitle . "Manage your account settings and deletion schedule.")
 (:account-deletion-title . "Account Deletion")
 (:account-deletion-scheduled . "Your account is scheduled for deletion on ~A.")
 (:account-deletion-cancel-hint . "You can cancel before this date to keep your account.")
 (:account-deletion-cancel . "Cancel deletion")
 (:account-deletion-request . "You can request account deletion at any time. Deletion is scheduled 14 days from confirmation. If you change your mind after deletion, please contact support.")
 (:account-deletion-confirm . "Schedule account deletion for 14 days from now?")
 (:account-deletion-schedule . "Schedule deletion")
 (:account-reminders-title . "Email Reminders")
 (:account-reminders-subtitle . "Control review and continuation reminders for this account.")
 (:account-reminders-opt-out . "Opt out of review/continuation reminders")
 (:account-reminders-save . "Save preferences")

 ;; Subscription
 (:subscribe-title . "Simple Pricing")
 (:subscribe-choose-plan . "Choose Your Plan")
 (:subscribe-start-today . "Start learning today with a 7-day free trial")
 (:subscribe-monthly . "Monthly")
 (:subscribe-annual . "Annual")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/month")
 (:subscribe-per-year . "/year")
 (:subscribe-monthly-desc . "600 translations per month")
 (:subscribe-unlimited-flashcards . "Unlimited flashcards")
 (:subscribe-grammar-explanations . "Grammar explanations")
 (:subscribe-spaced-repetition . "Spaced repetition")
 (:subscribe-annual-desc . "Save €20 — two months free!")
 (:subscribe-cta . "Subscribe")
 (:subscribe-success . "Subscription Successful!")
 (:subscribe-manage . "Manage Subscription")
 (:subscribe-activated . "Subscription Activated!")
 (:subscribe-thank-you . "Thank you for subscribing. Your account is now active.")
 (:subscribe-start-learning . "Start Learning")
 (:subscribe-management . "Subscription Management")
 (:subscribe-active . "Active Subscription")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Active")
 (:subscribe-days-remaining . "Days remaining:")
 (:subscribe-renews-on . "Renews on:")
 (:subscribe-no-subscription . "No Active Subscription")
 (:subscribe-access-features . "Subscribe to access all features.")
 (:subscribe-view-plans . "View Plans")
 (:subscribe-faq-title . "Frequently Asked Questions")
 (:subscribe-faq-trial-q . "What happens after the free trial?")
 (:subscribe-faq-trial-a . "After your 7-day free trial, you'll be charged for your selected plan. You can cancel anytime before the trial ends.")
 (:subscribe-faq-cancel-q . "Can I cancel anytime?")
 (:subscribe-faq-cancel-a . "Yes! You can cancel your subscription at any time. You'll keep access until the end of your billing period.")
 (:subscribe-faq-payment-q . "What payment methods do you accept?")
 (:subscribe-faq-payment-a . "We accept all major credit cards and debit cards through our payment partner Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 ;; API Errors
 (:api-error-missing-text . "Missing text to translate.")
 (:api-error-invalid-translation-id . "Invalid translation ID.")
 (:api-error-translation-not-found . "The translation you tried to save no longer exists.")
 (:api-error-invalid-bookmark-id . "Invalid bookmark ID")
 (:api-error-bookmark-not-found . "Bookmark not found")
 (:api-error-forbidden . "Forbidden")
 (:api-error-failed-delete-bookmark . "Failed to delete bookmark")
 (:api-error-invalid-flashcard-id . "Invalid flashcard ID")
 (:api-error-missing-deck-id . "Missing deck_id")
 (:api-error-flashcard-not-found . "Flashcard not found")
 (:api-error-deck-not-found . "Deck not found")
 (:api-error-deck-name-required . "Deck name is required")
 (:api-error-session-expired . "Your review session has expired. Please start a new session.")
 (:api-error-invalid-card-id . "Invalid card ID.")
 (:api-error-invalid-rating . "Invalid rating.")
 (:api-error-rating-range . "Rating must be between 0 and 5.")
 (:api-error-card-not-found . "Card not found.")
 (:api-error-permission-denied . "You don't have permission to review this card.")
 (:api-error-unknown-source-lang . "Unknown source language.")
 (:api-error-unknown-target-lang . "Unknown target language.")
 (:api-error-failed-add-to-deck . "Failed to add to deck")

 ;; API Success messages
 (:api-success-added . "Added!")
 (:api-success-added-simple . "Added")

 ;; API Stats
 (:api-stats-due . "~A due")
 (:api-stats-total . "~A total")

 ;; Time units
 (:api-time-day . "day")
 (:api-time-days . "days")
 (:api-time-day-left . "day left")
 (:api-time-days-left . "days left")

 ;; Subscription status
 (:api-subscription-active . "Active")
 (:api-subscription-inactive . "Inactive")
 (:api-subscription-subscribe-hint . "Subscribe to unlock translations")

 ;; Generic status
 (:status-bad-request . "Bad Request")
 (:status-not-found . "Not Found")
 (:status-forbidden . "Forbidden")

 (:error-generic . "Something went wrong")
 (:error-not-found . "Page not found")
 (:error-unauthorized . "Please log in to continue")
 (:error-subscription-required . "Subscription required")
 (:error-text-too-long . "Text is too long. Maximum translation length is 120 characters.")
 (:error-input-too-long . "Input Too Long")
 (:error-unknown-source-lang . "The source language you selected is not supported.")
 (:error-unknown-target-lang . "The target language you selected is not supported.")
 (:error-unknown-language . "Unknown Language")
 (:error-translation-unavailable . "Translation service is temporarily unavailable. Please try again in a moment.")
 (:error-translation-failed . "Translation Failed")
 (:error-translation-retry . "Unable to generate a translation after multiple attempts. Please try rephrasing your text.")
 (:error-quota-exceeded . "Translation Limit Reached")
 (:error-quota-exceeded-detail . "You've used all your translations for this month. Your quota resets automatically each month.")
 (:quota-warning . "Translations remaining: ~A")
 (:quota-low-warning . "Only ~A translations left. Consider purchasing more.")
 (:top-up-button . "Buy More Translations")
 (:top-up-success . "Top-up successful! You now have ~A additional translations.")
 (:top-up-price . "€5")
 (:top-up-amount . "300 translations")
 (:loading . "Loading...")
 (:empty-state . "Nothing here yet")

 ;; Institutions
 (:institutions-page-title . "Hiisi for Schools - Institutional Licenses")
 (:institutions-hero-title . "Hiisi for Schools")
 (:institutions-hero-subtitle . "Empower your students with AI-powered language learning")
 (:institutions-section-title . "Institutional Licenses")
 (:institutions-section-body . "We offer bulk licensing for schools, universities, and language learning institutions. Students with email addresses from your domain automatically receive full access.")
 (:institutions-benefit-1 . "Automatic enrollment for students with institutional email")
 (:institutions-benefit-2 . "No per-student accounts to manage")
 (:institutions-benefit-3 . "Flexible billing arrangements")
 (:institutions-benefit-4 . "Dedicated support for educators")
 (:institutions-request-title . "Request a License")
 (:institutions-request-subtitle . "Fill out the form below and we'll get back to you within 2 business days.")
 (:institutions-field-name . "Institution Name")
 (:institutions-field-name-placeholder . "University of Helsinki")
 (:institutions-field-contact-name . "Contact Name")
 (:institutions-field-contact-name-placeholder . "Your name")
 (:institutions-field-contact-email . "Contact Email")
 (:institutions-field-contact-email-placeholder . "you@university.edu")
 (:institutions-field-domains . "Email Domains")
 (:institutions-field-domains-placeholder . "university.edu, cs.university.edu")
 (:institutions-field-domains-help . "Comma-separated list of email domains for your institution")
 (:institutions-field-notes . "Additional Information")
 (:institutions-field-notes-placeholder . "Estimated number of students, preferred billing cycle, any special requirements...")
 (:institutions-submit . "Submit Inquiry")
 (:institutions-success-title . "Thank You - Hiisi for Schools")
 (:institutions-success-heading . "Thank You!")
 (:institutions-success-body . "We've received your institutional license inquiry. Our team will review your request and get back to you within 2 business days.")
 (:institutions-success-back . "Back to Home")

 ;; Footer
 (:footer-privacy . "Privacy Policy")
 (:footer-terms . "Terms of Service")
 (:footer-contact . "Contact")

 ;; Early software notice
 (:early-software-notice . "Hiisi is in early development. Found a bug or have a suggestion?")
 (:early-software-contact . "Contact us at")

 ;; Privacy Policy
 (:privacy-title . "Privacy Policy")
 (:privacy-updated . "Last updated: January 2026")
 (:privacy-who-title . "Who We Are")
 (:privacy-who-body . "Hiisi is operated by Lambda Symbolics OÜ, a company registered in Estonia. As an Estonian company, we comply with the European Union's General Data Protection Regulation (GDPR).")
 (:privacy-collect-title . "Data We Collect")
 (:privacy-collect-intro . "We collect the following information when you use Hiisi:")
 (:privacy-collect-account-key . "Account information: ")
 (:privacy-collect-account-val . "Email address, display name, and a securely hashed password.")
 (:privacy-collect-learning-key . "Learning data: ")
 (:privacy-collect-learning-val . "Your translations, saved flashcards, and review history.")
 (:privacy-collect-usage-key . "Usage data: ")
 (:privacy-collect-usage-val . "Basic server logs for security and debugging purposes.")
 (:privacy-use-title . "How We Use Your Data")
 (:privacy-use-auth-key . "Authentication: ")
 (:privacy-use-auth-val . "To verify your identity and secure your account.")
 (:privacy-use-service-key . "Service delivery: ")
 (:privacy-use-service-val . "To provide translations and manage your flashcard collection.")
 (:privacy-use-ai-key . "AI translations: ")
 (:privacy-use-ai-val . "Your translation requests are sent to Anthropic's Claude API to generate responses. See Anthropic's privacy policy for how they handle this data.")
 (:privacy-third-title . "Third-Party Services")
 (:privacy-third-intro . "We use the following third-party services:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "For AI-powered translations.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "For sending account activation and transactional emails.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "For subscription payment processing.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "We use only essential cookies:")
 (:privacy-cookies-auth-key . "Authentication token: ")
 (:privacy-cookies-auth-val . "A secure, HTTP-only cookie to keep you logged in.")
 (:privacy-cookies-lang-key . "Language preference: ")
 (:privacy-cookies-lang-val . "To remember your preferred UI language.")
 (:privacy-retention-title . "Data Retention")
 (:privacy-retention-body . "Your data is stored as long as you maintain an account. When you request deletion, your account is scheduled for deletion in 14 days.")
 (:privacy-rights-title . "Your Rights (GDPR)")
 (:privacy-rights-intro . "Under GDPR, you have the right to:")
 (:privacy-rights-access . "Access your personal data")
 (:privacy-rights-export . "Export your data (available at /app/api/export)")
 (:privacy-rights-correct . "Request correction of inaccurate data")
 (:privacy-rights-delete . "Request deletion of your account and data")
 (:privacy-rights-object . "Object to processing of your data")
 (:privacy-rights-contact . "To exercise these rights, contact us at")
 (:privacy-contact-title . "Contact")
 (:privacy-contact-intro . "For privacy-related inquiries:")
 (:privacy-contact-email-label . "Email: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Estonia")

 ;; Terms of Service
 (:terms-title . "Terms of Service")
 (:terms-updated . "Last updated: January 2026")
 (:terms-1-title . "1. Service Description")
 (:terms-1-body . "Hiisi is a language learning application that provides AI-powered translations with grammatical explanations and spaced repetition flashcards. The service is operated by Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Account Registration")
 (:terms-2-body . "To use Hiisi, you must create an account with a valid email address. You are responsible for maintaining the security of your account credentials.")
 (:terms-3-title . "3. Subscription and Payments")
 (:terms-3-body . "Hiisi offers paid subscription plans (monthly and annual). Subscriptions are processed through Polar.sh.")
 (:terms-3-list-1 . "Subscriptions auto-renew unless cancelled before the renewal date.")
 (:terms-3-list-2 . "Refunds are provided in accordance with applicable consumer protection laws.")
 (:terms-3-list-3 . "Non-payment results in loss of access to premium features.")
 (:terms-4-title . "4. Acceptable Use")
 (:terms-4-intro . "You agree not to:")
 (:terms-4-list-1 . "Use the service for any illegal purpose")
 (:terms-4-list-2 . "Attempt to circumvent usage limits or security measures")
 (:terms-4-list-3 . "Share your account credentials with others")
 (:terms-4-list-4 . "Use automated tools to access the service in a way that degrades performance for others")
 (:terms-5-title . "5. Content and Intellectual Property")
 (:terms-5-body-1 . "Translations generated by Hiisi are created using AI and may not be unique. You may use your translations and flashcards for any personal purpose, but you do not hold exclusive authorship rights over AI-generated content.")
 (:terms-5-body-2 . "The Hiisi application, branding, and original content remain the property of Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Service Availability")
 (:terms-6-intro . "Hiisi is provided on an \"as-is\" basis. We do not guarantee:")
 (:terms-6-list-1 . "Uninterrupted or error-free service")
 (:terms-6-list-2 . "Accuracy of AI-generated translations")
 (:terms-6-list-3 . "Availability of specific features")
 (:terms-6-body . "We may modify or discontinue features at any time.")
 (:terms-7-title . "7. Limitation of Liability")
 (:terms-7-body-1 . "To the maximum extent permitted by law, Lambda Symbolics OÜ shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of Hiisi.")
 (:terms-7-body-2 . "Our total liability shall not exceed the amount you paid for the service in the 12 months preceding the claim.")
 (:terms-8-title . "8. Account Termination")
 (:terms-8-body-1 . "We may suspend or terminate your account if you violate these terms. You may request account deletion at any time through the application.")
 (:terms-8-body-2 . "Upon deletion request, your account is scheduled for deletion in 14 days.")
 (:terms-9-title . "9. Changes to Terms")
 (:terms-9-body . "We may update these terms from time to time. Continued use of Hiisi after changes constitutes acceptance of the new terms.")
 (:terms-10-title . "10. Governing Law")
 (:terms-10-body . "These terms are governed by the laws of Estonia. Any disputes shall be resolved in the courts of Estonia.")
 (:terms-contact-title . "Contact")
 (:terms-contact-intro . "For questions about these terms:")
 (:terms-contact-email-label . "Email: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Estonia")



 ;; Decks
 (:decks-title . "Decks")
 (:decks-subtitle . "Create custom decks and share them with others.")
 (:decks-create-title . "Create Deck")
 (:decks-name-placeholder . "Deck name")
 (:decks-desc-placeholder . "Description")
 (:decks-create-btn . "Create deck")
 (:decks-your-title . "Your Decks")
 (:decks-col-name . "Name")
 (:decks-col-desc . "Description")
 (:decks-col-updated . "Updated")
 (:decks-col-actions . "Actions")
 (:decks-no-decks . "No decks yet.")
 (:decks-open-btn . "Open")
 (:decks-no-desc . "No description.")
 (:decks-share-title . "Share Link")
 (:decks-share-info . "Anyone with this link can import the deck:")
 (:decks-share-copy . "Copy link")
 (:decks-share-copied . "Copied")
 (:decks-add-from-flashcards-title . "Add translations")
 (:decks-add-from-flashcards-info . "Pick a flashcard to add its translation to this deck.")
 (:decks-open-flashcards . "Add from flashcards")
 (:decks-filter-from . "From language")
 (:decks-filter-to . "To language")
 (:decks-filter-any . "Any language")
 (:decks-filter-include-assigned . "Include flashcards already in a deck")
 (:decks-flashcards-col-from . "From")
 (:decks-flashcards-col-to . "To")
 (:decks-flashcards-add . "Add")
 (:decks-flashcards-added . "Added")
 (:decks-flashcards-in-deck . "In another deck")
 (:decks-flashcards-empty . "No flashcards match these filters.")
 (:decks-add-trans-title . "Add Translation")
 (:decks-trans-id-placeholder . "Translation ID")
 (:decks-add-trans-btn . "Add translation")
 (:decks-items-title . "Deck Items")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Translated")
 (:decks-col-lang . "Lang To")
 (:decks-no-items . "No items yet.")
 (:decks-share-page-title . "Share Deck")
 (:decks-share-preview . "Preview and import this deck.")
 (:decks-import-title . "Import")
 (:decks-import-btn . "Import deck")

 ;; Flashcards management page
 (:flashcards-title . "My Flashcards")
 (:flashcards-subtitle . "All your saved flashcards in one place. Search, organize, and manage.")
 (:flashcards-search-placeholder . "Search flashcards...")
 (:flashcards-col-original . "Original")
 (:flashcards-col-translated . "Translation")
 (:flashcards-col-lang . "Languages")
 (:flashcards-no-cards . "No flashcards yet. Start translating to create some!")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Learn Languages Comprehensively")
 (:landing-hero-subheadline . "Get translations with full grammar breakdowns and build lasting vocabulary through spaced repetition flashcards.")
 (:landing-hero-trust-line . "7-day free trial with 100 translations. Cancel anytime.")
 (:landing-credibility-languages . "14 languages")
 (:landing-credibility-ai . "Grammar breakdowns included")
 (:landing-credibility-origin . "Built in Estonia")
 (:landing-step-1-title . "Translate Any Text")
 (:landing-step-1-desc . "Enter a word or phrase. Get a translation with full grammar breakdown.")
 (:landing-step-2-title . "Save to Flashcards")
 (:landing-step-2-desc . "Bookmark translations you want to remember. Flashcards are created automatically.")
 (:landing-step-3-title . "Review and Remember")
 (:landing-step-3-desc . "Spaced repetition schedules reviews at the perfect moment for long-term memory.")
 (:landing-feature-grammar-title . "Understand Grammar, Not Just Words")
 (:landing-feature-grammar-desc . "Every translation comes with a detailed grammar breakdown -- word forms, cases, conjugations explained in your language.")
 (:landing-feature-srs-title . "Science-Backed Memorization")
 (:landing-feature-srs-desc . "The SM-2 spaced repetition algorithm adapts to your performance. Cards you struggle with appear more often. Cards you know well fade back.")
 (:landing-feature-share-title . "Share Decks with Students")
 (:landing-feature-share-desc . "Teachers can create custom flashcard decks and share them with a link. Students import the deck and start reviewing immediately.")
 (:landing-pricing-trial-note . "7-day free trial included")
 (:landing-pricing-monthly-after . "7-day free trial, then ~A/month")
 (:landing-pricing-annual-after . "7-day free trial, then ~A/year")
 (:landing-faq-title . "Frequently Asked Questions")
 (:landing-faq-trial-cap-q . "How many translations do I get during the trial?")
 (:landing-faq-trial-cap-a . "You get 100 translations during your 7-day trial. After subscribing, you get 600 per month.")
 (:landing-final-cta-title . "Start Learning Today")
 (:landing-final-cta-subtitle . "Join Hiisi and start building vocabulary that sticks.")

 ;; Trial status (in-app)
 (:trial-status . "Free Trial")
 (:trial-days-remaining . "~A days remaining")
 (:trial-translations-used . "~A/100 translations used")
 (:trial-upgrade-prompt . "Upgrade to continue translating")
 (:trial-expired . "Your free trial has ended")
 (:trial-expired-detail . "Subscribe to keep learning with Hiisi.")
 (:trial-quota-warning . "~A trial translations left (~A days remaining). Subscribe for 600/month.")
 (:trial-quota-exceeded . "Trial translation limit reached. Subscribe to continue.")
 (:error-trial-quota-exceeded . "Trial translation limit reached")
 (:error-trial-quota-detail . "You have used all 100 trial translations. Subscribe to continue learning.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Create Flashcard")
 (:custom-flashcard-edit-title . "Edit Flashcard")
 (:custom-flashcard-original . "Original Text")
 (:custom-flashcard-translated . "Translation")
 (:custom-flashcard-lang-from . "Source Language")
 (:custom-flashcard-lang-to . "Target Language")
 (:custom-flashcard-note . "Educational Note")
 (:custom-flashcard-forms . "Grammar Breakdown")
 (:custom-flashcard-form-term . "Term")
 (:custom-flashcard-form-explanation . "Explanation")
 (:custom-flashcard-add-form . "Add Grammar Term")
 (:custom-flashcard-remove-form . "Remove")
 (:custom-flashcard-ai-fill . "Fill with AI")
 (:custom-flashcard-ai-fill-all . "Fill All with AI")
 (:custom-flashcard-ai-fill-translation . "Translate with AI")
 (:custom-flashcard-ai-fill-breakdown . "Generate Breakdown")
 (:custom-flashcard-ai-fill-note . "Generate Note")
 (:custom-flashcard-create-btn . "Create Flashcard")
 (:custom-flashcard-update-btn . "Save Changes")
 (:custom-flashcard-delete-btn . "Delete Flashcard")
 (:custom-flashcard-delete-confirm . "Are you sure you want to delete this flashcard?")
 (:custom-flashcard-created . "Flashcard created successfully")
 (:custom-flashcard-updated . "Flashcard updated successfully")
 (:custom-flashcard-deleted . "Flashcard deleted successfully")
 (:custom-flashcard-add-to-deck . "Add to Deck")
 (:custom-flashcard-not-found . "Flashcard not found")
 (:custom-flashcard-not-owner . "You can only edit flashcards you created")
 (:custom-flashcard-ai-generating . "Generating with AI...")
 (:custom-flashcard-badge . "Custom")

 ;; Issue reporting
 (:issues-open-button . "Report an Issue")
 (:issues-modal-title . "Report an Issue")
 (:issues-modal-subtitle . "Describe what went wrong. We will include your current page automatically.")
 (:issues-message-label . "What happened?")
 (:issues-message-placeholder . "Please include steps to reproduce, expected behavior, and what happened instead.")
 (:issues-submit . "Submit Issue")
 (:issues-cancel . "Cancel")
 (:issues-success . "Thank you. Your issue report was submitted.")
 (:issues-error-required . "Please describe the issue before submitting.")
 (:issues-error-too-long . "Issue text is too long. Please keep it under 4000 characters.")
 (:issues-error-rate-limit . "Too many reports from this source. Please wait and try again later.")
 (:issues-error-generic . "Issue report could not be submitted. Please try again.")

)
