;;; Spanish translations
;;; This file should contain all keys from en.lisp

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Español")
 (:lang-flag . "🇪🇸")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Elige tu idioma")
 (:lang-modal-subtitle . "Selecciona tu idioma preferido para la interfaz:")

 ;; Navigation
 (:nav-translate . "Traducir")
 (:nav-review . "Repasar")
 (:nav-flashcards . "Mis tarjetas")
 (:nav-dashboard . "Panel")
 (:nav-decks . "Decks")
 (:nav-logout . "Cerrar sesión")
 (:nav-home . "Inicio")
 (:nav-pricing . "Precios")
 (:nav-export-data . "Exportar datos")

 ;; App title and branding
 (:app-title . "Hiisi")
 (:app-tagline . "Aprende idiomas a través de traducciones")

 ;; Landing page
 (:landing-hero-title . "Domina cualquier idioma")
 (:landing-hero-subtitle . "Traduce lo que quieras. Genera automáticamente tarjetas que te enseñan por qué funciona así.")
 (:landing-cta . "Comenzar a aprender")
 (:landing-learn-more . "Más información")
 (:landing-how-it-works . "Cómo funciona")
 (:landing-feature-1-title . "Tarjetas automáticas")
 (:landing-feature-1-desc . "Cada traducción genera tarjetas automáticamente con análisis gramatical. Sin creación manual de tarjetas.")
 (:landing-feature-2-title . "Repetición espaciada")
 (:landing-feature-2-desc . "El algoritmo SM-2 programa repasos en intervalos óptimos. Aprende eficientemente, recuerda permanentemente.")
 (:landing-feature-3-title . "Enseñanza de gramática")
 (:landing-feature-3-desc . "Cada traducción explica la gramática, las raíces de las palabras y la estructura de las oraciones. Comprende el porqué, no solo el qué.")
 (:landing-free-trial . "Prueba gratuita de 7 días. No se requiere tarjeta de crédito.")
 (:landing-start-trial . "Iniciar prueba gratuita")
 (:landing-best-value . "Mejor valor")
 (:landing-cta-title . "¿Listo para aprender idiomas a través de la gramática, no la memorización?")
 (:landing-cta-subtitle . "Cada traducción se convierte en una oportunidad de aprendizaje. Cada tarjeta te enseña el porqué.")
 (:landing-signup-free . "Regístrate gratis")

 ;; Auth pages
 (:auth-register . "Registrarse")
 (:auth-login . "Iniciar sesión")
 (:auth-logout . "Cerrar sesión")
 (:auth-email . "Correo electrónico")
 (:auth-password . "Contraseña")
 (:auth-password-again . "Confirmar contraseña")
 (:auth-display-name . "Nombre para mostrar")
 (:auth-register-title . "Regístrate en Hiisi")
 (:auth-register-subtitle . "Crear una cuenta nueva")
 (:auth-login-title . "Iniciar sesión en Hiisi")
 (:auth-login-subtitle . "Ingresa tus credenciales")
 (:auth-forgot-password . "¿Olvidaste tu contraseña?")
 (:auth-no-account . "¿No tienes cuenta?")
 (:auth-have-account . "¿Ya tienes cuenta?")
 (:auth-google . "Google")
 (:auth-account-created . "¡Cuenta creada!")
 (:auth-check-email . "Revisa tu correo electrónico para el enlace de activación.")
 (:auth-redirect-login . "Redirigiendo al inicio de sesión en")
 (:auth-seconds . "segundos...")
 (:auth-go-now . "Ir ahora")
 (:auth-not-activated . "Cuenta no activada")
 (:auth-activate-title . "¡Activa tu cuenta!")
 (:auth-activated . "¡Cuenta activada!")
 (:auth-activated-message . "Tu cuenta ha sido activada. Ya puedes usar Hiisi.")
 (:auth-redirecting . "Redirigiendo en")
 (:auth-go-to-app . "Ir a la app")
 (:auth-resend-title . "Reenviar correo de activación")
 (:auth-resend-subtitle . "Ingresa tu correo para recibir un nuevo enlace de activación.")
 (:auth-resend-button . "Reenviar correo de activación")
 (:auth-resend-success . "¡Correo de activación enviado!")
 (:auth-resend-success-detail . "Revisa tu bandeja de entrada para el nuevo enlace de activación.")
 (:auth-resend-rate-limited . "Por favor espera unos minutos antes de solicitar otro correo de activación.")
 (:auth-resend-cooldown . "Puedes solicitar otro correo en ~a segundos.")
 (:auth-back-to-login . "Volver al inicio de sesión")
 (:auth-forgot-password-title . "Olvidé mi contraseña")
 (:auth-forgot-password-subtitle . "Ingresa tu correo y te enviaremos un enlace para restablecer tu contraseña.")
 (:auth-send-reset-link . "Enviar enlace de restablecimiento")
 (:auth-reset-email-sent . "¡Enlace enviado!")
 (:auth-reset-email-sent-detail . "Si existe una cuenta con ese correo, recibirás un enlace para restablecer tu contraseña pronto.")
 (:auth-reset-rate-limited . "Por favor espera unos minutos antes de solicitar otro restablecimiento de contraseña.")
 (:auth-reset-invalid-token . "Este enlace de restablecimiento es inválido o ha expirado.")
 (:auth-reset-password-title . "Restablecer contraseña")
 (:auth-reset-password-subtitle . "Ingresa tu nueva contraseña abajo.")
 (:auth-new-password . "Nueva contraseña")
 (:auth-confirm-new-password . "Confirmar nueva contraseña")
 (:auth-reset-password . "Restablecer contraseña")
 (:auth-password-changed . "¡Contraseña cambiada!")
 (:auth-password-changed-detail . "Tu contraseña ha sido cambiada exitosamente. Ahora puedes iniciar sesión con tu nueva contraseña.")
 (:auth-change-password-title . "Cambiar contraseña")
 (:auth-change-password-subtitle . "Actualiza la contraseña de tu cuenta.")
 (:auth-current-password . "Contraseña actual")
 (:auth-change-password . "Cambiar contraseña")
 (:auth-back-to-app . "Volver a la app")
 (:auth-password-updated . "¡Contraseña actualizada!")
 (:auth-password-updated-detail . "Tu contraseña ha sido actualizada exitosamente.")

 ;; Translation page
 (:translate-title . "Traducir")
 (:translate-input-label . "Texto a traducir")
 (:translate-input-placeholder . "Ingresa el texto a traducir...")
 (:translate-from . "De:")
 (:translate-to . "A:")
 (:translate-submit . "Traducir")
 (:translate-save . "Guardar en tarjetas")
 (:translate-saved . "¡Guardado!")
 (:translate-like . "Me gusta")
 (:translate-dislike . "No me gusta")
 (:translate-char-limit . "caracteres restantes")
 (:translate-auto-detect . "Cualquiera (Autodetectar)")
 (:translate-empty-state . "Ingresa texto arriba y haz clic en Traducir para ver el resultado con análisis gramatical")
 (:translate-like-tooltip . "Buena traducción")
 (:translate-dislike-tooltip . "Mala traducción - solicitar una nueva")
 (:translate-dislike-confirm . "Esto generará una nueva traducción. ¿Continuar?")
 (:translate-liked . "¡Me gusta!")

 ;; Flashcard review
 (:review-title . "Repasar")
 (:review-session-title . "Sesión de repaso")
 (:review-session-subtitle . "Practica tus tarjetas guardadas")
 (:review-start . "Iniciar repaso")
 (:review-no-cards . "No hay tarjetas para repasar")
 (:review-no-cards-desc . "No tienes tarjetas pendientes de repaso en este momento.")
 (:review-no-cards-hint . "¡Traduce texto y haz clic en \"Guardar en tarjetas\" para crear tu mazo!")
 (:review-start-translating . "Empezar a traducir")
 (:review-show-answer . "Mostrar respuesta")
 (:review-click-reveal . "Haz clic para revelar la respuesta")
 (:review-grammar-breakdown . "Análisis gramatical")
 (:review-how-well . "¿Qué tan bien lo recordaste?")
 (:review-again . "Otra vez")
 (:review-hard . "Difícil")
 (:review-good . "Bien")
 (:review-easy . "Fácil")
 (:review-progress . "Tarjeta ~a de ~a")
 (:review-complete . "¡Sesión completada!")
 (:review-complete-msg . "Repasaste ~a tarjetas")
 (:review-correct . "Correctas")
 (:review-accuracy . "Precisión")
 (:review-again-btn . "Repasar de nuevo")
 (:review-translate-more . "Traducir más")
 (:review-streak . "días de racha")

 ;; Dashboard
 (:dashboard-title . "Panel")
 (:dashboard-cards-due . "Tarjetas pendientes")
 (:dashboard-total-cards . "Total de tarjetas")
 (:dashboard-subscription . "Suscripción")
 (:dashboard-subscribed-until . "Suscrito hasta")
 (:dashboard-not-subscribed . "Sin suscripción")
 (:dashboard-recent . "Traducciones recientes")
 (:dashboard-no-translations . "Aún no hay traducciones")
 (:dashboard-streak . "Racha de repaso")
 (:dashboard-days . "días")
 (:dashboard-quick-actions . "Acciones rápidas")
 (:dashboard-getting-started . "Primeros pasos")
 (:dashboard-tip-1 . "Traduce el texto que quieras aprender")
 (:dashboard-tip-2 . "Haz clic en \"Guardar en tarjetas\" en las traducciones que quieras recordar")
 (:dashboard-tip-3 . "Repasa tus tarjetas regularmente - la repetición espaciada te ayuda a recordar a largo plazo")
 (:dashboard-tip-4 . "Califica honestamente - ayuda al algoritmo a programar tus repasos de forma óptima")

 ;; Subscription
 (:subscribe-title . "Precios simples")
 (:subscribe-choose-plan . "Elige tu plan")
 (:subscribe-start-today . "Empieza a aprender hoy con una prueba gratuita de 7 días")
 (:subscribe-monthly . "Mensual")
 (:subscribe-annual . "Anual")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/mes")
 (:subscribe-per-year . "/año")
 (:subscribe-monthly-desc . "600 traducciones al mes")
 (:subscribe-unlimited-flashcards . "Tarjetas ilimitadas")
 (:subscribe-grammar-explanations . "Explicaciones gramaticales")
 (:subscribe-spaced-repetition . "Repetición espaciada")
 (:subscribe-annual-desc . "¡Ahorra 20€ — dos meses gratis!")
 (:subscribe-cta . "Suscribirse")
 (:subscribe-success . "¡Suscripción exitosa!")
 (:subscribe-manage . "Gestionar suscripción")
 (:subscribe-activated . "¡Suscripción activada!")
 (:subscribe-thank-you . "Gracias por suscribirte. Tu cuenta ya está activa.")
 (:subscribe-start-learning . "Empezar a aprender")
 (:subscribe-management . "Gestión de suscripción")
 (:subscribe-active . "Suscripción activa")
 (:subscribe-status . "Estado:")
 (:subscribe-status-active . "Activa")
 (:subscribe-days-remaining . "Días restantes:")
 (:subscribe-renews-on . "Se renueva el:")
 (:subscribe-no-subscription . "Sin suscripción activa")
 (:subscribe-access-features . "Suscríbete para acceder a todas las funciones.")
 (:subscribe-view-plans . "Ver planes")
 (:subscribe-faq-title . "Preguntas frecuentes")
 (:subscribe-faq-trial-q . "¿Qué pasa después de la prueba gratuita?")
 (:subscribe-faq-trial-a . "Después de tu prueba gratuita de 7 días, se te cobrará por el plan seleccionado. Puedes cancelar en cualquier momento antes de que termine la prueba.")
 (:subscribe-faq-cancel-q . "¿Puedo cancelar en cualquier momento?")
 (:subscribe-faq-cancel-a . "¡Sí! Puedes cancelar tu suscripción en cualquier momento. Mantendrás el acceso hasta el final de tu período de facturación.")
 (:subscribe-faq-payment-q . "¿Qué métodos de pago aceptan?")
 (:subscribe-faq-payment-a . "Aceptamos todas las tarjetas de crédito y débito principales a través de nuestro socio de pagos Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Algo salió mal")
 (:error-not-found . "Página no encontrada")
 (:error-unauthorized . "Por favor inicia sesión para continuar")
 (:error-subscription-required . "Se requiere suscripción")
 (:error-text-too-long . "El texto es demasiado largo. La longitud máxima de traducción es de 120 caracteres.")
 (:error-input-too-long . "Texto demasiado largo")
 (:error-unknown-source-lang . "El idioma de origen seleccionado no es compatible.")
 (:error-unknown-target-lang . "El idioma de destino seleccionado no es compatible.")
 (:error-unknown-language . "Idioma desconocido")
 (:error-translation-unavailable . "El servicio de traducción no está disponible temporalmente. Por favor, inténtalo de nuevo en un momento.")
 (:error-translation-failed . "Traducción fallida")
 (:error-translation-retry . "No se pudo generar una traducción después de varios intentos. Por favor, intenta reformular tu texto.")
 (:error-quota-exceeded . "Límite de traducciones alcanzado")
 (:error-quota-exceeded-detail . "Has usado todas tus traducciones de este mes. Tu cuota se restablece automáticamente cada mes." (:quota-warning . "Traducciones restantes: ~A")
 (:quota-low-warning . "Solo quedan ~A traducciones. Considere comprar más.")
 (:top-up-button . "Comprar más traducciones")
 (:top-up-success . "¡Recarga exitosa! Ahora tienes ~A traducciones adicionales.")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 traducciones"))
 (:loading . "Cargando...")
 (:empty-state . "Nada aquí todavía")

 ;; Footer
 (:footer-privacy . "Política de privacidad")
 (:footer-terms . "Términos de servicio")
 (:footer-contact . "Contacto")

 ;; Early software notice
 (:early-software-notice . "Hiisi está en desarrollo temprano. ¿Encontraste un error o tienes una sugerencia?")
 (:early-software-contact . "Contáctanos en")

 ;; Privacy Policy
 (:privacy-title . "Privacy Policy")
 (:privacy-updated . "Last updated: January 2026")
 (:privacy-who-title . "Who We Are")
 (:privacy-who-body . "Hiisi is operated by Lambda Symbolics OÜ, a company registered in Estonia. As an Estonian company, we comply with the European Union's General Data Protection Regulation (GDPR).")
 (:privacy-collect-title . "Data We Collect")
 (:privacy-collect-intro . "We collect the following information when you use Hiisi:")
 (:privacy-collect-account-key . "Account information: ")
 (:privacy-collect-account-val . "Email address, display name, and a securely hashed password.")
 (:privacy-collect-learning-key . "Learning data: ")
 (:privacy-collect-learning-val . "Your translations, saved flashcards, and review history.")
 (:privacy-collect-usage-key . "Usage data: ")
 (:privacy-collect-usage-val . "Basic server logs for security and debugging purposes.")
 (:privacy-use-title . "How We Use Your Data")
 (:privacy-use-auth-key . "Authentication: ")
 (:privacy-use-auth-val . "To verify your identity and secure your account.")
 (:privacy-use-service-key . "Service delivery: ")
 (:privacy-use-service-val . "To provide translations and manage your flashcard collection.")
 (:privacy-use-ai-key . "AI translations: ")
 (:privacy-use-ai-val . "Your translation requests are sent to Anthropic's Claude API to generate responses. See Anthropic's privacy policy for how they handle this data.")
 (:privacy-third-title . "Third-Party Services")
 (:privacy-third-intro . "We use the following third-party services:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "For AI-powered translations.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "For sending account activation and transactional emails.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "For subscription payment processing.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "We use only essential cookies:")
 (:privacy-cookies-auth-key . "Authentication token: ")
 (:privacy-cookies-auth-val . "A secure, HTTP-only cookie to keep you logged in.")
 (:privacy-cookies-lang-key . "Language preference: ")
 (:privacy-cookies-lang-val . "To remember your preferred UI language.")
 (:privacy-retention-title . "Data Retention")
 (:privacy-retention-body . "Your data is stored as long as you maintain an account. When you request deletion, your account is scheduled for deletion in 14 days.")
 (:privacy-rights-title . "Your Rights (GDPR)")
 (:privacy-rights-intro . "Under GDPR, you have the right to:")
 (:privacy-rights-access . "Access your personal data")
 (:privacy-rights-export . "Export your data (available at /app/api/export)")
 (:privacy-rights-correct . "Request correction of inaccurate data")
 (:privacy-rights-delete . "Request deletion of your account and data")
 (:privacy-rights-object . "Object to processing of your data")
 (:privacy-rights-contact . "To exercise these rights, contact us at")
 (:privacy-contact-title . "Contact")
 (:privacy-contact-intro . "For privacy-related inquiries:")
 (:privacy-contact-email-label . "Email: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Estonia")

 ;; Terms of Service
 (:terms-title . "Terms of Service")
 (:terms-updated . "Last updated: January 2026")
 (:terms-1-title . "1. Service Description")
 (:terms-1-body . "Hiisi is a language learning application that provides AI-powered translations with grammatical explanations and spaced repetition flashcards. The service is operated by Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Account Registration")
 (:terms-2-body . "To use Hiisi, you must create an account with a valid email address. You are responsible for maintaining the security of your account credentials.")
 (:terms-3-title . "3. Subscription and Payments")
 (:terms-3-body . "Hiisi offers paid subscription plans (monthly and annual). Subscriptions are processed through Polar.sh.")
 (:terms-3-list-1 . "Subscriptions auto-renew unless cancelled before the renewal date.")
 (:terms-3-list-2 . "Refunds are provided in accordance with applicable consumer protection laws.")
 (:terms-3-list-3 . "Non-payment results in loss of access to premium features.")
 (:terms-4-title . "4. Acceptable Use")
 (:terms-4-intro . "You agree not to:")
 (:terms-4-list-1 . "Use the service for any illegal purpose")
 (:terms-4-list-2 . "Attempt to circumvent usage limits or security measures")
 (:terms-4-list-3 . "Share your account credentials with others")
 (:terms-4-list-4 . "Use automated tools to access the service in a way that degrades performance for others")
 (:terms-5-title . "5. Content and Intellectual Property")
 (:terms-5-body-1 . "Translations generated by Hiisi are created using AI and may not be unique. You may use your translations and flashcards for any personal purpose, but you do not hold exclusive authorship rights over AI-generated content.")
 (:terms-5-body-2 . "The Hiisi application, branding, and original content remain the property of Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Service Availability")
 (:terms-6-intro . "Hiisi is provided on an \"as-is\" basis. We do not guarantee:")
 (:terms-6-list-1 . "Uninterrupted or error-free service")
 (:terms-6-list-2 . "Accuracy of AI-generated translations")
 (:terms-6-list-3 . "Availability of specific features")
 (:terms-6-body . "We may modify or discontinue features at any time.")
 (:terms-7-title . "7. Limitation of Liability")
 (:terms-7-body-1 . "To the maximum extent permitted by law, Lambda Symbolics OÜ shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of Hiisi.")
 (:terms-7-body-2 . "Our total liability shall not exceed the amount you paid for the service in the 12 months preceding the claim.")
 (:terms-8-title . "8. Account Termination")
 (:terms-8-body-1 . "We may suspend or terminate your account if you violate these terms. You may request account deletion at any time through the application.")
 (:terms-8-body-2 . "Upon deletion request, your account is scheduled for deletion in 14 days.")
 (:terms-9-title . "9. Changes to Terms")
 (:terms-9-body . "We may update these terms from time to time. Continued use of Hiisi after changes constitutes acceptance of the new terms.")
 (:terms-10-title . "10. Governing Law")
 (:terms-10-body . "These terms are governed by the laws of Estonia. Any disputes shall be resolved in the courts of Estonia.")
 (:terms-contact-title . "Contact")
 (:terms-contact-intro . "For questions about these terms:")
 (:terms-contact-email-label . "Email: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Estonia")



 ;; Decks
 (:decks-title . "Mazos")
 (:decks-subtitle . "Crea mazos personalizados y compártelos con otros.")
 (:decks-create-title . "Crear mazo")
 (:decks-name-placeholder . "Nombre del mazo")
 (:decks-desc-placeholder . "Descripción")
 (:decks-create-btn . "Crear mazo")
 (:decks-your-title . "Tus mazos")
 (:decks-col-name . "Nombre")
 (:decks-col-desc . "Descripción")
 (:decks-col-updated . "Actualizado")
 (:decks-col-actions . "Acciones")
 (:decks-no-decks . "Aún no hay mazos.")
 (:decks-open-btn . "Abrir")
 (:decks-no-desc . "Sin descripción.")
 (:decks-share-title . "Enlace para compartir")
 (:decks-share-info . "Cualquiera con este enlace puede importar el mazo:")
 (:decks-add-trans-title . "Añadir traducción")
 (:decks-trans-id-placeholder . "ID de traducción")
 (:decks-add-trans-btn . "Añadir traducción")
 (:decks-items-title . "Contenido del mazo")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Traducción")
 (:decks-col-lang . "Idioma destino")
 (:decks-no-items . "Aún no hay elementos.")
 (:decks-share-page-title . "Compartir mazo")
 (:decks-share-preview . "Vista previa e importación de este mazo.")
 (:decks-import-title . "Importar")
 (:decks-import-btn . "Importar mazo")

 ;; Flashcards management page
 (:flashcards-title . "Mis tarjetas")
 (:flashcards-subtitle . "Todas tus tarjetas guardadas en un solo lugar. Busca, organiza y gestiona.")
 (:flashcards-search-placeholder . "Buscar tarjetas...")
 (:flashcards-col-original . "Original")
 (:flashcards-col-translated . "Traducción")
 (:flashcards-col-lang . "Idiomas")
 (:flashcards-no-cards . "Aún no hay tarjetas. ¡Comienza a traducir para crear algunas!")

)
