;;; Spanish translations
;;; This file should contain all keys from en.lisp

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Español")
 (:lang-flag . "🇪🇸")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Elige tu idioma")
 (:lang-modal-subtitle . "Selecciona tu idioma preferido para la interfaz:")

 ;; Navigation
 (:nav-translate . "Traducir")
 (:nav-review . "Repasar")
 (:nav-flashcards . "Mis tarjetas")
 (:nav-dashboard . "Panel")
 (:nav-decks . "Decks")
 (:nav-logout . "Cerrar sesión")
 (:nav-home . "Inicio")
 (:nav-pricing . "Precios")
 (:nav-export-data . "Exportar datos")

 ;; App title and branding
 (:app-title . "Hiisi - Aprendizaje de idiomas")

 ;; Landing page
 (:landing-learn-more . "Más información")
 (:landing-how-it-works . "Cómo funciona")
 (:landing-start-trial . "Iniciar prueba gratuita")
 (:landing-best-value . "Mejor valor")

 ;; Auth pages
 (:auth-register . "Registrarse")
 (:auth-login . "Iniciar sesión")
 (:auth-email . "Correo electrónico")
 (:auth-password . "Contraseña")
 (:auth-password-again . "Confirmar contraseña")
 (:auth-display-name . "Nombre para mostrar")
 (:auth-register-title . "Regístrate en Hiisi")
 (:auth-register-subtitle . "Crear una cuenta nueva")
 (:auth-login-title . "Iniciar sesión en Hiisi")
 (:auth-login-subtitle . "Ingresa tus credenciales")
 (:auth-login-invalid-credentials . "Correo o contrasena incorrectos.")
 (:auth-login-rate-limited . "Demasiados intentos de inicio de sesion. Espera unos minutos e intentalo de nuevo.")
(:auth-register-rate-limited . "Demasiados intentos de registro. Espera unos minutos e inténtalo de nuevo.")
(:auth-email-invalid . "Introduce un correo electrónico válido.")
(:auth-password-too-short . "La contraseña debe tener al menos 8 caracteres.")
(:auth-passwords-mismatch . "Las contraseñas no coinciden.")
(:auth-display-name-invalid . "El nombre visible debe tener entre 1 y 100 caracteres.")
(:auth-register-email-exists . "Ya existe una cuenta con este correo electrónico.")
(:auth-register-unavailable . "El registro está temporalmente no disponible. Inténtalo de nuevo más tarde.")
(:auth-activation-email-send-failed . "No se pudo enviar el correo de activación. Inténtalo de nuevo.")
 (:auth-forgot-password . "¿Olvidaste tu contraseña?")
 (:auth-no-account . "¿No tienes cuenta?")
 (:auth-have-account . "¿Ya tienes cuenta?")
 (:auth-google . "Google")
 (:auth-account-created . "¡Cuenta creada!")
 (:auth-check-email . "Revisa tu correo electrónico para el enlace de activación.")
 (:auth-redirect-login . "Redirigiendo al inicio de sesión en")
 (:auth-seconds . "segundos...")
 (:auth-go-now . "Ir ahora")
 (:auth-not-activated . "Cuenta no activada")
 (:auth-activate-title . "¡Activa tu cuenta!")
 (:auth-activated . "¡Cuenta activada!")
 (:auth-activated-message . "Tu cuenta ha sido activada. Ya puedes usar Hiisi.")
 (:auth-redirecting . "Redirigiendo en")
 (:auth-go-to-app . "Ir a la app")
 (:auth-resend-title . "Reenviar correo de activación")
 (:auth-resend-subtitle . "Ingresa tu correo para recibir un nuevo enlace de activación.")
 (:auth-resend-button . "Reenviar correo de activación")
 (:auth-resend-success . "¡Correo de activación enviado!")
 (:auth-resend-success-detail . "Revisa tu bandeja de entrada para el nuevo enlace de activación.")
 (:auth-resend-rate-limited . "Por favor espera unos minutos antes de solicitar otro correo de activación.")
 (:auth-resend-cooldown . "Puedes solicitar otro correo en ~a segundos.")
 (:auth-back-to-login . "Volver al inicio de sesión")
 (:auth-forgot-password-title . "Olvidé mi contraseña")
 (:auth-forgot-password-subtitle . "Ingresa tu correo y te enviaremos un enlace para restablecer tu contraseña.")
 (:auth-send-reset-link . "Enviar enlace de restablecimiento")
 (:auth-reset-email-sent . "¡Enlace enviado!")
 (:auth-reset-email-sent-detail . "Si existe una cuenta con ese correo, recibirás un enlace para restablecer tu contraseña pronto.")
 (:auth-reset-rate-limited . "Por favor espera unos minutos antes de solicitar otro restablecimiento de contraseña.")
 (:auth-reset-invalid-token . "Este enlace de restablecimiento es inválido o ha expirado.")
 (:auth-reset-password-title . "Restablecer contraseña")
 (:auth-reset-password-subtitle . "Ingresa tu nueva contraseña abajo.")
 (:auth-new-password . "Nueva contraseña")
 (:auth-confirm-new-password . "Confirmar nueva contraseña")
 (:auth-reset-password . "Restablecer contraseña")
 (:auth-password-changed . "¡Contraseña cambiada!")
 (:auth-password-changed-detail . "Tu contraseña ha sido cambiada exitosamente. Ahora puedes iniciar sesión con tu nueva contraseña.")
 (:auth-change-password-title . "Cambiar contraseña")
 (:auth-change-password-subtitle . "Actualiza la contraseña de tu cuenta.")
 (:auth-current-password . "Contraseña actual")
 (:auth-change-password . "Cambiar contraseña")
 (:auth-back-to-app . "Volver a la app")
 (:auth-password-updated . "¡Contraseña actualizada!")
 (:auth-password-updated-detail . "Tu contraseña ha sido actualizada exitosamente.")
(:auth-current-password-invalid . "La contraseña actual es incorrecta.")
(:auth-new-password-same . "La nueva contraseña debe ser diferente de la contraseña actual.")

 ;; Translation page
 (:translate-title . "Traducir")
 (:translate-input-label . "Texto a traducir")
 (:translate-input-placeholder . "Ingresa el texto a traducir...")
 (:translate-from . "Idioma de origen:")
 (:translate-to . "Idioma de destino:")
 (:translate-submit . "Traducir")
 (:translate-auto-detect . "Cualquiera (Autodetectar)")
 (:translate-empty-state . "Ingresa texto arriba y haz clic en Traducir para ver el resultado con análisis gramatical")
 (:translate-select-deck-placeholder . "Seleccionar mazo (opcional)")
 (:translate-new-deck . "Nuevo mazo")
 (:translate-add-to-deck . "Añadir al mazo")
 (:translate-bookmark . "Guardar")
 (:translate-bookmarked . "Guardado")
 (:translate-retry . "Reintentar")
 (:translate-like-tooltip . "Buena traducción")
 (:translate-dislike-tooltip . "Mala traducción - solicitar una nueva")
 (:translate-dislike-confirm . "Esto generará una nueva traducción. ¿Continuar?")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Destino")
 (:translate-deck-create-title . "Crear nuevo mazo")
 (:translate-deck-name-label . "Nombre del mazo")
 (:translate-deck-name-placeholder . "p. ej., Fundamentos de finés")
 (:translate-deck-description-label . "Descripción (opcional)")
 (:translate-deck-cancel . "Cancelar")
 (:translate-deck-create . "Crear")
 (:translate-rate-label . "Valorar traducción")
 (:flashcards-delete-confirm . "¿Seguro que quieres eliminar esta tarjeta?")
 (:flashcards-deck-search-placeholder . "Buscar mazos...")
 (:flashcards-no-decks . "Aún no hay mazos. Crea uno primero.")
 (:flashcards-deck-cancel . "Cancelar")
 (:flashcards-recollection-tooltip . "Recuerdo: ~A")
 (:flashcards-recollection-poor . "Débil")
 (:flashcards-recollection-fair . "Aceptable")
 (:flashcards-recollection-normal . "Normal")
 (:flashcards-recollection-strong . "Fuerte")
 (:flashcards-recollection-very-strong . "Muy fuerte")

 ;; Flashcard review
 (:review-title . "Repasar")
 (:review-session-title . "Sesión de repaso")
 (:review-session-subtitle . "Practica tus tarjetas guardadas")
 (:review-selector-title . "Elige qué repasar")
 (:review-selector-subtitle . "Selecciona un mazo o un par de idiomas para enfocar tu sesión de repaso.")
 (:review-by-deck . "Repasar por mazo")
 (:review-by-language-pair . "Repasar por par de idiomas")
 (:review-all-cards . "Repasar todas las tarjetas")

 (:review-no-cards . "No hay tarjetas para repasar")
 (:review-no-cards-desc . "No tienes tarjetas pendientes de repaso en este momento.")
 (:review-no-cards-hint . "¡Traduce texto y haz clic en \"Guardar en tarjetas\" para crear tu mazo!")
 (:review-start-translating . "Empezar a traducir")
 (:review-click-reveal . "Haz clic para revelar la respuesta")
 (:review-grammar-breakdown . "Análisis gramatical")
 (:review-how-well . "¿Lo recordaste?")
 (:review-again . "No")
 (:review-hard . "A duras penas")
 (:review-good . "Sí")
 (:review-easy . "Fácilmente")
 (:review-progress . "Tarjeta ~a de ~a")
 (:review-complete . "¡Sesión completada!")
 (:review-complete-msg . "Repasaste ~a tarjetas")
 (:review-again-btn . "Repasar de nuevo")
 (:review-translate-more . "Traducir más")
 (:review-streak . "días de racha")

 ;; Dashboard
 (:dashboard-title . "Panel")
 (:dashboard-cards-due . "Tarjetas pendientes")
 (:dashboard-total-cards . "Total de tarjetas")
 (:dashboard-mastered-cards . "Tarjetas dominadas")
 (:dashboard-subscription . "Suscripción")
 (:dashboard-subscribed-until . "Suscrito hasta")
 (:dashboard-not-subscribed . "Sin suscripción")
 (:dashboard-recent . "Traducciones recientes")
 (:dashboard-no-translations . "Aún no hay traducciones")
 (:dashboard-streak . "Racha de repaso")
 (:dashboard-days . "días")
 (:dashboard-all-caught-up . "Todo al día.")
 (:dashboard-all-caught-up-hint . "Traduce más para ampliar tu colección.")
 (:dashboard-quick-actions . "Acciones rápidas")
 (:dashboard-getting-started . "Primeros pasos")
 (:dashboard-tip-1 . "Traduce el texto que quieras aprender")
 (:dashboard-tip-2 . "Haz clic en \"Guardar en tarjetas\" en las traducciones que quieras recordar")
 (:dashboard-tip-3 . "Repasa tus tarjetas regularmente - la repetición espaciada te ayuda a recordar a largo plazo")
 (:dashboard-tip-4 . "Califica honestamente - ayuda al algoritmo a programar tus repasos de forma óptima")

 ;; Account
 (:account-title . "Cuenta")
 (:account-subtitle . "Administra la configuración de tu cuenta y el calendario de eliminación.")
 (:account-deletion-title . "Eliminación de cuenta")
 (:account-deletion-scheduled . "Tu cuenta está programada para eliminarse el ~A.")
 (:account-deletion-cancel-hint . "Puedes cancelar antes de esta fecha para conservar tu cuenta.")
 (:account-deletion-cancel . "Cancelar eliminación")
 (:account-deletion-request . "Puedes solicitar la eliminación de la cuenta en cualquier momento. La eliminación se programa 14 días después de la confirmación. Si cambias de idea, contacta con soporte antes de que termine ese período de 14 días.")
 (:account-deletion-confirm . "¿Programar la eliminación de la cuenta dentro de 14 días a partir de hoy?")
 (:account-deletion-schedule . "Programar eliminación")
 (:account-reminders-title . "Recordatorios por correo")
 (:account-reminders-subtitle . "Controla los recordatorios de repaso y continuación de esta cuenta.")
 (:account-reminders-opt-out . "Desactivar recordatorios de repaso y continuación")
 (:account-reminders-save . "Guardar preferencias")

 ;; Subscription
 (:subscribe-title . "Precios simples")
 (:subscribe-choose-plan . "Elige tu plan")
 (:subscribe-start-today . "Empieza a aprender hoy con una prueba gratuita de 7 días")
 (:subscribe-monthly . "Mensual")
 (:subscribe-annual . "Anual")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/mes")
 (:subscribe-per-year . "/año")
 (:subscribe-monthly-desc . "600 traducciones al mes")
 (:subscribe-unlimited-flashcards . "Tarjetas ilimitadas")
 (:subscribe-grammar-explanations . "Explicaciones gramaticales")
 (:subscribe-spaced-repetition . "Repetición espaciada")
 (:subscribe-annual-desc . "¡Ahorra 20€ — dos meses gratis!")
 (:subscribe-manage . "Gestionar suscripción")
 (:subscribe-activated . "¡Suscripción activada!")
 (:subscribe-thank-you . "Gracias por suscribirte. Tu cuenta ya está activa.")
 (:subscribe-start-learning . "Empezar a aprender")
 (:subscribe-management . "Gestión de suscripción")
 (:subscribe-active . "Suscripción activa")
 (:subscribe-preapproved-access . "Acceso preaprobado")
 (:subscribe-status . "Estado:")
 (:subscribe-status-active . "Activa")
 (:subscribe-status-preapproved . "Preaprobado")
 (:subscribe-preapproved-detail . "Esta cuenta usa un acceso preaprobado gestionado por Hiisi.")
 (:subscribe-days-remaining . "Días restantes:")
 (:subscribe-renews-on . "Se renueva el:")
 (:subscribe-no-subscription . "Sin suscripción activa")
 (:subscribe-access-features . "Suscríbete para acceder a todas las funciones.")
 (:subscribe-view-plans . "Ver planes")
 (:subscribe-faq-title . "Preguntas frecuentes")
 (:subscribe-faq-trial-q . "¿Qué pasa después de la prueba gratuita?")
 (:subscribe-faq-trial-a . "Después de tu prueba gratuita de 7 días, se te cobrará por el plan seleccionado. Puedes cancelar en cualquier momento antes de que termine la prueba.")
 (:subscribe-faq-cancel-q . "¿Puedo cancelar en cualquier momento?")
 (:subscribe-faq-cancel-a . "¡Sí! Puedes cancelar tu suscripción en cualquier momento. Mantendrás el acceso hasta el final de tu período de facturación.")
 (:subscribe-faq-payment-q . "¿Qué métodos de pago aceptan?")
 (:subscribe-faq-payment-a . "Aceptamos todas las tarjetas de crédito y débito principales a través de nuestro socio de pagos Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")
(:subscribe-checkout-unavailable . "El proceso de pago está temporalmente no disponible. Inténtalo de nuevo.")
(:subscribe-portal-unavailable . "La gestión de la suscripción está temporalmente no disponible. Inténtalo de nuevo.")

 ;; Errors and status
 (:error-generic . "Algo salió mal")
(:error-invalid-request . "Datos de solicitud no válidos.")
(:error-not-found . "No se encontró el recurso solicitado.")
(:error-forbidden . "No tienes acceso a esto.")
(:error-rate-limited . "Espera un momento e inténtalo de nuevo.")
 (:error-text-too-long . "El texto es demasiado largo. La longitud máxima de traducción es de 120 caracteres.")
 (:error-input-too-long . "Texto demasiado largo")
 (:error-unknown-source-lang . "El idioma de origen seleccionado no es compatible.")
 (:error-unknown-target-lang . "El idioma de destino seleccionado no es compatible.")
 (:error-unknown-language . "Idioma desconocido")
 (:error-translation-unavailable . "El servicio de traducción no está disponible temporalmente. Por favor, inténtalo de nuevo en un momento.")
 (:error-translation-failed . "Traducción fallida")
 (:error-translation-retry . "No se pudo generar una traducción después de varios intentos. Por favor, intenta reformular tu texto.")
 (:error-quota-exceeded . "Límite de traducciones alcanzado")
 (:error-quota-exceeded-detail . "Has usado todas tus traducciones de este mes. Tu cuota se restablece automáticamente cada mes.")
 (:quota-low-warning . "Solo quedan ~A traducciones. Considere comprar más.")
 (:top-up-button . "Comprar más traducciones")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 traducciones")
(:review-session-expired . "Tu sesión de repaso ha expirado. Inicia una nueva sesión.")

 ;; Institutions
 (:institutions-page-title . "Hiisi para escuelas y universidades")
 (:institutions-hero-title . "Herramientas para la enseñanza de idiomas hechas para el aula")
 (:institutions-hero-subtitle . "Ofrece a tus estudiantes mazos compartibles, práctica con atención a la gramática y rutinas de repaso constantes que encajan en la enseñanza real.")
 (:institutions-section-title . "Por qué las instituciones usan Hiisi")
 (:institutions-section-body . "Hiisi ayuda al profesorado a convertir el material de clase en un estudio guiado que el alumnado realmente puede seguir. Crea mazos para un curso, compártelos con un enlace y apoya la práctica de vocabulario y gramática sin carga administrativa adicional.")
 (:institutions-benefit-1 . "Mazos compartibles y tareas personalizadas que se ajustan a tu plan de estudios.")
 (:institutions-benefit-2 . "Los me gusta y no me gusta del alumnado ayudan a que las mejores traducciones destaquen en frases habituales del aula.")
 (:institutions-benefit-3 . "Los desgloses gramaticales y el repaso espaciado apoyan mucho más que memorizar listas aisladas de palabras.")
 (:institutions-benefit-4 . "Acompañamiento pensado por y para docentes, de alguien que escucha con atención y se toma en serio las necesidades del aula.")
 (:institutions-request-title . "Empecemos a hablar")
 (:institutions-request-subtitle . "Cuéntanos sobre tu institución, tus idiomas y el tipo de apoyo docente que necesitas. Te responderemos en el plazo de una semana.")
 (:institutions-field-name . "Nombre de la institución")
 (:institutions-field-name-placeholder . "Universidad de Helsinki")
 (:institutions-field-contact-name . "Nombre de contacto")
 (:institutions-field-contact-name-placeholder . "Tu nombre")
 (:institutions-field-contact-email . "Correo de contacto")
 (:institutions-field-contact-email-placeholder . "tu@universidad.edu")
 (:institutions-field-domains . "Dominios de correo")
 (:institutions-field-domains-placeholder . "universidad.edu, cs.universidad.edu")
 (:institutions-field-domains-help . "Lista separada por comas de dominios de correo de tu institución")
 (:institutions-field-notes . "Información adicional")
 (:institutions-field-notes-placeholder . "Número estimado de estudiantes, ciclo de facturación preferido, requisitos especiales...")
 (:institutions-submit . "Enviar solicitud")
 (:institutions-success-title . "Gracias - Hiisi para escuelas y universidades")
 (:institutions-success-heading . "Gracias!")
 (:institutions-success-body . "Hemos recibido tu consulta. Revisaremos las necesidades de tu institución y te responderemos en el plazo de una semana.")
 (:institutions-success-back . "Volver al inicio")

 ;; Footer
 (:footer-privacy . "Política de privacidad")
 (:footer-terms . "Términos de servicio")

 ;; Early software notice
 (:early-software-notice . "Hiisi está en desarrollo temprano. ¿Encontraste un error o tienes una sugerencia?")

 ;; Política de privacidad
 (:privacy-title . "Política de privacidad")
 (:privacy-updated . "Última actualización: enero de 2026")
 (:privacy-who-title . "Quiénes somos")
 (:privacy-who-body . "Hiisi es operado por Lambda Symbolics OÜ, una empresa registrada en Estonia. Como empresa estonia, cumplimos con el Reglamento General de Protección de Datos (GDPR) de la Unión Europea.")
 (:privacy-collect-title . "Datos que recopilamos")
 (:privacy-collect-intro . "Cuando usas Hiisi, recopilamos la siguiente información:")
 (:privacy-collect-account-key . "Información de la cuenta: ")
 (:privacy-collect-account-val . "Dirección de correo electrónico, nombre para mostrar y una contraseña almacenada con hash seguro.")
 (:privacy-collect-learning-key . "Datos de aprendizaje: ")
 (:privacy-collect-learning-val . "Tus traducciones, tarjetas guardadas e historial de repaso.")
 (:privacy-collect-usage-key . "Datos de uso: ")
 (:privacy-collect-usage-val . "Registros básicos del servidor para fines de seguridad y depuración.")
 (:privacy-use-title . "Cómo usamos tus datos")
 (:privacy-use-auth-key . "Autenticación: ")
 (:privacy-use-auth-val . "Para verificar tu identidad y proteger tu cuenta.")
 (:privacy-use-service-key . "Prestación del servicio: ")
 (:privacy-use-service-val . "Para proporcionar traducciones y gestionar tu colección de tarjetas.")
 (:privacy-use-ai-key . "Traducciones con IA: ")
 (:privacy-use-ai-val . "Tus solicitudes de traducción se envían a OpenRouter para generar respuestas. OpenRouter puede enrutar las solicitudes al proveedor de modelos configurado. Consulta la política de privacidad de OpenRouter para saber cómo trata estos datos.")
 (:privacy-third-title . "Servicios de terceros")
 (:privacy-third-intro . "Usamos los siguientes servicios de terceros:")
 (:privacy-third-openrouter-key . "OpenRouter: ")
 (:privacy-third-openrouter-val . "Para solicitudes automáticas de traducción.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "Para enviar correos de activación de cuenta y correos transaccionales.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Para procesar pagos de suscripción.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "Usamos solo cookies esenciales:")
 (:privacy-cookies-auth-key . "Token de autenticación: ")
 (:privacy-cookies-auth-val . "Una cookie segura, solo HTTP, para mantener tu sesión iniciada.")
 (:privacy-cookies-lang-key . "Preferencia de idioma: ")
 (:privacy-cookies-lang-val . "Para recordar tu idioma preferido de la interfaz.")
 (:privacy-retention-title . "Conservación de datos")
 (:privacy-retention-body . "Tus datos se almacenan mientras mantengas una cuenta. Cuando solicitas su eliminación, tu cuenta se programa para eliminarse en 14 días.")
 (:privacy-rights-title . "Tus derechos (GDPR)")
 (:privacy-rights-intro . "Según el GDPR, tienes derecho a:")
 (:privacy-rights-access . "Acceder a tus datos personales")
 (:privacy-rights-export . "Exportar tus datos (disponible en /app/api/export)")
 (:privacy-rights-correct . "Solicitar la corrección de datos inexactos")
 (:privacy-rights-delete . "Solicitar la eliminación de tu cuenta y tus datos")
 (:privacy-rights-object . "Oponerte al tratamiento de tus datos")
 (:privacy-rights-contact . "Para ejercer estos derechos, contáctanos en")
 (:privacy-contact-title . "Contacto")
 (:privacy-contact-intro . "Para consultas relacionadas con la privacidad:")
 (:privacy-contact-email-label . "Correo electrónico: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Términos de servicio
 (:terms-title . "Términos de servicio")
 (:terms-updated . "Última actualización: enero de 2026")
 (:terms-1-title . "1. Descripción del servicio")
 (:terms-1-body . "Hiisi es una aplicación de aprendizaje de idiomas que ofrece traducciones automáticas con explicaciones gramaticales y tarjetas de repetición distribuida. El servicio es operado por Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Registro de cuenta")
 (:terms-2-body . "Para usar Hiisi, debes crear una cuenta con una dirección de correo válida. Eres responsable de mantener la seguridad de las credenciales de tu cuenta.")
 (:terms-3-title . "3. Suscripción y pagos")
 (:terms-3-body . "Hiisi ofrece planes de suscripción de pago (mensual y anual). Las suscripciones se procesan mediante Polar.sh.")
 (:terms-3-list-1 . "Las suscripciones se renuevan automáticamente a menos que se cancelen antes de la fecha de renovación.")
 (:terms-3-list-2 . "Los reembolsos se proporcionan conforme a la normativa de protección al consumidor aplicable.")
 (:terms-3-list-3 . "La falta de pago implica la pérdida de acceso a funciones premium.")
 (:terms-4-title . "4. Uso aceptable")
 (:terms-4-intro . "Aceptas no:")
 (:terms-4-list-1 . "Usar el servicio para fines ilegales")
 (:terms-4-list-2 . "Intentar eludir límites de uso o medidas de seguridad")
 (:terms-4-list-3 . "Compartir las credenciales de tu cuenta con otras personas")
 (:terms-4-list-4 . "Usar herramientas automatizadas de manera que degraden el rendimiento para otras personas")
 (:terms-5-title . "5. Contenido y propiedad intelectual")
 (:terms-5-body-1 . "Las traducciones generadas por Hiisi se crean automáticamente y pueden no ser únicas. Puedes usar tus traducciones y tarjetas para cualquier fin personal, pero no tienes derechos exclusivos de autoría sobre contenido generado automáticamente.")
 (:terms-5-body-2 . "La aplicación Hiisi, su marca y su contenido original siguen siendo propiedad de Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Disponibilidad del servicio")
 (:terms-6-intro . "Hiisi se proporciona tal cual. No garantizamos:")
 (:terms-6-list-1 . "Servicio ininterrumpido o libre de errores")
 (:terms-6-list-2 . "Exactitud de las traducciones generadas automáticamente")
 (:terms-6-list-3 . "Disponibilidad de funciones específicas")
 (:terms-6-body . "Podemos modificar o discontinuar funciones en cualquier momento.")
 (:terms-7-title . "7. Limitación de responsabilidad")
 (:terms-7-body-1 . "En la máxima medida permitida por la ley, Lambda Symbolics OÜ no será responsable por daños indirectos, incidentales, especiales o consecuentes derivados de tu uso de Hiisi.")
 (:terms-7-body-2 . "Nuestra responsabilidad total no superará el importe que hayas pagado por el servicio durante los 12 meses anteriores a la reclamación.")
 (:terms-8-title . "8. Terminación de cuenta")
 (:terms-8-body-1 . "Podemos suspender o terminar tu cuenta si incumples estos términos. Puedes solicitar la eliminación de tu cuenta en cualquier momento desde la aplicación.")
 (:terms-8-body-2 . "Tras una solicitud de eliminación, tu cuenta se programa para eliminarse en 14 días.")
 (:terms-9-title . "9. Cambios en los términos")
 (:terms-9-body . "Podemos actualizar estos términos periódicamente. El uso continuado de Hiisi después de los cambios constituye la aceptación de los nuevos términos.")
 (:terms-10-title . "10. Ley aplicable")
 (:terms-10-body . "Estos términos se rigen por las leyes de Estonia. Cualquier disputa se resolverá en los tribunales de Estonia.")
 (:terms-contact-title . "Contacto")
 (:terms-contact-intro . "Para preguntas sobre estos términos:")
 (:terms-contact-email-label . "Correo electrónico: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Decks
 (:decks-title . "Mazos")
 (:decks-subtitle . "Crea mazos personalizados y compártelos con otros.")
 (:decks-create-title . "Crear mazo")
 (:decks-name-placeholder . "Nombre del mazo")
 (:decks-desc-placeholder . "Descripción")
 (:decks-create-btn . "Crear mazo")
 (:decks-edit-title . "Editar mazo")
 (:decks-edit-btn . "Editar mazo")
 (:decks-update-btn . "Guardar cambios")
 (:decks-default-badge . "Automático")
 (:decks-default-description . "Este mazo se gestiona automáticamente para este par de idiomas.")
 (:decks-default-readonly . "Los mazos automáticos tienen nombres y descripciones fijos.")
 (:decks-error-name-required . "El nombre del mazo es obligatorio.")
 (:decks-error-name-too-long . "El nombre del mazo debe tener como máximo ~A caracteres.")
 (:decks-error-desc-too-long . "La descripción del mazo debe tener como máximo ~A caracteres.")
 (:decks-error-default-readonly . "Los mazos automáticos no se pueden editar.")
 (:decks-your-title . "Tus mazos")
 (:decks-col-updated . "Actualizado")
 (:decks-no-decks . "Aún no hay mazos.")
 (:decks-open-btn . "Abrir")
 (:decks-no-desc . "Sin descripción.")
 (:decks-share-title . "Enlace para compartir")
 (:decks-share-info . "Cualquiera con este enlace puede importar el mazo:")
 (:decks-share-copy . "Copiar enlace")
 (:decks-share-copied . "Copiado")
 (:decks-add-from-flashcards-title . "Añadir traducciones")
 (:decks-add-from-flashcards-info . "Elige una tarjeta para añadir su traducción a este mazo.")
 (:decks-open-flashcards . "Añadir desde tarjetas")
 (:decks-filter-from . "Idioma de origen")
 (:decks-filter-to . "Idioma de destino")
 (:decks-filter-any . "Cualquier idioma")
 (:decks-filter-include-assigned . "Incluir tarjetas que ya están en un mazo")
 (:decks-flashcards-add . "Añadir")
 (:decks-flashcards-added . "Añadido")
 (:decks-flashcards-in-deck . "En otro mazo")
 (:decks-flashcards-empty . "Ninguna tarjeta coincide con estos filtros.")
 (:decks-items-title . "Contenido del mazo")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Traducción")
 (:decks-col-lang . "Idioma destino")
 (:decks-no-items . "Aún no hay elementos.")
 (:decks-share-page-title . "Compartir mazo")
 (:decks-share-preview . "Vista previa e importación de este mazo.")
 (:decks-import-title . "Importar")
 (:decks-import-btn . "Importar mazo")
 (:starter-decks-title . "Biblioteca")
 (:starter-decks-subtitle . "Elige un trío de idiomas, explora mazos oficiales y de la comunidad e importa mazos de estudio listos para usar.")
 (:starter-decks-marketplace-btn . "Biblioteca")
 (:starter-decks-explanation-language . "Idioma de explicación")
 (:starter-decks-search-label . "Buscar")
 (:starter-decks-search-placeholder . "Buscar en la biblioteca")
 (:starter-decks-apply-filters . "Aplicar filtros")
 (:starter-decks-select-triplet-hint . "Elige el idioma de origen y destino para explorar mazos compatibles.")
 (:starter-decks-official-badge . "Oficial")
 (:starter-decks-community-badge . "Comunidad")
 (:starter-decks-by-hiisi . "De Hiisi")
 (:starter-decks-preview-btn . "Vista previa")
 (:starter-decks-card-count . "~A tarjetas")
 (:starter-decks-no-results . "Ningún mazo coincide con estos filtros.")
 (:starter-decks-concepts-title . "Conceptos de tarjetas previstos")
 (:starter-decks-sample-title . "Tarjetas de muestra")
 (:starter-decks-generating . "Generando mazo...")
 (:starter-decks-generating-detail . "Este mazo se está generando para tu trío de idiomas. Deja esta página abierta o vuelve dentro de un momento.")
 (:starter-decks-generation-failed . "La generación falló")
 (:starter-decks-generation-failed-detail . "El último intento de generación falló. Intenta importar el mazo de nuevo.")
 (:starter-decks-login-detail . "Inicia sesión para importar este mazo a tu colección.")
 (:starter-decks-subscribe-btn . "Ver planes")
 (:starter-decks-subscribe-detail . "Los mazos de la biblioteca están disponibles con una suscripción activa o una prueba.")
 (:library-submit-title . "Enviar a la biblioteca")
 (:library-submit-intro . "Envía este mazo a la biblioteca para revisión administrativa antes de su publicación.")
 (:library-submit-btn . "Enviar mazo")
 (:library-submit-approved . "Aprobado para la biblioteca")
 (:library-submit-approved-detail . "Este mazo está publicado en la biblioteca.")
 (:library-submit-pending . "En revisión")
 (:library-submit-pending-detail . "Este mazo se ha enviado y está esperando la revisión administrativa.")
 (:library-submit-rejected . "Necesita cambios antes de publicarse")
 (:library-submit-rejected-detail . "Este envío fue rechazado. Actualiza el mazo y vuelve a enviarlo.")
 (:library-error-empty . "Añade al menos una tarjeta antes de enviar este mazo a la biblioteca.")
 (:library-error-missing-triplet . "Cada tarjeta de un envío a la biblioteca debe tener un trío de idiomas completo.")
 (:library-error-mixed-triplet . "Todas las tarjetas de un envío a la biblioteca deben compartir el mismo trío de idiomas.")
 (:starter-deck-topic-greetings-title . "Saludos y presentaciones")
 (:starter-deck-topic-greetings-description . "Saludos, nombres, fórmulas básicas de cortesía y frases para un primer encuentro.")
 (:starter-deck-topic-travel-title . "Viaje esencial")
 (:starter-deck-topic-travel-description . "Estaciones, billetes, precios, pedir ayuda y moverse de un lugar a otro.")
 (:starter-deck-topic-numbers-title . "Números y precios")
 (:starter-deck-topic-numbers-description . "Contar, totales, precios, pisos y cantidades cotidianas.")
 (:starter-deck-topic-time-title . "Hora y fechas")
 (:starter-deck-topic-time-description . "Días, meses, citas, la hora y fechas relativas.")
 (:starter-deck-topic-food-title . "Restaurante y comida")
 (:starter-deck-topic-food-description . "Pedir, necesidades alimentarias, bebidas, la cuenta y comidas cotidianas fuera de casa.")
 (:starter-deck-topic-emergency-title . "Emergencias y salud")
 (:starter-deck-topic-emergency-description . "Médicos, farmacias, síntomas, partes del cuerpo y ayuda urgente.")
 (:starter-deck-topic-directions-title . "Indicaciones y transporte")
 (:starter-deck-topic-directions-description . "Giros, paradas, billetes, andenes y moverse por la ciudad.")
 (:starter-deck-topic-school-title . "Escuela y educación")
 (:starter-deck-topic-school-description . "Clases, deberes, exámenes, material escolar y la vida diaria en la escuela.")
 (:starter-deck-topic-university-title . "Universidad y estudios")
 (:starter-deck-topic-university-description . "Clases magistrales, seminarios, carreras, trabajos y la vida diaria en el campus.")

 ;; Flashcards management page
 (:flashcards-title . "Mis tarjetas")
 (:flashcards-subtitle . "Todas tus tarjetas guardadas en un solo lugar. Busca, organiza y gestiona.")
 (:flashcards-search-placeholder . "Buscar tarjetas...")
 (:flashcards-filter-button . "Filtros")
 (:flashcards-filter-title . "Filtrar tarjetas")
 (:flashcards-filter-recollection . "Qué tan bien las conoces")
 (:flashcards-filter-any-recollection . "Cualquier nivel")
 (:flashcards-hide-perfected . "Ocultar tarjetas dominadas")
 (:flashcards-col-original . "Original")
 (:flashcards-col-translated . "Traducción")
 (:flashcards-no-cards . "Aún no hay tarjetas. ¡Comienza a traducir para crear algunas!")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Aprende idiomas de forma integral")
 (:landing-hero-subheadline . "Obtén traducciones con análisis gramatical completo y construye vocabulario duradero con tarjetas de repetición espaciada.")
 (:landing-hero-trust-line . "7 días de prueba gratis con 100 traducciones. Cancela en cualquier momento.")
 (:landing-credibility-languages . "14 idiomas")
 (:landing-credibility-ai . "Análisis gramatical incluido")
 (:landing-step-1-title . "Traduce cualquier texto")
 (:landing-step-1-desc . "Ingresa una palabra o frase. Obtén una traducción con análisis gramatical completo.")
 (:landing-step-2-title . "Guarda como tarjetas")
 (:landing-step-2-desc . "Guarda las traducciones que quieras recordar. Las tarjetas se crean automáticamente.")
 (:landing-step-3-title . "Repasa y recuerda")
 (:landing-step-3-desc . "La repetición espaciada programa repasos en el momento ideal para la memoria a largo plazo.")
 (:landing-feature-grammar-title . "Comprende la gramática, no solo las palabras")
 (:landing-feature-grammar-desc . "Cada traducción incluye un análisis gramatical detallado - formas de palabras, casos y conjugaciones explicadas en tu idioma.")
 (:landing-feature-srs-title . "Memorización respaldada por la ciencia")
 (:landing-feature-srs-desc . "El algoritmo SM-2 se adapta a tu rendimiento. Las tarjetas difíciles aparecen más a menudo. Las que dominas aparecen menos.")
 (:landing-feature-share-title . "Comparte mazos con estudiantes")
 (:landing-feature-share-desc . "Los profesores pueden crear mazos personalizados y compartirlos con un enlace. Los estudiantes importan el mazo y empiezan a repasar de inmediato.")
 (:landing-pricing-trial-note . "Incluye 7 días de prueba gratis")
 (:landing-pricing-monthly-after . "7 días gratis, luego ~A/mes")
 (:landing-pricing-annual-after . "7 días gratis, luego ~A/año")
 (:landing-faq-title . "Preguntas frecuentes")
 (:landing-faq-trial-cap-q . "¿Cuántas traducciones obtengo durante la prueba?")
 (:landing-faq-trial-cap-a . "Obtienes 100 traducciones durante tu prueba de 7 días. Después de suscribirte, obtienes 600 por mes.")
 (:landing-final-cta-title . "Empieza a aprender hoy")
 (:landing-final-cta-subtitle . "Únete a Hiisi y empieza a construir vocabulario que perdura.")

 ;; Trial status (in-app)
 (:trial-status . "Prueba gratuita")
 (:error-trial-quota-exceeded . "Límite de traducciones de prueba alcanzado")
 (:error-trial-quota-detail . "Has usado las 100 traducciones de prueba. Suscríbete para seguir aprendiendo.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Crear tarjeta")
 (:custom-flashcard-edit-title . "Editar tarjeta")
 (:custom-flashcard-original . "Texto original")
 (:custom-flashcard-translated . "Traducción")
 (:custom-flashcard-lang-from . "Idioma de origen")
 (:custom-flashcard-lang-to . "Idioma de destino")
 (:custom-flashcard-note . "Nota educativa")
 (:custom-flashcard-forms . "Análisis gramatical")
 (:custom-flashcard-form-term . "Término")
 (:custom-flashcard-form-explanation . "Explicación")
 (:custom-flashcard-add-form . "Agregar término gramatical")
 (:custom-flashcard-remove-form . "Eliminar")
 (:custom-flashcard-ai-fill . "Rellenar con IA")
 (:custom-flashcard-create-btn . "Crear tarjeta")
 (:custom-flashcard-update-btn . "Guardar cambios")

 ;; Reporte de problemas
 (:issues-open-button . "Reportar un problema")
 (:issues-modal-title . "Reportar un problema")
 (:issues-modal-subtitle . "Describe qué salió mal. Incluiremos automáticamente la página actual.")
 (:issues-title-label . "Título breve")
 (:issues-title-placeholder . "Resumen breve del problema")
 (:issues-message-label . "¿Qué ocurrió?")
 (:issues-message-placeholder . "Incluye pasos para reproducir, el comportamiento esperado y lo que ocurrió en su lugar.")
 (:issues-submit . "Enviar reporte")
 (:issues-cancel . "Cancelar")
 (:issues-success . "Gracias. Tu reporte de problema fue enviado.")
 (:issues-error-required . "Describe el problema antes de enviarlo.")
 (:issues-error-title-too-long . "El título del reporte es demasiado largo. Mantenlo por debajo de 160 caracteres.")
 (:issues-error-too-long . "El texto del reporte es demasiado largo. Mantenlo por debajo de 4000 caracteres.")
 (:issues-error-rate-limit . "Demasiados reportes desde este origen. Espera e inténtalo de nuevo más tarde.")
 (:issues-error-generic . "No se pudo enviar el reporte de problema. Inténtalo de nuevo.")

)
