;;; Spanish translations
;;; This file should contain all keys from en.lisp

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Español")
 (:lang-flag . "🇪🇸")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Elige tu idioma")
 (:lang-modal-subtitle . "Selecciona tu idioma preferido para la interfaz:")

 ;; Navigation
 (:nav-translate . "Traducir")
 (:nav-review . "Repasar")
 (:nav-flashcards . "Mis tarjetas")
 (:nav-dashboard . "Panel")
 (:nav-decks . "Decks")
 (:nav-logout . "Cerrar sesión")
 (:nav-home . "Inicio")
 (:nav-pricing . "Precios")
 (:nav-export-data . "Exportar datos")

 ;; App title and branding
 (:app-title . "Hiisi - Aprendizaje de idiomas")
 (:app-tagline . "Aprende idiomas a través de traducciones")

 ;; Landing page
 (:landing-hero-title . "Domina cualquier idioma")
 (:landing-hero-subtitle . "Traduce lo que quieras. Genera automáticamente tarjetas que te enseñan por qué funciona así.")
 (:landing-cta . "Comenzar a aprender")
 (:landing-learn-more . "Más información")
 (:landing-how-it-works . "Cómo funciona")
 (:landing-feature-1-title . "Tarjetas automáticas")
 (:landing-feature-1-desc . "Cada traducción genera tarjetas automáticamente con análisis gramatical. Sin creación manual de tarjetas.")
 (:landing-feature-2-title . "Repetición espaciada")
 (:landing-feature-2-desc . "El algoritmo SM-2 programa repasos en intervalos óptimos. Aprende eficientemente, recuerda permanentemente.")
 (:landing-feature-3-title . "Enseñanza de gramática")
 (:landing-feature-3-desc . "Cada traducción explica la gramática, las raíces de las palabras y la estructura de las oraciones. Comprende el porqué, no solo el qué.")
 (:landing-free-trial . "Prueba gratuita de 7 días.")
 (:landing-start-trial . "Iniciar prueba gratuita")
 (:landing-best-value . "Mejor valor")
 (:landing-cta-title . "¿Listo para aprender idiomas a través de la gramática, no la memorización?")
 (:landing-cta-subtitle . "Cada traducción se convierte en una oportunidad de aprendizaje. Cada tarjeta te enseña el porqué.")
 (:landing-signup-free . "Regístrate gratis")

 ;; Auth pages
 (:auth-register . "Registrarse")
 (:auth-login . "Iniciar sesión")
 (:auth-logout . "Cerrar sesión")
 (:auth-email . "Correo electrónico")
 (:auth-password . "Contraseña")
 (:auth-password-again . "Confirmar contraseña")
 (:auth-display-name . "Nombre para mostrar")
 (:auth-register-title . "Regístrate en Hiisi")
 (:auth-register-subtitle . "Crear una cuenta nueva")
 (:auth-login-title . "Iniciar sesión en Hiisi")
 (:auth-login-subtitle . "Ingresa tus credenciales")
 (:auth-login-invalid-credentials . "Correo o contrasena incorrectos.")
 (:auth-login-rate-limited . "Demasiados intentos de inicio de sesion. Espera unos minutos e intentalo de nuevo.")
 (:auth-forgot-password . "¿Olvidaste tu contraseña?")
 (:auth-no-account . "¿No tienes cuenta?")
 (:auth-have-account . "¿Ya tienes cuenta?")
 (:auth-google . "Google")
 (:auth-account-created . "¡Cuenta creada!")
 (:auth-check-email . "Revisa tu correo electrónico para el enlace de activación.")
 (:auth-redirect-login . "Redirigiendo al inicio de sesión en")
 (:auth-seconds . "segundos...")
 (:auth-go-now . "Ir ahora")
 (:auth-not-activated . "Cuenta no activada")
 (:auth-activate-title . "¡Activa tu cuenta!")
 (:auth-activated . "¡Cuenta activada!")
 (:auth-activated-message . "Tu cuenta ha sido activada. Ya puedes usar Hiisi.")
 (:auth-redirecting . "Redirigiendo en")
 (:auth-go-to-app . "Ir a la app")
 (:auth-resend-title . "Reenviar correo de activación")
 (:auth-resend-subtitle . "Ingresa tu correo para recibir un nuevo enlace de activación.")
 (:auth-resend-button . "Reenviar correo de activación")
 (:auth-resend-success . "¡Correo de activación enviado!")
 (:auth-resend-success-detail . "Revisa tu bandeja de entrada para el nuevo enlace de activación.")
 (:auth-resend-rate-limited . "Por favor espera unos minutos antes de solicitar otro correo de activación.")
 (:auth-resend-cooldown . "Puedes solicitar otro correo en ~a segundos.")
 (:auth-back-to-login . "Volver al inicio de sesión")
 (:auth-forgot-password-title . "Olvidé mi contraseña")
 (:auth-forgot-password-subtitle . "Ingresa tu correo y te enviaremos un enlace para restablecer tu contraseña.")
 (:auth-send-reset-link . "Enviar enlace de restablecimiento")
 (:auth-reset-email-sent . "¡Enlace enviado!")
 (:auth-reset-email-sent-detail . "Si existe una cuenta con ese correo, recibirás un enlace para restablecer tu contraseña pronto.")
 (:auth-reset-rate-limited . "Por favor espera unos minutos antes de solicitar otro restablecimiento de contraseña.")
 (:auth-reset-invalid-token . "Este enlace de restablecimiento es inválido o ha expirado.")
 (:auth-reset-password-title . "Restablecer contraseña")
 (:auth-reset-password-subtitle . "Ingresa tu nueva contraseña abajo.")
 (:auth-new-password . "Nueva contraseña")
 (:auth-confirm-new-password . "Confirmar nueva contraseña")
 (:auth-reset-password . "Restablecer contraseña")
 (:auth-password-changed . "¡Contraseña cambiada!")
 (:auth-password-changed-detail . "Tu contraseña ha sido cambiada exitosamente. Ahora puedes iniciar sesión con tu nueva contraseña.")
 (:auth-change-password-title . "Cambiar contraseña")
 (:auth-change-password-subtitle . "Actualiza la contraseña de tu cuenta.")
 (:auth-current-password . "Contraseña actual")
 (:auth-change-password . "Cambiar contraseña")
 (:auth-back-to-app . "Volver a la app")
 (:auth-password-updated . "¡Contraseña actualizada!")
 (:auth-password-updated-detail . "Tu contraseña ha sido actualizada exitosamente.")

 ;; Translation page
 (:translate-title . "Traducir")
 (:translate-input-label . "Texto a traducir")
 (:translate-input-placeholder . "Ingresa el texto a traducir...")
 (:translate-from . "De:")
 (:translate-to . "A:")
 (:translate-submit . "Traducir")
 (:translate-save . "Guardar en tarjetas")
 (:translate-saved . "¡Guardado!")
 (:translate-like . "Me gusta")
 (:translate-dislike . "No me gusta")
 (:translate-char-limit . "caracteres restantes")
 (:translate-auto-detect . "Cualquiera (Autodetectar)")
 (:translate-empty-state . "Ingresa texto arriba y haz clic en Traducir para ver el resultado con análisis gramatical")
 (:translate-select-deck-placeholder . "Seleccionar mazo (opcional)")
 (:translate-new-deck . "Nuevo mazo")
 (:translate-add-to-deck . "Añadir al mazo")
 (:translate-bookmark . "Guardar")
 (:translate-bookmarked . "Guardado")
 (:translate-retry . "Reintentar")
 (:translate-like-tooltip . "Buena traducción")
 (:translate-dislike-tooltip . "Mala traducción - solicitar una nueva")
 (:translate-dislike-confirm . "Esto generará una nueva traducción. ¿Continuar?")
 (:translate-liked . "¡Me gusta!")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Destino")
 (:translate-deck-create-title . "Crear nuevo mazo")
 (:translate-deck-name-label . "Nombre del mazo")
 (:translate-deck-name-placeholder . "p. ej., Fundamentos de finés")
 (:translate-deck-description-label . "Descripción (opcional)")
 (:translate-deck-cancel . "Cancelar")
 (:translate-deck-create . "Crear")
 (:translate-rate-label . "Valorar traducción")
 (:flashcards-delete-confirm . "¿Seguro que quieres eliminar esta tarjeta?")
 (:flashcards-deck-search-placeholder . "Buscar mazos...")
 (:flashcards-no-decks . "Aún no hay mazos. Crea uno primero.")
 (:flashcards-deck-cancel . "Cancelar")
 (:flashcards-recollection-tooltip . "Recuerdo: ~A")
 (:flashcards-recollection-poor . "Débil")
 (:flashcards-recollection-fair . "Aceptable")
 (:flashcards-recollection-normal . "Normal")
 (:flashcards-recollection-strong . "Fuerte")
 (:flashcards-recollection-very-strong . "Muy fuerte")

 ;; Flashcard review
 (:review-title . "Repasar")
 (:review-session-title . "Sesión de repaso")
 (:review-session-subtitle . "Practica tus tarjetas guardadas")
 (:review-selector-title . "Elige qué repasar")
 (:review-selector-subtitle . "Selecciona un mazo o un par de idiomas para enfocar tu sesión de repaso.")
 (:review-by-deck . "Repasar por mazo")
 (:review-by-language-pair . "Repasar por par de idiomas")
 (:review-all-cards . "Repasar todas las tarjetas")

 (:review-start . "Iniciar repaso")
 (:review-no-cards . "No hay tarjetas para repasar")
 (:review-no-cards-desc . "No tienes tarjetas pendientes de repaso en este momento.")
 (:review-no-cards-hint . "¡Traduce texto y haz clic en \"Guardar en tarjetas\" para crear tu mazo!")
 (:review-start-translating . "Empezar a traducir")
 (:review-show-answer . "Mostrar respuesta")
 (:review-click-reveal . "Haz clic para revelar la respuesta")
 (:review-grammar-breakdown . "Análisis gramatical")
 (:review-how-well . "¿Qué tan bien lo recordaste?")
 (:review-again . "Otra vez")
 (:review-hard . "Difícil")
 (:review-good . "Bien")
 (:review-easy . "Fácil")
 (:review-progress . "Tarjeta ~a de ~a")
 (:review-complete . "¡Sesión completada!")
 (:review-complete-msg . "Repasaste ~a tarjetas")
 (:review-correct . "Correctas")
 (:review-accuracy . "Precisión")
 (:review-again-btn . "Repasar de nuevo")
 (:review-translate-more . "Traducir más")
 (:review-streak . "días de racha")

 ;; Dashboard
 (:dashboard-title . "Panel")
 (:dashboard-cards-due . "Tarjetas pendientes")
 (:dashboard-total-cards . "Total de tarjetas")
 (:dashboard-subscription . "Suscripción")
 (:dashboard-subscribed-until . "Suscrito hasta")
 (:dashboard-not-subscribed . "Sin suscripción")
 (:dashboard-recent . "Traducciones recientes")
 (:dashboard-no-translations . "Aún no hay traducciones")
 (:dashboard-streak . "Racha de repaso")
 (:dashboard-days . "días")
 (:dashboard-quick-actions . "Acciones rápidas")
 (:dashboard-getting-started . "Primeros pasos")
 (:dashboard-tip-1 . "Traduce el texto que quieras aprender")
 (:dashboard-tip-2 . "Haz clic en \"Guardar en tarjetas\" en las traducciones que quieras recordar")
 (:dashboard-tip-3 . "Repasa tus tarjetas regularmente - la repetición espaciada te ayuda a recordar a largo plazo")
 (:dashboard-tip-4 . "Califica honestamente - ayuda al algoritmo a programar tus repasos de forma óptima")

 ;; Account
 (:account-title . "Cuenta")
 (:account-subtitle . "Administra la configuración de tu cuenta y el calendario de eliminación.")
 (:account-deletion-title . "Eliminación de cuenta")
 (:account-deletion-scheduled . "Tu cuenta está programada para eliminarse el ~A.")
 (:account-deletion-cancel-hint . "Puedes cancelar antes de esta fecha para conservar tu cuenta.")
 (:account-deletion-cancel . "Cancelar eliminación")
 (:account-deletion-request . "Puedes solicitar la eliminación de la cuenta en cualquier momento. La eliminación se programa 14 días después de la confirmación. Si te arrepientes después de la eliminación, contacta con soporte.")
 (:account-deletion-confirm . "¿Programar la eliminación de la cuenta dentro de 14 días a partir de hoy?")
 (:account-deletion-schedule . "Programar eliminación")
 (:account-reminders-title . "Recordatorios por correo")
 (:account-reminders-subtitle . "Controla los recordatorios de repaso y continuación de esta cuenta.")
 (:account-reminders-opt-out . "Desactivar recordatorios de repaso y continuación")
 (:account-reminders-save . "Guardar preferencias")

 ;; Subscription
 (:subscribe-title . "Precios simples")
 (:subscribe-choose-plan . "Elige tu plan")
 (:subscribe-start-today . "Empieza a aprender hoy con una prueba gratuita de 7 días")
 (:subscribe-monthly . "Mensual")
 (:subscribe-annual . "Anual")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/mes")
 (:subscribe-per-year . "/año")
 (:subscribe-monthly-desc . "600 traducciones al mes")
 (:subscribe-unlimited-flashcards . "Tarjetas ilimitadas")
 (:subscribe-grammar-explanations . "Explicaciones gramaticales")
 (:subscribe-spaced-repetition . "Repetición espaciada")
 (:subscribe-annual-desc . "¡Ahorra 20€ — dos meses gratis!")
 (:subscribe-cta . "Suscribirse")
 (:subscribe-success . "¡Suscripción exitosa!")
 (:subscribe-manage . "Gestionar suscripción")
 (:subscribe-activated . "¡Suscripción activada!")
 (:subscribe-thank-you . "Gracias por suscribirte. Tu cuenta ya está activa.")
 (:subscribe-start-learning . "Empezar a aprender")
 (:subscribe-management . "Gestión de suscripción")
 (:subscribe-active . "Suscripción activa")
 (:subscribe-status . "Estado:")
 (:subscribe-status-active . "Activa")
 (:subscribe-days-remaining . "Días restantes:")
 (:subscribe-renews-on . "Se renueva el:")
 (:subscribe-no-subscription . "Sin suscripción activa")
 (:subscribe-access-features . "Suscríbete para acceder a todas las funciones.")
 (:subscribe-view-plans . "Ver planes")
 (:subscribe-faq-title . "Preguntas frecuentes")
 (:subscribe-faq-trial-q . "¿Qué pasa después de la prueba gratuita?")
 (:subscribe-faq-trial-a . "Después de tu prueba gratuita de 7 días, se te cobrará por el plan seleccionado. Puedes cancelar en cualquier momento antes de que termine la prueba.")
 (:subscribe-faq-cancel-q . "¿Puedo cancelar en cualquier momento?")
 (:subscribe-faq-cancel-a . "¡Sí! Puedes cancelar tu suscripción en cualquier momento. Mantendrás el acceso hasta el final de tu período de facturación.")
 (:subscribe-faq-payment-q . "¿Qué métodos de pago aceptan?")
 (:subscribe-faq-payment-a . "Aceptamos todas las tarjetas de crédito y débito principales a través de nuestro socio de pagos Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Algo salió mal")
 (:error-not-found . "Página no encontrada")
 (:error-unauthorized . "Por favor inicia sesión para continuar")
 (:error-subscription-required . "Se requiere suscripción")
 (:error-text-too-long . "El texto es demasiado largo. La longitud máxima de traducción es de 120 caracteres.")
 (:error-input-too-long . "Texto demasiado largo")
 (:error-unknown-source-lang . "El idioma de origen seleccionado no es compatible.")
 (:error-unknown-target-lang . "El idioma de destino seleccionado no es compatible.")
 (:error-unknown-language . "Idioma desconocido")
 (:error-translation-unavailable . "El servicio de traducción no está disponible temporalmente. Por favor, inténtalo de nuevo en un momento.")
 (:error-translation-failed . "Traducción fallida")
 (:error-translation-retry . "No se pudo generar una traducción después de varios intentos. Por favor, intenta reformular tu texto.")
 (:error-quota-exceeded . "Límite de traducciones alcanzado")
 (:error-quota-exceeded-detail . "Has usado todas tus traducciones de este mes. Tu cuota se restablece automáticamente cada mes.")
 (:quota-warning . "Traducciones restantes: ~A")
 (:quota-low-warning . "Solo quedan ~A traducciones. Considere comprar más.")
 (:top-up-button . "Comprar más traducciones")
 (:top-up-success . "¡Recarga exitosa! Ahora tienes ~A traducciones adicionales.")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 traducciones")
 (:loading . "Cargando...")
 (:empty-state . "Nada aquí todavía")

 ;; Institutions
 (:institutions-page-title . "Hiisi para escuelas - licencias institucionales")
 (:institutions-hero-title . "Hiisi para escuelas")
 (:institutions-hero-subtitle . "Impulsa a tus estudiantes con aprendizaje de idiomas con IA")
 (:institutions-section-title . "Licencias institucionales")
 (:institutions-section-body . "Ofrecemos licencias por volumen para escuelas, universidades e instituciones de idiomas. Los estudiantes con direcciones de correo de tu dominio reciben acceso completo automáticamente.")
 (:institutions-benefit-1 . "Inscripción automática para estudiantes con correo institucional")
 (:institutions-benefit-2 . "Sin cuentas individuales que gestionar")
 (:institutions-benefit-3 . "Opciones de facturación flexibles")
 (:institutions-benefit-4 . "Soporte dedicado para docentes")
 (:institutions-request-title . "Solicitar una licencia")
 (:institutions-request-subtitle . "Completa el formulario de abajo y te responderemos en un plazo de 2 días hábiles.")
 (:institutions-field-name . "Nombre de la institución")
 (:institutions-field-name-placeholder . "Universidad de Helsinki")
 (:institutions-field-contact-name . "Nombre de contacto")
 (:institutions-field-contact-name-placeholder . "Tu nombre")
 (:institutions-field-contact-email . "Correo de contacto")
 (:institutions-field-contact-email-placeholder . "tu@universidad.edu")
 (:institutions-field-domains . "Dominios de correo")
 (:institutions-field-domains-placeholder . "universidad.edu, cs.universidad.edu")
 (:institutions-field-domains-help . "Lista separada por comas de dominios de correo de tu institución")
 (:institutions-field-notes . "Información adicional")
 (:institutions-field-notes-placeholder . "Número estimado de estudiantes, ciclo de facturación preferido, requisitos especiales...")
 (:institutions-submit . "Enviar solicitud")
 (:institutions-success-title . "Gracias - Hiisi para escuelas")
 (:institutions-success-heading . "Gracias!")
 (:institutions-success-body . "Hemos recibido tu solicitud de licencia institucional. Nuestro equipo la revisará y se pondrá en contacto contigo en un plazo de 2 días hábiles.")
 (:institutions-success-back . "Volver al inicio")

 ;; Footer
 (:footer-privacy . "Política de privacidad")
 (:footer-terms . "Términos de servicio")
 (:footer-contact . "Contacto")

 ;; Early software notice
 (:early-software-notice . "Hiisi está en desarrollo temprano. ¿Encontraste un error o tienes una sugerencia?")
 (:early-software-contact . "Contáctanos en")

 ;; Política de privacidad
 (:privacy-title . "Política de privacidad")
 (:privacy-updated . "Última actualización: enero de 2026")
 (:privacy-who-title . "Quiénes somos")
 (:privacy-who-body . "Hiisi es operado por Lambda Symbolics OÜ, una empresa registrada en Estonia. Como empresa estonia, cumplimos con el Reglamento General de Protección de Datos (GDPR) de la Unión Europea.")
 (:privacy-collect-title . "Datos que recopilamos")
 (:privacy-collect-intro . "Cuando usas Hiisi, recopilamos la siguiente información:")
 (:privacy-collect-account-key . "Información de la cuenta: ")
 (:privacy-collect-account-val . "Dirección de correo electrónico, nombre para mostrar y una contraseña almacenada con hash seguro.")
 (:privacy-collect-learning-key . "Datos de aprendizaje: ")
 (:privacy-collect-learning-val . "Tus traducciones, tarjetas guardadas e historial de repaso.")
 (:privacy-collect-usage-key . "Datos de uso: ")
 (:privacy-collect-usage-val . "Registros básicos del servidor para fines de seguridad y depuración.")
 (:privacy-use-title . "Cómo usamos tus datos")
 (:privacy-use-auth-key . "Autenticación: ")
 (:privacy-use-auth-val . "Para verificar tu identidad y proteger tu cuenta.")
 (:privacy-use-service-key . "Prestación del servicio: ")
 (:privacy-use-service-val . "Para proporcionar traducciones y gestionar tu colección de tarjetas.")
 (:privacy-use-ai-key . "Traducciones con IA: ")
 (:privacy-use-ai-val . "Tus solicitudes de traducción se envían a la API Claude de Anthropic para generar respuestas. Consulta la política de privacidad de Anthropic para saber cómo gestionan esos datos.")
 (:privacy-third-title . "Servicios de terceros")
 (:privacy-third-intro . "Usamos los siguientes servicios de terceros:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "Para traducciones impulsadas por IA.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "Para enviar correos de activación de cuenta y correos transaccionales.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Para procesar pagos de suscripción.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "Usamos solo cookies esenciales:")
 (:privacy-cookies-auth-key . "Token de autenticación: ")
 (:privacy-cookies-auth-val . "Una cookie segura, solo HTTP, para mantener tu sesión iniciada.")
 (:privacy-cookies-lang-key . "Preferencia de idioma: ")
 (:privacy-cookies-lang-val . "Para recordar tu idioma preferido de la interfaz.")
 (:privacy-retention-title . "Conservación de datos")
 (:privacy-retention-body . "Tus datos se almacenan mientras mantengas una cuenta. Cuando solicitas su eliminación, tu cuenta se programa para eliminarse en 14 días.")
 (:privacy-rights-title . "Tus derechos (GDPR)")
 (:privacy-rights-intro . "Según el GDPR, tienes derecho a:")
 (:privacy-rights-access . "Acceder a tus datos personales")
 (:privacy-rights-export . "Exportar tus datos (disponible en /app/api/export)")
 (:privacy-rights-correct . "Solicitar la corrección de datos inexactos")
 (:privacy-rights-delete . "Solicitar la eliminación de tu cuenta y tus datos")
 (:privacy-rights-object . "Oponerte al tratamiento de tus datos")
 (:privacy-rights-contact . "Para ejercer estos derechos, contáctanos en")
 (:privacy-contact-title . "Contacto")
 (:privacy-contact-intro . "Para consultas relacionadas con la privacidad:")
 (:privacy-contact-email-label . "Correo electrónico: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Estonia")

 ;; Términos de servicio
 (:terms-title . "Términos de servicio")
 (:terms-updated . "Última actualización: enero de 2026")
 (:terms-1-title . "1. Descripción del servicio")
 (:terms-1-body . "Hiisi es una aplicación de aprendizaje de idiomas que ofrece traducciones impulsadas por IA con explicaciones gramaticales y tarjetas de repetición distribuida. El servicio es operado por Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Registro de cuenta")
 (:terms-2-body . "Para usar Hiisi, debes crear una cuenta con una dirección de correo válida. Eres responsable de mantener la seguridad de las credenciales de tu cuenta.")
 (:terms-3-title . "3. Suscripción y pagos")
 (:terms-3-body . "Hiisi ofrece planes de suscripción de pago (mensual y anual). Las suscripciones se procesan mediante Polar.sh.")
 (:terms-3-list-1 . "Las suscripciones se renuevan automáticamente a menos que se cancelen antes de la fecha de renovación.")
 (:terms-3-list-2 . "Los reembolsos se proporcionan conforme a la normativa de protección al consumidor aplicable.")
 (:terms-3-list-3 . "La falta de pago implica la pérdida de acceso a funciones premium.")
 (:terms-4-title . "4. Uso aceptable")
 (:terms-4-intro . "Aceptas no:")
 (:terms-4-list-1 . "Usar el servicio para fines ilegales")
 (:terms-4-list-2 . "Intentar eludir límites de uso o medidas de seguridad")
 (:terms-4-list-3 . "Compartir las credenciales de tu cuenta con otras personas")
 (:terms-4-list-4 . "Usar herramientas automatizadas de manera que degraden el rendimiento para otras personas")
 (:terms-5-title . "5. Contenido y propiedad intelectual")
 (:terms-5-body-1 . "Las traducciones generadas por Hiisi se crean con IA y pueden no ser únicas. Puedes usar tus traducciones y tarjetas para cualquier fin personal, pero no tienes derechos exclusivos de autoría sobre contenido generado por IA.")
 (:terms-5-body-2 . "La aplicación Hiisi, su marca y su contenido original siguen siendo propiedad de Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Disponibilidad del servicio")
 (:terms-6-intro . "Hiisi se proporciona tal cual. No garantizamos:")
 (:terms-6-list-1 . "Servicio ininterrumpido o libre de errores")
 (:terms-6-list-2 . "Exactitud de las traducciones generadas por IA")
 (:terms-6-list-3 . "Disponibilidad de funciones específicas")
 (:terms-6-body . "Podemos modificar o discontinuar funciones en cualquier momento.")
 (:terms-7-title . "7. Limitación de responsabilidad")
 (:terms-7-body-1 . "En la máxima medida permitida por la ley, Lambda Symbolics OÜ no será responsable por daños indirectos, incidentales, especiales o consecuentes derivados de tu uso de Hiisi.")
 (:terms-7-body-2 . "Nuestra responsabilidad total no superará el importe que hayas pagado por el servicio durante los 12 meses anteriores a la reclamación.")
 (:terms-8-title . "8. Terminación de cuenta")
 (:terms-8-body-1 . "Podemos suspender o terminar tu cuenta si incumples estos términos. Puedes solicitar la eliminación de tu cuenta en cualquier momento desde la aplicación.")
 (:terms-8-body-2 . "Tras una solicitud de eliminación, tu cuenta se programa para eliminarse en 14 días.")
 (:terms-9-title . "9. Cambios en los términos")
 (:terms-9-body . "Podemos actualizar estos términos periódicamente. El uso continuado de Hiisi después de los cambios constituye la aceptación de los nuevos términos.")
 (:terms-10-title . "10. Ley aplicable")
 (:terms-10-body . "Estos términos se rigen por las leyes de Estonia. Cualquier disputa se resolverá en los tribunales de Estonia.")
 (:terms-contact-title . "Contacto")
 (:terms-contact-intro . "Para preguntas sobre estos términos:")
 (:terms-contact-email-label . "Correo electrónico: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Estonia")



 ;; Decks
 (:decks-title . "Mazos")
 (:decks-subtitle . "Crea mazos personalizados y compártelos con otros.")
 (:decks-create-title . "Crear mazo")
 (:decks-name-placeholder . "Nombre del mazo")
 (:decks-desc-placeholder . "Descripción")
 (:decks-create-btn . "Crear mazo")
 (:decks-your-title . "Tus mazos")
 (:decks-col-name . "Nombre")
 (:decks-col-desc . "Descripción")
 (:decks-col-updated . "Actualizado")
 (:decks-col-actions . "Acciones")
 (:decks-no-decks . "Aún no hay mazos.")
 (:decks-open-btn . "Abrir")
 (:decks-no-desc . "Sin descripción.")
 (:decks-share-title . "Enlace para compartir")
 (:decks-share-info . "Cualquiera con este enlace puede importar el mazo:")
 (:decks-share-copy . "Copiar enlace")
 (:decks-share-copied . "Copiado")
 (:decks-add-from-flashcards-title . "Añadir traducciones")
 (:decks-add-from-flashcards-info . "Elige una tarjeta para añadir su traducción a este mazo.")
 (:decks-open-flashcards . "Añadir desde tarjetas")
 (:decks-filter-from . "Idioma de origen")
 (:decks-filter-to . "Idioma de destino")
 (:decks-filter-any . "Cualquier idioma")
 (:decks-filter-include-assigned . "Incluir tarjetas que ya están en un mazo")
 (:decks-flashcards-col-from . "De")
 (:decks-flashcards-col-to . "A")
 (:decks-flashcards-add . "Añadir")
 (:decks-flashcards-added . "Añadido")
 (:decks-flashcards-in-deck . "En otro mazo")
 (:decks-flashcards-empty . "Ninguna tarjeta coincide con estos filtros.")
 (:decks-add-trans-title . "Añadir traducción")
 (:decks-trans-id-placeholder . "ID de traducción")
 (:decks-add-trans-btn . "Añadir traducción")
 (:decks-items-title . "Contenido del mazo")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Traducción")
 (:decks-col-lang . "Idioma destino")
 (:decks-no-items . "Aún no hay elementos.")
 (:decks-share-page-title . "Compartir mazo")
 (:decks-share-preview . "Vista previa e importación de este mazo.")
 (:decks-import-title . "Importar")
 (:decks-import-btn . "Importar mazo")

 ;; Flashcards management page
 (:flashcards-title . "Mis tarjetas")
 (:flashcards-subtitle . "Todas tus tarjetas guardadas en un solo lugar. Busca, organiza y gestiona.")
 (:flashcards-search-placeholder . "Buscar tarjetas...")
 (:flashcards-col-original . "Original")
 (:flashcards-col-translated . "Traducción")
 (:flashcards-col-lang . "Idiomas")
 (:flashcards-no-cards . "Aún no hay tarjetas. ¡Comienza a traducir para crear algunas!")

 ;; API errors
 (:api-error-missing-text . "Falta texto para traducir.")
 (:api-error-invalid-translation-id . "ID de traducción inválido.")
 (:api-error-translation-not-found . "La traducción que intentaste guardar ya no existe.")
 (:api-error-invalid-bookmark-id . "ID de marcador inválido")
 (:api-error-bookmark-not-found . "Marcador no encontrado")
 (:api-error-forbidden . "Prohibido")
 (:api-error-failed-delete-bookmark . "No se pudo eliminar el marcador")
 (:api-error-invalid-flashcard-id . "ID de tarjeta inválido")
 (:api-error-missing-deck-id . "Falta ID del mazo")
 (:api-error-flashcard-not-found . "Tarjeta no encontrada")
 (:api-error-deck-not-found . "Mazo no encontrado")
 (:api-error-deck-name-required . "Se requiere el nombre del mazo")
 (:api-error-session-expired . "Tu sesión de repaso ha caducado. Inicia una nueva sesión.")
 (:api-error-invalid-card-id . "ID de tarjeta inválido.")
 (:api-error-invalid-rating . "Calificación inválida.")
 (:api-error-rating-range . "La calificación debe estar entre 0 y 5.")
 (:api-error-card-not-found . "Tarjeta no encontrada.")
 (:api-error-permission-denied . "No tienes permiso para repasar esta tarjeta.")
 (:api-error-unknown-source-lang . "Idioma de origen desconocido.")
 (:api-error-unknown-target-lang . "Idioma de destino desconocido.")
 (:api-error-failed-add-to-deck . "No se pudo añadir al mazo")

 ;; API success messages
 (:api-success-added . "¡Añadido!")
 (:api-success-added-simple . "Añadido")

 ;; API stats
 (:api-stats-due . "~A pendientes")
 (:api-stats-total . "~A en total")

 ;; Time units
 (:api-time-day . "día")
 (:api-time-days . "días")
 (:api-time-day-left . "día restante")
 (:api-time-days-left . "días restantes")

 ;; Subscription status
 (:api-subscription-active . "Activa")
 (:api-subscription-inactive . "Inactiva")
 (:api-subscription-subscribe-hint . "Suscríbete para desbloquear traducciones")

 ;; Generic status
 (:status-bad-request . "Solicitud incorrecta")
 (:status-not-found . "No encontrado")
 (:status-forbidden . "Prohibido")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Aprende idiomas de forma integral")
 (:landing-hero-subheadline . "Obtén traducciones con análisis gramatical completo y construye vocabulario duradero con tarjetas de repetición espaciada.")
 (:landing-hero-trust-line . "7 días de prueba gratis con 100 traducciones. Cancela en cualquier momento.")
 (:landing-credibility-languages . "14 idiomas")
 (:landing-credibility-ai . "Análisis gramatical incluido")
 (:landing-credibility-origin . "Hecho en Estonia")
 (:landing-step-1-title . "Traduce cualquier texto")
 (:landing-step-1-desc . "Ingresa una palabra o frase. Obtén una traducción con análisis gramatical completo.")
 (:landing-step-2-title . "Guarda como tarjetas")
 (:landing-step-2-desc . "Guarda las traducciones que quieras recordar. Las tarjetas se crean automáticamente.")
 (:landing-step-3-title . "Repasa y recuerda")
 (:landing-step-3-desc . "La repetición espaciada programa repasos en el momento ideal para la memoria a largo plazo.")
 (:landing-feature-grammar-title . "Comprende la gramática, no solo las palabras")
 (:landing-feature-grammar-desc . "Cada traducción incluye un análisis gramatical detallado - formas de palabras, casos y conjugaciones explicadas en tu idioma.")
 (:landing-feature-srs-title . "Memorización respaldada por la ciencia")
 (:landing-feature-srs-desc . "El algoritmo SM-2 se adapta a tu rendimiento. Las tarjetas difíciles aparecen más a menudo. Las que dominas aparecen menos.")
 (:landing-feature-share-title . "Comparte mazos con estudiantes")
 (:landing-feature-share-desc . "Los profesores pueden crear mazos personalizados y compartirlos con un enlace. Los estudiantes importan el mazo y empiezan a repasar de inmediato.")
 (:landing-pricing-trial-note . "Incluye 7 días de prueba gratis")
 (:landing-pricing-monthly-after . "7 días gratis, luego ~A/mes")
 (:landing-pricing-annual-after . "7 días gratis, luego ~A/año")
 (:landing-faq-title . "Preguntas frecuentes")
 (:landing-faq-trial-cap-q . "¿Cuántas traducciones obtengo durante la prueba?")
 (:landing-faq-trial-cap-a . "Obtienes 100 traducciones durante tu prueba de 7 días. Después de suscribirte, obtienes 600 por mes.")
 (:landing-final-cta-title . "Empieza a aprender hoy")
 (:landing-final-cta-subtitle . "Únete a Hiisi y empieza a construir vocabulario que perdura.")

 ;; Trial status (in-app)
 (:trial-status . "Prueba gratuita")
 (:trial-days-remaining . "~A días restantes")
 (:trial-translations-used . "~A/100 traducciones usadas")
 (:trial-upgrade-prompt . "Mejora tu plan para seguir traduciendo")
 (:trial-expired . "Tu prueba gratuita ha terminado")
 (:trial-expired-detail . "Suscríbete para seguir aprendiendo con Hiisi.")
 (:trial-quota-warning . "~A traducciones de prueba restantes (~A días). Suscríbete por 600/mes.")
 (:trial-quota-exceeded . "Límite de traducciones de prueba alcanzado. Suscríbete para continuar.")
 (:error-trial-quota-exceeded . "Límite de traducciones de prueba alcanzado")
 (:error-trial-quota-detail . "Has usado las 100 traducciones de prueba. Suscríbete para seguir aprendiendo.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Crear tarjeta")
 (:custom-flashcard-edit-title . "Editar tarjeta")
 (:custom-flashcard-original . "Texto original")
 (:custom-flashcard-translated . "Traducción")
 (:custom-flashcard-lang-from . "Idioma de origen")
 (:custom-flashcard-lang-to . "Idioma de destino")
 (:custom-flashcard-note . "Nota educativa")
 (:custom-flashcard-forms . "Análisis gramatical")
 (:custom-flashcard-form-term . "Término")
 (:custom-flashcard-form-explanation . "Explicación")
 (:custom-flashcard-add-form . "Agregar término gramatical")
 (:custom-flashcard-remove-form . "Eliminar")
 (:custom-flashcard-ai-fill . "Rellenar con IA")
 (:custom-flashcard-ai-fill-all . "Rellenar todo con IA")
 (:custom-flashcard-ai-fill-translation . "Traducir con IA")
 (:custom-flashcard-ai-fill-breakdown . "Generar análisis")
 (:custom-flashcard-ai-fill-note . "Generar nota")
 (:custom-flashcard-create-btn . "Crear tarjeta")
 (:custom-flashcard-update-btn . "Guardar cambios")
 (:custom-flashcard-delete-btn . "Eliminar tarjeta")
 (:custom-flashcard-delete-confirm . "¿Estás seguro de que quieres eliminar esta tarjeta?")
 (:custom-flashcard-created . "Tarjeta creada exitosamente")
 (:custom-flashcard-updated . "Tarjeta actualizada exitosamente")
 (:custom-flashcard-deleted . "Tarjeta eliminada exitosamente")
 (:custom-flashcard-add-to-deck . "Agregar al mazo")
 (:custom-flashcard-not-found . "Tarjeta no encontrada")
 (:custom-flashcard-not-owner . "Solo puedes editar tarjetas que hayas creado")
 (:custom-flashcard-ai-generating . "Generando con IA...")
 (:custom-flashcard-badge . "Personalizada")

 ;; Reporte de problemas
 (:issues-open-button . "Reportar un problema")
 (:issues-modal-title . "Reportar un problema")
 (:issues-modal-subtitle . "Describe qué salió mal. Incluiremos automáticamente la página actual.")
 (:issues-message-label . "¿Qué ocurrió?")
 (:issues-message-placeholder . "Incluye pasos para reproducir, el comportamiento esperado y lo que ocurrió en su lugar.")
 (:issues-submit . "Enviar reporte")
 (:issues-cancel . "Cancelar")
 (:issues-success . "Gracias. Tu reporte de problema fue enviado.")
 (:issues-error-required . "Describe el problema antes de enviarlo.")
 (:issues-error-too-long . "El texto del reporte es demasiado largo. Mantenlo por debajo de 4000 caracteres.")
 (:issues-error-rate-limit . "Demasiados reportes desde este origen. Espera e inténtalo de nuevo más tarde.")
 (:issues-error-generic . "No se pudo enviar el reporte de problema. Inténtalo de nuevo.")

)
