;;; Estonian translations

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Eesti")
 (:lang-flag . "🇪🇪")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Valige oma keel")
 (:lang-modal-subtitle . "Valige liidese eelistatud keel:")

 ;; Navigation
 (:nav-translate . "Tõlgi")
 (:nav-review . "Kordamine")
 (:nav-dashboard . "Ülevaade")
 (:nav-logout . "Logi välja")
 (:nav-home . "Avaleht")
 (:nav-pricing . "Hinnad")
 (:nav-export-data . "Ekspordi andmed")

 ;; App title and branding
 (:app-title . "Hiisi")
 (:app-tagline . "Õpi keeli tõlkimise kaudu")

 ;; Landing page
 (:landing-hero-title . "Omanda ükskõik milline keel")
 (:landing-hero-subtitle . "Tõlgi mida iganes. Loo automaatselt mälukaarte, mis õpetavad sulle, miks see nii toimib.")
 (:landing-cta . "Alusta õppimist")
 (:landing-learn-more . "Loe lähemalt")
 (:landing-how-it-works . "Kuidas see töötab")
 (:landing-feature-1-title . "Automaatsed mälukaardid")
 (:landing-feature-1-desc . "Iga tõlge loob automaatselt mälukaardid koos grammatika selgitustega. Pole vaja käsitsi kaarte luua.")
 (:landing-feature-2-title . "Hajutatud kordamine")
 (:landing-feature-2-desc . "SM-2 algoritm ajastab kordamised optimaalsete intervallidega. Õpi tõhusalt, jäta püsivalt meelde.")
 (:landing-feature-3-title . "Grammatika õpetus")
 (:landing-feature-3-desc . "Iga tõlge selgitab grammatikat, sõnatüvesid ja lauseehitust. Mõista põhjust, mitte ainult tulemust.")
 (:landing-free-trial . "7-päevane tasuta prooviperiood. Krediitkaarti pole vaja.")
 (:landing-start-trial . "Alusta tasuta prooviperioodi")
 (:landing-best-value . "Parim pakkumine")
 (:landing-cta-title . "Valmis õppima keeli grammatika, mitte päheõppimise kaudu?")
 (:landing-cta-subtitle . "Iga tõlge muutub õppimisvõimaluseks. Iga mälukaart õpetab sulle põhjust.")
 (:landing-signup-free . "Registreeru tasuta")

 ;; Auth pages
 (:auth-register . "Registreeru")
 (:auth-login . "Logi sisse")
 (:auth-logout . "Logi välja")
 (:auth-email . "E-post")
 (:auth-password . "Parool")
 (:auth-password-again . "Kinnita parool")
 (:auth-display-name . "Kuvatav nimi")
 (:auth-register-title . "Registreeru Hiisi kasutajaks")
 (:auth-register-subtitle . "Loo uus konto")
 (:auth-login-title . "Logi Hiisi sisse")
 (:auth-login-subtitle . "Sisesta oma andmed")
 (:auth-forgot-password . "Unustasid parooli?")
 (:auth-no-account . "Pole veel kontot?")
 (:auth-have-account . "On juba konto?")
 (:auth-google . "Google")
 (:auth-account-created . "Konto loodud!")
 (:auth-check-email . "Kontrolli oma e-posti aktiveerimislingi saamiseks.")
 (:auth-redirect-login . "Suunan sisselogimisele")
 (:auth-seconds . "sekundi pärast...")
 (:auth-go-now . "Mine kohe")
 (:auth-not-activated . "Konto pole aktiveeritud")
 (:auth-activate-title . "Aktiveeri oma konto!")
 (:auth-activated . "Konto aktiveeritud!")
 (:auth-activated-message . "Sinu konto on aktiveeritud. Võid nüüd Hiisi kasutada.")
 (:auth-redirecting . "Suunan ümber")
 (:auth-go-to-app . "Mine rakendusse")
 (:auth-resend-title . "Saada aktiveerimismeil uuesti")
 (:auth-resend-subtitle . "Sisesta oma e-post, et saada uus aktiveerimislink.")
 (:auth-resend-button . "Saada aktiveerimismeil uuesti")
 (:auth-resend-success . "Aktiveerimismeil saadetud!")
 (:auth-resend-success-detail . "Vaata oma postkasti uue aktiveerimislingi saamiseks.")
 (:auth-resend-rate-limited . "Palun oota mõni minut enne järgmise aktiveerimismeili taotlemist.")
 (:auth-resend-cooldown . "Saad uue meili taotleda ~a sekundi pärast.")
 (:auth-back-to-login . "Tagasi sisselogimisele")
 (:auth-forgot-password-title . "Unustasin parooli")
 (:auth-forgot-password-subtitle . "Sisesta oma e-post ja saadame sulle lingi parooli lähtestamiseks.")
 (:auth-send-reset-link . "Saada lähtestamise link")
 (:auth-reset-email-sent . "Link saadetud!")
 (:auth-reset-email-sent-detail . "Kui selle e-postiga konto eksisteerib, saad peagi parooli lähtestamise lingi.")
 (:auth-reset-rate-limited . "Palun oota mõni minut enne järgmise parooli lähtestamise taotlemist.")
 (:auth-reset-invalid-token . "See parooli lähtestamise link on kehtetu või aegunud.")
 (:auth-reset-password-title . "Lähtesta parool")
 (:auth-reset-password-subtitle . "Sisesta oma uus parool allpool.")
 (:auth-new-password . "Uus parool")
 (:auth-confirm-new-password . "Kinnita uus parool")
 (:auth-reset-password . "Lähtesta parool")
 (:auth-password-changed . "Parool muudetud!")
 (:auth-password-changed-detail . "Sinu parool on edukalt muudetud. Võid nüüd uue parooliga sisse logida.")
 (:auth-change-password-title . "Muuda parooli")
 (:auth-change-password-subtitle . "Uuenda oma konto parooli.")
 (:auth-current-password . "Praegune parool")
 (:auth-change-password . "Muuda parooli")
 (:auth-back-to-app . "Tagasi rakendusse")
 (:auth-password-updated . "Parool uuendatud!")
 (:auth-password-updated-detail . "Sinu parool on edukalt uuendatud.")

 ;; Translation page
 (:translate-title . "Tõlgi")
 (:translate-input-label . "Tõlgitav tekst")
 (:translate-input-placeholder . "Sisesta tõlgitav tekst...")
 (:translate-from . "Allikast:")
 (:translate-to . "Sihtkeelde:")
 (:translate-submit . "Tõlgi")
 (:translate-save . "Salvesta mälukaartidesse")
 (:translate-saved . "Salvestatud!")
 (:translate-like . "Meeldib")
 (:translate-dislike . "Ei meeldi")
 (:translate-char-limit . "tähemärki alles")
 (:translate-auto-detect . "Suvaline (automaattuvastus)")
 (:translate-empty-state . "Sisesta tekst ülal ja klõpsa Tõlgi, et näha tulemust koos grammatika analüüsiga")
 (:translate-like-tooltip . "Hea tõlge")
 (:translate-dislike-tooltip . "Halb tõlge - taotle uut")
 (:translate-dislike-confirm . "See genereerib uue tõlke. Jätkata?")
 (:translate-liked . "Meeldib!")

 ;; Flashcard review
 (:review-title . "Kordamine")
 (:review-session-title . "Kordamisseanss")
 (:review-session-subtitle . "Harjuta oma salvestatud mälukaarte")
 (:review-start . "Alusta kordamist")
 (:review-no-cards . "Pole kaarte kordamiseks")
 (:review-no-cards-desc . "Sul pole praegu ühtegi mälukaarti, mis vajaks kordamist.")
 (:review-no-cards-hint . "Tõlgi teksti ja klõpsa \"Salvesta mälukaartidesse\", et oma pakki üles ehitada!")
 (:review-start-translating . "Alusta tõlkimist")
 (:review-show-answer . "Näita vastust")
 (:review-click-reveal . "Klõpsa vastuse nägemiseks")
 (:review-grammar-breakdown . "Grammatika analüüs")
 (:review-how-well . "Kui hästi mäletasid?")
 (:review-again . "Uuesti")
 (:review-hard . "Raske")
 (:review-good . "Hea")
 (:review-easy . "Kerge")
 (:review-progress . "Kaart ~a/~a")
 (:review-complete . "Seanss lõpetatud!")
 (:review-complete-msg . "Kordasid ~a kaarti")
 (:review-correct . "Õige")
 (:review-accuracy . "Täpsus")
 (:review-again-btn . "Korda uuesti")
 (:review-translate-more . "Tõlgi rohkem")
 (:review-streak . "päevane seeria")

 ;; Dashboard
 (:dashboard-title . "Ülevaade")
 (:dashboard-cards-due . "Ootel kaardid")
 (:dashboard-total-cards . "Kaarte kokku")
 (:dashboard-subscription . "Tellimus")
 (:dashboard-subscribed-until . "Tellimus kehtib kuni")
 (:dashboard-not-subscribed . "Tellimus puudub")
 (:dashboard-recent . "Viimased tõlked")
 (:dashboard-no-translations . "Tõlkeid veel pole")
 (:dashboard-streak . "Kordamise seeria")
 (:dashboard-days . "päeva")
 (:dashboard-quick-actions . "Kiirtoimingud")
 (:dashboard-getting-started . "Alustamine")
 (:dashboard-tip-1 . "Tõlgi teksti, mida soovid õppida")
 (:dashboard-tip-2 . "Klõpsa \"Salvesta mälukaartidesse\" tõlgetel, mida soovid meelde jätta")
 (:dashboard-tip-3 . "Korda oma mälukaarte regulaarselt - hajutatud kordamine aitab pikaajalise mäluga")
 (:dashboard-tip-4 . "Hinda ausalt - see aitab algoritmil sinu kordamisi optimaalselt ajastada")

 ;; Subscription
 (:subscribe-title . "Lihtne hinnastus")
 (:subscribe-choose-plan . "Vali oma pakett")
 (:subscribe-start-today . "Alusta õppimist juba täna 7-päevase tasuta prooviperioodiga")
 (:subscribe-monthly . "Kuutellimus")
 (:subscribe-annual . "Aastatellimus")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/kuus")
 (:subscribe-per-year . "/aastas")
 (:subscribe-monthly-desc . "600 tõlget kuus")
 (:subscribe-unlimited-flashcards . "Piiramatu arv mälukaarte")
 (:subscribe-grammar-explanations . "Grammatika selgitused")
 (:subscribe-spaced-repetition . "Hajutatud kordamine")
 (:subscribe-annual-desc . "Säästa €20 — kaks kuud tasuta!")
 (:subscribe-cta . "Telli")
 (:subscribe-success . "Tellimus õnnestus!")
 (:subscribe-manage . "Halda tellimust")
 (:subscribe-activated . "Tellimus aktiveeritud!")
 (:subscribe-thank-you . "Täname tellimuse eest. Sinu konto on nüüd aktiivne.")
 (:subscribe-start-learning . "Alusta õppimist")
 (:subscribe-management . "Tellimuse haldamine")
 (:subscribe-active . "Aktiivne tellimus")
 (:subscribe-status . "Staatus:")
 (:subscribe-status-active . "Aktiivne")
 (:subscribe-days-remaining . "Päevi jäänud:")
 (:subscribe-renews-on . "Uueneb:")
 (:subscribe-no-subscription . "Aktiivne tellimus puudub")
 (:subscribe-access-features . "Telli, et pääseda ligi kõikidele funktsioonidele.")
 (:subscribe-view-plans . "Vaata pakette")
 (:subscribe-faq-title . "Korduma kippuvad küsimused")
 (:subscribe-faq-trial-q . "Mis juhtub pärast tasuta prooviperioodi?")
 (:subscribe-faq-trial-a . "Pärast 7-päevast tasuta prooviperioodi võetakse sinu valitud paketi eest tasu. Võid igal ajal enne prooviperioodi lõppu tühistada.")
 (:subscribe-faq-cancel-q . "Kas saan igal ajal tühistada?")
 (:subscribe-faq-cancel-a . "Jah! Võid oma tellimuse igal ajal tühistada. Ligipääs säilib arveldusperioodi lõpuni.")
 (:subscribe-faq-payment-q . "Milliseid makseviise aktsepteerite?")
 (:subscribe-faq-payment-a . "Aktsepteerime kõiki peamisi krediit- ja deebetkaarte meie maksepartneri Polar.sh kaudu.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Midagi läks valesti")
 (:error-not-found . "Lehte ei leitud")
 (:error-unauthorized . "Jätkamiseks logi palun sisse")
 (:error-subscription-required . "Tellimus nõutud")
 (:error-text-too-long . "Tekst on liiga pikk. Maksimaalne tõlke pikkus on 120 tähemärki.")
 (:error-input-too-long . "Sisend liiga pikk")
 (:error-unknown-source-lang . "Valitud lähtekeel ei ole toetatud.")
 (:error-unknown-target-lang . "Valitud sihtkeel ei ole toetatud.")
 (:error-unknown-language . "Tundmatu keel")
 (:error-translation-unavailable . "Tõlketeenus on ajutiselt kättesaamatu. Palun proovi hetke pärast uuesti.")
 (:error-translation-failed . "Tõlkimine ebaõnnestus")
 (:error-translation-retry . "Tõlget ei õnnestunud mitme katse järel genereerida. Palun proovi oma teksti ümber sõnastada.")
 (:error-quota-exceeded . "Tõlkelimiit täis")
 (:error-quota-exceeded-detail . "Oled kasutanud kõik oma selle kuu tõlked. Sinu kvoot lähtestub automaatselt iga kuu.")
 (:loading . "Laadimine...")
 (:empty-state . "Siin pole veel midagi")

 ;; Footer
 (:footer-privacy . "Privaatsuspoliitika")
 (:footer-terms . "Kasutustingimused")
 (:footer-contact . "Kontakt")

 ;; Early software notice
 (:early-software-notice . "Hiisi on varajases arendusfaasis. Leidsid vea või on sul ettepanek?")
 (:early-software-contact . "Võta meiega ühendust aadressil")

 ;; Privacy Policy
 (:privacy-title . "Privacy Policy")
 (:privacy-updated . "Last updated: January 2026")
 (:privacy-who-title . "Who We Are")
 (:privacy-who-body . "Hiisi is operated by Lambda Symbolics OÜ, a company registered in Estonia. As an Estonian company, we comply with the European Union's General Data Protection Regulation (GDPR).")
 (:privacy-collect-title . "Data We Collect")
 (:privacy-collect-intro . "We collect the following information when you use Hiisi:")
 (:privacy-collect-account-key . "Account information: ")
 (:privacy-collect-account-val . "Email address, display name, and a securely hashed password.")
 (:privacy-collect-learning-key . "Learning data: ")
 (:privacy-collect-learning-val . "Your translations, saved flashcards, and review history.")
 (:privacy-collect-usage-key . "Usage data: ")
 (:privacy-collect-usage-val . "Basic server logs for security and debugging purposes.")
 (:privacy-use-title . "How We Use Your Data")
 (:privacy-use-auth-key . "Authentication: ")
 (:privacy-use-auth-val . "To verify your identity and secure your account.")
 (:privacy-use-service-key . "Service delivery: ")
 (:privacy-use-service-val . "To provide translations and manage your flashcard collection.")
 (:privacy-use-ai-key . "AI translations: ")
 (:privacy-use-ai-val . "Your translation requests are sent to Anthropic's Claude API to generate responses. See Anthropic's privacy policy for how they handle this data.")
 (:privacy-third-title . "Third-Party Services")
 (:privacy-third-intro . "We use the following third-party services:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "For AI-powered translations.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "For sending account activation and transactional emails.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "For subscription payment processing.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "We use only essential cookies:")
 (:privacy-cookies-auth-key . "Authentication token: ")
 (:privacy-cookies-auth-val . "A secure, HTTP-only cookie to keep you logged in.")
 (:privacy-cookies-lang-key . "Language preference: ")
 (:privacy-cookies-lang-val . "To remember your preferred UI language.")
 (:privacy-retention-title . "Data Retention")
 (:privacy-retention-body . "Your data is stored as long as you maintain an account. When you request deletion, your account is scheduled for deletion in 14 days.")
 (:privacy-rights-title . "Your Rights (GDPR)")
 (:privacy-rights-intro . "Under GDPR, you have the right to:")
 (:privacy-rights-access . "Access your personal data")
 (:privacy-rights-export . "Export your data (available at /app/api/export)")
 (:privacy-rights-correct . "Request correction of inaccurate data")
 (:privacy-rights-delete . "Request deletion of your account and data")
 (:privacy-rights-object . "Object to processing of your data")
 (:privacy-rights-contact . "To exercise these rights, contact us at")
 (:privacy-contact-title . "Contact")
 (:privacy-contact-intro . "For privacy-related inquiries:")
 (:privacy-contact-email-label . "Email: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Estonia")

 ;; Terms of Service
 (:terms-title . "Terms of Service")
 (:terms-updated . "Last updated: January 2026")
 (:terms-1-title . "1. Service Description")
 (:terms-1-body . "Hiisi is a language learning application that provides AI-powered translations with grammatical explanations and spaced repetition flashcards. The service is operated by Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Account Registration")
 (:terms-2-body . "To use Hiisi, you must create an account with a valid email address. You are responsible for maintaining the security of your account credentials.")
 (:terms-3-title . "3. Subscription and Payments")
 (:terms-3-body . "Hiisi offers paid subscription plans (monthly and annual). Subscriptions are processed through Polar.sh.")
 (:terms-3-list-1 . "Subscriptions auto-renew unless cancelled before the renewal date.")
 (:terms-3-list-2 . "Refunds are provided in accordance with applicable consumer protection laws.")
 (:terms-3-list-3 . "Non-payment results in loss of access to premium features.")
 (:terms-4-title . "4. Acceptable Use")
 (:terms-4-intro . "You agree not to:")
 (:terms-4-list-1 . "Use the service for any illegal purpose")
 (:terms-4-list-2 . "Attempt to circumvent usage limits or security measures")
 (:terms-4-list-3 . "Share your account credentials with others")
 (:terms-4-list-4 . "Use automated tools to access the service in a way that degrades performance for others")
 (:terms-5-title . "5. Content and Intellectual Property")
 (:terms-5-body-1 . "Translations generated by Hiisi are created using AI and may not be unique. You may use your translations and flashcards for any personal purpose, but you do not hold exclusive authorship rights over AI-generated content.")
 (:terms-5-body-2 . "The Hiisi application, branding, and original content remain the property of Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Service Availability")
 (:terms-6-intro . "Hiisi is provided on an \"as-is\" basis. We do not guarantee:")
 (:terms-6-list-1 . "Uninterrupted or error-free service")
 (:terms-6-list-2 . "Accuracy of AI-generated translations")
 (:terms-6-list-3 . "Availability of specific features")
 (:terms-6-body . "We may modify or discontinue features at any time.")
 (:terms-7-title . "7. Limitation of Liability")
 (:terms-7-body-1 . "To the maximum extent permitted by law, Lambda Symbolics OÜ shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of Hiisi.")
 (:terms-7-body-2 . "Our total liability shall not exceed the amount you paid for the service in the 12 months preceding the claim.")
 (:terms-8-title . "8. Account Termination")
 (:terms-8-body-1 . "We may suspend or terminate your account if you violate these terms. You may request account deletion at any time through the application.")
 (:terms-8-body-2 . "Upon deletion request, your account is scheduled for deletion in 14 days.")
 (:terms-9-title . "9. Changes to Terms")
 (:terms-9-body . "We may update these terms from time to time. Continued use of Hiisi after changes constitutes acceptance of the new terms.")
 (:terms-10-title . "10. Governing Law")
 (:terms-10-body . "These terms are governed by the laws of Estonia. Any disputes shall be resolved in the courts of Estonia.")
 (:terms-contact-title . "Contact")
 (:terms-contact-intro . "For questions about these terms:")
 (:terms-contact-email-label . "Email: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Estonia")



 ;; Decks
 (:decks-title . "Decks")
 (:decks-subtitle . "Create custom decks and share them with others.")
 (:decks-create-title . "Create Deck")
 (:decks-name-placeholder . "Deck name")
 (:decks-desc-placeholder . "Description")
 (:decks-create-btn . "Create deck")
 (:decks-your-title . "Your Decks")
 (:decks-col-name . "Name")
 (:decks-col-desc . "Description")
 (:decks-col-updated . "Updated")
 (:decks-col-actions . "Actions")
 (:decks-no-decks . "No decks yet.")
 (:decks-open-btn . "Open")
 (:decks-no-desc . "No description.")
 (:decks-share-title . "Share Link")
 (:decks-share-info . "Anyone with this link can import the deck:")
 (:decks-add-trans-title . "Add Translation")
 (:decks-trans-id-placeholder . "Translation ID")
 (:decks-add-trans-btn . "Add translation")
 (:decks-items-title . "Deck Items")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Translated")
 (:decks-col-lang . "Lang To")
 (:decks-no-items . "No items yet.")
 (:decks-share-page-title . "Share Deck")
 (:decks-share-preview . "Preview and import this deck.")
 (:decks-import-title . "Import")
 (:decks-import-btn . "Import deck")

)
