;;; Estonian translations

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Eesti")
 (:lang-flag . "🇪🇪")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Valige oma keel")
 (:lang-modal-subtitle . "Valige liidese eelistatud keel:")

 ;; Navigation
 (:nav-translate . "Tõlgi")
 (:nav-review . "Kordamine")
 (:nav-flashcards . "Minu kaardid")
 (:nav-dashboard . "Ülevaade")
 (:nav-decks . "Kaardipakid")
 (:nav-logout . "Logi välja")
 (:nav-home . "Avaleht")
 (:nav-pricing . "Hinnad")
 (:nav-export-data . "Ekspordi andmed")

 ;; App title and branding
 (:app-title . "Hiisi - Keeleõpe")

 ;; Landing page
 (:landing-learn-more . "Loe lähemalt")
 (:landing-how-it-works . "Kuidas see töötab")
 (:landing-start-trial . "Alusta tasuta prooviperioodi")
 (:landing-best-value . "Parim pakkumine")

 ;; Auth pages
 (:auth-register . "Registreeru")
 (:auth-login . "Logi sisse")
 (:auth-email . "E-post")
 (:auth-password . "Parool")
 (:auth-password-again . "Kinnita parool")
 (:auth-display-name . "Kuvatav nimi")
 (:auth-register-title . "Registreeru Hiisi kasutajaks")
 (:auth-register-subtitle . "Loo uus konto")
 (:auth-login-title . "Logi Hiisi sisse")
 (:auth-login-subtitle . "Sisesta oma andmed")
 (:auth-login-invalid-credentials . "Vigane e-post või parool.")
 (:auth-login-rate-limited . "Liiga palju sisselogimiskatseid. Oota paar minutit ja proovi uuesti.")
 (:auth-forgot-password . "Unustasid parooli?")
 (:auth-no-account . "Pole veel kontot?")
 (:auth-have-account . "On juba konto?")
 (:auth-google . "Google")
 (:auth-account-created . "Konto loodud!")
 (:auth-check-email . "Kontrolli oma e-posti aktiveerimislingi saamiseks.")
 (:auth-redirect-login . "Suunan sisselogimisele")
 (:auth-seconds . "sekundi pärast...")
 (:auth-go-now . "Mine kohe")
 (:auth-not-activated . "Konto pole aktiveeritud")
 (:auth-activate-title . "Aktiveeri oma konto!")
 (:auth-activated . "Konto aktiveeritud!")
 (:auth-activated-message . "Sinu konto on aktiveeritud. Võid nüüd Hiisi kasutada.")
 (:auth-redirecting . "Suunan ümber")
 (:auth-go-to-app . "Mine rakendusse")
 (:auth-resend-title . "Saada aktiveerimismeil uuesti")
 (:auth-resend-subtitle . "Sisesta oma e-post, et saada uus aktiveerimislink.")
 (:auth-resend-button . "Saada aktiveerimismeil uuesti")
 (:auth-resend-success . "Aktiveerimismeil saadetud!")
 (:auth-resend-success-detail . "Vaata oma postkasti uue aktiveerimislingi saamiseks.")
 (:auth-resend-rate-limited . "Palun oota mõni minut enne järgmise aktiveerimismeili taotlemist.")
 (:auth-resend-cooldown . "Saad uue meili taotleda ~a sekundi pärast.")
 (:auth-back-to-login . "Tagasi sisselogimisele")
 (:auth-forgot-password-title . "Unustasin parooli")
 (:auth-forgot-password-subtitle . "Sisesta oma e-post ja saadame sulle lingi parooli lähtestamiseks.")
 (:auth-send-reset-link . "Saada lähtestamise link")
 (:auth-reset-email-sent . "Link saadetud!")
 (:auth-reset-email-sent-detail . "Kui selle e-postiga konto eksisteerib, saad peagi parooli lähtestamise lingi.")
 (:auth-reset-rate-limited . "Palun oota mõni minut enne järgmise parooli lähtestamise taotlemist.")
 (:auth-reset-invalid-token . "See parooli lähtestamise link on kehtetu või aegunud.")
 (:auth-reset-password-title . "Lähtesta parool")
 (:auth-reset-password-subtitle . "Sisesta oma uus parool allpool.")
 (:auth-new-password . "Uus parool")
 (:auth-confirm-new-password . "Kinnita uus parool")
 (:auth-reset-password . "Lähtesta parool")
 (:auth-password-changed . "Parool muudetud!")
 (:auth-password-changed-detail . "Sinu parool on edukalt muudetud. Võid nüüd uue parooliga sisse logida.")
 (:auth-change-password-title . "Muuda parooli")
 (:auth-change-password-subtitle . "Uuenda oma konto parooli.")
 (:auth-current-password . "Praegune parool")
 (:auth-change-password . "Muuda parooli")
 (:auth-back-to-app . "Tagasi rakendusse")
 (:auth-password-updated . "Parool uuendatud!")
 (:auth-password-updated-detail . "Sinu parool on edukalt uuendatud.")

 ;; Translation page
 (:translate-title . "Tõlgi")
 (:translate-input-label . "Tõlgitav tekst")
 (:translate-input-placeholder . "Sisesta tõlgitav tekst...")
 (:translate-from . "Lähtkeel:")
 (:translate-to . "Sihtkeel:")
 (:translate-submit . "Tõlgi")
 (:translate-auto-detect . "Suvaline (automaattuvastus)")
 (:translate-empty-state . "Sisesta tekst ülal ja klõpsa Tõlgi, et näha tulemust koos grammatika analüüsiga")
 (:translate-select-deck-placeholder . "Vali kaardipakk (valikuline)")
 (:translate-new-deck . "Uus kaardipakk")
 (:translate-add-to-deck . "Lisa kaardipakki")
 (:translate-bookmark . "Salvesta")
 (:translate-bookmarked . "Salvestatud")
 (:translate-retry . "Proovi uuesti")
 (:translate-like-tooltip . "Hea tõlge")
 (:translate-dislike-tooltip . "Halb tõlge - taotle uut")
 (:translate-dislike-confirm . "See genereerib uue tõlke. Jätkata?")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Siht")
 (:translate-deck-create-title . "Loo uus kaardipakk")
 (:translate-deck-name-label . "Kaardipaki nimi")
 (:translate-deck-name-placeholder . "nt Soome keele alused")
 (:translate-deck-description-label . "Kirjeldus (valikuline)")
 (:translate-deck-cancel . "Tühista")
 (:translate-deck-create . "Loo")
 (:translate-rate-label . "Hinda tõlget")
 (:flashcards-delete-confirm . "Kas oled kindel, et soovid selle kaardi kustutada?")
 (:flashcards-deck-search-placeholder . "Otsi kaardipakke...")
 (:flashcards-no-decks . "Kaardipakke veel pole. Loo üks kõigepealt!")
 (:flashcards-deck-cancel . "Tühista")
 (:flashcards-recollection-tooltip . "Meeldejäävus: ~A")
 (:flashcards-recollection-poor . "Nõrk")
 (:flashcards-recollection-fair . "Rahuldav")
 (:flashcards-recollection-normal . "Tavaline")
 (:flashcards-recollection-strong . "Tugev")
 (:flashcards-recollection-very-strong . "Väga tugev")

 ;; Flashcard review
 (:review-title . "Kordamine")
 (:review-session-title . "Kordamisseanss")
 (:review-session-subtitle . "Harjuta oma salvestatud mälukaarte")
 (:review-selector-title . "Vali, mida korrata")
 (:review-selector-subtitle . "Vali pakk või keelepaar, millele selles kordamisseansis keskenduda.")
 (:review-by-deck . "Korda paki järgi")
 (:review-by-language-pair . "Korda keelepaari järgi")
 (:review-all-cards . "Korda kõiki kaarte")

 (:review-no-cards . "Pole kaarte kordamiseks")
 (:review-no-cards-desc . "Sul pole praegu ühtegi mälukaarti, mis vajaks kordamist.")
 (:review-no-cards-hint . "Tõlgi teksti ja klõpsa \"Salvesta mälukaartidesse\", et oma pakki üles ehitada!")
 (:review-start-translating . "Alusta tõlkimist")
 (:review-click-reveal . "Klõpsa vastuse nägemiseks")
 (:review-grammar-breakdown . "Grammatika analüüs")
 (:review-how-well . "Kas tuli meelde?")
 (:review-again . "Ei")
 (:review-hard . "Vaevalt")
 (:review-good . "Jah")
 (:review-easy . "Kergesti")
 (:review-progress . "Kaart ~a/~a")
 (:review-complete . "Seanss lõpetatud!")
 (:review-complete-msg . "Kordasid ~a kaarti")
 (:review-again-btn . "Korda uuesti")
 (:review-translate-more . "Tõlgi rohkem")
 (:review-streak . "päevane seeria")

 ;; Dashboard
 (:dashboard-title . "Ülevaade")
 (:dashboard-cards-due . "Ootel kaardid")
 (:dashboard-total-cards . "Kaarte kokku")
 (:dashboard-subscription . "Tellimus")
 (:dashboard-subscribed-until . "Tellimus kehtib kuni")
 (:dashboard-not-subscribed . "Tellimus puudub")
 (:dashboard-recent . "Viimased tõlked")
 (:dashboard-no-translations . "Tõlkeid veel pole")
 (:dashboard-streak . "Kordamise seeria")
 (:dashboard-days . "päeva")
 (:dashboard-all-caught-up . "Kõik on üle vaadatud!")
 (:dashboard-all-caught-up-hint . "Tõlgi veel, et oma kogu kasvatada.")
 (:dashboard-quick-actions . "Kiirtoimingud")
 (:dashboard-getting-started . "Alustamine")
 (:dashboard-tip-1 . "Tõlgi teksti, mida soovid õppida")
 (:dashboard-tip-2 . "Klõpsa \"Salvesta mälukaartidesse\" tõlgetel, mida soovid meelde jätta")
 (:dashboard-tip-3 . "Korda oma mälukaarte regulaarselt - hajutatud kordamine aitab pikaajalise mäluga")
 (:dashboard-tip-4 . "Hinda ausalt - see aitab algoritmil sinu kordamisi optimaalselt ajastada")

 ;; Account
 (:account-title . "Konto")
 (:account-subtitle . "Halda oma konto seadeid ja kustutamise ajakava.")
 (:account-deletion-title . "Konto kustutamine")
 (:account-deletion-scheduled . "Sinu konto on planeeritud kustutamiseks kuupäeval ~A.")
 (:account-deletion-cancel-hint . "Saad enne seda kuupäeva tühistada ja konto alles jätta.")
 (:account-deletion-cancel . "Tühista kustutamine")
 (:account-deletion-request . "Kontot saad kustutada igal ajal. Kustutamine on planeeritud 14 päeva pärast kinnitamist. Kui pärast kustutamist meelt muudad, võta ühendust toega.")
 (:account-deletion-confirm . "Kas planeerida konto kustutamine 14 päeva pärast tänast?")
 (:account-deletion-schedule . "Planeeri kustutamine")
 (:account-reminders-title . "E-posti meeldetuletused")
 (:account-reminders-subtitle . "Halda selle konto kordamise ja jätkamise meeldetuletusi.")
 (:account-reminders-opt-out . "Lülita kordamise ja jätkamise meeldetuletused välja")
 (:account-reminders-save . "Salvesta eelistused")

 ;; Subscription
 (:subscribe-title . "Lihtne hinnastus")
 (:subscribe-choose-plan . "Vali oma pakett")
 (:subscribe-start-today . "Alusta õppimist juba täna 7-päevase tasuta prooviperioodiga")
 (:subscribe-monthly . "Kuutellimus")
 (:subscribe-annual . "Aastatellimus")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/kuus")
 (:subscribe-per-year . "/aastas")
 (:subscribe-monthly-desc . "600 tõlget kuus")
 (:subscribe-unlimited-flashcards . "Piiramatu arv mälukaarte")
 (:subscribe-grammar-explanations . "Grammatika selgitused")
 (:subscribe-spaced-repetition . "Hajutatud kordamine")
 (:subscribe-annual-desc . "Säästa €20 — kaks kuud tasuta!")
 (:subscribe-manage . "Halda tellimust")
 (:subscribe-activated . "Tellimus aktiveeritud!")
 (:subscribe-thank-you . "Täname tellimuse eest. Sinu konto on nüüd aktiivne.")
 (:subscribe-start-learning . "Alusta õppimist")
 (:subscribe-management . "Tellimuse haldamine")
 (:subscribe-active . "Aktiivne tellimus")
 (:subscribe-status . "Staatus:")
 (:subscribe-status-active . "Aktiivne")
 (:subscribe-days-remaining . "Päevi jäänud:")
 (:subscribe-renews-on . "Uueneb:")
 (:subscribe-no-subscription . "Aktiivne tellimus puudub")
 (:subscribe-access-features . "Telli, et pääseda ligi kõikidele funktsioonidele.")
 (:subscribe-view-plans . "Vaata pakette")
 (:subscribe-faq-title . "Korduma kippuvad küsimused")
 (:subscribe-faq-trial-q . "Mis juhtub pärast tasuta prooviperioodi?")
 (:subscribe-faq-trial-a . "Pärast 7-päevast tasuta prooviperioodi võetakse sinu valitud paketi eest tasu. Võid igal ajal enne prooviperioodi lõppu tühistada.")
 (:subscribe-faq-cancel-q . "Kas saan igal ajal tühistada?")
 (:subscribe-faq-cancel-a . "Jah! Võid oma tellimuse igal ajal tühistada. Ligipääs säilib arveldusperioodi lõpuni.")
 (:subscribe-faq-payment-q . "Milliseid makseviise aktsepteerite?")
 (:subscribe-faq-payment-a . "Aktsepteerime kõiki peamisi krediit- ja deebetkaarte meie maksepartneri Polar.sh kaudu.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Midagi läks valesti")
 (:error-text-too-long . "Tekst on liiga pikk. Maksimaalne tõlke pikkus on 120 tähemärki.")
 (:error-input-too-long . "Sisend liiga pikk")
 (:error-unknown-source-lang . "Valitud lähtekeel ei ole toetatud.")
 (:error-unknown-target-lang . "Valitud sihtkeel ei ole toetatud.")
 (:error-unknown-language . "Tundmatu keel")
 (:error-translation-unavailable . "Tõlketeenus on ajutiselt kättesaamatu. Palun proovi hetke pärast uuesti.")
 (:error-translation-failed . "Tõlkimine ebaõnnestus")
 (:error-translation-retry . "Tõlget ei õnnestunud mitme katse järel genereerida. Palun proovi oma teksti ümber sõnastada.")
 (:error-quota-exceeded . "Tõlkelimiit täis")
 (:error-quota-exceeded-detail . "Oled kasutanud kõik oma selle kuu tõlked. Sinu kvoot lähtestub automaatselt iga kuu.")
 (:quota-low-warning . "Alles ~A tõlget. Kaaluge juurde ostmist.")
 (:top-up-button . "Osta rohkem tõlkeid")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 tõlget")

 ;; Institutions
 (:institutions-page-title . "Hiisi koolidele ja ülikoolidele")
 (:institutions-hero-title . "Keeleõppe tööriistad, mis on loodud klassiruumi jaoks")
 (:institutions-hero-subtitle . "Paku oma õppijatele jagatavaid kaardipakke, grammatikat arvestavat harjutamist ja püsivat kordamisrütmi, mis sobib päris õpetusega.")
 (:institutions-section-title . "Miks asutused kasutavad Hiisit")
 (:institutions-section-body . "Hiisi aitab õpetajatel muuta õppematerjali juhendatud harjutamiseks, millega õppijad päriselt kaasa jõuavad. Loo kursuse jaoks kaardipakke, jaga neid lingiga ning toeta sõnavara ja grammatika harjutamist ilma lisahalduse koormata.")
 (:institutions-benefit-1 . "Jagatavad kaardipakid ja oma ülesanded, mis sobivad teie õppekavaga.")
 (:institutions-benefit-2 . "Õppijate meeldimised ja mittemeeldimised aitavad tavapäraste tunniväljendite jaoks parimad tõlked esile tõsta.")
 (:institutions-benefit-3 . "Grammatika jaotused ning hajutatud kordamine toetavad enamat kui üksikute sõnaloendite päheõppimist.")
 (:institutions-benefit-4 . "Õpetajast lähtuv tugi inimeselt, kes kuulab tähelepanelikult ja hoolib klassiruumi vajadustest.")
 (:institutions-request-title . "Räägime sellest")
 (:institutions-request-subtitle . "Kirjelda oma asutust, keeli ja seda, millist õpet toetavat abi vajad. Vastame nädala jooksul.")
 (:institutions-field-name . "Asutuse nimi")
 (:institutions-field-name-placeholder . "Helsingi Ülikool")
 (:institutions-field-contact-name . "Kontaktisiku nimi")
 (:institutions-field-contact-name-placeholder . "Sinu nimi")
 (:institutions-field-contact-email . "Kontakti e-post")
 (:institutions-field-contact-email-placeholder . "sinu@ulikool.ee")
 (:institutions-field-domains . "E-posti domeenid")
 (:institutions-field-domains-placeholder . "ulikool.ee, cs.ulikool.ee")
 (:institutions-field-domains-help . "Komadega eraldatud e-posti domeenide loend sinu asutuse jaoks")
 (:institutions-field-notes . "Lisainfo")
 (:institutions-field-notes-placeholder . "Hinnanguline õpilaste arv, eelistatud arveldustsükkel, erisoovid...")
 (:institutions-submit . "Esita päring")
 (:institutions-success-title . "Aitäh - Hiisi koolidele ja ülikoolidele")
 (:institutions-success-heading . "Aitäh!")
 (:institutions-success-body . "Oleme sinu päringu kätte saanud. Vaatame üle teie asutuse vajadused ja võtame ühendust nädala jooksul.")
 (:institutions-success-back . "Tagasi avalehele")

 ;; Footer
 (:footer-privacy . "Privaatsuspoliitika")
 (:footer-terms . "Kasutustingimused")

 ;; Early software notice
 (:early-software-notice . "Hiisi on varajases arendusfaasis. Leidsid vea või on sul ettepanek?")

 ;; Privacy Policy
 (:privacy-title . "Privaatsuspoliitika")
 (:privacy-updated . "Viimati uuendatud: jaanuar 2026")
 (:privacy-who-title . "Kes me oleme")
 (:privacy-who-body . "Hiisi-d käitab Lambda Symbolics OÜ, Eestis registreeritud ettevõte. Eestis registreeritud ettevõttena järgime Euroopa Liidu üldist andmekaitsemäärust (GDPR).")
 (:privacy-collect-title . "Kogutavad andmed")
 (:privacy-collect-intro . "Kui kasutate Hiisi-d, kogume järgmist teavet:")
 (:privacy-collect-account-key . "Konto teave: ")
 (:privacy-collect-account-val . "E-posti aadress, kuvatav nimi ja turvaliselt räsitud parool.")
 (:privacy-collect-learning-key . "Õppeandmed: ")
 (:privacy-collect-learning-val . "Teie tõlked, salvestatud kaardid ja kordamise ajalugu.")
 (:privacy-collect-usage-key . "Kasutusandmed: ")
 (:privacy-collect-usage-val . "Põhilised serverilogid turvalisuse ja silumise eesmärgil.")
 (:privacy-use-title . "Kuidas me teie andmeid kasutame")
 (:privacy-use-auth-key . "Autentimine: ")
 (:privacy-use-auth-val . "Teie identiteedi kinnitamiseks ja konto turvalisuse tagamiseks.")
 (:privacy-use-service-key . "Teenuse osutamine: ")
 (:privacy-use-service-val . "Tõlkide pakkumiseks ja teie kaardikogu haldamiseks.")
 (:privacy-use-ai-key . "AI tõlked: ")
 (:privacy-use-ai-val . "Teie tõlketaotlused saadetakse Anthropic'i Claude API-le vastuste genereerimiseks. Vaadake Anthropic'i privaatsuspoliitikat, et teada saada, kuidas nad nende andmetega toimivad.")
 (:privacy-third-title . "Kolmandate osapoolte teenused")
 (:privacy-third-intro . "Kasutame järgmisi kolmandate osapoolte teenuseid:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "AI-toeliste tõlkide jaoks.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "Konto aktiveerimis- ja tehingue-kirjade saatmiseks.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Tellimuste maksete töötlemiseks.")
 (:privacy-cookies-title . "Küpsised")
 (:privacy-cookies-intro . "Kasutame ainult hädavajalikke küpsiseid:")
 (:privacy-cookies-auth-key . "Autentimisluba: ")
 (:privacy-cookies-auth-val . "Turvaline, HTTP-only küpsis, mis hoiab teid sisselogituna.")
 (:privacy-cookies-lang-key . "Keele eelistus: ")
 (:privacy-cookies-lang-val . "Teie eelistatud kasutajaliidese keeles meelde jätmiseks.")
 (:privacy-retention-title . "Andmete säilitamine")
 (:privacy-retention-body . "Teie andmeid säilitatakse nii kaua, kui teil on konto. Kui soovite kustutamist, planeeritakse teie konto kustutamine 14 päeva jooksul.")
 (:privacy-rights-title . "Teie õigused (GDPR)")
 (:privacy-rights-intro . "GDPR-i alusel on teil õigus:")
 (:privacy-rights-access . "Pääseda ligi oma isikuandmetele")
 (:privacy-rights-export . "Eksportida oma andmeid (saadaval aadressil /app/api/export)")
 (:privacy-rights-correct . "Nõuda ebatäpsete andmete parandamist")
 (:privacy-rights-delete . "Nõuda oma konto ja andmete kustutamist")
 (:privacy-rights-object . "Vaidlustada oma andmete töötlemist")
 (:privacy-rights-contact . "Nende õiguste kasutamiseks võtke meiega ühendust aadressil")
 (:privacy-contact-title . "Kontakt")
 (:privacy-contact-intro . "Privaatsuspuudutavate päringute jaoks:")
 (:privacy-contact-email-label . "E-post: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Eesti")

 ;; Terms of Service
 (:terms-title . "Kasutustingimused")
 (:terms-updated . "Viimati uuendatud: jaanuar 2026")
 (:terms-1-title . "1. Teenuse kirjeldus")
 (:terms-1-body . "Hiisi on keeleõppe rakendus, mis pakub grammatiliste selgitustega automaatseid tõlkeid ja ruumilise kordamisega kaarte. Teenust käitab Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Konto registreerimine")
 (:terms-2-body . "Hiisi kasutamiseks peate looma konto kehtiva e-posti aadressiga. Teie vastutate oma konto volituste turvalisuse säilitamise eest.")
 (:terms-3-title . "3. Tellimus ja maksed")
 (:terms-3-body . "Hiisi pakub tasulisi tellimusplaane (kuu- ja aastapõhised). Tellimusi töödeldakse Polar.sh-i kaudu.")
 (:terms-3-list-1 . "Tellimused uuenevad automaatselt, kui neid ei tühistata enne uuendamise kuupäeva.")
 (:terms-3-list-2 . "Tagasimakseid pakutakse vastavalt kohaldatavatele tarbijakaitse seadustele.")
 (:terms-3-list-3 . "Maksmata jätmine põhjustab juurdepääsu kaotamise premium-funktsioonidele.")
 (:terms-4-title . "4. Aktsepteeritav kasutamine")
 (:terms-4-intro . "Te nõustute mitte:")
 (:terms-4-list-1 . "Kasutama teenust mis tahes ebaseaduslikul eesmärgil")
 (:terms-4-list-2 . "Üritama kasutuspiiranguid või turvameetmeid mööda hiilida")
 (:terms-4-list-3 . "Jagama oma konto volitusi teistega")
 (:terms-4-list-4 . "Kasutama automatiseeritud tööriistu teenusele juurdepääsuks viisil, mis halvendab jõudlust teiste jaoks")
 (:terms-5-title . "5. Sisu ja intellektuaalne omand")
 (:terms-5-body-1 . "Hiisi poolt genereeritud tõlked luuakse automaatselt ja need ei pruugi olla unikaalsed. Võite oma tõlkeid ja kaarte kasutada mis tahes isiklikul eesmärgil, kuid te ei oma automaatselt genereeritud sisu suhtes eksklusiivset autorikaitset.")
 (:terms-5-body-2 . "Hiisi rakendus, kaubamärk ja originaalsisu jäävad Lambda Symbolics OÜ omandiks.")
 (:terms-6-title . "6. Teenuse kättesaadavus")
 (:terms-6-intro . "Hiisi pakutakse \"sellisena, nagu see on\". Me ei garanteeri:")
 (:terms-6-list-1 . "Katkematut või veavaba teenust")
 (:terms-6-list-2 . "Automaatselt genereeritud tõlgete täpsust")
 (:terms-6-list-3 . "Konkreetsete funktsioonide kättesaadavust")
 (:terms-6-body . "Võime funktsioone igal ajal muuta või lõpetada.")
 (:terms-7-title . "7. Vastutuse piiramine")
 (:terms-7-body-1 . "Seaduses lubatud maksimaalses ulatuses ei vastuta Lambda Symbolics OÜ Hiisi kasutamisest tulenevate kaudsete, juhuslike, eriliste või tagajärjeliste kahjude eest.")
 (:terms-7-body-2 . "Meie koguvastutus ei ületa teenuse eest makstud summat 12 kuu jooksul enne nõude esitamist.")
 (:terms-8-title . "8. Konto lõpetamine")
 (:terms-8-body-1 . "Võime teie konto peatada või lõpetada, kui rikute neid tingimusi. Konto kustutamist võite taotleda igal ajal rakenduse kaudu.")
 (:terms-8-body-2 . "Kustutamistaotluse korral planeeritakse teie konto kustutamine 14 päeva jooksul.")
 (:terms-9-title . "9. Tingimuste muudatused")
 (:terms-9-body . "Võime neid tingimusi aeg-ajalt värskendada. Hiisi kasutamise jätkamine pärast muudatusi tähendab uute tingimustega nõustumist.")
 (:terms-10-title . "10. Kohaldatav õigus")
 (:terms-10-body . "Neid tingimusi reguleerivad Eesti seadused. Kõik vaidlused lahendatakse Eesti kohtutes.")
 (:terms-contact-title . "Kontakt")
 (:terms-contact-intro . "Küsimuste korral nende tingimuste kohta:")
 (:terms-contact-email-label . "E-post: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Eesti")

 ;; Decks
 (:decks-title . "Kaardipakid")
 (:decks-subtitle . "Loo kohandatud kaardipakke ja jaga neid teistega.")
 (:decks-create-title . "Loo kaardipakk")
 (:decks-name-placeholder . "Kaardipaki nimi")
 (:decks-desc-placeholder . "Kirjeldus")
 (:decks-create-btn . "Loo kaardipakk")
 (:decks-edit-title . "Muuda kaardipakki")
 (:decks-edit-btn . "Muuda kaardipakki")
 (:decks-update-btn . "Salvesta muudatused")
 (:decks-default-badge . "Automaatne")
 (:decks-default-description . "Seda kaardipakki hallatakse selle keelepaari jaoks automaatselt.")
 (:decks-default-readonly . "Automaatsetel kaardipakkidel on kindlad nimed ja kirjeldused.")
 (:decks-error-name-required . "Kaardipaki nimi on kohustuslik.")
 (:decks-error-name-too-long . "Kaardipaki nimi võib olla kuni ~A märki pikk.")
 (:decks-error-desc-too-long . "Kaardipaki kirjeldus võib olla kuni ~A märki pikk.")
 (:decks-error-default-readonly . "Automaatseid kaardipakke ei saa muuta.")
 (:decks-your-title . "Sinu kaardipakid")
 (:decks-col-updated . "Uuendatud")
 (:decks-no-decks . "Kaardipakke veel pole.")
 (:decks-open-btn . "Ava")
 (:decks-no-desc . "Kirjeldus puudub.")
 (:decks-share-title . "Jagamislink")
 (:decks-share-info . "Igaüks selle lingiga saab kaardipaki importida:")
 (:decks-share-copy . "Kopeeri link")
 (:decks-share-copied . "Kopeeritud")
 (:decks-add-from-flashcards-title . "Lisa tõlked")
 (:decks-add-from-flashcards-info . "Vali kaart, et lisada selle tõlge sellesse kaardipakki.")
 (:decks-open-flashcards . "Lisa kaartidest")
 (:decks-filter-from . "Lähtekeel")
 (:decks-filter-to . "Sihtkeel")
 (:decks-filter-any . "Mis tahes keel")
 (:decks-filter-include-assigned . "Kuva kaardid, mis on juba kaardipakis")
 (:decks-flashcards-add . "Lisa")
 (:decks-flashcards-added . "Lisatud")
 (:decks-flashcards-in-deck . "Teises kaardipakis")
 (:decks-flashcards-empty . "Ükski kaart ei vasta nendele filtritele.")
 (:decks-items-title . "Kaardipaki sisu")
 (:decks-col-original . "Originaal")
 (:decks-col-translated . "Tõlge")
 (:decks-col-lang . "Sihtkeel")
 (:decks-no-items . "Üksusi veel pole.")
 (:decks-share-page-title . "Jaga kaardipakki")
 (:decks-share-preview . "Eelvaade ja impordi see kaardipakk.")
 (:decks-import-title . "Impordi")
 (:decks-import-btn . "Impordi kaardipakk")

 ;; Flashcards management page
 (:flashcards-title . "Minu kaardid")
 (:flashcards-subtitle . "Kõik sinu salvestatud kaardid ühes kohas. Otsi, korrasta ja halda.")
 (:flashcards-search-placeholder . "Otsi kaarte...")
 (:flashcards-hide-perfected . "Peida täielikult omandatud kaardid")
 (:flashcards-col-original . "Originaal")
 (:flashcards-col-translated . "Tõlge")
 (:flashcards-no-cards . "Kaarte veel pole. Alusta tõlkimist, et neid luua!")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Õpi keeli põhjalikult")
 (:landing-hero-subheadline . "Saa tõlkeid koos täieliku grammatilise analüüsiga ja ehita kestev sõnavara hajutatud kordamise õppekaartide abil.")
 (:landing-hero-trust-line . "7 päeva tasuta prooviperioodi 100 tõlkega. Tühista igal ajal.")
 (:landing-credibility-languages . "14 keelt")
 (:landing-credibility-ai . "Grammatiline analüüs kaasas")
 (:landing-step-1-title . "Tõlgi mistahes teksti")
 (:landing-step-1-desc . "Sisesta sõna või fraas. Saa tõlge koos täieliku grammatilise analüüsiga.")
 (:landing-step-2-title . "Salvesta õppekaartidena")
 (:landing-step-2-desc . "Salvesta tõlked, mida soovid meelde jätta. Õppekaardid luuakse automaatselt.")
 (:landing-step-3-title . "Korda ja jäta meelde")
 (:landing-step-3-desc . "Hajutatud kordamine planeerib ülevaatamised ideaalsel hetkel pikaajalise mälu jaoks.")
 (:landing-feature-grammar-title . "Mõista grammatikat, mitte ainult sõnu")
 (:landing-feature-grammar-desc . "Iga tõlge sisaldab üksikasjalikku grammatilist analüüsi -- sõnavormid, käänded ja pöörded on selgitatud sinu keeles.")
 (:landing-feature-srs-title . "Teaduspõhine meeldejätmine")
 (:landing-feature-srs-desc . "SM-2 algoritm kohaneb sinu sooritusega. Rasked kaardid ilmuvad sagedamini. Kaardid, mida tead, taanduvad.")
 (:landing-feature-share-title . "Jaga kaardipakke õpilastega")
 (:landing-feature-share-desc . "Õpetajad saavad luua kohandatud õppekaardipakke ja jagada neid lingiga. Õpilased impordivad paki ja alustavad kohe kordamist.")
 (:landing-pricing-trial-note . "Sisaldab 7 päeva tasuta prooviperioodi")
 (:landing-pricing-monthly-after . "7 päeva tasuta, seejärel ~A/kuu")
 (:landing-pricing-annual-after . "7 päeva tasuta, seejärel ~A/aasta")
 (:landing-faq-title . "Korduma kippuvad küsimused")
 (:landing-faq-trial-cap-q . "Mitu tõlget saan prooviperioodil?")
 (:landing-faq-trial-cap-a . "Saad 100 tõlget 7-päevase prooviperioodi jooksul. Pärast tellimist saad 600 kuus.")
 (:landing-final-cta-title . "Alusta õppimist täna")
 (:landing-final-cta-subtitle . "Liitu Hiisiga ja hakka ehitama sõnavara, mis püsib.")

 ;; Trial status (in-app)
 (:trial-status . "Tasuta prooviperiood")
 (:error-trial-quota-exceeded . "Proovitõlgete limiit täis")
 (:error-trial-quota-detail . "Oled kasutanud kõik 100 proovitõlget. Telli, et jätkata õppimist.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Loo õppekaart")
 (:custom-flashcard-edit-title . "Muuda õppekaarti")
 (:custom-flashcard-original . "Algne tekst")
 (:custom-flashcard-translated . "Tõlge")
 (:custom-flashcard-lang-from . "Lähtekeel")
 (:custom-flashcard-lang-to . "Sihtkeel")
 (:custom-flashcard-note . "Õppemärkus")
 (:custom-flashcard-forms . "Grammatiline analüüs")
 (:custom-flashcard-form-term . "Termin")
 (:custom-flashcard-form-explanation . "Selgitus")
 (:custom-flashcard-add-form . "Lisa grammatiline termin")
 (:custom-flashcard-remove-form . "Eemalda")
 (:custom-flashcard-ai-fill . "Täida tehisaruga")
 (:custom-flashcard-create-btn . "Loo õppekaart")
 (:custom-flashcard-update-btn . "Salvesta muudatused")

 ;; Probleemidest teavitamine
 (:issues-open-button . "Teata probleemist")
 (:issues-modal-title . "Teata probleemist")
 (:issues-modal-subtitle . "Kirjelda, mis läks valesti. Sinu praegune leht lisatakse automaatselt.")
 (:issues-title-label . "Lühike pealkiri")
 (:issues-title-placeholder . "Probleemi lühikokkuvõte")
 (:issues-message-label . "Mis juhtus?")
 (:issues-message-placeholder . "Lisa palun taasesitamise sammud, oodatud tulemus ja tegelik tulemus.")
 (:issues-submit . "Saada teade")
 (:issues-cancel . "Tühista")
 (:issues-success . "Aitäh. Probleemiteade on saadetud.")
 (:issues-error-required . "Palun kirjelda enne saatmist probleemi.")
 (:issues-error-title-too-long . "Teate pealkiri on liiga pikk. Hoia see alla 160 märgi.")
 (:issues-error-too-long . "Teate tekst on liiga pikk. Hoia see alla 4000 märgi.")
 (:issues-error-rate-limit . "Sellest allikast on saadetud liiga palju teateid. Palun oota ja proovi hiljem uuesti.")
 (:issues-error-generic . "Probleemiteadet ei õnnestunud saata. Palun proovi uuesti.")

)
