;;; Estonian translations

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Eesti")
 (:lang-flag . "🇪🇪")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Valige oma keel")
 (:lang-modal-subtitle . "Valige liidese eelistatud keel:")

 ;; Navigation
 (:nav-translate . "Tõlgi")
 (:nav-review . "Kordamine")
 (:nav-flashcards . "Minu kaardid")
 (:nav-dashboard . "Ülevaade")
 (:nav-decks . "Kaardipakid")
 (:nav-logout . "Logi välja")
 (:nav-home . "Avaleht")
 (:nav-pricing . "Hinnad")
 (:nav-export-data . "Ekspordi andmed")

 ;; App title and branding
 (:app-title . "Hiisi - Keeleõpe")
 (:app-tagline . "Õpi keeli tõlkimise kaudu")

 ;; Landing page
 (:landing-hero-title . "Omanda ükskõik milline keel")
 (:landing-hero-subtitle . "Tõlgi mida iganes. Loo automaatselt mälukaarte, mis õpetavad sulle, miks see nii toimib.")
 (:landing-cta . "Alusta õppimist")
 (:landing-learn-more . "Loe lähemalt")
 (:landing-how-it-works . "Kuidas see töötab")
 (:landing-feature-1-title . "Automaatsed mälukaardid")
 (:landing-feature-1-desc . "Iga tõlge loob automaatselt mälukaardid koos grammatika selgitustega. Pole vaja käsitsi kaarte luua.")
 (:landing-feature-2-title . "Hajutatud kordamine")
 (:landing-feature-2-desc . "SM-2 algoritm ajastab kordamised optimaalsete intervallidega. Õpi tõhusalt, jäta püsivalt meelde.")
 (:landing-feature-3-title . "Grammatika õpetus")
 (:landing-feature-3-desc . "Iga tõlge selgitab grammatikat, sõnatüvesid ja lauseehitust. Mõista põhjust, mitte ainult tulemust.")
 (:landing-free-trial . "7-päevane tasuta prooviperiood. Krediitkaarti pole vaja.")
 (:landing-start-trial . "Alusta tasuta prooviperioodi")
 (:landing-best-value . "Parim pakkumine")
 (:landing-cta-title . "Valmis õppima keeli grammatika, mitte päheõppimise kaudu?")
 (:landing-cta-subtitle . "Iga tõlge muutub õppimisvõimaluseks. Iga mälukaart õpetab sulle põhjust.")
 (:landing-signup-free . "Registreeru tasuta")

 ;; Auth pages
 (:auth-register . "Registreeru")
 (:auth-login . "Logi sisse")
 (:auth-logout . "Logi välja")
 (:auth-email . "E-post")
 (:auth-password . "Parool")
 (:auth-password-again . "Kinnita parool")
 (:auth-display-name . "Kuvatav nimi")
 (:auth-register-title . "Registreeru Hiisi kasutajaks")
 (:auth-register-subtitle . "Loo uus konto")
 (:auth-login-title . "Logi Hiisi sisse")
 (:auth-login-subtitle . "Sisesta oma andmed")
 (:auth-forgot-password . "Unustasid parooli?")
 (:auth-no-account . "Pole veel kontot?")
 (:auth-have-account . "On juba konto?")
 (:auth-google . "Google")
 (:auth-account-created . "Konto loodud!")
 (:auth-check-email . "Kontrolli oma e-posti aktiveerimislingi saamiseks.")
 (:auth-redirect-login . "Suunan sisselogimisele")
 (:auth-seconds . "sekundi pärast...")
 (:auth-go-now . "Mine kohe")
 (:auth-not-activated . "Konto pole aktiveeritud")
 (:auth-activate-title . "Aktiveeri oma konto!")
 (:auth-activated . "Konto aktiveeritud!")
 (:auth-activated-message . "Sinu konto on aktiveeritud. Võid nüüd Hiisi kasutada.")
 (:auth-redirecting . "Suunan ümber")
 (:auth-go-to-app . "Mine rakendusse")
 (:auth-resend-title . "Saada aktiveerimismeil uuesti")
 (:auth-resend-subtitle . "Sisesta oma e-post, et saada uus aktiveerimislink.")
 (:auth-resend-button . "Saada aktiveerimismeil uuesti")
 (:auth-resend-success . "Aktiveerimismeil saadetud!")
 (:auth-resend-success-detail . "Vaata oma postkasti uue aktiveerimislingi saamiseks.")
 (:auth-resend-rate-limited . "Palun oota mõni minut enne järgmise aktiveerimismeili taotlemist.")
 (:auth-resend-cooldown . "Saad uue meili taotleda ~a sekundi pärast.")
 (:auth-back-to-login . "Tagasi sisselogimisele")
 (:auth-forgot-password-title . "Unustasin parooli")
 (:auth-forgot-password-subtitle . "Sisesta oma e-post ja saadame sulle lingi parooli lähtestamiseks.")
 (:auth-send-reset-link . "Saada lähtestamise link")
 (:auth-reset-email-sent . "Link saadetud!")
 (:auth-reset-email-sent-detail . "Kui selle e-postiga konto eksisteerib, saad peagi parooli lähtestamise lingi.")
 (:auth-reset-rate-limited . "Palun oota mõni minut enne järgmise parooli lähtestamise taotlemist.")
 (:auth-reset-invalid-token . "See parooli lähtestamise link on kehtetu või aegunud.")
 (:auth-reset-password-title . "Lähtesta parool")
 (:auth-reset-password-subtitle . "Sisesta oma uus parool allpool.")
 (:auth-new-password . "Uus parool")
 (:auth-confirm-new-password . "Kinnita uus parool")
 (:auth-reset-password . "Lähtesta parool")
 (:auth-password-changed . "Parool muudetud!")
 (:auth-password-changed-detail . "Sinu parool on edukalt muudetud. Võid nüüd uue parooliga sisse logida.")
 (:auth-change-password-title . "Muuda parooli")
 (:auth-change-password-subtitle . "Uuenda oma konto parooli.")
 (:auth-current-password . "Praegune parool")
 (:auth-change-password . "Muuda parooli")
 (:auth-back-to-app . "Tagasi rakendusse")
 (:auth-password-updated . "Parool uuendatud!")
 (:auth-password-updated-detail . "Sinu parool on edukalt uuendatud.")

 ;; Translation page
 (:translate-title . "Tõlgi")
 (:translate-input-label . "Tõlgitav tekst")
 (:translate-input-placeholder . "Sisesta tõlgitav tekst...")
 (:translate-from . "Allikast:")
 (:translate-to . "Sihtkeelde:")
 (:translate-submit . "Tõlgi")
 (:translate-save . "Salvesta mälukaartidesse")
 (:translate-saved . "Salvestatud!")
 (:translate-like . "Meeldib")
 (:translate-dislike . "Ei meeldi")
 (:translate-char-limit . "tähemärki alles")
 (:translate-auto-detect . "Suvaline (automaattuvastus)")
 (:translate-empty-state . "Sisesta tekst ülal ja klõpsa Tõlgi, et näha tulemust koos grammatika analüüsiga")
 (:translate-select-deck-placeholder . "Vali kaardipakk (valikuline)")
 (:translate-new-deck . "Uus kaardipakk")
 (:translate-add-to-deck . "Lisa kaardipakki")
 (:translate-bookmark . "Salvesta")
 (:translate-bookmarked . "Salvestatud")
 (:translate-retry . "Proovi uuesti")
 (:translate-like-tooltip . "Hea tõlge")
 (:translate-dislike-tooltip . "Halb tõlge - taotle uut")
 (:translate-dislike-confirm . "See genereerib uue tõlke. Jätkata?")
 (:translate-liked . "Meeldib!")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Siht")
 (:translate-deck-create-title . "Loo uus kaardipakk")
 (:translate-deck-name-label . "Kaardipaki nimi")
 (:translate-deck-name-placeholder . "nt Soome keele alused")
 (:translate-deck-description-label . "Kirjeldus (valikuline)")
 (:translate-deck-cancel . "Tühista")
 (:translate-deck-create . "Loo")
 (:translate-rate-label . "Hinda tõlget")
 (:flashcards-delete-confirm . "Kas oled kindel, et soovid selle kaardi kustutada?")
 (:flashcards-deck-search-placeholder . "Otsi kaardipakke...")
 (:flashcards-no-decks . "Kaardipakke veel pole. Loo üks kõigepealt!")
 (:flashcards-deck-cancel . "Tühista")

 ;; Flashcard review
 (:review-title . "Kordamine")
 (:review-session-title . "Kordamisseanss")
 (:review-session-subtitle . "Harjuta oma salvestatud mälukaarte")
 (:review-selector-title . "Vali, mida korrata")
 (:review-selector-subtitle . "Vali pakk või keelepaar, millele selles kordamisseansis keskenduda.")
 (:review-by-deck . "Korda paki järgi")
 (:review-by-language-pair . "Korda keelepaari järgi")
 (:review-all-cards . "Korda kõiki kaarte")

 (:review-start . "Alusta kordamist")
 (:review-no-cards . "Pole kaarte kordamiseks")
 (:review-no-cards-desc . "Sul pole praegu ühtegi mälukaarti, mis vajaks kordamist.")
 (:review-no-cards-hint . "Tõlgi teksti ja klõpsa \"Salvesta mälukaartidesse\", et oma pakki üles ehitada!")
 (:review-start-translating . "Alusta tõlkimist")
 (:review-show-answer . "Näita vastust")
 (:review-click-reveal . "Klõpsa vastuse nägemiseks")
 (:review-grammar-breakdown . "Grammatika analüüs")
 (:review-how-well . "Kui hästi mäletasid?")
 (:review-again . "Uuesti")
 (:review-hard . "Raske")
 (:review-good . "Hea")
 (:review-easy . "Kerge")
 (:review-progress . "Kaart ~a/~a")
 (:review-complete . "Seanss lõpetatud!")
 (:review-complete-msg . "Kordasid ~a kaarti")
 (:review-correct . "Õige")
 (:review-accuracy . "Täpsus")
 (:review-again-btn . "Korda uuesti")
 (:review-translate-more . "Tõlgi rohkem")
 (:review-streak . "päevane seeria")

 ;; Dashboard
 (:dashboard-title . "Ülevaade")
 (:dashboard-cards-due . "Ootel kaardid")
 (:dashboard-total-cards . "Kaarte kokku")
 (:dashboard-subscription . "Tellimus")
 (:dashboard-subscribed-until . "Tellimus kehtib kuni")
 (:dashboard-not-subscribed . "Tellimus puudub")
 (:dashboard-recent . "Viimased tõlked")
 (:dashboard-no-translations . "Tõlkeid veel pole")
 (:dashboard-streak . "Kordamise seeria")
 (:dashboard-days . "päeva")
 (:dashboard-quick-actions . "Kiirtoimingud")
 (:dashboard-getting-started . "Alustamine")
 (:dashboard-tip-1 . "Tõlgi teksti, mida soovid õppida")
 (:dashboard-tip-2 . "Klõpsa \"Salvesta mälukaartidesse\" tõlgetel, mida soovid meelde jätta")
 (:dashboard-tip-3 . "Korda oma mälukaarte regulaarselt - hajutatud kordamine aitab pikaajalise mäluga")
 (:dashboard-tip-4 . "Hinda ausalt - see aitab algoritmil sinu kordamisi optimaalselt ajastada")

 ;; Account
 (:account-title . "Konto")
 (:account-subtitle . "Halda oma konto seadeid ja kustutamise ajakava.")
 (:account-deletion-title . "Konto kustutamine")
 (:account-deletion-scheduled . "Sinu konto on planeeritud kustutamiseks kuupäeval ~A.")
 (:account-deletion-cancel-hint . "Saad enne seda kuupäeva tühistada ja konto alles jätta.")
 (:account-deletion-cancel . "Tühista kustutamine")
 (:account-deletion-request . "Kontot saad kustutada igal ajal. Kustutamine on planeeritud 14 päeva pärast kinnitamist. Kui pärast kustutamist meelt muudad, võta ühendust toega.")
 (:account-deletion-confirm . "Kas planeerida konto kustutamine 14 päeva pärast tänast?")
 (:account-deletion-schedule . "Planeeri kustutamine")
 (:account-reminders-title . "E-posti meeldetuletused")
 (:account-reminders-subtitle . "Halda selle konto kordamise ja jätkamise meeldetuletusi.")
 (:account-reminders-opt-out . "Lülita kordamise ja jätkamise meeldetuletused välja")
 (:account-reminders-save . "Salvesta eelistused")

 ;; Subscription
 (:subscribe-title . "Lihtne hinnastus")
 (:subscribe-choose-plan . "Vali oma pakett")
 (:subscribe-start-today . "Alusta õppimist juba täna 7-päevase tasuta prooviperioodiga")
 (:subscribe-monthly . "Kuutellimus")
 (:subscribe-annual . "Aastatellimus")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/kuus")
 (:subscribe-per-year . "/aastas")
 (:subscribe-monthly-desc . "600 tõlget kuus")
 (:subscribe-unlimited-flashcards . "Piiramatu arv mälukaarte")
 (:subscribe-grammar-explanations . "Grammatika selgitused")
 (:subscribe-spaced-repetition . "Hajutatud kordamine")
 (:subscribe-annual-desc . "Säästa €20 — kaks kuud tasuta!")
 (:subscribe-cta . "Telli")
 (:subscribe-success . "Tellimus õnnestus!")
 (:subscribe-manage . "Halda tellimust")
 (:subscribe-activated . "Tellimus aktiveeritud!")
 (:subscribe-thank-you . "Täname tellimuse eest. Sinu konto on nüüd aktiivne.")
 (:subscribe-start-learning . "Alusta õppimist")
 (:subscribe-management . "Tellimuse haldamine")
 (:subscribe-active . "Aktiivne tellimus")
 (:subscribe-status . "Staatus:")
 (:subscribe-status-active . "Aktiivne")
 (:subscribe-days-remaining . "Päevi jäänud:")
 (:subscribe-renews-on . "Uueneb:")
 (:subscribe-no-subscription . "Aktiivne tellimus puudub")
 (:subscribe-access-features . "Telli, et pääseda ligi kõikidele funktsioonidele.")
 (:subscribe-view-plans . "Vaata pakette")
 (:subscribe-faq-title . "Korduma kippuvad küsimused")
 (:subscribe-faq-trial-q . "Mis juhtub pärast tasuta prooviperioodi?")
 (:subscribe-faq-trial-a . "Pärast 7-päevast tasuta prooviperioodi võetakse sinu valitud paketi eest tasu. Võid igal ajal enne prooviperioodi lõppu tühistada.")
 (:subscribe-faq-cancel-q . "Kas saan igal ajal tühistada?")
 (:subscribe-faq-cancel-a . "Jah! Võid oma tellimuse igal ajal tühistada. Ligipääs säilib arveldusperioodi lõpuni.")
 (:subscribe-faq-payment-q . "Milliseid makseviise aktsepteerite?")
 (:subscribe-faq-payment-a . "Aktsepteerime kõiki peamisi krediit- ja deebetkaarte meie maksepartneri Polar.sh kaudu.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Midagi läks valesti")
 (:error-not-found . "Lehte ei leitud")
 (:error-unauthorized . "Jätkamiseks logi palun sisse")
 (:error-subscription-required . "Tellimus nõutud")
 (:error-text-too-long . "Tekst on liiga pikk. Maksimaalne tõlke pikkus on 120 tähemärki.")
 (:error-input-too-long . "Sisend liiga pikk")
 (:error-unknown-source-lang . "Valitud lähtekeel ei ole toetatud.")
 (:error-unknown-target-lang . "Valitud sihtkeel ei ole toetatud.")
 (:error-unknown-language . "Tundmatu keel")
 (:error-translation-unavailable . "Tõlketeenus on ajutiselt kättesaamatu. Palun proovi hetke pärast uuesti.")
 (:error-translation-failed . "Tõlkimine ebaõnnestus")
 (:error-translation-retry . "Tõlget ei õnnestunud mitme katse järel genereerida. Palun proovi oma teksti ümber sõnastada.")
 (:error-quota-exceeded . "Tõlkelimiit täis")
 (:error-quota-exceeded-detail . "Oled kasutanud kõik oma selle kuu tõlked. Sinu kvoot lähtestub automaatselt iga kuu.")
 (:quota-warning . "Jäänud tõlked: ~A")
 (:quota-low-warning . "Alles ~A tõlget. Kaaluge juurde ostmist.")
 (:top-up-button . "Osta rohkem tõlkeid")
 (:top-up-success . "Laadimine õnnestus! Teil on nüüd ~A lisatõlget.")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 tõlget")
 (:loading . "Laadimine...")
 (:empty-state . "Siin pole veel midagi")

 ;; Institutions
 (:institutions-page-title . "Hiisi koolidele - institutsionaalsed litsentsid")
 (:institutions-hero-title . "Hiisi koolidele")
 (:institutions-hero-subtitle . "Võimenda oma õpilasi tehisintellektiga keeleõppega")
 (:institutions-section-title . "Institutsionaalsed litsentsid")
 (:institutions-section-body . "Pakume hulgilitsentse koolidele, ülikoolidele ja keeleõppeasutustele. Teie domeenist pärit e-posti aadressidega õpilased saavad automaatselt täieliku juurdepääsu.")
 (:institutions-benefit-1 . "Automaatne registreerimine institutsionaalse e-postiga õpilastele")
 (:institutions-benefit-2 . "Ei mingeid individuaalseid kontosid hallata")
 (:institutions-benefit-3 . "Paindlikud arveldusvõimalused")
 (:institutions-benefit-4 . "Pühendatud tugi õpetajatele")
 (:institutions-request-title . "Taotle litsentsi")
 (:institutions-request-subtitle . "Täida allolev vorm ja võtame sinuga ühendust 2 tööpäeva jooksul.")
 (:institutions-field-name . "Asutuse nimi")
 (:institutions-field-name-placeholder . "Helsingi Ülikool")
 (:institutions-field-contact-name . "Kontaktisiku nimi")
 (:institutions-field-contact-name-placeholder . "Sinu nimi")
 (:institutions-field-contact-email . "Kontakti e-post")
 (:institutions-field-contact-email-placeholder . "sinu@ulikool.ee")
 (:institutions-field-domains . "E-posti domeenid")
 (:institutions-field-domains-placeholder . "ulikool.ee, cs.ulikool.ee")
 (:institutions-field-domains-help . "Komadega eraldatud e-posti domeenide loend sinu asutuse jaoks")
 (:institutions-field-notes . "Lisainfo")
 (:institutions-field-notes-placeholder . "Hinnanguline õpilaste arv, eelistatud arveldustsükkel, erisoovid...")
 (:institutions-submit . "Esita päring")
 (:institutions-success-title . "Aitäh - Hiisi koolidele")
 (:institutions-success-heading . "Aitäh!")
 (:institutions-success-body . "Oleme saanud sinu institutsionaalse litsentsi taotluse. Meie meeskond vaatab selle üle ja võtab sinuga ühendust 2 tööpäeva jooksul.")
 (:institutions-success-back . "Tagasi avalehele")

 ;; Footer
 (:footer-privacy . "Privaatsuspoliitika")
 (:footer-terms . "Kasutustingimused")
 (:footer-contact . "Kontakt")

 ;; Early software notice
 (:early-software-notice . "Hiisi on varajases arendusfaasis. Leidsid vea või on sul ettepanek?")
 (:early-software-contact . "Võta meiega ühendust aadressil")

 ;; Privacy Policy
 (:privacy-title . "Privaatsuspoliitika")
 (:privacy-updated . "Viimati uuendatud: jaanuar 2026")
 (:privacy-who-title . "Kes me oleme")
 (:privacy-who-body . "Hiisi-d käitab Lambda Symbolics OÜ, Eestis registreeritud ettevõte. Eestis registreeritud ettevõttena järgime Euroopa Liidu üldist andmekaitsemäärust (GDPR).")
 (:privacy-collect-title . "Kogutavad andmed")
 (:privacy-collect-intro . "Kui kasutate Hiisi-d, kogume järgmist teavet:")
 (:privacy-collect-account-key . "Konto teave: ")
 (:privacy-collect-account-val . "E-posti aadress, kuvatav nimi ja turvaliselt räsitud parool.")
 (:privacy-collect-learning-key . "Õppeandmed: ")
 (:privacy-collect-learning-val . "Teie tõlked, salvestatud kaardid ja kordamise ajalugu.")
 (:privacy-collect-usage-key . "Kasutusandmed: ")
 (:privacy-collect-usage-val . "Põhilised serverilogid turvalisuse ja silumise eesmärgil.")
 (:privacy-use-title . "Kuidas me teie andmeid kasutame")
 (:privacy-use-auth-key . "Autentimine: ")
 (:privacy-use-auth-val . "Teie identiteedi kinnitamiseks ja konto turvalisuse tagamiseks.")
 (:privacy-use-service-key . "Teenuse osutamine: ")
 (:privacy-use-service-val . "Tõlkide pakkumiseks ja teie kaardikogu haldamiseks.")
 (:privacy-use-ai-key . "AI tõlked: ")
 (:privacy-use-ai-val . "Teie tõlketaotlused saadetakse Anthropic'i Claude API-le vastuste genereerimiseks. Vaadake Anthropic'i privaatsuspoliitikat, et teada saada, kuidas nad nende andmetega toimivad.")
 (:privacy-third-title . "Kolmandate osapoolte teenused")
 (:privacy-third-intro . "Kasutame järgmisi kolmandate osapoolte teenuseid:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "AI-toeliste tõlkide jaoks.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "Konto aktiveerimis- ja tehingue-kirjade saatmiseks.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Tellimuste maksete töötlemiseks.")
 (:privacy-cookies-title . "Küpsised")
 (:privacy-cookies-intro . "Kasutame ainult hädavajalikke küpsiseid:")
 (:privacy-cookies-auth-key . "Autentimisluba: ")
 (:privacy-cookies-auth-val . "Turvaline, HTTP-only küpsis, mis hoiab teid sisselogituna.")
 (:privacy-cookies-lang-key . "Keele eelistus: ")
 (:privacy-cookies-lang-val . "Teie eelistatud kasutajaliidese keeles meelde jätmiseks.")
 (:privacy-retention-title . "Andmete säilitamine")
 (:privacy-retention-body . "Teie andmeid säilitatakse nii kaua, kui teil on konto. Kui soovite kustutamist, planeeritakse teie konto kustutamine 14 päeva jooksul.")
 (:privacy-rights-title . "Teie õigused (GDPR)")
 (:privacy-rights-intro . "GDPR-i alusel on teil õigus:")
 (:privacy-rights-access . "Pääseda ligi oma isikuandmetele")
 (:privacy-rights-export . "Eksportida oma andmeid (saadaval aadressil /app/api/export)")
 (:privacy-rights-correct . "Nõuda ebatäpsete andmete parandamist")
 (:privacy-rights-delete . "Nõuda oma konto ja andmete kustutamist")
 (:privacy-rights-object . "Vaidlustada oma andmete töötlemist")
 (:privacy-rights-contact . "Nende õiguste kasutamiseks võtke meiega ühendust aadressil")
 (:privacy-contact-title . "Kontakt")
 (:privacy-contact-intro . "Privaatsuspuudutavate päringute jaoks:")
 (:privacy-contact-email-label . "E-post: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Eesti")

 ;; Terms of Service
 (:terms-title . "Kasutustingimused")
 (:terms-updated . "Viimati uuendatud: jaanuar 2026")
 (:terms-1-title . "1. Teenuse kirjeldus")
 (:terms-1-body . "Hiisi on keeleõppe rakendus, mis pakub grammatiliste selgitustega AI-toelisi tõlkeid ja ruumilise kordamisega kaarte. Teenust käitab Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Konto registreerimine")
 (:terms-2-body . "Hiisi kasutamiseks peate looma konto kehtiva e-posti aadressiga. Teie vastutate oma konto volituste turvalisuse säilitamise eest.")
 (:terms-3-title . "3. Tellimus ja maksed")
 (:terms-3-body . "Hiisi pakub tasulisi tellimusplaane (kuu- ja aastapõhised). Tellimusi töödeldakse Polar.sh-i kaudu.")
 (:terms-3-list-1 . "Tellimused uuenevad automaatselt, kui neid ei tühistata enne uuendamise kuupäeva.")
 (:terms-3-list-2 . "Tagasimakseid pakutakse vastavalt kohaldatavatele tarbijakaitse seadustele.")
 (:terms-3-list-3 . "Maksmata jätmine põhjustab juurdepääsu kaotamise premium-funktsioonidele.")
 (:terms-4-title . "4. Aktsepteeritav kasutamine")
 (:terms-4-intro . "Te nõustute mitte:")
 (:terms-4-list-1 . "Kasutama teenust mis tahes ebaseaduslikul eesmärgil")
 (:terms-4-list-2 . "Üritama kasutuspiiranguid või turvameetmeid mööda hiilida")
 (:terms-4-list-3 . "Jagama oma konto volitusi teistega")
 (:terms-4-list-4 . "Kasutama automatiseeritud tööriistu teenusele juurdepääsuks viisil, mis halvendab jõudlust teiste jaoks")
 (:terms-5-title . "5. Sisu ja intellektuaalne omand")
 (:terms-5-body-1 . "Hiisi poolt genereeritud tõlked luuakse AI abil ja need ei pruugi olla unikaalsed. Võite oma tõlkeid ja kaarte kasutada mis tahes isiklikul eesmärgil, kuid te ei oma AI-genereeritud sisu suhtes eksklusiivset autorikaitset.")
 (:terms-5-body-2 . "Hiisi rakendus, kaubamärk ja originaalsisu jäävad Lambda Symbolics OÜ omandiks.")
 (:terms-6-title . "6. Teenuse kättesaadavus")
 (:terms-6-intro . "Hiisi pakutakse \"sellisena, nagu see on\". Me ei garanteeri:")
 (:terms-6-list-1 . "Katkematut või veavaba teenust")
 (:terms-6-list-2 . "AI-genereeritud tõlgete täpsust")
 (:terms-6-list-3 . "Konkreetsete funktsioonide kättesaadavust")
 (:terms-6-body . "Võime funktsioone igal ajal muuta või lõpetada.")
 (:terms-7-title . "7. Vastutuse piiramine")
 (:terms-7-body-1 . "Seaduses lubatud maksimaalses ulatuses ei vastuta Lambda Symbolics OÜ Hiisi kasutamisest tulenevate kaudsete, juhuslike, eriliste või tagajärjeliste kahjude eest.")
 (:terms-7-body-2 . "Meie koguvastutus ei ületa teenuse eest makstud summat 12 kuu jooksul enne nõude esitamist.")
 (:terms-8-title . "8. Konto lõpetamine")
 (:terms-8-body-1 . "Võime teie konto peatada või lõpetada, kui rikute neid tingimusi. Konto kustutamist võite taotleda igal ajal rakenduse kaudu.")
 (:terms-8-body-2 . "Kustutamistaotluse korral planeeritakse teie konto kustutamine 14 päeva jooksul.")
 (:terms-9-title . "9. Tingimuste muudatused")
 (:terms-9-body . "Võime neid tingimusi aeg-ajalt värskendada. Hiisi kasutamise jätkamine pärast muudatusi tähendab uute tingimustega nõustumist.")
 (:terms-10-title . "10. Kohaldatav õigus")
 (:terms-10-body . "Neid tingimusi reguleerivad Eesti seadused. Kõik vaidlused lahendatakse Eesti kohtutes.")
 (:terms-contact-title . "Kontakt")
 (:terms-contact-intro . "Küsimuste korral nende tingimuste kohta:")
 (:terms-contact-email-label . "E-post: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Eesti")



 ;; Decks
 (:decks-title . "Kaardipakid")
 (:decks-subtitle . "Loo kohandatud kaardipakke ja jaga neid teistega.")
 (:decks-create-title . "Loo kaardipakk")
 (:decks-name-placeholder . "Kaardipaki nimi")
 (:decks-desc-placeholder . "Kirjeldus")
 (:decks-create-btn . "Loo kaardipakk")
 (:decks-your-title . "Sinu kaardipakid")
 (:decks-col-name . "Nimi")
 (:decks-col-desc . "Kirjeldus")
 (:decks-col-updated . "Uuendatud")
 (:decks-col-actions . "Tegevused")
 (:decks-no-decks . "Kaardipakke veel pole.")
 (:decks-open-btn . "Ava")
 (:decks-no-desc . "Kirjeldus puudub.")
 (:decks-share-title . "Jagamislink")
 (:decks-share-info . "Igaüks selle lingiga saab kaardipaki importida:")
 (:decks-share-copy . "Kopeeri link")
 (:decks-share-copied . "Kopeeritud")
 (:decks-add-from-flashcards-title . "Lisa tõlked")
 (:decks-add-from-flashcards-info . "Vali kaart, et lisada selle tõlge sellesse kaardipakki.")
 (:decks-open-flashcards . "Lisa kaartidest")
 (:decks-filter-from . "Lähtekeel")
 (:decks-filter-to . "Sihtkeel")
 (:decks-filter-any . "Mis tahes keel")
 (:decks-filter-include-assigned . "Kuva kaardid, mis on juba kaardipakis")
 (:decks-flashcards-col-from . "Lähte")
 (:decks-flashcards-col-to . "Siht")
 (:decks-flashcards-add . "Lisa")
 (:decks-flashcards-added . "Lisatud")
 (:decks-flashcards-in-deck . "Teises kaardipakis")
 (:decks-flashcards-empty . "Ükski kaart ei vasta nendele filtritele.")
 (:decks-add-trans-title . "Lisa tõlge")
 (:decks-trans-id-placeholder . "Tõlke ID")
 (:decks-add-trans-btn . "Lisa tõlge")
 (:decks-items-title . "Kaardipaki sisu")
 (:decks-col-original . "Originaal")
 (:decks-col-translated . "Tõlge")
 (:decks-col-lang . "Sihtkeel")
 (:decks-no-items . "Üksusi veel pole.")
 (:decks-share-page-title . "Jaga kaardipakki")
 (:decks-share-preview . "Eelvaade ja impordi see kaardipakk.")
 (:decks-import-title . "Impordi")
 (:decks-import-btn . "Impordi kaardipakk")

 ;; Flashcards management page
 (:flashcards-title . "Minu kaardid")
 (:flashcards-subtitle . "Kõik sinu salvestatud kaardid ühes kohas. Otsi, korrasta ja halda.")
 (:flashcards-search-placeholder . "Otsi kaarte...")
 (:flashcards-col-original . "Originaal")
 (:flashcards-col-translated . "Tõlge")
 (:flashcards-col-lang . "Keeled")
 (:flashcards-no-cards . "Kaarte veel pole. Alusta tõlkimist, et neid luua!")

 ;; API Errors (EN fallback)
 (:api-error-missing-text . "Missing text to translate.")
 (:api-error-invalid-translation-id . "Invalid translation ID.")
 (:api-error-translation-not-found . "The translation you tried to save no longer exists.")
 (:api-error-invalid-bookmark-id . "Invalid bookmark ID")
 (:api-error-bookmark-not-found . "Bookmark not found")
 (:api-error-forbidden . "Forbidden")
 (:api-error-failed-delete-bookmark . "Failed to delete bookmark")
 (:api-error-invalid-flashcard-id . "Invalid flashcard ID")
 (:api-error-missing-deck-id . "Missing deck_id")
 (:api-error-flashcard-not-found . "Flashcard not found")
 (:api-error-deck-not-found . "Deck not found")
 (:api-error-deck-name-required . "Deck name is required")
 (:api-error-session-expired . "Your review session has expired. Please start a new session.")
 (:api-error-invalid-card-id . "Invalid card ID.")
 (:api-error-invalid-rating . "Invalid rating.")
 (:api-error-rating-range . "Rating must be between 0 and 5.")
 (:api-error-card-not-found . "Card not found.")
 (:api-error-permission-denied . "You don't have permission to review this card.")
 (:api-error-unknown-source-lang . "Unknown source language.")
 (:api-error-unknown-target-lang . "Unknown target language.")
 (:api-error-failed-add-to-deck . "Failed to add to deck")

 ;; API Success messages
 (:api-success-added . "Added!")
 (:api-success-added-simple . "Added")

 ;; API Stats
 (:api-stats-due . "~A due")
 (:api-stats-total . "~A total")

 ;; Time units
 (:api-time-day . "day")
 (:api-time-days . "days")
 (:api-time-day-left . "day left")
 (:api-time-days-left . "days left")

 ;; Subscription status
 (:api-subscription-active . "Active")
 (:api-subscription-inactive . "Inactive")
 (:api-subscription-subscribe-hint . "Subscribe to unlock translations")

 ;; Generic status
 (:status-bad-request . "Bad Request")
 (:status-not-found . "Not Found")
 (:status-forbidden . "Forbidden")

)
