;;; Finnish translations

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Suomi")
 (:lang-flag . "🇫🇮")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Valitse kieli")
 (:lang-modal-subtitle . "Valitse käyttöliittymän kieli:")

 ;; Navigation
 (:nav-translate . "Käännä")
 (:nav-review . "Kertaa")
 (:nav-flashcards . "Korttini")
 (:nav-dashboard . "Hallintapaneeli")
 (:nav-decks . "Decks")
 (:nav-logout . "Kirjaudu ulos")
 (:nav-home . "Etusivu")
 (:nav-pricing . "Hinnoittelu")
 (:nav-export-data . "Vie tiedot")

 ;; App title and branding
 (:app-title . "Hiisi - Kielten oppiminen")
 (:app-tagline . "Opi kieliä käännösten avulla")

 ;; Landing page
 (:landing-hero-title . "Hallitse mikä tahansa kieli")
 (:landing-hero-subtitle . "Käännä mitä tahansa. Luo automaattisesti muistikortit, jotka opettavat sinulle miksi se toimii niin.")
 (:landing-cta . "Aloita oppiminen")
 (:landing-learn-more . "Lue lisää")
 (:landing-how-it-works . "Näin se toimii")
 (:landing-feature-1-title . "Automaattiset muistikortit")
 (:landing-feature-1-desc . "Jokainen käännös luo automaattisesti muistikortit kielioppiselityksineen. Ei manuaalista korttien luomista.")
 (:landing-feature-2-title . "Hajautettu toisto")
 (:landing-feature-2-desc . "SM-2-algoritmi ajoittaa kertaukset optimaalisesti. Opi tehokkaasti, muista pysyvästi.")
 (:landing-feature-3-title . "Kieliopin opetus")
 (:landing-feature-3-desc . "Jokainen käännös selittää kieliopin, sanojen juuret ja lauserakenteen. Ymmärrä miksi, älä vain mitä.")
 (:landing-free-trial . "7 päivän ilmainen kokeilu. Luottokorttia ei tarvita.")
 (:landing-start-trial . "Aloita ilmainen kokeilu")
 (:landing-best-value . "Paras arvo")
 (:landing-cta-title . "Valmis oppimaan kieliä kieliopin, ei ulkoa opettelun, kautta?")
 (:landing-cta-subtitle . "Jokainen käännös on oppimismahdollisuus. Jokainen muistikortti opettaa sinulle miksi.")
 (:landing-signup-free . "Rekisteröidy ilmaiseksi")

 ;; Auth pages
 (:auth-register . "Rekisteröidy")
 (:auth-login . "Kirjaudu")
 (:auth-logout . "Kirjaudu ulos")
 (:auth-email . "Sähköposti")
 (:auth-password . "Salasana")
 (:auth-password-again . "Vahvista salasana")
 (:auth-display-name . "Näyttönimi")
 (:auth-register-title . "Rekisteröidy Hiisiin")
 (:auth-register-subtitle . "Luo uusi tili")
 (:auth-login-title . "Kirjaudu Hiisiin")
 (:auth-login-subtitle . "Syötä tunnuksesi")
 (:auth-login-invalid-credentials . "Virheellinen sahkoposti tai salasana.")
 (:auth-login-rate-limited . "Liian monta kirjautumisyritysta. Odota muutama minuutti ja yrita uudelleen.")
 (:auth-forgot-password . "Unohditko salasanan?")
 (:auth-no-account . "Eikö sinulla ole tiliä?")
 (:auth-have-account . "Onko sinulla jo tili?")
 (:auth-google . "Google")
 (:auth-account-created . "Tili luotu!")
 (:auth-check-email . "Tarkista sähköpostisi aktivointilinkin varalta.")
 (:auth-redirect-login . "Uudelleenohjaus kirjautumiseen")
 (:auth-seconds . "sekunnissa...")
 (:auth-go-now . "Siirry nyt")
 (:auth-not-activated . "Tiliä ei ole aktivoitu")
 (:auth-activate-title . "Aktivoi tilisi!")
 (:auth-activated . "Tili aktivoitu!")
 (:auth-activated-message . "Tilisi on aktivoitu. Voit nyt käyttää Hiisiä.")
 (:auth-redirecting . "Uudelleenohjaus")
 (:auth-go-to-app . "Siirry sovellukseen")
 (:auth-resend-title . "Lähetä aktivointisähköposti uudelleen")
 (:auth-resend-subtitle . "Anna sähköpostiosoitteesi saadaksesi uuden aktivointilinkin.")
 (:auth-resend-button . "Lähetä aktivointisähköposti uudelleen")
 (:auth-resend-success . "Aktivointisähköposti lähetetty!")
 (:auth-resend-success-detail . "Tarkista postilaatikkosi uuden aktivointilinkin saamiseksi.")
 (:auth-resend-rate-limited . "Odota muutama minuutti ennen kuin pyydät uutta aktivointisähköpostia.")
 (:auth-resend-cooldown . "Voit pyytää uuden sähköpostin ~a sekunnin kuluttua.")
 (:auth-back-to-login . "Takaisin kirjautumiseen")
 (:auth-forgot-password-title . "Unohtunut salasana")
 (:auth-forgot-password-subtitle . "Anna sähköpostiosoitteesi ja lähetämme sinulle linkin salasanan vaihtamiseen.")
 (:auth-send-reset-link . "Lähetä nollauslinkki")
 (:auth-reset-email-sent . "Linkki lähetetty!")
 (:auth-reset-email-sent-detail . "Jos tällä sähköpostiosoitteella on tili, saat pian salasanan nollauslinkin.")
 (:auth-reset-rate-limited . "Odota muutama minuutti ennen kuin pyydät uutta salasanan nollausta.")
 (:auth-reset-invalid-token . "Tämä salasanan nollauslinkki on virheellinen tai vanhentunut.")
 (:auth-reset-password-title . "Nollaa salasana")
 (:auth-reset-password-subtitle . "Syötä uusi salasanasi alle.")
 (:auth-new-password . "Uusi salasana")
 (:auth-confirm-new-password . "Vahvista uusi salasana")
 (:auth-reset-password . "Nollaa salasana")
 (:auth-password-changed . "Salasana vaihdettu!")
 (:auth-password-changed-detail . "Salasanasi on vaihdettu onnistuneesti. Voit nyt kirjautua sisään uudella salasanallasi.")
 (:auth-change-password-title . "Vaihda salasana")
 (:auth-change-password-subtitle . "Päivitä tilisi salasana.")
 (:auth-current-password . "Nykyinen salasana")
 (:auth-change-password . "Vaihda salasana")
 (:auth-back-to-app . "Takaisin sovellukseen")
 (:auth-password-updated . "Salasana päivitetty!")
 (:auth-password-updated-detail . "Salasanasi on päivitetty onnistuneesti.")

 ;; Translation page
 (:translate-title . "Käännä")
 (:translate-input-label . "Käännettävä teksti")
 (:translate-input-placeholder . "Kirjoita käännettävä teksti...")
 (:translate-from . "Mistä:")
 (:translate-to . "Mihin:")
 (:translate-submit . "Käännä")
 (:translate-save . "Tallenna muistikortteihin")
 (:translate-saved . "Tallennettu!")
 (:translate-like . "Tykkää")
 (:translate-dislike . "En tykkää")
 (:translate-char-limit . "merkkiä jäljellä")
 (:translate-auto-detect . "Mikä tahansa (tunnista automaattisesti)")
 (:translate-empty-state . "Kirjoita teksti yllä ja napsauta Käännä nähdäksesi tuloksen kielioppiselityksineen")
 (:translate-select-deck-placeholder . "Valitse pakka (valinnainen)")
 (:translate-new-deck . "Uusi pakka")
 (:translate-add-to-deck . "Lisää pakkaan")
 (:translate-bookmark . "Tallenna")
 (:translate-bookmarked . "Tallennettu")
 (:translate-retry . "Yritä uudelleen")
 (:translate-like-tooltip . "Hyvä käännös")
 (:translate-dislike-tooltip . "Huono käännös - pyydä uusi")
 (:translate-dislike-confirm . "Tämä luo uuden käännöksen. Jatketaanko?")
 (:translate-liked . "Tykätty!")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Kohde")
 (:translate-deck-create-title . "Luo uusi pakka")
 (:translate-deck-name-label . "Pakan nimi")
 (:translate-deck-name-placeholder . "esim. Suomen perusteet")
 (:translate-deck-description-label . "Kuvaus (valinnainen)")
 (:translate-deck-cancel . "Peruuta")
 (:translate-deck-create . "Luo")
 (:translate-rate-label . "Arvioi käännös")
 (:flashcards-delete-confirm . "Haluatko varmasti poistaa tämän kortin?")
 (:flashcards-deck-search-placeholder . "Hae pakkoja...")
 (:flashcards-no-decks . "Ei vielä pakkoja. Luo ensin yksi!")
 (:flashcards-deck-cancel . "Peruuta")

 ;; Flashcard review
 (:review-title . "Kertaus")
 (:review-session-title . "Kertausjakso")
 (:review-session-subtitle . "Harjoittele tallennettuja muistikorttejasi")
 (:review-selector-title . "Valitse, mitä kertaat")
 (:review-selector-subtitle . "Valitse pakka tai kielipari, johon haluat keskittyä tässä kertausjaksossa.")
 (:review-by-deck . "Kertaa pakan mukaan")
 (:review-by-language-pair . "Kertaa kieliparin mukaan")
 (:review-all-cards . "Kertaa kaikki kortit")

 (:review-start . "Aloita kertaus")
 (:review-no-cards . "Ei kerattavia kortteja")
 (:review-no-cards-desc . "Sinulla ei ole muistikortteja kerattavana juuri nyt.")
 (:review-no-cards-hint . "Käännä tekstiä ja napsauta \"Tallenna muistikortteihin\" rakentaaksesi pakkasi!")
 (:review-start-translating . "Aloita kääntäminen")
 (:review-show-answer . "Näytä vastaus")
 (:review-click-reveal . "Napsauta paljastaaksesi vastauksen")
 (:review-grammar-breakdown . "Kielioppiselitys")
 (:review-how-well . "Kuinka hyvin muistit?")
 (:review-again . "Uudelleen")
 (:review-hard . "Vaikea")
 (:review-good . "Hyvä")
 (:review-easy . "Helppo")
 (:review-progress . "Kortti ~a/~a")
 (:review-complete . "Kertaus valmis!")
 (:review-complete-msg . "Kertasit ~a korttia")
 (:review-correct . "Oikein")
 (:review-accuracy . "Tarkkuus")
 (:review-again-btn . "Kertaa uudelleen")
 (:review-translate-more . "Käännä lisää")
 (:review-streak . "päivän putki")

 ;; Dashboard
 (:dashboard-title . "Hallintapaneeli")
 (:dashboard-cards-due . "Kerattavat kortit")
 (:dashboard-total-cards . "Kortit yhteensä")
 (:dashboard-subscription . "Tilaus")
 (:dashboard-subscribed-until . "Tilattu asti")
 (:dashboard-not-subscribed . "Ei tilausta")
 (:dashboard-recent . "Viimeaikaiset käännökset")
 (:dashboard-no-translations . "Ei käännöksiä vielä")
 (:dashboard-streak . "Kertausputki")
 (:dashboard-days . "päivää")
 (:dashboard-quick-actions . "Pikatoiminnot")
 (:dashboard-getting-started . "Näin pääset alkuun")
 (:dashboard-tip-1 . "Käännä tekstiä, jonka haluat oppia")
 (:dashboard-tip-2 . "Napsauta \"Tallenna muistikortteihin\" käännöksissä, jotka haluat muistaa")
 (:dashboard-tip-3 . "Kertaa muistikorttisi säännöllisesti - hajautettu toisto auttaa muistamaan pitkäaikaisesti")
 (:dashboard-tip-4 . "Arvioi rehellisesti - se auttaa algoritmia ajoittamaan kertauksesi optimaalisesti")

 ;; Account
 (:account-title . "Tili")
 (:account-subtitle . "Hallitse tilin asetuksia ja poistamisaikataulua.")
 (:account-deletion-title . "Tilin poisto")
 (:account-deletion-scheduled . "Tilisi on ajastettu poistettavaksi päivänä ~A.")
 (:account-deletion-cancel-hint . "Voit perua ennen tätä päivää ja pitää tilisi.")
 (:account-deletion-cancel . "Peru poisto")
 (:account-deletion-request . "Voit pyytää tilin poistamista milloin tahansa. Poisto ajoitetaan 14 päivän päähän vahvistuksesta. Jos muutat mieltäsi poiston jälkeen, ota yhteyttä tukeen.")
 (:account-deletion-confirm . "Ajastetaanko tilin poisto 14 päivän päähän tästä päivästä?")
 (:account-deletion-schedule . "Ajasta poisto")
 (:account-reminders-title . "Sähköpostimuistutukset")
 (:account-reminders-subtitle . "Hallitse tämän tilin kertaamisen ja jatkamisen muistutuksia.")
 (:account-reminders-opt-out . "Poista kertaamis- ja jatkomuistutukset käytöstä")
 (:account-reminders-save . "Tallenna asetukset")

 ;; Subscription
 (:subscribe-title . "Selkeä hinnoittelu")
 (:subscribe-choose-plan . "Valitse tilauksesi")
 (:subscribe-start-today . "Aloita oppiminen tänään 7 päivän ilmaisella kokeilulla")
 (:subscribe-monthly . "Kuukausittain")
 (:subscribe-annual . "Vuosittain")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/kk")
 (:subscribe-per-year . "/vuosi")
 (:subscribe-monthly-desc . "600 käännöstä kuukaudessa")
 (:subscribe-unlimited-flashcards . "Rajattomat muistikortit")
 (:subscribe-grammar-explanations . "Kielioppiselitykset")
 (:subscribe-spaced-repetition . "Hajautettu toisto")
 (:subscribe-annual-desc . "Säästä 20 € — kaksi kuukautta ilmaiseksi!")
 (:subscribe-cta . "Tilaa")
 (:subscribe-success . "Tilaus onnistui!")
 (:subscribe-manage . "Hallitse tilausta")
 (:subscribe-activated . "Tilaus aktivoitu!")
 (:subscribe-thank-you . "Kiitos tilauksesta. Tilisi on nyt aktiivinen.")
 (:subscribe-start-learning . "Aloita oppiminen")
 (:subscribe-management . "Tilauksen hallinta")
 (:subscribe-active . "Aktiivinen tilaus")
 (:subscribe-status . "Tila:")
 (:subscribe-status-active . "Aktiivinen")
 (:subscribe-days-remaining . "Päiviä jäljellä:")
 (:subscribe-renews-on . "Uusiutuu:")
 (:subscribe-no-subscription . "Ei aktiivista tilausta")
 (:subscribe-access-features . "Tilaa saadaksesi kaikki ominaisuudet käyttöösi.")
 (:subscribe-view-plans . "Näytä tilausvaihtoehdot")
 (:subscribe-faq-title . "Usein kysytyt kysymykset")
 (:subscribe-faq-trial-q . "Mitä tapahtuu ilmaisen kokeilun jälkeen?")
 (:subscribe-faq-trial-a . "7 päivän ilmaisen kokeilun jälkeen sinulta veloitetaan valitsemasi tilaus. Voit peruuttaa milloin tahansa ennen kokeilun päättymistä.")
 (:subscribe-faq-cancel-q . "Voinko peruuttaa milloin tahansa?")
 (:subscribe-faq-cancel-a . "Kyllä! Voit peruuttaa tilauksesi milloin tahansa. Pääsy säilyy laskutuskauden loppuun asti.")
 (:subscribe-faq-payment-q . "Mitä maksutapoja hyväksytte?")
 (:subscribe-faq-payment-a . "Hyväksymme kaikki yleisimmät luotto- ja pankkikortit maksukumppanimme Polar.sh:n kautta.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Jokin meni pieleen")
 (:error-not-found . "Sivua ei löytynyt")
 (:error-unauthorized . "Kirjaudu jatkaaksesi")
 (:error-subscription-required . "Tilaus vaaditaan")
 (:error-text-too-long . "Teksti on liian pitkä. Käännöksen enimmäispituus on 120 merkkiä.")
 (:error-input-too-long . "Syöte liian pitkä")
 (:error-unknown-source-lang . "Valitsemaasi lähdekieltä ei tueta.")
 (:error-unknown-target-lang . "Valitsemaasi kohdekieltä ei tueta.")
 (:error-unknown-language . "Tuntematon kieli")
 (:error-translation-unavailable . "Käännöspalvelu ei ole tilapäisesti käytettävissä. Yritä hetken kuluttua uudelleen.")
 (:error-translation-failed . "Käännös epäonnistui")
 (:error-translation-retry . "Käännöstä ei voitu luoda useiden yritysten jälkeen. Yritä muotoilla tekstisi toisin.")
 (:error-quota-exceeded . "Käännösraja saavutettu")
 (:error-quota-exceeded-detail . "Olet käyttänyt kaikki käännöksesi tälle kuukaudelle. Kiintiösi nollautuu automaattisesti joka kuukausi.")
 (:quota-warning . "Jäljellä olevat käännökset: ~A")
 (:quota-low-warning . "Vain ~A käännöstä jäljellä. Harkitse lisää ostamista.")
 (:top-up-button . "Osta lisää käännöksiä")
 (:top-up-success . "Lataus onnistui! Sinulla on nyt ~A lisäännöstä.")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 käännöstä")
 (:loading . "Ladataan...")
 (:empty-state . "Ei vielä mitään täällä")

 ;; Institutions
 (:institutions-page-title . "Hiisi kouluille - oppilaitoslisenssit")
 (:institutions-hero-title . "Hiisi kouluille")
 (:institutions-hero-subtitle . "Vahvista opiskelijoitasi tekoälyavusteisella kieltenopiskelulla")
 (:institutions-section-title . "Oppilaitoslisenssit")
 (:institutions-section-body . "Tarjoamme volyymilisenssejä kouluille, yliopistoille ja kielioppilaitoksille. Oppilaat, joiden sähköpostiosoite on organisaatiosi domainissa, saavat automaattisesti täyden käyttöoikeuden.")
 (:institutions-benefit-1 . "Automaattinen käyttöönotto oppilaille, joilla on oppilaitossähköposti")
 (:institutions-benefit-2 . "Ei yksittäisiä oppilastilejä hallittavaksi")
 (:institutions-benefit-3 . "Joustavat laskutusvaihtoehdot")
 (:institutions-benefit-4 . "Omistautunut tuki opettajille")
 (:institutions-request-title . "Pyydä lisenssiä")
 (:institutions-request-subtitle . "Täytä alla oleva lomake ja palaamme asiaan 2 arkipäivän kuluessa.")
 (:institutions-field-name . "Oppilaitoksen nimi")
 (:institutions-field-name-placeholder . "Helsingin yliopisto")
 (:institutions-field-contact-name . "Yhteyshenkilön nimi")
 (:institutions-field-contact-name-placeholder . "Nimesi")
 (:institutions-field-contact-email . "Yhteyssähköposti")
 (:institutions-field-contact-email-placeholder . "sina@yliopisto.fi")
 (:institutions-field-domains . "Sähköpostidomainit")
 (:institutions-field-domains-placeholder . "yliopisto.fi, cs.yliopisto.fi")
 (:institutions-field-domains-help . "Pilkulla erotettu luettelo oppilaitoksesi sähköpostidomaineista")
 (:institutions-field-notes . "Lisätiedot")
 (:institutions-field-notes-placeholder . "Arvioitu opiskelijamäärä, toivottu laskutuskausi, erityisvaatimukset...")
 (:institutions-submit . "Lähetä tiedustelu")
 (:institutions-success-title . "Kiitos - Hiisi kouluille")
 (:institutions-success-heading . "Kiitos!")
 (:institutions-success-body . "Olemme vastaanottaneet oppilaitoslisenssikyselysi. Tiimimme käsittelee sen ja palaa asiaan 2 arkipäivän kuluessa.")
 (:institutions-success-back . "Takaisin etusivulle")

 ;; Footer
 (:footer-privacy . "Tietosuojakäytäntö")
 (:footer-terms . "Käyttöehdot")
 (:footer-contact . "Yhteystiedot")

 ;; Early software notice
 (:early-software-notice . "Hiisi on varhaisessa kehitysvaiheessa. Löysitkö virheen tai onko sinulla ehdotus?")
 (:early-software-contact . "Ota yhteyttä osoitteessa")

 ;; Privacy Policy
 (:privacy-title . "Privacy Policy")
 (:privacy-updated . "Last updated: January 2026")
 (:privacy-who-title . "Who We Are")
 (:privacy-who-body . "Hiisi is operated by Lambda Symbolics OÜ, a company registered in Estonia. As an Estonian company, we comply with the European Union's General Data Protection Regulation (GDPR).")
 (:privacy-collect-title . "Data We Collect")
 (:privacy-collect-intro . "We collect the following information when you use Hiisi:")
 (:privacy-collect-account-key . "Account information: ")
 (:privacy-collect-account-val . "Email address, display name, and a securely hashed password.")
 (:privacy-collect-learning-key . "Learning data: ")
 (:privacy-collect-learning-val . "Your translations, saved flashcards, and review history.")
 (:privacy-collect-usage-key . "Usage data: ")
 (:privacy-collect-usage-val . "Basic server logs for security and debugging purposes.")
 (:privacy-use-title . "How We Use Your Data")
 (:privacy-use-auth-key . "Authentication: ")
 (:privacy-use-auth-val . "To verify your identity and secure your account.")
 (:privacy-use-service-key . "Service delivery: ")
 (:privacy-use-service-val . "To provide translations and manage your flashcard collection.")
 (:privacy-use-ai-key . "AI translations: ")
 (:privacy-use-ai-val . "Your translation requests are sent to Anthropic's Claude API to generate responses. See Anthropic's privacy policy for how they handle this data.")
 (:privacy-third-title . "Third-Party Services")
 (:privacy-third-intro . "We use the following third-party services:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "For AI-powered translations.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "For sending account activation and transactional emails.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "For subscription payment processing.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "We use only essential cookies:")
 (:privacy-cookies-auth-key . "Authentication token: ")
 (:privacy-cookies-auth-val . "A secure, HTTP-only cookie to keep you logged in.")
 (:privacy-cookies-lang-key . "Language preference: ")
 (:privacy-cookies-lang-val . "To remember your preferred UI language.")
 (:privacy-retention-title . "Data Retention")
 (:privacy-retention-body . "Your data is stored as long as you maintain an account. When you request deletion, your account is scheduled for deletion in 14 days.")
 (:privacy-rights-title . "Your Rights (GDPR)")
 (:privacy-rights-intro . "Under GDPR, you have the right to:")
 (:privacy-rights-access . "Access your personal data")
 (:privacy-rights-export . "Export your data (available at /app/api/export)")
 (:privacy-rights-correct . "Request correction of inaccurate data")
 (:privacy-rights-delete . "Request deletion of your account and data")
 (:privacy-rights-object . "Object to processing of your data")
 (:privacy-rights-contact . "To exercise these rights, contact us at")
 (:privacy-contact-title . "Contact")
 (:privacy-contact-intro . "For privacy-related inquiries:")
 (:privacy-contact-email-label . "Email: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Estonia")

 ;; Terms of Service
 (:terms-title . "Terms of Service")
 (:terms-updated . "Last updated: January 2026")
 (:terms-1-title . "1. Service Description")
 (:terms-1-body . "Hiisi is a language learning application that provides AI-powered translations with grammatical explanations and spaced repetition flashcards. The service is operated by Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Account Registration")
 (:terms-2-body . "To use Hiisi, you must create an account with a valid email address. You are responsible for maintaining the security of your account credentials.")
 (:terms-3-title . "3. Subscription and Payments")
 (:terms-3-body . "Hiisi offers paid subscription plans (monthly and annual). Subscriptions are processed through Polar.sh.")
 (:terms-3-list-1 . "Subscriptions auto-renew unless cancelled before the renewal date.")
 (:terms-3-list-2 . "Refunds are provided in accordance with applicable consumer protection laws.")
 (:terms-3-list-3 . "Non-payment results in loss of access to premium features.")
 (:terms-4-title . "4. Acceptable Use")
 (:terms-4-intro . "You agree not to:")
 (:terms-4-list-1 . "Use the service for any illegal purpose")
 (:terms-4-list-2 . "Attempt to circumvent usage limits or security measures")
 (:terms-4-list-3 . "Share your account credentials with others")
 (:terms-4-list-4 . "Use automated tools to access the service in a way that degrades performance for others")
 (:terms-5-title . "5. Content and Intellectual Property")
 (:terms-5-body-1 . "Translations generated by Hiisi are created using AI and may not be unique. You may use your translations and flashcards for any personal purpose, but you do not hold exclusive authorship rights over AI-generated content.")
 (:terms-5-body-2 . "The Hiisi application, branding, and original content remain the property of Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Service Availability")
 (:terms-6-intro . "Hiisi is provided on an \"as-is\" basis. We do not guarantee:")
 (:terms-6-list-1 . "Uninterrupted or error-free service")
 (:terms-6-list-2 . "Accuracy of AI-generated translations")
 (:terms-6-list-3 . "Availability of specific features")
 (:terms-6-body . "We may modify or discontinue features at any time.")
 (:terms-7-title . "7. Limitation of Liability")
 (:terms-7-body-1 . "To the maximum extent permitted by law, Lambda Symbolics OÜ shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of Hiisi.")
 (:terms-7-body-2 . "Our total liability shall not exceed the amount you paid for the service in the 12 months preceding the claim.")
 (:terms-8-title . "8. Account Termination")
 (:terms-8-body-1 . "We may suspend or terminate your account if you violate these terms. You may request account deletion at any time through the application.")
 (:terms-8-body-2 . "Upon deletion request, your account is scheduled for deletion in 14 days.")
 (:terms-9-title . "9. Changes to Terms")
 (:terms-9-body . "We may update these terms from time to time. Continued use of Hiisi after changes constitutes acceptance of the new terms.")
 (:terms-10-title . "10. Governing Law")
 (:terms-10-body . "These terms are governed by the laws of Estonia. Any disputes shall be resolved in the courts of Estonia.")
 (:terms-contact-title . "Contact")
 (:terms-contact-intro . "For questions about these terms:")
 (:terms-contact-email-label . "Email: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Estonia")



 ;; Decks
 (:decks-title . "Pakkat")
 (:decks-subtitle . "Luo omia pakkoja ja jaa niitä muiden kanssa.")
 (:decks-create-title . "Luo pakka")
 (:decks-name-placeholder . "Pakan nimi")
 (:decks-desc-placeholder . "Kuvaus")
 (:decks-create-btn . "Luo pakka")
 (:decks-your-title . "Omat pakkat")
 (:decks-col-name . "Nimi")
 (:decks-col-desc . "Kuvaus")
 (:decks-col-updated . "Päivitetty")
 (:decks-col-actions . "Toiminnot")
 (:decks-no-decks . "Ei vielä pakkoja.")
 (:decks-open-btn . "Avaa")
 (:decks-no-desc . "Ei kuvausta.")
 (:decks-share-title . "Jakolinkki")
 (:decks-share-info . "Kuka tahansa voi tuoda pakan tällä linkillä:")
 (:decks-share-copy . "Kopioi linkki")
 (:decks-share-copied . "Kopioitu")
 (:decks-add-from-flashcards-title . "Lisää käännöksiä")
 (:decks-add-from-flashcards-info . "Valitse kortti ja lisää sen käännös tähän pakkaan.")
 (:decks-open-flashcards . "Lisää korteista")
 (:decks-filter-from . "Lähdekieli")
 (:decks-filter-to . "Kohdekieli")
 (:decks-filter-any . "Mikä tahansa kieli")
 (:decks-filter-include-assigned . "Näytä myös kortit, jotka ovat jo pakassa")
 (:decks-flashcards-col-from . "Lähde")
 (:decks-flashcards-col-to . "Kohde")
 (:decks-flashcards-add . "Lisää")
 (:decks-flashcards-added . "Lisätty")
 (:decks-flashcards-in-deck . "Toisessa pakassa")
 (:decks-flashcards-empty . "Yksikään kortti ei vastaa näitä suodattimia.")
 (:decks-add-trans-title . "Lisää käännös")
 (:decks-trans-id-placeholder . "Käännöksen ID")
 (:decks-add-trans-btn . "Lisää käännös")
 (:decks-items-title . "Pakan sisältö")
 (:decks-col-original . "Alkuperäinen")
 (:decks-col-translated . "Käännös")
 (:decks-col-lang . "Kohdekieli")
 (:decks-no-items . "Ei vielä sisältöä.")
 (:decks-share-page-title . "Jaa pakka")
 (:decks-share-preview . "Esikatsele ja tuo tämä pakka.")
 (:decks-import-title . "Tuo")
 (:decks-import-btn . "Tuo pakka")

 ;; Flashcards management page
 (:flashcards-title . "Korttini")
 (:flashcards-subtitle . "Kaikki tallennetut korttisi yhdessä paikassa. Hae, järjestä ja hallitse.")
 (:flashcards-search-placeholder . "Hae kortteja...")
 (:flashcards-col-original . "Alkuperäinen")
 (:flashcards-col-translated . "Käännös")
 (:flashcards-col-lang . "Kielet")
 (:flashcards-no-cards . "Ei vielä kortteja. Aloita kääntäminen luodaksesi niitä!")

 ;; API Errors (EN fallback)
 (:api-error-missing-text . "Missing text to translate.")
 (:api-error-invalid-translation-id . "Invalid translation ID.")
 (:api-error-translation-not-found . "The translation you tried to save no longer exists.")
 (:api-error-invalid-bookmark-id . "Invalid bookmark ID")
 (:api-error-bookmark-not-found . "Bookmark not found")
 (:api-error-forbidden . "Forbidden")
 (:api-error-failed-delete-bookmark . "Failed to delete bookmark")
 (:api-error-invalid-flashcard-id . "Invalid flashcard ID")
 (:api-error-missing-deck-id . "Missing deck_id")
 (:api-error-flashcard-not-found . "Flashcard not found")
 (:api-error-deck-not-found . "Deck not found")
 (:api-error-deck-name-required . "Deck name is required")
 (:api-error-session-expired . "Your review session has expired. Please start a new session.")
 (:api-error-invalid-card-id . "Invalid card ID.")
 (:api-error-invalid-rating . "Invalid rating.")
 (:api-error-rating-range . "Rating must be between 0 and 5.")
 (:api-error-card-not-found . "Card not found.")
 (:api-error-permission-denied . "You don't have permission to review this card.")
 (:api-error-unknown-source-lang . "Unknown source language.")
 (:api-error-unknown-target-lang . "Unknown target language.")
 (:api-error-failed-add-to-deck . "Failed to add to deck")

 ;; API Success messages
 (:api-success-added . "Added!")
 (:api-success-added-simple . "Added")

 ;; API Stats
 (:api-stats-due . "~A due")
 (:api-stats-total . "~A total")

 ;; Time units
 (:api-time-day . "day")
 (:api-time-days . "days")
 (:api-time-day-left . "day left")
 (:api-time-days-left . "days left")

 ;; Subscription status
 (:api-subscription-active . "Active")
 (:api-subscription-inactive . "Inactive")
 (:api-subscription-subscribe-hint . "Subscribe to unlock translations")

 ;; Generic status
 (:status-bad-request . "Bad Request")
 (:status-not-found . "Not Found")
 (:status-forbidden . "Forbidden")

)
