;;; Finnish translations

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Suomi")
 (:lang-flag . "🇫🇮")

 ;; Navigation
 (:nav-translate . "Käännä")
 (:nav-review . "Kertaa")
 (:nav-dashboard . "Hallintapaneeli")
 (:nav-logout . "Kirjaudu ulos")
 (:nav-home . "Etusivu")
 (:nav-pricing . "Hinnoittelu")
 (:nav-export-data . "Vie tiedot")

 ;; App title and branding
 (:app-title . "Hiisi")
 (:app-tagline . "Opi kieliä käännösten avulla")

 ;; Landing page
 (:landing-hero-title . "Hallitse mikä tahansa kieli")
 (:landing-hero-subtitle . "Käännä mitä tahansa. Luo automaattisesti muistikortit, jotka opettavat sinulle miksi se toimii niin.")
 (:landing-cta . "Aloita oppiminen")
 (:landing-learn-more . "Lue lisää")
 (:landing-how-it-works . "Näin se toimii")
 (:landing-feature-1-title . "Automaattiset muistikortit")
 (:landing-feature-1-desc . "Jokainen käännös luo automaattisesti muistikortit kielioppiselityksineen. Ei manuaalista korttien luomista.")
 (:landing-feature-2-title . "Hajautettu toisto")
 (:landing-feature-2-desc . "SM-2-algoritmi ajoittaa kertaukset optimaalisesti. Opi tehokkaasti, muista pysyvästi.")
 (:landing-feature-3-title . "Kieliopin opetus")
 (:landing-feature-3-desc . "Jokainen käännös selittää kieliopin, sanojen juuret ja lauserakenteen. Ymmärrä miksi, älä vain mitä.")
 (:landing-free-trial . "7 päivän ilmainen kokeilu. Luottokorttia ei tarvita.")
 (:landing-start-trial . "Aloita ilmainen kokeilu")
 (:landing-best-value . "Paras arvo")
 (:landing-cta-title . "Valmis oppimaan kieliä kieliopin, ei ulkoa opettelun, kautta?")
 (:landing-cta-subtitle . "Jokainen käännös on oppimismahdollisuus. Jokainen muistikortti opettaa sinulle miksi.")
 (:landing-signup-free . "Rekisteröidy ilmaiseksi")

 ;; Auth pages
 (:auth-register . "Rekisteröidy")
 (:auth-login . "Kirjaudu")
 (:auth-logout . "Kirjaudu ulos")
 (:auth-email . "Sähköposti")
 (:auth-password . "Salasana")
 (:auth-password-again . "Vahvista salasana")
 (:auth-display-name . "Näyttönimi")
 (:auth-register-title . "Rekisteröidy Hiisiin")
 (:auth-register-subtitle . "Luo uusi tili")
 (:auth-login-title . "Kirjaudu Hiisiin")
 (:auth-login-subtitle . "Syötä tunnuksesi")
 (:auth-forgot-password . "Unohditko salasanan?")
 (:auth-no-account . "Eikö sinulla ole tiliä?")
 (:auth-have-account . "Onko sinulla jo tili?")

 ;; Translation page
 (:translate-title . "Käännä")
 (:translate-input-label . "Käännettävä teksti")
 (:translate-input-placeholder . "Kirjoita käännettävä teksti...")
 (:translate-from . "Mistä:")
 (:translate-to . "Mihin:")
 (:translate-submit . "Käännä")
 (:translate-save . "Tallenna muistikortteihin")
 (:translate-saved . "Tallennettu!")
 (:translate-like . "Tykkää")
 (:translate-dislike . "En tykkää")
 (:translate-char-limit . "merkkiä jäljellä")
 (:translate-auto-detect . "Mikä tahansa (tunnista automaattisesti)")
 (:translate-empty-state . "Kirjoita teksti yllä ja napsauta Käännä nähdäksesi tuloksen kielioppiselityksineen")

 ;; Flashcard review
 (:review-title . "Kertaus")
 (:review-session-title . "Kertausjakso")
 (:review-session-subtitle . "Harjoittele tallennettuja muistikorttejasi")
 (:review-start . "Aloita kertaus")
 (:review-no-cards . "Ei kerattavia kortteja")
 (:review-no-cards-desc . "Sinulla ei ole muistikortteja kerattavana juuri nyt.")
 (:review-no-cards-hint . "Käännä tekstiä ja napsauta \"Tallenna muistikortteihin\" rakentaaksesi pakkasi!")
 (:review-start-translating . "Aloita kääntäminen")
 (:review-show-answer . "Näytä vastaus")
 (:review-click-reveal . "Napsauta paljastaaksesi vastauksen")
 (:review-grammar-breakdown . "Kielioppiselitys")
 (:review-how-well . "Kuinka hyvin muistit?")
 (:review-again . "Uudelleen")
 (:review-hard . "Vaikea")
 (:review-good . "Hyvä")
 (:review-easy . "Helppo")
 (:review-progress . "Kortti ~a/~a")
 (:review-complete . "Kertaus valmis!")
 (:review-complete-msg . "Kertasit ~a korttia")
 (:review-correct . "Oikein")
 (:review-accuracy . "Tarkkuus")
 (:review-again-btn . "Kertaa uudelleen")
 (:review-translate-more . "Käännä lisää")
 (:review-streak . "päivän putki")

 ;; Dashboard
 (:dashboard-title . "Hallintapaneeli")
 (:dashboard-cards-due . "Kerattavat kortit")
 (:dashboard-total-cards . "Kortit yhteensä")
 (:dashboard-subscription . "Tilaus")
 (:dashboard-subscribed-until . "Tilattu asti")
 (:dashboard-not-subscribed . "Ei tilausta")
 (:dashboard-recent . "Viimeaikaiset käännökset")
 (:dashboard-no-translations . "Ei käännöksiä vielä")
 (:dashboard-streak . "Kertausputki")
 (:dashboard-days . "päivää")
 (:dashboard-quick-actions . "Pikatoiminnot")
 (:dashboard-getting-started . "Näin pääset alkuun")
 (:dashboard-tip-1 . "Käännä tekstiä, jonka haluat oppia")
 (:dashboard-tip-2 . "Napsauta \"Tallenna muistikortteihin\" käännöksissä, jotka haluat muistaa")
 (:dashboard-tip-3 . "Kertaa muistikorttisi säännöllisesti - hajautettu toisto auttaa muistamaan pitkäaikaisesti")
 (:dashboard-tip-4 . "Arvioi rehellisesti - se auttaa algoritmia ajoittamaan kertauksesi optimaalisesti")

 ;; Subscription
 (:subscribe-title . "Selkeä hinnoittelu")
 (:subscribe-monthly . "Kuukausittain")
 (:subscribe-annual . "Vuosittain")
 (:subscribe-monthly-price . "10 €/kk")
 (:subscribe-annual-price . "100 €/vuosi")
 (:subscribe-monthly-desc . "600 käännöstä kuukaudessa")
 (:subscribe-annual-desc . "Säästä 20 € — kaksi kuukautta ilmaiseksi!")
 (:subscribe-cta . "Tilaa")
 (:subscribe-success . "Tilaus onnistui!")
 (:subscribe-manage . "Hallitse tilausta")

 ;; Errors and status
 (:error-generic . "Jokin meni pieleen")
 (:error-not-found . "Sivua ei löytynyt")
 (:error-unauthorized . "Kirjaudu jatkaaksesi")
 (:error-subscription-required . "Tilaus vaaditaan")
 (:error-text-too-long . "Teksti on liian pitkä. Käännöksen enimmäispituus on 120 merkkiä.")
 (:error-input-too-long . "Syöte liian pitkä")
 (:error-unknown-source-lang . "Valitsemaasi lähdekieltä ei tueta.")
 (:error-unknown-target-lang . "Valitsemaasi kohdekieltä ei tueta.")
 (:error-unknown-language . "Tuntematon kieli")
 (:error-translation-unavailable . "Käännöspalvelu ei ole tilapäisesti käytettävissä. Yritä hetken kuluttua uudelleen.")
 (:error-translation-failed . "Käännös epäonnistui")
 (:error-translation-retry . "Käännöstä ei voitu luoda useiden yritysten jälkeen. Yritä muotoilla tekstisi toisin.")
 (:loading . "Ladataan...")
 (:empty-state . "Ei vielä mitään täällä")

 ;; Footer
 (:footer-privacy . "Tietosuojakäytäntö")
 (:footer-terms . "Käyttöehdot")
 (:footer-contact . "Yhteystiedot")
)
