;;; Italian translations
;;; This file should contain all keys from en.lisp

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Italiano")
 (:lang-flag . "🇮🇹")

 ;; Navigation
 (:nav-translate . "Traduci")
 (:nav-review . "Ripassa")
 (:nav-dashboard . "Dashboard")
 (:nav-logout . "Esci")
 (:nav-home . "Home")
 (:nav-pricing . "Prezzi")
 (:nav-export-data . "Esporta dati")

 ;; App title and branding
 (:app-title . "Hiisi")
 (:app-tagline . "Impara le lingue attraverso le traduzioni")

 ;; Landing page
 (:landing-hero-title . "Padroneggia qualsiasi lingua")
 (:landing-hero-subtitle . "Traduci qualsiasi cosa. Genera automaticamente flashcard che ti insegnano perché funziona così.")
 (:landing-cta . "Inizia a imparare")
 (:landing-learn-more . "Scopri di più")
 (:landing-how-it-works . "Come funziona")
 (:landing-feature-1-title . "Flashcard automatiche")
 (:landing-feature-1-desc . "Ogni traduzione genera automaticamente flashcard con analisi grammaticale. Nessuna creazione manuale.")
 (:landing-feature-2-title . "Ripetizione spaziata")
 (:landing-feature-2-desc . "L'algoritmo SM-2 pianifica i ripassi a intervalli ottimali. Impara in modo efficiente, ricorda per sempre.")
 (:landing-feature-3-title . "Insegnamento grammaticale")
 (:landing-feature-3-desc . "Ogni traduzione spiega grammatica, radici delle parole e struttura della frase. Capisci il perché, non solo il cosa.")
 (:landing-free-trial . "7 giorni di prova gratuita. Nessuna carta di credito richiesta.")
 (:landing-start-trial . "Inizia la prova gratuita")
 (:landing-best-value . "Miglior valore")
 (:landing-cta-title . "Pronto a imparare le lingue attraverso la grammatica, non la memorizzazione?")
 (:landing-cta-subtitle . "Ogni traduzione diventa un'opportunità di apprendimento. Ogni flashcard ti insegna il perché.")
 (:landing-signup-free . "Registrati gratis")

 ;; Auth pages
 (:auth-register . "Registrati")
 (:auth-login . "Accedi")
 (:auth-logout . "Esci")
 (:auth-email . "Email")
 (:auth-password . "Password")
 (:auth-password-again . "Conferma password")
 (:auth-display-name . "Nome visualizzato")
 (:auth-register-title . "Registrati su Hiisi")
 (:auth-register-subtitle . "Crea un nuovo account")
 (:auth-login-title . "Accedi a Hiisi")
 (:auth-login-subtitle . "Inserisci le tue credenziali")
 (:auth-forgot-password . "Password dimenticata?")
 (:auth-no-account . "Non hai un account?")
 (:auth-have-account . "Hai già un account?")

 ;; Translation page
 (:translate-title . "Traduci")
 (:translate-input-label . "Testo da tradurre")
 (:translate-input-placeholder . "Inserisci il testo da tradurre...")
 (:translate-from . "Da:")
 (:translate-to . "A:")
 (:translate-submit . "Traduci")
 (:translate-save . "Salva nelle flashcard")
 (:translate-saved . "Salvato!")
 (:translate-like . "Mi piace")
 (:translate-dislike . "Non mi piace")
 (:translate-char-limit . "caratteri rimanenti")
 (:translate-auto-detect . "Qualsiasi (Rilevamento automatico)")
 (:translate-empty-state . "Inserisci il testo sopra e clicca Traduci per vedere il risultato con l'analisi grammaticale")

 ;; Flashcard review
 (:review-title . "Ripassa")
 (:review-session-title . "Sessione di ripasso")
 (:review-session-subtitle . "Esercitati con le tue flashcard salvate")
 (:review-start . "Inizia il ripasso")
 (:review-no-cards . "Nessuna carta da ripassare")
 (:review-no-cards-desc . "Non hai flashcard da ripassare in questo momento.")
 (:review-no-cards-hint . "Traduci del testo e clicca \"Salva nelle flashcard\" per costruire il tuo mazzo!")
 (:review-start-translating . "Inizia a tradurre")
 (:review-show-answer . "Mostra risposta")
 (:review-click-reveal . "Clicca per rivelare la risposta")
 (:review-grammar-breakdown . "Analisi grammaticale")
 (:review-how-well . "Quanto bene l'hai ricordato?")
 (:review-again . "Ancora")
 (:review-hard . "Difficile")
 (:review-good . "Bene")
 (:review-easy . "Facile")
 (:review-progress . "Carta ~a di ~a")
 (:review-complete . "Sessione completata!")
 (:review-complete-msg . "Hai ripassato ~a carte")
 (:review-correct . "Corrette")
 (:review-accuracy . "Precisione")
 (:review-again-btn . "Ripassa ancora")
 (:review-translate-more . "Traduci altro")
 (:review-streak . "giorni consecutivi")

 ;; Dashboard
 (:dashboard-title . "Dashboard")
 (:dashboard-cards-due . "Carte da ripassare")
 (:dashboard-total-cards . "Carte totali")
 (:dashboard-subscription . "Abbonamento")
 (:dashboard-subscribed-until . "Abbonato fino al")
 (:dashboard-not-subscribed . "Non abbonato")
 (:dashboard-recent . "Traduzioni recenti")
 (:dashboard-no-translations . "Nessuna traduzione ancora")
 (:dashboard-streak . "Serie di ripasso")
 (:dashboard-days . "giorni")
 (:dashboard-quick-actions . "Azioni rapide")
 (:dashboard-getting-started . "Per iniziare")
 (:dashboard-tip-1 . "Traduci il testo che vuoi imparare")
 (:dashboard-tip-2 . "Clicca \"Salva nelle flashcard\" sulle traduzioni che vuoi ricordare")
 (:dashboard-tip-3 . "Ripassa le tue flashcard regolarmente - la ripetizione spaziata ti aiuta a ricordare a lungo termine")
 (:dashboard-tip-4 . "Valuta onestamente - aiuta l'algoritmo a pianificare i ripassi in modo ottimale")

 ;; Subscription
 (:subscribe-title . "Prezzi semplici")
 (:subscribe-monthly . "Mensile")
 (:subscribe-annual . "Annuale")
 (:subscribe-monthly-price . "€10/mese")
 (:subscribe-annual-price . "€100/anno")
 (:subscribe-monthly-desc . "600 traduzioni al mese")
 (:subscribe-annual-desc . "Risparmia €20 — due mesi gratis!")
 (:subscribe-cta . "Abbonati")
 (:subscribe-success . "Abbonamento riuscito!")
 (:subscribe-manage . "Gestisci abbonamento")

 ;; Errors and status
 (:error-generic . "Qualcosa è andato storto")
 (:error-not-found . "Pagina non trovata")
 (:error-unauthorized . "Accedi per continuare")
 (:error-subscription-required . "Abbonamento richiesto")
 (:error-text-too-long . "Il testo è troppo lungo. La lunghezza massima della traduzione è 120 caratteri.")
 (:error-input-too-long . "Testo troppo lungo")
 (:error-unknown-source-lang . "La lingua di origine selezionata non è supportata.")
 (:error-unknown-target-lang . "La lingua di destinazione selezionata non è supportata.")
 (:error-unknown-language . "Lingua sconosciuta")
 (:error-translation-unavailable . "Il servizio di traduzione è temporaneamente non disponibile. Riprova tra un momento.")
 (:error-translation-failed . "Traduzione fallita")
 (:error-translation-retry . "Impossibile generare una traduzione dopo vari tentativi. Prova a riformulare il testo.")
 (:loading . "Caricamento...")
 (:empty-state . "Niente qui ancora")

 ;; Footer
 (:footer-privacy . "Informativa sulla privacy")
 (:footer-terms . "Termini di servizio")
 (:footer-contact . "Contatti")
)
