;;; Italian translations
;;; This file should contain all keys from en.lisp

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Italiano")
 (:lang-flag . "🇮🇹")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Scegli la tua lingua")
 (:lang-modal-subtitle . "Seleziona la lingua preferita per l'interfaccia:")

 ;; Navigation
 (:nav-translate . "Traduci")
 (:nav-review . "Ripassa")
 (:nav-flashcards . "Le mie carte")
 (:nav-dashboard . "Dashboard")
 (:nav-decks . "Decks")
 (:nav-logout . "Esci")
 (:nav-home . "Home")
 (:nav-pricing . "Prezzi")
 (:nav-export-data . "Esporta dati")

 ;; App title and branding
 (:app-title . "Hiisi - Apprendimento delle lingue")
 (:app-tagline . "Impara le lingue attraverso le traduzioni")

 ;; Landing page
 (:landing-hero-title . "Padroneggia qualsiasi lingua")
 (:landing-hero-subtitle . "Traduci qualsiasi cosa. Genera automaticamente flashcard che ti insegnano perché funziona così.")
 (:landing-cta . "Inizia a imparare")
 (:landing-learn-more . "Scopri di più")
 (:landing-how-it-works . "Come funziona")
 (:landing-feature-1-title . "Flashcard automatiche")
 (:landing-feature-1-desc . "Ogni traduzione genera automaticamente flashcard con analisi grammaticale. Nessuna creazione manuale.")
 (:landing-feature-2-title . "Ripetizione spaziata")
 (:landing-feature-2-desc . "L'algoritmo SM-2 pianifica i ripassi a intervalli ottimali. Impara in modo efficiente, ricorda per sempre.")
 (:landing-feature-3-title . "Insegnamento grammaticale")
 (:landing-feature-3-desc . "Ogni traduzione spiega grammatica, radici delle parole e struttura della frase. Capisci il perché, non solo il cosa.")
 (:landing-free-trial . "7 giorni di prova gratuita. Nessuna carta di credito richiesta.")
 (:landing-start-trial . "Inizia la prova gratuita")
 (:landing-best-value . "Miglior valore")
 (:landing-cta-title . "Pronto a imparare le lingue attraverso la grammatica, non la memorizzazione?")
 (:landing-cta-subtitle . "Ogni traduzione diventa un'opportunità di apprendimento. Ogni flashcard ti insegna il perché.")
 (:landing-signup-free . "Registrati gratis")

 ;; Auth pages
 (:auth-register . "Registrati")
 (:auth-login . "Accedi")
 (:auth-logout . "Esci")
 (:auth-email . "Email")
 (:auth-password . "Password")
 (:auth-password-again . "Conferma password")
 (:auth-display-name . "Nome visualizzato")
 (:auth-register-title . "Registrati su Hiisi")
 (:auth-register-subtitle . "Crea un nuovo account")
 (:auth-login-title . "Accedi a Hiisi")
 (:auth-login-subtitle . "Inserisci le tue credenziali")
 (:auth-forgot-password . "Password dimenticata?")
 (:auth-no-account . "Non hai un account?")
 (:auth-have-account . "Hai già un account?")
 (:auth-google . "Google")
 (:auth-account-created . "Account creato!")
 (:auth-check-email . "Controlla la tua email per il link di attivazione.")
 (:auth-redirect-login . "Reindirizzamento al login tra")
 (:auth-seconds . "secondi...")
 (:auth-go-now . "Vai ora")
 (:auth-not-activated . "Account non attivato")
 (:auth-activate-title . "Attiva il tuo account!")
 (:auth-activated . "Account attivato!")
 (:auth-activated-message . "Il tuo account è stato attivato. Ora puoi usare Hiisi.")
 (:auth-redirecting . "Reindirizzamento tra")
 (:auth-go-to-app . "Vai all'app")
 (:auth-resend-title . "Reinvia email di attivazione")
 (:auth-resend-subtitle . "Inserisci la tua email per ricevere un nuovo link di attivazione.")
 (:auth-resend-button . "Reinvia email di attivazione")
 (:auth-resend-success . "Email di attivazione inviata!")
 (:auth-resend-success-detail . "Controlla la tua casella di posta per il nuovo link di attivazione.")
 (:auth-resend-rate-limited . "Per favore attendi qualche minuto prima di richiedere un'altra email di attivazione.")
 (:auth-resend-cooldown . "Puoi richiedere un'altra email tra ~a secondi.")
 (:auth-back-to-login . "Torna al login")
 (:auth-forgot-password-title . "Password dimenticata")
 (:auth-forgot-password-subtitle . "Inserisci la tua email e ti invieremo un link per reimpostare la password.")
 (:auth-send-reset-link . "Invia link di reimpostazione")
 (:auth-reset-email-sent . "Link inviato!")
 (:auth-reset-email-sent-detail . "Se esiste un account con questa email, riceverai presto un link per reimpostare la password.")
 (:auth-reset-rate-limited . "Per favore attendi qualche minuto prima di richiedere un'altra reimpostazione della password.")
 (:auth-reset-invalid-token . "Questo link di reimpostazione non è valido o è scaduto.")
 (:auth-reset-password-title . "Reimposta password")
 (:auth-reset-password-subtitle . "Inserisci la tua nuova password qui sotto.")
 (:auth-new-password . "Nuova password")
 (:auth-confirm-new-password . "Conferma nuova password")
 (:auth-reset-password . "Reimposta password")
 (:auth-password-changed . "Password cambiata!")
 (:auth-password-changed-detail . "La tua password è stata cambiata con successo. Ora puoi accedere con la tua nuova password.")
 (:auth-change-password-title . "Cambia password")
 (:auth-change-password-subtitle . "Aggiorna la password del tuo account.")
 (:auth-current-password . "Password attuale")
 (:auth-change-password . "Cambia password")
 (:auth-back-to-app . "Torna all'app")
 (:auth-password-updated . "Password aggiornata!")
 (:auth-password-updated-detail . "La tua password è stata aggiornata con successo.")

 ;; Translation page
 (:translate-title . "Traduci")
 (:translate-input-label . "Testo da tradurre")
 (:translate-input-placeholder . "Inserisci il testo da tradurre...")
 (:translate-from . "Da:")
 (:translate-to . "A:")
 (:translate-submit . "Traduci")
 (:translate-save . "Salva nelle flashcard")
 (:translate-saved . "Salvato!")
 (:translate-like . "Mi piace")
 (:translate-dislike . "Non mi piace")
 (:translate-char-limit . "caratteri rimanenti")
 (:translate-auto-detect . "Qualsiasi (Rilevamento automatico)")
 (:translate-empty-state . "Inserisci il testo sopra e clicca Traduci per vedere il risultato con l'analisi grammaticale")
 (:translate-select-deck-placeholder . "Seleziona mazzo (opzionale)")
 (:translate-new-deck . "Nuovo mazzo")
 (:translate-add-to-deck . "Aggiungi al mazzo")
 (:translate-bookmark . "Salva")
 (:translate-bookmarked . "Salvato")
 (:translate-retry . "Riprova")
 (:translate-like-tooltip . "Buona traduzione")
 (:translate-dislike-tooltip . "Cattiva traduzione - richiedine una nuova")
 (:translate-dislike-confirm . "Questo genererà una nuova traduzione. Continuare?")
 (:translate-liked . "Mi piace!")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Destinazione")
 (:translate-deck-create-title . "Crea nuovo mazzo")
 (:translate-deck-name-label . "Nome del mazzo")
 (:translate-deck-name-placeholder . "ad es., Fondamenti di finlandese")
 (:translate-deck-description-label . "Descrizione (opzionale)")
 (:translate-deck-cancel . "Annulla")
 (:translate-deck-create . "Crea")
 (:translate-rate-label . "Valuta la traduzione")
 (:flashcards-delete-confirm . "Sei sicuro di voler eliminare questa carta?")
 (:flashcards-deck-search-placeholder . "Cerca mazzi...")
 (:flashcards-no-decks . "Nessun mazzo ancora. Creane uno prima!")
 (:flashcards-deck-cancel . "Annulla")

 ;; Flashcard review
 (:review-title . "Ripassa")
 (:review-session-title . "Sessione di ripasso")
 (:review-session-subtitle . "Esercitati con le tue flashcard salvate")
 (:review-start . "Inizia il ripasso")
 (:review-no-cards . "Nessuna carta da ripassare")
 (:review-no-cards-desc . "Non hai flashcard da ripassare in questo momento.")
 (:review-no-cards-hint . "Traduci del testo e clicca \"Salva nelle flashcard\" per costruire il tuo mazzo!")
 (:review-start-translating . "Inizia a tradurre")
 (:review-show-answer . "Mostra risposta")
 (:review-click-reveal . "Clicca per rivelare la risposta")
 (:review-grammar-breakdown . "Analisi grammaticale")
 (:review-how-well . "Quanto bene l'hai ricordato?")
 (:review-again . "Ancora")
 (:review-hard . "Difficile")
 (:review-good . "Bene")
 (:review-easy . "Facile")
 (:review-progress . "Carta ~a di ~a")
 (:review-complete . "Sessione completata!")
 (:review-complete-msg . "Hai ripassato ~a carte")
 (:review-correct . "Corrette")
 (:review-accuracy . "Precisione")
 (:review-again-btn . "Ripassa ancora")
 (:review-translate-more . "Traduci altro")
 (:review-streak . "giorni consecutivi")

 ;; Dashboard
 (:dashboard-title . "Dashboard")
 (:dashboard-cards-due . "Carte da ripassare")
 (:dashboard-total-cards . "Carte totali")
 (:dashboard-subscription . "Abbonamento")
 (:dashboard-subscribed-until . "Abbonato fino al")
 (:dashboard-not-subscribed . "Non abbonato")
 (:dashboard-recent . "Traduzioni recenti")
 (:dashboard-no-translations . "Nessuna traduzione ancora")
 (:dashboard-streak . "Serie di ripasso")
 (:dashboard-days . "giorni")
 (:dashboard-quick-actions . "Azioni rapide")
 (:dashboard-getting-started . "Per iniziare")
 (:dashboard-tip-1 . "Traduci il testo che vuoi imparare")
 (:dashboard-tip-2 . "Clicca \"Salva nelle flashcard\" sulle traduzioni che vuoi ricordare")
 (:dashboard-tip-3 . "Ripassa le tue flashcard regolarmente - la ripetizione spaziata ti aiuta a ricordare a lungo termine")
 (:dashboard-tip-4 . "Valuta onestamente - aiuta l'algoritmo a pianificare i ripassi in modo ottimale")

 ;; Account
 (:account-title . "Account")
 (:account-subtitle . "Gestisci le impostazioni dell'account e la programmazione di eliminazione.")
 (:account-deletion-title . "Eliminazione account")
 (:account-deletion-scheduled . "Il tuo account è programmato per l'eliminazione il ~A.")
 (:account-deletion-cancel-hint . "Puoi annullare prima di questa data per mantenere il tuo account.")
 (:account-deletion-cancel . "Annulla eliminazione")
 (:account-deletion-request . "Puoi richiedere l'eliminazione dell'account in qualsiasi momento. L'eliminazione è programmata 14 giorni dopo la conferma. Se cambi idea dopo l'eliminazione, contatta l'assistenza.")
 (:account-deletion-confirm . "Programmare l'eliminazione dell'account tra 14 giorni da oggi?")
 (:account-deletion-schedule . "Programma eliminazione")
 (:account-reminders-title . "Promemoria email")
 (:account-reminders-subtitle . "Gestisci i promemoria di ripasso e continuazione per questo account.")
 (:account-reminders-opt-out . "Disattiva i promemoria di ripasso e continuazione")
 (:account-reminders-save . "Salva preferenze")

 ;; Subscription
 (:subscribe-title . "Prezzi semplici")
 (:subscribe-choose-plan . "Scegli il tuo piano")
 (:subscribe-start-today . "Inizia a imparare oggi con 7 giorni di prova gratuita")
 (:subscribe-monthly . "Mensile")
 (:subscribe-annual . "Annuale")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/mese")
 (:subscribe-per-year . "/anno")
 (:subscribe-monthly-desc . "600 traduzioni al mese")
 (:subscribe-unlimited-flashcards . "Flashcard illimitate")
 (:subscribe-grammar-explanations . "Spiegazioni grammaticali")
 (:subscribe-spaced-repetition . "Ripetizione spaziata")
 (:subscribe-annual-desc . "Risparmia €20 — due mesi gratis!")
 (:subscribe-cta . "Abbonati")
 (:subscribe-success . "Abbonamento riuscito!")
 (:subscribe-manage . "Gestisci abbonamento")
 (:subscribe-activated . "Abbonamento attivato!")
 (:subscribe-thank-you . "Grazie per l'abbonamento. Il tuo account è ora attivo.")
 (:subscribe-start-learning . "Inizia a imparare")
 (:subscribe-management . "Gestione abbonamento")
 (:subscribe-active . "Abbonamento attivo")
 (:subscribe-status . "Stato:")
 (:subscribe-status-active . "Attivo")
 (:subscribe-days-remaining . "Giorni rimanenti:")
 (:subscribe-renews-on . "Si rinnova il:")
 (:subscribe-no-subscription . "Nessun abbonamento attivo")
 (:subscribe-access-features . "Abbonati per accedere a tutte le funzionalità.")
 (:subscribe-view-plans . "Visualizza piani")
 (:subscribe-faq-title . "Domande frequenti")
 (:subscribe-faq-trial-q . "Cosa succede dopo la prova gratuita?")
 (:subscribe-faq-trial-a . "Dopo i 7 giorni di prova gratuita, ti verrà addebitato il piano selezionato. Puoi annullare in qualsiasi momento prima della fine della prova.")
 (:subscribe-faq-cancel-q . "Posso annullare in qualsiasi momento?")
 (:subscribe-faq-cancel-a . "Sì! Puoi annullare il tuo abbonamento in qualsiasi momento. Manterrai l'accesso fino alla fine del periodo di fatturazione.")
 (:subscribe-faq-payment-q . "Quali metodi di pagamento accettate?")
 (:subscribe-faq-payment-a . "Accettiamo tutte le principali carte di credito e debito tramite il nostro partner di pagamento Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Qualcosa è andato storto")
 (:error-not-found . "Pagina non trovata")
 (:error-unauthorized . "Accedi per continuare")
 (:error-subscription-required . "Abbonamento richiesto")
 (:error-text-too-long . "Il testo è troppo lungo. La lunghezza massima della traduzione è 120 caratteri.")
 (:error-input-too-long . "Testo troppo lungo")
 (:error-unknown-source-lang . "La lingua di origine selezionata non è supportata.")
 (:error-unknown-target-lang . "La lingua di destinazione selezionata non è supportata.")
 (:error-unknown-language . "Lingua sconosciuta")
 (:error-translation-unavailable . "Il servizio di traduzione è temporaneamente non disponibile. Riprova tra un momento.")
 (:error-translation-failed . "Traduzione fallita")
 (:error-translation-retry . "Impossibile generare una traduzione dopo vari tentativi. Prova a riformulare il testo.")
 (:error-quota-exceeded . "Limite traduzioni raggiunto")
 (:error-quota-exceeded-detail . "Hai esaurito tutte le traduzioni per questo mese. La tua quota si azzera automaticamente ogni mese.")
 (:quota-warning . "Traduzioni rimanenti: ~A")
 (:quota-low-warning . "Solo ~A traduzioni rimaste. Considera di acquistarne altre.")
 (:top-up-button . "Acquista più traduzioni")
 (:top-up-success . "Ricarica riuscita! Hai ora ~A traduzioni aggiuntive.")
 (:top-up-price . "€5")
 (:top-up-amount . "300 traduzioni")
 (:loading . "Caricamento...")
 (:empty-state . "Niente qui ancora")

 ;; Institutions
 (:institutions-page-title . "Hiisi per le scuole - licenze istituzionali")
 (:institutions-hero-title . "Hiisi per le scuole")
 (:institutions-hero-subtitle . "Dai ai tuoi studenti l'apprendimento linguistico con l'AI")
 (:institutions-section-title . "Licenze istituzionali")
 (:institutions-section-body . "Offriamo licenze in blocco per scuole, università e istituti di lingue. Gli studenti con indirizzi email del tuo dominio ricevono automaticamente l'accesso completo.")
 (:institutions-benefit-1 . "Iscrizione automatica per studenti con email istituzionale")
 (:institutions-benefit-2 . "Nessun account per studente da gestire")
 (:institutions-benefit-3 . "Opzioni di fatturazione flessibili")
 (:institutions-benefit-4 . "Supporto dedicato per gli educatori")
 (:institutions-request-title . "Richiedi una licenza")
 (:institutions-request-subtitle . "Compila il modulo qui sotto e ti risponderemo entro 2 giorni lavorativi.")
 (:institutions-field-name . "Nome dell'istituzione")
 (:institutions-field-name-placeholder . "Università di Helsinki")
 (:institutions-field-contact-name . "Nome del contatto")
 (:institutions-field-contact-name-placeholder . "Il tuo nome")
 (:institutions-field-contact-email . "Email di contatto")
 (:institutions-field-contact-email-placeholder . "tuo@universita.it")
 (:institutions-field-domains . "Domini email")
 (:institutions-field-domains-placeholder . "universita.it, cs.universita.it")
 (:institutions-field-domains-help . "Elenco di domini email della tua istituzione separati da virgole")
 (:institutions-field-notes . "Informazioni aggiuntive")
 (:institutions-field-notes-placeholder . "Numero stimato di studenti, ciclo di fatturazione preferito, eventuali requisiti speciali...")
 (:institutions-submit . "Invia richiesta")
 (:institutions-success-title . "Grazie - Hiisi per le scuole")
 (:institutions-success-heading . "Grazie!")
 (:institutions-success-body . "Abbiamo ricevuto la tua richiesta di licenza istituzionale. Il nostro team la esaminerà e ti contatterà entro 2 giorni lavorativi.")
 (:institutions-success-back . "Torna alla home")

 ;; Footer
 (:footer-privacy . "Informativa sulla privacy")
 (:footer-terms . "Termini di servizio")
 (:footer-contact . "Contatti")

 ;; Early software notice
 (:early-software-notice . "Hiisi è in fase di sviluppo iniziale. Hai trovato un bug o hai un suggerimento?")
 (:early-software-contact . "Contattaci a")

 ;; Privacy Policy
 (:privacy-title . "Privacy Policy")
 (:privacy-updated . "Last updated: January 2026")
 (:privacy-who-title . "Who We Are")
 (:privacy-who-body . "Hiisi is operated by Lambda Symbolics OÜ, a company registered in Estonia. As an Estonian company, we comply with the European Union's General Data Protection Regulation (GDPR).")
 (:privacy-collect-title . "Data We Collect")
 (:privacy-collect-intro . "We collect the following information when you use Hiisi:")
 (:privacy-collect-account-key . "Account information: ")
 (:privacy-collect-account-val . "Email address, display name, and a securely hashed password.")
 (:privacy-collect-learning-key . "Learning data: ")
 (:privacy-collect-learning-val . "Your translations, saved flashcards, and review history.")
 (:privacy-collect-usage-key . "Usage data: ")
 (:privacy-collect-usage-val . "Basic server logs for security and debugging purposes.")
 (:privacy-use-title . "How We Use Your Data")
 (:privacy-use-auth-key . "Authentication: ")
 (:privacy-use-auth-val . "To verify your identity and secure your account.")
 (:privacy-use-service-key . "Service delivery: ")
 (:privacy-use-service-val . "To provide translations and manage your flashcard collection.")
 (:privacy-use-ai-key . "AI translations: ")
 (:privacy-use-ai-val . "Your translation requests are sent to Anthropic's Claude API to generate responses. See Anthropic's privacy policy for how they handle this data.")
 (:privacy-third-title . "Third-Party Services")
 (:privacy-third-intro . "We use the following third-party services:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "For AI-powered translations.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "For sending account activation and transactional emails.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "For subscription payment processing.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "We use only essential cookies:")
 (:privacy-cookies-auth-key . "Authentication token: ")
 (:privacy-cookies-auth-val . "A secure, HTTP-only cookie to keep you logged in.")
 (:privacy-cookies-lang-key . "Language preference: ")
 (:privacy-cookies-lang-val . "To remember your preferred UI language.")
 (:privacy-retention-title . "Data Retention")
 (:privacy-retention-body . "Your data is stored as long as you maintain an account. When you request deletion, your account is scheduled for deletion in 14 days.")
 (:privacy-rights-title . "Your Rights (GDPR)")
 (:privacy-rights-intro . "Under GDPR, you have the right to:")
 (:privacy-rights-access . "Access your personal data")
 (:privacy-rights-export . "Export your data (available at /app/api/export)")
 (:privacy-rights-correct . "Request correction of inaccurate data")
 (:privacy-rights-delete . "Request deletion of your account and data")
 (:privacy-rights-object . "Object to processing of your data")
 (:privacy-rights-contact . "To exercise these rights, contact us at")
 (:privacy-contact-title . "Contact")
 (:privacy-contact-intro . "For privacy-related inquiries:")
 (:privacy-contact-email-label . "Email: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Estonia")

 ;; Terms of Service
 (:terms-title . "Terms of Service")
 (:terms-updated . "Last updated: January 2026")
 (:terms-1-title . "1. Service Description")
 (:terms-1-body . "Hiisi is a language learning application that provides AI-powered translations with grammatical explanations and spaced repetition flashcards. The service is operated by Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Account Registration")
 (:terms-2-body . "To use Hiisi, you must create an account with a valid email address. You are responsible for maintaining the security of your account credentials.")
 (:terms-3-title . "3. Subscription and Payments")
 (:terms-3-body . "Hiisi offers paid subscription plans (monthly and annual). Subscriptions are processed through Polar.sh.")
 (:terms-3-list-1 . "Subscriptions auto-renew unless cancelled before the renewal date.")
 (:terms-3-list-2 . "Refunds are provided in accordance with applicable consumer protection laws.")
 (:terms-3-list-3 . "Non-payment results in loss of access to premium features.")
 (:terms-4-title . "4. Acceptable Use")
 (:terms-4-intro . "You agree not to:")
 (:terms-4-list-1 . "Use the service for any illegal purpose")
 (:terms-4-list-2 . "Attempt to circumvent usage limits or security measures")
 (:terms-4-list-3 . "Share your account credentials with others")
 (:terms-4-list-4 . "Use automated tools to access the service in a way that degrades performance for others")
 (:terms-5-title . "5. Content and Intellectual Property")
 (:terms-5-body-1 . "Translations generated by Hiisi are created using AI and may not be unique. You may use your translations and flashcards for any personal purpose, but you do not hold exclusive authorship rights over AI-generated content.")
 (:terms-5-body-2 . "The Hiisi application, branding, and original content remain the property of Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Service Availability")
 (:terms-6-intro . "Hiisi is provided on an \"as-is\" basis. We do not guarantee:")
 (:terms-6-list-1 . "Uninterrupted or error-free service")
 (:terms-6-list-2 . "Accuracy of AI-generated translations")
 (:terms-6-list-3 . "Availability of specific features")
 (:terms-6-body . "We may modify or discontinue features at any time.")
 (:terms-7-title . "7. Limitation of Liability")
 (:terms-7-body-1 . "To the maximum extent permitted by law, Lambda Symbolics OÜ shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of Hiisi.")
 (:terms-7-body-2 . "Our total liability shall not exceed the amount you paid for the service in the 12 months preceding the claim.")
 (:terms-8-title . "8. Account Termination")
 (:terms-8-body-1 . "We may suspend or terminate your account if you violate these terms. You may request account deletion at any time through the application.")
 (:terms-8-body-2 . "Upon deletion request, your account is scheduled for deletion in 14 days.")
 (:terms-9-title . "9. Changes to Terms")
 (:terms-9-body . "We may update these terms from time to time. Continued use of Hiisi after changes constitutes acceptance of the new terms.")
 (:terms-10-title . "10. Governing Law")
 (:terms-10-body . "These terms are governed by the laws of Estonia. Any disputes shall be resolved in the courts of Estonia.")
 (:terms-contact-title . "Contact")
 (:terms-contact-intro . "For questions about these terms:")
 (:terms-contact-email-label . "Email: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Estonia")



 ;; Decks
 (:decks-title . "Mazzi")
 (:decks-subtitle . "Crea mazzi personalizzati e condividili con altri.")
 (:decks-create-title . "Crea mazzo")
 (:decks-name-placeholder . "Nome del mazzo")
 (:decks-desc-placeholder . "Descrizione")
 (:decks-create-btn . "Crea mazzo")
 (:decks-your-title . "I tuoi mazzi")
 (:decks-col-name . "Nome")
 (:decks-col-desc . "Descrizione")
 (:decks-col-updated . "Aggiornato")
 (:decks-col-actions . "Azioni")
 (:decks-no-decks . "Ancora nessun mazzo.")
 (:decks-open-btn . "Apri")
 (:decks-no-desc . "Nessuna descrizione.")
 (:decks-share-title . "Link di condivisione")
 (:decks-share-info . "Chiunque con questo link può importare il mazzo:")
 (:decks-share-copy . "Copia link")
 (:decks-share-copied . "Copiato")
 (:decks-add-from-flashcards-title . "Aggiungi traduzioni")
 (:decks-add-from-flashcards-info . "Scegli una scheda per aggiungere la sua traduzione a questo mazzo.")
 (:decks-open-flashcards . "Aggiungi dalle schede")
 (:decks-filter-from . "Lingua di partenza")
 (:decks-filter-to . "Lingua di arrivo")
 (:decks-filter-any . "Qualsiasi lingua")
 (:decks-filter-include-assigned . "Includi le schede già in un mazzo")
 (:decks-flashcards-col-from . "Da")
 (:decks-flashcards-col-to . "A")
 (:decks-flashcards-add . "Aggiungi")
 (:decks-flashcards-added . "Aggiunto")
 (:decks-flashcards-in-deck . "In un altro mazzo")
 (:decks-flashcards-empty . "Nessuna scheda corrisponde a questi filtri.")
 (:decks-add-trans-title . "Aggiungi traduzione")
 (:decks-trans-id-placeholder . "ID traduzione")
 (:decks-add-trans-btn . "Aggiungi traduzione")
 (:decks-items-title . "Contenuto del mazzo")
 (:decks-col-original . "Originale")
 (:decks-col-translated . "Traduzione")
 (:decks-col-lang . "Lingua destinazione")
 (:decks-no-items . "Ancora nessun elemento.")
 (:decks-share-page-title . "Condividi mazzo")
 (:decks-share-preview . "Anteprima e importa questo mazzo.")
 (:decks-import-title . "Importa")
 (:decks-import-btn . "Importa mazzo")

 ;; Flashcards management page
 (:flashcards-title . "Le mie carte")
 (:flashcards-subtitle . "Tutte le tue carte salvate in un unico posto. Cerca, organizza e gestisci.")
 (:flashcards-search-placeholder . "Cerca carte...")
 (:flashcards-col-original . "Originale")
 (:flashcards-col-translated . "Traduzione")
 (:flashcards-col-lang . "Lingue")
 (:flashcards-no-cards . "Nessuna carta ancora. Inizia a tradurre per crearne alcune!")

 ;; API Errors (EN fallback)
 (:api-error-missing-text . "Missing text to translate.")
 (:api-error-invalid-translation-id . "Invalid translation ID.")
 (:api-error-translation-not-found . "The translation you tried to save no longer exists.")
 (:api-error-invalid-bookmark-id . "Invalid bookmark ID")
 (:api-error-bookmark-not-found . "Bookmark not found")
 (:api-error-forbidden . "Forbidden")
 (:api-error-failed-delete-bookmark . "Failed to delete bookmark")
 (:api-error-invalid-flashcard-id . "Invalid flashcard ID")
 (:api-error-missing-deck-id . "Missing deck_id")
 (:api-error-flashcard-not-found . "Flashcard not found")
 (:api-error-deck-not-found . "Deck not found")
 (:api-error-deck-name-required . "Deck name is required")
 (:api-error-session-expired . "Your review session has expired. Please start a new session.")
 (:api-error-invalid-card-id . "Invalid card ID.")
 (:api-error-invalid-rating . "Invalid rating.")
 (:api-error-rating-range . "Rating must be between 0 and 5.")
 (:api-error-card-not-found . "Card not found.")
 (:api-error-permission-denied . "You don't have permission to review this card.")
 (:api-error-unknown-source-lang . "Unknown source language.")
 (:api-error-unknown-target-lang . "Unknown target language.")
 (:api-error-failed-add-to-deck . "Failed to add to deck")

 ;; API Success messages
 (:api-success-added . "Added!")
 (:api-success-added-simple . "Added")

 ;; API Stats
 (:api-stats-due . "~A due")
 (:api-stats-total . "~A total")

 ;; Time units
 (:api-time-day . "day")
 (:api-time-days . "days")
 (:api-time-day-left . "day left")
 (:api-time-days-left . "days left")

 ;; Subscription status
 (:api-subscription-active . "Active")
 (:api-subscription-inactive . "Inactive")
 (:api-subscription-subscribe-hint . "Subscribe to unlock translations")

 ;; Generic status
 (:status-bad-request . "Bad Request")
 (:status-not-found . "Not Found")
 (:status-forbidden . "Forbidden")

)
