;;; Dutch translations

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Nederlands")
 (:lang-flag . "🇳🇱")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Kies je taal")
 (:lang-modal-subtitle . "Selecteer je voorkeurstaal voor de interface:")

 ;; Navigation
 (:nav-translate . "Vertalen")
 (:nav-review . "Herhalen")
 (:nav-flashcards . "Mijn kaarten")
 (:nav-dashboard . "Dashboard")
 (:nav-decks . "Decks")
 (:nav-logout . "Uitloggen")
 (:nav-home . "Home")
 (:nav-pricing . "Prijzen")
 (:nav-export-data . "Gegevens exporteren")

 ;; App title and branding
 (:app-title . "Hiisi - Talen leren")

 ;; Landing page
 (:landing-learn-more . "Meer informatie")
 (:landing-how-it-works . "Hoe het werkt")
 (:landing-start-trial . "Start gratis proefperiode")
 (:landing-best-value . "Beste waarde")

 ;; Auth pages
 (:auth-register . "Registreren")
 (:auth-login . "Inloggen")
 (:auth-email . "E-mail")
 (:auth-password . "Wachtwoord")
 (:auth-password-again . "Bevestig wachtwoord")
 (:auth-display-name . "Weergavenaam")
 (:auth-register-title . "Registreer bij Hiisi")
 (:auth-register-subtitle . "Maak een nieuw account aan")
 (:auth-login-title . "Log in bij Hiisi")
 (:auth-login-subtitle . "Voer je gegevens in")
 (:auth-login-invalid-credentials . "Ongeldig e-mailadres of wachtwoord.")
 (:auth-login-rate-limited . "Te veel inlogpogingen. Wacht een paar minuten en probeer het opnieuw.")
 (:auth-forgot-password . "Wachtwoord vergeten?")
 (:auth-no-account . "Heb je geen account?")
 (:auth-have-account . "Heb je al een account?")
 (:auth-google . "Google")
 (:auth-account-created . "Account aangemaakt!")
 (:auth-check-email . "Controleer je e-mail voor de activatielink.")
 (:auth-redirect-login . "Doorsturen naar inloggen over")
 (:auth-seconds . "seconden...")
 (:auth-go-now . "Ga nu")
 (:auth-not-activated . "Account niet geactiveerd")
 (:auth-activate-title . "Activeer je account!")
 (:auth-activated . "Account geactiveerd!")
 (:auth-activated-message . "Je account is geactiveerd. Je kunt Hiisi nu gebruiken.")
 (:auth-redirecting . "Doorsturen over")
 (:auth-go-to-app . "Naar de app")
 (:auth-resend-title . "Activatiemail opnieuw verzenden")
 (:auth-resend-subtitle . "Voer je e-mailadres in om een nieuwe activatielink te ontvangen.")
 (:auth-resend-button . "Activatiemail opnieuw verzenden")
 (:auth-resend-success . "Activatiemail verzonden!")
 (:auth-resend-success-detail . "Controleer je inbox voor de nieuwe activatielink.")
 (:auth-resend-rate-limited . "Wacht een paar minuten voordat je nog een activatiemail aanvraagt.")
 (:auth-resend-cooldown . "Je kunt over ~a seconden een nieuwe mail aanvragen.")
 (:auth-back-to-login . "Terug naar inloggen")
 (:auth-forgot-password-title . "Wachtwoord vergeten")
 (:auth-forgot-password-subtitle . "Voer je e-mailadres in en we sturen je een link om je wachtwoord opnieuw in te stellen.")
 (:auth-send-reset-link . "Stuur resetlink")
 (:auth-reset-email-sent . "Resetlink verzonden!")
 (:auth-reset-email-sent-detail . "Als er een account bestaat met dit e-mailadres, ontvang je binnenkort een link om je wachtwoord opnieuw in te stellen.")
 (:auth-reset-rate-limited . "Wacht een paar minuten voordat je nog een wachtwoord-reset aanvraagt.")
 (:auth-reset-invalid-token . "Deze resetlink is ongeldig of verlopen.")
 (:auth-reset-password-title . "Wachtwoord opnieuw instellen")
 (:auth-reset-password-subtitle . "Voer hieronder je nieuwe wachtwoord in.")
 (:auth-new-password . "Nieuw wachtwoord")
 (:auth-confirm-new-password . "Bevestig nieuw wachtwoord")
 (:auth-reset-password . "Wachtwoord opnieuw instellen")
 (:auth-password-changed . "Wachtwoord gewijzigd!")
 (:auth-password-changed-detail . "Je wachtwoord is succesvol gewijzigd. Je kunt nu inloggen met je nieuwe wachtwoord.")
 (:auth-change-password-title . "Wachtwoord wijzigen")
 (:auth-change-password-subtitle . "Werk het wachtwoord van je account bij.")
 (:auth-current-password . "Huidig wachtwoord")
 (:auth-change-password . "Wachtwoord wijzigen")
 (:auth-back-to-app . "Terug naar app")
 (:auth-password-updated . "Wachtwoord bijgewerkt!")
 (:auth-password-updated-detail . "Je wachtwoord is succesvol bijgewerkt.")

 ;; Translation page
 (:translate-title . "Vertalen")
 (:translate-input-label . "Te vertalen tekst")
 (:translate-input-placeholder . "Voer tekst in om te vertalen...")
 (:translate-from . "Brontaal:")
 (:translate-to . "Doeltaal:")
 (:translate-submit . "Vertalen")
 (:translate-auto-detect . "Elke (Automatisch detecteren)")
 (:translate-empty-state . "Voer hierboven tekst in en klik op Vertalen om het resultaat met grammaticale uitleg te zien")
 (:translate-select-deck-placeholder . "Selecteer stapel (optioneel)")
 (:translate-new-deck . "Nieuwe stapel")
 (:translate-add-to-deck . "Toevoegen aan stapel")
 (:translate-bookmark . "Opslaan")
 (:translate-bookmarked . "Opgeslagen")
 (:translate-retry . "Opnieuw proberen")
 (:translate-like-tooltip . "Goede vertaling")
 (:translate-dislike-tooltip . "Slechte vertaling - vraag een nieuwe aan")
 (:translate-dislike-confirm . "Dit genereert een nieuwe vertaling. Doorgaan?")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Doel")
 (:translate-deck-create-title . "Nieuwe stapel maken")
 (:translate-deck-name-label . "Stapelnaam")
 (:translate-deck-name-placeholder . "bijv. Basis Fins")
 (:translate-deck-description-label . "Beschrijving (optioneel)")
 (:translate-deck-cancel . "Annuleren")
 (:translate-deck-create . "Maken")
 (:translate-rate-label . "Vertaling beoordelen")
 (:flashcards-delete-confirm . "Weet je zeker dat je deze kaart wilt verwijderen?")
 (:flashcards-deck-search-placeholder . "Stapels zoeken...")
 (:flashcards-no-decks . "Nog geen stapels. Maak er eerst een!")
 (:flashcards-deck-cancel . "Annuleren")
 (:flashcards-recollection-tooltip . "Herinnering: ~A")
 (:flashcards-recollection-poor . "Zwak")
 (:flashcards-recollection-fair . "Redelijk")
 (:flashcards-recollection-normal . "Normaal")
 (:flashcards-recollection-strong . "Sterk")
 (:flashcards-recollection-very-strong . "Zeer sterk")

 ;; Flashcard review
 (:review-title . "Herhalen")
 (:review-session-title . "Herhalingssessie")
 (:review-session-subtitle . "Oefen je opgeslagen flashcards")
 (:review-selector-title . "Kies wat je wilt herhalen")
 (:review-selector-subtitle . "Selecteer een deck of taalpaar om je herhalingssessie op te richten.")
 (:review-by-deck . "Herhaal per deck")
 (:review-by-language-pair . "Herhaal per taalpaar")
 (:review-all-cards . "Herhaal alle kaarten")

 (:review-no-cards . "Geen kaarten te herhalen")
 (:review-no-cards-desc . "Je hebt momenteel geen flashcards die herhaald moeten worden.")
 (:review-no-cards-hint . "Vertaal wat tekst en klik op \"Opslaan als flashcard\" om je stapel op te bouwen!")
 (:review-start-translating . "Begin met vertalen")
 (:review-click-reveal . "Klik om antwoord te tonen")
 (:review-grammar-breakdown . "Grammaticale uitleg")
 (:review-how-well . "Herinnerde je het?")
 (:review-again . "Nee")
 (:review-hard . "Nauwelijks")
 (:review-good . "Ja")
 (:review-easy . "Gemakkelijk")
 (:review-progress . "Kaart ~a van ~a")
 (:review-complete . "Sessie voltooid!")
 (:review-complete-msg . "Je hebt ~a kaarten herhaald")
 (:review-again-btn . "Opnieuw herhalen")
 (:review-translate-more . "Meer vertalen")
 (:review-streak . "dagen op rij")

 ;; Dashboard
 (:dashboard-title . "Dashboard")
 (:dashboard-cards-due . "Kaarten voor vandaag")
 (:dashboard-total-cards . "Totaal kaarten")
 (:dashboard-subscription . "Abonnement")
 (:dashboard-subscribed-until . "Geabonneerd tot")
 (:dashboard-not-subscribed . "Niet geabonneerd")
 (:dashboard-recent . "Recente vertalingen")
 (:dashboard-no-translations . "Nog geen vertalingen")
 (:dashboard-streak . "Herhalingsreeks")
 (:dashboard-days . "dagen")
 (:dashboard-all-caught-up . "Helemaal bij!")
 (:dashboard-all-caught-up-hint . "Vertaal meer om je verzameling uit te bouwen.")
 (:dashboard-quick-actions . "Snelle acties")
 (:dashboard-getting-started . "Aan de slag")
 (:dashboard-tip-1 . "Vertaal tekst die je wilt leren")
 (:dashboard-tip-2 . "Klik op \"Opslaan als flashcard\" bij vertalingen die je wilt onthouden")
 (:dashboard-tip-3 . "Herhaal je flashcards regelmatig - gespreide herhaling helpt je om langdurig te onthouden")
 (:dashboard-tip-4 . "Beoordeel eerlijk - het helpt het algoritme om je herhalingen optimaal te plannen")

 ;; Account
 (:account-title . "Account")
 (:account-subtitle . "Beheer je accountinstellingen en verwijderingsplanning.")
 (:account-deletion-title . "Account verwijderen")
 (:account-deletion-scheduled . "Je account staat gepland voor verwijdering op ~A.")
 (:account-deletion-cancel-hint . "Je kunt voor deze datum annuleren om je account te behouden.")
 (:account-deletion-cancel . "Verwijdering annuleren")
 (:account-deletion-request . "Je kunt op elk moment een verzoek tot verwijdering van je account indienen. Verwijdering wordt 14 dagen na bevestiging gepland. Als je na verwijdering van gedachten verandert, neem contact op met support.")
 (:account-deletion-confirm . "Accountverwijdering plannen over 14 dagen vanaf vandaag?")
 (:account-deletion-schedule . "Verwijdering plannen")
 (:account-reminders-title . "E-mailherinneringen")
 (:account-reminders-subtitle . "Beheer herinneringen voor herhalen en doorgaan voor dit account.")
 (:account-reminders-opt-out . "Herinneringen voor herhalen en doorgaan uitschakelen")
 (:account-reminders-save . "Voorkeuren opslaan")

 ;; Subscription
 (:subscribe-title . "Eenvoudige prijzen")
 (:subscribe-choose-plan . "Kies je abonnement")
 (:subscribe-start-today . "Begin vandaag met leren met een 7-daagse gratis proefperiode")
 (:subscribe-monthly . "Maandelijks")
 (:subscribe-annual . "Jaarlijks")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/maand")
 (:subscribe-per-year . "/jaar")
 (:subscribe-monthly-desc . "600 vertalingen per maand")
 (:subscribe-unlimited-flashcards . "Onbeperkte flashcards")
 (:subscribe-grammar-explanations . "Grammatica-uitleg")
 (:subscribe-spaced-repetition . "Gespreide herhaling")
 (:subscribe-annual-desc . "Bespaar €20 - twee maanden gratis!")
 (:subscribe-manage . "Beheer abonnement")
 (:subscribe-activated . "Abonnement geactiveerd!")
 (:subscribe-thank-you . "Bedankt voor je abonnement. Je account is nu actief.")
 (:subscribe-start-learning . "Begin met leren")
 (:subscribe-management . "Abonnementsbeheer")
 (:subscribe-active . "Actief abonnement")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Actief")
 (:subscribe-days-remaining . "Dagen resterend:")
 (:subscribe-renews-on . "Verlengt op:")
 (:subscribe-no-subscription . "Geen actief abonnement")
 (:subscribe-access-features . "Abonneer om toegang te krijgen tot alle functies.")
 (:subscribe-view-plans . "Bekijk abonnementen")
 (:subscribe-faq-title . "Veelgestelde vragen")
 (:subscribe-faq-trial-q . "Wat gebeurt er na de gratis proefperiode?")
 (:subscribe-faq-trial-a . "Na je 7-daagse gratis proefperiode word je in rekening gebracht voor je gekozen abonnement. Je kunt op elk moment voor het einde van de proefperiode opzeggen.")
 (:subscribe-faq-cancel-q . "Kan ik op elk moment opzeggen?")
 (:subscribe-faq-cancel-a . "Ja! Je kunt je abonnement op elk moment opzeggen. Je behoudt toegang tot het einde van je factureringsperiode.")
 (:subscribe-faq-payment-q . "Welke betaalmethoden accepteren jullie?")
 (:subscribe-faq-payment-a . "We accepteren alle gangbare creditcards en betaalkaarten via onze betalingspartner Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Er ging iets mis")
 (:error-text-too-long . "Tekst is te lang. Maximale vertalingslengte is 120 tekens.")
 (:error-input-too-long . "Invoer te lang")
 (:error-unknown-source-lang . "De brontaal die je hebt geselecteerd wordt niet ondersteund.")
 (:error-unknown-target-lang . "De doeltaal die je hebt geselecteerd wordt niet ondersteund.")
 (:error-unknown-language . "Onbekende taal")
 (:error-translation-unavailable . "Vertaalservice is tijdelijk niet beschikbaar. Probeer het zo opnieuw.")
 (:error-translation-failed . "Vertaling mislukt")
 (:error-translation-retry . "Kon na meerdere pogingen geen vertaling genereren. Probeer je tekst anders te formuleren.")
 (:error-quota-exceeded . "Vertaallimiet bereikt")
 (:error-quota-exceeded-detail . "Je hebt al je vertalingen voor deze maand gebruikt. Je quotum wordt automatisch elke maand gereset.")
 (:quota-low-warning . "Nog maar ~A vertalingen over. Overweeg om meer te kopen.")
 (:top-up-button . "Koop meer vertalingen")
 (:top-up-price . "€5")
 (:top-up-amount . "300 vertalingen")

 ;; Institutions
 (:institutions-page-title . "Hiisi voor scholen en universiteiten")
 (:institutions-hero-title . "Hulpmiddelen voor taalonderwijs, gemaakt voor de klas")
 (:institutions-hero-subtitle . "Geef je studenten deelbare stapels, grammatica-bewuste oefening en vaste herhaalroutines die passen bij echt onderwijs.")
 (:institutions-section-title . "Waarom instellingen Hiisi gebruiken")
 (:institutions-section-body . "Hiisi helpt docenten om lesmateriaal om te zetten in begeleide studie die studenten echt kunnen volhouden. Maak stapels voor een cursus, deel ze met een link en ondersteun woordenschat- en grammaticaoefening zonder extra administratieve last.")
 (:institutions-benefit-1 . "Deelbare stapels en eigen opdrachten die aansluiten op jullie curriculum.")
 (:institutions-benefit-2 . "Likes en dislikes van studenten helpen de sterkste vertalingen naar boven voor veelvoorkomende zinnen uit de les.")
 (:institutions-benefit-3 . "Grammatica-uitsplitsingen en gespreide herhaling ondersteunen meer dan het uit het hoofd leren van losse woordenlijsten.")
 (:institutions-benefit-4 . "Ondersteuning met een docentenblik, van iemand die goed luistert en echt geeft om wat er in de klas nodig is.")
 (:institutions-request-title . "Laten we in gesprek gaan")
 (:institutions-request-subtitle . "Vertel ons over je instelling, jullie talen en het soort ondersteuning dat je in het onderwijs nodig hebt. We nemen binnen een week contact op.")
 (:institutions-field-name . "Naam van de instelling")
 (:institutions-field-name-placeholder . "Universiteit van Helsinki")
 (:institutions-field-contact-name . "Contactpersoon")
 (:institutions-field-contact-name-placeholder . "Jouw naam")
 (:institutions-field-contact-email . "Contact-e-mail")
 (:institutions-field-contact-email-placeholder . "jij@universiteit.nl")
 (:institutions-field-domains . "E-maildomeinen")
 (:institutions-field-domains-placeholder . "universiteit.nl, cs.universiteit.nl")
 (:institutions-field-domains-help . "Komma-gescheiden lijst met e-maildomeinen van je instelling")
 (:institutions-field-notes . "Aanvullende informatie")
 (:institutions-field-notes-placeholder . "Geschat aantal studenten, gewenste factureringscyclus, eventuele speciale wensen...")
 (:institutions-submit . "Verzoek indienen")
 (:institutions-success-title . "Bedankt - Hiisi voor scholen en universiteiten")
 (:institutions-success-heading . "Bedankt!")
 (:institutions-success-body . "We hebben je aanvraag ontvangen. We bekijken de behoeften van je instelling en nemen binnen een week contact op.")
 (:institutions-success-back . "Terug naar start")

 ;; Footer
 (:footer-privacy . "Privacybeleid")
 (:footer-terms . "Servicevoorwaarden")

 ;; Early software notice
 (:early-software-notice . "Hiisi is in vroege ontwikkeling. Een bug gevonden of een suggestie?")

 ;; Privacybeleid
 (:privacy-title . "Privacybeleid")
 (:privacy-updated . "Laatst bijgewerkt: januari 2026")
 (:privacy-who-title . "Wie wij zijn")
 (:privacy-who-body . "Hiisi wordt beheerd door Lambda Symbolics OÜ, een bedrijf dat is geregistreerd in Estland. Als Ests bedrijf voldoen wij aan de Algemene Verordening Gegevensbescherming (AVG/GDPR) van de Europese Unie.")
 (:privacy-collect-title . "Gegevens die wij verzamelen")
 (:privacy-collect-intro . "Wanneer je Hiisi gebruikt, verzamelen wij de volgende informatie:")
 (:privacy-collect-account-key . "Accountgegevens: ")
 (:privacy-collect-account-val . "E-mailadres, weergavenaam en een veilig gehashte wachtwoordwaarde.")
 (:privacy-collect-learning-key . "Leerdata: ")
 (:privacy-collect-learning-val . "Je vertalingen, opgeslagen flashcards en repetitiegeschiedenis.")
 (:privacy-collect-usage-key . "Gebruiksgegevens: ")
 (:privacy-collect-usage-val . "Basisserverlogs voor beveiliging en foutopsporing.")
 (:privacy-use-title . "Hoe wij je gegevens gebruiken")
 (:privacy-use-auth-key . "Authenticatie: ")
 (:privacy-use-auth-val . "Om je identiteit te verifiëren en je account te beveiligen.")
 (:privacy-use-service-key . "Dienstverlening: ")
 (:privacy-use-service-val . "Om vertalingen te leveren en je flashcardverzameling te beheren.")
 (:privacy-use-ai-key . "AI-vertalingen: ")
 (:privacy-use-ai-val . "Je vertaalverzoeken worden naar de Claude API van Anthropic gestuurd om antwoorden te genereren. Zie het privacybeleid van Anthropic voor hoe zij deze gegevens verwerken.")
 (:privacy-third-title . "Diensten van derden")
 (:privacy-third-intro . "Wij gebruiken de volgende diensten van derden:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "Voor AI-gestuurde vertalingen.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "Voor het versturen van accountactivatie- en transactie-e-mails.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Voor de verwerking van abonnementsbetalingen.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "Wij gebruiken alleen essentiële cookies:")
 (:privacy-cookies-auth-key . "Authenticatietoken: ")
 (:privacy-cookies-auth-val . "Een veilige HTTP-only cookie om je ingelogd te houden.")
 (:privacy-cookies-lang-key . "Taalvoorkeur: ")
 (:privacy-cookies-lang-val . "Om je voorkeursinterface-taal te onthouden.")
 (:privacy-retention-title . "Bewaartermijn van gegevens")
 (:privacy-retention-body . "Je gegevens worden bewaard zolang je een account hebt. Wanneer je verwijdering aanvraagt, wordt je account gepland voor verwijdering over 14 dagen.")
 (:privacy-rights-title . "Jouw rechten (GDPR)")
 (:privacy-rights-intro . "Onder de GDPR heb je het recht om:")
 (:privacy-rights-access . "Toegang te krijgen tot je persoonsgegevens")
 (:privacy-rights-export . "Je gegevens te exporteren (beschikbaar op /app/api/export)")
 (:privacy-rights-correct . "Correctie van onjuiste gegevens aan te vragen")
 (:privacy-rights-delete . "Verwijdering van je account en gegevens aan te vragen")
 (:privacy-rights-object . "Bezwaar te maken tegen verwerking van je gegevens")
 (:privacy-rights-contact . "Om deze rechten uit te oefenen, neem contact met ons op via")
 (:privacy-contact-title . "Contact")
 (:privacy-contact-intro . "Voor privacygerelateerde vragen:")
 (:privacy-contact-email-label . "E-mail: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Gebruiksvoorwaarden
 (:terms-title . "Gebruiksvoorwaarden")
 (:terms-updated . "Laatst bijgewerkt: januari 2026")
 (:terms-1-title . "1. Beschrijving van de dienst")
 (:terms-1-body . "Hiisi is een app voor taalverwerving die automatische vertalingen met grammaticale uitleg en flashcards met gespreide herhaling biedt. De dienst wordt beheerd door Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Accountregistratie")
 (:terms-2-body . "Om Hiisi te gebruiken moet je een account maken met een geldig e-mailadres. Je bent verantwoordelijk voor de beveiliging van je accountgegevens.")
 (:terms-3-title . "3. Abonnement en betalingen")
 (:terms-3-body . "Hiisi biedt betaalde abonnementen (maandelijks en jaarlijks). Abonnementen worden verwerkt via Polar.sh.")
 (:terms-3-list-1 . "Abonnementen worden automatisch verlengd tenzij ze vóór de verlengingsdatum worden opgezegd.")
 (:terms-3-list-2 . "Terugbetalingen worden verleend in overeenstemming met toepasselijke consumentenwetgeving.")
 (:terms-3-list-3 . "Niet-betaling leidt tot verlies van toegang tot premiumfuncties.")
 (:terms-4-title . "4. Toegestaan gebruik")
 (:terms-4-intro . "Je stemt ermee in om niet:")
 (:terms-4-list-1 . "De dienst te gebruiken voor illegale doeleinden")
 (:terms-4-list-2 . "Te proberen gebruikslimieten of beveiligingsmaatregelen te omzeilen")
 (:terms-4-list-3 . "Je accountgegevens met anderen te delen")
 (:terms-4-list-4 . "Geautomatiseerde tools te gebruiken op een manier die de prestaties voor anderen verslechtert")
 (:terms-5-title . "5. Inhoud en intellectueel eigendom")
 (:terms-5-body-1 . "Door Hiisi gegenereerde vertalingen worden automatisch gemaakt en zijn mogelijk niet uniek. Je mag je vertalingen en flashcards voor persoonlijke doeleinden gebruiken, maar je hebt geen exclusieve auteursrechten op automatisch gegenereerde inhoud.")
 (:terms-5-body-2 . "De Hiisi-applicatie, branding en oorspronkelijke inhoud blijven eigendom van Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Beschikbaarheid van de dienst")
 (:terms-6-intro . "Hiisi wordt geleverd zoals die is. Wij garanderen niet:")
 (:terms-6-list-1 . "Ononderbroken of foutloze dienstverlening")
 (:terms-6-list-2 . "Nauwkeurigheid van automatisch gegenereerde vertalingen")
 (:terms-6-list-3 . "Beschikbaarheid van specifieke functies")
 (:terms-6-body . "Wij kunnen functies op elk moment wijzigen of beëindigen.")
 (:terms-7-title . "7. Beperking van aansprakelijkheid")
 (:terms-7-body-1 . "Voor zover wettelijk toegestaan is Lambda Symbolics OÜ niet aansprakelijk voor enige indirecte, incidentele, bijzondere of gevolgschade die voortvloeit uit je gebruik van Hiisi.")
 (:terms-7-body-2 . "Onze totale aansprakelijkheid is beperkt tot het bedrag dat je in de 12 maanden voorafgaand aan de claim voor de dienst hebt betaald.")
 (:terms-8-title . "8. Beëindiging van account")
 (:terms-8-body-1 . "Wij kunnen je account opschorten of beëindigen als je deze voorwaarden schendt. Je kunt op elk moment via de applicatie verwijdering van je account aanvragen.")
 (:terms-8-body-2 . "Na een verwijderverzoek wordt je account gepland voor verwijdering over 14 dagen.")
 (:terms-9-title . "9. Wijzigingen in de voorwaarden")
 (:terms-9-body . "Wij kunnen deze voorwaarden van tijd tot tijd bijwerken. Door Hiisi te blijven gebruiken na wijzigingen, accepteer je de nieuwe voorwaarden.")
 (:terms-10-title . "10. Toepasselijk recht")
 (:terms-10-body . "Op deze voorwaarden is het recht van Estland van toepassing. Eventuele geschillen worden beslecht door de rechtbanken van Estland.")
 (:terms-contact-title . "Contact")
 (:terms-contact-intro . "Voor vragen over deze voorwaarden:")
 (:terms-contact-email-label . "E-mail: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Decks
 (:decks-title . "Stapels")
 (:decks-subtitle . "Maak aangepaste stapels en deel ze met anderen.")
 (:decks-create-title . "Stapel maken")
 (:decks-name-placeholder . "Stapelnaam")
 (:decks-desc-placeholder . "Beschrijving")
 (:decks-create-btn . "Stapel maken")
 (:decks-edit-title . "Stapel bewerken")
 (:decks-edit-btn . "Stapel bewerken")
 (:decks-update-btn . "Wijzigingen opslaan")
 (:decks-default-badge . "Automatisch")
 (:decks-default-description . "Deze stapel wordt automatisch beheerd voor dit talenpaar.")
 (:decks-default-readonly . "Automatische stapels hebben vaste namen en beschrijvingen.")
 (:decks-error-name-required . "De naam van de stapel is verplicht.")
 (:decks-error-name-too-long . "De naam van de stapel mag maximaal ~A tekens bevatten.")
 (:decks-error-desc-too-long . "De beschrijving van de stapel mag maximaal ~A tekens bevatten.")
 (:decks-error-default-readonly . "Automatische stapels kunnen niet worden bewerkt.")
 (:decks-your-title . "Jouw stapels")
 (:decks-col-updated . "Bijgewerkt")
 (:decks-no-decks . "Nog geen stapels.")
 (:decks-open-btn . "Openen")
 (:decks-no-desc . "Geen beschrijving.")
 (:decks-share-title . "Deellink")
 (:decks-share-info . "Iedereen met deze link kan de stapel importeren:")
 (:decks-share-copy . "Link kopiëren")
 (:decks-share-copied . "Gekopieerd")
 (:decks-add-from-flashcards-title . "Vertalingen toevoegen")
 (:decks-add-from-flashcards-info . "Kies een kaart om de vertaling aan deze stapel toe te voegen.")
 (:decks-open-flashcards . "Toevoegen vanuit kaartjes")
 (:decks-filter-from . "Brontaal")
 (:decks-filter-to . "Doeltaal")
 (:decks-filter-any . "Elke taal")
 (:decks-filter-include-assigned . "Neem kaartjes op die al in een stapel zitten")
 (:decks-flashcards-add . "Toevoegen")
 (:decks-flashcards-added . "Toegevoegd")
 (:decks-flashcards-in-deck . "In een andere stapel")
 (:decks-flashcards-empty . "Geen kaartjes komen overeen met deze filters.")
 (:decks-items-title . "Stapelinhoud")
 (:decks-col-original . "Origineel")
 (:decks-col-translated . "Vertaling")
 (:decks-col-lang . "Doeltaal")
 (:decks-no-items . "Nog geen items.")
 (:decks-share-page-title . "Stapel delen")
 (:decks-share-preview . "Voorbeeld en importeer deze stapel.")
 (:decks-import-title . "Importeren")
 (:decks-import-btn . "Stapel importeren")
 (:starter-decks-title . "Officiële startdecks")
 (:starter-decks-subtitle . "Kies een taaltriplet, bekijk officiële Hiisi-thema's en importeer kant-en-klare studiedecks.")
 (:starter-decks-marketplace-btn . "Officiële decks")
 (:starter-decks-explanation-language . "Uitlegtaal")
 (:starter-decks-search-label . "Zoeken")
 (:starter-decks-search-placeholder . "Zoek naar thema's voor startdecks")
 (:starter-decks-apply-filters . "Filters toepassen")
 (:starter-decks-select-triplet-hint . "Kies een bron- en doeltaal om een deck te bekijken.")
 (:starter-decks-official-badge . "Officieel")
 (:starter-decks-by-hiisi . "Van Hiisi")
 (:starter-decks-preview-btn . "Bekijken")
 (:starter-decks-card-count . "~A kaarten")
 (:starter-decks-concepts-title . "Geplande kaartconcepten")
 (:starter-decks-sample-title . "Voorbeeldkaarten")
 (:starter-decks-generating . "Deck wordt gegenereerd...")
 (:starter-decks-generating-detail . "Dit deck wordt nu voor jouw taaltriplet gegenereerd. Laat deze pagina open of kom zo terug.")
 (:starter-decks-generation-failed . "Genereren mislukt")
 (:starter-decks-generation-failed-detail . "De laatste genereerpoging is mislukt. Probeer het deck opnieuw te importeren.")
 (:starter-decks-login-detail . "Log in om dit deck in je verzameling te importeren.")
 (:starter-decks-subscribe-btn . "Bekijk plannen")
 (:starter-decks-subscribe-detail . "Startdecks zijn beschikbaar met een actief abonnement of een proefperiode.")
 (:starter-deck-topic-greetings-title . "Begroetingen en kennismaking")
 (:starter-deck-topic-greetings-description . "Begroetingen, namen, beleefde basiszinnen en uitdrukkingen voor een eerste ontmoeting.")
 (:starter-deck-topic-travel-title . "Essentieel reizen")
 (:starter-deck-topic-travel-description . "Stations, tickets, prijzen, hulp vragen en je verplaatsen.")
 (:starter-deck-topic-numbers-title . "Getallen en prijzen")
 (:starter-deck-topic-numbers-description . "Tellen, totalen, prijzen, verdiepingen en alledaagse hoeveelheden.")
 (:starter-deck-topic-time-title . "Tijd en data")
 (:starter-deck-topic-time-description . "Dagen, maanden, afspraken, kloktijden en relatieve datums.")
 (:starter-deck-topic-food-title . "Restaurant en eten")
 (:starter-deck-topic-food-description . "Bestellen, dieetwensen, drankjes, de rekening en alledaagse maaltijden buitenshuis.")
 (:starter-deck-topic-emergency-title . "Noodsituaties en gezondheid")
 (:starter-deck-topic-emergency-description . "Artsen, apotheken, symptomen, lichaamsdelen en dringende hulp.")
 (:starter-deck-topic-directions-title . "Routebeschrijvingen en vervoer")
 (:starter-deck-topic-directions-description . "Afslaan, haltes, tickets, perrons en je verplaatsen in de stad.")

 ;; Flashcards management page
 (:flashcards-title . "Mijn kaarten")
 (:flashcards-subtitle . "Al je opgeslagen kaarten op één plek. Zoek, organiseer en beheer.")
 (:flashcards-search-placeholder . "Kaarten zoeken...")
 (:flashcards-hide-perfected . "Beheerste kaartjes verbergen")
 (:flashcards-col-original . "Origineel")
 (:flashcards-col-translated . "Vertaling")
 (:flashcards-no-cards . "Nog geen kaarten. Begin met vertalen om er een paar te maken!")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Leer talen op een complete manier")
 (:landing-hero-subheadline . "Krijg vertalingen met volledige grammaticale analyse en bouw blijvende woordenschat op via gespreid herhalen met flashcards.")
 (:landing-hero-trust-line . "7 dagen gratis proberen met 100 vertalingen. Op elk moment opzegbaar.")
 (:landing-credibility-languages . "14 talen")
 (:landing-credibility-ai . "Grammaticale analyse inbegrepen")
 (:landing-step-1-title . "Vertaal elke tekst")
 (:landing-step-1-desc . "Voer een woord of zin in. Krijg een vertaling met volledige grammaticale analyse.")
 (:landing-step-2-title . "Bewaar als flashcards")
 (:landing-step-2-desc . "Bewaar vertalingen die je wilt onthouden. Flashcards worden automatisch aangemaakt.")
 (:landing-step-3-title . "Herhaal en onthoud")
 (:landing-step-3-desc . "Gespreide herhaling plant herhalingen op het perfecte moment voor het langetermijngeheugen.")
 (:landing-feature-grammar-title . "Begrijp grammatica, niet alleen woorden")
 (:landing-feature-grammar-desc . "Elke vertaling bevat een gedetailleerde grammaticale analyse -- woordvormen, naamvallen, vervoegingen uitgelegd in je eigen taal.")
 (:landing-feature-srs-title . "Wetenschappelijk onderbouwd onthouden")
 (:landing-feature-srs-desc . "Het SM-2-algoritme past zich aan je prestaties aan. Moeilijke kaarten verschijnen vaker. Kaarten die je kent wijken terug.")
 (:landing-feature-share-title . "Deel kaartenstapels met leerlingen")
 (:landing-feature-share-desc . "Docenten kunnen eigen kaartenstapels maken en delen via een link. Leerlingen importeren de stapel en beginnen direct met herhalen.")
 (:landing-pricing-trial-note . "Inclusief 7 dagen gratis proefperiode")
 (:landing-pricing-monthly-after . "7 dagen gratis, daarna ~A/maand")
 (:landing-pricing-annual-after . "7 dagen gratis, daarna ~A/jaar")
 (:landing-faq-title . "Veelgestelde vragen")
 (:landing-faq-trial-cap-q . "Hoeveel vertalingen krijg ik tijdens de proefperiode?")
 (:landing-faq-trial-cap-a . "Je krijgt 100 vertalingen tijdens je 7-daagse proefperiode. Na het abonnement krijg je 600 per maand.")
 (:landing-final-cta-title . "Begin vandaag met leren")
 (:landing-final-cta-subtitle . "Sluit je aan bij Hiisi en begin met het opbouwen van woordenschat die beklijft.")

 ;; Trial status (in-app)
 (:trial-status . "Gratis proefperiode")
 (:error-trial-quota-exceeded . "Proefvertalingslimiet bereikt")
 (:error-trial-quota-detail . "Je hebt alle 100 proefvertalingen gebruikt. Abonneer om door te leren.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Flashcard aanmaken")
 (:custom-flashcard-edit-title . "Flashcard bewerken")
 (:custom-flashcard-original . "Originele tekst")
 (:custom-flashcard-translated . "Vertaling")
 (:custom-flashcard-lang-from . "Brontaal")
 (:custom-flashcard-lang-to . "Doeltaal")
 (:custom-flashcard-note . "Educatieve notitie")
 (:custom-flashcard-forms . "Grammaticale analyse")
 (:custom-flashcard-form-term . "Term")
 (:custom-flashcard-form-explanation . "Uitleg")
 (:custom-flashcard-add-form . "Grammaticale term toevoegen")
 (:custom-flashcard-remove-form . "Verwijderen")
 (:custom-flashcard-ai-fill . "Invullen met AI")
 (:custom-flashcard-create-btn . "Flashcard aanmaken")
 (:custom-flashcard-update-btn . "Wijzigingen opslaan")

 ;; Probleemrapportage
 (:issues-open-button . "Probleem melden")
 (:issues-modal-title . "Probleem melden")
 (:issues-modal-subtitle . "Beschrijf wat er misging. We voegen je huidige pagina automatisch toe.")
 (:issues-title-label . "Korte titel")
 (:issues-title-placeholder . "Korte samenvatting van het probleem")
 (:issues-message-label . "Wat is er gebeurd?")
 (:issues-message-placeholder . "Vermeld stappen om te reproduceren, verwacht gedrag en wat er in plaats daarvan gebeurde.")
 (:issues-submit . "Melding verzenden")
 (:issues-cancel . "Annuleren")
 (:issues-success . "Bedankt. Je probleemmelding is verzonden.")
 (:issues-error-required . "Beschrijf het probleem voordat je verzendt.")
 (:issues-error-title-too-long . "De titel van de melding is te lang. Houd deze onder 160 tekens.")
 (:issues-error-too-long . "De melding is te lang. Houd het onder 4000 tekens.")
 (:issues-error-rate-limit . "Te veel meldingen vanaf deze bron. Wacht even en probeer later opnieuw.")
 (:issues-error-generic . "De probleemmelding kon niet worden verzonden. Probeer het opnieuw.")

)
