;;; Dutch translations

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Nederlands")
 (:lang-flag . "🇳🇱")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Kies je taal")
 (:lang-modal-subtitle . "Selecteer je voorkeurstaal voor de interface:")

 ;; Navigation
 (:nav-translate . "Vertalen")
 (:nav-review . "Herhalen")
 (:nav-flashcards . "Mijn kaarten")
 (:nav-dashboard . "Dashboard")
 (:nav-decks . "Decks")
 (:nav-logout . "Uitloggen")
 (:nav-home . "Home")
 (:nav-pricing . "Prijzen")
 (:nav-export-data . "Gegevens exporteren")

 ;; App title and branding
 (:app-title . "Hiisi - Talen leren")
 (:app-tagline . "Leer talen door vertalingen")

 ;; Landing page
 (:landing-hero-title . "Beheers elke taal")
 (:landing-hero-subtitle . "Vertaal alles. Genereer automatisch flashcards die je leren waarom het zo werkt.")
 (:landing-cta . "Begin met leren")
 (:landing-learn-more . "Meer informatie")
 (:landing-how-it-works . "Hoe het werkt")
 (:landing-feature-1-title . "Automatische flashcards")
 (:landing-feature-1-desc . "Elke vertaling genereert automatisch flashcards met grammaticale uitleg. Geen handmatige kaarten maken.")
 (:landing-feature-2-title . "Gespreide herhaling")
 (:landing-feature-2-desc . "Het SM-2 algoritme plant herhalingen op optimale intervallen. Leer efficient, onthoud permanent.")
 (:landing-feature-3-title . "Grammatica-onderwijs")
 (:landing-feature-3-desc . "Elke vertaling legt grammatica, woordwortels en zinsstructuur uit. Begrijp het waarom, niet alleen het wat.")
 (:landing-free-trial . "7 dagen gratis proberen. Geen creditcard nodig.")
 (:landing-start-trial . "Start gratis proefperiode")
 (:landing-best-value . "Beste waarde")
 (:landing-cta-title . "Klaar om talen te leren via grammatica in plaats van uit het hoofd leren?")
 (:landing-cta-subtitle . "Elke vertaling wordt een leermogelijkheid. Elke flashcard leert je waarom.")
 (:landing-signup-free . "Gratis aanmelden")

 ;; Auth pages
 (:auth-register . "Registreren")
 (:auth-login . "Inloggen")
 (:auth-logout . "Uitloggen")
 (:auth-email . "E-mail")
 (:auth-password . "Wachtwoord")
 (:auth-password-again . "Bevestig wachtwoord")
 (:auth-display-name . "Weergavenaam")
 (:auth-register-title . "Registreer bij Hiisi")
 (:auth-register-subtitle . "Maak een nieuw account aan")
 (:auth-login-title . "Log in bij Hiisi")
 (:auth-login-subtitle . "Voer je gegevens in")
 (:auth-forgot-password . "Wachtwoord vergeten?")
 (:auth-no-account . "Heb je geen account?")
 (:auth-have-account . "Heb je al een account?")
 (:auth-google . "Google")
 (:auth-account-created . "Account aangemaakt!")
 (:auth-check-email . "Controleer je e-mail voor de activatielink.")
 (:auth-redirect-login . "Doorsturen naar inloggen over")
 (:auth-seconds . "seconden...")
 (:auth-go-now . "Ga nu")
 (:auth-not-activated . "Account niet geactiveerd")
 (:auth-activate-title . "Activeer je account!")
 (:auth-activated . "Account geactiveerd!")
 (:auth-activated-message . "Je account is geactiveerd. Je kunt Hiisi nu gebruiken.")
 (:auth-redirecting . "Doorsturen over")
 (:auth-go-to-app . "Naar de app")
 (:auth-resend-title . "Activatiemail opnieuw verzenden")
 (:auth-resend-subtitle . "Voer je e-mailadres in om een nieuwe activatielink te ontvangen.")
 (:auth-resend-button . "Activatiemail opnieuw verzenden")
 (:auth-resend-success . "Activatiemail verzonden!")
 (:auth-resend-success-detail . "Controleer je inbox voor de nieuwe activatielink.")
 (:auth-resend-rate-limited . "Wacht een paar minuten voordat je nog een activatiemail aanvraagt.")
 (:auth-resend-cooldown . "Je kunt over ~a seconden een nieuwe mail aanvragen.")
 (:auth-back-to-login . "Terug naar inloggen")
 (:auth-forgot-password-title . "Wachtwoord vergeten")
 (:auth-forgot-password-subtitle . "Voer je e-mailadres in en we sturen je een link om je wachtwoord opnieuw in te stellen.")
 (:auth-send-reset-link . "Stuur resetlink")
 (:auth-reset-email-sent . "Resetlink verzonden!")
 (:auth-reset-email-sent-detail . "Als er een account bestaat met dit e-mailadres, ontvang je binnenkort een link om je wachtwoord opnieuw in te stellen.")
 (:auth-reset-rate-limited . "Wacht een paar minuten voordat je nog een wachtwoord-reset aanvraagt.")
 (:auth-reset-invalid-token . "Deze resetlink is ongeldig of verlopen.")
 (:auth-reset-password-title . "Wachtwoord opnieuw instellen")
 (:auth-reset-password-subtitle . "Voer hieronder je nieuwe wachtwoord in.")
 (:auth-new-password . "Nieuw wachtwoord")
 (:auth-confirm-new-password . "Bevestig nieuw wachtwoord")
 (:auth-reset-password . "Wachtwoord opnieuw instellen")
 (:auth-password-changed . "Wachtwoord gewijzigd!")
 (:auth-password-changed-detail . "Je wachtwoord is succesvol gewijzigd. Je kunt nu inloggen met je nieuwe wachtwoord.")
 (:auth-change-password-title . "Wachtwoord wijzigen")
 (:auth-change-password-subtitle . "Werk het wachtwoord van je account bij.")
 (:auth-current-password . "Huidig wachtwoord")
 (:auth-change-password . "Wachtwoord wijzigen")
 (:auth-back-to-app . "Terug naar app")
 (:auth-password-updated . "Wachtwoord bijgewerkt!")
 (:auth-password-updated-detail . "Je wachtwoord is succesvol bijgewerkt.")

 ;; Translation page
 (:translate-title . "Vertalen")
 (:translate-input-label . "Te vertalen tekst")
 (:translate-input-placeholder . "Voer tekst in om te vertalen...")
 (:translate-from . "Van:")
 (:translate-to . "Naar:")
 (:translate-submit . "Vertalen")
 (:translate-save . "Opslaan als flashcard")
 (:translate-saved . "Opgeslagen!")
 (:translate-like . "Leuk")
 (:translate-dislike . "Niet leuk")
 (:translate-char-limit . "tekens over")
 (:translate-auto-detect . "Elke (Automatisch detecteren)")
 (:translate-empty-state . "Voer hierboven tekst in en klik op Vertalen om het resultaat met grammaticale uitleg te zien")
 (:translate-select-deck-placeholder . "Selecteer stapel (optioneel)")
 (:translate-new-deck . "Nieuwe stapel")
 (:translate-add-to-deck . "Toevoegen aan stapel")
 (:translate-bookmark . "Opslaan")
 (:translate-bookmarked . "Opgeslagen")
 (:translate-retry . "Opnieuw proberen")
 (:translate-like-tooltip . "Goede vertaling")
 (:translate-dislike-tooltip . "Slechte vertaling - vraag een nieuwe aan")
 (:translate-dislike-confirm . "Dit genereert een nieuwe vertaling. Doorgaan?")
 (:translate-liked . "Leuk!")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Doel")
 (:translate-deck-create-title . "Nieuwe stapel maken")
 (:translate-deck-name-label . "Stapelnaam")
 (:translate-deck-name-placeholder . "bijv. Basis Fins")
 (:translate-deck-description-label . "Beschrijving (optioneel)")
 (:translate-deck-cancel . "Annuleren")
 (:translate-deck-create . "Maken")
 (:translate-rate-label . "Vertaling beoordelen")
 (:flashcards-delete-confirm . "Weet je zeker dat je deze kaart wilt verwijderen?")
 (:flashcards-deck-search-placeholder . "Stapels zoeken...")
 (:flashcards-no-decks . "Nog geen stapels. Maak er eerst een!")
 (:flashcards-deck-cancel . "Annuleren")

 ;; Flashcard review
 (:review-title . "Herhalen")
 (:review-session-title . "Herhalingssessie")
 (:review-session-subtitle . "Oefen je opgeslagen flashcards")
 (:review-start . "Start herhaling")
 (:review-no-cards . "Geen kaarten te herhalen")
 (:review-no-cards-desc . "Je hebt momenteel geen flashcards die herhaald moeten worden.")
 (:review-no-cards-hint . "Vertaal wat tekst en klik op \"Opslaan als flashcard\" om je stapel op te bouwen!")
 (:review-start-translating . "Begin met vertalen")
 (:review-show-answer . "Toon antwoord")
 (:review-click-reveal . "Klik om antwoord te tonen")
 (:review-grammar-breakdown . "Grammaticale uitleg")
 (:review-how-well . "Hoe goed herinnerde je het?")
 (:review-again . "Opnieuw")
 (:review-hard . "Moeilijk")
 (:review-good . "Goed")
 (:review-easy . "Makkelijk")
 (:review-progress . "Kaart ~a van ~a")
 (:review-complete . "Sessie voltooid!")
 (:review-complete-msg . "Je hebt ~a kaarten herhaald")
 (:review-correct . "Correct")
 (:review-accuracy . "Nauwkeurigheid")
 (:review-again-btn . "Opnieuw herhalen")
 (:review-translate-more . "Meer vertalen")
 (:review-streak . "dagen op rij")

 ;; Dashboard
 (:dashboard-title . "Dashboard")
 (:dashboard-cards-due . "Kaarten voor vandaag")
 (:dashboard-total-cards . "Totaal kaarten")
 (:dashboard-subscription . "Abonnement")
 (:dashboard-subscribed-until . "Geabonneerd tot")
 (:dashboard-not-subscribed . "Niet geabonneerd")
 (:dashboard-recent . "Recente vertalingen")
 (:dashboard-no-translations . "Nog geen vertalingen")
 (:dashboard-streak . "Herhalingsreeks")
 (:dashboard-days . "dagen")
 (:dashboard-quick-actions . "Snelle acties")
 (:dashboard-getting-started . "Aan de slag")
 (:dashboard-tip-1 . "Vertaal tekst die je wilt leren")
 (:dashboard-tip-2 . "Klik op \"Opslaan als flashcard\" bij vertalingen die je wilt onthouden")
 (:dashboard-tip-3 . "Herhaal je flashcards regelmatig - gespreide herhaling helpt je om langdurig te onthouden")
 (:dashboard-tip-4 . "Beoordeel eerlijk - het helpt het algoritme om je herhalingen optimaal te plannen")

 ;; Account
 (:account-title . "Account")
 (:account-subtitle . "Beheer je accountinstellingen en verwijderingsplanning.")
 (:account-deletion-title . "Account verwijderen")
 (:account-deletion-scheduled . "Je account staat gepland voor verwijdering op ~A.")
 (:account-deletion-cancel-hint . "Je kunt voor deze datum annuleren om je account te behouden.")
 (:account-deletion-cancel . "Verwijdering annuleren")
 (:account-deletion-request . "Je kunt op elk moment een verzoek tot verwijdering van je account indienen. Verwijdering wordt 14 dagen na bevestiging gepland. Als je na verwijdering van gedachten verandert, neem contact op met support.")
 (:account-deletion-confirm . "Accountverwijdering plannen over 14 dagen vanaf vandaag?")
 (:account-deletion-schedule . "Verwijdering plannen")
 (:account-reminders-title . "E-mailherinneringen")
 (:account-reminders-subtitle . "Beheer herinneringen voor herhalen en doorgaan voor dit account.")
 (:account-reminders-opt-out . "Herinneringen voor herhalen en doorgaan uitschakelen")
 (:account-reminders-save . "Voorkeuren opslaan")

 ;; Subscription
 (:subscribe-title . "Eenvoudige prijzen")
 (:subscribe-choose-plan . "Kies je abonnement")
 (:subscribe-start-today . "Begin vandaag met leren met een 7-daagse gratis proefperiode")
 (:subscribe-monthly . "Maandelijks")
 (:subscribe-annual . "Jaarlijks")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/maand")
 (:subscribe-per-year . "/jaar")
 (:subscribe-monthly-desc . "600 vertalingen per maand")
 (:subscribe-unlimited-flashcards . "Onbeperkte flashcards")
 (:subscribe-grammar-explanations . "Grammatica-uitleg")
 (:subscribe-spaced-repetition . "Gespreide herhaling")
 (:subscribe-annual-desc . "Bespaar €20 - twee maanden gratis!")
 (:subscribe-cta . "Abonneren")
 (:subscribe-success . "Abonnement gelukt!")
 (:subscribe-manage . "Beheer abonnement")
 (:subscribe-activated . "Abonnement geactiveerd!")
 (:subscribe-thank-you . "Bedankt voor je abonnement. Je account is nu actief.")
 (:subscribe-start-learning . "Begin met leren")
 (:subscribe-management . "Abonnementsbeheer")
 (:subscribe-active . "Actief abonnement")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Actief")
 (:subscribe-days-remaining . "Dagen resterend:")
 (:subscribe-renews-on . "Verlengt op:")
 (:subscribe-no-subscription . "Geen actief abonnement")
 (:subscribe-access-features . "Abonneer om toegang te krijgen tot alle functies.")
 (:subscribe-view-plans . "Bekijk abonnementen")
 (:subscribe-faq-title . "Veelgestelde vragen")
 (:subscribe-faq-trial-q . "Wat gebeurt er na de gratis proefperiode?")
 (:subscribe-faq-trial-a . "Na je 7-daagse gratis proefperiode word je in rekening gebracht voor je gekozen abonnement. Je kunt op elk moment voor het einde van de proefperiode opzeggen.")
 (:subscribe-faq-cancel-q . "Kan ik op elk moment opzeggen?")
 (:subscribe-faq-cancel-a . "Ja! Je kunt je abonnement op elk moment opzeggen. Je behoudt toegang tot het einde van je factureringsperiode.")
 (:subscribe-faq-payment-q . "Welke betaalmethoden accepteren jullie?")
 (:subscribe-faq-payment-a . "We accepteren alle gangbare creditcards en betaalkaarten via onze betalingspartner Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Er ging iets mis")
 (:error-not-found . "Pagina niet gevonden")
 (:error-unauthorized . "Log in om door te gaan")
 (:error-subscription-required . "Abonnement vereist")
 (:error-text-too-long . "Tekst is te lang. Maximale vertalingslengte is 120 tekens.")
 (:error-input-too-long . "Invoer te lang")
 (:error-unknown-source-lang . "De brontaal die je hebt geselecteerd wordt niet ondersteund.")
 (:error-unknown-target-lang . "De doeltaal die je hebt geselecteerd wordt niet ondersteund.")
 (:error-unknown-language . "Onbekende taal")
 (:error-translation-unavailable . "Vertaalservice is tijdelijk niet beschikbaar. Probeer het zo opnieuw.")
 (:error-translation-failed . "Vertaling mislukt")
 (:error-translation-retry . "Kon na meerdere pogingen geen vertaling genereren. Probeer je tekst anders te formuleren.")
 (:error-quota-exceeded . "Vertaallimiet bereikt")
 (:error-quota-exceeded-detail . "Je hebt al je vertalingen voor deze maand gebruikt. Je quotum wordt automatisch elke maand gereset.")
 (:quota-warning . "Resterende vertalingen: ~A")
 (:quota-low-warning . "Nog maar ~A vertalingen over. Overweeg om meer te kopen.")
 (:top-up-button . "Koop meer vertalingen")
 (:top-up-success . "Top-up gelukt! Je hebt nu ~A extra vertalingen.")
 (:top-up-price . "€5")
 (:top-up-amount . "300 vertalingen")
 (:loading . "Laden...")
 (:empty-state . "Hier is nog niets")

 ;; Institutions
 (:institutions-page-title . "Hiisi voor scholen - institutionele licenties")
 (:institutions-hero-title . "Hiisi voor scholen")
 (:institutions-hero-subtitle . "Geef je studenten AI-ondersteund taalonderwijs")
 (:institutions-section-title . "Institutionele licenties")
 (:institutions-section-body . "We bieden volumelicenties voor scholen, universiteiten en taalinstituten. Studenten met e-mailadressen van je domein krijgen automatisch volledige toegang.")
 (:institutions-benefit-1 . "Automatische inschrijving voor studenten met institutionele e-mail")
 (:institutions-benefit-2 . "Geen afzonderlijke studentenaccounts om te beheren")
 (:institutions-benefit-3 . "Flexibele factureringsopties")
 (:institutions-benefit-4 . "Toegewijde ondersteuning voor docenten")
 (:institutions-request-title . "Vraag een licentie aan")
 (:institutions-request-subtitle . "Vul het formulier hieronder in en we nemen binnen 2 werkdagen contact op.")
 (:institutions-field-name . "Naam van de instelling")
 (:institutions-field-name-placeholder . "Universiteit van Helsinki")
 (:institutions-field-contact-name . "Contactpersoon")
 (:institutions-field-contact-name-placeholder . "Jouw naam")
 (:institutions-field-contact-email . "Contact-e-mail")
 (:institutions-field-contact-email-placeholder . "jij@universiteit.nl")
 (:institutions-field-domains . "E-maildomeinen")
 (:institutions-field-domains-placeholder . "universiteit.nl, cs.universiteit.nl")
 (:institutions-field-domains-help . "Komma-gescheiden lijst met e-maildomeinen van je instelling")
 (:institutions-field-notes . "Aanvullende informatie")
 (:institutions-field-notes-placeholder . "Geschat aantal studenten, gewenste factureringscyclus, eventuele speciale wensen...")
 (:institutions-submit . "Verzoek indienen")
 (:institutions-success-title . "Bedankt - Hiisi voor scholen")
 (:institutions-success-heading . "Bedankt!")
 (:institutions-success-body . "We hebben je aanvraag voor een institutionele licentie ontvangen. Ons team beoordeelt je aanvraag en neemt binnen 2 werkdagen contact op.")
 (:institutions-success-back . "Terug naar start")

 ;; Footer
 (:footer-privacy . "Privacybeleid")
 (:footer-terms . "Servicevoorwaarden")
 (:footer-contact . "Contact")

 ;; Early software notice
 (:early-software-notice . "Hiisi is in vroege ontwikkeling. Een bug gevonden of een suggestie?")
 (:early-software-contact . "Neem contact op via")

 ;; Privacy Policy
 (:privacy-title . "Privacy Policy")
 (:privacy-updated . "Last updated: January 2026")
 (:privacy-who-title . "Who We Are")
 (:privacy-who-body . "Hiisi is operated by Lambda Symbolics OÜ, a company registered in Estonia. As an Estonian company, we comply with the European Union's General Data Protection Regulation (GDPR).")
 (:privacy-collect-title . "Data We Collect")
 (:privacy-collect-intro . "We collect the following information when you use Hiisi:")
 (:privacy-collect-account-key . "Account information: ")
 (:privacy-collect-account-val . "Email address, display name, and a securely hashed password.")
 (:privacy-collect-learning-key . "Learning data: ")
 (:privacy-collect-learning-val . "Your translations, saved flashcards, and review history.")
 (:privacy-collect-usage-key . "Usage data: ")
 (:privacy-collect-usage-val . "Basic server logs for security and debugging purposes.")
 (:privacy-use-title . "How We Use Your Data")
 (:privacy-use-auth-key . "Authentication: ")
 (:privacy-use-auth-val . "To verify your identity and secure your account.")
 (:privacy-use-service-key . "Service delivery: ")
 (:privacy-use-service-val . "To provide translations and manage your flashcard collection.")
 (:privacy-use-ai-key . "AI translations: ")
 (:privacy-use-ai-val . "Your translation requests are sent to Anthropic's Claude API to generate responses. See Anthropic's privacy policy for how they handle this data.")
 (:privacy-third-title . "Third-Party Services")
 (:privacy-third-intro . "We use the following third-party services:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "For AI-powered translations.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "For sending account activation and transactional emails.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "For subscription payment processing.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "We use only essential cookies:")
 (:privacy-cookies-auth-key . "Authentication token: ")
 (:privacy-cookies-auth-val . "A secure, HTTP-only cookie to keep you logged in.")
 (:privacy-cookies-lang-key . "Language preference: ")
 (:privacy-cookies-lang-val . "To remember your preferred UI language.")
 (:privacy-retention-title . "Data Retention")
 (:privacy-retention-body . "Your data is stored as long as you maintain an account. When you request deletion, your account is scheduled for deletion in 14 days.")
 (:privacy-rights-title . "Your Rights (GDPR)")
 (:privacy-rights-intro . "Under GDPR, you have the right to:")
 (:privacy-rights-access . "Access your personal data")
 (:privacy-rights-export . "Export your data (available at /app/api/export)")
 (:privacy-rights-correct . "Request correction of inaccurate data")
 (:privacy-rights-delete . "Request deletion of your account and data")
 (:privacy-rights-object . "Object to processing of your data")
 (:privacy-rights-contact . "To exercise these rights, contact us at")
 (:privacy-contact-title . "Contact")
 (:privacy-contact-intro . "For privacy-related inquiries:")
 (:privacy-contact-email-label . "Email: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Estonia")

 ;; Terms of Service
 (:terms-title . "Terms of Service")
 (:terms-updated . "Last updated: January 2026")
 (:terms-1-title . "1. Service Description")
 (:terms-1-body . "Hiisi is a language learning application that provides AI-powered translations with grammatical explanations and spaced repetition flashcards. The service is operated by Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Account Registration")
 (:terms-2-body . "To use Hiisi, you must create an account with a valid email address. You are responsible for maintaining the security of your account credentials.")
 (:terms-3-title . "3. Subscription and Payments")
 (:terms-3-body . "Hiisi offers paid subscription plans (monthly and annual). Subscriptions are processed through Polar.sh.")
 (:terms-3-list-1 . "Subscriptions auto-renew unless cancelled before the renewal date.")
 (:terms-3-list-2 . "Refunds are provided in accordance with applicable consumer protection laws.")
 (:terms-3-list-3 . "Non-payment results in loss of access to premium features.")
 (:terms-4-title . "4. Acceptable Use")
 (:terms-4-intro . "You agree not to:")
 (:terms-4-list-1 . "Use the service for any illegal purpose")
 (:terms-4-list-2 . "Attempt to circumvent usage limits or security measures")
 (:terms-4-list-3 . "Share your account credentials with others")
 (:terms-4-list-4 . "Use automated tools to access the service in a way that degrades performance for others")
 (:terms-5-title . "5. Content and Intellectual Property")
 (:terms-5-body-1 . "Translations generated by Hiisi are created using AI and may not be unique. You may use your translations and flashcards for any personal purpose, but you do not hold exclusive authorship rights over AI-generated content.")
 (:terms-5-body-2 . "The Hiisi application, branding, and original content remain the property of Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Service Availability")
 (:terms-6-intro . "Hiisi is provided on an \"as-is\" basis. We do not guarantee:")
 (:terms-6-list-1 . "Uninterrupted or error-free service")
 (:terms-6-list-2 . "Accuracy of AI-generated translations")
 (:terms-6-list-3 . "Availability of specific features")
 (:terms-6-body . "We may modify or discontinue features at any time.")
 (:terms-7-title . "7. Limitation of Liability")
 (:terms-7-body-1 . "To the maximum extent permitted by law, Lambda Symbolics OÜ shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of Hiisi.")
 (:terms-7-body-2 . "Our total liability shall not exceed the amount you paid for the service in the 12 months preceding the claim.")
 (:terms-8-title . "8. Account Termination")
 (:terms-8-body-1 . "We may suspend or terminate your account if you violate these terms. You may request account deletion at any time through the application.")
 (:terms-8-body-2 . "Upon deletion request, your account is scheduled for deletion in 14 days.")
 (:terms-9-title . "9. Changes to Terms")
 (:terms-9-body . "We may update these terms from time to time. Continued use of Hiisi after changes constitutes acceptance of the new terms.")
 (:terms-10-title . "10. Governing Law")
 (:terms-10-body . "These terms are governed by the laws of Estonia. Any disputes shall be resolved in the courts of Estonia.")
 (:terms-contact-title . "Contact")
 (:terms-contact-intro . "For questions about these terms:")
 (:terms-contact-email-label . "Email: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Estonia")



 ;; Decks
 (:decks-title . "Stapels")
 (:decks-subtitle . "Maak aangepaste stapels en deel ze met anderen.")
 (:decks-create-title . "Stapel maken")
 (:decks-name-placeholder . "Stapelnaam")
 (:decks-desc-placeholder . "Beschrijving")
 (:decks-create-btn . "Stapel maken")
 (:decks-your-title . "Jouw stapels")
 (:decks-col-name . "Naam")
 (:decks-col-desc . "Beschrijving")
 (:decks-col-updated . "Bijgewerkt")
 (:decks-col-actions . "Acties")
 (:decks-no-decks . "Nog geen stapels.")
 (:decks-open-btn . "Openen")
 (:decks-no-desc . "Geen beschrijving.")
 (:decks-share-title . "Deellink")
 (:decks-share-info . "Iedereen met deze link kan de stapel importeren:")
 (:decks-add-trans-title . "Vertaling toevoegen")
 (:decks-trans-id-placeholder . "Vertaling-ID")
 (:decks-add-trans-btn . "Vertaling toevoegen")
 (:decks-items-title . "Stapelinhoud")
 (:decks-col-original . "Origineel")
 (:decks-col-translated . "Vertaling")
 (:decks-col-lang . "Doeltaal")
 (:decks-no-items . "Nog geen items.")
 (:decks-share-page-title . "Stapel delen")
 (:decks-share-preview . "Voorbeeld en importeer deze stapel.")
 (:decks-import-title . "Importeren")
 (:decks-import-btn . "Stapel importeren")

 ;; Flashcards management page
 (:flashcards-title . "Mijn kaarten")
 (:flashcards-subtitle . "Al je opgeslagen kaarten op één plek. Zoek, organiseer en beheer.")
 (:flashcards-search-placeholder . "Kaarten zoeken...")
 (:flashcards-col-original . "Origineel")
 (:flashcards-col-translated . "Vertaling")
 (:flashcards-col-lang . "Talen")
 (:flashcards-no-cards . "Nog geen kaarten. Begin met vertalen om er een paar te maken!")

)

 ;; API Errors (EN fallback)
 (:api-error-missing-text . "Missing text to translate.")
 (:api-error-invalid-translation-id . "Invalid translation ID.")
 (:api-error-translation-not-found . "The translation you tried to save no longer exists.")
 (:api-error-invalid-bookmark-id . "Invalid bookmark ID")
 (:api-error-bookmark-not-found . "Bookmark not found")
 (:api-error-forbidden . "Forbidden")
 (:api-error-failed-delete-bookmark . "Failed to delete bookmark")
 (:api-error-invalid-flashcard-id . "Invalid flashcard ID")
 (:api-error-missing-deck-id . "Missing deck_id")
 (:api-error-flashcard-not-found . "Flashcard not found")
 (:api-error-deck-not-found . "Deck not found")
 (:api-error-deck-name-required . "Deck name is required")
 (:api-error-session-expired . "Your review session has expired. Please start a new session.")
 (:api-error-invalid-card-id . "Invalid card ID.")
 (:api-error-invalid-rating . "Invalid rating.")
 (:api-error-rating-range . "Rating must be between 0 and 5.")
 (:api-error-card-not-found . "Card not found.")
 (:api-error-permission-denied . "You don't have permission to review this card.")
 (:api-error-unknown-source-lang . "Unknown source language.")
 (:api-error-unknown-target-lang . "Unknown target language.")
 (:api-error-failed-add-to-deck . "Failed to add to deck")

 ;; API Success messages
 (:api-success-added . "Added!")
 (:api-success-added-simple . "Added")

 ;; API Stats
 (:api-stats-due . "~A due")
 (:api-stats-total . "~A total")

 ;; Time units
 (:api-time-day . "day")
 (:api-time-days . "days")
 (:api-time-day-left . "day left")
 (:api-time-days-left . "days left")

 ;; Subscription status
 (:api-subscription-active . "Active")
 (:api-subscription-inactive . "Inactive")
 (:api-subscription-subscribe-hint . "Subscribe to unlock translations")

 ;; Generic status
 (:status-bad-request . "Bad Request")
 (:status-not-found . "Not Found")
 (:status-forbidden . "Forbidden")

)
