;;; Norwegian translations (Bokmål)
;;; This file must contain all keys from en.lisp

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Norsk")
 (:lang-flag . "🇳🇴")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Velg språk")
 (:lang-modal-subtitle . "Velg foretrukket språk for grensesnittet:")

 ;; Navigation
 (:nav-translate . "Oversett")
 (:nav-review . "Repeter")
 (:nav-flashcards . "Mine kort")
 (:nav-dashboard . "Oversikt")
 (:nav-decks . "Decks")
 (:nav-logout . "Logg ut")
 (:nav-home . "Hjem")
 (:nav-pricing . "Priser")
 (:nav-export-data . "Eksporter data")

 ;; App title and branding
 (:app-title . "Hiisi - Språklæring")
 (:app-tagline . "Lær språk gjennom oversettelser")

 ;; Landing page
 (:landing-hero-title . "Mestre ethvert språk")
 (:landing-hero-subtitle . "Oversett hva som helst. Generer automatisk flashcards som lærer deg hvorfor det fungerer slik.")
 (:landing-cta . "Begynn å lære")
 (:landing-learn-more . "Lær mer")
 (:landing-how-it-works . "Slik fungerer det")
 (:landing-feature-1-title . "Automatiske flashcards")
 (:landing-feature-1-desc . "Hver oversettelse genererer automatisk flashcards med grammatiske forklaringer. Ingen manuell kortlaging.")
 (:landing-feature-2-title . "Spredt repetisjon")
 (:landing-feature-2-desc . "SM-2-algoritmen planlegger repetisjoner i optimale intervaller. Lær effektivt, husk permanent.")
 (:landing-feature-3-title . "Grammatikkundervisning")
 (:landing-feature-3-desc . "Hver oversettelse forklarer grammatikk, ordrøtter og setningsstruktur. Forstå hvorfor, ikke bare hva.")
 (:landing-free-trial . "7 dagers gratis prøveperiode.")
 (:landing-start-trial . "Start gratis prøveperiode")
 (:landing-best-value . "Best verdi")
 (:landing-cta-title . "Klar til å lære språk gjennom grammatikk, ikke pugging?")
 (:landing-cta-subtitle . "Hver oversettelse blir en læringsmulighet. Hvert flashcard lærer deg hvorfor.")
 (:landing-signup-free . "Registrer deg gratis")

 ;; Auth pages
 (:auth-register . "Registrer")
 (:auth-login . "Logg inn")
 (:auth-logout . "Logg ut")
 (:auth-email . "E-post")
 (:auth-password . "Passord")
 (:auth-password-again . "Bekreft passord")
 (:auth-display-name . "Visningsnavn")
 (:auth-register-title . "Registrer deg på Hiisi")
 (:auth-register-subtitle . "Opprett en ny konto")
 (:auth-login-title . "Logg inn på Hiisi")
 (:auth-login-subtitle . "Skriv inn opplysningene dine")
 (:auth-login-invalid-credentials . "Ugyldig e-post eller passord.")
 (:auth-login-rate-limited . "For mange innloggingsforsok. Vent noen minutter og prov igjen.")
 (:auth-forgot-password . "Glemt passord?")
 (:auth-no-account . "Har du ikke konto?")
 (:auth-have-account . "Har du allerede en konto?")
 (:auth-google . "Google")
 (:auth-account-created . "Konto opprettet!")
 (:auth-check-email . "Sjekk e-posten din for aktiveringslenken.")
 (:auth-redirect-login . "Omdirigerer til innlogging om")
 (:auth-seconds . "sekunder...")
 (:auth-go-now . "Gå nå")
 (:auth-not-activated . "Konto ikke aktivert")
 (:auth-activate-title . "Aktiver kontoen din!")
 (:auth-activated . "Konto aktivert!")
 (:auth-activated-message . "Kontoen din er aktivert. Du kan nå bruke Hiisi.")
 (:auth-redirecting . "Omdirigerer om")
 (:auth-go-to-app . "Gå til appen")
 (:auth-resend-title . "Send aktiveringsmail på nytt")
 (:auth-resend-subtitle . "Skriv inn e-posten din for å motta en ny aktiveringslenke.")
 (:auth-resend-button . "Send aktiveringsmail på nytt")
 (:auth-resend-success . "Aktiveringsmail sendt!")
 (:auth-resend-success-detail . "Sjekk innboksen din for den nye aktiveringslenken.")
 (:auth-resend-rate-limited . "Vennligst vent noen minutter før du ber om en ny aktiveringsmail.")
 (:auth-resend-cooldown . "Du kan be om en ny mail om ~a sekunder.")
 (:auth-back-to-login . "Tilbake til innlogging")
 (:auth-forgot-password-title . "Glemt passord")
 (:auth-forgot-password-subtitle . "Skriv inn e-posten din, så sender vi deg en lenke for å tilbakestille passordet.")
 (:auth-send-reset-link . "Send tilbakestillingslenke")
 (:auth-reset-email-sent . "Lenke sendt!")
 (:auth-reset-email-sent-detail . "Hvis det finnes en konto med den e-posten, vil du snart motta en lenke for å tilbakestille passordet.")
 (:auth-reset-rate-limited . "Vennligst vent noen minutter før du ber om en ny tilbakestilling av passord.")
 (:auth-reset-invalid-token . "Denne tilbakestillingslenken er ugyldig eller utløpt.")
 (:auth-reset-password-title . "Tilbakestill passord")
 (:auth-reset-password-subtitle . "Skriv inn ditt nye passord nedenfor.")
 (:auth-new-password . "Nytt passord")
 (:auth-confirm-new-password . "Bekreft nytt passord")
 (:auth-reset-password . "Tilbakestill passord")
 (:auth-password-changed . "Passord endret!")
 (:auth-password-changed-detail . "Passordet ditt er endret. Du kan nå logge inn med ditt nye passord.")
 (:auth-change-password-title . "Endre passord")
 (:auth-change-password-subtitle . "Oppdater kontoens passord.")
 (:auth-current-password . "Nåværende passord")
 (:auth-change-password . "Endre passord")
 (:auth-back-to-app . "Tilbake til appen")
 (:auth-password-updated . "Passord oppdatert!")
 (:auth-password-updated-detail . "Passordet ditt er oppdatert.")

 ;; Translation page
 (:translate-title . "Oversett")
 (:translate-input-label . "Tekst å oversette")
 (:translate-input-placeholder . "Skriv inn tekst å oversette...")
 (:translate-from . "Fra:")
 (:translate-to . "Til:")
 (:translate-submit . "Oversett")
 (:translate-save . "Lagre som flashcard")
 (:translate-saved . "Lagret!")
 (:translate-like . "Lik")
 (:translate-dislike . "Mislik")
 (:translate-char-limit . "tegn igjen")
 (:translate-auto-detect . "Alle (Automatisk gjenkjenning)")
 (:translate-empty-state . "Skriv inn tekst ovenfor og klikk Oversett for å se resultatet med grammatisk forklaring")
 (:translate-select-deck-placeholder . "Velg kortstokk (valgfritt)")
 (:translate-new-deck . "Ny kortstokk")
 (:translate-add-to-deck . "Legg til i kortstokk")
 (:translate-bookmark . "Lagre")
 (:translate-bookmarked . "Lagret")
 (:translate-retry . "Prøv igjen")
 (:translate-like-tooltip . "God oversettelse")
 (:translate-dislike-tooltip . "Dårlig oversettelse - be om en ny")
 (:translate-dislike-confirm . "Dette genererer en ny oversettelse. Fortsette?")
 (:translate-liked . "Liker!")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Mål")
 (:translate-deck-create-title . "Lag ny kortstokk")
 (:translate-deck-name-label . "Navn på kortstokk")
 (:translate-deck-name-placeholder . "f.eks. Finsk grunnlag")
 (:translate-deck-description-label . "Beskrivelse (valgfritt)")
 (:translate-deck-cancel . "Avbryt")
 (:translate-deck-create . "Lag")
 (:translate-rate-label . "Vurder oversettelse")
 (:flashcards-delete-confirm . "Er du sikker på at du vil slette dette kortet?")
 (:flashcards-deck-search-placeholder . "Søk i kortstokker...")
 (:flashcards-no-decks . "Ingen kortstokker ennå. Lag en først!")
 (:flashcards-deck-cancel . "Avbryt")
 (:flashcards-recollection-tooltip . "Hukommelse: ~A")
 (:flashcards-recollection-poor . "Svak")
 (:flashcards-recollection-fair . "Grei")
 (:flashcards-recollection-normal . "Normal")
 (:flashcards-recollection-strong . "Sterk")
 (:flashcards-recollection-very-strong . "Veldig sterk")

 ;; Flashcard review
 (:review-title . "Repeter")
 (:review-session-title . "Repetisjonsøkt")
 (:review-session-subtitle . "Øv på dine lagrede flashcards")
 (:review-selector-title . "Velg hva du vil repetere")
 (:review-selector-subtitle . "Velg en kortstokk eller et språkpar for å fokusere repetisjonsøkten.")
 (:review-by-deck . "Repeter etter kortstokk")
 (:review-by-language-pair . "Repeter etter språkpar")
 (:review-all-cards . "Repeter alle kort")

 (:review-start . "Start repetisjon")
 (:review-no-cards . "Ingen kort å repetere")
 (:review-no-cards-desc . "Du har ingen flashcards som skal repeteres akkurat nå.")
 (:review-no-cards-hint . "Oversett noe tekst og klikk \"Lagre som flashcard\" for å bygge kortstokken din!")
 (:review-start-translating . "Begynn å oversette")
 (:review-show-answer . "Vis svar")
 (:review-click-reveal . "Klikk for å vise svar")
 (:review-grammar-breakdown . "Grammatisk forklaring")
 (:review-how-well . "Hvor godt husket du?")
 (:review-again . "Igjen")
 (:review-hard . "Vanskelig")
 (:review-good . "Bra")
 (:review-easy . "Lett")
 (:review-progress . "Kort ~a av ~a")
 (:review-complete . "Økt fullført!")
 (:review-complete-msg . "Du repeterte ~a kort")
 (:review-correct . "Riktig")
 (:review-accuracy . "Nøyaktighet")
 (:review-again-btn . "Repeter igjen")
 (:review-translate-more . "Oversett mer")
 (:review-streak . "dager på rad")

 ;; Dashboard
 (:dashboard-title . "Oversikt")
 (:dashboard-cards-due . "Kort for i dag")
 (:dashboard-total-cards . "Totalt antall kort")
 (:dashboard-subscription . "Abonnement")
 (:dashboard-subscribed-until . "Abonnerer til")
 (:dashboard-not-subscribed . "Ikke abonnert")
 (:dashboard-recent . "Nylige oversettelser")
 (:dashboard-no-translations . "Ingen oversettelser ennå")
 (:dashboard-streak . "Rekke med repetisjoner")
 (:dashboard-days . "dager")
 (:dashboard-quick-actions . "Hurtighandlinger")
 (:dashboard-getting-started . "Kom i gang")
 (:dashboard-tip-1 . "Oversett tekst du vil lære")
 (:dashboard-tip-2 . "Klikk \"Lagre som flashcard\" på oversettelser du vil huske")
 (:dashboard-tip-3 . "Repeter flashcards jevnlig - spredt repetisjon hjelper deg å huske på lang sikt")
 (:dashboard-tip-4 . "Vurder ærlig - det hjelper algoritmen å planlegge repetisjonene dine optimalt")

 ;; Account
 (:account-title . "Konto")
 (:account-subtitle . "Administrer kontoinnstillingene og sletteplanen.")
 (:account-deletion-title . "Sletting av konto")
 (:account-deletion-scheduled . "Kontoen din er planlagt slettet den ~A.")
 (:account-deletion-cancel-hint . "Du kan avbryte før denne datoen for å beholde kontoen.")
 (:account-deletion-cancel . "Avbryt sletting")
 (:account-deletion-request . "Du kan be om sletting av kontoen når som helst. Sletting planlegges 14 dager etter bekreftelse. Hvis du ombestemmer deg etter sletting, kontakt støtte.")
 (:account-deletion-confirm . "Planlegg sletting av konto om 14 dager fra i dag?")
 (:account-deletion-schedule . "Planlegg sletting")
 (:account-reminders-title . "E-postpåminnelser")
 (:account-reminders-subtitle . "Styr påminnelser om repetisjon og fortsettelse for denne kontoen.")
 (:account-reminders-opt-out . "Slå av påminnelser om repetisjon og fortsettelse")
 (:account-reminders-save . "Lagre innstillinger")

 ;; Subscription
 (:subscribe-title . "Enkel prissetting")
 (:subscribe-choose-plan . "Velg ditt abonnement")
 (:subscribe-start-today . "Begynn å lære i dag med 7 dagers gratis prøveperiode")
 (:subscribe-monthly . "Månedlig")
 (:subscribe-annual . "Årlig")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/måned")
 (:subscribe-per-year . "/år")
 (:subscribe-monthly-desc . "600 oversettelser per måned")
 (:subscribe-unlimited-flashcards . "Ubegrensede flashcards")
 (:subscribe-grammar-explanations . "Grammatiske forklaringer")
 (:subscribe-spaced-repetition . "Spredt repetisjon")
 (:subscribe-annual-desc . "Spar €20 — to måneder gratis!")
 (:subscribe-cta . "Abonner")
 (:subscribe-success . "Abonnement vellykket!")
 (:subscribe-manage . "Administrer abonnement")
 (:subscribe-activated . "Abonnement aktivert!")
 (:subscribe-thank-you . "Takk for at du abonnerer. Kontoen din er nå aktiv.")
 (:subscribe-start-learning . "Begynn å lære")
 (:subscribe-management . "Abonnementshåndtering")
 (:subscribe-active . "Aktivt abonnement")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Aktiv")
 (:subscribe-days-remaining . "Dager igjen:")
 (:subscribe-renews-on . "Fornyes den:")
 (:subscribe-no-subscription . "Ingen aktivt abonnement")
 (:subscribe-access-features . "Abonner for å få tilgang til alle funksjoner.")
 (:subscribe-view-plans . "Se abonnementer")
 (:subscribe-faq-title . "Ofte stilte spørsmål")
 (:subscribe-faq-trial-q . "Hva skjer etter gratis prøveperiode?")
 (:subscribe-faq-trial-a . "Etter din 7-dagers gratis prøveperiode vil du bli belastet for det valgte abonnementet. Du kan kansellere når som helst før prøveperioden utløper.")
 (:subscribe-faq-cancel-q . "Kan jeg kansellere når som helst?")
 (:subscribe-faq-cancel-a . "Ja! Du kan kansellere abonnementet ditt når som helst. Du beholder tilgang til slutten av faktureringsperioden.")
 (:subscribe-faq-payment-q . "Hvilke betalingsmetoder godtar dere?")
 (:subscribe-faq-payment-a . "Vi godtar alle store kredittkort og debetkort gjennom vår betalingspartner Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Noe gikk galt")
 (:error-not-found . "Siden ble ikke funnet")
 (:error-unauthorized . "Logg inn for å fortsette")
 (:error-subscription-required . "Abonnement påkrevd")
 (:error-text-too-long . "Teksten er for lang. Maksimal oversettelseslengde er 120 tegn.")
 (:error-input-too-long . "Teksten er for lang")
 (:error-unknown-source-lang . "Kildespråket du valgte støttes ikke.")
 (:error-unknown-target-lang . "Målspråket du valgte støttes ikke.")
 (:error-unknown-language . "Ukjent språk")
 (:error-translation-unavailable . "Oversettelsestjenesten er midlertidig utilgjengelig. Prøv igjen om et øyeblikk.")
 (:error-translation-failed . "Oversettelse mislyktes")
 (:error-translation-retry . "Kunne ikke generere en oversettelse etter flere forsøk. Prøv å omformulere teksten din.")
 (:error-quota-exceeded . "Oversettelsesgrense nådd")
 (:error-quota-exceeded-detail . "Du har brukt alle oversettelsene dine for denne måneden. Kvoten din tilbakestilles automatisk hver måned.")
 (:quota-warning . "Gjenværende oversettelser: ~A")
 (:quota-low-warning . "Kun ~A oversettelser igjen. Vurder å kjøpe flere.")
 (:top-up-button . "Kjøp flere oversettelser")
 (:top-up-success . "Påfylling vellykket! Du har nå ~A ekstra oversettelser.")
 (:top-up-price . "€5")
 (:top-up-amount . "300 oversettelser")
 (:loading . "Laster...")
 (:empty-state . "Ingenting her ennå")

 ;; Institutions
 (:institutions-page-title . "Hiisi for skoler - institusjonelle lisenser")
 (:institutions-hero-title . "Hiisi for skoler")
 (:institutions-hero-subtitle . "Gi studentene dine AI-støttet språklæring")
 (:institutions-section-title . "Institusjonelle lisenser")
 (:institutions-section-body . "Vi tilbyr volumlisenser for skoler, universiteter og språkinstitusjoner. Studenter med e-postadresser fra domenet ditt får automatisk full tilgang.")
 (:institutions-benefit-1 . "Automatisk registrering for studenter med institusjonell e-post")
 (:institutions-benefit-2 . "Ingen individuelle studentkontoer å administrere")
 (:institutions-benefit-3 . "Fleksible faktureringsordninger")
 (:institutions-benefit-4 . "Dedikert støtte for undervisere")
 (:institutions-request-title . "Be om en lisens")
 (:institutions-request-subtitle . "Fyll ut skjemaet nedenfor, så tar vi kontakt innen 2 virkedager.")
 (:institutions-field-name . "Institusjonsnavn")
 (:institutions-field-name-placeholder . "Universitetet i Helsinki")
 (:institutions-field-contact-name . "Kontaktperson")
 (:institutions-field-contact-name-placeholder . "Ditt navn")
 (:institutions-field-contact-email . "Kontakt-e-post")
 (:institutions-field-contact-email-placeholder . "deg@universitet.no")
 (:institutions-field-domains . "E-postdomener")
 (:institutions-field-domains-placeholder . "universitet.no, cs.universitet.no")
 (:institutions-field-domains-help . "Komma-separert liste over e-postdomener for institusjonen din")
 (:institutions-field-notes . "Tilleggsinformasjon")
 (:institutions-field-notes-placeholder . "Estimert antall studenter, foretrukket faktureringssyklus, eventuelle spesielle krav...")
 (:institutions-submit . "Send forespørsel")
 (:institutions-success-title . "Takk - Hiisi for skoler")
 (:institutions-success-heading . "Takk!")
 (:institutions-success-body . "Vi har mottatt forespørselen din om en institusjonell lisens. Teamet vårt vil vurdere den og ta kontakt innen 2 virkedager.")
 (:institutions-success-back . "Tilbake til forsiden")

 ;; Footer
 (:footer-privacy . "Personvernerklæring")
 (:footer-terms . "Vilkår for bruk")
 (:footer-contact . "Kontakt")

 ;; Early software notice
 (:early-software-notice . "Hiisi er under tidlig utvikling. Funnet en feil eller har du et forslag?")
 (:early-software-contact . "Kontakt oss på")

 ;; Privacy Policy
 (:privacy-title . "Privacy Policy")
 (:privacy-updated . "Last updated: January 2026")
 (:privacy-who-title . "Who We Are")
 (:privacy-who-body . "Hiisi is operated by Lambda Symbolics OÜ, a company registered in Estonia. As an Estonian company, we comply with the European Union's General Data Protection Regulation (GDPR).")
 (:privacy-collect-title . "Data We Collect")
 (:privacy-collect-intro . "We collect the following information when you use Hiisi:")
 (:privacy-collect-account-key . "Account information: ")
 (:privacy-collect-account-val . "Email address, display name, and a securely hashed password.")
 (:privacy-collect-learning-key . "Learning data: ")
 (:privacy-collect-learning-val . "Your translations, saved flashcards, and review history.")
 (:privacy-collect-usage-key . "Usage data: ")
 (:privacy-collect-usage-val . "Basic server logs for security and debugging purposes.")
 (:privacy-use-title . "How We Use Your Data")
 (:privacy-use-auth-key . "Authentication: ")
 (:privacy-use-auth-val . "To verify your identity and secure your account.")
 (:privacy-use-service-key . "Service delivery: ")
 (:privacy-use-service-val . "To provide translations and manage your flashcard collection.")
 (:privacy-use-ai-key . "AI translations: ")
 (:privacy-use-ai-val . "Your translation requests are sent to Anthropic's Claude API to generate responses. See Anthropic's privacy policy for how they handle this data.")
 (:privacy-third-title . "Third-Party Services")
 (:privacy-third-intro . "We use the following third-party services:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "For AI-powered translations.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "For sending account activation and transactional emails.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "For subscription payment processing.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "We use only essential cookies:")
 (:privacy-cookies-auth-key . "Authentication token: ")
 (:privacy-cookies-auth-val . "A secure, HTTP-only cookie to keep you logged in.")
 (:privacy-cookies-lang-key . "Language preference: ")
 (:privacy-cookies-lang-val . "To remember your preferred UI language.")
 (:privacy-retention-title . "Data Retention")
 (:privacy-retention-body . "Your data is stored as long as you maintain an account. When you request deletion, your account is scheduled for deletion in 14 days.")
 (:privacy-rights-title . "Your Rights (GDPR)")
 (:privacy-rights-intro . "Under GDPR, you have the right to:")
 (:privacy-rights-access . "Access your personal data")
 (:privacy-rights-export . "Export your data (available at /app/api/export)")
 (:privacy-rights-correct . "Request correction of inaccurate data")
 (:privacy-rights-delete . "Request deletion of your account and data")
 (:privacy-rights-object . "Object to processing of your data")
 (:privacy-rights-contact . "To exercise these rights, contact us at")
 (:privacy-contact-title . "Contact")
 (:privacy-contact-intro . "For privacy-related inquiries:")
 (:privacy-contact-email-label . "Email: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Estonia")

 ;; Terms of Service
 (:terms-title . "Terms of Service")
 (:terms-updated . "Last updated: January 2026")
 (:terms-1-title . "1. Service Description")
 (:terms-1-body . "Hiisi is a language learning application that provides AI-powered translations with grammatical explanations and spaced repetition flashcards. The service is operated by Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Account Registration")
 (:terms-2-body . "To use Hiisi, you must create an account with a valid email address. You are responsible for maintaining the security of your account credentials.")
 (:terms-3-title . "3. Subscription and Payments")
 (:terms-3-body . "Hiisi offers paid subscription plans (monthly and annual). Subscriptions are processed through Polar.sh.")
 (:terms-3-list-1 . "Subscriptions auto-renew unless cancelled before the renewal date.")
 (:terms-3-list-2 . "Refunds are provided in accordance with applicable consumer protection laws.")
 (:terms-3-list-3 . "Non-payment results in loss of access to premium features.")
 (:terms-4-title . "4. Acceptable Use")
 (:terms-4-intro . "You agree not to:")
 (:terms-4-list-1 . "Use the service for any illegal purpose")
 (:terms-4-list-2 . "Attempt to circumvent usage limits or security measures")
 (:terms-4-list-3 . "Share your account credentials with others")
 (:terms-4-list-4 . "Use automated tools to access the service in a way that degrades performance for others")
 (:terms-5-title . "5. Content and Intellectual Property")
 (:terms-5-body-1 . "Translations generated by Hiisi are created using AI and may not be unique. You may use your translations and flashcards for any personal purpose, but you do not hold exclusive authorship rights over AI-generated content.")
 (:terms-5-body-2 . "The Hiisi application, branding, and original content remain the property of Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Service Availability")
 (:terms-6-intro . "Hiisi is provided on an \"as-is\" basis. We do not guarantee:")
 (:terms-6-list-1 . "Uninterrupted or error-free service")
 (:terms-6-list-2 . "Accuracy of AI-generated translations")
 (:terms-6-list-3 . "Availability of specific features")
 (:terms-6-body . "We may modify or discontinue features at any time.")
 (:terms-7-title . "7. Limitation of Liability")
 (:terms-7-body-1 . "To the maximum extent permitted by law, Lambda Symbolics OÜ shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of Hiisi.")
 (:terms-7-body-2 . "Our total liability shall not exceed the amount you paid for the service in the 12 months preceding the claim.")
 (:terms-8-title . "8. Account Termination")
 (:terms-8-body-1 . "We may suspend or terminate your account if you violate these terms. You may request account deletion at any time through the application.")
 (:terms-8-body-2 . "Upon deletion request, your account is scheduled for deletion in 14 days.")
 (:terms-9-title . "9. Changes to Terms")
 (:terms-9-body . "We may update these terms from time to time. Continued use of Hiisi after changes constitutes acceptance of the new terms.")
 (:terms-10-title . "10. Governing Law")
 (:terms-10-body . "These terms are governed by the laws of Estonia. Any disputes shall be resolved in the courts of Estonia.")
 (:terms-contact-title . "Contact")
 (:terms-contact-intro . "For questions about these terms:")
 (:terms-contact-email-label . "Email: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Estonia")



 ;; Decks
 (:decks-title . "Kortstokker")
 (:decks-subtitle . "Lag egne kortstokker og del dem med andre.")
 (:decks-create-title . "Lag kortstokk")
 (:decks-name-placeholder . "Navn på kortstokk")
 (:decks-desc-placeholder . "Beskrivelse")
 (:decks-create-btn . "Lag kortstokk")
 (:decks-your-title . "Dine kortstokker")
 (:decks-col-name . "Navn")
 (:decks-col-desc . "Beskrivelse")
 (:decks-col-updated . "Oppdatert")
 (:decks-col-actions . "Handlinger")
 (:decks-no-decks . "Ingen kortstokker ennå.")
 (:decks-open-btn . "Åpne")
 (:decks-no-desc . "Ingen beskrivelse.")
 (:decks-share-title . "Delingslenke")
 (:decks-share-info . "Alle med denne lenken kan importere kortstokken:")
 (:decks-share-copy . "Kopier lenke")
 (:decks-share-copied . "Kopiert")
 (:decks-add-from-flashcards-title . "Legg til oversettelser")
 (:decks-add-from-flashcards-info . "Velg et kort for å legge oversettelsen til i denne kortstokken.")
 (:decks-open-flashcards . "Legg til fra kort")
 (:decks-filter-from . "Kildespråk")
 (:decks-filter-to . "Målspråk")
 (:decks-filter-any . "Alle språk")
 (:decks-filter-include-assigned . "Inkluder kort som allerede er i en kortstokk")
 (:decks-flashcards-col-from . "Fra")
 (:decks-flashcards-col-to . "Til")
 (:decks-flashcards-add . "Legg til")
 (:decks-flashcards-added . "Lagt til")
 (:decks-flashcards-in-deck . "I en annen kortstokk")
 (:decks-flashcards-empty . "Ingen kort samsvarer med disse filtrene.")
 (:decks-add-trans-title . "Legg til oversettelse")
 (:decks-trans-id-placeholder . "Oversettelse-ID")
 (:decks-add-trans-btn . "Legg til oversettelse")
 (:decks-items-title . "Innhold i kortstokk")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Oversettelse")
 (:decks-col-lang . "Målspråk")
 (:decks-no-items . "Ingen elementer ennå.")
 (:decks-share-page-title . "Del kortstokk")
 (:decks-share-preview . "Forhåndsvis og importer denne kortstokken.")
 (:decks-import-title . "Importer")
 (:decks-import-btn . "Importer kortstokk")

 ;; Flashcards management page
 (:flashcards-title . "Mine kort")
 (:flashcards-subtitle . "Alle dine lagrede kort på ett sted. Søk, organiser og administrer.")
 (:flashcards-search-placeholder . "Søk i kort...")
 (:flashcards-col-original . "Original")
 (:flashcards-col-translated . "Oversettelse")
 (:flashcards-col-lang . "Språk")
 (:flashcards-no-cards . "Ingen kort ennå. Begynn å oversette for å lage noen!")

 ;; API errors
 (:api-error-missing-text . "Mangler tekst for oversettelse.")
 (:api-error-invalid-translation-id . "Ugyldig oversettelses-ID.")
 (:api-error-translation-not-found . "Oversettelsen du prøvde å lagre finnes ikke lenger.")
 (:api-error-invalid-bookmark-id . "Ugyldig bokmerke-ID")
 (:api-error-bookmark-not-found . "Bokmerke ikke funnet")
 (:api-error-forbidden . "Forbudt")
 (:api-error-failed-delete-bookmark . "Kunne ikke slette bokmerke")
 (:api-error-invalid-flashcard-id . "Ugyldig kort-ID")
 (:api-error-missing-deck-id . "Mangler kortstokk-ID")
 (:api-error-flashcard-not-found . "Kort ikke funnet")
 (:api-error-deck-not-found . "Kortstokk ikke funnet")
 (:api-error-deck-name-required . "Kortstokk-navn er påkrevd")
 (:api-error-session-expired . "Repetisjonsøkten din har utløpt. Start en ny økt.")
 (:api-error-invalid-card-id . "Ugyldig kort-ID.")
 (:api-error-invalid-rating . "Ugyldig vurdering.")
 (:api-error-rating-range . "Vurderingen må være mellom 0 og 5.")
 (:api-error-card-not-found . "Kort ikke funnet.")
 (:api-error-permission-denied . "Du har ikke tillatelse til å repetere dette kortet.")
 (:api-error-unknown-source-lang . "Ukjent kildespråk.")
 (:api-error-unknown-target-lang . "Ukjent målspråk.")
 (:api-error-failed-add-to-deck . "Kunne ikke legge til i kortstokk")

 ;; API success messages
 (:api-success-added . "Lagt til!")
 (:api-success-added-simple . "Lagt til")

 ;; API stats
 (:api-stats-due . "~A forfaller")
 (:api-stats-total . "~A totalt")

 ;; Time units
 (:api-time-day . "dag")
 (:api-time-days . "dager")
 (:api-time-day-left . "dag igjen")
 (:api-time-days-left . "dager igjen")

 ;; Subscription status
 (:api-subscription-active . "Aktiv")
 (:api-subscription-inactive . "Inaktiv")
 (:api-subscription-subscribe-hint . "Abonner for å låse opp oversettelser")

 ;; Generic status
 (:status-bad-request . "Ugyldig forespørsel")
 (:status-not-found . "Ikke funnet")
 (:status-forbidden . "Forbudt")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Lær språk grundig")
 (:landing-hero-subheadline . "Få oversettelser med full grammatisk analyse og bygg varig ordforråd med studiekort og distribuert repetisjon.")
 (:landing-hero-trust-line . "7 dagers gratis prøveperiode med 100 oversettelser. Kort kreves. Avslutt når som helst.")
 (:landing-credibility-languages . "14 språk")
 (:landing-credibility-ai . "Grammatikkanalyse inkludert")
 (:landing-credibility-origin . "Laget i Estland")
 (:landing-step-1-title . "Oversett hvilken som helst tekst")
 (:landing-step-1-desc . "Skriv inn et ord eller en setning. Få en oversettelse med full grammatisk analyse.")
 (:landing-step-2-title . "Lagre som studiekort")
 (:landing-step-2-desc . "Lagre oversettelser du vil huske. Studiekort opprettes automatisk.")
 (:landing-step-3-title . "Repeter og husk")
 (:landing-step-3-desc . "Distribuert repetisjon planlegger gjennomganger på riktig tidspunkt for langtidsminnet.")
 (:landing-feature-grammar-title . "Forstå grammatikk, ikke bare ord")
 (:landing-feature-grammar-desc . "Hver oversettelse inneholder en detaljert grammatisk analyse - ordformer, kasus og bøyninger forklart på ditt språk.")
 (:landing-feature-srs-title . "Vitenskapelig basert memorering")
 (:landing-feature-srs-desc . "SM-2-algoritmen tilpasser seg resultatene dine. Vanskelige kort vises oftere. Kort du kan, vises sjeldnere.")
 (:landing-feature-share-title . "Del kortstokker med elever")
 (:landing-feature-share-desc . "Lærere kan lage egne kortstokker og dele dem med en lenke. Elever importerer kortstokken og begynner å repetere med en gang.")
 (:landing-pricing-trial-note . "Inkluderer 7 dagers gratis prøveperiode")
 (:landing-pricing-monthly-after . "7 dager gratis, deretter ~A/måned")
 (:landing-pricing-annual-after . "7 dager gratis, deretter ~A/år")
 (:landing-faq-title . "Ofte stilte spørsmål")
 (:landing-faq-trial-cap-q . "Hvor mange oversettelser får jeg i prøveperioden?")
 (:landing-faq-trial-cap-a . "Du får 100 oversettelser i løpet av 7 dagers prøveperiode. Etter abonnement får du 600 per måned.")
 (:landing-final-cta-title . "Begynn å lære i dag")
 (:landing-final-cta-subtitle . "Bli med i Hiisi og bygg et ordforråd som varer.")

 ;; Trial status (in-app)
 (:trial-status . "Gratis prøveperiode")
 (:trial-days-remaining . "~A dager igjen")
 (:trial-translations-used . "~A/100 oversettelser brukt")
 (:trial-upgrade-prompt . "Oppgrader for å fortsette å oversette")
 (:trial-expired . "Din gratis prøveperiode er over")
 (:trial-expired-detail . "Abonner for å fortsette å lære med Hiisi.")
 (:trial-quota-warning . "~A prøveoversettelser igjen (~A dager). Abonner for 600/måned.")
 (:trial-quota-exceeded . "Grense for prøveoversettelser nådd. Abonner for å fortsette.")
 (:error-trial-quota-exceeded . "Grense for prøveoversettelser nådd")
 (:error-trial-quota-detail . "Du har brukt alle 100 prøveoversettelsene. Abonner for å fortsette å lære.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Opprett studiekort")
 (:custom-flashcard-edit-title . "Rediger studiekort")
 (:custom-flashcard-original . "Originaltekst")
 (:custom-flashcard-translated . "Oversettelse")
 (:custom-flashcard-lang-from . "Kildespråk")
 (:custom-flashcard-lang-to . "Målspråk")
 (:custom-flashcard-note . "Pedagogisk notat")
 (:custom-flashcard-forms . "Grammatikkanalyse")
 (:custom-flashcard-form-term . "Begrep")
 (:custom-flashcard-form-explanation . "Forklaring")
 (:custom-flashcard-add-form . "Legg til grammatikkbegrep")
 (:custom-flashcard-remove-form . "Fjern")
 (:custom-flashcard-ai-fill . "Fyll ut med KI")
 (:custom-flashcard-ai-fill-all . "Fyll ut alt med KI")
 (:custom-flashcard-ai-fill-translation . "Oversett med KI")
 (:custom-flashcard-ai-fill-breakdown . "Generer analyse")
 (:custom-flashcard-ai-fill-note . "Generer notat")
 (:custom-flashcard-create-btn . "Opprett studiekort")
 (:custom-flashcard-update-btn . "Lagre endringer")
 (:custom-flashcard-delete-btn . "Slett studiekort")
 (:custom-flashcard-delete-confirm . "Er du sikker på at du vil slette dette studiekortet?")
 (:custom-flashcard-created . "Studiekort opprettet")
 (:custom-flashcard-updated . "Studiekort oppdatert")
 (:custom-flashcard-deleted . "Studiekort slettet")
 (:custom-flashcard-add-to-deck . "Legg til i kortstokk")
 (:custom-flashcard-not-found . "Studiekort ikke funnet")
 (:custom-flashcard-not-owner . "Du kan bare redigere studiekort du har opprettet")
 (:custom-flashcard-ai-generating . "Genererer med KI...")
 (:custom-flashcard-badge . "Egendefinert")

)
