;;; Norwegian translations (Bokmål)
;;; This file must contain all keys from en.lisp

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Norsk")
 (:lang-flag . "🇳🇴")

 ;; Navigation
 (:nav-translate . "Oversett")
 (:nav-review . "Repeter")
 (:nav-dashboard . "Oversikt")
 (:nav-logout . "Logg ut")
 (:nav-home . "Hjem")
 (:nav-pricing . "Priser")
 (:nav-export-data . "Eksporter data")

 ;; App title and branding
 (:app-title . "Hiisi")
 (:app-tagline . "Lær språk gjennom oversettelser")

 ;; Landing page
 (:landing-hero-title . "Mestre ethvert språk")
 (:landing-hero-subtitle . "Oversett hva som helst. Generer automatisk flashcards som lærer deg hvorfor det fungerer slik.")
 (:landing-cta . "Begynn å lære")
 (:landing-learn-more . "Lær mer")
 (:landing-how-it-works . "Slik fungerer det")
 (:landing-feature-1-title . "Automatiske flashcards")
 (:landing-feature-1-desc . "Hver oversettelse genererer automatisk flashcards med grammatiske forklaringer. Ingen manuell kortlaging.")
 (:landing-feature-2-title . "Spredt repetisjon")
 (:landing-feature-2-desc . "SM-2-algoritmen planlegger repetisjoner i optimale intervaller. Lær effektivt, husk permanent.")
 (:landing-feature-3-title . "Grammatikkundervisning")
 (:landing-feature-3-desc . "Hver oversettelse forklarer grammatikk, ordrøtter og setningsstruktur. Forstå hvorfor, ikke bare hva.")
 (:landing-free-trial . "7 dagers gratis prøveperiode. Ingen kredittkort nødvendig.")
 (:landing-start-trial . "Start gratis prøveperiode")
 (:landing-best-value . "Best verdi")
 (:landing-cta-title . "Klar til å lære språk gjennom grammatikk, ikke pugging?")
 (:landing-cta-subtitle . "Hver oversettelse blir en læringsmulighet. Hvert flashcard lærer deg hvorfor.")
 (:landing-signup-free . "Registrer deg gratis")

 ;; Auth pages
 (:auth-register . "Registrer")
 (:auth-login . "Logg inn")
 (:auth-logout . "Logg ut")
 (:auth-email . "E-post")
 (:auth-password . "Passord")
 (:auth-password-again . "Bekreft passord")
 (:auth-display-name . "Visningsnavn")
 (:auth-register-title . "Registrer deg på Hiisi")
 (:auth-register-subtitle . "Opprett en ny konto")
 (:auth-login-title . "Logg inn på Hiisi")
 (:auth-login-subtitle . "Skriv inn opplysningene dine")
 (:auth-forgot-password . "Glemt passord?")
 (:auth-no-account . "Har du ikke konto?")
 (:auth-have-account . "Har du allerede en konto?")
 (:auth-google . "Google")
 (:auth-account-created . "Konto opprettet!")
 (:auth-check-email . "Sjekk e-posten din for aktiveringslenken.")
 (:auth-redirect-login . "Omdirigerer til innlogging om")
 (:auth-seconds . "sekunder...")
 (:auth-go-now . "Gå nå")
 (:auth-not-activated . "Konto ikke aktivert")
 (:auth-activate-title . "Aktiver kontoen din!")
 (:auth-activated . "Konto aktivert!")
 (:auth-activated-message . "Kontoen din er aktivert. Du kan nå bruke Hiisi.")
 (:auth-redirecting . "Omdirigerer om")
 (:auth-go-to-app . "Gå til appen")

 ;; Translation page
 (:translate-title . "Oversett")
 (:translate-input-label . "Tekst å oversette")
 (:translate-input-placeholder . "Skriv inn tekst å oversette...")
 (:translate-from . "Fra:")
 (:translate-to . "Til:")
 (:translate-submit . "Oversett")
 (:translate-save . "Lagre som flashcard")
 (:translate-saved . "Lagret!")
 (:translate-like . "Lik")
 (:translate-dislike . "Mislik")
 (:translate-char-limit . "tegn igjen")
 (:translate-auto-detect . "Alle (Automatisk gjenkjenning)")
 (:translate-empty-state . "Skriv inn tekst ovenfor og klikk Oversett for å se resultatet med grammatisk forklaring")
 (:translate-like-tooltip . "God oversettelse")
 (:translate-dislike-tooltip . "Dårlig oversettelse - be om en ny")
 (:translate-dislike-confirm . "Dette genererer en ny oversettelse. Fortsette?")
 (:translate-liked . "Liker!")

 ;; Flashcard review
 (:review-title . "Repeter")
 (:review-session-title . "Repetisjonsøkt")
 (:review-session-subtitle . "Øv på dine lagrede flashcards")
 (:review-start . "Start repetisjon")
 (:review-no-cards . "Ingen kort å repetere")
 (:review-no-cards-desc . "Du har ingen flashcards som skal repeteres akkurat nå.")
 (:review-no-cards-hint . "Oversett noe tekst og klikk \"Lagre som flashcard\" for å bygge kortstokken din!")
 (:review-start-translating . "Begynn å oversette")
 (:review-show-answer . "Vis svar")
 (:review-click-reveal . "Klikk for å vise svar")
 (:review-grammar-breakdown . "Grammatisk forklaring")
 (:review-how-well . "Hvor godt husket du?")
 (:review-again . "Igjen")
 (:review-hard . "Vanskelig")
 (:review-good . "Bra")
 (:review-easy . "Lett")
 (:review-progress . "Kort ~a av ~a")
 (:review-complete . "Økt fullført!")
 (:review-complete-msg . "Du repeterte ~a kort")
 (:review-correct . "Riktig")
 (:review-accuracy . "Nøyaktighet")
 (:review-again-btn . "Repeter igjen")
 (:review-translate-more . "Oversett mer")
 (:review-streak . "dager på rad")

 ;; Dashboard
 (:dashboard-title . "Oversikt")
 (:dashboard-cards-due . "Kort for i dag")
 (:dashboard-total-cards . "Totalt antall kort")
 (:dashboard-subscription . "Abonnement")
 (:dashboard-subscribed-until . "Abonnerer til")
 (:dashboard-not-subscribed . "Ikke abonnert")
 (:dashboard-recent . "Nylige oversettelser")
 (:dashboard-no-translations . "Ingen oversettelser ennå")
 (:dashboard-streak . "Rekke med repetisjoner")
 (:dashboard-days . "dager")
 (:dashboard-quick-actions . "Hurtighandlinger")
 (:dashboard-getting-started . "Kom i gang")
 (:dashboard-tip-1 . "Oversett tekst du vil lære")
 (:dashboard-tip-2 . "Klikk \"Lagre som flashcard\" på oversettelser du vil huske")
 (:dashboard-tip-3 . "Repeter flashcards jevnlig - spredt repetisjon hjelper deg å huske på lang sikt")
 (:dashboard-tip-4 . "Vurder ærlig - det hjelper algoritmen å planlegge repetisjonene dine optimalt")

 ;; Subscription
 (:subscribe-title . "Enkel prissetting")
 (:subscribe-choose-plan . "Velg ditt abonnement")
 (:subscribe-start-today . "Begynn å lære i dag med 7 dagers gratis prøveperiode")
 (:subscribe-monthly . "Månedlig")
 (:subscribe-annual . "Årlig")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/måned")
 (:subscribe-per-year . "/år")
 (:subscribe-monthly-desc . "600 oversettelser per måned")
 (:subscribe-unlimited-flashcards . "Ubegrensede flashcards")
 (:subscribe-grammar-explanations . "Grammatiske forklaringer")
 (:subscribe-spaced-repetition . "Spredt repetisjon")
 (:subscribe-annual-desc . "Spar €20 — to måneder gratis!")
 (:subscribe-cta . "Abonner")
 (:subscribe-success . "Abonnement vellykket!")
 (:subscribe-manage . "Administrer abonnement")
 (:subscribe-activated . "Abonnement aktivert!")
 (:subscribe-thank-you . "Takk for at du abonnerer. Kontoen din er nå aktiv.")
 (:subscribe-start-learning . "Begynn å lære")
 (:subscribe-management . "Abonnementshåndtering")
 (:subscribe-active . "Aktivt abonnement")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Aktiv")
 (:subscribe-days-remaining . "Dager igjen:")
 (:subscribe-renews-on . "Fornyes den:")
 (:subscribe-no-subscription . "Ingen aktivt abonnement")
 (:subscribe-access-features . "Abonner for å få tilgang til alle funksjoner.")
 (:subscribe-view-plans . "Se abonnementer")
 (:subscribe-faq-title . "Ofte stilte spørsmål")
 (:subscribe-faq-trial-q . "Hva skjer etter gratis prøveperiode?")
 (:subscribe-faq-trial-a . "Etter din 7-dagers gratis prøveperiode vil du bli belastet for det valgte abonnementet. Du kan kansellere når som helst før prøveperioden utløper.")
 (:subscribe-faq-cancel-q . "Kan jeg kansellere når som helst?")
 (:subscribe-faq-cancel-a . "Ja! Du kan kansellere abonnementet ditt når som helst. Du beholder tilgang til slutten av faktureringsperioden.")
 (:subscribe-faq-payment-q . "Hvilke betalingsmetoder godtar dere?")
 (:subscribe-faq-payment-a . "Vi godtar alle store kredittkort og debetkort gjennom vår betalingspartner Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Noe gikk galt")
 (:error-not-found . "Siden ble ikke funnet")
 (:error-unauthorized . "Logg inn for å fortsette")
 (:error-subscription-required . "Abonnement påkrevd")
 (:error-text-too-long . "Teksten er for lang. Maksimal oversettelseslengde er 120 tegn.")
 (:error-input-too-long . "Teksten er for lang")
 (:error-unknown-source-lang . "Kildespråket du valgte støttes ikke.")
 (:error-unknown-target-lang . "Målspråket du valgte støttes ikke.")
 (:error-unknown-language . "Ukjent språk")
 (:error-translation-unavailable . "Oversettelsestjenesten er midlertidig utilgjengelig. Prøv igjen om et øyeblikk.")
 (:error-translation-failed . "Oversettelse mislyktes")
 (:error-translation-retry . "Kunne ikke generere en oversettelse etter flere forsøk. Prøv å omformulere teksten din.")
 (:loading . "Laster...")
 (:empty-state . "Ingenting her ennå")

 ;; Footer
 (:footer-privacy . "Personvernerklæring")
 (:footer-terms . "Vilkår for bruk")
 (:footer-contact . "Kontakt")

 ;; Early software notice
 (:early-software-notice . "Hiisi er under tidlig utvikling. Funnet en feil eller har du et forslag?")
 (:early-software-contact . "Kontakt oss på")
)
