;;; Polish translations
;;; This file should contain all keys from en.lisp

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Polski")
 (:lang-flag . "🇵🇱")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Wybierz język")
 (:lang-modal-subtitle . "Wybierz preferowany język interfejsu:")

 ;; Navigation
 (:nav-translate . "Tłumacz")
 (:nav-review . "Powtórka")
 (:nav-flashcards . "Moje fiszki")
 (:nav-dashboard . "Panel")
 (:nav-decks . "Decks")
 (:nav-logout . "Wyloguj")
 (:nav-home . "Strona główna")
 (:nav-pricing . "Cennik")
 (:nav-export-data . "Eksportuj dane")

 ;; App title and branding
 (:app-title . "Hiisi - Nauka języków")
 (:app-tagline . "Ucz się języków przez tłumaczenia")

 ;; Landing page
 (:landing-hero-title . "Opanuj każdy język")
 (:landing-hero-subtitle . "Tłumacz cokolwiek. Automatycznie generuj fiszki, które uczą dlaczego to tak działa.")
 (:landing-cta . "Zacznij naukę")
 (:landing-learn-more . "Dowiedz się więcej")
 (:landing-how-it-works . "Jak to działa")
 (:landing-feature-1-title . "Automatyczne fiszki")
 (:landing-feature-1-desc . "Każde tłumaczenie automatycznie generuje fiszki z rozkładem gramatycznym. Bez ręcznego tworzenia kart.")
 (:landing-feature-2-title . "Powtórki rozłożone w czasie")
 (:landing-feature-2-desc . "Algorytm SM-2 planuje powtórki w optymalnych odstępach. Ucz się efektywnie, zapamiętuj na stałe.")
 (:landing-feature-3-title . "Nauka gramatyki")
 (:landing-feature-3-desc . "Każde tłumaczenie wyjaśnia gramatykę, pochodzenie słów i strukturę zdania. Zrozum dlaczego, nie tylko co.")
 (:landing-free-trial . "7-dniowy okres próbny.")
 (:landing-start-trial . "Rozpocznij bezpłatny okres próbny")
 (:landing-best-value . "Najlepsza oferta")
 (:landing-cta-title . "Gotowy uczyć się języków przez gramatykę, a nie wkuwanie?")
 (:landing-cta-subtitle . "Każde tłumaczenie staje się okazją do nauki. Każda fiszka uczy dlaczego.")
 (:landing-signup-free . "Zarejestruj się za darmo")

 ;; Auth pages
 (:auth-register . "Zarejestruj się")
 (:auth-login . "Zaloguj się")
 (:auth-logout . "Wyloguj")
 (:auth-email . "Email")
 (:auth-password . "Hasło")
 (:auth-password-again . "Potwierdź hasło")
 (:auth-display-name . "Nazwa wyświetlana")
 (:auth-register-title . "Zarejestruj się w Hiisi")
 (:auth-register-subtitle . "Utwórz nowe konto")
 (:auth-login-title . "Zaloguj się do Hiisi")
 (:auth-login-subtitle . "Wprowadź swoje dane")
 (:auth-login-invalid-credentials . "Nieprawidlowy e-mail lub haslo.")
 (:auth-login-rate-limited . "Zbyt wiele prob logowania. Poczekaj kilka minut i sproboj ponownie.")
 (:auth-forgot-password . "Zapomniałeś hasła?")
 (:auth-no-account . "Nie masz konta?")
 (:auth-have-account . "Masz już konto?")
 (:auth-google . "Google")
 (:auth-account-created . "Konto utworzone!")
 (:auth-check-email . "Sprawdź swoją skrzynkę email, aby znaleźć link aktywacyjny.")
 (:auth-redirect-login . "Przekierowanie do logowania za")
 (:auth-seconds . "sekund...")
 (:auth-go-now . "Przejdź teraz")
 (:auth-not-activated . "Konto nie zostało aktywowane")
 (:auth-activate-title . "Aktywuj swoje konto!")
 (:auth-activated . "Konto aktywowane!")
 (:auth-activated-message . "Twoje konto zostało aktywowane. Możesz teraz korzystać z Hiisi.")
 (:auth-redirecting . "Przekierowanie za")
 (:auth-go-to-app . "Przejdź do aplikacji")
 (:auth-resend-title . "Wyślij ponownie email aktywacyjny")
 (:auth-resend-subtitle . "Wpisz swój email, aby otrzymać nowy link aktywacyjny.")
 (:auth-resend-button . "Wyślij ponownie email aktywacyjny")
 (:auth-resend-success . "Email aktywacyjny wysłany!")
 (:auth-resend-success-detail . "Sprawdź swoją skrzynkę odbiorczą, aby znaleźć nowy link aktywacyjny.")
 (:auth-resend-rate-limited . "Poczekaj kilka minut przed ponownym wysłaniem emaila aktywacyjnego.")
 (:auth-resend-cooldown . "Możesz poprosić o kolejny email za ~a sekund.")
 (:auth-back-to-login . "Wróć do logowania")
 (:auth-forgot-password-title . "Zapomniałem hasła")
 (:auth-forgot-password-subtitle . "Wpisz swój email, a wyślemy ci link do zresetowania hasła.")
 (:auth-send-reset-link . "Wyślij link do resetowania")
 (:auth-reset-email-sent . "Link wysłany!")
 (:auth-reset-email-sent-detail . "Jeśli konto z tym emailem istnieje, wkrótce otrzymasz link do zresetowania hasła.")
 (:auth-reset-rate-limited . "Poczekaj kilka minut przed kolejną próbą resetowania hasła.")
 (:auth-reset-invalid-token . "Ten link do resetowania jest nieprawidłowy lub wygasł.")
 (:auth-reset-password-title . "Zresetuj hasło")
 (:auth-reset-password-subtitle . "Wpisz swoje nowe hasło poniżej.")
 (:auth-new-password . "Nowe hasło")
 (:auth-confirm-new-password . "Potwierdź nowe hasło")
 (:auth-reset-password . "Zresetuj hasło")
 (:auth-password-changed . "Hasło zmienione!")
 (:auth-password-changed-detail . "Twoje hasło zostało pomyślnie zmienione. Możesz teraz zalogować się nowym hasłem.")
 (:auth-change-password-title . "Zmień hasło")
 (:auth-change-password-subtitle . "Zaktualizuj hasło do swojego konta.")
 (:auth-current-password . "Obecne hasło")
 (:auth-change-password . "Zmień hasło")
 (:auth-back-to-app . "Wróć do aplikacji")
 (:auth-password-updated . "Hasło zaktualizowane!")
 (:auth-password-updated-detail . "Twoje hasło zostało pomyślnie zaktualizowane.")

 ;; Translation page
 (:translate-title . "Tłumacz")
 (:translate-input-label . "Tekst do przetłumaczenia")
 (:translate-input-placeholder . "Wprowadź tekst do przetłumaczenia...")
 (:translate-from . "Z:")
 (:translate-to . "Na:")
 (:translate-submit . "Przetłumacz")
 (:translate-save . "Zapisz do fiszek")
 (:translate-saved . "Zapisano!")
 (:translate-like . "Lubię")
 (:translate-dislike . "Nie lubię")
 (:translate-char-limit . "znaków pozostało")
 (:translate-auto-detect . "Dowolny (Autowykrywanie)")
 (:translate-empty-state . "Wprowadź tekst powyżej i kliknij Przetłumacz, aby zobaczyć wynik z rozkładem gramatycznym")
 (:translate-select-deck-placeholder . "Wybierz talię (opcjonalnie)")
 (:translate-new-deck . "Nowa talia")
 (:translate-add-to-deck . "Dodaj do talii")
 (:translate-bookmark . "Zapisz")
 (:translate-bookmarked . "Zapisano")
 (:translate-retry . "Spróbuj ponownie")
 (:translate-like-tooltip . "Dobre tłumaczenie")
 (:translate-dislike-tooltip . "Złe tłumaczenie - poproś o nowe")
 (:translate-dislike-confirm . "To wygeneruje nowe tłumaczenie. Kontynuować?")
 (:translate-liked . "Polubione!")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Cel")
 (:translate-deck-create-title . "Utwórz nową talię")
 (:translate-deck-name-label . "Nazwa talii")
 (:translate-deck-name-placeholder . "np. Podstawy fińskiego")
 (:translate-deck-description-label . "Opis (opcjonalny)")
 (:translate-deck-cancel . "Anuluj")
 (:translate-deck-create . "Utwórz")
 (:translate-rate-label . "Oceń tłumaczenie")
 (:flashcards-delete-confirm . "Czy na pewno chcesz usunąć tę fiszkę?")
 (:flashcards-deck-search-placeholder . "Szukaj talii...")
 (:flashcards-no-decks . "Brak talii. Utwórz najpierw jedną!")
 (:flashcards-deck-cancel . "Anuluj")
 (:flashcards-recollection-tooltip . "Zapamiętanie: ~A")
 (:flashcards-recollection-poor . "Słabe")
 (:flashcards-recollection-fair . "Umiarkowane")
 (:flashcards-recollection-normal . "Normalne")
 (:flashcards-recollection-strong . "Silne")
 (:flashcards-recollection-very-strong . "Bardzo silne")

 ;; Flashcard review
 (:review-title . "Powtórka")
 (:review-session-title . "Sesja powtórkowa")
 (:review-session-subtitle . "Ćwicz zapisane fiszki")
 (:review-selector-title . "Wybierz, co chcesz powtórzyć")
 (:review-selector-subtitle . "Wybierz talię lub parę językową, na której chcesz skupić sesję powtórkową.")
 (:review-by-deck . "Powtórka według talii")
 (:review-by-language-pair . "Powtórka według pary językowej")
 (:review-all-cards . "Powtórz wszystkie fiszki")

 (:review-start . "Rozpocznij powtórkę")
 (:review-no-cards . "Brak fiszek do powtórki")
 (:review-no-cards-desc . "Nie masz teraz żadnych fiszek do powtórki.")
 (:review-no-cards-hint . "Przetłumacz tekst i kliknij \"Zapisz do fiszek\", aby zbudować swoją talię!")
 (:review-start-translating . "Zacznij tłumaczyć")
 (:review-show-answer . "Pokaż odpowiedź")
 (:review-click-reveal . "Kliknij, aby odsłonić odpowiedź")
 (:review-grammar-breakdown . "Rozkład gramatyczny")
 (:review-how-well . "Czy udało Ci się przypomnieć?")
 (:review-again . "Nie")
 (:review-hard . "Z trudem")
 (:review-good . "Tak")
 (:review-easy . "Łatwo")
 (:review-progress . "Fiszka ~a z ~a")
 (:review-complete . "Sesja zakończona!")
 (:review-complete-msg . "Powtórzyłeś ~a fiszek")
 (:review-correct . "Poprawnie")
 (:review-accuracy . "Dokładność")
 (:review-again-btn . "Powtórz ponownie")
 (:review-translate-more . "Tłumacz więcej")
 (:review-streak . "dni z rzędu")

 ;; Dashboard
 (:dashboard-title . "Panel")
 (:dashboard-cards-due . "Fiszki na dziś")
 (:dashboard-total-cards . "Wszystkie fiszki")
 (:dashboard-subscription . "Subskrypcja")
 (:dashboard-subscribed-until . "Subskrypcja do")
 (:dashboard-not-subscribed . "Brak subskrypcji")
 (:dashboard-recent . "Ostatnie tłumaczenia")
 (:dashboard-no-translations . "Brak tłumaczeń")
 (:dashboard-streak . "Seria powtórek")
 (:dashboard-days . "dni")
 (:dashboard-all-caught-up . "Wszystko nadrobione!")
 (:dashboard-all-caught-up-hint . "Tłumacz więcej, aby rozbudować swoją kolekcję.")
 (:dashboard-quick-actions . "Szybkie akcje")
 (:dashboard-getting-started . "Jak zacząć")
 (:dashboard-tip-1 . "Tłumacz tekst, którego chcesz się nauczyć")
 (:dashboard-tip-2 . "Kliknij \"Zapisz do fiszek\" przy tłumaczeniach, które chcesz zapamiętać")
 (:dashboard-tip-3 . "Regularnie powtarzaj fiszki - powtórki rozłożone w czasie pomagają zapamiętać na dłużej")
 (:dashboard-tip-4 . "Oceniaj szczerze - pomaga to algorytmowi optymalnie planować powtórki")

 ;; Account
 (:account-title . "Konto")
 (:account-subtitle . "Zarządzaj ustawieniami konta i harmonogramem usunięcia.")
 (:account-deletion-title . "Usunięcie konta")
 (:account-deletion-scheduled . "Twoje konto jest zaplanowane do usunięcia na ~A.")
 (:account-deletion-cancel-hint . "Możesz anulować przed tą datą, aby zachować konto.")
 (:account-deletion-cancel . "Anuluj usunięcie")
 (:account-deletion-request . "Możesz poprosić o usunięcie konta w dowolnym momencie. Usunięcie jest zaplanowane 14 dni po potwierdzeniu. Jeśli po usunięciu zmienisz zdanie, skontaktuj się z pomocą.")
 (:account-deletion-confirm . "Zaplanować usunięcie konta za 14 dni od dziś?")
 (:account-deletion-schedule . "Zaplanuj usunięcie")
 (:account-reminders-title . "Przypomnienia e-mail")
 (:account-reminders-subtitle . "Zarządzaj przypomnieniami o powtórkach i kontynuacji dla tego konta.")
 (:account-reminders-opt-out . "Wyłącz przypomnienia o powtórkach i kontynuacji")
 (:account-reminders-save . "Zapisz preferencje")

 ;; Subscription
 (:subscribe-title . "Prosty cennik")
 (:subscribe-choose-plan . "Wybierz swój plan")
 (:subscribe-start-today . "Zacznij naukę już dziś z 7-dniowym bezpłatnym okresem próbnym")
 (:subscribe-monthly . "Miesięczny")
 (:subscribe-annual . "Roczny")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/miesiąc")
 (:subscribe-per-year . "/rok")
 (:subscribe-monthly-desc . "600 tłumaczeń miesięcznie")
 (:subscribe-unlimited-flashcards . "Nieograniczona liczba fiszek")
 (:subscribe-grammar-explanations . "Wyjaśnienia gramatyczne")
 (:subscribe-spaced-repetition . "Powtórki rozłożone w czasie")
 (:subscribe-annual-desc . "Zaoszczędź 20€ — dwa miesiące gratis!")
 (:subscribe-cta . "Subskrybuj")
 (:subscribe-success . "Subskrypcja aktywna!")
 (:subscribe-manage . "Zarządzaj subskrypcją")
 (:subscribe-activated . "Subskrypcja aktywowana!")
 (:subscribe-thank-you . "Dziękujemy za subskrypcję. Twoje konto jest teraz aktywne.")
 (:subscribe-start-learning . "Rozpocznij naukę")
 (:subscribe-management . "Zarządzanie subskrypcją")
 (:subscribe-active . "Aktywna subskrypcja")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Aktywna")
 (:subscribe-days-remaining . "Pozostało dni:")
 (:subscribe-renews-on . "Odnawia się:")
 (:subscribe-no-subscription . "Brak aktywnej subskrypcji")
 (:subscribe-access-features . "Subskrybuj, aby uzyskać dostęp do wszystkich funkcji.")
 (:subscribe-view-plans . "Zobacz plany")
 (:subscribe-faq-title . "Najczęściej zadawane pytania")
 (:subscribe-faq-trial-q . "Co się dzieje po zakończeniu bezpłatnego okresu próbnego?")
 (:subscribe-faq-trial-a . "Po 7-dniowym bezpłatnym okresie próbnym zostaniesz obciążony za wybrany plan. Możesz anulować w dowolnym momencie przed końcem okresu próbnego.")
 (:subscribe-faq-cancel-q . "Czy mogę anulować w dowolnym momencie?")
 (:subscribe-faq-cancel-a . "Tak! Możesz anulować subskrypcję w dowolnym momencie. Zachowasz dostęp do końca okresu rozliczeniowego.")
 (:subscribe-faq-payment-q . "Jakie metody płatności akceptujecie?")
 (:subscribe-faq-payment-a . "Akceptujemy wszystkie główne karty kredytowe i debetowe za pośrednictwem naszego partnera płatniczego Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Coś poszło nie tak")
 (:error-not-found . "Strona nie znaleziona")
 (:error-unauthorized . "Zaloguj się, aby kontynuować")
 (:error-subscription-required . "Wymagana subskrypcja")
 (:error-text-too-long . "Tekst jest za długi. Maksymalna długość tłumaczenia to 120 znaków.")
 (:error-input-too-long . "Tekst za długi")
 (:error-unknown-source-lang . "Wybrany język źródłowy nie jest obsługiwany.")
 (:error-unknown-target-lang . "Wybrany język docelowy nie jest obsługiwany.")
 (:error-unknown-language . "Nieznany język")
 (:error-translation-unavailable . "Usługa tłumaczenia jest chwilowo niedostępna. Spróbuj ponownie za chwilę.")
 (:error-translation-failed . "Tłumaczenie nie powiodło się")
 (:error-translation-retry . "Nie udało się wygenerować tłumaczenia po wielu próbach. Spróbuj przeformułować tekst.")
 (:error-quota-exceeded . "Osiągnięto limit tłumaczeń")
 (:error-quota-exceeded-detail . "Wykorzystałeś wszystkie tłumaczenia na ten miesiąc. Twój limit odnawia się automatycznie co miesiąc.")
 (:quota-warning . "Pozostałe tłumaczenia: ~A")
 (:quota-low-warning . "Zostało tylko ~A tłumaczeń. Rozważ zakup większej ilości.")
 (:top-up-button . "Kup więcej tłumaczeń")
 (:top-up-success . "Doładowanie udane! Masz teraz ~A dodatkowych tłumaczeń.")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 tłumaczeń")
 (:loading . "Ładowanie...")
 (:empty-state . "Nic tu jeszcze nie ma")

 ;; Institutions
 (:institutions-page-title . "Hiisi dla szkół - licencje instytucjonalne")
 (:institutions-hero-title . "Hiisi dla szkół")
 (:institutions-hero-subtitle . "Wzmocnij swoich uczniów dzięki nauce języków z AI")
 (:institutions-section-title . "Licencje instytucjonalne")
 (:institutions-section-body . "Oferujemy licencje hurtowe dla szkół, uniwersytetów i instytucji językowych. Studenci z adresami e-mail z Twojej domeny automatycznie otrzymują pełny dostęp.")
 (:institutions-benefit-1 . "Automatyczna rejestracja studentów z instytucjonalnym e-mailem")
 (:institutions-benefit-2 . "Brak indywidualnych kont studentów do zarządzania")
 (:institutions-benefit-3 . "Elastyczne opcje rozliczeń")
 (:institutions-benefit-4 . "Dedykowane wsparcie dla nauczycieli")
 (:institutions-request-title . "Poproś o licencję")
 (:institutions-request-subtitle . "Wypełnij poniższy formularz, a odpowiemy w ciągu 2 dni roboczych.")
 (:institutions-field-name . "Nazwa instytucji")
 (:institutions-field-name-placeholder . "Uniwersytet w Helsinkach")
 (:institutions-field-contact-name . "Imię i nazwisko kontaktowe")
 (:institutions-field-contact-name-placeholder . "Twoje imię")
 (:institutions-field-contact-email . "E-mail kontaktowy")
 (:institutions-field-contact-email-placeholder . "ty@uniwersytet.pl")
 (:institutions-field-domains . "Domeny e-mail")
 (:institutions-field-domains-placeholder . "uniwersytet.pl, cs.uniwersytet.pl")
 (:institutions-field-domains-help . "Lista domen e-mail Twojej instytucji oddzielona przecinkami")
 (:institutions-field-notes . "Dodatkowe informacje")
 (:institutions-field-notes-placeholder . "Szacowana liczba studentów, preferowany cykl rozliczeniowy, specjalne wymagania...")
 (:institutions-submit . "Wyślij zapytanie")
 (:institutions-success-title . "Dziękujemy - Hiisi dla szkół")
 (:institutions-success-heading . "Dziękujemy!")
 (:institutions-success-body . "Otrzymaliśmy Twoje zapytanie o licencję instytucjonalną. Nasz zespół je rozpatrzy i skontaktuje się w ciągu 2 dni roboczych.")
 (:institutions-success-back . "Wróć na stronę główną")

 ;; Footer
 (:footer-privacy . "Polityka prywatności")
 (:footer-terms . "Regulamin")
 (:footer-contact . "Kontakt")

 ;; Early software notice
 (:early-software-notice . "Hiisi jest we wczesnej fazie rozwoju. Znalazłeś błąd lub masz sugestię?")
 (:early-software-contact . "Skontaktuj się z nami pod adresem")

 ;; Polityka prywatności
 (:privacy-title . "Polityka prywatności")
 (:privacy-updated . "Ostatnia aktualizacja: styczeń 2026")
 (:privacy-who-title . "Kim jesteśmy")
 (:privacy-who-body . "Hiisi jest obsługiwane przez Lambda Symbolics OÜ, spółkę zarejestrowaną w Estonii. Jako estońska firma przestrzegamy ogólnego rozporządzenia o ochronie danych (GDPR) Unii Europejskiej.")
 (:privacy-collect-title . "Dane, które zbieramy")
 (:privacy-collect-intro . "Podczas korzystania z Hiisi zbieramy następujące informacje:")
 (:privacy-collect-account-key . "Informacje o koncie: ")
 (:privacy-collect-account-val . "Adres e-mail, nazwa wyświetlana oraz bezpiecznie haszowane hasło.")
 (:privacy-collect-learning-key . "Dane o nauce: ")
 (:privacy-collect-learning-val . "Twoje tłumaczenia, zapisane fiszki i historia powtórek.")
 (:privacy-collect-usage-key . "Dane użycia: ")
 (:privacy-collect-usage-val . "Podstawowe logi serwera do celów bezpieczeństwa i debugowania.")
 (:privacy-use-title . "Jak wykorzystujemy Twoje dane")
 (:privacy-use-auth-key . "Uwierzytelnianie: ")
 (:privacy-use-auth-val . "Aby potwierdzić Twoją tożsamość i zabezpieczyć konto.")
 (:privacy-use-service-key . "Świadczenie usługi: ")
 (:privacy-use-service-val . "Aby dostarczać tłumaczenia i zarządzać Twoją kolekcją fiszek.")
 (:privacy-use-ai-key . "Tłumaczenia AI: ")
 (:privacy-use-ai-val . "Twoje żądania tłumaczeń są wysyłane do API Claude firmy Anthropic w celu wygenerowania odpowiedzi. Zobacz politykę prywatności Anthropic, aby dowiedzieć się, jak przetwarzają te dane.")
 (:privacy-third-title . "Usługi stron trzecich")
 (:privacy-third-intro . "Korzystamy z następujących usług stron trzecich:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "Do tłumaczeń opartych na AI.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "Do wysyłania e-maili aktywacyjnych i transakcyjnych.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Do przetwarzania płatności subskrypcyjnych.")
 (:privacy-cookies-title . "Pliki cookie")
 (:privacy-cookies-intro . "Używamy wyłącznie niezbędnych plików cookie:")
 (:privacy-cookies-auth-key . "Token uwierzytelniania: ")
 (:privacy-cookies-auth-val . "Bezpieczny plik cookie HTTP-only, który utrzymuje zalogowanie.")
 (:privacy-cookies-lang-key . "Preferencja języka: ")
 (:privacy-cookies-lang-val . "Aby zapamiętać preferowany język interfejsu.")
 (:privacy-retention-title . "Przechowywanie danych")
 (:privacy-retention-body . "Twoje dane są przechowywane tak długo, jak utrzymujesz konto. Gdy poprosisz o usunięcie, Twoje konto zostanie zaplanowane do usunięcia za 14 dni.")
 (:privacy-rights-title . "Twoje prawa (GDPR)")
 (:privacy-rights-intro . "Zgodnie z GDPR masz prawo do:")
 (:privacy-rights-access . "Dostępu do swoich danych osobowych")
 (:privacy-rights-export . "Eksportu swoich danych (dostępny pod adresem /app/api/export)")
 (:privacy-rights-correct . "Żądania sprostowania nieprawidłowych danych")
 (:privacy-rights-delete . "Żądania usunięcia konta i danych")
 (:privacy-rights-object . "Sprzeciwu wobec przetwarzania swoich danych")
 (:privacy-rights-contact . "Aby skorzystać z tych praw, skontaktuj się z nami pod adresem")
 (:privacy-contact-title . "Kontakt")
 (:privacy-contact-intro . "W sprawach związanych z prywatnością:")
 (:privacy-contact-email-label . "E-mail: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Estonia")

 ;; Warunki korzystania z usługi
 (:terms-title . "Warunki korzystania z usługi")
 (:terms-updated . "Ostatnia aktualizacja: styczeń 2026")
 (:terms-1-title . "1. Opis usługi")
 (:terms-1-body . "Hiisi to aplikacja do nauki języków oferująca tłumaczenia oparte na AI z wyjaśnieniami gramatycznymi oraz fiszki z rozłożonymi powtórkami. Usługa jest obsługiwana przez Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Rejestracja konta")
 (:terms-2-body . "Aby korzystać z Hiisi, musisz utworzyć konto z prawidłowym adresem e-mail. Odpowiadasz za bezpieczeństwo danych logowania do konta.")
 (:terms-3-title . "3. Subskrypcja i płatności")
 (:terms-3-body . "Hiisi oferuje płatne plany subskrypcji (miesięczny i roczny). Subskrypcje są przetwarzane przez Polar.sh.")
 (:terms-3-list-1 . "Subskrypcje odnawiają się automatycznie, jeśli nie zostaną anulowane przed datą odnowienia.")
 (:terms-3-list-2 . "Zwroty są realizowane zgodnie z obowiązującymi przepisami ochrony konsumentów.")
 (:terms-3-list-3 . "Brak płatności powoduje utratę dostępu do funkcji premium.")
 (:terms-4-title . "4. Dozwolone użycie")
 (:terms-4-intro . "Zgadzasz się, że nie będziesz:")
 (:terms-4-list-1 . "Używać usługi do celów niezgodnych z prawem")
 (:terms-4-list-2 . "Próbować obchodzić limitów użycia ani zabezpieczeń")
 (:terms-4-list-3 . "Udostępniać danych logowania do konta innym osobom")
 (:terms-4-list-4 . "Używać narzędzi automatycznych w sposób pogarszający wydajność usługi dla innych")
 (:terms-5-title . "5. Treści i własność intelektualna")
 (:terms-5-body-1 . "Tłumaczenia generowane przez Hiisi są tworzone przez AI i mogą nie być unikalne. Możesz używać swoich tłumaczeń i fiszek do celów osobistych, ale nie przysługują Ci wyłączne prawa autorskie do treści generowanych przez AI.")
 (:terms-5-body-2 . "Aplikacja Hiisi, marka i oryginalne treści pozostają własnością Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Dostępność usługi")
 (:terms-6-intro . "Hiisi jest dostarczane w stanie takim, jaki jest. Nie gwarantujemy:")
 (:terms-6-list-1 . "Nieprzerwanej i bezbłędnej pracy usługi")
 (:terms-6-list-2 . "Dokładności tłumaczeń generowanych przez AI")
 (:terms-6-list-3 . "Dostępności określonych funkcji")
 (:terms-6-body . "Możemy modyfikować lub wycofywać funkcje w dowolnym momencie.")
 (:terms-7-title . "7. Ograniczenie odpowiedzialności")
 (:terms-7-body-1 . "W maksymalnym zakresie dozwolonym przez prawo Lambda Symbolics OÜ nie ponosi odpowiedzialności za szkody pośrednie, przypadkowe, szczególne ani wtórne wynikające z korzystania z Hiisi.")
 (:terms-7-body-2 . "Nasza łączna odpowiedzialność nie przekroczy kwoty zapłaconej przez Ciebie za usługę w ciągu 12 miesięcy poprzedzających roszczenie.")
 (:terms-8-title . "8. Zakończenie konta")
 (:terms-8-body-1 . "Możemy zawiesić lub zakończyć Twoje konto, jeśli naruszysz te warunki. W dowolnym momencie możesz zażądać usunięcia konta w aplikacji.")
 (:terms-8-body-2 . "Po zgłoszeniu usunięcia Twoje konto zostanie zaplanowane do usunięcia za 14 dni.")
 (:terms-9-title . "9. Zmiany warunków")
 (:terms-9-body . "Możemy okresowo aktualizować te warunki. Dalsze korzystanie z Hiisi po zmianach oznacza akceptację nowych warunków.")
 (:terms-10-title . "10. Prawo właściwe")
 (:terms-10-body . "Niniejsze warunki podlegają prawu Estonii. Wszelkie spory będą rozstrzygane przez sądy Estonii.")
 (:terms-contact-title . "Kontakt")
 (:terms-contact-intro . "W razie pytań dotyczących tych warunków:")
 (:terms-contact-email-label . "E-mail: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Estonia")



 ;; Decks
 (:decks-title . "Talie")
 (:decks-subtitle . "Twórz własne talie i udostępniaj je innym.")
 (:decks-create-title . "Utwórz talię")
 (:decks-name-placeholder . "Nazwa talii")
 (:decks-desc-placeholder . "Opis")
 (:decks-create-btn . "Utwórz talię")
 (:decks-your-title . "Twoje talie")
 (:decks-col-name . "Nazwa")
 (:decks-col-desc . "Opis")
 (:decks-col-updated . "Zaktualizowano")
 (:decks-col-actions . "Akcje")
 (:decks-no-decks . "Brak talii.")
 (:decks-open-btn . "Otwórz")
 (:decks-no-desc . "Brak opisu.")
 (:decks-share-title . "Link do udostępnienia")
 (:decks-share-info . "Każdy z tym linkiem może zaimportować talię:")
 (:decks-share-copy . "Kopiuj link")
 (:decks-share-copied . "Skopiowano")
 (:decks-add-from-flashcards-title . "Dodaj tłumaczenia")
 (:decks-add-from-flashcards-info . "Wybierz fiszkę, aby dodać jej tłumaczenie do tej talii.")
 (:decks-open-flashcards . "Dodaj z fiszek")
 (:decks-filter-from . "Język źródłowy")
 (:decks-filter-to . "Język docelowy")
 (:decks-filter-any . "Dowolny język")
 (:decks-filter-include-assigned . "Uwzględnij fiszki, które są już w talii")
 (:decks-flashcards-col-from . "Z")
 (:decks-flashcards-col-to . "Na")
 (:decks-flashcards-add . "Dodaj")
 (:decks-flashcards-added . "Dodano")
 (:decks-flashcards-in-deck . "W innej talii")
 (:decks-flashcards-empty . "Brak fiszek spełniających te filtry.")
 (:decks-add-trans-title . "Dodaj tłumaczenie")
 (:decks-trans-id-placeholder . "ID tłumaczenia")
 (:decks-add-trans-btn . "Dodaj tłumaczenie")
 (:decks-items-title . "Zawartość talii")
 (:decks-col-original . "Oryginał")
 (:decks-col-translated . "Tłumaczenie")
 (:decks-col-lang . "Język docelowy")
 (:decks-no-items . "Brak elementów.")
 (:decks-share-page-title . "Udostępnij talię")
 (:decks-share-preview . "Podgląd i import tej talii.")
 (:decks-import-title . "Importuj")
 (:decks-import-btn . "Importuj talię")

 ;; Flashcards management page
 (:flashcards-title . "Moje fiszki")
 (:flashcards-subtitle . "Wszystkie zapisane fiszki w jednym miejscu. Szukaj, organizuj i zarządzaj.")
 (:flashcards-search-placeholder . "Szukaj fiszek...")
 (:flashcards-hide-perfected . "Ukryj opanowane fiszki")
 (:flashcards-col-original . "Oryginał")
 (:flashcards-col-translated . "Tłumaczenie")
 (:flashcards-col-lang . "Języki")
 (:flashcards-no-cards . "Brak fiszek. Zacznij tłumaczyć, aby je utworzyć!")

 ;; API errors
 (:api-error-missing-text . "Brak tekstu do tłumaczenia.")
 (:api-error-invalid-translation-id . "Nieprawidłowe ID tłumaczenia.")
 (:api-error-translation-not-found . "Tłumaczenie, które próbowałeś zapisać, już nie istnieje.")
 (:api-error-invalid-bookmark-id . "Nieprawidłowe ID zakładki")
 (:api-error-bookmark-not-found . "Nie znaleziono zakładki")
 (:api-error-forbidden . "Zabronione")
 (:api-error-failed-delete-bookmark . "Nie udało się usunąć zakładki")
 (:api-error-invalid-flashcard-id . "Nieprawidłowe ID fiszki")
 (:api-error-missing-deck-id . "Brak ID talii")
 (:api-error-flashcard-not-found . "Nie znaleziono fiszki")
 (:api-error-deck-not-found . "Nie znaleziono talii")
 (:api-error-deck-name-required . "Nazwa talii jest wymagana")
 (:api-error-session-expired . "Twoja sesja powtórek wygasła. Rozpocznij nową sesję.")
 (:api-error-invalid-card-id . "Nieprawidłowe ID karty.")
 (:api-error-invalid-rating . "Nieprawidłowa ocena.")
 (:api-error-rating-range . "Ocena musi być między 0 a 5.")
 (:api-error-card-not-found . "Nie znaleziono karty.")
 (:api-error-permission-denied . "Nie masz uprawnień do powtarzania tej karty.")
 (:api-error-unknown-source-lang . "Nieznany język źródłowy.")
 (:api-error-unknown-target-lang . "Nieznany język docelowy.")
 (:api-error-failed-add-to-deck . "Nie udało się dodać do talii")

 ;; API success messages
 (:api-success-added . "Dodano!")
 (:api-success-added-simple . "Dodano")

 ;; API stats
 (:api-stats-due . "~A do powtórki")
 (:api-stats-total . "~A łącznie")

 ;; Time units
 (:api-time-day . "dzień")
 (:api-time-days . "dni")
 (:api-time-day-left . "dzień pozostał")
 (:api-time-days-left . "dni pozostało")

 ;; Subscription status
 (:api-subscription-active . "Aktywna")
 (:api-subscription-inactive . "Nieaktywna")
 (:api-subscription-subscribe-hint . "Subskrybuj, aby odblokować tłumaczenia")

 ;; Generic status
 (:status-bad-request . "Nieprawidłowe żądanie")
 (:status-not-found . "Nie znaleziono")
 (:status-forbidden . "Zabronione")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Ucz się języków kompleksowo")
 (:landing-hero-subheadline . "Otrzymuj tłumaczenia z pełną analizą gramatyczną i buduj trwałe słownictwo dzięki fiszkom z powtórkami rozłożonymi w czasie.")
 (:landing-hero-trust-line . "7 dni darmowego okresu próbnego ze 100 tłumaczeniami. Anuluj w każdej chwili.")
 (:landing-credibility-languages . "14 języków")
 (:landing-credibility-ai . "Analiza gramatyczna w zestawie")
 (:landing-credibility-origin . "Stworzone w Estonii")
 (:landing-step-1-title . "Przetłumacz dowolny tekst")
 (:landing-step-1-desc . "Wpisz słowo lub zwrot. Otrzymaj tłumaczenie z pełną analizą gramatyczną.")
 (:landing-step-2-title . "Zapisz jako fiszki")
 (:landing-step-2-desc . "Zapisuj tłumaczenia, które chcesz zapamiętać. Fiszki tworzą się automatycznie.")
 (:landing-step-3-title . "Powtarzaj i zapamiętuj")
 (:landing-step-3-desc . "Powtórki rozłożone w czasie planują przeglądy w idealnym momencie dla pamięci długotrwałej.")
 (:landing-feature-grammar-title . "Zrozum gramatykę, nie tylko słowa")
 (:landing-feature-grammar-desc . "Każde tłumaczenie zawiera szczegółową analizę gramatyczną - formy słów, przypadki i odmiany wyjaśnione w Twoim języku.")
 (:landing-feature-srs-title . "Zapamiętywanie oparte na nauce")
 (:landing-feature-srs-desc . "Algorytm SM-2 dostosowuje się do Twoich wyników. Trudne fiszki pojawiają się częściej. Fiszki, które znasz, pojawiają się rzadziej.")
 (:landing-feature-share-title . "Udostępniaj talie uczniom")
 (:landing-feature-share-desc . "Nauczyciele mogą tworzyć własne talie fiszek i udostępniać je linkiem. Uczniowie importują talię i od razu zaczynają powtórki.")
 (:landing-pricing-trial-note . "Zawiera 7-dniowy darmowy okres próbny")
 (:landing-pricing-monthly-after . "7 dni za darmo, potem ~A/miesiąc")
 (:landing-pricing-annual-after . "7 dni za darmo, potem ~A/rok")
 (:landing-faq-title . "Często zadawane pytania")
 (:landing-faq-trial-cap-q . "Ile tłumaczeń otrzymam w okresie próbnym?")
 (:landing-faq-trial-cap-a . "Otrzymujesz 100 tłumaczeń podczas 7-dniowego okresu próbnego. Po subskrypcji otrzymujesz 600 miesięcznie.")
 (:landing-final-cta-title . "Zacznij uczyć się już dziś")
 (:landing-final-cta-subtitle . "Dołącz do Hiisi i zacznij budować słownictwo, które zostaje na długo.")

 ;; Trial status (in-app)
 (:trial-status . "Darmowy okres próbny")
 (:trial-days-remaining . "Pozostało ~A dni")
 (:trial-translations-used . "~A/100 wykorzystanych tłumaczeń")
 (:trial-upgrade-prompt . "Uaktualnij, aby kontynuować tłumaczenie")
 (:trial-expired . "Twój darmowy okres próbny się zakończył")
 (:trial-expired-detail . "Zasubskrybuj, aby kontynuować naukę z Hiisi.")
 (:trial-quota-warning . "Pozostało ~A próbnych tłumaczeń (~A dni). Zasubskrybuj 600/miesiąc.")
 (:trial-quota-exceeded . "Osiągnięto limit próbnych tłumaczeń. Zasubskrybuj, aby kontynuować.")
 (:error-trial-quota-exceeded . "Osiągnięto limit próbnych tłumaczeń")
 (:error-trial-quota-detail . "Wykorzystałeś wszystkie 100 próbnych tłumaczeń. Zasubskrybuj, aby kontynuować naukę.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Utwórz fiszkę")
 (:custom-flashcard-edit-title . "Edytuj fiszkę")
 (:custom-flashcard-original . "Oryginalny tekst")
 (:custom-flashcard-translated . "Tłumaczenie")
 (:custom-flashcard-lang-from . "Język źródłowy")
 (:custom-flashcard-lang-to . "Język docelowy")
 (:custom-flashcard-note . "Notatka edukacyjna")
 (:custom-flashcard-forms . "Analiza gramatyczna")
 (:custom-flashcard-form-term . "Termin")
 (:custom-flashcard-form-explanation . "Wyjaśnienie")
 (:custom-flashcard-add-form . "Dodaj termin gramatyczny")
 (:custom-flashcard-remove-form . "Usuń")
 (:custom-flashcard-ai-fill . "Wypełnij za pomocą AI")
 (:custom-flashcard-ai-fill-all . "Wypełnij wszystko za pomocą AI")
 (:custom-flashcard-ai-fill-translation . "Przetłumacz za pomocą AI")
 (:custom-flashcard-ai-fill-breakdown . "Wygeneruj analizę")
 (:custom-flashcard-ai-fill-note . "Wygeneruj notatkę")
 (:custom-flashcard-create-btn . "Utwórz fiszkę")
 (:custom-flashcard-update-btn . "Zapisz zmiany")
 (:custom-flashcard-delete-btn . "Usuń fiszkę")
 (:custom-flashcard-delete-confirm . "Czy na pewno chcesz usunąć tę fiszkę?")
 (:custom-flashcard-created . "Fiszka utworzona pomyślnie")
 (:custom-flashcard-updated . "Fiszka zaktualizowana pomyślnie")
 (:custom-flashcard-deleted . "Fiszka usunięta pomyślnie")
 (:custom-flashcard-add-to-deck . "Dodaj do talii")
 (:custom-flashcard-not-found . "Fiszka nie znaleziona")
 (:custom-flashcard-not-owner . "Możesz edytować tylko fiszki, które sam utworzyłeś")
 (:custom-flashcard-ai-generating . "Generowanie za pomocą AI...")
 (:custom-flashcard-badge . "Własna")

 ;; Zgłaszanie problemów
 (:issues-open-button . "Zgłoś problem")
 (:issues-modal-title . "Zgłoś problem")
 (:issues-modal-subtitle . "Opisz, co poszło nie tak. Automatycznie dołączymy bieżącą stronę.")
 (:issues-title-label . "Krótki tytuł")
 (:issues-title-placeholder . "Krótkie podsumowanie problemu")
 (:issues-message-label . "Co się stało?")
 (:issues-message-placeholder . "Podaj kroki odtworzenia, oczekiwane działanie i to, co wydarzyło się zamiast tego.")
 (:issues-submit . "Wyślij zgłoszenie")
 (:issues-cancel . "Anuluj")
 (:issues-success . "Dziękujemy. Twoje zgłoszenie zostało wysłane.")
 (:issues-error-required . "Opisz problem przed wysłaniem.")
 (:issues-error-title-too-long . "Tytuł zgłoszenia jest za długi. Utrzymaj go poniżej 160 znaków.")
 (:issues-error-too-long . "Treść zgłoszenia jest za długa. Zachowaj limit 4000 znaków.")
 (:issues-error-rate-limit . "Zbyt wiele zgłoszeń z tego źródła. Poczekaj i spróbuj ponownie później.")
 (:issues-error-generic . "Nie udało się wysłać zgłoszenia. Spróbuj ponownie.")

)
