;;; Polish translations
;;; This file should contain all keys from en.lisp

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Polski")
 (:lang-flag . "🇵🇱")

 ;; Navigation
 (:nav-translate . "Tłumacz")
 (:nav-review . "Powtórka")
 (:nav-dashboard . "Panel")
 (:nav-logout . "Wyloguj")
 (:nav-home . "Strona główna")
 (:nav-pricing . "Cennik")
 (:nav-export-data . "Eksportuj dane")

 ;; App title and branding
 (:app-title . "Hiisi")
 (:app-tagline . "Ucz się języków przez tłumaczenia")

 ;; Landing page
 (:landing-hero-title . "Opanuj każdy język")
 (:landing-hero-subtitle . "Tłumacz cokolwiek. Automatycznie generuj fiszki, które uczą dlaczego to tak działa.")
 (:landing-cta . "Zacznij naukę")
 (:landing-learn-more . "Dowiedz się więcej")
 (:landing-how-it-works . "Jak to działa")
 (:landing-feature-1-title . "Automatyczne fiszki")
 (:landing-feature-1-desc . "Każde tłumaczenie automatycznie generuje fiszki z rozkładem gramatycznym. Bez ręcznego tworzenia kart.")
 (:landing-feature-2-title . "Powtórki rozłożone w czasie")
 (:landing-feature-2-desc . "Algorytm SM-2 planuje powtórki w optymalnych odstępach. Ucz się efektywnie, zapamiętuj na stałe.")
 (:landing-feature-3-title . "Nauka gramatyki")
 (:landing-feature-3-desc . "Każde tłumaczenie wyjaśnia gramatykę, pochodzenie słów i strukturę zdania. Zrozum dlaczego, nie tylko co.")
 (:landing-free-trial . "7-dniowy okres próbny. Karta kredytowa nie jest wymagana.")
 (:landing-start-trial . "Rozpocznij bezpłatny okres próbny")
 (:landing-best-value . "Najlepsza oferta")
 (:landing-cta-title . "Gotowy uczyć się języków przez gramatykę, a nie wkuwanie?")
 (:landing-cta-subtitle . "Każde tłumaczenie staje się okazją do nauki. Każda fiszka uczy dlaczego.")
 (:landing-signup-free . "Zarejestruj się za darmo")

 ;; Auth pages
 (:auth-register . "Zarejestruj się")
 (:auth-login . "Zaloguj się")
 (:auth-logout . "Wyloguj")
 (:auth-email . "Email")
 (:auth-password . "Hasło")
 (:auth-password-again . "Potwierdź hasło")
 (:auth-display-name . "Nazwa wyświetlana")
 (:auth-register-title . "Zarejestruj się w Hiisi")
 (:auth-register-subtitle . "Utwórz nowe konto")
 (:auth-login-title . "Zaloguj się do Hiisi")
 (:auth-login-subtitle . "Wprowadź swoje dane")
 (:auth-forgot-password . "Zapomniałeś hasła?")
 (:auth-no-account . "Nie masz konta?")
 (:auth-have-account . "Masz już konto?")

 ;; Translation page
 (:translate-title . "Tłumacz")
 (:translate-input-label . "Tekst do przetłumaczenia")
 (:translate-input-placeholder . "Wprowadź tekst do przetłumaczenia...")
 (:translate-from . "Z:")
 (:translate-to . "Na:")
 (:translate-submit . "Przetłumacz")
 (:translate-save . "Zapisz do fiszek")
 (:translate-saved . "Zapisano!")
 (:translate-like . "Lubię")
 (:translate-dislike . "Nie lubię")
 (:translate-char-limit . "znaków pozostało")
 (:translate-auto-detect . "Dowolny (Autowykrywanie)")
 (:translate-empty-state . "Wprowadź tekst powyżej i kliknij Przetłumacz, aby zobaczyć wynik z rozkładem gramatycznym")

 ;; Flashcard review
 (:review-title . "Powtórka")
 (:review-session-title . "Sesja powtórkowa")
 (:review-session-subtitle . "Ćwicz zapisane fiszki")
 (:review-start . "Rozpocznij powtórkę")
 (:review-no-cards . "Brak fiszek do powtórki")
 (:review-no-cards-desc . "Nie masz teraz żadnych fiszek do powtórki.")
 (:review-no-cards-hint . "Przetłumacz tekst i kliknij \"Zapisz do fiszek\", aby zbudować swoją talię!")
 (:review-start-translating . "Zacznij tłumaczyć")
 (:review-show-answer . "Pokaż odpowiedź")
 (:review-click-reveal . "Kliknij, aby odsłonić odpowiedź")
 (:review-grammar-breakdown . "Rozkład gramatyczny")
 (:review-how-well . "Jak dobrze pamiętałeś?")
 (:review-again . "Jeszcze raz")
 (:review-hard . "Trudne")
 (:review-good . "Dobrze")
 (:review-easy . "Łatwe")
 (:review-progress . "Fiszka ~a z ~a")
 (:review-complete . "Sesja zakończona!")
 (:review-complete-msg . "Powtórzyłeś ~a fiszek")
 (:review-correct . "Poprawnie")
 (:review-accuracy . "Dokładność")
 (:review-again-btn . "Powtórz ponownie")
 (:review-translate-more . "Tłumacz więcej")
 (:review-streak . "dni z rzędu")

 ;; Dashboard
 (:dashboard-title . "Panel")
 (:dashboard-cards-due . "Fiszki na dziś")
 (:dashboard-total-cards . "Wszystkie fiszki")
 (:dashboard-subscription . "Subskrypcja")
 (:dashboard-subscribed-until . "Subskrypcja do")
 (:dashboard-not-subscribed . "Brak subskrypcji")
 (:dashboard-recent . "Ostatnie tłumaczenia")
 (:dashboard-no-translations . "Brak tłumaczeń")
 (:dashboard-streak . "Seria powtórek")
 (:dashboard-days . "dni")
 (:dashboard-quick-actions . "Szybkie akcje")
 (:dashboard-getting-started . "Jak zacząć")
 (:dashboard-tip-1 . "Tłumacz tekst, którego chcesz się nauczyć")
 (:dashboard-tip-2 . "Kliknij \"Zapisz do fiszek\" przy tłumaczeniach, które chcesz zapamiętać")
 (:dashboard-tip-3 . "Regularnie powtarzaj fiszki - powtórki rozłożone w czasie pomagają zapamiętać na dłużej")
 (:dashboard-tip-4 . "Oceniaj szczerze - pomaga to algorytmowi optymalnie planować powtórki")

 ;; Subscription
 (:subscribe-title . "Prosty cennik")
 (:subscribe-monthly . "Miesięczny")
 (:subscribe-annual . "Roczny")
 (:subscribe-monthly-price . "10€/miesiąc")
 (:subscribe-annual-price . "100€/rok")
 (:subscribe-monthly-desc . "600 tłumaczeń miesięcznie")
 (:subscribe-annual-desc . "Zaoszczędź 20€ — dwa miesiące gratis!")
 (:subscribe-cta . "Subskrybuj")
 (:subscribe-success . "Subskrypcja aktywna!")
 (:subscribe-manage . "Zarządzaj subskrypcją")

 ;; Errors and status
 (:error-generic . "Coś poszło nie tak")
 (:error-not-found . "Strona nie znaleziona")
 (:error-unauthorized . "Zaloguj się, aby kontynuować")
 (:error-subscription-required . "Wymagana subskrypcja")
 (:error-text-too-long . "Tekst jest za długi. Maksymalna długość tłumaczenia to 120 znaków.")
 (:error-input-too-long . "Tekst za długi")
 (:error-unknown-source-lang . "Wybrany język źródłowy nie jest obsługiwany.")
 (:error-unknown-target-lang . "Wybrany język docelowy nie jest obsługiwany.")
 (:error-unknown-language . "Nieznany język")
 (:error-translation-unavailable . "Usługa tłumaczenia jest chwilowo niedostępna. Spróbuj ponownie za chwilę.")
 (:error-translation-failed . "Tłumaczenie nie powiodło się")
 (:error-translation-retry . "Nie udało się wygenerować tłumaczenia po wielu próbach. Spróbuj przeformułować tekst.")
 (:loading . "Ładowanie...")
 (:empty-state . "Nic tu jeszcze nie ma")

 ;; Footer
 (:footer-privacy . "Polityka prywatności")
 (:footer-terms . "Regulamin")
 (:footer-contact . "Kontakt")
)
