;;; Portuguese translations
;;; This file follows the structure of en.lisp (authoritative source)

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Português")
 (:lang-flag . "🇵🇹")

 ;; Navigation
 (:nav-translate . "Traduzir")
 (:nav-review . "Revisar")
 (:nav-dashboard . "Painel")
 (:nav-logout . "Sair")
 (:nav-home . "Início")
 (:nav-pricing . "Preços")
 (:nav-export-data . "Exportar Dados")

 ;; App title and branding
 (:app-title . "Hiisi")
 (:app-tagline . "Aprenda idiomas através de traduções")

 ;; Landing page
 (:landing-hero-title . "Domine Qualquer Idioma")
 (:landing-hero-subtitle . "Traduza qualquer coisa. Gere automaticamente flashcards que ensinam por que funciona assim.")
 (:landing-cta . "Começar a Aprender")
 (:landing-learn-more . "Saiba Mais")
 (:landing-how-it-works . "Como Funciona")
 (:landing-feature-1-title . "Flashcards Automáticos")
 (:landing-feature-1-desc . "Cada tradução gera automaticamente flashcards com análise gramatical. Sem criação manual de cartões.")
 (:landing-feature-2-title . "Repetição Espaçada")
 (:landing-feature-2-desc . "O algoritmo SM-2 agenda revisões em intervalos ideais. Aprenda eficientemente, lembre-se permanentemente.")
 (:landing-feature-3-title . "Ensino de Gramática")
 (:landing-feature-3-desc . "Cada tradução explica gramática, raízes das palavras e estrutura das frases. Entenda o porquê, não apenas o quê.")
 (:landing-free-trial . "7 dias de teste grátis. Sem necessidade de cartão de crédito.")
 (:landing-start-trial . "Iniciar Teste Grátis")
 (:landing-best-value . "Melhor Valor")
 (:landing-cta-title . "Pronto para aprender idiomas através da gramática, não da memorização?")
 (:landing-cta-subtitle . "Cada tradução se torna uma oportunidade de aprendizado. Cada flashcard ensina o porquê.")
 (:landing-signup-free . "Cadastre-se Grátis")

 ;; Auth pages
 (:auth-register . "Registrar")
 (:auth-login . "Entrar")
 (:auth-logout . "Sair")
 (:auth-email . "Email")
 (:auth-password . "Senha")
 (:auth-password-again . "Confirmar Senha")
 (:auth-display-name . "Nome de Exibição")
 (:auth-register-title . "Registre-se no Hiisi")
 (:auth-register-subtitle . "Criar uma nova conta")
 (:auth-login-title . "Entrar no Hiisi")
 (:auth-login-subtitle . "Digite suas credenciais")
 (:auth-forgot-password . "Esqueceu a senha?")
 (:auth-no-account . "Não tem uma conta?")
 (:auth-have-account . "Já tem uma conta?")
 (:auth-google . "Google")
 (:auth-account-created . "Conta criada!")
 (:auth-check-email . "Verifique seu email para o link de ativação.")
 (:auth-redirect-login . "Redirecionando para login em")
 (:auth-seconds . "segundos...")
 (:auth-go-now . "Ir agora")
 (:auth-not-activated . "Conta não ativada")
 (:auth-activate-title . "Ative sua conta!")

 ;; Translation page
 (:translate-title . "Traduzir")
 (:translate-input-label . "Texto para traduzir")
 (:translate-input-placeholder . "Digite o texto para traduzir...")
 (:translate-from . "De:")
 (:translate-to . "Para:")
 (:translate-submit . "Traduzir")
 (:translate-save . "Salvar em Flashcards")
 (:translate-saved . "Salvo!")
 (:translate-like . "Gostei")
 (:translate-dislike . "Não Gostei")
 (:translate-char-limit . "caracteres restantes")
 (:translate-auto-detect . "Qualquer (Detectar automaticamente)")
 (:translate-empty-state . "Digite o texto acima e clique em Traduzir para ver o resultado com análise gramatical")

 ;; Flashcard review
 (:review-title . "Revisar")
 (:review-session-title . "Sessão de Revisão")
 (:review-session-subtitle . "Pratique seus flashcards salvos")
 (:review-start . "Iniciar Revisão")
 (:review-no-cards . "Nenhum Cartão para Revisar")
 (:review-no-cards-desc . "Você não tem nenhum flashcard pendente para revisão agora.")
 (:review-no-cards-hint . "Traduza algum texto e clique em \"Salvar em Flashcards\" para construir seu baralho!")
 (:review-start-translating . "Começar a Traduzir")
 (:review-show-answer . "Mostrar Resposta")
 (:review-click-reveal . "Clique para revelar a resposta")
 (:review-grammar-breakdown . "Análise Gramatical")
 (:review-how-well . "Quão bem você lembrou?")
 (:review-again . "De Novo")
 (:review-hard . "Difícil")
 (:review-good . "Bom")
 (:review-easy . "Fácil")
 (:review-progress . "Cartão ~a de ~a")
 (:review-complete . "Sessão Completa!")
 (:review-complete-msg . "Você revisou ~a cartões")
 (:review-correct . "Corretos")
 (:review-accuracy . "Precisão")
 (:review-again-btn . "Revisar Novamente")
 (:review-translate-more . "Traduzir Mais")
 (:review-streak . "dias de sequência")

 ;; Dashboard
 (:dashboard-title . "Painel")
 (:dashboard-cards-due . "Cartões Pendentes")
 (:dashboard-total-cards . "Total de Cartões")
 (:dashboard-subscription . "Assinatura")
 (:dashboard-subscribed-until . "Assinado até")
 (:dashboard-not-subscribed . "Não assinado")
 (:dashboard-recent . "Traduções Recentes")
 (:dashboard-no-translations . "Nenhuma tradução ainda")
 (:dashboard-streak . "Sequência de Revisão")
 (:dashboard-days . "dias")
 (:dashboard-quick-actions . "Ações Rápidas")
 (:dashboard-getting-started . "Primeiros Passos")
 (:dashboard-tip-1 . "Traduza textos que você quer aprender")
 (:dashboard-tip-2 . "Clique em \"Salvar em Flashcards\" nas traduções que você quer lembrar")
 (:dashboard-tip-3 . "Revise seus flashcards regularmente - a repetição espaçada ajuda você a lembrar a longo prazo")
 (:dashboard-tip-4 . "Avalie honestamente - isso ajuda o algoritmo a agendar suas revisões de forma ideal")

 ;; Subscription
 (:subscribe-title . "Preços Simples")
 (:subscribe-choose-plan . "Escolha Seu Plano")
 (:subscribe-start-today . "Comece a aprender hoje com 7 dias de teste grátis")
 (:subscribe-monthly . "Mensal")
 (:subscribe-annual . "Anual")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/mês")
 (:subscribe-per-year . "/ano")
 (:subscribe-monthly-desc . "600 traduções por mês")
 (:subscribe-unlimited-flashcards . "Flashcards ilimitados")
 (:subscribe-grammar-explanations . "Explicações gramaticais")
 (:subscribe-spaced-repetition . "Repetição espaçada")
 (:subscribe-annual-desc . "Economize €20 — dois meses grátis!")
 (:subscribe-cta . "Assinar")
 (:subscribe-success . "Assinatura Bem-sucedida!")
 (:subscribe-manage . "Gerenciar Assinatura")
 (:subscribe-activated . "Assinatura Ativada!")
 (:subscribe-thank-you . "Obrigado por assinar. Sua conta agora está ativa.")
 (:subscribe-start-learning . "Começar a Aprender")
 (:subscribe-management . "Gerenciamento de Assinatura")
 (:subscribe-active . "Assinatura Ativa")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Ativa")
 (:subscribe-days-remaining . "Dias restantes:")
 (:subscribe-renews-on . "Renova em:")
 (:subscribe-no-subscription . "Nenhuma Assinatura Ativa")
 (:subscribe-access-features . "Assine para acessar todos os recursos.")
 (:subscribe-view-plans . "Ver Planos")
 (:subscribe-faq-title . "Perguntas Frequentes")
 (:subscribe-faq-trial-q . "O que acontece após o teste grátis?")
 (:subscribe-faq-trial-a . "Após os 7 dias de teste grátis, você será cobrado pelo plano selecionado. Você pode cancelar a qualquer momento antes do fim do teste.")
 (:subscribe-faq-cancel-q . "Posso cancelar a qualquer momento?")
 (:subscribe-faq-cancel-a . "Sim! Você pode cancelar sua assinatura a qualquer momento. Você manterá o acesso até o final do seu período de cobrança.")
 (:subscribe-faq-payment-q . "Quais métodos de pagamento vocês aceitam?")
 (:subscribe-faq-payment-a . "Aceitamos todos os principais cartões de crédito e débito através do nosso parceiro de pagamentos Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Algo deu errado")
 (:error-not-found . "Página não encontrada")
 (:error-unauthorized . "Faça login para continuar")
 (:error-subscription-required . "Assinatura necessária")
 (:error-text-too-long . "O texto é muito longo. O comprimento máximo da tradução é de 120 caracteres.")
 (:error-input-too-long . "Entrada Muito Longa")
 (:error-unknown-source-lang . "O idioma de origem selecionado não é suportado.")
 (:error-unknown-target-lang . "O idioma de destino selecionado não é suportado.")
 (:error-unknown-language . "Idioma Desconhecido")
 (:error-translation-unavailable . "O serviço de tradução está temporariamente indisponível. Por favor, tente novamente em um momento.")
 (:error-translation-failed . "Tradução Falhou")
 (:error-translation-retry . "Não foi possível gerar uma tradução após várias tentativas. Por favor, tente reformular seu texto.")
 (:loading . "Carregando...")
 (:empty-state . "Nada aqui ainda")

 ;; Footer
 (:footer-privacy . "Política de Privacidade")
 (:footer-terms . "Termos de Serviço")
 (:footer-contact . "Contato")
)
