;;; Portuguese translations
;;; This file follows the structure of en.lisp (authoritative source)

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Português")
 (:lang-flag . "🇵🇹")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Escolha seu idioma")
 (:lang-modal-subtitle . "Selecione seu idioma preferido para a interface:")

 ;; Navigation
 (:nav-translate . "Traduzir")
 (:nav-review . "Revisar")
 (:nav-flashcards . "Meus cartões")
 (:nav-dashboard . "Painel")
 (:nav-decks . "Decks")
 (:nav-logout . "Sair")
 (:nav-home . "Início")
 (:nav-pricing . "Preços")
 (:nav-export-data . "Exportar Dados")

 ;; App title and branding
 (:app-title . "Hiisi - Aprendizado de idiomas")
 (:app-tagline . "Aprenda idiomas através de traduções")

 ;; Landing page
 (:landing-hero-title . "Domine Qualquer Idioma")
 (:landing-hero-subtitle . "Traduza qualquer coisa. Gere automaticamente flashcards que ensinam por que funciona assim.")
 (:landing-cta . "Começar a Aprender")
 (:landing-learn-more . "Saiba Mais")
 (:landing-how-it-works . "Como Funciona")
 (:landing-feature-1-title . "Flashcards Automáticos")
 (:landing-feature-1-desc . "Cada tradução gera automaticamente flashcards com análise gramatical. Sem criação manual de cartões.")
 (:landing-feature-2-title . "Repetição Espaçada")
 (:landing-feature-2-desc . "O algoritmo SM-2 agenda revisões em intervalos ideais. Aprenda eficientemente, lembre-se permanentemente.")
 (:landing-feature-3-title . "Ensino de Gramática")
 (:landing-feature-3-desc . "Cada tradução explica gramática, raízes das palavras e estrutura das frases. Entenda o porquê, não apenas o quê.")
 (:landing-free-trial . "7 dias de teste grátis. Sem necessidade de cartão de crédito.")
 (:landing-start-trial . "Iniciar Teste Grátis")
 (:landing-best-value . "Melhor Valor")
 (:landing-cta-title . "Pronto para aprender idiomas através da gramática, não da memorização?")
 (:landing-cta-subtitle . "Cada tradução se torna uma oportunidade de aprendizado. Cada flashcard ensina o porquê.")
 (:landing-signup-free . "Cadastre-se Grátis")

 ;; Auth pages
 (:auth-register . "Registrar")
 (:auth-login . "Entrar")
 (:auth-logout . "Sair")
 (:auth-email . "Email")
 (:auth-password . "Senha")
 (:auth-password-again . "Confirmar Senha")
 (:auth-display-name . "Nome de Exibição")
 (:auth-register-title . "Registre-se no Hiisi")
 (:auth-register-subtitle . "Criar uma nova conta")
 (:auth-login-title . "Entrar no Hiisi")
 (:auth-login-subtitle . "Digite suas credenciais")
 (:auth-forgot-password . "Esqueceu a senha?")
 (:auth-no-account . "Não tem uma conta?")
 (:auth-have-account . "Já tem uma conta?")
 (:auth-google . "Google")
 (:auth-account-created . "Conta criada!")
 (:auth-check-email . "Verifique seu email para o link de ativação.")
 (:auth-redirect-login . "Redirecionando para login em")
 (:auth-seconds . "segundos...")
 (:auth-go-now . "Ir agora")
 (:auth-not-activated . "Conta não ativada")
 (:auth-activate-title . "Ative sua conta!")
 (:auth-activated . "Conta ativada!")
 (:auth-activated-message . "Sua conta foi ativada. Agora você pode usar o Hiisi.")
 (:auth-redirecting . "Redirecionando em")
 (:auth-go-to-app . "Ir para o app")
 (:auth-resend-title . "Reenviar email de ativação")
 (:auth-resend-subtitle . "Digite seu email para receber um novo link de ativação.")
 (:auth-resend-button . "Reenviar email de ativação")
 (:auth-resend-success . "Email de ativação enviado!")
 (:auth-resend-success-detail . "Verifique sua caixa de entrada para o novo link de ativação.")
 (:auth-resend-rate-limited . "Por favor aguarde alguns minutos antes de solicitar outro email de ativação.")
 (:auth-resend-cooldown . "Você pode solicitar outro email em ~a segundos.")
 (:auth-back-to-login . "Voltar ao login")
 (:auth-forgot-password-title . "Esqueci a senha")
 (:auth-forgot-password-subtitle . "Digite seu email e enviaremos um link para redefinir sua senha.")
 (:auth-send-reset-link . "Enviar link de redefinição")
 (:auth-reset-email-sent . "Link enviado!")
 (:auth-reset-email-sent-detail . "Se uma conta existe com esse email, você receberá um link de redefinição de senha em breve.")
 (:auth-reset-rate-limited . "Por favor aguarde alguns minutos antes de solicitar outra redefinição de senha.")
 (:auth-reset-invalid-token . "Este link de redefinição é inválido ou expirou.")
 (:auth-reset-password-title . "Redefinir senha")
 (:auth-reset-password-subtitle . "Digite sua nova senha abaixo.")
 (:auth-new-password . "Nova senha")
 (:auth-confirm-new-password . "Confirmar nova senha")
 (:auth-reset-password . "Redefinir senha")
 (:auth-password-changed . "Senha alterada!")
 (:auth-password-changed-detail . "Sua senha foi alterada com sucesso. Agora você pode entrar com sua nova senha.")
 (:auth-change-password-title . "Alterar senha")
 (:auth-change-password-subtitle . "Atualize a senha da sua conta.")
 (:auth-current-password . "Senha atual")
 (:auth-change-password . "Alterar senha")
 (:auth-back-to-app . "Voltar para o app")
 (:auth-password-updated . "Senha atualizada!")
 (:auth-password-updated-detail . "Sua senha foi atualizada com sucesso.")

 ;; Translation page
 (:translate-title . "Traduzir")
 (:translate-input-label . "Texto para traduzir")
 (:translate-input-placeholder . "Digite o texto para traduzir...")
 (:translate-from . "De:")
 (:translate-to . "Para:")
 (:translate-submit . "Traduzir")
 (:translate-save . "Salvar em Flashcards")
 (:translate-saved . "Salvo!")
 (:translate-like . "Gostei")
 (:translate-dislike . "Não Gostei")
 (:translate-char-limit . "caracteres restantes")
 (:translate-auto-detect . "Qualquer (Detectar automaticamente)")
 (:translate-empty-state . "Digite o texto acima e clique em Traduzir para ver o resultado com análise gramatical")
 (:translate-select-deck-placeholder . "Selecionar baralho (opcional)")
 (:translate-new-deck . "Novo baralho")
 (:translate-add-to-deck . "Adicionar ao baralho")
 (:translate-bookmark . "Salvar")
 (:translate-bookmarked . "Salvo")
 (:translate-retry . "Tentar novamente")
 (:translate-like-tooltip . "Boa tradução")
 (:translate-dislike-tooltip . "Má tradução - solicitar uma nova")
 (:translate-dislike-confirm . "Isso gerará uma nova tradução. Continuar?")
 (:translate-liked . "Gostei!")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Destino")
 (:translate-deck-create-title . "Criar novo baralho")
 (:translate-deck-name-label . "Nome do baralho")
 (:translate-deck-name-placeholder . "ex.: Fundamentos de finlandês")
 (:translate-deck-description-label . "Descrição (opcional)")
 (:translate-deck-cancel . "Cancelar")
 (:translate-deck-create . "Criar")
 (:translate-rate-label . "Avaliar tradução")
 (:flashcards-delete-confirm . "Tem certeza de que deseja excluir este cartão?")
 (:flashcards-deck-search-placeholder . "Pesquisar baralhos...")
 (:flashcards-no-decks . "Ainda não há baralhos. Crie um primeiro!")
 (:flashcards-deck-cancel . "Cancelar")

 ;; Flashcard review
 (:review-title . "Revisar")
 (:review-session-title . "Sessão de Revisão")
 (:review-session-subtitle . "Pratique seus flashcards salvos")
 (:review-start . "Iniciar Revisão")
 (:review-no-cards . "Nenhum Cartão para Revisar")
 (:review-no-cards-desc . "Você não tem nenhum flashcard pendente para revisão agora.")
 (:review-no-cards-hint . "Traduza algum texto e clique em \"Salvar em Flashcards\" para construir seu baralho!")
 (:review-start-translating . "Começar a Traduzir")
 (:review-show-answer . "Mostrar Resposta")
 (:review-click-reveal . "Clique para revelar a resposta")
 (:review-grammar-breakdown . "Análise Gramatical")
 (:review-how-well . "Quão bem você lembrou?")
 (:review-again . "De Novo")
 (:review-hard . "Difícil")
 (:review-good . "Bom")
 (:review-easy . "Fácil")
 (:review-progress . "Cartão ~a de ~a")
 (:review-complete . "Sessão Completa!")
 (:review-complete-msg . "Você revisou ~a cartões")
 (:review-correct . "Corretos")
 (:review-accuracy . "Precisão")
 (:review-again-btn . "Revisar Novamente")
 (:review-translate-more . "Traduzir Mais")
 (:review-streak . "dias de sequência")

 ;; Dashboard
 (:dashboard-title . "Painel")
 (:dashboard-cards-due . "Cartões Pendentes")
 (:dashboard-total-cards . "Total de Cartões")
 (:dashboard-subscription . "Assinatura")
 (:dashboard-subscribed-until . "Assinado até")
 (:dashboard-not-subscribed . "Não assinado")
 (:dashboard-recent . "Traduções Recentes")
 (:dashboard-no-translations . "Nenhuma tradução ainda")
 (:dashboard-streak . "Sequência de Revisão")
 (:dashboard-days . "dias")
 (:dashboard-quick-actions . "Ações Rápidas")
 (:dashboard-getting-started . "Primeiros Passos")
 (:dashboard-tip-1 . "Traduza textos que você quer aprender")
 (:dashboard-tip-2 . "Clique em \"Salvar em Flashcards\" nas traduções que você quer lembrar")
 (:dashboard-tip-3 . "Revise seus flashcards regularmente - a repetição espaçada ajuda você a lembrar a longo prazo")
 (:dashboard-tip-4 . "Avalie honestamente - isso ajuda o algoritmo a agendar suas revisões de forma ideal")

 ;; Account
 (:account-title . "Conta")
 (:account-subtitle . "Gerencie as configurações da sua conta e o agendamento de exclusão.")
 (:account-deletion-title . "Exclusão da conta")
 (:account-deletion-scheduled . "Sua conta está programada para exclusão em ~A.")
 (:account-deletion-cancel-hint . "Você pode cancelar antes dessa data para manter sua conta.")
 (:account-deletion-cancel . "Cancelar exclusão")
 (:account-deletion-request . "Você pode solicitar a exclusão da conta a qualquer momento. A exclusão é programada para 14 dias após a confirmação. Se você mudar de ideia após a exclusão, entre em contato com o suporte.")
 (:account-deletion-confirm . "Agendar a exclusão da conta para 14 dias a partir de hoje?")
 (:account-deletion-schedule . "Agendar exclusão")
 (:account-reminders-title . "Lembretes por e-mail")
 (:account-reminders-subtitle . "Controle lembretes de revisão e continuação para esta conta.")
 (:account-reminders-opt-out . "Desativar lembretes de revisão e continuação")
 (:account-reminders-save . "Salvar preferências")

 ;; Subscription
 (:subscribe-title . "Preços Simples")
 (:subscribe-choose-plan . "Escolha Seu Plano")
 (:subscribe-start-today . "Comece a aprender hoje com 7 dias de teste grátis")
 (:subscribe-monthly . "Mensal")
 (:subscribe-annual . "Anual")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/mês")
 (:subscribe-per-year . "/ano")
 (:subscribe-monthly-desc . "600 traduções por mês")
 (:subscribe-unlimited-flashcards . "Flashcards ilimitados")
 (:subscribe-grammar-explanations . "Explicações gramaticais")
 (:subscribe-spaced-repetition . "Repetição espaçada")
 (:subscribe-annual-desc . "Economize €20 — dois meses grátis!")
 (:subscribe-cta . "Assinar")
 (:subscribe-success . "Assinatura Bem-sucedida!")
 (:subscribe-manage . "Gerenciar Assinatura")
 (:subscribe-activated . "Assinatura Ativada!")
 (:subscribe-thank-you . "Obrigado por assinar. Sua conta agora está ativa.")
 (:subscribe-start-learning . "Começar a Aprender")
 (:subscribe-management . "Gerenciamento de Assinatura")
 (:subscribe-active . "Assinatura Ativa")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Ativa")
 (:subscribe-days-remaining . "Dias restantes:")
 (:subscribe-renews-on . "Renova em:")
 (:subscribe-no-subscription . "Nenhuma Assinatura Ativa")
 (:subscribe-access-features . "Assine para acessar todos os recursos.")
 (:subscribe-view-plans . "Ver Planos")
 (:subscribe-faq-title . "Perguntas Frequentes")
 (:subscribe-faq-trial-q . "O que acontece após o teste grátis?")
 (:subscribe-faq-trial-a . "Após os 7 dias de teste grátis, você será cobrado pelo plano selecionado. Você pode cancelar a qualquer momento antes do fim do teste.")
 (:subscribe-faq-cancel-q . "Posso cancelar a qualquer momento?")
 (:subscribe-faq-cancel-a . "Sim! Você pode cancelar sua assinatura a qualquer momento. Você manterá o acesso até o final do seu período de cobrança.")
 (:subscribe-faq-payment-q . "Quais métodos de pagamento vocês aceitam?")
 (:subscribe-faq-payment-a . "Aceitamos todos os principais cartões de crédito e débito através do nosso parceiro de pagamentos Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Algo deu errado")
 (:error-not-found . "Página não encontrada")
 (:error-unauthorized . "Faça login para continuar")
 (:error-subscription-required . "Assinatura necessária")
 (:error-text-too-long . "O texto é muito longo. O comprimento máximo da tradução é de 120 caracteres.")
 (:error-input-too-long . "Entrada Muito Longa")
 (:error-unknown-source-lang . "O idioma de origem selecionado não é suportado.")
 (:error-unknown-target-lang . "O idioma de destino selecionado não é suportado.")
 (:error-unknown-language . "Idioma Desconhecido")
 (:error-translation-unavailable . "O serviço de tradução está temporariamente indisponível. Por favor, tente novamente em um momento.")
 (:error-translation-failed . "Tradução Falhou")
 (:error-translation-retry . "Não foi possível gerar uma tradução após várias tentativas. Por favor, tente reformular seu texto.")
 (:error-quota-exceeded . "Limite de traduções atingido")
 (:error-quota-exceeded-detail . "Você usou todas as suas traduções deste mês. Sua cota é redefinida automaticamente todo mês.")
 (:quota-warning . "Traduções restantes: ~A")
 (:quota-low-warning . "Apenas ~A traduções restantes. Considere comprar mais.")
 (:top-up-button . "Comprar mais traduções")
 (:top-up-success . "Recarga bem-sucedida! Agora você tem ~A traduções adicionais.")
 (:top-up-price . "€5")
 (:top-up-amount . "300 traduções")
 (:loading . "Carregando...")
 (:empty-state . "Nada aqui ainda")

 ;; Institutions
 (:institutions-page-title . "Hiisi para escolas - licenças institucionais")
 (:institutions-hero-title . "Hiisi para escolas")
 (:institutions-hero-subtitle . "Capacite seus estudantes com aprendizagem de idiomas com IA")
 (:institutions-section-title . "Licenças institucionais")
 (:institutions-section-body . "Oferecemos licenças em volume para escolas, universidades e instituições de idiomas. Estudantes com endereços de email do seu domínio recebem acesso completo automaticamente.")
 (:institutions-benefit-1 . "Matrícula automática para estudantes com email institucional")
 (:institutions-benefit-2 . "Sem contas individuais de estudantes para gerenciar")
 (:institutions-benefit-3 . "Opções de faturamento flexíveis")
 (:institutions-benefit-4 . "Suporte dedicado para educadores")
 (:institutions-request-title . "Solicitar uma licença")
 (:institutions-request-subtitle . "Preencha o formulário abaixo e retornaremos em até 2 dias úteis.")
 (:institutions-field-name . "Nome da instituição")
 (:institutions-field-name-placeholder . "Universidade de Helsinque")
 (:institutions-field-contact-name . "Nome do contato")
 (:institutions-field-contact-name-placeholder . "Seu nome")
 (:institutions-field-contact-email . "Email de contato")
 (:institutions-field-contact-email-placeholder . "voce@universidade.edu")
 (:institutions-field-domains . "Domínios de email")
 (:institutions-field-domains-placeholder . "universidade.edu, cs.universidade.edu")
 (:institutions-field-domains-help . "Lista de domínios de email da sua instituição separada por vírgulas")
 (:institutions-field-notes . "Informações adicionais")
 (:institutions-field-notes-placeholder . "Número estimado de estudantes, ciclo de faturamento preferido, quaisquer requisitos especiais...")
 (:institutions-submit . "Enviar solicitação")
 (:institutions-success-title . "Obrigado - Hiisi para escolas")
 (:institutions-success-heading . "Obrigado!")
 (:institutions-success-body . "Recebemos sua solicitação de licença institucional. Nossa equipe vai analisar e entrar em contato em até 2 dias úteis.")
 (:institutions-success-back . "Voltar para a página inicial")

 ;; Footer
 (:footer-privacy . "Política de Privacidade")
 (:footer-terms . "Termos de Serviço")
 (:footer-contact . "Contato")

 ;; Early software notice
 (:early-software-notice . "Hiisi está em desenvolvimento inicial. Encontrou um bug ou tem uma sugestão?")
 (:early-software-contact . "Contacte-nos em")

 ;; Privacy Policy
 (:privacy-title . "Privacy Policy")
 (:privacy-updated . "Last updated: January 2026")
 (:privacy-who-title . "Who We Are")
 (:privacy-who-body . "Hiisi is operated by Lambda Symbolics OÜ, a company registered in Estonia. As an Estonian company, we comply with the European Union's General Data Protection Regulation (GDPR).")
 (:privacy-collect-title . "Data We Collect")
 (:privacy-collect-intro . "We collect the following information when you use Hiisi:")
 (:privacy-collect-account-key . "Account information: ")
 (:privacy-collect-account-val . "Email address, display name, and a securely hashed password.")
 (:privacy-collect-learning-key . "Learning data: ")
 (:privacy-collect-learning-val . "Your translations, saved flashcards, and review history.")
 (:privacy-collect-usage-key . "Usage data: ")
 (:privacy-collect-usage-val . "Basic server logs for security and debugging purposes.")
 (:privacy-use-title . "How We Use Your Data")
 (:privacy-use-auth-key . "Authentication: ")
 (:privacy-use-auth-val . "To verify your identity and secure your account.")
 (:privacy-use-service-key . "Service delivery: ")
 (:privacy-use-service-val . "To provide translations and manage your flashcard collection.")
 (:privacy-use-ai-key . "AI translations: ")
 (:privacy-use-ai-val . "Your translation requests are sent to Anthropic's Claude API to generate responses. See Anthropic's privacy policy for how they handle this data.")
 (:privacy-third-title . "Third-Party Services")
 (:privacy-third-intro . "We use the following third-party services:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "For AI-powered translations.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "For sending account activation and transactional emails.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "For subscription payment processing.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "We use only essential cookies:")
 (:privacy-cookies-auth-key . "Authentication token: ")
 (:privacy-cookies-auth-val . "A secure, HTTP-only cookie to keep you logged in.")
 (:privacy-cookies-lang-key . "Language preference: ")
 (:privacy-cookies-lang-val . "To remember your preferred UI language.")
 (:privacy-retention-title . "Data Retention")
 (:privacy-retention-body . "Your data is stored as long as you maintain an account. When you request deletion, your account is scheduled for deletion in 14 days.")
 (:privacy-rights-title . "Your Rights (GDPR)")
 (:privacy-rights-intro . "Under GDPR, you have the right to:")
 (:privacy-rights-access . "Access your personal data")
 (:privacy-rights-export . "Export your data (available at /app/api/export)")
 (:privacy-rights-correct . "Request correction of inaccurate data")
 (:privacy-rights-delete . "Request deletion of your account and data")
 (:privacy-rights-object . "Object to processing of your data")
 (:privacy-rights-contact . "To exercise these rights, contact us at")
 (:privacy-contact-title . "Contact")
 (:privacy-contact-intro . "For privacy-related inquiries:")
 (:privacy-contact-email-label . "Email: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Estonia")

 ;; Terms of Service
 (:terms-title . "Terms of Service")
 (:terms-updated . "Last updated: January 2026")
 (:terms-1-title . "1. Service Description")
 (:terms-1-body . "Hiisi is a language learning application that provides AI-powered translations with grammatical explanations and spaced repetition flashcards. The service is operated by Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Account Registration")
 (:terms-2-body . "To use Hiisi, you must create an account with a valid email address. You are responsible for maintaining the security of your account credentials.")
 (:terms-3-title . "3. Subscription and Payments")
 (:terms-3-body . "Hiisi offers paid subscription plans (monthly and annual). Subscriptions are processed through Polar.sh.")
 (:terms-3-list-1 . "Subscriptions auto-renew unless cancelled before the renewal date.")
 (:terms-3-list-2 . "Refunds are provided in accordance with applicable consumer protection laws.")
 (:terms-3-list-3 . "Non-payment results in loss of access to premium features.")
 (:terms-4-title . "4. Acceptable Use")
 (:terms-4-intro . "You agree not to:")
 (:terms-4-list-1 . "Use the service for any illegal purpose")
 (:terms-4-list-2 . "Attempt to circumvent usage limits or security measures")
 (:terms-4-list-3 . "Share your account credentials with others")
 (:terms-4-list-4 . "Use automated tools to access the service in a way that degrades performance for others")
 (:terms-5-title . "5. Content and Intellectual Property")
 (:terms-5-body-1 . "Translations generated by Hiisi are created using AI and may not be unique. You may use your translations and flashcards for any personal purpose, but you do not hold exclusive authorship rights over AI-generated content.")
 (:terms-5-body-2 . "The Hiisi application, branding, and original content remain the property of Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Service Availability")
 (:terms-6-intro . "Hiisi is provided on an \"as-is\" basis. We do not guarantee:")
 (:terms-6-list-1 . "Uninterrupted or error-free service")
 (:terms-6-list-2 . "Accuracy of AI-generated translations")
 (:terms-6-list-3 . "Availability of specific features")
 (:terms-6-body . "We may modify or discontinue features at any time.")
 (:terms-7-title . "7. Limitation of Liability")
 (:terms-7-body-1 . "To the maximum extent permitted by law, Lambda Symbolics OÜ shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of Hiisi.")
 (:terms-7-body-2 . "Our total liability shall not exceed the amount you paid for the service in the 12 months preceding the claim.")
 (:terms-8-title . "8. Account Termination")
 (:terms-8-body-1 . "We may suspend or terminate your account if you violate these terms. You may request account deletion at any time through the application.")
 (:terms-8-body-2 . "Upon deletion request, your account is scheduled for deletion in 14 days.")
 (:terms-9-title . "9. Changes to Terms")
 (:terms-9-body . "We may update these terms from time to time. Continued use of Hiisi after changes constitutes acceptance of the new terms.")
 (:terms-10-title . "10. Governing Law")
 (:terms-10-body . "These terms are governed by the laws of Estonia. Any disputes shall be resolved in the courts of Estonia.")
 (:terms-contact-title . "Contact")
 (:terms-contact-intro . "For questions about these terms:")
 (:terms-contact-email-label . "Email: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Estonia")



 ;; Decks
 (:decks-title . "Baralhos")
 (:decks-subtitle . "Crie baralhos personalizados e partilhe-os com outros.")
 (:decks-create-title . "Criar baralho")
 (:decks-name-placeholder . "Nome do baralho")
 (:decks-desc-placeholder . "Descrição")
 (:decks-create-btn . "Criar baralho")
 (:decks-your-title . "Os seus baralhos")
 (:decks-col-name . "Nome")
 (:decks-col-desc . "Descrição")
 (:decks-col-updated . "Atualizado")
 (:decks-col-actions . "Ações")
 (:decks-no-decks . "Ainda não há baralhos.")
 (:decks-open-btn . "Abrir")
 (:decks-no-desc . "Sem descrição.")
 (:decks-share-title . "Link de partilha")
 (:decks-share-info . "Qualquer pessoa com este link pode importar o baralho:")
 (:decks-share-copy . "Copiar link")
 (:decks-share-copied . "Copiado")
 (:decks-add-from-flashcards-title . "Adicionar traduções")
 (:decks-add-from-flashcards-info . "Escolha um cartão para adicionar a tradução a este baralho.")
 (:decks-open-flashcards . "Adicionar a partir de cartões")
 (:decks-filter-from . "Idioma de origem")
 (:decks-filter-to . "Idioma de destino")
 (:decks-filter-any . "Qualquer idioma")
 (:decks-filter-include-assigned . "Incluir cartões que já estão num baralho")
 (:decks-flashcards-col-from . "De")
 (:decks-flashcards-col-to . "Para")
 (:decks-flashcards-add . "Adicionar")
 (:decks-flashcards-added . "Adicionado")
 (:decks-flashcards-in-deck . "Noutro baralho")
 (:decks-flashcards-empty . "Nenhum cartão corresponde a estes filtros.")
 (:decks-add-trans-title . "Adicionar tradução")
 (:decks-trans-id-placeholder . "ID da tradução")
 (:decks-add-trans-btn . "Adicionar tradução")
 (:decks-items-title . "Conteúdo do baralho")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Tradução")
 (:decks-col-lang . "Língua destino")
 (:decks-no-items . "Ainda não há itens.")
 (:decks-share-page-title . "Partilhar baralho")
 (:decks-share-preview . "Pré-visualizar e importar este baralho.")
 (:decks-import-title . "Importar")
 (:decks-import-btn . "Importar baralho")

 ;; Flashcards management page
 (:flashcards-title . "Meus cartões")
 (:flashcards-subtitle . "Todos os seus cartões guardados num só lugar. Pesquise, organize e gira.")
 (:flashcards-search-placeholder . "Pesquisar cartões...")
 (:flashcards-col-original . "Original")
 (:flashcards-col-translated . "Tradução")
 (:flashcards-col-lang . "Idiomas")
 (:flashcards-no-cards . "Ainda não há cartões. Comece a traduzir para criar alguns!")

 ;; API Errors (EN fallback)
 (:api-error-missing-text . "Missing text to translate.")
 (:api-error-invalid-translation-id . "Invalid translation ID.")
 (:api-error-translation-not-found . "The translation you tried to save no longer exists.")
 (:api-error-invalid-bookmark-id . "Invalid bookmark ID")
 (:api-error-bookmark-not-found . "Bookmark not found")
 (:api-error-forbidden . "Forbidden")
 (:api-error-failed-delete-bookmark . "Failed to delete bookmark")
 (:api-error-invalid-flashcard-id . "Invalid flashcard ID")
 (:api-error-missing-deck-id . "Missing deck_id")
 (:api-error-flashcard-not-found . "Flashcard not found")
 (:api-error-deck-not-found . "Deck not found")
 (:api-error-deck-name-required . "Deck name is required")
 (:api-error-session-expired . "Your review session has expired. Please start a new session.")
 (:api-error-invalid-card-id . "Invalid card ID.")
 (:api-error-invalid-rating . "Invalid rating.")
 (:api-error-rating-range . "Rating must be between 0 and 5.")
 (:api-error-card-not-found . "Card not found.")
 (:api-error-permission-denied . "You don't have permission to review this card.")
 (:api-error-unknown-source-lang . "Unknown source language.")
 (:api-error-unknown-target-lang . "Unknown target language.")
 (:api-error-failed-add-to-deck . "Failed to add to deck")

 ;; API Success messages
 (:api-success-added . "Added!")
 (:api-success-added-simple . "Added")

 ;; API Stats
 (:api-stats-due . "~A due")
 (:api-stats-total . "~A total")

 ;; Time units
 (:api-time-day . "day")
 (:api-time-days . "days")
 (:api-time-day-left . "day left")
 (:api-time-days-left . "days left")

 ;; Subscription status
 (:api-subscription-active . "Active")
 (:api-subscription-inactive . "Inactive")
 (:api-subscription-subscribe-hint . "Subscribe to unlock translations")

 ;; Generic status
 (:status-bad-request . "Bad Request")
 (:status-not-found . "Not Found")
 (:status-forbidden . "Forbidden")

)
