;;; Portuguese translations
;;; This file follows the structure of en.lisp (authoritative source)

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Português")
 (:lang-flag . "🇵🇹")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Escolha seu idioma")
 (:lang-modal-subtitle . "Selecione seu idioma preferido para a interface:")

 ;; Navigation
 (:nav-translate . "Traduzir")
 (:nav-review . "Revisar")
 (:nav-flashcards . "Meus cartões")
 (:nav-dashboard . "Painel")
 (:nav-decks . "Decks")
 (:nav-logout . "Sair")
 (:nav-home . "Início")
 (:nav-pricing . "Preços")
 (:nav-export-data . "Exportar Dados")

 ;; App title and branding
 (:app-title . "Hiisi - Aprendizado de idiomas")
 (:app-tagline . "Aprenda idiomas através de traduções")

 ;; Landing page
 (:landing-hero-title . "Domine Qualquer Idioma")
 (:landing-hero-subtitle . "Traduza qualquer coisa. Gere automaticamente flashcards que ensinam por que funciona assim.")
 (:landing-cta . "Começar a Aprender")
 (:landing-learn-more . "Saiba Mais")
 (:landing-how-it-works . "Como Funciona")
 (:landing-feature-1-title . "Flashcards Automáticos")
 (:landing-feature-1-desc . "Cada tradução gera automaticamente flashcards com análise gramatical. Sem criação manual de cartões.")
 (:landing-feature-2-title . "Repetição Espaçada")
 (:landing-feature-2-desc . "O algoritmo SM-2 agenda revisões em intervalos ideais. Aprenda eficientemente, lembre-se permanentemente.")
 (:landing-feature-3-title . "Ensino de Gramática")
 (:landing-feature-3-desc . "Cada tradução explica gramática, raízes das palavras e estrutura das frases. Entenda o porquê, não apenas o quê.")
 (:landing-free-trial . "7 dias de teste grátis.")
 (:landing-start-trial . "Iniciar Teste Grátis")
 (:landing-best-value . "Melhor Valor")
 (:landing-cta-title . "Pronto para aprender idiomas através da gramática, não da memorização?")
 (:landing-cta-subtitle . "Cada tradução se torna uma oportunidade de aprendizado. Cada flashcard ensina o porquê.")
 (:landing-signup-free . "Cadastre-se Grátis")

 ;; Auth pages
 (:auth-register . "Registrar")
 (:auth-login . "Entrar")
 (:auth-logout . "Sair")
 (:auth-email . "Email")
 (:auth-password . "Senha")
 (:auth-password-again . "Confirmar Senha")
 (:auth-display-name . "Nome de Exibição")
 (:auth-register-title . "Registre-se no Hiisi")
 (:auth-register-subtitle . "Criar uma nova conta")
 (:auth-login-title . "Entrar no Hiisi")
 (:auth-login-subtitle . "Digite suas credenciais")
 (:auth-login-invalid-credentials . "E-mail ou senha invalidos.")
 (:auth-login-rate-limited . "Muitas tentativas de login. Aguarde alguns minutos e tente novamente.")
 (:auth-forgot-password . "Esqueceu a senha?")
 (:auth-no-account . "Não tem uma conta?")
 (:auth-have-account . "Já tem uma conta?")
 (:auth-google . "Google")
 (:auth-account-created . "Conta criada!")
 (:auth-check-email . "Verifique seu email para o link de ativação.")
 (:auth-redirect-login . "Redirecionando para login em")
 (:auth-seconds . "segundos...")
 (:auth-go-now . "Ir agora")
 (:auth-not-activated . "Conta não ativada")
 (:auth-activate-title . "Ative sua conta!")
 (:auth-activated . "Conta ativada!")
 (:auth-activated-message . "Sua conta foi ativada. Agora você pode usar o Hiisi.")
 (:auth-redirecting . "Redirecionando em")
 (:auth-go-to-app . "Ir para o app")
 (:auth-resend-title . "Reenviar email de ativação")
 (:auth-resend-subtitle . "Digite seu email para receber um novo link de ativação.")
 (:auth-resend-button . "Reenviar email de ativação")
 (:auth-resend-success . "Email de ativação enviado!")
 (:auth-resend-success-detail . "Verifique sua caixa de entrada para o novo link de ativação.")
 (:auth-resend-rate-limited . "Por favor aguarde alguns minutos antes de solicitar outro email de ativação.")
 (:auth-resend-cooldown . "Você pode solicitar outro email em ~a segundos.")
 (:auth-back-to-login . "Voltar ao login")
 (:auth-forgot-password-title . "Esqueci a senha")
 (:auth-forgot-password-subtitle . "Digite seu email e enviaremos um link para redefinir sua senha.")
 (:auth-send-reset-link . "Enviar link de redefinição")
 (:auth-reset-email-sent . "Link enviado!")
 (:auth-reset-email-sent-detail . "Se uma conta existe com esse email, você receberá um link de redefinição de senha em breve.")
 (:auth-reset-rate-limited . "Por favor aguarde alguns minutos antes de solicitar outra redefinição de senha.")
 (:auth-reset-invalid-token . "Este link de redefinição é inválido ou expirou.")
 (:auth-reset-password-title . "Redefinir senha")
 (:auth-reset-password-subtitle . "Digite sua nova senha abaixo.")
 (:auth-new-password . "Nova senha")
 (:auth-confirm-new-password . "Confirmar nova senha")
 (:auth-reset-password . "Redefinir senha")
 (:auth-password-changed . "Senha alterada!")
 (:auth-password-changed-detail . "Sua senha foi alterada com sucesso. Agora você pode entrar com sua nova senha.")
 (:auth-change-password-title . "Alterar senha")
 (:auth-change-password-subtitle . "Atualize a senha da sua conta.")
 (:auth-current-password . "Senha atual")
 (:auth-change-password . "Alterar senha")
 (:auth-back-to-app . "Voltar para o app")
 (:auth-password-updated . "Senha atualizada!")
 (:auth-password-updated-detail . "Sua senha foi atualizada com sucesso.")

 ;; Translation page
 (:translate-title . "Traduzir")
 (:translate-input-label . "Texto para traduzir")
 (:translate-input-placeholder . "Digite o texto para traduzir...")
 (:translate-from . "De:")
 (:translate-to . "Para:")
 (:translate-submit . "Traduzir")
 (:translate-save . "Salvar em Flashcards")
 (:translate-saved . "Salvo!")
 (:translate-like . "Gostei")
 (:translate-dislike . "Não Gostei")
 (:translate-char-limit . "caracteres restantes")
 (:translate-auto-detect . "Qualquer (Detectar automaticamente)")
 (:translate-empty-state . "Digite o texto acima e clique em Traduzir para ver o resultado com análise gramatical")
 (:translate-select-deck-placeholder . "Selecionar baralho (opcional)")
 (:translate-new-deck . "Novo baralho")
 (:translate-add-to-deck . "Adicionar ao baralho")
 (:translate-bookmark . "Salvar")
 (:translate-bookmarked . "Salvo")
 (:translate-retry . "Tentar novamente")
 (:translate-like-tooltip . "Boa tradução")
 (:translate-dislike-tooltip . "Má tradução - solicitar uma nova")
 (:translate-dislike-confirm . "Isso gerará uma nova tradução. Continuar?")
 (:translate-liked . "Gostei!")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Destino")
 (:translate-deck-create-title . "Criar novo baralho")
 (:translate-deck-name-label . "Nome do baralho")
 (:translate-deck-name-placeholder . "ex.: Fundamentos de finlandês")
 (:translate-deck-description-label . "Descrição (opcional)")
 (:translate-deck-cancel . "Cancelar")
 (:translate-deck-create . "Criar")
 (:translate-rate-label . "Avaliar tradução")
 (:flashcards-delete-confirm . "Tem certeza de que deseja excluir este cartão?")
 (:flashcards-deck-search-placeholder . "Pesquisar baralhos...")
 (:flashcards-no-decks . "Ainda não há baralhos. Crie um primeiro!")
 (:flashcards-deck-cancel . "Cancelar")
 (:flashcards-recollection-tooltip . "Recordação: ~A")
 (:flashcards-recollection-poor . "Fraca")
 (:flashcards-recollection-fair . "Razoável")
 (:flashcards-recollection-normal . "Normal")
 (:flashcards-recollection-strong . "Forte")
 (:flashcards-recollection-very-strong . "Muito forte")

 ;; Flashcard review
 (:review-title . "Revisar")
 (:review-session-title . "Sessão de Revisão")
 (:review-session-subtitle . "Pratique seus flashcards salvos")
 (:review-selector-title . "Escolha o que revisar")
 (:review-selector-subtitle . "Selecione um baralho ou par de idiomas para focar sua sessão de revisão.")
 (:review-by-deck . "Revisar por baralho")
 (:review-by-language-pair . "Revisar por par de idiomas")
 (:review-all-cards . "Revisar todos os cartões")

 (:review-start . "Iniciar Revisão")
 (:review-no-cards . "Nenhum Cartão para Revisar")
 (:review-no-cards-desc . "Você não tem nenhum flashcard pendente para revisão agora.")
 (:review-no-cards-hint . "Traduza algum texto e clique em \"Salvar em Flashcards\" para construir seu baralho!")
 (:review-start-translating . "Começar a Traduzir")
 (:review-show-answer . "Mostrar Resposta")
 (:review-click-reveal . "Clique para revelar a resposta")
 (:review-grammar-breakdown . "Análise Gramatical")
 (:review-how-well . "Você se lembrou?")
 (:review-again . "Não")
 (:review-hard . "Com dificuldade")
 (:review-good . "Sim")
 (:review-easy . "Facilmente")
 (:review-progress . "Cartão ~a de ~a")
 (:review-complete . "Sessão Completa!")
 (:review-complete-msg . "Você revisou ~a cartões")
 (:review-correct . "Corretos")
 (:review-accuracy . "Precisão")
 (:review-again-btn . "Revisar Novamente")
 (:review-translate-more . "Traduzir Mais")
 (:review-streak . "dias de sequência")

 ;; Dashboard
 (:dashboard-title . "Painel")
 (:dashboard-cards-due . "Cartões Pendentes")
 (:dashboard-total-cards . "Total de Cartões")
 (:dashboard-subscription . "Assinatura")
 (:dashboard-subscribed-until . "Assinado até")
 (:dashboard-not-subscribed . "Não assinado")
 (:dashboard-recent . "Traduções Recentes")
 (:dashboard-no-translations . "Nenhuma tradução ainda")
 (:dashboard-streak . "Sequência de Revisão")
 (:dashboard-days . "dias")
 (:dashboard-all-caught-up . "Tudo em dia!")
 (:dashboard-all-caught-up-hint . "Traduza mais para ampliar a sua coleção.")
 (:dashboard-quick-actions . "Ações Rápidas")
 (:dashboard-getting-started . "Primeiros Passos")
 (:dashboard-tip-1 . "Traduza textos que você quer aprender")
 (:dashboard-tip-2 . "Clique em \"Salvar em Flashcards\" nas traduções que você quer lembrar")
 (:dashboard-tip-3 . "Revise seus flashcards regularmente - a repetição espaçada ajuda você a lembrar a longo prazo")
 (:dashboard-tip-4 . "Avalie honestamente - isso ajuda o algoritmo a agendar suas revisões de forma ideal")

 ;; Account
 (:account-title . "Conta")
 (:account-subtitle . "Gerencie as configurações da sua conta e o agendamento de exclusão.")
 (:account-deletion-title . "Exclusão da conta")
 (:account-deletion-scheduled . "Sua conta está programada para exclusão em ~A.")
 (:account-deletion-cancel-hint . "Você pode cancelar antes dessa data para manter sua conta.")
 (:account-deletion-cancel . "Cancelar exclusão")
 (:account-deletion-request . "Você pode solicitar a exclusão da conta a qualquer momento. A exclusão é programada para 14 dias após a confirmação. Se você mudar de ideia após a exclusão, entre em contato com o suporte.")
 (:account-deletion-confirm . "Agendar a exclusão da conta para 14 dias a partir de hoje?")
 (:account-deletion-schedule . "Agendar exclusão")
 (:account-reminders-title . "Lembretes por e-mail")
 (:account-reminders-subtitle . "Controle lembretes de revisão e continuação para esta conta.")
 (:account-reminders-opt-out . "Desativar lembretes de revisão e continuação")
 (:account-reminders-save . "Salvar preferências")

 ;; Subscription
 (:subscribe-title . "Preços Simples")
 (:subscribe-choose-plan . "Escolha Seu Plano")
 (:subscribe-start-today . "Comece a aprender hoje com 7 dias de teste grátis")
 (:subscribe-monthly . "Mensal")
 (:subscribe-annual . "Anual")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-per-month . "/mês")
 (:subscribe-per-year . "/ano")
 (:subscribe-monthly-desc . "600 traduções por mês")
 (:subscribe-unlimited-flashcards . "Flashcards ilimitados")
 (:subscribe-grammar-explanations . "Explicações gramaticais")
 (:subscribe-spaced-repetition . "Repetição espaçada")
 (:subscribe-annual-desc . "Economize €20 — dois meses grátis!")
 (:subscribe-cta . "Assinar")
 (:subscribe-success . "Assinatura Bem-sucedida!")
 (:subscribe-manage . "Gerenciar Assinatura")
 (:subscribe-activated . "Assinatura Ativada!")
 (:subscribe-thank-you . "Obrigado por assinar. Sua conta agora está ativa.")
 (:subscribe-start-learning . "Começar a Aprender")
 (:subscribe-management . "Gerenciamento de Assinatura")
 (:subscribe-active . "Assinatura Ativa")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Ativa")
 (:subscribe-days-remaining . "Dias restantes:")
 (:subscribe-renews-on . "Renova em:")
 (:subscribe-no-subscription . "Nenhuma Assinatura Ativa")
 (:subscribe-access-features . "Assine para acessar todos os recursos.")
 (:subscribe-view-plans . "Ver Planos")
 (:subscribe-faq-title . "Perguntas Frequentes")
 (:subscribe-faq-trial-q . "O que acontece após o teste grátis?")
 (:subscribe-faq-trial-a . "Após os 7 dias de teste grátis, você será cobrado pelo plano selecionado. Você pode cancelar a qualquer momento antes do fim do teste.")
 (:subscribe-faq-cancel-q . "Posso cancelar a qualquer momento?")
 (:subscribe-faq-cancel-a . "Sim! Você pode cancelar sua assinatura a qualquer momento. Você manterá o acesso até o final do seu período de cobrança.")
 (:subscribe-faq-payment-q . "Quais métodos de pagamento vocês aceitam?")
 (:subscribe-faq-payment-a . "Aceitamos todos os principais cartões de crédito e débito através do nosso parceiro de pagamentos Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")

 ;; Errors and status
 (:error-generic . "Algo deu errado")
 (:error-not-found . "Página não encontrada")
 (:error-unauthorized . "Faça login para continuar")
 (:error-subscription-required . "Assinatura necessária")
 (:error-text-too-long . "O texto é muito longo. O comprimento máximo da tradução é de 120 caracteres.")
 (:error-input-too-long . "Entrada Muito Longa")
 (:error-unknown-source-lang . "O idioma de origem selecionado não é suportado.")
 (:error-unknown-target-lang . "O idioma de destino selecionado não é suportado.")
 (:error-unknown-language . "Idioma Desconhecido")
 (:error-translation-unavailable . "O serviço de tradução está temporariamente indisponível. Por favor, tente novamente em um momento.")
 (:error-translation-failed . "Tradução Falhou")
 (:error-translation-retry . "Não foi possível gerar uma tradução após várias tentativas. Por favor, tente reformular seu texto.")
 (:error-quota-exceeded . "Limite de traduções atingido")
 (:error-quota-exceeded-detail . "Você usou todas as suas traduções deste mês. Sua cota é redefinida automaticamente todo mês.")
 (:quota-warning . "Traduções restantes: ~A")
 (:quota-low-warning . "Apenas ~A traduções restantes. Considere comprar mais.")
 (:top-up-button . "Comprar mais traduções")
 (:top-up-success . "Recarga bem-sucedida! Agora você tem ~A traduções adicionais.")
 (:top-up-price . "€5")
 (:top-up-amount . "300 traduções")
 (:loading . "Carregando...")
 (:empty-state . "Nada aqui ainda")

 ;; Institutions
 (:institutions-page-title . "Hiisi para escolas - licenças institucionais")
 (:institutions-hero-title . "Hiisi para escolas")
 (:institutions-hero-subtitle . "Capacite seus estudantes com aprendizagem de idiomas com IA")
 (:institutions-section-title . "Licenças institucionais")
 (:institutions-section-body . "Oferecemos licenças em volume para escolas, universidades e instituições de idiomas. Estudantes com endereços de email do seu domínio recebem acesso completo automaticamente.")
 (:institutions-benefit-1 . "Matrícula automática para estudantes com email institucional")
 (:institutions-benefit-2 . "Sem contas individuais de estudantes para gerenciar")
 (:institutions-benefit-3 . "Opções de faturamento flexíveis")
 (:institutions-benefit-4 . "Suporte dedicado para educadores")
 (:institutions-request-title . "Solicitar uma licença")
 (:institutions-request-subtitle . "Preencha o formulário abaixo e retornaremos em até 2 dias úteis.")
 (:institutions-field-name . "Nome da instituição")
 (:institutions-field-name-placeholder . "Universidade de Helsinque")
 (:institutions-field-contact-name . "Nome do contato")
 (:institutions-field-contact-name-placeholder . "Seu nome")
 (:institutions-field-contact-email . "Email de contato")
 (:institutions-field-contact-email-placeholder . "voce@universidade.edu")
 (:institutions-field-domains . "Domínios de email")
 (:institutions-field-domains-placeholder . "universidade.edu, cs.universidade.edu")
 (:institutions-field-domains-help . "Lista de domínios de email da sua instituição separada por vírgulas")
 (:institutions-field-notes . "Informações adicionais")
 (:institutions-field-notes-placeholder . "Número estimado de estudantes, ciclo de faturamento preferido, quaisquer requisitos especiais...")
 (:institutions-submit . "Enviar solicitação")
 (:institutions-success-title . "Obrigado - Hiisi para escolas")
 (:institutions-success-heading . "Obrigado!")
 (:institutions-success-body . "Recebemos sua solicitação de licença institucional. Nossa equipe vai analisar e entrar em contato em até 2 dias úteis.")
 (:institutions-success-back . "Voltar para a página inicial")

 ;; Footer
 (:footer-privacy . "Política de Privacidade")
 (:footer-terms . "Termos de Serviço")
 (:footer-contact . "Contato")

 ;; Early software notice
 (:early-software-notice . "Hiisi está em desenvolvimento inicial. Encontrou um bug ou tem uma sugestão?")
 (:early-software-contact . "Contacte-nos em")

 ;; Política de privacidade
 (:privacy-title . "Política de privacidade")
 (:privacy-updated . "Última atualização: janeiro de 2026")
 (:privacy-who-title . "Quem somos")
 (:privacy-who-body . "A Hiisi é operada pela Lambda Symbolics OÜ, uma empresa registada na Estónia. Como empresa estónia, cumprimos o Regulamento Geral sobre a Proteção de Dados (GDPR) da União Europeia.")
 (:privacy-collect-title . "Dados que recolhemos")
 (:privacy-collect-intro . "Quando utiliza a Hiisi, recolhemos as seguintes informações:")
 (:privacy-collect-account-key . "Informações da conta: ")
 (:privacy-collect-account-val . "Endereço de e-mail, nome de apresentação e palavra-passe guardada com hash seguro.")
 (:privacy-collect-learning-key . "Dados de aprendizagem: ")
 (:privacy-collect-learning-val . "As suas traduções, cartões guardados e histórico de revisão.")
 (:privacy-collect-usage-key . "Dados de utilização: ")
 (:privacy-collect-usage-val . "Registos básicos do servidor para segurança e depuração.")
 (:privacy-use-title . "Como usamos os seus dados")
 (:privacy-use-auth-key . "Autenticação: ")
 (:privacy-use-auth-val . "Para verificar a sua identidade e proteger a sua conta.")
 (:privacy-use-service-key . "Prestação do serviço: ")
 (:privacy-use-service-val . "Para fornecer traduções e gerir a sua coleção de cartões.")
 (:privacy-use-ai-key . "Traduções com IA: ")
 (:privacy-use-ai-val . "Os seus pedidos de tradução são enviados para a API Claude da Anthropic para gerar respostas. Consulte a política de privacidade da Anthropic para saber como tratam esses dados.")
 (:privacy-third-title . "Serviços de terceiros")
 (:privacy-third-intro . "Usamos os seguintes serviços de terceiros:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "Para traduções com IA.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "Para envio de e-mails de ativação de conta e e-mails transacionais.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Para processamento de pagamentos de subscrição.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "Usamos apenas cookies essenciais:")
 (:privacy-cookies-auth-key . "Token de autenticação: ")
 (:privacy-cookies-auth-val . "Um cookie seguro, HTTP-only, para manter a sua sessão iniciada.")
 (:privacy-cookies-lang-key . "Preferência de idioma: ")
 (:privacy-cookies-lang-val . "Para memorizar o idioma preferido da interface.")
 (:privacy-retention-title . "Retenção de dados")
 (:privacy-retention-body . "Os seus dados são guardados enquanto mantiver uma conta. Quando pede eliminação, a sua conta é agendada para ser eliminada em 14 dias.")
 (:privacy-rights-title . "Os seus direitos (GDPR)")
 (:privacy-rights-intro . "Ao abrigo do GDPR, tem direito a:")
 (:privacy-rights-access . "Aceder aos seus dados pessoais")
 (:privacy-rights-export . "Exportar os seus dados (disponível em /app/api/export)")
 (:privacy-rights-correct . "Pedir a correção de dados incorretos")
 (:privacy-rights-delete . "Pedir a eliminação da sua conta e dos seus dados")
 (:privacy-rights-object . "Opor-se ao tratamento dos seus dados")
 (:privacy-rights-contact . "Para exercer estes direitos, contacte-nos em")
 (:privacy-contact-title . "Contacto")
 (:privacy-contact-intro . "Para questões de privacidade:")
 (:privacy-contact-email-label . "E-mail: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Estónia")

 ;; Termos de serviço
 (:terms-title . "Termos de serviço")
 (:terms-updated . "Última atualização: janeiro de 2026")
 (:terms-1-title . "1. Descrição do serviço")
 (:terms-1-body . "A Hiisi é uma aplicação de aprendizagem de línguas que fornece traduções com IA, explicações gramaticais e cartões de repetição distribuída. O serviço é operado pela Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Registo de conta")
 (:terms-2-body . "Para usar a Hiisi, tem de criar uma conta com um endereço de e-mail válido. É responsável por manter a segurança das credenciais da sua conta.")
 (:terms-3-title . "3. Subscrição e pagamentos")
 (:terms-3-body . "A Hiisi oferece planos pagos de subscrição (mensal e anual). As subscrições são processadas através da Polar.sh.")
 (:terms-3-list-1 . "As subscrições renovam automaticamente, salvo cancelamento antes da data de renovação.")
 (:terms-3-list-2 . "Os reembolsos são concedidos de acordo com a legislação aplicável de proteção do consumidor.")
 (:terms-3-list-3 . "A falta de pagamento resulta na perda de acesso a funcionalidades premium.")
 (:terms-4-title . "4. Utilização aceitável")
 (:terms-4-intro . "Concorda em não:")
 (:terms-4-list-1 . "Usar o serviço para qualquer finalidade ilegal")
 (:terms-4-list-2 . "Tentar contornar limites de utilização ou medidas de segurança")
 (:terms-4-list-3 . "Partilhar as credenciais da sua conta com terceiros")
 (:terms-4-list-4 . "Usar ferramentas automatizadas de forma a degradar o desempenho para outras pessoas")
 (:terms-5-title . "5. Conteúdo e propriedade intelectual")
 (:terms-5-body-1 . "As traduções geradas pela Hiisi são criadas com IA e podem não ser únicas. Pode usar as suas traduções e cartões para fins pessoais, mas não detém direitos exclusivos de autoria sobre conteúdo gerado por IA.")
 (:terms-5-body-2 . "A aplicação Hiisi, a marca e o conteúdo original continuam a ser propriedade da Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Disponibilidade do serviço")
 (:terms-6-intro . "A Hiisi é fornecida tal como está. Não garantimos:")
 (:terms-6-list-1 . "Serviço ininterrupto ou sem erros")
 (:terms-6-list-2 . "Precisão das traduções geradas por IA")
 (:terms-6-list-3 . "Disponibilidade de funcionalidades específicas")
 (:terms-6-body . "Podemos modificar ou descontinuar funcionalidades a qualquer momento.")
 (:terms-7-title . "7. Limitação de responsabilidade")
 (:terms-7-body-1 . "Na máxima medida permitida por lei, a Lambda Symbolics OÜ não será responsável por quaisquer danos indiretos, incidentais, especiais ou consequentes resultantes da sua utilização da Hiisi.")
 (:terms-7-body-2 . "A nossa responsabilidade total não excederá o montante pago por si pelo serviço nos 12 meses anteriores à reclamação.")
 (:terms-8-title . "8. Encerramento de conta")
 (:terms-8-body-1 . "Podemos suspender ou terminar a sua conta se violar estes termos. Pode pedir a eliminação da conta a qualquer momento na aplicação.")
 (:terms-8-body-2 . "Após pedido de eliminação, a sua conta é agendada para ser eliminada em 14 dias.")
 (:terms-9-title . "9. Alterações aos termos")
 (:terms-9-body . "Podemos atualizar estes termos ocasionalmente. O uso continuado da Hiisi após alterações constitui aceitação dos novos termos.")
 (:terms-10-title . "10. Lei aplicável")
 (:terms-10-body . "Estes termos regem-se pela legislação da Estónia. Quaisquer litígios serão resolvidos nos tribunais da Estónia.")
 (:terms-contact-title . "Contacto")
 (:terms-contact-intro . "Para questões sobre estes termos:")
 (:terms-contact-email-label . "E-mail: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Estónia")



 ;; Decks
 (:decks-title . "Baralhos")
 (:decks-subtitle . "Crie baralhos personalizados e partilhe-os com outros.")
 (:decks-create-title . "Criar baralho")
 (:decks-name-placeholder . "Nome do baralho")
 (:decks-desc-placeholder . "Descrição")
 (:decks-create-btn . "Criar baralho")
 (:decks-edit-title . "Editar baralho")
 (:decks-edit-btn . "Editar baralho")
 (:decks-update-btn . "Guardar alterações")
 (:decks-default-badge . "Automático")
 (:decks-default-description . "Este baralho é gerido automaticamente para este par de línguas.")
 (:decks-default-readonly . "Os baralhos automáticos têm nomes e descrições fixos.")
 (:decks-error-name-required . "O nome do baralho é obrigatório.")
 (:decks-error-name-too-long . "O nome do baralho deve ter no máximo ~A caracteres.")
 (:decks-error-desc-too-long . "A descrição do baralho deve ter no máximo ~A caracteres.")
 (:decks-error-default-readonly . "Os baralhos automáticos não podem ser editados.")
 (:decks-your-title . "Os seus baralhos")
 (:decks-col-name . "Nome")
 (:decks-col-desc . "Descrição")
 (:decks-col-updated . "Atualizado")
 (:decks-col-actions . "Ações")
 (:decks-no-decks . "Ainda não há baralhos.")
 (:decks-open-btn . "Abrir")
 (:decks-no-desc . "Sem descrição.")
 (:decks-share-title . "Link de partilha")
 (:decks-share-info . "Qualquer pessoa com este link pode importar o baralho:")
 (:decks-share-copy . "Copiar link")
 (:decks-share-copied . "Copiado")
 (:decks-add-from-flashcards-title . "Adicionar traduções")
 (:decks-add-from-flashcards-info . "Escolha um cartão para adicionar a tradução a este baralho.")
 (:decks-open-flashcards . "Adicionar a partir de cartões")
 (:decks-filter-from . "Idioma de origem")
 (:decks-filter-to . "Idioma de destino")
 (:decks-filter-any . "Qualquer idioma")
 (:decks-filter-include-assigned . "Incluir cartões que já estão num baralho")
 (:decks-flashcards-col-from . "De")
 (:decks-flashcards-col-to . "Para")
 (:decks-flashcards-add . "Adicionar")
 (:decks-flashcards-added . "Adicionado")
 (:decks-flashcards-in-deck . "Noutro baralho")
 (:decks-flashcards-empty . "Nenhum cartão corresponde a estes filtros.")
 (:decks-add-trans-title . "Adicionar tradução")
 (:decks-trans-id-placeholder . "ID da tradução")
 (:decks-add-trans-btn . "Adicionar tradução")
 (:decks-items-title . "Conteúdo do baralho")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Tradução")
 (:decks-col-lang . "Língua destino")
 (:decks-no-items . "Ainda não há itens.")
 (:decks-share-page-title . "Partilhar baralho")
 (:decks-share-preview . "Pré-visualizar e importar este baralho.")
 (:decks-import-title . "Importar")
 (:decks-import-btn . "Importar baralho")

 ;; Flashcards management page
 (:flashcards-title . "Meus cartões")
 (:flashcards-subtitle . "Todos os seus cartões guardados num só lugar. Pesquise, organize e gira.")
 (:flashcards-search-placeholder . "Pesquisar cartões...")
 (:flashcards-hide-perfected . "Ocultar cartões dominados")
 (:flashcards-col-original . "Original")
 (:flashcards-col-translated . "Tradução")
 (:flashcards-col-lang . "Idiomas")
 (:flashcards-no-cards . "Ainda não há cartões. Comece a traduzir para criar alguns!")

 ;; API errors
 (:api-error-missing-text . "Falta texto para traduzir.")
 (:api-error-invalid-translation-id . "ID de tradução inválido.")
 (:api-error-translation-not-found . "A tradução que tentou guardar já não existe.")
 (:api-error-invalid-bookmark-id . "ID de marcador inválido")
 (:api-error-bookmark-not-found . "Marcador não encontrado")
 (:api-error-forbidden . "Proibido")
 (:api-error-failed-delete-bookmark . "Falha ao eliminar marcador")
 (:api-error-invalid-flashcard-id . "ID de cartão inválido")
 (:api-error-missing-deck-id . "Falta ID do baralho")
 (:api-error-flashcard-not-found . "Cartão não encontrado")
 (:api-error-deck-not-found . "Baralho não encontrado")
 (:api-error-deck-name-required . "O nome do baralho é obrigatório")
 (:api-error-session-expired . "A sua sessão de revisão expirou. Inicie uma nova sessão.")
 (:api-error-invalid-card-id . "ID de cartão inválido.")
 (:api-error-invalid-rating . "Classificação inválida.")
 (:api-error-rating-range . "A classificação deve estar entre 0 e 5.")
 (:api-error-card-not-found . "Cartão não encontrado.")
 (:api-error-permission-denied . "Não tem permissão para rever este cartão.")
 (:api-error-unknown-source-lang . "Idioma de origem desconhecido.")
 (:api-error-unknown-target-lang . "Idioma de destino desconhecido.")
 (:api-error-failed-add-to-deck . "Falha ao adicionar ao baralho")

 ;; API success messages
 (:api-success-added . "Adicionado!")
 (:api-success-added-simple . "Adicionado")

 ;; API stats
 (:api-stats-due . "~A pendentes")
 (:api-stats-total . "~A no total")

 ;; Time units
 (:api-time-day . "dia")
 (:api-time-days . "dias")
 (:api-time-day-left . "dia restante")
 (:api-time-days-left . "dias restantes")

 ;; Subscription status
 (:api-subscription-active . "Ativo")
 (:api-subscription-inactive . "Inativo")
 (:api-subscription-subscribe-hint . "Subscreva para desbloquear traduções")

 ;; Generic status
 (:status-bad-request . "Pedido inválido")
 (:status-not-found . "Não encontrado")
 (:status-forbidden . "Proibido")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Aprenda idiomas de forma abrangente")
 (:landing-hero-subheadline . "Obtenha traduções com análise gramatical completa e construa vocabulário duradouro através de cartões com repetição espaçada.")
 (:landing-hero-trust-line . "7 dias de teste grátis com 100 traduções. Cancele a qualquer momento.")
 (:landing-credibility-languages . "14 idiomas")
 (:landing-credibility-ai . "Análise gramatical incluída")
 (:landing-credibility-origin . "Feito na Estónia")
 (:landing-step-1-title . "Traduza qualquer texto")
 (:landing-step-1-desc . "Insira uma palavra ou frase. Obtenha uma tradução com análise gramatical completa.")
 (:landing-step-2-title . "Guarde como cartões")
 (:landing-step-2-desc . "Guarde as traduções que deseja lembrar. Os cartões são criados automaticamente.")
 (:landing-step-3-title . "Revise e lembre")
 (:landing-step-3-desc . "A repetição espaçada agenda revisões no momento certo para a memória de longo prazo.")
 (:landing-feature-grammar-title . "Compreenda a gramática, não apenas palavras")
 (:landing-feature-grammar-desc . "Cada tradução inclui uma análise gramatical detalhada - formas de palavras, casos e conjugações explicadas no seu idioma.")
 (:landing-feature-srs-title . "Memorização baseada em ciência")
 (:landing-feature-srs-desc . "O algoritmo SM-2 adapta-se ao seu desempenho. Cartões difíceis aparecem com mais frequência. Cartões que domina aparecem menos.")
 (:landing-feature-share-title . "Partilhe baralhos com alunos")
 (:landing-feature-share-desc . "Os professores podem criar baralhos personalizados e partilhá-los com um link. Os alunos importam o baralho e começam a rever imediatamente.")
 (:landing-pricing-trial-note . "Inclui 7 dias de teste grátis")
 (:landing-pricing-monthly-after . "7 dias grátis, depois ~A/mês")
 (:landing-pricing-annual-after . "7 dias grátis, depois ~A/ano")
 (:landing-faq-title . "Perguntas frequentes")
 (:landing-faq-trial-cap-q . "Quantas traduções recebo durante o teste?")
 (:landing-faq-trial-cap-a . "Recebe 100 traduções durante o teste de 7 dias. Após a subscrição, recebe 600 por mês.")
 (:landing-final-cta-title . "Comece a aprender hoje")
 (:landing-final-cta-subtitle . "Junte-se ao Hiisi e comece a construir vocabulário que permanece.")

 ;; Trial status (in-app)
 (:trial-status . "Teste gratuito")
 (:trial-days-remaining . "~A dias restantes")
 (:trial-translations-used . "~A/100 traduções usadas")
 (:trial-upgrade-prompt . "Faça upgrade para continuar a traduzir")
 (:trial-expired . "O seu teste gratuito terminou")
 (:trial-expired-detail . "Subscreva para continuar a aprender com o Hiisi.")
 (:trial-quota-warning . "~A traduções de teste restantes (~A dias). Subscreva por 600/mês.")
 (:trial-quota-exceeded . "Limite de traduções de teste atingido. Subscreva para continuar.")
 (:error-trial-quota-exceeded . "Limite de traduções de teste atingido")
 (:error-trial-quota-detail . "Usou todas as 100 traduções de teste. Subscreva para continuar a aprender.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Criar cartão")
 (:custom-flashcard-edit-title . "Editar cartão")
 (:custom-flashcard-original . "Texto original")
 (:custom-flashcard-translated . "Tradução")
 (:custom-flashcard-lang-from . "Idioma de origem")
 (:custom-flashcard-lang-to . "Idioma de destino")
 (:custom-flashcard-note . "Nota educativa")
 (:custom-flashcard-forms . "Análise gramatical")
 (:custom-flashcard-form-term . "Termo")
 (:custom-flashcard-form-explanation . "Explicação")
 (:custom-flashcard-add-form . "Adicionar termo gramatical")
 (:custom-flashcard-remove-form . "Remover")
 (:custom-flashcard-ai-fill . "Preencher com IA")
 (:custom-flashcard-ai-fill-all . "Preencher tudo com IA")
 (:custom-flashcard-ai-fill-translation . "Traduzir com IA")
 (:custom-flashcard-ai-fill-breakdown . "Gerar análise")
 (:custom-flashcard-ai-fill-note . "Gerar nota")
 (:custom-flashcard-create-btn . "Criar cartão")
 (:custom-flashcard-update-btn . "Guardar alterações")
 (:custom-flashcard-delete-btn . "Eliminar cartão")
 (:custom-flashcard-delete-confirm . "Tem a certeza de que quer eliminar este cartão?")
 (:custom-flashcard-created . "Cartão criado com sucesso")
 (:custom-flashcard-updated . "Cartão atualizado com sucesso")
 (:custom-flashcard-deleted . "Cartão eliminado com sucesso")
 (:custom-flashcard-add-to-deck . "Adicionar ao baralho")
 (:custom-flashcard-not-found . "Cartão não encontrado")
 (:custom-flashcard-not-owner . "Só pode editar cartões que criou")
 (:custom-flashcard-ai-generating . "A gerar com IA...")
 (:custom-flashcard-badge . "Personalizado")

 ;; Relato de problemas
 (:issues-open-button . "Reportar um problema")
 (:issues-modal-title . "Reportar um problema")
 (:issues-modal-subtitle . "Descreva o que deu errado. Vamos incluir automaticamente a página atual.")
 (:issues-title-label . "Título curto")
 (:issues-title-placeholder . "Resumo breve do problema")
 (:issues-message-label . "O que aconteceu?")
 (:issues-message-placeholder . "Inclua passos para reproduzir, comportamento esperado e o que aconteceu no lugar.")
 (:issues-submit . "Enviar relato")
 (:issues-cancel . "Cancelar")
 (:issues-success . "Obrigado. Seu relato de problema foi enviado.")
 (:issues-error-required . "Descreva o problema antes de enviar.")
 (:issues-error-title-too-long . "O título do relato está longo demais. Mantenha-o com menos de 160 caracteres.")
 (:issues-error-too-long . "O texto do relato é longo demais. Mantenha abaixo de 4000 caracteres.")
 (:issues-error-rate-limit . "Muitos relatos desta origem. Aguarde e tente novamente mais tarde.")
 (:issues-error-generic . "Não foi possível enviar o relato de problema. Tente novamente.")

)
