;;; Russian translations
;;; Русские переводы

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Русский")
 (:lang-flag . "🇷🇺")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Выберите язык")
 (:lang-modal-subtitle . "Выберите предпочтительный язык интерфейса:")

 ;; Navigation
 (:nav-translate . "Перевод")
 (:nav-review . "Повторение")
 (:nav-flashcards . "Мои карточки")
 (:nav-dashboard . "Панель")
 (:nav-decks . "Decks")
 (:nav-logout . "Выйти")
 (:nav-home . "Главная")
 (:nav-pricing . "Цены")
 (:nav-export-data . "Экспорт данных")

 ;; App title and branding
 (:app-title . "Hiisi - Изучение языков")
 (:app-tagline . "Изучайте языки через переводы")

 ;; Landing page
 (:landing-hero-title . "Освойте любой язык")
 (:landing-hero-subtitle . "Переводите что угодно. Автоматически создавайте карточки, которые объясняют, почему это работает именно так.")
 (:landing-cta . "Начать обучение")
 (:landing-learn-more . "Узнать больше")
 (:landing-how-it-works . "Как это работает")
 (:landing-feature-1-title . "Автоматические карточки")
 (:landing-feature-1-desc . "Каждый перевод автоматически создаёт карточки с грамматическим разбором. Никакого ручного создания карточек.")
 (:landing-feature-2-title . "Интервальное повторение")
 (:landing-feature-2-desc . "Алгоритм SM-2 планирует повторения через оптимальные интервалы. Учитесь эффективно, запоминайте навсегда.")
 (:landing-feature-3-title . "Обучение грамматике")
 (:landing-feature-3-desc . "Каждый перевод объясняет грамматику, корни слов и структуру предложения. Понимайте почему, а не только что.")
 (:landing-free-trial . "7 дней бесплатно.")
 (:landing-start-trial . "Начать бесплатно")
 (:landing-best-value . "Лучшая цена")
 (:landing-cta-title . "Готовы изучать языки через грамматику, а не зубрёжку?")
 (:landing-cta-subtitle . "Каждый перевод становится возможностью для обучения. Каждая карточка объясняет почему.")
 (:landing-signup-free . "Зарегистрироваться бесплатно")

 ;; Auth pages
 (:auth-register . "Регистрация")
 (:auth-login . "Войти")
 (:auth-logout . "Выйти")
 (:auth-email . "Email")
 (:auth-password . "Пароль")
 (:auth-password-again . "Подтвердите пароль")
 (:auth-display-name . "Отображаемое имя")
 (:auth-register-title . "Регистрация в Hiisi")
 (:auth-register-subtitle . "Создать новый аккаунт")
 (:auth-login-title . "Вход в Hiisi")
 (:auth-login-subtitle . "Введите данные")
 (:auth-login-invalid-credentials . "Nevernyi e-mail ili parol.")
 (:auth-login-rate-limited . "Slishkom mnogo popytok vhoda. Podozhdite neskolko minut i poprobuyte snova.")
 (:auth-forgot-password . "Забыли пароль?")
 (:auth-no-account . "Нет аккаунта?")
 (:auth-have-account . "Уже есть аккаунт?")
 (:auth-google . "Войти через Google")
 (:auth-account-created . "Аккаунт создан")
 (:auth-check-email . "Проверьте почту для активации аккаунта")
 (:auth-redirect-login . "Перенаправление на страницу входа через")
 (:auth-seconds . "секунд")
 (:auth-go-now . "Перейти сейчас")
 (:auth-not-activated . "Аккаунт не активирован. Проверьте почту для получения ссылки активации.")
 (:auth-activate-title . "Активация аккаунта")
 (:auth-activated . "Аккаунт активирован!")
 (:auth-activated-message . "Ваш аккаунт активирован. Теперь вы можете использовать Hiisi.")
 (:auth-redirecting . "Перенаправление через")
 (:auth-go-to-app . "Перейти в приложение")
 (:auth-resend-title . "Отправить письмо активации повторно")
 (:auth-resend-subtitle . "Введите email, чтобы получить новую ссылку активации.")
 (:auth-resend-button . "Отправить письмо активации повторно")
 (:auth-resend-success . "Письмо активации отправлено!")
 (:auth-resend-success-detail . "Проверьте почту для получения новой ссылки активации.")
 (:auth-resend-rate-limited . "Пожалуйста, подождите несколько минут перед повторной отправкой.")
 (:auth-resend-cooldown . "Вы можете запросить новое письмо через ~a секунд.")
 (:auth-back-to-login . "Вернуться к входу")
 (:auth-forgot-password-title . "Забыли пароль")
 (:auth-forgot-password-subtitle . "Введите email и мы отправим вам ссылку для сброса пароля.")
 (:auth-send-reset-link . "Отправить ссылку для сброса")
 (:auth-reset-email-sent . "Ссылка отправлена!")
 (:auth-reset-email-sent-detail . "Если аккаунт с таким email существует, вы скоро получите ссылку для сброса пароля.")
 (:auth-reset-rate-limited . "Пожалуйста, подождите несколько минут перед следующим запросом сброса пароля.")
 (:auth-reset-invalid-token . "Эта ссылка для сброса недействительна или истекла.")
 (:auth-reset-password-title . "Сброс пароля")
 (:auth-reset-password-subtitle . "Введите новый пароль ниже.")
 (:auth-new-password . "Новый пароль")
 (:auth-confirm-new-password . "Подтвердите новый пароль")
 (:auth-reset-password . "Сбросить пароль")
 (:auth-password-changed . "Пароль изменён!")
 (:auth-password-changed-detail . "Ваш пароль успешно изменён. Теперь вы можете войти с новым паролем.")
 (:auth-change-password-title . "Изменить пароль")
 (:auth-change-password-subtitle . "Обновите пароль вашего аккаунта.")
 (:auth-current-password . "Текущий пароль")
 (:auth-change-password . "Изменить пароль")
 (:auth-back-to-app . "Вернуться в приложение")
 (:auth-password-updated . "Пароль обновлён!")
 (:auth-password-updated-detail . "Ваш пароль успешно обновлён.")

 ;; Translation page
 (:translate-title . "Перевод")
 (:translate-input-label . "Текст для перевода")
 (:translate-input-placeholder . "Введите текст для перевода...")
 (:translate-from . "С:")
 (:translate-to . "На:")
 (:translate-submit . "Перевести")
 (:translate-save . "Сохранить в карточки")
 (:translate-saved . "Сохранено!")
 (:translate-like . "Нравится")
 (:translate-dislike . "Не нравится")
 (:translate-char-limit . "символов осталось")
 (:translate-auto-detect . "Любой (Автоопределение)")
 (:translate-empty-state . "Введите текст выше и нажмите Перевести, чтобы увидеть результат с грамматическим разбором")
 (:translate-select-deck-placeholder . "Выберите колоду (необязательно)")
 (:translate-new-deck . "Новая колода")
 (:translate-add-to-deck . "Добавить в колоду")
 (:translate-bookmark . "Сохранить")
 (:translate-bookmarked . "Сохранено")
 (:translate-retry . "Повторить")
 (:translate-like-tooltip . "Хороший перевод")
 (:translate-dislike-tooltip . "Плохой перевод - запросить новый")
 (:translate-dislike-confirm . "Это сгенерирует новый перевод. Продолжить?")
 (:translate-liked . "Нравится!")

 ;; Translation and Flashcards
 (:lang-auto . "Авто")
 (:lang-unknown . "?")
 (:lang-target . "Цель")
 (:translate-deck-create-title . "Создать новую колоду")
 (:translate-deck-name-label . "Название колоды")
 (:translate-deck-name-placeholder . "например, Основы финского")
 (:translate-deck-description-label . "Описание (необязательно)")
 (:translate-deck-cancel . "Отмена")
 (:translate-deck-create . "Создать")
 (:translate-rate-label . "Оценить перевод")
 (:flashcards-delete-confirm . "Вы уверены, что хотите удалить эту карточку?")
 (:flashcards-deck-search-placeholder . "Искать колоды...")
 (:flashcards-no-decks . "Колоды пока нет. Сначала создайте одну!")
 (:flashcards-deck-cancel . "Отмена")
 (:flashcards-recollection-tooltip . "Запоминание: ~A")
 (:flashcards-recollection-poor . "Слабое")
 (:flashcards-recollection-fair . "Среднее")
 (:flashcards-recollection-normal . "Нормальное")
 (:flashcards-recollection-strong . "Сильное")
 (:flashcards-recollection-very-strong . "Очень сильное")

 ;; Flashcard review
 (:review-title . "Повторение")
 (:review-session-title . "Сессия повторения")
 (:review-session-subtitle . "Практикуйте сохранённые карточки")
 (:review-selector-title . "Выберите, что повторять")
 (:review-selector-subtitle . "Выберите колоду или языковую пару, на которой хотите сосредоточиться в этой сессии повторения.")
 (:review-by-deck . "Повторять по колоде")
 (:review-by-language-pair . "Повторять по языковой паре")
 (:review-all-cards . "Повторить все карточки")

 (:review-start . "Начать повторение")
 (:review-no-cards . "Нет карточек для повторения")
 (:review-no-cards-desc . "У вас нет карточек, запланированных на повторение прямо сейчас.")
 (:review-no-cards-hint . "Переведите текст и нажмите \"Сохранить в карточки\", чтобы создать колоду!")
 (:review-start-translating . "Начать переводить")
 (:review-show-answer . "Показать ответ")
 (:review-click-reveal . "Нажмите, чтобы показать ответ")
 (:review-grammar-breakdown . "Грамматический разбор")
 (:review-how-well . "Насколько хорошо вы запомнили?")
 (:review-again . "Снова")
 (:review-hard . "Сложно")
 (:review-good . "Хорошо")
 (:review-easy . "Легко")
 (:review-progress . "Карточка ~a из ~a")
 (:review-complete . "Сессия завершена!")
 (:review-complete-msg . "Вы повторили ~a карточек")
 (:review-correct . "Правильно")
 (:review-accuracy . "Точность")
 (:review-again-btn . "Повторить снова")
 (:review-translate-more . "Переводить ещё")
 (:review-streak . "дней подряд")

 ;; Dashboard
 (:dashboard-title . "Панель")
 (:dashboard-cards-due . "Карточек на сегодня")
 (:dashboard-total-cards . "Всего карточек")
 (:dashboard-subscription . "Подписка")
 (:dashboard-subscribed-until . "Подписка до")
 (:dashboard-not-subscribed . "Нет подписки")
 (:dashboard-recent . "Недавние переводы")
 (:dashboard-no-translations . "Пока нет переводов")
 (:dashboard-streak . "Текущая серия")
 (:dashboard-days . "дней")
 (:dashboard-quick-actions . "Быстрые действия")
 (:dashboard-getting-started . "Начало работы")
 (:dashboard-tip-1 . "Переводите текст, который хотите выучить")
 (:dashboard-tip-2 . "Нажмите \"Сохранить в карточки\" на переводах, которые хотите запомнить")
 (:dashboard-tip-3 . "Регулярно повторяйте карточки — интервальное повторение помогает запоминать надолго")
 (:dashboard-tip-4 . "Оценивайте честно — это помогает алгоритму оптимально планировать повторения")

 ;; Account
 (:account-title . "Аккаунт")
 (:account-subtitle . "Управляйте настройками аккаунта и графиком удаления.")
 (:account-deletion-title . "Удаление аккаунта")
 (:account-deletion-scheduled . "Ваш аккаунт запланирован к удалению на ~A.")
 (:account-deletion-cancel-hint . "Вы можете отменить до этой даты, чтобы сохранить аккаунт.")
 (:account-deletion-cancel . "Отменить удаление")
 (:account-deletion-request . "Вы можете запросить удаление аккаунта в любое время. Удаление запланировано через 14 дней после подтверждения. Если вы передумаете после удаления, свяжитесь с поддержкой.")
 (:account-deletion-confirm . "Запланировать удаление аккаунта через 14 дней с сегодняшнего дня?")
 (:account-deletion-schedule . "Запланировать удаление")
 (:account-reminders-title . "Напоминания по email")
 (:account-reminders-subtitle . "Управляйте напоминаниями о повторении и продолжении для этого аккаунта.")
 (:account-reminders-opt-out . "Отключить напоминания о повторении и продолжении")
 (:account-reminders-save . "Сохранить настройки")

 ;; Subscription
 (:subscribe-title . "Простые цены")
 (:subscribe-monthly . "Месячный")
 (:subscribe-annual . "Годовой")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-monthly-desc . "600 переводов в месяц")
 (:subscribe-annual-desc . "Сэкономьте €20 — два месяца бесплатно!")
 (:subscribe-cta . "Подписаться")
 (:subscribe-success . "Подписка оформлена!")
 (:subscribe-manage . "Управление подпиской")
 (:subscribe-choose-plan . "Выберите тариф")
 (:subscribe-start-today . "Начните сегодня")
 (:subscribe-per-month . "/месяц")
 (:subscribe-per-year . "/год")
 (:subscribe-unlimited-flashcards . "Неограниченное количество карточек")
 (:subscribe-grammar-explanations . "Грамматические объяснения")
 (:subscribe-spaced-repetition . "Интервальное повторение")
 (:subscribe-activated . "Подписка активирована")
 (:subscribe-thank-you . "Спасибо за подписку!")
 (:subscribe-start-learning . "Начать обучение")
 (:subscribe-management . "Управление подпиской")
 (:subscribe-active . "Активна")
 (:subscribe-status . "Статус подписки")
 (:subscribe-status-active . "Ваша подписка активна")
 (:subscribe-days-remaining . "дней осталось")
 (:subscribe-renews-on . "Продление")
 (:subscribe-no-subscription . "Нет активной подписки")
 (:subscribe-access-features . "Оформите подписку для доступа ко всем функциям")
 (:subscribe-view-plans . "Посмотреть тарифы")
 (:subscribe-faq-title . "Часто задаваемые вопросы")
 (:subscribe-faq-trial-q . "Есть ли пробный период?")
 (:subscribe-faq-trial-a . "Да, вы получаете 7 дней бесплатного пробного периода при регистрации.")
 (:subscribe-faq-cancel-q . "Могу ли я отменить подписку?")
 (:subscribe-faq-cancel-a . "Да, вы можете отменить подписку в любое время. Доступ сохранится до конца оплаченного периода.")
 (:subscribe-faq-payment-q . "Какие способы оплаты принимаются?")
 (:subscribe-faq-payment-a . "Мы принимаем все основные кредитные карты через Polar.")
 (:subscribe-copyright . "Все права защищены")

 ;; Errors and status
 (:error-generic . "Что-то пошло не так")
 (:error-not-found . "Страница не найдена")
 (:error-unauthorized . "Войдите для продолжения")
 (:error-subscription-required . "Требуется подписка")
 (:error-text-too-long . "Текст слишком длинный. Максимальная длина перевода — 120 символов.")
 (:error-input-too-long . "Слишком длинный ввод")
 (:error-unknown-source-lang . "Выбранный исходный язык не поддерживается.")
 (:error-unknown-target-lang . "Выбранный целевой язык не поддерживается.")
 (:error-unknown-language . "Неизвестный язык")
 (:error-translation-unavailable . "Сервис перевода временно недоступен. Пожалуйста, попробуйте позже.")
 (:error-translation-failed . "Ошибка перевода")
 (:error-translation-retry . "Не удалось сгенерировать перевод после нескольких попыток. Попробуйте переформулировать текст.")
 (:error-quota-exceeded . "Лимит переводов исчерпан")
 (:error-quota-exceeded-detail . "Вы использовали все переводы за этот месяц. Ваша квота автоматически сбрасывается каждый месяц.")
 (:quota-warning . "Осталось переводов: ~A")
 (:quota-low-warning . "Осталось всего ~A переводов. Рассмотрите возможность покупки.")
 (:top-up-button . "Купить больше переводов")
 (:top-up-success . "Пополнение успешно! Теперь у вас ~A дополнительных переводов.")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 переводов")
 (:loading . "Загрузка...")
 (:empty-state . "Здесь пока ничего нет")

 ;; Institutions
 (:institutions-page-title . "Hiisi для школ - институциональные лицензии")
 (:institutions-hero-title . "Hiisi для школ")
 (:institutions-hero-subtitle . "Дайте своим студентам обучение языкам с поддержкой ИИ")
 (:institutions-section-title . "Институциональные лицензии")
 (:institutions-section-body . "Мы предлагаем оптовые лицензии для школ, университетов и языковых учреждений. Студенты с адресами электронной почты вашего домена автоматически получают полный доступ.")
 (:institutions-benefit-1 . "Автоматическая регистрация студентов с институциональной почтой")
 (:institutions-benefit-2 . "Не нужно управлять отдельными учетными записями студентов")
 (:institutions-benefit-3 . "Гибкие варианты оплаты")
 (:institutions-benefit-4 . "Выделенная поддержка для преподавателей")
 (:institutions-request-title . "Запросить лицензию")
 (:institutions-request-subtitle . "Заполните форму ниже, и мы свяжемся с вами в течение 2 рабочих дней.")
 (:institutions-field-name . "Название учреждения")
 (:institutions-field-name-placeholder . "Хельсинкский университет")
 (:institutions-field-contact-name . "Контактное лицо")
 (:institutions-field-contact-name-placeholder . "Ваше имя")
 (:institutions-field-contact-email . "Контактный email")
 (:institutions-field-contact-email-placeholder . "vy@universitet.ru")
 (:institutions-field-domains . "Домены email")
 (:institutions-field-domains-placeholder . "universitet.ru, cs.universitet.ru")
 (:institutions-field-domains-help . "Список доменов электронной почты вашей организации через запятую")
 (:institutions-field-notes . "Дополнительная информация")
 (:institutions-field-notes-placeholder . "Примерное количество студентов, предпочтительный цикл оплаты, особые требования...")
 (:institutions-submit . "Отправить запрос")
 (:institutions-success-title . "Спасибо - Hiisi для школ")
 (:institutions-success-heading . "Спасибо!")
 (:institutions-success-body . "Мы получили ваш запрос на институциональную лицензию. Наша команда рассмотрит его и свяжется с вами в течение 2 рабочих дней.")
 (:institutions-success-back . "Назад на главную")

 ;; Footer
 (:footer-privacy . "Политика конфиденциальности")
 (:footer-terms . "Условия использования")
 (:footer-contact . "Контакты")

 ;; Early software notice
 (:early-software-notice . "Hiisi находится на ранней стадии разработки. Нашли ошибку или есть предложение?")
 (:early-software-contact . "Свяжитесь с нами по адресу")

 ;; Privacy Policy
 (:privacy-title . "Privacy Policy")
 (:privacy-updated . "Last updated: January 2026")
 (:privacy-who-title . "Who We Are")
 (:privacy-who-body . "Hiisi is operated by Lambda Symbolics OÜ, a company registered in Estonia. As an Estonian company, we comply with the European Union's General Data Protection Regulation (GDPR).")
 (:privacy-collect-title . "Data We Collect")
 (:privacy-collect-intro . "We collect the following information when you use Hiisi:")
 (:privacy-collect-account-key . "Account information: ")
 (:privacy-collect-account-val . "Email address, display name, and a securely hashed password.")
 (:privacy-collect-learning-key . "Learning data: ")
 (:privacy-collect-learning-val . "Your translations, saved flashcards, and review history.")
 (:privacy-collect-usage-key . "Usage data: ")
 (:privacy-collect-usage-val . "Basic server logs for security and debugging purposes.")
 (:privacy-use-title . "How We Use Your Data")
 (:privacy-use-auth-key . "Authentication: ")
 (:privacy-use-auth-val . "To verify your identity and secure your account.")
 (:privacy-use-service-key . "Service delivery: ")
 (:privacy-use-service-val . "To provide translations and manage your flashcard collection.")
 (:privacy-use-ai-key . "AI translations: ")
 (:privacy-use-ai-val . "Your translation requests are sent to Anthropic's Claude API to generate responses. See Anthropic's privacy policy for how they handle this data.")
 (:privacy-third-title . "Third-Party Services")
 (:privacy-third-intro . "We use the following third-party services:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "For AI-powered translations.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "For sending account activation and transactional emails.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "For subscription payment processing.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "We use only essential cookies:")
 (:privacy-cookies-auth-key . "Authentication token: ")
 (:privacy-cookies-auth-val . "A secure, HTTP-only cookie to keep you logged in.")
 (:privacy-cookies-lang-key . "Language preference: ")
 (:privacy-cookies-lang-val . "To remember your preferred UI language.")
 (:privacy-retention-title . "Data Retention")
 (:privacy-retention-body . "Your data is stored as long as you maintain an account. When you request deletion, your account is scheduled for deletion in 14 days.")
 (:privacy-rights-title . "Your Rights (GDPR)")
 (:privacy-rights-intro . "Under GDPR, you have the right to:")
 (:privacy-rights-access . "Access your personal data")
 (:privacy-rights-export . "Export your data (available at /app/api/export)")
 (:privacy-rights-correct . "Request correction of inaccurate data")
 (:privacy-rights-delete . "Request deletion of your account and data")
 (:privacy-rights-object . "Object to processing of your data")
 (:privacy-rights-contact . "To exercise these rights, contact us at")
 (:privacy-contact-title . "Contact")
 (:privacy-contact-intro . "For privacy-related inquiries:")
 (:privacy-contact-email-label . "Email: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Estonia")

 ;; Terms of Service
 (:terms-title . "Terms of Service")
 (:terms-updated . "Last updated: January 2026")
 (:terms-1-title . "1. Service Description")
 (:terms-1-body . "Hiisi is a language learning application that provides AI-powered translations with grammatical explanations and spaced repetition flashcards. The service is operated by Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Account Registration")
 (:terms-2-body . "To use Hiisi, you must create an account with a valid email address. You are responsible for maintaining the security of your account credentials.")
 (:terms-3-title . "3. Subscription and Payments")
 (:terms-3-body . "Hiisi offers paid subscription plans (monthly and annual). Subscriptions are processed through Polar.sh.")
 (:terms-3-list-1 . "Subscriptions auto-renew unless cancelled before the renewal date.")
 (:terms-3-list-2 . "Refunds are provided in accordance with applicable consumer protection laws.")
 (:terms-3-list-3 . "Non-payment results in loss of access to premium features.")
 (:terms-4-title . "4. Acceptable Use")
 (:terms-4-intro . "You agree not to:")
 (:terms-4-list-1 . "Use the service for any illegal purpose")
 (:terms-4-list-2 . "Attempt to circumvent usage limits or security measures")
 (:terms-4-list-3 . "Share your account credentials with others")
 (:terms-4-list-4 . "Use automated tools to access the service in a way that degrades performance for others")
 (:terms-5-title . "5. Content and Intellectual Property")
 (:terms-5-body-1 . "Translations generated by Hiisi are created using AI and may not be unique. You may use your translations and flashcards for any personal purpose, but you do not hold exclusive authorship rights over AI-generated content.")
 (:terms-5-body-2 . "The Hiisi application, branding, and original content remain the property of Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Service Availability")
 (:terms-6-intro . "Hiisi is provided on an \"as-is\" basis. We do not guarantee:")
 (:terms-6-list-1 . "Uninterrupted or error-free service")
 (:terms-6-list-2 . "Accuracy of AI-generated translations")
 (:terms-6-list-3 . "Availability of specific features")
 (:terms-6-body . "We may modify or discontinue features at any time.")
 (:terms-7-title . "7. Limitation of Liability")
 (:terms-7-body-1 . "To the maximum extent permitted by law, Lambda Symbolics OÜ shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of Hiisi.")
 (:terms-7-body-2 . "Our total liability shall not exceed the amount you paid for the service in the 12 months preceding the claim.")
 (:terms-8-title . "8. Account Termination")
 (:terms-8-body-1 . "We may suspend or terminate your account if you violate these terms. You may request account deletion at any time through the application.")
 (:terms-8-body-2 . "Upon deletion request, your account is scheduled for deletion in 14 days.")
 (:terms-9-title . "9. Changes to Terms")
 (:terms-9-body . "We may update these terms from time to time. Continued use of Hiisi after changes constitutes acceptance of the new terms.")
 (:terms-10-title . "10. Governing Law")
 (:terms-10-body . "These terms are governed by the laws of Estonia. Any disputes shall be resolved in the courts of Estonia.")
 (:terms-contact-title . "Contact")
 (:terms-contact-intro . "For questions about these terms:")
 (:terms-contact-email-label . "Email: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Estonia")



 ;; Decks
 (:decks-title . "Колоды")
 (:decks-subtitle . "Создавайте собственные колоды и делитесь ими с другими.")
 (:decks-create-title . "Создать колоду")
 (:decks-name-placeholder . "Название колоды")
 (:decks-desc-placeholder . "Описание")
 (:decks-create-btn . "Создать колоду")
 (:decks-your-title . "Ваши колоды")
 (:decks-col-name . "Название")
 (:decks-col-desc . "Описание")
 (:decks-col-updated . "Обновлено")
 (:decks-col-actions . "Действия")
 (:decks-no-decks . "Колод пока нет.")
 (:decks-open-btn . "Открыть")
 (:decks-no-desc . "Без описания.")
 (:decks-share-title . "Ссылка для обмена")
 (:decks-share-info . "Любой с этой ссылкой может импортировать колоду:")
 (:decks-share-copy . "Скопировать ссылку")
 (:decks-share-copied . "Скопировано")
 (:decks-add-from-flashcards-title . "Добавить переводы")
 (:decks-add-from-flashcards-info . "Выберите карточку, чтобы добавить её перевод в эту колоду.")
 (:decks-open-flashcards . "Добавить из карточек")
 (:decks-filter-from . "Язык источника")
 (:decks-filter-to . "Язык перевода")
 (:decks-filter-any . "Любой язык")
 (:decks-filter-include-assigned . "Показывать карточки, которые уже в колоде")
 (:decks-flashcards-col-from . "Из")
 (:decks-flashcards-col-to . "В")
 (:decks-flashcards-add . "Добавить")
 (:decks-flashcards-added . "Добавлено")
 (:decks-flashcards-in-deck . "В другой колоде")
 (:decks-flashcards-empty . "Нет карточек, соответствующих этим фильтрам.")
 (:decks-add-trans-title . "Добавить перевод")
 (:decks-trans-id-placeholder . "ID перевода")
 (:decks-add-trans-btn . "Добавить перевод")
 (:decks-items-title . "Содержимое колоды")
 (:decks-col-original . "Оригинал")
 (:decks-col-translated . "Перевод")
 (:decks-col-lang . "Целевой язык")
 (:decks-no-items . "Элементов пока нет.")
 (:decks-share-page-title . "Поделиться колодой")
 (:decks-share-preview . "Предпросмотр и импорт этой колоды.")
 (:decks-import-title . "Импорт")
 (:decks-import-btn . "Импортировать колоду")

 ;; Flashcards management page
 (:flashcards-title . "Мои карточки")
 (:flashcards-subtitle . "Все ваши сохранённые карточки в одном месте. Ищите, организуйте и управляйте.")
 (:flashcards-search-placeholder . "Поиск карточек...")
 (:flashcards-col-original . "Оригинал")
 (:flashcards-col-translated . "Перевод")
 (:flashcards-col-lang . "Языки")
 (:flashcards-no-cards . "Карточек пока нет. Начните переводить, чтобы создать их!")

 ;; API Errors (EN fallback)
 (:api-error-missing-text . "Missing text to translate.")
 (:api-error-invalid-translation-id . "Invalid translation ID.")
 (:api-error-translation-not-found . "The translation you tried to save no longer exists.")
 (:api-error-invalid-bookmark-id . "Invalid bookmark ID")
 (:api-error-bookmark-not-found . "Bookmark not found")
 (:api-error-forbidden . "Forbidden")
 (:api-error-failed-delete-bookmark . "Failed to delete bookmark")
 (:api-error-invalid-flashcard-id . "Invalid flashcard ID")
 (:api-error-missing-deck-id . "Missing deck_id")
 (:api-error-flashcard-not-found . "Flashcard not found")
 (:api-error-deck-not-found . "Deck not found")
 (:api-error-deck-name-required . "Deck name is required")
 (:api-error-session-expired . "Your review session has expired. Please start a new session.")
 (:api-error-invalid-card-id . "Invalid card ID.")
 (:api-error-invalid-rating . "Invalid rating.")
 (:api-error-rating-range . "Rating must be between 0 and 5.")
 (:api-error-card-not-found . "Card not found.")
 (:api-error-permission-denied . "You don't have permission to review this card.")
 (:api-error-unknown-source-lang . "Unknown source language.")
 (:api-error-unknown-target-lang . "Unknown target language.")
 (:api-error-failed-add-to-deck . "Failed to add to deck")

 ;; API Success messages
 (:api-success-added . "Added!")
 (:api-success-added-simple . "Added")

 ;; API Stats
 (:api-stats-due . "~A due")
 (:api-stats-total . "~A total")

 ;; Time units
 (:api-time-day . "day")
 (:api-time-days . "days")
 (:api-time-day-left . "day left")
 (:api-time-days-left . "days left")

 ;; Subscription status
 (:api-subscription-active . "Active")
 (:api-subscription-inactive . "Inactive")
 (:api-subscription-subscribe-hint . "Subscribe to unlock translations")

 ;; Generic status
 (:status-bad-request . "Bad Request")
 (:status-not-found . "Not Found")
 (:status-forbidden . "Forbidden")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Izuchajte jazyki vsestoronne")
 (:landing-hero-subheadline . "Poluchajte perevody s polnym grammaticheskim razborom i strojte ustojchivyj slovarnyj zapas s pomoshhju kartochek intervalnogo povtorenija.")
 (:landing-hero-trust-line . "7 dnej besplatnogo probnogo perioda so 100 perevodami. Karta objazatelna. Otmena v ljuboj moment.")
 (:landing-credibility-languages . "14 jazykov")
 (:landing-credibility-ai . "Grammaticheskij razbor vkljuchen")
 (:landing-credibility-origin . "Sozdano v Jestonii")
 (:landing-step-1-title . "Perevedite ljuboj tekst")
 (:landing-step-1-desc . "Vvedite slovo ili frazu. Poluchite perevod s polnym grammaticheskim razborom.")
 (:landing-step-2-title . "Sohranite kak kartochki")
 (:landing-step-2-desc . "Sohranjajte perevody, kotorye hotite zapomnit. Kartochki sozdajutsja avtomaticheski.")
 (:landing-step-3-title . "Povtorjajte i zapominajte")
 (:landing-step-3-desc . "Intervalnoe povtorenie planiruet proverki v idealnyj moment dlja dolgovremennoj pamjati.")
 (:landing-feature-grammar-title . "Ponimajte grammatiku, a ne tolko slova")
 (:landing-feature-grammar-desc . "Kazhdyj perevod soderzhit podrobnyj grammaticheskij razbor -- formy slov, padezhi, sprjazhenija objasneny na vashem jazyke.")
 (:landing-feature-srs-title . "Zapominanie na osnove nauki")
 (:landing-feature-srs-desc . "Algoritm SM-2 adaptiruetsja k vashim rezultatam. Slozhnye kartochki pojavljajutsja chashhe. Kartochki, kotorye vy znaete, othodjat.")
 (:landing-feature-share-title . "Deljtes kolodami s uchenikami")
 (:landing-feature-share-desc . "Prepodavateli mogut sozdavat sobstvennye kolody kartochek i delitsja imi po ssylke. Ucheniki importirujut kolodu i srazu nachinajut povtorenie.")
 (:landing-pricing-trial-note . "Vkljuchaja 7 dnej besplatnogo probnogo perioda")
 (:landing-pricing-monthly-after . "7 dnej besplatno, zatem ~A/mesjac")
 (:landing-pricing-annual-after . "7 dnej besplatno, zatem ~A/god")
 (:landing-faq-title . "Chasto zadavaemye voprosy")
 (:landing-faq-trial-cap-q . "Skolko perevodov ja poluchaju v probnom periode?")
 (:landing-faq-trial-cap-a . "Vy poluchajete 100 perevodov v techenie 7-dnevnogo probnogo perioda. Posle podpiski vy poluchajete 600 v mesjac.")
 (:landing-final-cta-title . "Nachnite uchitsja segodnja")
 (:landing-final-cta-subtitle . "Prisoedinjajtesja k Hiisi i nachnite stroit slovarnyj zapas, kotoryj ostajotsja.")

 ;; Trial status (in-app)
 (:trial-status . "Besplatnyj probnyj period")
 (:trial-days-remaining . "Ostalos ~A dnej")
 (:trial-translations-used . "~A/100 perevodov ispolzovano")
 (:trial-upgrade-prompt . "Obnovite, chtoby prodolzhit perevod")
 (:trial-expired . "Vash besplatnyj probnyj period zavershilsja")
 (:trial-expired-detail . "Podpishites, chtoby prodolzhit obuchenie s Hiisi.")
 (:trial-quota-warning . "Ostalos ~A probnyh perevodov (~A dnej). Podpishites na 600/mesjac.")
 (:trial-quota-exceeded . "Limit probnyh perevodov dostignut. Podpishites, chtoby prodolzhit.")
 (:error-trial-quota-exceeded . "Limit probnyh perevodov dostignut")
 (:error-trial-quota-detail . "Vy ispolzovali vse 100 probnyh perevodov. Podpishites, chtoby prodolzhit obuchenie.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Sozdat kartochku")
 (:custom-flashcard-edit-title . "Redaktirovat kartochku")
 (:custom-flashcard-original . "Ishodnyj tekst")
 (:custom-flashcard-translated . "Perevod")
 (:custom-flashcard-lang-from . "Ishodnyj jazyk")
 (:custom-flashcard-lang-to . "Celevoj jazyk")
 (:custom-flashcard-note . "Uchebnaja zametka")
 (:custom-flashcard-forms . "Grammaticheskij razbor")
 (:custom-flashcard-form-term . "Termin")
 (:custom-flashcard-form-explanation . "Objasnenie")
 (:custom-flashcard-add-form . "Dobavit grammaticheskij termin")
 (:custom-flashcard-remove-form . "Udalit")
 (:custom-flashcard-ai-fill . "Zapolnit s pomoshhju II")
 (:custom-flashcard-ai-fill-all . "Zapolnit vse s pomoshhju II")
 (:custom-flashcard-ai-fill-translation . "Perevesti s pomoshhju II")
 (:custom-flashcard-ai-fill-breakdown . "Sgenerirovat razbor")
 (:custom-flashcard-ai-fill-note . "Sgenerirovat zametku")
 (:custom-flashcard-create-btn . "Sozdat kartochku")
 (:custom-flashcard-update-btn . "Sohranit izmenenija")
 (:custom-flashcard-delete-btn . "Udalit kartochku")
 (:custom-flashcard-delete-confirm . "Vy uvereny, chto hotite udalit jetu kartochku?")
 (:custom-flashcard-created . "Kartochka uspeshno sozdana")
 (:custom-flashcard-updated . "Kartochka uspeshno obnovlena")
 (:custom-flashcard-deleted . "Kartochka uspeshno udalena")
 (:custom-flashcard-add-to-deck . "Dobavit v kolodu")
 (:custom-flashcard-not-found . "Kartochka ne najdena")
 (:custom-flashcard-not-owner . "Vy mozhete redaktirovat tolko kartochki, kotorye sozdali sami")
 (:custom-flashcard-ai-generating . "Generiruetsja s pomoshhju II...")
 (:custom-flashcard-badge . "Polzovatelskaja")

)
