;;; Russian translations
;;; Русские переводы

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Русский")
 (:lang-flag . "🇷🇺")

 ;; Navigation
 (:nav-translate . "Перевод")
 (:nav-review . "Повторение")
 (:nav-dashboard . "Панель")
 (:nav-logout . "Выйти")
 (:nav-home . "Главная")
 (:nav-pricing . "Цены")
 (:nav-export-data . "Экспорт данных")

 ;; App title and branding
 (:app-title . "Hiisi")
 (:app-tagline . "Изучайте языки через переводы")

 ;; Landing page
 (:landing-hero-title . "Освойте любой язык")
 (:landing-hero-subtitle . "Переводите что угодно. Автоматически создавайте карточки, которые объясняют, почему это работает именно так.")
 (:landing-cta . "Начать обучение")
 (:landing-learn-more . "Узнать больше")
 (:landing-how-it-works . "Как это работает")
 (:landing-feature-1-title . "Автоматические карточки")
 (:landing-feature-1-desc . "Каждый перевод автоматически создаёт карточки с грамматическим разбором. Никакого ручного создания карточек.")
 (:landing-feature-2-title . "Интервальное повторение")
 (:landing-feature-2-desc . "Алгоритм SM-2 планирует повторения через оптимальные интервалы. Учитесь эффективно, запоминайте навсегда.")
 (:landing-feature-3-title . "Обучение грамматике")
 (:landing-feature-3-desc . "Каждый перевод объясняет грамматику, корни слов и структуру предложения. Понимайте почему, а не только что.")
 (:landing-free-trial . "7 дней бесплатно. Карта не требуется.")
 (:landing-start-trial . "Начать бесплатно")
 (:landing-best-value . "Лучшая цена")
 (:landing-cta-title . "Готовы изучать языки через грамматику, а не зубрёжку?")
 (:landing-cta-subtitle . "Каждый перевод становится возможностью для обучения. Каждая карточка объясняет почему.")
 (:landing-signup-free . "Зарегистрироваться бесплатно")

 ;; Auth pages
 (:auth-register . "Регистрация")
 (:auth-login . "Войти")
 (:auth-logout . "Выйти")
 (:auth-email . "Email")
 (:auth-password . "Пароль")
 (:auth-password-again . "Подтвердите пароль")
 (:auth-display-name . "Отображаемое имя")
 (:auth-register-title . "Регистрация в Hiisi")
 (:auth-register-subtitle . "Создать новый аккаунт")
 (:auth-login-title . "Вход в Hiisi")
 (:auth-login-subtitle . "Введите данные")
 (:auth-forgot-password . "Забыли пароль?")
 (:auth-no-account . "Нет аккаунта?")
 (:auth-have-account . "Уже есть аккаунт?")

 ;; Translation page
 (:translate-title . "Перевод")
 (:translate-input-label . "Текст для перевода")
 (:translate-input-placeholder . "Введите текст для перевода...")
 (:translate-from . "С:")
 (:translate-to . "На:")
 (:translate-submit . "Перевести")
 (:translate-save . "Сохранить в карточки")
 (:translate-saved . "Сохранено!")
 (:translate-like . "Нравится")
 (:translate-dislike . "Не нравится")
 (:translate-char-limit . "символов осталось")
 (:translate-auto-detect . "Любой (Автоопределение)")
 (:translate-empty-state . "Введите текст выше и нажмите Перевести, чтобы увидеть результат с грамматическим разбором")

 ;; Flashcard review
 (:review-title . "Повторение")
 (:review-session-title . "Сессия повторения")
 (:review-session-subtitle . "Практикуйте сохранённые карточки")
 (:review-start . "Начать повторение")
 (:review-no-cards . "Нет карточек для повторения")
 (:review-no-cards-desc . "У вас нет карточек, запланированных на повторение прямо сейчас.")
 (:review-no-cards-hint . "Переведите текст и нажмите \"Сохранить в карточки\", чтобы создать колоду!")
 (:review-start-translating . "Начать переводить")
 (:review-show-answer . "Показать ответ")
 (:review-click-reveal . "Нажмите, чтобы показать ответ")
 (:review-grammar-breakdown . "Грамматический разбор")
 (:review-how-well . "Насколько хорошо вы запомнили?")
 (:review-again . "Снова")
 (:review-hard . "Сложно")
 (:review-good . "Хорошо")
 (:review-easy . "Легко")
 (:review-progress . "Карточка ~a из ~a")
 (:review-complete . "Сессия завершена!")
 (:review-complete-msg . "Вы повторили ~a карточек")
 (:review-correct . "Правильно")
 (:review-accuracy . "Точность")
 (:review-again-btn . "Повторить снова")
 (:review-translate-more . "Переводить ещё")
 (:review-streak . "дней подряд")

 ;; Dashboard
 (:dashboard-title . "Панель")
 (:dashboard-cards-due . "Карточек на сегодня")
 (:dashboard-total-cards . "Всего карточек")
 (:dashboard-subscription . "Подписка")
 (:dashboard-subscribed-until . "Подписка до")
 (:dashboard-not-subscribed . "Нет подписки")
 (:dashboard-recent . "Недавние переводы")
 (:dashboard-no-translations . "Пока нет переводов")
 (:dashboard-streak . "Текущая серия")
 (:dashboard-days . "дней")
 (:dashboard-quick-actions . "Быстрые действия")
 (:dashboard-getting-started . "Начало работы")
 (:dashboard-tip-1 . "Переводите текст, который хотите выучить")
 (:dashboard-tip-2 . "Нажмите \"Сохранить в карточки\" на переводах, которые хотите запомнить")
 (:dashboard-tip-3 . "Регулярно повторяйте карточки — интервальное повторение помогает запоминать надолго")
 (:dashboard-tip-4 . "Оценивайте честно — это помогает алгоритму оптимально планировать повторения")

 ;; Subscription
 (:subscribe-title . "Простые цены")
 (:subscribe-monthly . "Месячный")
 (:subscribe-annual . "Годовой")
 (:subscribe-monthly-price . "€10/месяц")
 (:subscribe-annual-price . "€100/год")
 (:subscribe-monthly-desc . "600 переводов в месяц")
 (:subscribe-annual-desc . "Сэкономьте €20 — два месяца бесплатно!")
 (:subscribe-cta . "Подписаться")
 (:subscribe-success . "Подписка оформлена!")
 (:subscribe-manage . "Управление подпиской")

 ;; Errors and status
 (:error-generic . "Что-то пошло не так")
 (:error-not-found . "Страница не найдена")
 (:error-unauthorized . "Войдите для продолжения")
 (:error-subscription-required . "Требуется подписка")
 (:error-text-too-long . "Текст слишком длинный. Максимальная длина перевода — 120 символов.")
 (:error-input-too-long . "Слишком длинный ввод")
 (:error-unknown-source-lang . "Выбранный исходный язык не поддерживается.")
 (:error-unknown-target-lang . "Выбранный целевой язык не поддерживается.")
 (:error-unknown-language . "Неизвестный язык")
 (:error-translation-unavailable . "Сервис перевода временно недоступен. Пожалуйста, попробуйте позже.")
 (:error-translation-failed . "Ошибка перевода")
 (:error-translation-retry . "Не удалось сгенерировать перевод после нескольких попыток. Попробуйте переформулировать текст.")
 (:loading . "Загрузка...")
 (:empty-state . "Здесь пока ничего нет")

 ;; Footer
 (:footer-privacy . "Политика конфиденциальности")
 (:footer-terms . "Условия использования")
 (:footer-contact . "Контакты")
)
