;;; Russian translations
;;; Русские переводы

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Русский")
 (:lang-flag . "🇷🇺")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Выберите язык")
 (:lang-modal-subtitle . "Выберите предпочтительный язык интерфейса:")

 ;; Navigation
 (:nav-translate . "Перевод")
 (:nav-review . "Повторение")
 (:nav-flashcards . "Мои карточки")
 (:nav-dashboard . "Панель")
 (:nav-decks . "Decks")
 (:nav-logout . "Выйти")
 (:nav-home . "Главная")
 (:nav-pricing . "Цены")
 (:nav-export-data . "Экспорт данных")

 ;; App title and branding
 (:app-title . "Hiisi - Изучение языков")

 ;; Landing page
 (:landing-learn-more . "Узнать больше")
 (:landing-how-it-works . "Как это работает")
 (:landing-start-trial . "Начать бесплатно")
 (:landing-best-value . "Лучшая цена")

 ;; Auth pages
 (:auth-register . "Регистрация")
 (:auth-login . "Войти")
 (:auth-email . "Email")
 (:auth-password . "Пароль")
 (:auth-password-again . "Подтвердите пароль")
 (:auth-display-name . "Отображаемое имя")
 (:auth-register-title . "Регистрация в Hiisi")
 (:auth-register-subtitle . "Создать новый аккаунт")
 (:auth-login-title . "Вход в Hiisi")
 (:auth-login-subtitle . "Введите данные")
 (:auth-login-invalid-credentials . "Nevernyi e-mail ili parol.")
 (:auth-login-rate-limited . "Slishkom mnogo popytok vhoda. Podozhdite neskolko minut i poprobuyte snova.")
 (:auth-forgot-password . "Забыли пароль?")
 (:auth-no-account . "Нет аккаунта?")
 (:auth-have-account . "Уже есть аккаунт?")
 (:auth-google . "Войти через Google")
 (:auth-account-created . "Аккаунт создан")
 (:auth-check-email . "Проверьте почту для активации аккаунта")
 (:auth-redirect-login . "Перенаправление на страницу входа через")
 (:auth-seconds . "секунд")
 (:auth-go-now . "Перейти сейчас")
 (:auth-not-activated . "Аккаунт не активирован. Проверьте почту для получения ссылки активации.")
 (:auth-activate-title . "Активация аккаунта")
 (:auth-activated . "Аккаунт активирован!")
 (:auth-activated-message . "Ваш аккаунт активирован. Теперь вы можете использовать Hiisi.")
 (:auth-redirecting . "Перенаправление через")
 (:auth-go-to-app . "Перейти в приложение")
 (:auth-resend-title . "Отправить письмо активации повторно")
 (:auth-resend-subtitle . "Введите email, чтобы получить новую ссылку активации.")
 (:auth-resend-button . "Отправить письмо активации повторно")
 (:auth-resend-success . "Письмо активации отправлено!")
 (:auth-resend-success-detail . "Проверьте почту для получения новой ссылки активации.")
 (:auth-resend-rate-limited . "Пожалуйста, подождите несколько минут перед повторной отправкой.")
 (:auth-resend-cooldown . "Вы можете запросить новое письмо через ~a секунд.")
 (:auth-back-to-login . "Вернуться к входу")
 (:auth-forgot-password-title . "Забыли пароль")
 (:auth-forgot-password-subtitle . "Введите email и мы отправим вам ссылку для сброса пароля.")
 (:auth-send-reset-link . "Отправить ссылку для сброса")
 (:auth-reset-email-sent . "Ссылка отправлена!")
 (:auth-reset-email-sent-detail . "Если аккаунт с таким email существует, вы скоро получите ссылку для сброса пароля.")
 (:auth-reset-rate-limited . "Пожалуйста, подождите несколько минут перед следующим запросом сброса пароля.")
 (:auth-reset-invalid-token . "Эта ссылка для сброса недействительна или истекла.")
 (:auth-reset-password-title . "Сброс пароля")
 (:auth-reset-password-subtitle . "Введите новый пароль ниже.")
 (:auth-new-password . "Новый пароль")
 (:auth-confirm-new-password . "Подтвердите новый пароль")
 (:auth-reset-password . "Сбросить пароль")
 (:auth-password-changed . "Пароль изменён!")
 (:auth-password-changed-detail . "Ваш пароль успешно изменён. Теперь вы можете войти с новым паролем.")
 (:auth-change-password-title . "Изменить пароль")
 (:auth-change-password-subtitle . "Обновите пароль вашего аккаунта.")
 (:auth-current-password . "Текущий пароль")
 (:auth-change-password . "Изменить пароль")
 (:auth-back-to-app . "Вернуться в приложение")
 (:auth-password-updated . "Пароль обновлён!")
 (:auth-password-updated-detail . "Ваш пароль успешно обновлён.")

 ;; Translation page
 (:translate-title . "Перевод")
 (:translate-input-label . "Текст для перевода")
 (:translate-input-placeholder . "Введите текст для перевода...")
 (:translate-from . "Исходный язык:")
 (:translate-to . "Язык перевода:")
 (:translate-submit . "Перевести")
 (:translate-auto-detect . "Любой (Автоопределение)")
 (:translate-empty-state . "Введите текст выше и нажмите Перевести, чтобы увидеть результат с грамматическим разбором")
 (:translate-select-deck-placeholder . "Выберите колоду (необязательно)")
 (:translate-new-deck . "Новая колода")
 (:translate-add-to-deck . "Добавить в колоду")
 (:translate-bookmark . "Сохранить")
 (:translate-bookmarked . "Сохранено")
 (:translate-retry . "Повторить")
 (:translate-like-tooltip . "Хороший перевод")
 (:translate-dislike-tooltip . "Плохой перевод - запросить новый")
 (:translate-dislike-confirm . "Это сгенерирует новый перевод. Продолжить?")

 ;; Translation and Flashcards
 (:lang-auto . "Авто")
 (:lang-unknown . "?")
 (:lang-target . "Цель")
 (:translate-deck-create-title . "Создать новую колоду")
 (:translate-deck-name-label . "Название колоды")
 (:translate-deck-name-placeholder . "например, Основы финского")
 (:translate-deck-description-label . "Описание (необязательно)")
 (:translate-deck-cancel . "Отмена")
 (:translate-deck-create . "Создать")
 (:translate-rate-label . "Оценить перевод")
 (:flashcards-delete-confirm . "Вы уверены, что хотите удалить эту карточку?")
 (:flashcards-deck-search-placeholder . "Искать колоды...")
 (:flashcards-no-decks . "Колоды пока нет. Сначала создайте одну!")
 (:flashcards-deck-cancel . "Отмена")
 (:flashcards-recollection-tooltip . "Запоминание: ~A")
 (:flashcards-recollection-poor . "Слабое")
 (:flashcards-recollection-fair . "Среднее")
 (:flashcards-recollection-normal . "Нормальное")
 (:flashcards-recollection-strong . "Сильное")
 (:flashcards-recollection-very-strong . "Очень сильное")

 ;; Flashcard review
 (:review-title . "Повторение")
 (:review-session-title . "Сессия повторения")
 (:review-session-subtitle . "Практикуйте сохранённые карточки")
 (:review-selector-title . "Выберите, что повторять")
 (:review-selector-subtitle . "Выберите колоду или языковую пару, на которой хотите сосредоточиться в этой сессии повторения.")
 (:review-by-deck . "Повторять по колоде")
 (:review-by-language-pair . "Повторять по языковой паре")
 (:review-all-cards . "Повторить все карточки")

 (:review-no-cards . "Нет карточек для повторения")
 (:review-no-cards-desc . "У вас нет карточек, запланированных на повторение прямо сейчас.")
 (:review-no-cards-hint . "Переведите текст и нажмите \"Сохранить в карточки\", чтобы создать колоду!")
 (:review-start-translating . "Начать переводить")
 (:review-click-reveal . "Нажмите, чтобы показать ответ")
 (:review-grammar-breakdown . "Грамматический разбор")
 (:review-how-well . "Вы вспомнили?")
 (:review-again . "Нет")
 (:review-hard . "С трудом")
 (:review-good . "Да")
 (:review-easy . "Легко")
 (:review-progress . "Карточка ~a из ~a")
 (:review-complete . "Сессия завершена!")
 (:review-complete-msg . "Вы повторили ~a карточек")
 (:review-again-btn . "Повторить снова")
 (:review-translate-more . "Переводить ещё")
 (:review-streak . "дней подряд")

 ;; Dashboard
 (:dashboard-title . "Панель")
 (:dashboard-cards-due . "Карточек на сегодня")
 (:dashboard-total-cards . "Всего карточек")
 (:dashboard-subscription . "Подписка")
 (:dashboard-subscribed-until . "Подписка до")
 (:dashboard-not-subscribed . "Нет подписки")
 (:dashboard-recent . "Недавние переводы")
 (:dashboard-no-translations . "Пока нет переводов")
 (:dashboard-streak . "Текущая серия")
 (:dashboard-days . "дней")
 (:dashboard-all-caught-up . "Все повторено!")
 (:dashboard-all-caught-up-hint . "Переводите больше, чтобы пополнять свою коллекцию.")
 (:dashboard-quick-actions . "Быстрые действия")
 (:dashboard-getting-started . "Начало работы")
 (:dashboard-tip-1 . "Переводите текст, который хотите выучить")
 (:dashboard-tip-2 . "Нажмите \"Сохранить в карточки\" на переводах, которые хотите запомнить")
 (:dashboard-tip-3 . "Регулярно повторяйте карточки — интервальное повторение помогает запоминать надолго")
 (:dashboard-tip-4 . "Оценивайте честно — это помогает алгоритму оптимально планировать повторения")

 ;; Account
 (:account-title . "Аккаунт")
 (:account-subtitle . "Управляйте настройками аккаунта и графиком удаления.")
 (:account-deletion-title . "Удаление аккаунта")
 (:account-deletion-scheduled . "Ваш аккаунт запланирован к удалению на ~A.")
 (:account-deletion-cancel-hint . "Вы можете отменить до этой даты, чтобы сохранить аккаунт.")
 (:account-deletion-cancel . "Отменить удаление")
 (:account-deletion-request . "Вы можете запросить удаление аккаунта в любое время. Удаление запланировано через 14 дней после подтверждения. Если вы передумаете, свяжитесь с поддержкой до окончания этого 14-дневного срока.")
 (:account-deletion-confirm . "Запланировать удаление аккаунта через 14 дней с сегодняшнего дня?")
 (:account-deletion-schedule . "Запланировать удаление")
 (:account-reminders-title . "Напоминания по email")
 (:account-reminders-subtitle . "Управляйте напоминаниями о повторении и продолжении для этого аккаунта.")
 (:account-reminders-opt-out . "Отключить напоминания о повторении и продолжении")
 (:account-reminders-save . "Сохранить настройки")

 ;; Subscription
 (:subscribe-title . "Простые цены")
 (:subscribe-monthly . "Месячный")
 (:subscribe-annual . "Годовой")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-monthly-desc . "600 переводов в месяц")
 (:subscribe-annual-desc . "Сэкономьте €20 — два месяца бесплатно!")
 (:subscribe-manage . "Управление подпиской")
 (:subscribe-choose-plan . "Выберите тариф")
 (:subscribe-start-today . "Начните сегодня")
 (:subscribe-per-month . "/месяц")
 (:subscribe-per-year . "/год")
 (:subscribe-unlimited-flashcards . "Неограниченное количество карточек")
 (:subscribe-grammar-explanations . "Грамматические объяснения")
 (:subscribe-spaced-repetition . "Интервальное повторение")
 (:subscribe-activated . "Подписка активирована")
 (:subscribe-thank-you . "Спасибо за подписку!")
 (:subscribe-start-learning . "Начать обучение")
 (:subscribe-management . "Управление подпиской")
 (:subscribe-active . "Активна")
 (:subscribe-preapproved-access . "Предварительно одобренный доступ")
 (:subscribe-status . "Статус подписки")
 (:subscribe-status-active . "Ваша подписка активна")
 (:subscribe-status-preapproved . "Предварительно одобрен")
 (:subscribe-preapproved-detail . "Эта учётная запись использует предварительно одобренный доступ, управляемый Hiisi.")
 (:subscribe-days-remaining . "дней осталось")
 (:subscribe-renews-on . "Продление")
 (:subscribe-no-subscription . "Нет активной подписки")
 (:subscribe-access-features . "Оформите подписку для доступа ко всем функциям")
 (:subscribe-view-plans . "Посмотреть тарифы")
 (:subscribe-faq-title . "Часто задаваемые вопросы")
 (:subscribe-faq-trial-q . "Есть ли пробный период?")
 (:subscribe-faq-trial-a . "Да, вы получаете 7 дней бесплатного пробного периода при регистрации.")
 (:subscribe-faq-cancel-q . "Могу ли я отменить подписку?")
 (:subscribe-faq-cancel-a . "Да, вы можете отменить подписку в любое время. Доступ сохранится до конца оплаченного периода.")
 (:subscribe-faq-payment-q . "Какие способы оплаты принимаются?")
 (:subscribe-faq-payment-a . "Мы принимаем все основные кредитные карты через Polar.")
 (:subscribe-copyright . "Все права защищены")

 ;; Errors and status
 (:error-generic . "Что-то пошло не так")
 (:error-text-too-long . "Текст слишком длинный. Максимальная длина перевода — 120 символов.")
 (:error-input-too-long . "Слишком длинный ввод")
 (:error-unknown-source-lang . "Выбранный исходный язык не поддерживается.")
 (:error-unknown-target-lang . "Выбранный целевой язык не поддерживается.")
 (:error-unknown-language . "Неизвестный язык")
 (:error-translation-unavailable . "Сервис перевода временно недоступен. Пожалуйста, попробуйте позже.")
 (:error-translation-failed . "Ошибка перевода")
 (:error-translation-retry . "Не удалось сгенерировать перевод после нескольких попыток. Попробуйте переформулировать текст.")
 (:error-quota-exceeded . "Лимит переводов исчерпан")
 (:error-quota-exceeded-detail . "Вы использовали все переводы за этот месяц. Ваша квота автоматически сбрасывается каждый месяц.")
 (:quota-low-warning . "Осталось всего ~A переводов. Рассмотрите возможность покупки.")
 (:top-up-button . "Купить больше переводов")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 переводов")

 ;; Institutions
 (:institutions-page-title . "Hiisi для школ и университетов")
 (:institutions-hero-title . "Инструменты для преподавания языков, созданные для класса")
 (:institutions-hero-subtitle . "Дайте своим студентам и ученикам общие колоды, практику с вниманием к грамматике и устойчивый ритм повторения, который вписывается в реальное преподавание.")
 (:institutions-section-title . "Почему учреждения выбирают Hiisi")
 (:institutions-section-body . "Hiisi помогает преподавателям превращать учебные материалы в направляемую практику, за которой учащиеся действительно успевают. Создавайте колоды для курса, делитесь ими по ссылке и поддерживайте работу со словарным запасом и грамматикой без лишней административной нагрузки.")
 (:institutions-benefit-1 . "Колоды для совместного использования и собственные задания, соответствующие вашей программе.")
 (:institutions-benefit-2 . "Лайки и дизлайки учащихся помогают поднимать лучшие переводы для распространённых фраз из учебных материалов.")
 (:institutions-benefit-3 . "Грамматические разборы и интервальное повторение поддерживают не только заучивание отдельных списков слов.")
 (:institutions-benefit-4 . "Поддержка с учительским взглядом от человека, который внимательно слушает и действительно заботится о потребностях класса.")
 (:institutions-request-title . "Давайте обсудим")
 (:institutions-request-subtitle . "Расскажите нам о вашей организации, языках и о том, какая учебная поддержка вам нужна. Мы ответим в течение недели.")
 (:institutions-field-name . "Название учреждения")
 (:institutions-field-name-placeholder . "Хельсинкский университет")
 (:institutions-field-contact-name . "Контактное лицо")
 (:institutions-field-contact-name-placeholder . "Ваше имя")
 (:institutions-field-contact-email . "Контактный email")
 (:institutions-field-contact-email-placeholder . "vy@universitet.ru")
 (:institutions-field-domains . "Домены email")
 (:institutions-field-domains-placeholder . "universitet.ru, cs.universitet.ru")
 (:institutions-field-domains-help . "Список доменов электронной почты вашей организации через запятую")
 (:institutions-field-notes . "Дополнительная информация")
 (:institutions-field-notes-placeholder . "Примерное количество студентов, предпочтительный цикл оплаты, особые требования...")
 (:institutions-submit . "Отправить запрос")
 (:institutions-success-title . "Спасибо - Hiisi для школ и университетов")
 (:institutions-success-heading . "Спасибо!")
 (:institutions-success-body . "Мы получили ваше обращение. Мы рассмотрим потребности вашей организации и свяжемся с вами в течение недели.")
 (:institutions-success-back . "Назад на главную")

 ;; Footer
 (:footer-privacy . "Политика конфиденциальности")
 (:footer-terms . "Условия использования")

 ;; Early software notice
 (:early-software-notice . "Hiisi находится на ранней стадии разработки. Нашли ошибку или есть предложение?")

 ;; Политика конфиденциальности
 (:privacy-title . "Политика конфиденциальности")
 (:privacy-updated . "Последнее обновление: январь 2026")
 (:privacy-who-title . "Кто мы")
 (:privacy-who-body . "Hiisi управляется компанией Lambda Symbolics OÜ, зарегистрированной в Эстонии. Как эстонская компания, мы соблюдаем Общий регламент по защите данных (GDPR) Европейского Союза.")
 (:privacy-collect-title . "Какие данные мы собираем")
 (:privacy-collect-intro . "Когда вы используете Hiisi, мы собираем следующую информацию:")
 (:privacy-collect-account-key . "Данные аккаунта: ")
 (:privacy-collect-account-val . "Адрес электронной почты, отображаемое имя и безопасно хэшированный пароль.")
 (:privacy-collect-learning-key . "Учебные данные: ")
 (:privacy-collect-learning-val . "Ваши переводы, сохранённые карточки и история повторений.")
 (:privacy-collect-usage-key . "Данные использования: ")
 (:privacy-collect-usage-val . "Базовые серверные логи для целей безопасности и отладки.")
 (:privacy-use-title . "Как мы используем ваши данные")
 (:privacy-use-auth-key . "Аутентификация: ")
 (:privacy-use-auth-val . "Для подтверждения вашей личности и защиты вашего аккаунта.")
 (:privacy-use-service-key . "Предоставление сервиса: ")
 (:privacy-use-service-val . "Для предоставления переводов и управления вашей коллекцией карточек.")
 (:privacy-use-ai-key . "Переводы с ИИ: ")
 (:privacy-use-ai-val . "Ваши запросы на перевод отправляются в API Claude компании Anthropic для генерации ответов. См. политику конфиденциальности Anthropic, чтобы узнать, как они обрабатывают эти данные.")
 (:privacy-third-title . "Сторонние сервисы")
 (:privacy-third-intro . "Мы используем следующие сторонние сервисы:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "Для переводов на основе ИИ.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "Для отправки писем активации аккаунта и транзакционных писем.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Для обработки платежей по подписке.")
 (:privacy-cookies-title . "Cookie")
 (:privacy-cookies-intro . "Мы используем только необходимые cookie:")
 (:privacy-cookies-auth-key . "Токен аутентификации: ")
 (:privacy-cookies-auth-val . "Безопасный cookie с доступом только по HTTP, который сохраняет вход в систему.")
 (:privacy-cookies-lang-key . "Языковое предпочтение: ")
 (:privacy-cookies-lang-val . "Чтобы запомнить предпочтительный язык интерфейса.")
 (:privacy-retention-title . "Хранение данных")
 (:privacy-retention-body . "Ваши данные хранятся, пока у вас есть аккаунт. Когда вы запрашиваете удаление, удаление аккаунта планируется через 14 дней.")
 (:privacy-rights-title . "Ваши права (GDPR)")
 (:privacy-rights-intro . "Согласно GDPR вы имеете право:")
 (:privacy-rights-access . "Получить доступ к вашим персональным данным")
 (:privacy-rights-export . "Экспортировать ваши данные (доступно по адресу /app/api/export)")
 (:privacy-rights-correct . "Запросить исправление неточных данных")
 (:privacy-rights-delete . "Запросить удаление аккаунта и данных")
 (:privacy-rights-object . "Возражать против обработки ваших данных")
 (:privacy-rights-contact . "Чтобы воспользоваться этими правами, свяжитесь с нами по адресу")
 (:privacy-contact-title . "Контакт")
 (:privacy-contact-intro . "По вопросам конфиденциальности:")
 (:privacy-contact-email-label . "E-mail: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Условия использования
 (:terms-title . "Условия использования")
 (:terms-updated . "Последнее обновление: январь 2026")
 (:terms-1-title . "1. Описание сервиса")
 (:terms-1-body . "Hiisi - это приложение для изучения языков, которое предоставляет автоматические переводы с грамматическими объяснениями и карточки с распределённым повторением. Сервис управляется Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Регистрация аккаунта")
 (:terms-2-body . "Чтобы пользоваться Hiisi, необходимо создать аккаунт с действующим адресом электронной почты. Вы несёте ответственность за безопасность данных вашего аккаунта.")
 (:terms-3-title . "3. Подписка и платежи")
 (:terms-3-body . "Hiisi предлагает платные тарифы подписки (ежемесячный и годовой). Подписки обрабатываются через Polar.sh.")
 (:terms-3-list-1 . "Подписки продлеваются автоматически, если не отменены до даты продления.")
 (:terms-3-list-2 . "Возвраты осуществляются в соответствии с применимым законодательством о защите прав потребителей.")
 (:terms-3-list-3 . "Неоплата приводит к потере доступа к премиум-функциям.")
 (:terms-4-title . "4. Допустимое использование")
 (:terms-4-intro . "Вы соглашаетесь не:")
 (:terms-4-list-1 . "Использовать сервис для незаконных целей")
 (:terms-4-list-2 . "Пытаться обходить ограничения использования или меры безопасности")
 (:terms-4-list-3 . "Передавать данные аккаунта другим лицам")
 (:terms-4-list-4 . "Использовать автоматизированные инструменты так, чтобы ухудшать работу сервиса для других")
 (:terms-5-title . "5. Контент и интеллектуальная собственность")
 (:terms-5-body-1 . "Переводы, создаваемые Hiisi, генерируются автоматически и могут быть неуникальными. Вы можете использовать свои переводы и карточки в личных целях, но не получаете исключительных авторских прав на автоматически созданный контент.")
 (:terms-5-body-2 . "Приложение Hiisi, бренд и оригинальный контент остаются собственностью Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Доступность сервиса")
 (:terms-6-intro . "Hiisi предоставляется как есть. Мы не гарантируем:")
 (:terms-6-list-1 . "Бесперебойную и безошибочную работу сервиса")
 (:terms-6-list-2 . "Точность автоматически сгенерированных переводов")
 (:terms-6-list-3 . "Доступность конкретных функций")
 (:terms-6-body . "Мы можем изменять или прекращать функции в любое время.")
 (:terms-7-title . "7. Ограничение ответственности")
 (:terms-7-body-1 . "В максимально допустимой законом степени Lambda Symbolics OÜ не несёт ответственности за любые косвенные, случайные, специальные или последующие убытки, возникающие в связи с использованием Hiisi.")
 (:terms-7-body-2 . "Наша совокупная ответственность не превышает сумму, уплаченную вами за сервис за 12 месяцев, предшествующих претензии.")
 (:terms-8-title . "8. Прекращение аккаунта")
 (:terms-8-body-1 . "Мы можем приостановить или закрыть ваш аккаунт, если вы нарушите эти условия. Вы можете в любое время запросить удаление аккаунта через приложение.")
 (:terms-8-body-2 . "После запроса на удаление ваш аккаунт будет запланирован к удалению через 14 дней.")
 (:terms-9-title . "9. Изменения условий")
 (:terms-9-body . "Мы можем периодически обновлять эти условия. Продолжение использования Hiisi после изменений означает принятие новых условий.")
 (:terms-10-title . "10. Применимое право")
 (:terms-10-body . "Эти условия регулируются законодательством Эстонии. Любые споры рассматриваются судами Эстонии.")
 (:terms-contact-title . "Контакт")
 (:terms-contact-intro . "По вопросам об этих условиях:")
 (:terms-contact-email-label . "E-mail: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Decks
 (:decks-title . "Колоды")
 (:decks-subtitle . "Создавайте собственные колоды и делитесь ими с другими.")
 (:decks-create-title . "Создать колоду")
 (:decks-name-placeholder . "Название колоды")
 (:decks-desc-placeholder . "Описание")
 (:decks-create-btn . "Создать колоду")
 (:decks-edit-title . "Редактировать колоду")
 (:decks-edit-btn . "Редактировать колоду")
 (:decks-update-btn . "Сохранить изменения")
 (:decks-default-badge . "Автоматическая")
 (:decks-default-description . "Эта колода управляется автоматически для этой языковой пары.")
 (:decks-default-readonly . "У автоматических колод фиксированные названия и описания.")
 (:decks-error-name-required . "Название колоды обязательно.")
 (:decks-error-name-too-long . "Название колоды должно быть не длиннее ~A символов.")
 (:decks-error-desc-too-long . "Описание колоды должно быть не длиннее ~A символов.")
 (:decks-error-default-readonly . "Автоматические колоды нельзя редактировать.")
 (:decks-your-title . "Ваши колоды")
 (:decks-col-updated . "Обновлено")
 (:decks-no-decks . "Колод пока нет.")
 (:decks-open-btn . "Открыть")
 (:decks-no-desc . "Без описания.")
 (:decks-share-title . "Ссылка для обмена")
 (:decks-share-info . "Любой с этой ссылкой может импортировать колоду:")
 (:decks-share-copy . "Скопировать ссылку")
 (:decks-share-copied . "Скопировано")
 (:decks-add-from-flashcards-title . "Добавить переводы")
 (:decks-add-from-flashcards-info . "Выберите карточку, чтобы добавить её перевод в эту колоду.")
 (:decks-open-flashcards . "Добавить из карточек")
 (:decks-filter-from . "Язык источника")
 (:decks-filter-to . "Язык перевода")
 (:decks-filter-any . "Любой язык")
 (:decks-filter-include-assigned . "Показывать карточки, которые уже в колоде")
 (:decks-flashcards-add . "Добавить")
 (:decks-flashcards-added . "Добавлено")
 (:decks-flashcards-in-deck . "В другой колоде")
 (:decks-flashcards-empty . "Нет карточек, соответствующих этим фильтрам.")
 (:decks-items-title . "Содержимое колоды")
 (:decks-col-original . "Оригинал")
 (:decks-col-translated . "Перевод")
 (:decks-col-lang . "Целевой язык")
 (:decks-no-items . "Элементов пока нет.")
 (:decks-share-page-title . "Поделиться колодой")
 (:decks-share-preview . "Предпросмотр и импорт этой колоды.")
 (:decks-import-title . "Импорт")
 (:decks-import-btn . "Импортировать колоду")
 (:starter-decks-title . "Официальные стартовые колоды")
 (:starter-decks-subtitle . "Выберите языковую тройку, просматривайте официальные темы Hiisi и импортируйте готовые учебные колоды.")
 (:starter-decks-marketplace-btn . "Официальные колоды")
 (:starter-decks-explanation-language . "Язык объяснений")
 (:starter-decks-search-label . "Поиск")
 (:starter-decks-search-placeholder . "Искать темы стартовых колод")
 (:starter-decks-apply-filters . "Применить фильтры")
 (:starter-decks-select-triplet-hint . "Выберите исходный и целевой язык, чтобы открыть предпросмотр колоды.")
 (:starter-decks-official-badge . "Официальная")
 (:starter-decks-by-hiisi . "От Hiisi")
 (:starter-decks-preview-btn . "Предпросмотр")
 (:starter-decks-card-count . "~A карточек")
 (:starter-decks-concepts-title . "Запланированные темы карточек")
 (:starter-decks-sample-title . "Примеры карточек")
 (:starter-decks-generating . "Колода создаётся...")
 (:starter-decks-generating-detail . "Эта колода сейчас создаётся для вашей языковой тройки. Оставьте страницу открытой или вернитесь через минуту.")
 (:starter-decks-generation-failed . "Создание не удалось")
 (:starter-decks-generation-failed-detail . "Последняя попытка создания не удалась. Попробуйте импортировать колоду ещё раз.")
 (:starter-decks-login-detail . "Войдите, чтобы импортировать эту колоду в свою коллекцию.")
 (:starter-decks-subscribe-btn . "Посмотреть тарифы")
 (:starter-decks-subscribe-detail . "Стартовые колоды доступны при активной подписке или пробном периоде.")
 (:starter-deck-topic-greetings-title . "Приветствия и знакомство")
 (:starter-deck-topic-greetings-description . "Приветствия, имена, вежливые базовые фразы и выражения для первой встречи.")
 (:starter-deck-topic-travel-title . "Базовые фразы для поездок")
 (:starter-deck-topic-travel-description . "Вокзалы, билеты, цены, просьбы о помощи и ориентирование в дороге.")
 (:starter-deck-topic-numbers-title . "Числа и цены")
 (:starter-deck-topic-numbers-description . "Счёт, суммы, цены, этажи и повседневные количества.")
 (:starter-deck-topic-time-title . "Время и даты")
 (:starter-deck-topic-time-description . "Дни, месяцы, встречи, время на часах и относительные даты.")
 (:starter-deck-topic-food-title . "Ресторан и еда")
 (:starter-deck-topic-food-description . "Заказ, особенности питания, напитки, счёт и повседневные приёмы пищи вне дома.")
 (:starter-deck-topic-emergency-title . "Экстренные ситуации и здоровье")
 (:starter-deck-topic-emergency-description . "Врачи, аптеки, симптомы, части тела и срочная помощь.")
 (:starter-deck-topic-directions-title . "Ориентирование и транспорт")
 (:starter-deck-topic-directions-description . "Повороты, остановки, билеты, платформы и передвижение по городу.")
 (:starter-deck-topic-school-title . "Школа и учёба")
 (:starter-deck-topic-school-description . "Уроки, домашние задания, экзамены, школьные принадлежности и повседневная школьная жизнь.")
 (:starter-deck-topic-university-title . "Университет и учёба")
 (:starter-deck-topic-university-description . "Лекции, семинары, специальности, задания и повседневная жизнь в кампусе.")

 ;; Flashcards management page
 (:flashcards-title . "Мои карточки")
 (:flashcards-subtitle . "Все ваши сохранённые карточки в одном месте. Ищите, организуйте и управляйте.")
 (:flashcards-search-placeholder . "Поиск карточек...")
 (:flashcards-hide-perfected . "Скрыть полностью освоенные карточки")
 (:flashcards-col-original . "Оригинал")
 (:flashcards-col-translated . "Перевод")
 (:flashcards-no-cards . "Карточек пока нет. Начните переводить, чтобы создать их!")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Изучайте языки всесторонне")
 (:landing-hero-subheadline . "Получайте переводы с полным грамматическим разбором и развивайте устойчивый словарный запас с помощью карточек с интервальным повторением.")
 (:landing-hero-trust-line . "7 дней бесплатного пробного периода со 100 переводами. Отменить можно в любой момент.")
 (:landing-credibility-languages . "14 языков")
 (:landing-credibility-ai . "Грамматический разбор включён")
 (:landing-step-1-title . "Переводите любой текст")
 (:landing-step-1-desc . "Введите слово или фразу. Получите перевод с полным грамматическим разбором.")
 (:landing-step-2-title . "Сохраните как карточки")
 (:landing-step-2-desc . "Сохраняйте переводы, которые хотите запомнить. Карточки создаются автоматически.")
 (:landing-step-3-title . "Повторяйте и запоминайте")
 (:landing-step-3-desc . "Интервальное повторение планирует повторения в идеальный момент для долговременной памяти.")
 (:landing-feature-grammar-title . "Понимайте грамматику, а не только слова")
 (:landing-feature-grammar-desc . "Каждый перевод содержит подробный грамматический разбор - формы слов, падежи и спряжения, объяснённые на вашем языке.")
 (:landing-feature-srs-title . "Запоминание на основе науки")
 (:landing-feature-srs-desc . "Алгоритм SM-2 адаптируется к вашим результатам. Сложные карточки появляются чаще. Карточки, которые вы уже знаете, появляются реже.")
 (:landing-feature-share-title . "Делитесь колодами с учениками")
 (:landing-feature-share-desc . "Преподаватели могут создавать собственные колоды карточек и делиться ими по ссылке. Ученики импортируют колоду и сразу начинают повторение.")
 (:landing-pricing-trial-note . "Включает 7 дней бесплатного пробного периода")
 (:landing-pricing-monthly-after . "7 дней бесплатно, затем ~A/месяц")
 (:landing-pricing-annual-after . "7 дней бесплатно, затем ~A/год")
 (:landing-faq-title . "Часто задаваемые вопросы")
 (:landing-faq-trial-cap-q . "Сколько переводов я получу в пробный период?")
 (:landing-faq-trial-cap-a . "Вы получаете 100 переводов в течение 7-дневного пробного периода. После подписки вы получаете 600 в месяц.")
 (:landing-final-cta-title . "Начните учиться сегодня")
 (:landing-final-cta-subtitle . "Присоединяйтесь к Hiisi и начинайте строить словарный запас, который остаётся с вами.")

 ;; Trial status (in-app)
 (:trial-status . "Бесплатный пробный период")
 (:error-trial-quota-exceeded . "Лимит пробных переводов достигнут")
 (:error-trial-quota-detail . "Вы использовали все 100 пробных переводов. Подпишитесь, чтобы продолжить обучение.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Создать карточку")
 (:custom-flashcard-edit-title . "Редактировать карточку")
 (:custom-flashcard-original . "Исходный текст")
 (:custom-flashcard-translated . "Перевод")
 (:custom-flashcard-lang-from . "Исходный язык")
 (:custom-flashcard-lang-to . "Целевой язык")
 (:custom-flashcard-note . "Учебная заметка")
 (:custom-flashcard-forms . "Грамматический разбор")
 (:custom-flashcard-form-term . "Термин")
 (:custom-flashcard-form-explanation . "Объяснение")
 (:custom-flashcard-add-form . "Добавить грамматический термин")
 (:custom-flashcard-remove-form . "Удалить")
 (:custom-flashcard-ai-fill . "Заполнить с помощью ИИ")
 (:custom-flashcard-create-btn . "Создать карточку")
 (:custom-flashcard-update-btn . "Сохранить изменения")

 ;; Сообщения о проблемах
 (:issues-open-button . "Сообщить о проблеме")
 (:issues-modal-title . "Сообщить о проблеме")
 (:issues-modal-subtitle . "Опишите, что пошло не так. Текущая страница будет добавлена автоматически.")
 (:issues-title-label . "Краткий заголовок")
 (:issues-title-placeholder . "Краткое описание проблемы")
 (:issues-message-label . "Что произошло?")
 (:issues-message-placeholder . "Укажите шаги для воспроизведения, ожидаемое поведение и что произошло вместо этого.")
 (:issues-submit . "Отправить сообщение")
 (:issues-cancel . "Отмена")
 (:issues-success . "Спасибо. Сообщение о проблеме отправлено.")
 (:issues-error-required . "Опишите проблему перед отправкой.")
 (:issues-error-title-too-long . "Заголовок обращения слишком длинный. Оставьте не более 160 символов.")
 (:issues-error-too-long . "Текст сообщения слишком длинный. Оставьте не более 4000 символов.")
 (:issues-error-rate-limit . "С этого источника отправлено слишком много сообщений. Подождите и попробуйте позже.")
 (:issues-error-generic . "Не удалось отправить сообщение о проблеме. Попробуйте снова.")

)
