;;; Swedish translations

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Svenska")
 (:lang-flag . "🇸🇪")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Välj ditt språk")
 (:lang-modal-subtitle . "Välj ditt föredragna språk för gränssnittet:")

 ;; Navigation
 (:nav-translate . "Översätt")
 (:nav-review . "Repetera")
 (:nav-flashcards . "Mina kort")
 (:nav-dashboard . "Översikt")
 (:nav-decks . "Decks")
 (:nav-logout . "Logga ut")
 (:nav-home . "Hem")
 (:nav-pricing . "Priser")
 (:nav-export-data . "Exportera data")

 ;; App title and branding
 (:app-title . "Hiisi - Språkinlärning")
 (:app-tagline . "Lär dig språk genom översättningar")

 ;; Landing page
 (:landing-hero-title . "Bemästra vilket språk som helst")
 (:landing-hero-subtitle . "Översätt vad som helst. Generera automatiskt flashcards som lär dig varför det fungerar så.")
 (:landing-cta . "Börja lära dig")
 (:landing-learn-more . "Läs mer")
 (:landing-how-it-works . "Så fungerar det")
 (:landing-feature-1-title . "Automatiska flashcards")
 (:landing-feature-1-desc . "Varje översättning genererar automatiskt flashcards med grammatikförklaringar. Inget manuellt kortskapande.")
 (:landing-feature-2-title . "Spaced repetition")
 (:landing-feature-2-desc . "SM-2-algoritmen schemalägger repetitioner vid optimala intervall. Lär dig effektivt, kom ihåg permanent.")
 (:landing-feature-3-title . "Grammatikundervisning")
 (:landing-feature-3-desc . "Varje översättning förklarar grammatik, ordstammar och meningsstruktur. Förstå varför, inte bara vad.")
 (:landing-free-trial . "7 dagars gratis provperiod.")
 (:landing-start-trial . "Starta gratis provperiod")
 (:landing-best-value . "Bäst värde")
 (:landing-cta-title . "Redo att lära dig språk genom grammatik, inte utantillärning?")
 (:landing-cta-subtitle . "Varje översättning blir ett lärtillfälle. Varje flashcard lär dig varför.")
 (:landing-signup-free . "Registrera dig gratis")

 ;; Auth pages
 (:auth-register . "Registrera")
 (:auth-login . "Logga in")
 (:auth-logout . "Logga ut")
 (:auth-email . "E-post")
 (:auth-password . "Lösenord")
 (:auth-password-again . "Bekräfta lösenord")
 (:auth-display-name . "Visningsnamn")
 (:auth-register-title . "Registrera dig på Hiisi")
 (:auth-register-subtitle . "Skapa ett nytt konto")
 (:auth-login-title . "Logga in på Hiisi")
 (:auth-login-subtitle . "Ange dina uppgifter")
 (:auth-login-invalid-credentials . "Ogiltig e-post eller losenord.")
 (:auth-login-rate-limited . "For manga inloggningsforsok. Vanta nagra minuter och forsok igen.")
 (:auth-forgot-password . "Glömt lösenordet?")
 (:auth-no-account . "Har du inget konto?")
 (:auth-have-account . "Har du redan ett konto?")
 (:auth-google . "Fortsätt med Google")
 (:auth-account-created . "Konto skapat!")
 (:auth-check-email . "Kontrollera din e-post för aktiveringslänken.")
 (:auth-redirect-login . "Omdirigerar till inloggning om")
 (:auth-seconds . "sekunder")
 (:auth-go-now . "Gå nu")
 (:auth-not-activated . "Kontot är inte aktiverat. Kontrollera din e-post för aktiveringslänken.")
 (:auth-activate-title . "Aktivera ditt konto")
 (:auth-activated . "Konto aktiverat!")
 (:auth-activated-message . "Ditt konto har aktiverats. Du kan nu använda Hiisi.")
 (:auth-redirecting . "Omdirigerar om")
 (:auth-go-to-app . "Gå till appen")
 (:auth-resend-title . "Skicka aktiveringsmail igen")
 (:auth-resend-subtitle . "Ange din e-postadress för att få en ny aktiveringslänk.")
 (:auth-resend-button . "Skicka aktiveringsmail igen")
 (:auth-resend-success . "Aktiveringsmail skickat!")
 (:auth-resend-success-detail . "Kontrollera din inkorg för den nya aktiveringslänken.")
 (:auth-resend-rate-limited . "Vänta några minuter innan du begär ett nytt aktiveringsmail.")
 (:auth-resend-cooldown . "Du kan begära ett nytt mail om ~a sekunder.")
 (:auth-back-to-login . "Tillbaka till inloggning")
 (:auth-forgot-password-title . "Glömt lösenord")
 (:auth-forgot-password-subtitle . "Ange din e-postadress så skickar vi dig en länk för att återställa ditt lösenord.")
 (:auth-send-reset-link . "Skicka återställningslänk")
 (:auth-reset-email-sent . "Länk skickad!")
 (:auth-reset-email-sent-detail . "Om ett konto finns med den e-postadressen kommer du snart att få en länk för att återställa lösenordet.")
 (:auth-reset-rate-limited . "Vänta några minuter innan du begär en ny lösenordsåterställning.")
 (:auth-reset-invalid-token . "Denna återställningslänk är ogiltig eller har upphört.")
 (:auth-reset-password-title . "Återställ lösenord")
 (:auth-reset-password-subtitle . "Ange ditt nya lösenord nedan.")
 (:auth-new-password . "Nytt lösenord")
 (:auth-confirm-new-password . "Bekräfta nytt lösenord")
 (:auth-reset-password . "Återställ lösenord")
 (:auth-password-changed . "Lösenord ändrat!")
 (:auth-password-changed-detail . "Ditt lösenord har ändrats. Du kan nu logga in med ditt nya lösenord.")
 (:auth-change-password-title . "Ändra lösenord")
 (:auth-change-password-subtitle . "Uppdatera ditt kontolösenord.")
 (:auth-current-password . "Nuvarande lösenord")
 (:auth-change-password . "Ändra lösenord")
 (:auth-back-to-app . "Tillbaka till appen")
 (:auth-password-updated . "Lösenord uppdaterat!")
 (:auth-password-updated-detail . "Ditt lösenord har uppdaterats.")

 ;; Translation page
 (:translate-title . "Översätt")
 (:translate-input-label . "Text att översätta")
 (:translate-input-placeholder . "Skriv text att översätta...")
 (:translate-from . "Från:")
 (:translate-to . "Till:")
 (:translate-submit . "Översätt")
 (:translate-save . "Spara som flashcard")
 (:translate-saved . "Sparat!")
 (:translate-like . "Gilla")
 (:translate-dislike . "Ogilla")
 (:translate-char-limit . "tecken kvar")
 (:translate-auto-detect . "Valfritt (Identifiera automatiskt)")
 (:translate-empty-state . "Skriv text ovan och klicka Översätt för att se resultatet med grammatikförklaring")
 (:translate-select-deck-placeholder . "Välj kortlek (valfritt)")
 (:translate-new-deck . "Ny kortlek")
 (:translate-add-to-deck . "Lägg till i kortlek")
 (:translate-bookmark . "Spara")
 (:translate-bookmarked . "Sparat")
 (:translate-retry . "Försök igen")
 (:translate-like-tooltip . "Bra översättning")
 (:translate-dislike-tooltip . "Dålig översättning - begär en ny")
 (:translate-dislike-confirm . "Detta genererar en ny översättning. Fortsätta?")
 (:translate-liked . "Gillar!")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Mål")
 (:translate-deck-create-title . "Skapa ny kortlek")
 (:translate-deck-name-label . "Kortlekens namn")
 (:translate-deck-name-placeholder . "t.ex. Finska grunder")
 (:translate-deck-description-label . "Beskrivning (valfri)")
 (:translate-deck-cancel . "Avbryt")
 (:translate-deck-create . "Skapa")
 (:translate-rate-label . "Betygsätt översättning")
 (:flashcards-delete-confirm . "Är du säker på att du vill ta bort det här kortet?")
 (:flashcards-deck-search-placeholder . "Sök kortlekar...")
 (:flashcards-no-decks . "Inga kortlekar ännu. Skapa en först!")
 (:flashcards-deck-cancel . "Avbryt")
 (:flashcards-recollection-tooltip . "Minnesstyrka: ~A")
 (:flashcards-recollection-poor . "Svag")
 (:flashcards-recollection-fair . "Måttlig")
 (:flashcards-recollection-normal . "Normal")
 (:flashcards-recollection-strong . "Stark")
 (:flashcards-recollection-very-strong . "Mycket stark")

 ;; Flashcard review
 (:review-title . "Repetera")
 (:review-session-title . "Repetitionssession")
 (:review-session-subtitle . "Öva på dina sparade flashcards")
 (:review-selector-title . "Välj vad du vill repetera")
 (:review-selector-subtitle . "Välj en kortlek eller ett språkpar att fokusera på i repetitionspasset.")
 (:review-by-deck . "Repetera efter kortlek")
 (:review-by-language-pair . "Repetera efter språkpar")
 (:review-all-cards . "Repetera alla kort")

 (:review-start . "Starta repetition")
 (:review-no-cards . "Inga kort att repetera")
 (:review-no-cards-desc . "Du har inga flashcards som behöver repeteras just nu.")
 (:review-no-cards-hint . "Översätt lite text och klicka \"Spara som flashcard\" för att bygga din kortlek!")
 (:review-start-translating . "Börja översätta")
 (:review-show-answer . "Visa svar")
 (:review-click-reveal . "Klicka för att visa svaret")
 (:review-grammar-breakdown . "Grammatikförklaring")
 (:review-how-well . "Kom du ihåg det?")
 (:review-again . "Nej")
 (:review-hard . "Knappt")
 (:review-good . "Ja")
 (:review-easy . "Lätt")
 (:review-progress . "Kort ~a av ~a")
 (:review-complete . "Session klar!")
 (:review-complete-msg . "Du repeterade ~a kort")
 (:review-correct . "Rätt")
 (:review-accuracy . "Träffsäkerhet")
 (:review-again-btn . "Repetera igen")
 (:review-translate-more . "Översätt mer")
 (:review-streak . "dagar i rad")

 ;; Dashboard
 (:dashboard-title . "Översikt")
 (:dashboard-cards-due . "Kort för idag")
 (:dashboard-total-cards . "Totalt antal kort")
 (:dashboard-subscription . "Prenumeration")
 (:dashboard-subscribed-until . "Prenumererar till")
 (:dashboard-not-subscribed . "Ingen prenumeration")
 (:dashboard-recent . "Senaste översättningar")
 (:dashboard-no-translations . "Inga översättningar än")
 (:dashboard-streak . "Nuvarande svit")
 (:dashboard-days . "dagar")
 (:dashboard-all-caught-up . "Allt är avklarat!")
 (:dashboard-all-caught-up-hint . "Översätt mer för att bygga upp din samling.")
 (:dashboard-quick-actions . "Snabbåtgärder")
 (:dashboard-getting-started . "Kom igång")
 (:dashboard-tip-1 . "Översätt text du vill lära dig")
 (:dashboard-tip-2 . "Klicka \"Spara som flashcard\" på översättningar du vill komma ihåg")
 (:dashboard-tip-3 . "Repetera dina flashcards regelbundet - spaced repetition hjälper dig minnas långsiktigt")
 (:dashboard-tip-4 . "Bedöm ärligt - det hjälper algoritmen schemalägga dina repetitioner optimalt")

 ;; Account
 (:account-title . "Konto")
 (:account-subtitle . "Hantera dina kontoinställningar och raderingsschema.")
 (:account-deletion-title . "Kontoradering")
 (:account-deletion-scheduled . "Ditt konto är planerat att raderas den ~A.")
 (:account-deletion-cancel-hint . "Du kan avbryta före detta datum för att behålla kontot.")
 (:account-deletion-cancel . "Avbryt radering")
 (:account-deletion-request . "Du kan begära att kontot raderas när som helst. Radering planeras 14 dagar efter bekräftelse. Om du ångrar dig efter radering, kontakta support.")
 (:account-deletion-confirm . "Planera kontoradering om 14 dagar från i dag?")
 (:account-deletion-schedule . "Planera radering")
 (:account-reminders-title . "E-postpåminnelser")
 (:account-reminders-subtitle . "Hantera påminnelser om repetition och fortsättning för detta konto.")
 (:account-reminders-opt-out . "Stäng av påminnelser om repetition och fortsättning")
 (:account-reminders-save . "Spara inställningar")

 ;; Subscription
 (:subscribe-title . "Enkla priser")
 (:subscribe-monthly . "Månadsvis")
 (:subscribe-annual . "Årsvis")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-monthly-desc . "600 översättningar per månad")
 (:subscribe-annual-desc . "Spara €20 — två månader gratis!")
 (:subscribe-cta . "Prenumerera")
 (:subscribe-success . "Prenumeration lyckades!")
 (:subscribe-manage . "Hantera prenumeration")
 (:subscribe-choose-plan . "Välj din plan")
 (:subscribe-start-today . "Börja lära dig idag")
 (:subscribe-per-month . "per månad")
 (:subscribe-per-year . "per år")
 (:subscribe-unlimited-flashcards . "Obegränsade flashcards")
 (:subscribe-grammar-explanations . "Grammatikförklaringar")
 (:subscribe-spaced-repetition . "Spaced repetition-schemaläggning")
 (:subscribe-activated . "Prenumeration aktiverad!")
 (:subscribe-thank-you . "Tack för din prenumeration!")
 (:subscribe-start-learning . "Börja lära dig")
 (:subscribe-management . "Hantera prenumeration")
 (:subscribe-active . "Aktiv")
 (:subscribe-status . "Prenumerationsstatus")
 (:subscribe-status-active . "Din prenumeration är aktiv")
 (:subscribe-days-remaining . "dagar kvar")
 (:subscribe-renews-on . "Förnyas den")
 (:subscribe-no-subscription . "Ingen aktiv prenumeration")
 (:subscribe-access-features . "Prenumerera för att få tillgång till alla funktioner")
 (:subscribe-view-plans . "Visa planer")
 (:subscribe-faq-title . "Vanliga frågor")
 (:subscribe-faq-trial-q . "Finns det en gratis provperiod?")
 (:subscribe-faq-trial-a . "Ja! Du får 7 dagars gratis provperiod när du registrerar dig.")
 (:subscribe-faq-cancel-q . "Kan jag avbryta när som helst?")
 (:subscribe-faq-cancel-a . "Ja, du kan avbryta din prenumeration när som helst. Du behåller tillgång till slutet av faktureringsperioden.")
 (:subscribe-faq-payment-q . "Vilka betalningsmetoder accepteras?")
 (:subscribe-faq-payment-a . "Vi accepterar alla större kreditkort och PayPal.")
 (:subscribe-copyright . "© 2025 Hiisi. Alla rättigheter förbehållna.")

 ;; Errors and status
 (:error-generic . "Något gick fel")
 (:error-not-found . "Sidan hittades inte")
 (:error-unauthorized . "Logga in för att fortsätta")
 (:error-subscription-required . "Prenumeration krävs")
 (:error-text-too-long . "Texten är för lång. Maximal översättningslängd är 120 tecken.")
 (:error-input-too-long . "Inmatningen är för lång")
 (:error-unknown-source-lang . "Källspråket du valde stöds inte.")
 (:error-unknown-target-lang . "Målspråket du valde stöds inte.")
 (:error-unknown-language . "Okänt språk")
 (:error-translation-unavailable . "Översättningstjänsten är tillfälligt otillgänglig. Försök igen om en stund.")
 (:error-translation-failed . "Översättningen misslyckades")
 (:error-translation-retry . "Kunde inte generera en översättning efter flera försök. Försök omformulera din text.")
 (:error-quota-exceeded . "Översättningsgräns nådd")
 (:error-quota-exceeded-detail . "Du har använt alla dina översättningar för denna månad. Din kvot återställs automatiskt varje månad.")
 (:quota-warning . "Återstående översättningar: ~A")
 (:quota-low-warning . "Endast ~A översättningar kvar. Överväg att köpa fler.")
 (:top-up-button . "Köp fler översättningar")
 (:top-up-success . "Påfyllning lyckades! Du har nu ~A ytterligare översättningar.")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 översättningar")
 (:loading . "Laddar...")
 (:empty-state . "Inget här än")

 ;; Institutions
 (:institutions-page-title . "Hiisi för skolor och universitet")
 (:institutions-hero-title . "Språkundervisningsverktyg byggda för klassrummet")
 (:institutions-hero-subtitle . "Ge dina studenter delbara kortlekar, grammatikmedveten träning och stabila repetitionsrutiner som fungerar i verklig undervisning.")
 (:institutions-section-title . "Varför institutioner använder Hiisi")
 (:institutions-section-body . "Hiisi hjälper lärare att förvandla kursmaterial till vägledd träning som studenter faktiskt orkar följa. Skapa kortlekar för en kurs, dela dem med en länk och stöd arbete med ordförråd och grammatik utan extra administrativ belastning.")
 (:institutions-benefit-1 . "Delbara kortlekar och egna uppgifter som passar er undervisning.")
 (:institutions-benefit-2 . "Studenternas gilla- och ogilla-markeringar hjälper de starkaste översättningarna att lyftas fram för vanliga fraser i undervisningen.")
 (:institutions-benefit-3 . "Grammatikuppdelningar och utspridd repetition stöder mer än att bara memorera fristående ordlistor.")
 (:institutions-benefit-4 . "Lärarnära stöd från någon som lyssnar noga och bryr sig om behoven i klassrummet.")
 (:institutions-request-title . "Låt oss prata")
 (:institutions-request-subtitle . "Berätta om er institution, era språk och vilken undervisningsstöd ni behöver. Vi återkommer inom 2 arbetsdagar.")
 (:institutions-field-name . "Institutionsnamn")
 (:institutions-field-name-placeholder . "Helsingfors universitet")
 (:institutions-field-contact-name . "Kontaktperson")
 (:institutions-field-contact-name-placeholder . "Ditt namn")
 (:institutions-field-contact-email . "Kontakt-e-post")
 (:institutions-field-contact-email-placeholder . "du@universitet.se")
 (:institutions-field-domains . "E-postdomäner")
 (:institutions-field-domains-placeholder . "universitet.se, cs.universitet.se")
 (:institutions-field-domains-help . "Kommaseparerad lista över e-postdomäner för din institution")
 (:institutions-field-notes . "Ytterligare information")
 (:institutions-field-notes-placeholder . "Uppskattat antal studenter, föredragen faktureringscykel, särskilda krav...")
 (:institutions-submit . "Skicka förfrågan")
 (:institutions-success-title . "Tack - Hiisi för skolor och universitet")
 (:institutions-success-heading . "Tack!")
 (:institutions-success-body . "Vi har tagit emot er förfrågan. Vi går igenom institutionens behov och återkommer inom 2 arbetsdagar.")
 (:institutions-success-back . "Tillbaka till startsidan")

 ;; Footer
 (:footer-privacy . "Integritetspolicy")
 (:footer-terms . "Användarvillkor")
 (:footer-contact . "Kontakt")

 ;; Early software notice
 (:early-software-notice . "Hiisi är under tidig utveckling. Hittat en bugg eller har du ett förslag?")
 (:early-software-contact . "Kontakta oss på")

 ;; Integritetspolicy
 (:privacy-title . "Integritetspolicy")
 (:privacy-updated . "Senast uppdaterad: januari 2026")
 (:privacy-who-title . "Vilka vi är")
 (:privacy-who-body . "Hiisi drivs av Lambda Symbolics OÜ, ett företag registrerat i Estland. Som estniskt företag följer vi EU:s allmänna dataskyddsförordning (GDPR).")
 (:privacy-collect-title . "Data vi samlar in")
 (:privacy-collect-intro . "När du använder Hiisi samlar vi in följande information:")
 (:privacy-collect-account-key . "Kontoinformation: ")
 (:privacy-collect-account-val . "E-postadress, visningsnamn och ett säkert hashat lösenord.")
 (:privacy-collect-learning-key . "Inlärningsdata: ")
 (:privacy-collect-learning-val . "Dina översättningar, sparade flashkort och din repetitionshistorik.")
 (:privacy-collect-usage-key . "Användningsdata: ")
 (:privacy-collect-usage-val . "Grundläggande serverloggar för säkerhet och felsökning.")
 (:privacy-use-title . "Hur vi använder dina data")
 (:privacy-use-auth-key . "Autentisering: ")
 (:privacy-use-auth-val . "För att verifiera din identitet och skydda ditt konto.")
 (:privacy-use-service-key . "Tjänsteleverans: ")
 (:privacy-use-service-val . "För att tillhandahålla översättningar och hantera din flashkortsamling.")
 (:privacy-use-ai-key . "AI-översättningar: ")
 (:privacy-use-ai-val . "Dina översättningsförfrågningar skickas till Anthropics Claude API för att generera svar. Se Anthropics integritetspolicy för hur de hanterar dessa data.")
 (:privacy-third-title . "Tredjepartstjänster")
 (:privacy-third-intro . "Vi använder följande tredjepartstjänster:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "För AI-drivna översättningar.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "För att skicka aktiveringsmail och transaktionsmail.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "För hantering av abonnemangsbetalningar.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "Vi använder endast nödvändiga cookies:")
 (:privacy-cookies-auth-key . "Autentiseringstoken: ")
 (:privacy-cookies-auth-val . "En säker HTTP-only cookie som håller dig inloggad.")
 (:privacy-cookies-lang-key . "Språkinställning: ")
 (:privacy-cookies-lang-val . "För att komma ihåg ditt föredragna gränssnittsspråk.")
 (:privacy-retention-title . "Lagring av data")
 (:privacy-retention-body . "Dina data lagras så länge du har ett konto. När du begär radering schemaläggs ditt konto för radering om 14 dagar.")
 (:privacy-rights-title . "Dina rättigheter (GDPR)")
 (:privacy-rights-intro . "Enligt GDPR har du rätt att:")
 (:privacy-rights-access . "Få tillgång till dina personuppgifter")
 (:privacy-rights-export . "Exportera dina data (tillgängligt på /app/api/export)")
 (:privacy-rights-correct . "Begära rättelse av felaktiga uppgifter")
 (:privacy-rights-delete . "Begära radering av ditt konto och dina data")
 (:privacy-rights-object . "Invända mot behandling av dina data")
 (:privacy-rights-contact . "För att utöva dessa rättigheter, kontakta oss på")
 (:privacy-contact-title . "Kontakt")
 (:privacy-contact-intro . "För frågor om integritet:")
 (:privacy-contact-email-label . "E-post: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Estland")

 ;; Användarvillkor
 (:terms-title . "Användarvillkor")
 (:terms-updated . "Senast uppdaterade: januari 2026")
 (:terms-1-title . "1. Tjänstebeskrivning")
 (:terms-1-body . "Hiisi är en språkinlärningsapp som erbjuder AI-drivna översättningar med grammatiska förklaringar och flashkort med distribuerad repetition. Tjänsten drivs av Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Kontoregistrering")
 (:terms-2-body . "För att använda Hiisi måste du skapa ett konto med en giltig e-postadress. Du ansvarar för säkerheten för dina kontouppgifter.")
 (:terms-3-title . "3. Abonnemang och betalningar")
 (:terms-3-body . "Hiisi erbjuder betalda abonnemang (månadsvis och årsvis). Abonnemang hanteras via Polar.sh.")
 (:terms-3-list-1 . "Abonnemang förnyas automatiskt om de inte sägs upp före förnyelsedatumet.")
 (:terms-3-list-2 . "Återbetalning ges i enlighet med tillämpliga konsumentskyddslagar.")
 (:terms-3-list-3 . "Utebliven betalning leder till förlorad tillgång till premiumfunktioner.")
 (:terms-4-title . "4. Tillåten användning")
 (:terms-4-intro . "Du samtycker till att inte:")
 (:terms-4-list-1 . "Använda tjänsten för olagliga ändamål")
 (:terms-4-list-2 . "Försöka kringgå användningsgränser eller säkerhetsåtgärder")
 (:terms-4-list-3 . "Dela dina kontouppgifter med andra")
 (:terms-4-list-4 . "Använda automatiserade verktyg på ett sätt som försämrar tjänstens prestanda för andra")
 (:terms-5-title . "5. Innehåll och immateriella rättigheter")
 (:terms-5-body-1 . "Översättningar som genereras av Hiisi skapas med AI och är kanske inte unika. Du får använda dina översättningar och flashkort för personliga ändamål, men du har inte exklusiv upphovsrätt till AI-genererat innehåll.")
 (:terms-5-body-2 . "Hiisi-applikationen, varumärket och originalinnehållet förblir Lambda Symbolics OÜ:s egendom.")
 (:terms-6-title . "6. Tjänstens tillgänglighet")
 (:terms-6-intro . "Hiisi tillhandahålls i befintligt skick. Vi garanterar inte:")
 (:terms-6-list-1 . "Oavbruten eller felfri tjänst")
 (:terms-6-list-2 . "Noggrannhet i AI-genererade översättningar")
 (:terms-6-list-3 . "Tillgång till specifika funktioner")
 (:terms-6-body . "Vi kan ändra eller avveckla funktioner när som helst.")
 (:terms-7-title . "7. Ansvarsbegränsning")
 (:terms-7-body-1 . "I den utsträckning lagen tillåter ansvarar Lambda Symbolics OÜ inte för indirekta, tillfälliga, särskilda eller följdskador som uppstår genom din användning av Hiisi.")
 (:terms-7-body-2 . "Vårt totala ansvar överstiger inte det belopp du har betalat för tjänsten under de 12 månader som föregår kravet.")
 (:terms-8-title . "8. Uppsägning av konto")
 (:terms-8-body-1 . "Vi kan stänga av eller avsluta ditt konto om du bryter mot dessa villkor. Du kan när som helst begära radering av konto i applikationen.")
 (:terms-8-body-2 . "Vid begäran om radering schemaläggs ditt konto för radering om 14 dagar.")
 (:terms-9-title . "9. Ändringar av villkor")
 (:terms-9-body . "Vi kan uppdatera dessa villkor då och då. Fortsatt användning av Hiisi efter ändringar innebär att du accepterar de nya villkoren.")
 (:terms-10-title . "10. Tillämplig lag")
 (:terms-10-body . "Dessa villkor regleras av estnisk lag. Eventuella tvister ska avgöras av domstolar i Estland.")
 (:terms-contact-title . "Kontakt")
 (:terms-contact-intro . "För frågor om dessa villkor:")
 (:terms-contact-email-label . "E-post: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Estland")



 ;; Decks
 (:decks-title . "Kortlekar")
 (:decks-subtitle . "Skapa egna kortlekar och dela dem med andra.")
 (:decks-create-title . "Skapa kortlek")
 (:decks-name-placeholder . "Kortlekens namn")
 (:decks-desc-placeholder . "Beskrivning")
 (:decks-create-btn . "Skapa kortlek")
 (:decks-edit-title . "Redigera kortlek")
 (:decks-edit-btn . "Redigera kortlek")
 (:decks-update-btn . "Spara ändringar")
 (:decks-default-badge . "Automatisk")
 (:decks-default-description . "Den här kortleken hanteras automatiskt för det här språkparet.")
 (:decks-default-readonly . "Automatiska kortlekar har fasta namn och beskrivningar.")
 (:decks-error-name-required . "Kortlekens namn är obligatoriskt.")
 (:decks-error-name-too-long . "Kortlekens namn får vara högst ~A tecken långt.")
 (:decks-error-desc-too-long . "Kortlekens beskrivning får vara högst ~A tecken lång.")
 (:decks-error-default-readonly . "Automatiska kortlekar kan inte redigeras.")
 (:decks-your-title . "Dina kortlekar")
 (:decks-col-name . "Namn")
 (:decks-col-desc . "Beskrivning")
 (:decks-col-updated . "Uppdaterad")
 (:decks-col-actions . "Åtgärder")
 (:decks-no-decks . "Inga kortlekar ännu.")
 (:decks-open-btn . "Öppna")
 (:decks-no-desc . "Ingen beskrivning.")
 (:decks-share-title . "Delningslänk")
 (:decks-share-info . "Alla med denna länk kan importera kortleken:")
 (:decks-share-copy . "Kopiera länk")
 (:decks-share-copied . "Kopierad")
 (:decks-add-from-flashcards-title . "Lägg till översättningar")
 (:decks-add-from-flashcards-info . "Välj ett kort för att lägga till dess översättning i den här kortleken.")
 (:decks-open-flashcards . "Lägg till från kort")
 (:decks-filter-from . "Källspråk")
 (:decks-filter-to . "Målspråk")
 (:decks-filter-any . "Alla språk")
 (:decks-filter-include-assigned . "Inkludera kort som redan finns i en kortlek")
 (:decks-flashcards-col-from . "Från")
 (:decks-flashcards-col-to . "Till")
 (:decks-flashcards-add . "Lägg till")
 (:decks-flashcards-added . "Tillagt")
 (:decks-flashcards-in-deck . "I en annan kortlek")
 (:decks-flashcards-empty . "Inga kort matchar dessa filter.")
 (:decks-add-trans-title . "Lägg till översättning")
 (:decks-trans-id-placeholder . "Översättnings-ID")
 (:decks-add-trans-btn . "Lägg till översättning")
 (:decks-items-title . "Kortlekens innehåll")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Översättning")
 (:decks-col-lang . "Målspråk")
 (:decks-no-items . "Inga objekt ännu.")
 (:decks-share-page-title . "Dela kortlek")
 (:decks-share-preview . "Förhandsgranska och importera denna kortlek.")
 (:decks-import-title . "Importera")
 (:decks-import-btn . "Importera kortlek")

 ;; Flashcards management page
 (:flashcards-title . "Mina kort")
 (:flashcards-subtitle . "Alla dina sparade kort på ett ställe. Sök, organisera och hantera.")
 (:flashcards-search-placeholder . "Sök kort...")
 (:flashcards-hide-perfected . "Dölj fullständigt inlärda kort")
 (:flashcards-col-original . "Original")
 (:flashcards-col-translated . "Översättning")
 (:flashcards-col-lang . "Språk")
 (:flashcards-no-cards . "Inga kort ännu. Börja översätta för att skapa några!")

 ;; API errors
 (:api-error-missing-text . "Text att översätta saknas.")
 (:api-error-invalid-translation-id . "Ogiltigt översättnings-ID.")
 (:api-error-translation-not-found . "Översättningen du försökte spara finns inte längre.")
 (:api-error-invalid-bookmark-id . "Ogiltigt bokmärkes-ID")
 (:api-error-bookmark-not-found . "Bokmärke hittades inte")
 (:api-error-forbidden . "Förbjudet")
 (:api-error-failed-delete-bookmark . "Det gick inte att ta bort bokmärket")
 (:api-error-invalid-flashcard-id . "Ogiltigt kort-ID")
 (:api-error-missing-deck-id . "Kortleks-ID saknas")
 (:api-error-flashcard-not-found . "Kort hittades inte")
 (:api-error-deck-not-found . "Kortlek hittades inte")
 (:api-error-deck-name-required . "Kortleksnamn krävs")
 (:api-error-session-expired . "Din repetitionssession har gått ut. Starta en ny session.")
 (:api-error-invalid-card-id . "Ogiltigt kort-ID.")
 (:api-error-invalid-rating . "Ogiltigt betyg.")
 (:api-error-rating-range . "Betyg måste vara mellan 0 och 5.")
 (:api-error-card-not-found . "Kort hittades inte.")
 (:api-error-permission-denied . "Du har inte behörighet att repetera detta kort.")
 (:api-error-unknown-source-lang . "Okänt källspråk.")
 (:api-error-unknown-target-lang . "Okänt målspråk.")
 (:api-error-failed-add-to-deck . "Det gick inte att lägga till i kortlek")

 ;; API success messages
 (:api-success-added . "Tillagt!")
 (:api-success-added-simple . "Tillagt")

 ;; API stats
 (:api-stats-due . "~A förfaller")
 (:api-stats-total . "~A totalt")

 ;; Time units
 (:api-time-day . "dag")
 (:api-time-days . "dagar")
 (:api-time-day-left . "dag kvar")
 (:api-time-days-left . "dagar kvar")

 ;; Subscription status
 (:api-subscription-active . "Aktiv")
 (:api-subscription-inactive . "Inaktiv")
 (:api-subscription-subscribe-hint . "Prenumerera för att låsa upp översättningar")

 ;; Generic status
 (:status-bad-request . "Felaktig begäran")
 (:status-not-found . "Hittades inte")
 (:status-forbidden . "Förbjudet")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Lär dig språk på djupet")
 (:landing-hero-subheadline . "Få översättningar med fullständig grammatikanalys och bygg ett varaktigt ordförråd med flashkort och distribuerad repetition.")
 (:landing-hero-trust-line . "7 dagars gratis provperiod med 100 översättningar. Avsluta när som helst.")
 (:landing-credibility-languages . "14 språk")
 (:landing-credibility-ai . "Grammatikanalys inkluderad")
 (:landing-credibility-origin . "Byggt i Estland")
 (:landing-step-1-title . "Översätt vilken text som helst")
 (:landing-step-1-desc . "Skriv in ett ord eller en fras. Få en översättning med fullständig grammatikanalys.")
 (:landing-step-2-title . "Spara som flashkort")
 (:landing-step-2-desc . "Spara översättningar du vill minnas. Flashkort skapas automatiskt.")
 (:landing-step-3-title . "Repetera och minns")
 (:landing-step-3-desc . "Distribuerad repetition planerar genomgångar vid rätt tidpunkt för långtidsminnet.")
 (:landing-feature-grammar-title . "Förstå grammatik, inte bara ord")
 (:landing-feature-grammar-desc . "Varje översättning innehåller en detaljerad grammatikanalys - ordformer, kasus och böjningar förklarade på ditt språk.")
 (:landing-feature-srs-title . "Vetenskapligt stödd memorering")
 (:landing-feature-srs-desc . "SM-2-algoritmen anpassar sig efter din prestation. Svåra kort visas oftare. Kort du kan visas mer sällan.")
 (:landing-feature-share-title . "Dela kortlekar med elever")
 (:landing-feature-share-desc . "Lärare kan skapa egna kortlekar och dela dem med en länk. Elever importerar kortleken och börjar repetera direkt.")
 (:landing-pricing-trial-note . "Inkluderar 7 dagars gratis provperiod")
 (:landing-pricing-monthly-after . "7 dagar gratis, sedan ~A/månad")
 (:landing-pricing-annual-after . "7 dagar gratis, sedan ~A/år")
 (:landing-faq-title . "Vanliga frågor")
 (:landing-faq-trial-cap-q . "Hur många översättningar får jag under provperioden?")
 (:landing-faq-trial-cap-a . "Du får 100 översättningar under din 7-dagars provperiod. Efter prenumeration får du 600 per månad.")
 (:landing-final-cta-title . "Börja lära dig i dag")
 (:landing-final-cta-subtitle . "Gå med i Hiisi och börja bygga ordförråd som håller.")

 ;; Trial status (in-app)
 (:trial-status . "Gratis provperiod")
 (:trial-days-remaining . "~A dagar kvar")
 (:trial-translations-used . "~A/100 översättningar använda")
 (:trial-upgrade-prompt . "Uppgradera för att fortsätta översätta")
 (:trial-expired . "Din gratis provperiod har gått ut")
 (:trial-expired-detail . "Prenumerera för att fortsätta lära med Hiisi.")
 (:trial-quota-warning . "~A provöversättningar kvar (~A dagar). Prenumerera för 600/månad.")
 (:trial-quota-exceeded . "Gräns för provöversättningar nådd. Prenumerera för att fortsätta.")
 (:error-trial-quota-exceeded . "Gräns för provöversättningar nådd")
 (:error-trial-quota-detail . "Du har använt alla 100 provöversättningar. Prenumerera för att fortsätta lära.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Skapa flashkort")
 (:custom-flashcard-edit-title . "Redigera flashkort")
 (:custom-flashcard-original . "Originaltext")
 (:custom-flashcard-translated . "Översättning")
 (:custom-flashcard-lang-from . "Källspråk")
 (:custom-flashcard-lang-to . "Målspråk")
 (:custom-flashcard-note . "Pedagogisk anteckning")
 (:custom-flashcard-forms . "Grammatikanalys")
 (:custom-flashcard-form-term . "Term")
 (:custom-flashcard-form-explanation . "Förklaring")
 (:custom-flashcard-add-form . "Lägg till grammatikterm")
 (:custom-flashcard-remove-form . "Ta bort")
 (:custom-flashcard-ai-fill . "Fyll i med AI")
 (:custom-flashcard-ai-fill-all . "Fyll i allt med AI")
 (:custom-flashcard-ai-fill-translation . "Översätt med AI")
 (:custom-flashcard-ai-fill-breakdown . "Generera analys")
 (:custom-flashcard-ai-fill-note . "Generera anteckning")
 (:custom-flashcard-create-btn . "Skapa flashkort")
 (:custom-flashcard-update-btn . "Spara ändringar")
 (:custom-flashcard-delete-btn . "Ta bort flashkort")
 (:custom-flashcard-delete-confirm . "Är du säker på att du vill ta bort detta flashkort?")
 (:custom-flashcard-created . "Flashkort skapat")
 (:custom-flashcard-updated . "Flashkort uppdaterat")
 (:custom-flashcard-deleted . "Flashkort borttaget")
 (:custom-flashcard-add-to-deck . "Lägg till i kortlek")
 (:custom-flashcard-not-found . "Flashkort hittades inte")
 (:custom-flashcard-not-owner . "Du kan bara redigera flashkort du har skapat")
 (:custom-flashcard-ai-generating . "Genererar med AI...")
 (:custom-flashcard-badge . "Eget")

 ;; Problemrapportering
 (:issues-open-button . "Rapportera ett problem")
 (:issues-modal-title . "Rapportera ett problem")
 (:issues-modal-subtitle . "Beskriv vad som gick fel. Vi lägger automatiskt till sidan du är på.")
 (:issues-title-label . "Kort titel")
 (:issues-title-placeholder . "Kort sammanfattning av problemet")
 (:issues-message-label . "Vad hände?")
 (:issues-message-placeholder . "Ange steg för att återskapa, förväntat beteende och vad som hände i stället.")
 (:issues-submit . "Skicka rapport")
 (:issues-cancel . "Avbryt")
 (:issues-success . "Tack. Din problemrapport har skickats.")
 (:issues-error-required . "Beskriv problemet innan du skickar.")
 (:issues-error-title-too-long . "Ärendets titel är för lång. Håll den under 160 tecken.")
 (:issues-error-too-long . "Rapporttexten är för lång. Håll den under 4000 tecken.")
 (:issues-error-rate-limit . "För många rapporter från denna källa. Vänta och försök igen senare.")
 (:issues-error-generic . "Problemrapporten kunde inte skickas. Försök igen.")

)
