;;; Swedish translations

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Svenska")
 (:lang-flag . "🇸🇪")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Välj ditt språk")
 (:lang-modal-subtitle . "Välj ditt föredragna språk för gränssnittet:")

 ;; Navigation
 (:nav-translate . "Översätt")
 (:nav-review . "Repetera")
 (:nav-flashcards . "Mina kort")
 (:nav-dashboard . "Översikt")
 (:nav-decks . "Decks")
 (:nav-logout . "Logga ut")
 (:nav-home . "Hem")
 (:nav-pricing . "Priser")
 (:nav-export-data . "Exportera data")

 ;; App title and branding
 (:app-title . "Hiisi")
 (:app-tagline . "Lär dig språk genom översättningar")

 ;; Landing page
 (:landing-hero-title . "Bemästra vilket språk som helst")
 (:landing-hero-subtitle . "Översätt vad som helst. Generera automatiskt flashcards som lär dig varför det fungerar så.")
 (:landing-cta . "Börja lära dig")
 (:landing-learn-more . "Läs mer")
 (:landing-how-it-works . "Så fungerar det")
 (:landing-feature-1-title . "Automatiska flashcards")
 (:landing-feature-1-desc . "Varje översättning genererar automatiskt flashcards med grammatikförklaringar. Inget manuellt kortskapande.")
 (:landing-feature-2-title . "Spaced repetition")
 (:landing-feature-2-desc . "SM-2-algoritmen schemalägger repetitioner vid optimala intervall. Lär dig effektivt, kom ihåg permanent.")
 (:landing-feature-3-title . "Grammatikundervisning")
 (:landing-feature-3-desc . "Varje översättning förklarar grammatik, ordstammar och meningsstruktur. Förstå varför, inte bara vad.")
 (:landing-free-trial . "7 dagars gratis provperiod. Inget kreditkort krävs.")
 (:landing-start-trial . "Starta gratis provperiod")
 (:landing-best-value . "Bäst värde")
 (:landing-cta-title . "Redo att lära dig språk genom grammatik, inte utantillärning?")
 (:landing-cta-subtitle . "Varje översättning blir ett lärtillfälle. Varje flashcard lär dig varför.")
 (:landing-signup-free . "Registrera dig gratis")

 ;; Auth pages
 (:auth-register . "Registrera")
 (:auth-login . "Logga in")
 (:auth-logout . "Logga ut")
 (:auth-email . "E-post")
 (:auth-password . "Lösenord")
 (:auth-password-again . "Bekräfta lösenord")
 (:auth-display-name . "Visningsnamn")
 (:auth-register-title . "Registrera dig på Hiisi")
 (:auth-register-subtitle . "Skapa ett nytt konto")
 (:auth-login-title . "Logga in på Hiisi")
 (:auth-login-subtitle . "Ange dina uppgifter")
 (:auth-forgot-password . "Glömt lösenordet?")
 (:auth-no-account . "Har du inget konto?")
 (:auth-have-account . "Har du redan ett konto?")
 (:auth-google . "Fortsätt med Google")
 (:auth-account-created . "Konto skapat!")
 (:auth-check-email . "Kontrollera din e-post för aktiveringslänken.")
 (:auth-redirect-login . "Omdirigerar till inloggning om")
 (:auth-seconds . "sekunder")
 (:auth-go-now . "Gå nu")
 (:auth-not-activated . "Kontot är inte aktiverat. Kontrollera din e-post för aktiveringslänken.")
 (:auth-activate-title . "Aktivera ditt konto")
 (:auth-activated . "Konto aktiverat!")
 (:auth-activated-message . "Ditt konto har aktiverats. Du kan nu använda Hiisi.")
 (:auth-redirecting . "Omdirigerar om")
 (:auth-go-to-app . "Gå till appen")
 (:auth-resend-title . "Skicka aktiveringsmail igen")
 (:auth-resend-subtitle . "Ange din e-postadress för att få en ny aktiveringslänk.")
 (:auth-resend-button . "Skicka aktiveringsmail igen")
 (:auth-resend-success . "Aktiveringsmail skickat!")
 (:auth-resend-success-detail . "Kontrollera din inkorg för den nya aktiveringslänken.")
 (:auth-resend-rate-limited . "Vänta några minuter innan du begär ett nytt aktiveringsmail.")
 (:auth-resend-cooldown . "Du kan begära ett nytt mail om ~a sekunder.")
 (:auth-back-to-login . "Tillbaka till inloggning")
 (:auth-forgot-password-title . "Glömt lösenord")
 (:auth-forgot-password-subtitle . "Ange din e-postadress så skickar vi dig en länk för att återställa ditt lösenord.")
 (:auth-send-reset-link . "Skicka återställningslänk")
 (:auth-reset-email-sent . "Länk skickad!")
 (:auth-reset-email-sent-detail . "Om ett konto finns med den e-postadressen kommer du snart att få en länk för att återställa lösenordet.")
 (:auth-reset-rate-limited . "Vänta några minuter innan du begär en ny lösenordsåterställning.")
 (:auth-reset-invalid-token . "Denna återställningslänk är ogiltig eller har upphört.")
 (:auth-reset-password-title . "Återställ lösenord")
 (:auth-reset-password-subtitle . "Ange ditt nya lösenord nedan.")
 (:auth-new-password . "Nytt lösenord")
 (:auth-confirm-new-password . "Bekräfta nytt lösenord")
 (:auth-reset-password . "Återställ lösenord")
 (:auth-password-changed . "Lösenord ändrat!")
 (:auth-password-changed-detail . "Ditt lösenord har ändrats. Du kan nu logga in med ditt nya lösenord.")
 (:auth-change-password-title . "Ändra lösenord")
 (:auth-change-password-subtitle . "Uppdatera ditt kontolösenord.")
 (:auth-current-password . "Nuvarande lösenord")
 (:auth-change-password . "Ändra lösenord")
 (:auth-back-to-app . "Tillbaka till appen")
 (:auth-password-updated . "Lösenord uppdaterat!")
 (:auth-password-updated-detail . "Ditt lösenord har uppdaterats.")

 ;; Translation page
 (:translate-title . "Översätt")
 (:translate-input-label . "Text att översätta")
 (:translate-input-placeholder . "Skriv text att översätta...")
 (:translate-from . "Från:")
 (:translate-to . "Till:")
 (:translate-submit . "Översätt")
 (:translate-save . "Spara som flashcard")
 (:translate-saved . "Sparat!")
 (:translate-like . "Gilla")
 (:translate-dislike . "Ogilla")
 (:translate-char-limit . "tecken kvar")
 (:translate-auto-detect . "Valfritt (Identifiera automatiskt)")
 (:translate-empty-state . "Skriv text ovan och klicka Översätt för att se resultatet med grammatikförklaring")
 (:translate-select-deck-placeholder . "Välj kortlek (valfritt)")
 (:translate-new-deck . "Ny kortlek")
 (:translate-add-to-deck . "Lägg till i kortlek")
 (:translate-bookmark . "Spara")
 (:translate-bookmarked . "Sparat")
 (:translate-retry . "Försök igen")
 (:translate-like-tooltip . "Bra översättning")
 (:translate-dislike-tooltip . "Dålig översättning - begär en ny")
 (:translate-dislike-confirm . "Detta genererar en ny översättning. Fortsätta?")
 (:translate-liked . "Gillar!")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Mål")
 (:translate-deck-create-title . "Skapa ny kortlek")
 (:translate-deck-name-label . "Kortlekens namn")
 (:translate-deck-name-placeholder . "t.ex. Finska grunder")
 (:translate-deck-description-label . "Beskrivning (valfri)")
 (:translate-deck-cancel . "Avbryt")
 (:translate-deck-create . "Skapa")
 (:translate-rate-label . "Betygsätt översättning")
 (:flashcards-delete-confirm . "Är du säker på att du vill ta bort det här kortet?")
 (:flashcards-deck-search-placeholder . "Sök kortlekar...")
 (:flashcards-no-decks . "Inga kortlekar ännu. Skapa en först!")
 (:flashcards-deck-cancel . "Avbryt")

 ;; Flashcard review
 (:review-title . "Repetera")
 (:review-session-title . "Repetitionssession")
 (:review-session-subtitle . "Öva på dina sparade flashcards")
 (:review-start . "Starta repetition")
 (:review-no-cards . "Inga kort att repetera")
 (:review-no-cards-desc . "Du har inga flashcards som behöver repeteras just nu.")
 (:review-no-cards-hint . "Översätt lite text och klicka \"Spara som flashcard\" för att bygga din kortlek!")
 (:review-start-translating . "Börja översätta")
 (:review-show-answer . "Visa svar")
 (:review-click-reveal . "Klicka för att visa svaret")
 (:review-grammar-breakdown . "Grammatikförklaring")
 (:review-how-well . "Hur väl kom du ihåg?")
 (:review-again . "Igen")
 (:review-hard . "Svårt")
 (:review-good . "Bra")
 (:review-easy . "Lätt")
 (:review-progress . "Kort ~a av ~a")
 (:review-complete . "Session klar!")
 (:review-complete-msg . "Du repeterade ~a kort")
 (:review-correct . "Rätt")
 (:review-accuracy . "Träffsäkerhet")
 (:review-again-btn . "Repetera igen")
 (:review-translate-more . "Översätt mer")
 (:review-streak . "dagar i rad")

 ;; Dashboard
 (:dashboard-title . "Översikt")
 (:dashboard-cards-due . "Kort för idag")
 (:dashboard-total-cards . "Totalt antal kort")
 (:dashboard-subscription . "Prenumeration")
 (:dashboard-subscribed-until . "Prenumererar till")
 (:dashboard-not-subscribed . "Ingen prenumeration")
 (:dashboard-recent . "Senaste översättningar")
 (:dashboard-no-translations . "Inga översättningar än")
 (:dashboard-streak . "Nuvarande svit")
 (:dashboard-days . "dagar")
 (:dashboard-quick-actions . "Snabbåtgärder")
 (:dashboard-getting-started . "Kom igång")
 (:dashboard-tip-1 . "Översätt text du vill lära dig")
 (:dashboard-tip-2 . "Klicka \"Spara som flashcard\" på översättningar du vill komma ihåg")
 (:dashboard-tip-3 . "Repetera dina flashcards regelbundet - spaced repetition hjälper dig minnas långsiktigt")
 (:dashboard-tip-4 . "Bedöm ärligt - det hjälper algoritmen schemalägga dina repetitioner optimalt")

 ;; Account
 (:account-title . "Konto")
 (:account-subtitle . "Hantera dina kontoinställningar och raderingsschema.")
 (:account-deletion-title . "Kontoradering")
 (:account-deletion-scheduled . "Ditt konto är planerat att raderas den ~A.")
 (:account-deletion-cancel-hint . "Du kan avbryta före detta datum för att behålla kontot.")
 (:account-deletion-cancel . "Avbryt radering")
 (:account-deletion-request . "Du kan begära att kontot raderas när som helst. Radering planeras 14 dagar efter bekräftelse. Om du ångrar dig efter radering, kontakta support.")
 (:account-deletion-confirm . "Planera kontoradering om 14 dagar från i dag?")
 (:account-deletion-schedule . "Planera radering")
 (:account-reminders-title . "E-postpåminnelser")
 (:account-reminders-subtitle . "Hantera påminnelser om repetition och fortsättning för detta konto.")
 (:account-reminders-opt-out . "Stäng av påminnelser om repetition och fortsättning")
 (:account-reminders-save . "Spara inställningar")

 ;; Subscription
 (:subscribe-title . "Enkla priser")
 (:subscribe-monthly . "Månadsvis")
 (:subscribe-annual . "Årsvis")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-monthly-desc . "600 översättningar per månad")
 (:subscribe-annual-desc . "Spara €20 — två månader gratis!")
 (:subscribe-cta . "Prenumerera")
 (:subscribe-success . "Prenumeration lyckades!")
 (:subscribe-manage . "Hantera prenumeration")
 (:subscribe-choose-plan . "Välj din plan")
 (:subscribe-start-today . "Börja lära dig idag")
 (:subscribe-per-month . "per månad")
 (:subscribe-per-year . "per år")
 (:subscribe-unlimited-flashcards . "Obegränsade flashcards")
 (:subscribe-grammar-explanations . "Grammatikförklaringar")
 (:subscribe-spaced-repetition . "Spaced repetition-schemaläggning")
 (:subscribe-activated . "Prenumeration aktiverad!")
 (:subscribe-thank-you . "Tack för din prenumeration!")
 (:subscribe-start-learning . "Börja lära dig")
 (:subscribe-management . "Hantera prenumeration")
 (:subscribe-active . "Aktiv")
 (:subscribe-status . "Prenumerationsstatus")
 (:subscribe-status-active . "Din prenumeration är aktiv")
 (:subscribe-days-remaining . "dagar kvar")
 (:subscribe-renews-on . "Förnyas den")
 (:subscribe-no-subscription . "Ingen aktiv prenumeration")
 (:subscribe-access-features . "Prenumerera för att få tillgång till alla funktioner")
 (:subscribe-view-plans . "Visa planer")
 (:subscribe-faq-title . "Vanliga frågor")
 (:subscribe-faq-trial-q . "Finns det en gratis provperiod?")
 (:subscribe-faq-trial-a . "Ja! Du får 7 dagars gratis provperiod när du registrerar dig.")
 (:subscribe-faq-cancel-q . "Kan jag avbryta när som helst?")
 (:subscribe-faq-cancel-a . "Ja, du kan avbryta din prenumeration när som helst. Du behåller tillgång till slutet av faktureringsperioden.")
 (:subscribe-faq-payment-q . "Vilka betalningsmetoder accepteras?")
 (:subscribe-faq-payment-a . "Vi accepterar alla större kreditkort och PayPal.")
 (:subscribe-copyright . "© 2025 Hiisi. Alla rättigheter förbehållna.")

 ;; Errors and status
 (:error-generic . "Något gick fel")
 (:error-not-found . "Sidan hittades inte")
 (:error-unauthorized . "Logga in för att fortsätta")
 (:error-subscription-required . "Prenumeration krävs")
 (:error-text-too-long . "Texten är för lång. Maximal översättningslängd är 120 tecken.")
 (:error-input-too-long . "Inmatningen är för lång")
 (:error-unknown-source-lang . "Källspråket du valde stöds inte.")
 (:error-unknown-target-lang . "Målspråket du valde stöds inte.")
 (:error-unknown-language . "Okänt språk")
 (:error-translation-unavailable . "Översättningstjänsten är tillfälligt otillgänglig. Försök igen om en stund.")
 (:error-translation-failed . "Översättningen misslyckades")
 (:error-translation-retry . "Kunde inte generera en översättning efter flera försök. Försök omformulera din text.")
 (:error-quota-exceeded . "Översättningsgräns nådd")
 (:error-quota-exceeded-detail . "Du har använt alla dina översättningar för denna månad. Din kvot återställs automatiskt varje månad.")
 (:quota-warning . "Återstående översättningar: ~A")
 (:quota-low-warning . "Endast ~A översättningar kvar. Överväg att köpa fler.")
 (:top-up-button . "Köp fler översättningar")
 (:top-up-success . "Påfyllning lyckades! Du har nu ~A ytterligare översättningar.")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 översättningar")
 (:loading . "Laddar...")
 (:empty-state . "Inget här än")

 ;; Institutions
 (:institutions-page-title . "Hiisi för skolor - institutionslicenser")
 (:institutions-hero-title . "Hiisi för skolor")
 (:institutions-hero-subtitle . "Ge dina studenter AI-stödd språkinlärning")
 (:institutions-section-title . "Institutionslicenser")
 (:institutions-section-body . "Vi erbjuder volymlicenser för skolor, universitet och språkinstitutioner. Studenter med e-postadresser från din domän får automatiskt full åtkomst.")
 (:institutions-benefit-1 . "Automatisk registrering för studenter med institutionell e-post")
 (:institutions-benefit-2 . "Inga enskilda studentkonton att hantera")
 (:institutions-benefit-3 . "Flexibla faktureringsalternativ")
 (:institutions-benefit-4 . "Dedikerat stöd för lärare")
 (:institutions-request-title . "Begär en licens")
 (:institutions-request-subtitle . "Fyll i formuläret nedan så återkommer vi inom 2 arbetsdagar.")
 (:institutions-field-name . "Institutionsnamn")
 (:institutions-field-name-placeholder . "Helsingfors universitet")
 (:institutions-field-contact-name . "Kontaktperson")
 (:institutions-field-contact-name-placeholder . "Ditt namn")
 (:institutions-field-contact-email . "Kontakt-e-post")
 (:institutions-field-contact-email-placeholder . "du@universitet.se")
 (:institutions-field-domains . "E-postdomäner")
 (:institutions-field-domains-placeholder . "universitet.se, cs.universitet.se")
 (:institutions-field-domains-help . "Kommaseparerad lista över e-postdomäner för din institution")
 (:institutions-field-notes . "Ytterligare information")
 (:institutions-field-notes-placeholder . "Uppskattat antal studenter, föredragen faktureringscykel, särskilda krav...")
 (:institutions-submit . "Skicka förfrågan")
 (:institutions-success-title . "Tack - Hiisi för skolor")
 (:institutions-success-heading . "Tack!")
 (:institutions-success-body . "Vi har tagit emot din förfrågan om en institutionslicens. Vårt team granskar den och återkommer inom 2 arbetsdagar.")
 (:institutions-success-back . "Tillbaka till startsidan")

 ;; Footer
 (:footer-privacy . "Integritetspolicy")
 (:footer-terms . "Användarvillkor")
 (:footer-contact . "Kontakt")

 ;; Early software notice
 (:early-software-notice . "Hiisi är under tidig utveckling. Hittat en bugg eller har du ett förslag?")
 (:early-software-contact . "Kontakta oss på")

 ;; Privacy Policy
 (:privacy-title . "Privacy Policy")
 (:privacy-updated . "Last updated: January 2026")
 (:privacy-who-title . "Who We Are")
 (:privacy-who-body . "Hiisi is operated by Lambda Symbolics OÜ, a company registered in Estonia. As an Estonian company, we comply with the European Union's General Data Protection Regulation (GDPR).")
 (:privacy-collect-title . "Data We Collect")
 (:privacy-collect-intro . "We collect the following information when you use Hiisi:")
 (:privacy-collect-account-key . "Account information: ")
 (:privacy-collect-account-val . "Email address, display name, and a securely hashed password.")
 (:privacy-collect-learning-key . "Learning data: ")
 (:privacy-collect-learning-val . "Your translations, saved flashcards, and review history.")
 (:privacy-collect-usage-key . "Usage data: ")
 (:privacy-collect-usage-val . "Basic server logs for security and debugging purposes.")
 (:privacy-use-title . "How We Use Your Data")
 (:privacy-use-auth-key . "Authentication: ")
 (:privacy-use-auth-val . "To verify your identity and secure your account.")
 (:privacy-use-service-key . "Service delivery: ")
 (:privacy-use-service-val . "To provide translations and manage your flashcard collection.")
 (:privacy-use-ai-key . "AI translations: ")
 (:privacy-use-ai-val . "Your translation requests are sent to Anthropic's Claude API to generate responses. See Anthropic's privacy policy for how they handle this data.")
 (:privacy-third-title . "Third-Party Services")
 (:privacy-third-intro . "We use the following third-party services:")
 (:privacy-third-anthropic-key . "Anthropic (Claude API): ")
 (:privacy-third-anthropic-val . "For AI-powered translations.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "For sending account activation and transactional emails.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "For subscription payment processing.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "We use only essential cookies:")
 (:privacy-cookies-auth-key . "Authentication token: ")
 (:privacy-cookies-auth-val . "A secure, HTTP-only cookie to keep you logged in.")
 (:privacy-cookies-lang-key . "Language preference: ")
 (:privacy-cookies-lang-val . "To remember your preferred UI language.")
 (:privacy-retention-title . "Data Retention")
 (:privacy-retention-body . "Your data is stored as long as you maintain an account. When you request deletion, your account is scheduled for deletion in 14 days.")
 (:privacy-rights-title . "Your Rights (GDPR)")
 (:privacy-rights-intro . "Under GDPR, you have the right to:")
 (:privacy-rights-access . "Access your personal data")
 (:privacy-rights-export . "Export your data (available at /app/api/export)")
 (:privacy-rights-correct . "Request correction of inaccurate data")
 (:privacy-rights-delete . "Request deletion of your account and data")
 (:privacy-rights-object . "Object to processing of your data")
 (:privacy-rights-contact . "To exercise these rights, contact us at")
 (:privacy-contact-title . "Contact")
 (:privacy-contact-intro . "For privacy-related inquiries:")
 (:privacy-contact-email-label . "Email: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Estonia")

 ;; Terms of Service
 (:terms-title . "Terms of Service")
 (:terms-updated . "Last updated: January 2026")
 (:terms-1-title . "1. Service Description")
 (:terms-1-body . "Hiisi is a language learning application that provides AI-powered translations with grammatical explanations and spaced repetition flashcards. The service is operated by Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Account Registration")
 (:terms-2-body . "To use Hiisi, you must create an account with a valid email address. You are responsible for maintaining the security of your account credentials.")
 (:terms-3-title . "3. Subscription and Payments")
 (:terms-3-body . "Hiisi offers paid subscription plans (monthly and annual). Subscriptions are processed through Polar.sh.")
 (:terms-3-list-1 . "Subscriptions auto-renew unless cancelled before the renewal date.")
 (:terms-3-list-2 . "Refunds are provided in accordance with applicable consumer protection laws.")
 (:terms-3-list-3 . "Non-payment results in loss of access to premium features.")
 (:terms-4-title . "4. Acceptable Use")
 (:terms-4-intro . "You agree not to:")
 (:terms-4-list-1 . "Use the service for any illegal purpose")
 (:terms-4-list-2 . "Attempt to circumvent usage limits or security measures")
 (:terms-4-list-3 . "Share your account credentials with others")
 (:terms-4-list-4 . "Use automated tools to access the service in a way that degrades performance for others")
 (:terms-5-title . "5. Content and Intellectual Property")
 (:terms-5-body-1 . "Translations generated by Hiisi are created using AI and may not be unique. You may use your translations and flashcards for any personal purpose, but you do not hold exclusive authorship rights over AI-generated content.")
 (:terms-5-body-2 . "The Hiisi application, branding, and original content remain the property of Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Service Availability")
 (:terms-6-intro . "Hiisi is provided on an \"as-is\" basis. We do not guarantee:")
 (:terms-6-list-1 . "Uninterrupted or error-free service")
 (:terms-6-list-2 . "Accuracy of AI-generated translations")
 (:terms-6-list-3 . "Availability of specific features")
 (:terms-6-body . "We may modify or discontinue features at any time.")
 (:terms-7-title . "7. Limitation of Liability")
 (:terms-7-body-1 . "To the maximum extent permitted by law, Lambda Symbolics OÜ shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of Hiisi.")
 (:terms-7-body-2 . "Our total liability shall not exceed the amount you paid for the service in the 12 months preceding the claim.")
 (:terms-8-title . "8. Account Termination")
 (:terms-8-body-1 . "We may suspend or terminate your account if you violate these terms. You may request account deletion at any time through the application.")
 (:terms-8-body-2 . "Upon deletion request, your account is scheduled for deletion in 14 days.")
 (:terms-9-title . "9. Changes to Terms")
 (:terms-9-body . "We may update these terms from time to time. Continued use of Hiisi after changes constitutes acceptance of the new terms.")
 (:terms-10-title . "10. Governing Law")
 (:terms-10-body . "These terms are governed by the laws of Estonia. Any disputes shall be resolved in the courts of Estonia.")
 (:terms-contact-title . "Contact")
 (:terms-contact-intro . "For questions about these terms:")
 (:terms-contact-email-label . "Email: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Estonia")



 ;; Decks
 (:decks-title . "Kortlekar")
 (:decks-subtitle . "Skapa egna kortlekar och dela dem med andra.")
 (:decks-create-title . "Skapa kortlek")
 (:decks-name-placeholder . "Kortlekens namn")
 (:decks-desc-placeholder . "Beskrivning")
 (:decks-create-btn . "Skapa kortlek")
 (:decks-your-title . "Dina kortlekar")
 (:decks-col-name . "Namn")
 (:decks-col-desc . "Beskrivning")
 (:decks-col-updated . "Uppdaterad")
 (:decks-col-actions . "Åtgärder")
 (:decks-no-decks . "Inga kortlekar ännu.")
 (:decks-open-btn . "Öppna")
 (:decks-no-desc . "Ingen beskrivning.")
 (:decks-share-title . "Delningslänk")
 (:decks-share-info . "Alla med denna länk kan importera kortleken:")
 (:decks-add-trans-title . "Lägg till översättning")
 (:decks-trans-id-placeholder . "Översättnings-ID")
 (:decks-add-trans-btn . "Lägg till översättning")
 (:decks-items-title . "Kortlekens innehåll")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Översättning")
 (:decks-col-lang . "Målspråk")
 (:decks-no-items . "Inga objekt ännu.")
 (:decks-share-page-title . "Dela kortlek")
 (:decks-share-preview . "Förhandsgranska och importera denna kortlek.")
 (:decks-import-title . "Importera")
 (:decks-import-btn . "Importera kortlek")

 ;; Flashcards management page
 (:flashcards-title . "Mina kort")
 (:flashcards-subtitle . "Alla dina sparade kort på ett ställe. Sök, organisera och hantera.")
 (:flashcards-search-placeholder . "Sök kort...")
 (:flashcards-col-original . "Original")
 (:flashcards-col-translated . "Översättning")
 (:flashcards-col-lang . "Språk")
 (:flashcards-no-cards . "Inga kort ännu. Börja översätta för att skapa några!")

)

 ;; API Errors (EN fallback)
 (:api-error-missing-text . "Missing text to translate.")
 (:api-error-invalid-translation-id . "Invalid translation ID.")
 (:api-error-translation-not-found . "The translation you tried to save no longer exists.")
 (:api-error-invalid-bookmark-id . "Invalid bookmark ID")
 (:api-error-bookmark-not-found . "Bookmark not found")
 (:api-error-forbidden . "Forbidden")
 (:api-error-failed-delete-bookmark . "Failed to delete bookmark")
 (:api-error-invalid-flashcard-id . "Invalid flashcard ID")
 (:api-error-missing-deck-id . "Missing deck_id")
 (:api-error-flashcard-not-found . "Flashcard not found")
 (:api-error-deck-not-found . "Deck not found")
 (:api-error-deck-name-required . "Deck name is required")
 (:api-error-session-expired . "Your review session has expired. Please start a new session.")
 (:api-error-invalid-card-id . "Invalid card ID.")
 (:api-error-invalid-rating . "Invalid rating.")
 (:api-error-rating-range . "Rating must be between 0 and 5.")
 (:api-error-card-not-found . "Card not found.")
 (:api-error-permission-denied . "You don't have permission to review this card.")
 (:api-error-unknown-source-lang . "Unknown source language.")
 (:api-error-unknown-target-lang . "Unknown target language.")
 (:api-error-failed-add-to-deck . "Failed to add to deck")

 ;; API Success messages
 (:api-success-added . "Added!")
 (:api-success-added-simple . "Added")

 ;; API Stats
 (:api-stats-due . "~A due")
 (:api-stats-total . "~A total")

 ;; Time units
 (:api-time-day . "day")
 (:api-time-days . "days")
 (:api-time-day-left . "day left")
 (:api-time-days-left . "days left")

 ;; Subscription status
 (:api-subscription-active . "Active")
 (:api-subscription-inactive . "Inactive")
 (:api-subscription-subscribe-hint . "Subscribe to unlock translations")

 ;; Generic status
 (:status-bad-request . "Bad Request")
 (:status-not-found . "Not Found")
 (:status-forbidden . "Forbidden")

)
