;;; Swedish translations

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Svenska")
 (:lang-flag . "🇸🇪")

 ;; Navigation
 (:nav-translate . "Översätt")
 (:nav-review . "Repetera")
 (:nav-dashboard . "Översikt")
 (:nav-logout . "Logga ut")
 (:nav-home . "Hem")
 (:nav-pricing . "Priser")
 (:nav-export-data . "Exportera data")

 ;; App title and branding
 (:app-title . "Hiisi")
 (:app-tagline . "Lär dig språk genom översättningar")

 ;; Landing page
 (:landing-hero-title . "Bemästra vilket språk som helst")
 (:landing-hero-subtitle . "Översätt vad som helst. Generera automatiskt flashcards som lär dig varför det fungerar så.")
 (:landing-cta . "Börja lära dig")
 (:landing-learn-more . "Läs mer")
 (:landing-how-it-works . "Så fungerar det")
 (:landing-feature-1-title . "Automatiska flashcards")
 (:landing-feature-1-desc . "Varje översättning genererar automatiskt flashcards med grammatikförklaringar. Inget manuellt kortskapande.")
 (:landing-feature-2-title . "Spaced repetition")
 (:landing-feature-2-desc . "SM-2-algoritmen schemalägger repetitioner vid optimala intervall. Lär dig effektivt, kom ihåg permanent.")
 (:landing-feature-3-title . "Grammatikundervisning")
 (:landing-feature-3-desc . "Varje översättning förklarar grammatik, ordstammar och meningsstruktur. Förstå varför, inte bara vad.")
 (:landing-free-trial . "7 dagars gratis provperiod. Inget kreditkort krävs.")
 (:landing-start-trial . "Starta gratis provperiod")
 (:landing-best-value . "Bäst värde")
 (:landing-cta-title . "Redo att lära dig språk genom grammatik, inte utantillärning?")
 (:landing-cta-subtitle . "Varje översättning blir ett lärtillfälle. Varje flashcard lär dig varför.")
 (:landing-signup-free . "Registrera dig gratis")

 ;; Auth pages
 (:auth-register . "Registrera")
 (:auth-login . "Logga in")
 (:auth-logout . "Logga ut")
 (:auth-email . "E-post")
 (:auth-password . "Lösenord")
 (:auth-password-again . "Bekräfta lösenord")
 (:auth-display-name . "Visningsnamn")
 (:auth-register-title . "Registrera dig på Hiisi")
 (:auth-register-subtitle . "Skapa ett nytt konto")
 (:auth-login-title . "Logga in på Hiisi")
 (:auth-login-subtitle . "Ange dina uppgifter")
 (:auth-forgot-password . "Glömt lösenordet?")
 (:auth-no-account . "Har du inget konto?")
 (:auth-have-account . "Har du redan ett konto?")

 ;; Translation page
 (:translate-title . "Översätt")
 (:translate-input-label . "Text att översätta")
 (:translate-input-placeholder . "Skriv text att översätta...")
 (:translate-from . "Från:")
 (:translate-to . "Till:")
 (:translate-submit . "Översätt")
 (:translate-save . "Spara som flashcard")
 (:translate-saved . "Sparat!")
 (:translate-like . "Gilla")
 (:translate-dislike . "Ogilla")
 (:translate-char-limit . "tecken kvar")
 (:translate-auto-detect . "Valfritt (Identifiera automatiskt)")
 (:translate-empty-state . "Skriv text ovan och klicka Översätt för att se resultatet med grammatikförklaring")

 ;; Flashcard review
 (:review-title . "Repetera")
 (:review-session-title . "Repetitionssession")
 (:review-session-subtitle . "Öva på dina sparade flashcards")
 (:review-start . "Starta repetition")
 (:review-no-cards . "Inga kort att repetera")
 (:review-no-cards-desc . "Du har inga flashcards som behöver repeteras just nu.")
 (:review-no-cards-hint . "Översätt lite text och klicka \"Spara som flashcard\" för att bygga din kortlek!")
 (:review-start-translating . "Börja översätta")
 (:review-show-answer . "Visa svar")
 (:review-click-reveal . "Klicka för att visa svaret")
 (:review-grammar-breakdown . "Grammatikförklaring")
 (:review-how-well . "Hur väl kom du ihåg?")
 (:review-again . "Igen")
 (:review-hard . "Svårt")
 (:review-good . "Bra")
 (:review-easy . "Lätt")
 (:review-progress . "Kort ~a av ~a")
 (:review-complete . "Session klar!")
 (:review-complete-msg . "Du repeterade ~a kort")
 (:review-correct . "Rätt")
 (:review-accuracy . "Träffsäkerhet")
 (:review-again-btn . "Repetera igen")
 (:review-translate-more . "Översätt mer")
 (:review-streak . "dagar i rad")

 ;; Dashboard
 (:dashboard-title . "Översikt")
 (:dashboard-cards-due . "Kort för idag")
 (:dashboard-total-cards . "Totalt antal kort")
 (:dashboard-subscription . "Prenumeration")
 (:dashboard-subscribed-until . "Prenumererar till")
 (:dashboard-not-subscribed . "Ingen prenumeration")
 (:dashboard-recent . "Senaste översättningar")
 (:dashboard-no-translations . "Inga översättningar än")
 (:dashboard-streak . "Nuvarande svit")
 (:dashboard-days . "dagar")
 (:dashboard-quick-actions . "Snabbåtgärder")
 (:dashboard-getting-started . "Kom igång")
 (:dashboard-tip-1 . "Översätt text du vill lära dig")
 (:dashboard-tip-2 . "Klicka \"Spara som flashcard\" på översättningar du vill komma ihåg")
 (:dashboard-tip-3 . "Repetera dina flashcards regelbundet - spaced repetition hjälper dig minnas långsiktigt")
 (:dashboard-tip-4 . "Bedöm ärligt - det hjälper algoritmen schemalägga dina repetitioner optimalt")

 ;; Subscription
 (:subscribe-title . "Enkla priser")
 (:subscribe-monthly . "Månadsvis")
 (:subscribe-annual . "Årsvis")
 (:subscribe-monthly-price . "€10/månad")
 (:subscribe-annual-price . "€100/år")
 (:subscribe-monthly-desc . "600 översättningar per månad")
 (:subscribe-annual-desc . "Spara €20 — två månader gratis!")
 (:subscribe-cta . "Prenumerera")
 (:subscribe-success . "Prenumeration lyckades!")
 (:subscribe-manage . "Hantera prenumeration")

 ;; Errors and status
 (:error-generic . "Något gick fel")
 (:error-not-found . "Sidan hittades inte")
 (:error-unauthorized . "Logga in för att fortsätta")
 (:error-subscription-required . "Prenumeration krävs")
 (:error-text-too-long . "Texten är för lång. Maximal översättningslängd är 120 tecken.")
 (:error-input-too-long . "Inmatningen är för lång")
 (:error-unknown-source-lang . "Källspråket du valde stöds inte.")
 (:error-unknown-target-lang . "Målspråket du valde stöds inte.")
 (:error-unknown-language . "Okänt språk")
 (:error-translation-unavailable . "Översättningstjänsten är tillfälligt otillgänglig. Försök igen om en stund.")
 (:error-translation-failed . "Översättningen misslyckades")
 (:error-translation-retry . "Kunde inte generera en översättning efter flera försök. Försök omformulera din text.")
 (:loading . "Laddar...")
 (:empty-state . "Inget här än")

 ;; Footer
 (:footer-privacy . "Integritetspolicy")
 (:footer-terms . "Användarvillkor")
 (:footer-contact . "Kontakt")
)
